### ISSUE TITLE
Provide a way to do shallow clones of jruby.git and ruby.git

### ISSUE THREAD

**Issue by michaelklishin** [rvm/rvm#1293]
For travis-ci.org (this probably will never matter for any other environment), we need to have a way to do shallow clones of jruby.git and ruby.git. Otherwise provisioning on peak consumes more disk space than our ~ partition has. An env variable would be sufficient for us. I think the default should be about 200.

**Comment by bval** [comment]
As I sit here rvm installing the 1.8.7 HEAD (only place to grab security patches now) I wonder if a shallow clone of the branch being requested shouldn't be the default. The ruby git repo is extremely large. Doing a deep clone just to install one version is extremely expensive, both locally and for GitHub. Thoughts?
