### ISSUE TITLE
object allocation during garbage collection phase

### ISSUE THREAD

**Issue by mheimschild** [rvm/rvm#1342]
Error occurs randomly on sidekiq startup or sometimes in redis driver:

environment: Ubuntu 12.04 64bit, ruby 1.9.3p327 (2012-11-10 revision 37606) [x86_64-linux]

not reproducible with non-rvm ruby 1.9.3

shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:45: [BUG] object allocation during garbage collection phase

-- Control frame information -----------------------------------------------
c:0018 p:---- s:0062 b:0062 l:000061 d:000061 CFUNC :new
c:0017 p:0034 s:0059 b:0059 l:000058 d:000058 METHOD shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:45
c:0016 p:0030 s:0054 b:0054 l:000047 d:000053 BLOCK shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:20
c:0015 p:0019 s:0051 b:0051 l:000050 d:000050 METHOD internal:prelude:10
c:0014 p:0013 s:0048 b:0048 l:000047 d:000047 METHOD shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:17
c:0013 p:0053 s:0044 b:0044 l:000358 d:000358 METHOD shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/thread_handle.rb:15
c:0012 p:---- s:0041 b:0041 l:000040 d:000040 FINISH
c:0011 p:---- s:0039 b:0039 l:000038 d:000038 CFUNC :new
c:0010 p:0216 s:0036 b:0036 l:000838 d:000838 METHOD shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/actor.rb:179
c:0009 p:---- s:0031 b:0031 l:000030 d:000030 FINISH
c:0008 p:---- s:0029 b:0029 l:000028 d:000028 CFUNC :new
c:0007 p:0031 s:0024 b:0024 l:000023 d:000023 METHOD shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid.rb:100
c:0006 p:0104 s:0018 b:0018 l:002650 d:002650 METHOD shared/bundle/ruby/1.9.1/gems/sidekiq-2.5.3/lib/sidekiq/manager.rb:28
c:0005 p:0038 s:0014 b:0014 l:000013 d:000013 METHOD shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/calls.rb:57
c:0004 p:0014 s:0007 b:0007 l:000690 d:000006 BLOCK shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/actor.rb:323
c:0003 p:0108 s:0005 b:0005 l:000880 d:000004 BLOCK shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/tasks/task_fiber.rb:22
c:0002 p:---- s:0003 b:0003 l:000002 d:000002 FINISH
c:0001 p:---- s:0001 b:-001 l:000000 d:000000 ------

-- Ruby level backtrace information ----------------------------------------
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/tasks/task_fiber.rb:22:in block in initialize'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/actor.rb:323:inblock in handle_message'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/calls.rb:57:in dispatch'
shared/bundle/ruby/1.9.1/gems/sidekiq-2.5.3/lib/sidekiq/manager.rb:28:ininitialize'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid.rbin new'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid.rb:100:innew'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/actor.rb:179:in initialize'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/actor.rb:179:innew'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/thread_handle.rb:15:in initialize'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:17:inget'
internal:prelude:10:in synchronize'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:20:inblock in get'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:45:in create'
shared/bundle/ruby/1.9.1/gems/celluloid-0.12.3/lib/celluloid/internal_pool.rb:45:innew'

**Comment by wuboy0307** [comment]
I get this bug on latest ruby 2.2.2p95
It happened randomly in different scenarios(start web server, rake precompile, rake migrate and so on...).
And it doesn't happen every time ( So maybe this time I start web server successfully, next time I see this error).

Is this still an RVM relative issue? Or I should submit issue to ruby team?
```
ruby -rrbconfig -e 'puts RbConfig::CONFIG["CFLAGS"]'
 -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration -Wdeprecated-declarations -Wno-packed-bitfield-compat  -fPIC
```

below is the log (it's a really long log so I just take the first few lines)
```
App 25311 stderr: Instance method "open" is already defined in Object, use generic helper instead or set StateMachines::Machine.ignore_method_conflicts = true.
App 25311 stderr:
App 25311 stderr: /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:
App 25311 stderr: [BUG]
App 25311 stderr: object allocation during garbage collection phase
App 25311 stderr:
App 25311 stderr: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
App 25311 stderr:
App 25311 stderr: -- Control frame information -----------------------------------------------
App 25311 stderr: c:0098
App 25311 stderr: p:----
App 25311 stderr: s:0439
App 25311 stderr: e:000438
App 25311 stderr: CFUNC
App 25311 stderr:  :require
App 25311 stderr:
App 25311 stderr: c:0097
App 25311 stderr: p:0013
App 25311 stderr: s:0435
App 25311 stderr: e:000434
App 25311 stderr: METHOD
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/polyglot-0.3.5/lib/polyglot.rb:65
App 25311 stderr:
App 25311 stderr: c:0096
App 25311 stderr: p:0010
App 25311 stderr: s:0428
App 25311 stderr: e:000427
App 25311 stderr: BLOCK
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274
App 25311 stderr:
App 25311 stderr: c:0095
App 25311 stderr: p:0054
App 25311 stderr: s:0426
App 25311 stderr: e:000425
App 25311 stderr: METHOD
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240
App 25311 stderr:
App 25311 stderr: c:0094
App 25311 stderr: p:0015
App 25311 stderr: s:0421
App 25311 stderr: e:000420
App 25311 stderr: METHOD
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274
App 25311 stderr:
App 25311 stderr: c:0093
App 25311 stderr: p:0191
App 25311 stderr: s:0416
App 25311 stderr: e:000415
App 25311 stderr: METHOD
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:360
App 25311 stderr:
App 25311 stderr: c:0092
App 25311 stderr: p:0159
App 25311 stderr: s:0408
App 25311 stderr: e:000407
App 25311 stderr: METHOD
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:494
App 25311 stderr:
App 25311 stderr: c:0091
App 25311 stderr: p:0034
App 25311 stderr: s:0395
App 25311 stderr: e:000394
App 25311 stderr: METHOD
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:184
App 25311 stderr:  [FINISH]
App 25311 stderr:
App 25311 stderr: c:0090
App 25311 stderr: p:0023
App 25311 stderr: s:0390
App 25311 stderr: e:000387
App 25311 stderr: BLOCK
App 25311 stderr:  /home/makeanegg/web/hiway_backend/shared/bundle/ruby/2.2.0/bundler/gems/spree-8147dcaac7c6/core/app/models/spree/payment/proces
App 25311 stderr:  [FINISH]

**Comment by mpapis** [comment]
this is different error, please open a bug for MRI

**Comment by noff** [comment]
Have this problem using 2.2.2p95:
Trace: https://gist.github.com/noff/3e5b86be602ec072f10e
Happens on rake, rails runner, etc.

**Comment by skaes** [comment]
I believe this has been fixed on the 2.2 branch.

Try 2.2.2 with the my patches (they include most of the patches on the 2.2 branch already).

rvm install 2.2.2 --patch railsexpress

**Comment by noff** [comment]
```
$ rvm install 2.2.2 --patch railsexpress
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /home/rails/.rvm/rubies/ruby-2.2.2, this may take a while depending on your cpu(s)...
ruby-2.2.2 - #downloading ruby-2.2.2, this may take a while depending on your connection...
ruby-2.2.2 - #extracting ruby-2.2.2 to /home/rails/.rvm/src/ruby-2.2.2....
Patch 'railsexpress' not found.
There has been an error applying the specified patches. Halting the installation.

```

**Comment by skaes** [comment]
rvm get master ?

**Comment by noff** [comment]
Done rvm get master. Then trying to install with patch. Results:

```
$ rvm install 2.2.2 --patch railsexpress
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /home/rails/.rvm/rubies/ruby-2.2.2, this may take a while depending on your cpu(s)...
ruby-2.2.2 - #downloading ruby-2.2.2, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.6M  100 12.6M    0     0  5976k      0  0:00:02  0:00:02 --:--:-- 9525k
ruby-2.2.2 - #extracting ruby-2.2.2 to /home/rails/.rvm/src/ruby-2.2.2....
Fetching patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/01-zero-broken-tests.patch
ruby-2.2.2 - #applying patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/01-zero-broken-tests.patch.
Fetching patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/02-improve-gc-stats.patch
ruby-2.2.2 - #applying patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/02-improve-gc-stats.patch.
Fetching patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/03-display-more-detailed-stack-trace.patch
ruby-2.2.2 - #applying patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/03-display-more-detailed-stack-trace.patch.
Fetching patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/04-backported-bugfixes-222.patch
ruby-2.2.2 - #applying patch https://raw.githubusercontent.com/skaes/rvm-patchsets/master/patches/ruby/2.2.2/railsexpress/04-backported-bugfixes-222.patch.....|
ruby-2.2.2 - #applying patch /home/rails/.rvm/patches/ruby/2.2.2/fix_installing_bundled_gems.patch.
ruby-2.2.2 - #autoreconf.
ruby-2.2.2 - #configuring......................................................|
ruby-2.2.2 - #post-configuration..
ruby-2.2.2 - #compiling......
Error running '__rvm_make -j4',
showing last 15 lines of /home/rails/.rvm/log/1437040684_ruby-2.2.2/make.log
compiling gc.c
compiling hash.c
compiling inits.c
compiling io.c
compiling marshal.c
compiling math.c
compiling node.c
compiling numeric.c
compiling object.c
compiling pack.c
generating parse.c
executable host ruby is required. use --with-baseruby option.
make: *** [parse.c] Error 1
make: *** Waiting for unfinished jobs....
++ return 2
There has been an error while running make. Halting the installation.
```

What in can mean?
