### ISSUE TITLE
RVM 1.17.2 implode - /etc/rvmrc

### ISSUE THREAD

**Issue by theduke** [rvm/rvm#1380]
The current stable version (1.17.2) does not remove /etc/rvmrc, which causes problems in some situations.

For example, i wanted to remove the multi-user setup and do a single user installation.
This failed due to permission errors, because rvm still tried to place the files in /usr/local/rvm, even when running as a normal user.

rvm implode should either delte /etc/rvmrc or provide a clear warning that this needs to be deleted for single installs to work.

**Comment by adaam2** [comment]
@mpapis  Quick question - why does implode not delete the rvmrc file? I just spent ages figuring out why rvm wasn't installing to the default directory in a borked rvm installation on a GCP compute instance. Can we change the behaviour to delete this file by default? What are the reasons for keeping it?

**Comment by mpapis** [comment]
@adaam2 because those are configuration files created by user, you might have there settings that you prefer, we can not cleanup everything, what if `rvm_path` was in `.shrc` and it was sourced in `.bashrc` should RVM detect that too? ;)
