### ISSUE TITLE
Using RVM with Lubuntu 12.10 and lxterminal 0.1.11

### ISSUE THREAD

**Issue by timolehto** [rvm/rvm#1421]
Hi

It seems login shell functionality in lxterminal is broken or I'm just missing some crucial bit of information. Anybody gotten this to work? According to this older [ticket](https://github.com/wayneeseguin/rvm/issues/864) someone has gotten RVM to work nicely with lxterminal, but I can't get it to work. If so could you please tell me what version of lxterminal are you using and did you have to do other tweaking? Here's a [thread](http://forum.lxde.org/viewtopic.php?t=31978&f=26) of mine on another forum with more information (but no answers). But in short, when starting lxterminal normally rvm complains that the shell is not a login shell. Starting it with `lxterminal -l` will result in no rvm command found at all. Perhaps this [image](http://dl.dropbox.com/u/15451596/caputre.png) will demonstrate the bad, not good and expected behaviour. In it:
1. lxterminal -l
2. lxterminal
3. lxterm -ls

**Comment by OlehZiniak** [comment]
I can't seem to find "x-terminal-emulator" in my ~/.config/openbox/lubuntu-rc.xml. Could anyone help me?

**Comment by raelgc** [comment]
@OlehZiniak Can you, please, check if you terminal is running as a login shell running the following command on it?

    shopt login_shell

**Comment by OlehZiniak** [comment]
@raelgc 
> login_shell    	off

**Comment by raelgc** [comment]
@OlehZiniak (nice avatar, by the way), reading the [Ubuntu Manpage for lxterminal](http://manpages.ubuntu.com/manpages/xenial/man1/lxterminal.1.html), I can see there is an option to run lxterminal as a login shell:

>  --loginshell
>           Executes login shell.

**Comment by OlehZiniak** [comment]
@raelgc thanks, lol. Yeah, I've used this workaround yesterday to solve my problems with the rvm. If I remember correctly it was a hint from rvm in the console when I got "rvm is not a function" or something like that.

**Comment by raelgc** [comment]
Can you edit the menu launcher to include this option?

**Comment by qwexer** [comment]
The -e "bash -il" would not work for my Lubuntu v17.10 lxterminal but the addition of --loginshell worked perfectly. Thanks @raelgc!
