### ISSUE TITLE
After rvm upgrade fails with: ruby: error while loading shared libraries: libruby.so.1.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by igalic** [rvm/rvm#1528]
After a supposedly successful `rvm get stable`, `rvm update 1.9.3`, `gem update` fails: https://gist.github.com/igalic/4757569

env | sort: https://gist.github.com/igalic/4757561

`ldd /usr/local/rvm/rubies/ruby-1.9.3-p327/bin/ruby` shows

```
    linux-vdso.so.1 =>  (0x00007fff2e8ea000)
libruby.so.1.9 => not found
libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff81d8a1000)
/lib64/ld-linux-x86-64.so.2 (0x00007ff81dc6b000)
```

from IRC:

@mpapis jMCg, gist: find /usr/local/rvm/rubies/ruby-1.9.3-p327 -name 'libruby.so*'
@mpapis jMCg, ah, wait
< jMCg> mpapis: it's right there in lib - and it works when I LD_LIBRARY_PATH it
@mpapis jMCg, that's odd, it mixes /usr/local/rvm/rubies/ruby-1.9.3-p385 with /usr/local/rvm/rubies/ruby-1.9.3-p327

**Comment by lmhsjackson** [comment]
This last comment, saved my morning. Thanks
