### ISSUE TITLE
Expired SSL for https://rvm.io

### ISSUE THREAD

**Issue by smaboshe** [rvm/rvm#1684]
Hello!

I'm getting errors today trying to update RVM:

```
$ rvm get head
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle" of Certificate Authority (CA) public keys (CA certs). If the default bundle file isn't adequate, you can specify an alternate file using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in the bundle, the certificate verification probably failed due to a problem with the certificate (it might be expired, or the name might not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use the -k (or --insecure) option.
RVM reloaded!
```

I get the same with `rvm get stable`.

On visiting https://rvm.io in Chrome, I get an SSL Error page with:

```
The site's security certificate has expired!
You attempted to reach rvm.io, but the server presented an expired certificate. No information is available to indicate whether that certificate has been compromised since its expiration. This means Google Chrome cannot guarantee that you are communicating with rvm.io and not an attacker. Your computer's clock is currently set to Friday, March 15, 2013 10:16:13 AM. Does that look right? If not, you should correct the error and refresh this page.
You should not proceed, especially if you have never seen this warning before for this site.
```

Is this accurate? Earlier, I was getting warnings from cURL about this potentially being a man in the middle attack so I'd really like to make sure.

**Comment by 1z2x3c4v5b6n7m8** [comment]
> Hello!
> 
> I'm getting errors today trying to update RVM:
> 
> ```
> $ rvm get head
> % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> Dload  Upload   Total   Spent    Left  Speed
> 0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
> error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
> More details here: http://curl.haxx.se/docs/sslcerts.html
> 
> curl performs SSL certificate verification by default, using a "bundle" of Certificate Authority (CA) public keys (CA certs). If the default bundle file isn't adequate, you can specify an alternate file using the --cacert option.
> If this HTTPS server uses a certificate signed by a CA represented in the bundle, the certificate verification probably failed due to a problem with the certificate (it might be expired, or the name might not match the domain name in the URL).
> If you'd like to turn off curl's verification of the certificate, use the -k (or --insecure) option.
> RVM reloaded!
> ```
> 
> I get the same with `rvm get stable`.
> 
> On visiting https://rvm.io in Chrome, I get an SSL Error page with:
> 
> ```
> The site's security certificate has expired!
> You attempted to reach rvm.io, but the server presented an expired certificate. No information is available to indicate whether that certificate has been compromised since its expiration. This means - - # [ ] Google Chrome ca~~@[]()_****_~~nnot guarantee that you are communicating with rvm.io and not an attacker. Your computer's clock is currently set to Friday, March 15, 2013 10:16:13 AM. Does that look right? If not, you should correct the error and refresh this page.
> You should not proceed, especially if you have never seen this warning before for this site.
> ```
> 
> Is this accurate? Earlier, I was getting warnings from cURL about this potentially being a man in the middle attack so I'd really like to make sure.
> 

- [ ] @

**Comment by 1z2x3c4v5b6n7m8** [comment]
@kostikbart05@gmail.com
