### ISSUE TITLE
(stucked in) ERROR: Gem bundler is not installed, run `gem install bundler` first.

### ISSUE THREAD

**Issue by noAlvaro** [rvm/rvm#1860]
Even though I've installed bundler already (`gem install bundler`), running `bundle` will throw the same error message again:

```
ERROR: Gem bundler is not installed, run `gem install bundler` first.
```

The issue started happening after I changed the `.rvmrc` file to a slightly different version of Ruby (`1.9.2-p320` to `1.9.2-p290`)... although another bundler installation is still working in other Ruby version (`1.9.3-p327`), for another project.

What could be causing this?

**Comment by leocurilan** [comment]
rvm get head
rvm reload
rvm reset
rvm use .
gem install bundler
which bundle

**Comment by leocurilan** [comment]
It works for me in resolving the issue thanks for the help. 

rvm get head
rvm reload
rvm reset
rvm use .
gem install bundler
which bundle

**Comment by leocurilan** [comment]
It worked for me in resolving the issue thanks for the help.

rvm get head
rvm reload
rvm reset
rvm use .
gem install bundler
which bundle

**Comment by alvarotrigo** [comment]
> rvm use .

Trying to run that I got:

> Unknown ruby interpreter version (do not know how to handle): RUBY_VERSION. Could not determine which Ruby to use; . should contain .rvmrc or .versions.conf or .ruby-version or .rbfu-version or .rbenv-version, or an appropriate line in Gemfile.

Which I guess refers to the variable RUBY_VERSION in the Gemfile:

> source "https://rubygems.org" 
ruby RUBY_VERSION

What should I do? I guess RUBY_VERSION variable has to be defined as a system variable ?
I'm just trying to use Jekyll.

**Comment by snpd25** [comment]
@mpapis I am stuck here, I ran `rvm use 2.5.0` 
`ruby -v`
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
`bundler -v`
Bundler version 2.0.1
`which bundle`
/home/snpd/.rvm/rubies/ruby-2.5.0/bin/bundle
 `echo $PATH`
/home/snpd/.rvm/gems/ruby-2.5.0/bin:/home/snpd/.rvm/gems/ruby-2.5.0@global/bin:/home/snpd/.rvm/rubies/ruby-2.5.0/bin:/home/snpd/.rvm/bin:/home/snpd/.local/bin:/home/snpd/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/bin
but `bundle exec` gives this error:
Traceback (most recent call last):
	2: from /usr/bin/bundle:23:in `<main>'
	1: from /usr/lib64/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/usr/lib64/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
Please Help!
