### ISSUE TITLE
using ruby version from gemfile and gemset from .ruby-gemset 

### ISSUE THREAD

**Issue by kamelury** [rvm/rvm#1879]
I just started using rvm 1.19.6 (stable) in a rails. 
I converted my .rvmrc to .ruby-version and ruby-gemset.
I discovered that without .ruby-version file, rvm will use gemfile to select ruby version:
RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
And I think it is great! However, in that case it is ignoring .ruby-gemset.
Am I doing something wrong, is that intentional or a potentially good candidate for a new feature?

**Comment by willywg** [comment]
@mpapis on Gemfile is:

ruby '1.9.3'

not

ruby='1.9.3'

**Comment by mpapis** [comment]
@willywg sorry mised the hash up front, there are two notations:

1. the bad one from `bundler`:

    ```ruby
    ruby "2.3.1"
    ```
    
    it is bad because it's not `bundler` place to select ruby version, it's already to late for that as ruby has been already loaded.

2. the harmless one from `rvm`:

    ```ruby
    ruby "2.3.1"
    ```
    
    it is just a directive for version switchers which `ruby` to pick, will not cause loading wrong `ruby` and failing from it.

**Comment by willywg** [comment]
@mpapis  thank you! 👍
