### ISSUE TITLE
Arch GNU/Linux, "configure: error: no acceptable C compiler found in $PATH" (and others)

### ISSUE THREAD

**Issue by panth0r** [rvm/rvm#1891]
[Actually, took a look at the code; both "make" and "gcc" are in rvm's "/scripts/functions/requirements/" "requirements_arch_define" function, so don't really know what's happened here.  Based on this revelation, some context: after installing RVM and before installing any Rubies via RVM, I changed to an existing project's directory and ran "rvm --rvmrc --create ruby-2.0.0-p0@project", this command printed something along the lines of "ruby-2.0.0-p0 not installed, please run 'rvm install ruby-2.0.0-p0'"; an rvmrc file for the project was not created (which seems like good behavior).  So I took its advice and ended up here.]

To wit, ruby-2.0.0-p0 (perhaps other Rubies, as well) an "acceptable C compiler":

> configure: error: in `/home/panth0r/.rvm/src/ruby-2.0.0-p0':
> configure: error: no acceptable C compiler found in $PATH"

 as well as "GNU Make":

> "checking if make is GNU make... ./configure: line 18790: make: command not found
> no
> checking for safe null command for make... configure: error: no candidate for safe null command"

The "solution" is straightforward: just "$ sudo pacman -Syu make gcc" (maybe others, depending on what the logs say).  I'm guessing RVM presupposes the "base-devel" group is installed and feel as though you should drop this assumption and consider at least one of the following:
1. include appropriate logic in "autolibs"
   - on the Arch side of things, pulling the entire "base-devel" group would be overkill, but...
     - a good chunk of people would probably just go with it and
     - others could easily install the individual packages manually (well, "easily" if they're documented)
2. include this information in the "requirements" or "notes"
   - this is probably overkill, as installing other Rubies may not require these extras
3. include information about this on RVM's Arch "Interpreter" page (https://rvm.io/os/archlinux/)

**Comment by banrieen** [comment]
Thank you @mpapis mpapis !
Run： pacman -T make gcc && echo found || echo missing
[root@archlinux siege-4.0.2]# pacman -T make gcc && echo found || echo missing
make
gcc
missing
Then， I install the **make**，**gcc** 
After that , I re-install siege success.
