### ISSUE TITLE
parse error near `\n'

### ISSUE THREAD

**Issue by hut8** [rvm/rvm#1993]
Every time I do anything related to RVM (open a new console, rvm list, etc), I get:
    /home/lbowen/.rvm/scripts/functions/rvmrc:1: parse error near `\n'

I'm using a fresh install of zsh which I compiled myself.  I have been using it for quite a while with no problems.

On Ubuntu 12.04/12.10 with their zsh package, this works with no issue.

Versions:

```
$ zsh --version
zsh 5.0.2 (x86_64-unknown-linux-gnu)

$ rvm --version
/home/lbowen/.rvm/scripts/functions/rvmrc:1: parse error near `\n'

rvm 1.21.3 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

Seems related to [1320](https://github.com/wayneeseguin/rvm/issues/1320)

**Comment by solarmicrobe** [comment]
I just had the same error and I wanted to let anyone coming from google (as I did) what my problem was.  Hopefully it'll help you.

````shell
$which zsh
/opt/custom/bin/zsh

$zsh --version
zsh 5.0.7 (x86_64-unknown-linux-gnu)

$echo $SHELL
/bin/zsh

$/bin/zsh --version
zsh 4.3.6 (x86_64-suse-linux-gnu)
````

As you can see above even though some checks were reporting zsh 5.0.7 my actual shell was not set to that.  Setting it to the right one fixed my problem.

````shell
$chsh -s $(which zsh)
Changing login shell for rparks.
Password:
Shell changed.

# Restarted session

$echo $SHELL
/opt/custom/bin/zsh
````
