### ISSUE TITLE
No binary rubies available for: ubuntu/12.04/x86_64/ruby-1.9.3-p448

### ISSUE THREAD

**Issue by jujugrrr** [rvm/rvm#2008]
Hello, 
The binary is missing for:
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.2 LTS
Release:    12.04
Codename:   precise

Which is the ubuntu LTS.

Could you add it?

Cheers

**Comment by parthisivaraj** [comment]
when I tried to install ruby using rvm , i got the following issue . 
parthiban@parth:~$ rvm install ruby-2.1.1
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/14.04/i386/ruby-2.1.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx_port.
Can not find compiler and 'make' tool - make sure Xcode and/or Command Line Tools are installed.
Requirements installation failed with status: 11.
  
Could you help in this ?
