### ISSUE TITLE
Error: rvm CLI may not be called from within /etc/rvmrc

### ISSUE THREAD

**Issue by PeterWooster** [rvm/rvm#2180]
I recently installed RVM as a multiuser install on Fedora 17 Linux.  I've filed [a StackOverflow question](http://stackoverflow.com/questions/18552297/error-rvm-cli-may-not-be-called-from-within-etc-rvmrc) and searched Google for answers to this to no avail.

The error message is:

```
Error:
  /etc/rvmrc is for rvm settings only.
  rvm CLI may NOT be called from within /etc/rvmrc.
  Skipping the loading of /etc/rvmrc
```

The error occurs when a user logs on and appears to be coming from line 45 of the rvm script.  My /etc/rvmrc is simply:

```
umask u=rwx,g=rwx,o=rx
```

There is also an error when a user logs out:

```
bash: return: can only `return' from a function or sourced script
```

 I don't know if they are related.

BTW: I did the install using the instructions on rvm.io

**Comment by vishaltps** [comment]
I am having same issue . Everything working fine since this morning . But now suddenly i am getting this error in my all projects. 

> home/tps/.rvmrc: line 1: rvm: command not found
> 
> Error:
>         /home/tps/.rvmrc is for rvm settings only.
>         rvm CLI may NOT be called from within /home/tps/.rvmrc.
> 

Even when i install rvm again it is giving me same error.

**Comment by mpapis** [comment]
@vishaltps please open a new issue with all details
