### ISSUE TITLE
Can do a multi user install using sudo on centos

### ISSUE THREAD

**Issue by kernow** [rvm/rvm#2242]
When running as a non-root user I get the output from the command:

\curl -L https://get.rvm.io | sudo bash -s stable

Creating group 'rvm'
/usr/local/rvm/src/rvm/scripts/functions/group: line 74: groupadd: command not found

Upgrading the RVM installation in /usr/local/rvm/
chown: `:rvm': invalid group
    could not set group of '/usr/local/rvm/share/man/man1/rvm.1.gz', prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
chown:`:rvm': invalid group
    could not set group of '/usr/local/rvm/share/man/man1/rvm.1', prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
chown: `:rvm': invalid group
    could not set group of '/etc/rvmrc', prefix the command with 'rvmsudo' to fix it, if the situation persist report a bug.
chown:`root:rvm': invalid group
find: invalid argument `rvm' to`-group'
Upgrade of RVM in /usr/local/rvm/ is complete.

system info is:

system:

  system:
    uname:       "Linux system.net 2.6.18-128.7.1.el5PAE #1 SMP Mon Aug 24 08:41:30 EDT 2009 i686 i686 i386 GNU/Linux"
    system:      "centos/5/i386"
    bash:        "/bin/bash => GNU bash, version 3.2.25(1)-release (i386-redhat-linux-gnu)"
    zsh:         " => not installed"

**Comment by bridiver** [comment]
am I missing something here? I just installed the latest rvm, this change is not in there and I'm getting the same error.
