### ISSUE TITLE
Issue with installing ruby 1.8.7 on OS 10.9

### ISSUE THREAD

**Issue by ttback** [rvm/rvm#2318]
I am unable to install the ruby 1.8.7 on the new Mac OS, please let me know how to resolve this problem. Thanks.

$ rvm install 1.8.7
Searching for binary rubies, this might take some time.
Found remote file 
No binary rubies available for: osx/10.9/x86_64/ruby-1.8.7-p374.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Installing requirements for osx.
Updating system.....
Error running 'requirements_osx_brew_update_system ruby-1.8.7-p374',
please read /Users/admin/.rvm/log/1382654150_ruby-1.8.7-p374/update_system.log
Requirements installation failed with status: 1.

**Comment by gheron** [comment]
I had success running 
`brew upgrade`
