### ISSUE TITLE
Please prefer private bin directory in PATH

### ISSUE THREAD

**Issue by michas2** [rvm/rvm#2323]
If someone has a ~/bin directory the first place of PATH, the intention usually is to prefer the contained commands before everything else. - If I put some script there and call it via PATH searching, I expect exactly this script to be called.

Now rvm always puts all rvm stuff in the very front of PATH breaking the above behaviour.

It would be great if rvm would add ~/bin before the rvm stuff, in case it has already been there before.

**Comment by adisos** [comment]
After several hours of researching find out that warning "Warning! PATH is not properly set up..." was connected with this hook.
