### ISSUE TITLE
Error running '__rvm_make -j 1' when running 'rvm install 2.0.0'

### ISSUE THREAD

**Issue by FluffyCode** [rvm/rvm#2333]
rvm version: 1.23.13

While trying to install Ruby 2.0.0 on Mac OSX 10.6.8, I ran into the following:

> Error running '__rvm_make -j 1',
> please read /Users/ey/.rvm/log/1383347832_ruby-1.9.3-p448/make.log
> There has been an error while running make. Halting the installation.

The make.log file contents:
https://gist.github.com/FluffyCode/a55a8264f8a69965f9e0

And the results of running 'rvm install 2.0.0 --debug':
https://gist.github.com/FluffyCode/7e9047761234f4555b7f

Prior to attempting to install 2.0.0, I also ran into the same error message (Error running '__rvm_make -j 1') when trying to install Ruby 1.9.3.

**Comment by yinhuanyi** [comment]
oh!!!

**Comment by SanjayYadav90** [comment]
I was trying to install ruby 1.9.3 but have error as-
Error running '__rvm_make -j4'
I follow @mpapis and got my issue resolved

**rvm remove 1.9.3
CC=clang rvm install 1.9.3**   

Now I have this setup-

```
rvm rubies
   ruby-1.9.3-p551 [ x86_64 ]
   ruby-2.1.3 [ x86_64 ]
=* ruby-2.3.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

```

**Comment by yupengyang** [comment]
I got similar issue：
```
ruby-2.4.0 - #compiling - please wait
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/ypy/.rvm/log/1491065073_ruby-2.4.0/make.log
        ret = clock_gettime(c, &ts);
              ^
process.c:7519:9: error: unknown type name 'clockid_t'; did you mean 'clock_id_t'?
        clockid_t c = NUM2CLOCKID(clk_id);
        ^~~~~~~~~
        clock_id_t
/usr/include/mach/clock_types.h:53:13: note: 'clock_id_t' declared here
typedef int     clock_id_t;                     /* clock identification type */
                ^
process.c:7520:19: warning: implicit declaration of function 'clock_getres' is invalid in C99 [-Wimplicit-function-declaration]
        int ret = clock_getres(c, &ts);
                  ^
2 warnings and 2 errors generated.
make: *** [process.o] Error 1
+__rvm_make:0> return 2
There has been an error while running make. Halting the installation.
```

**Comment by mpapis** [comment]
@yupengyang please open a new ticket, this issue has been closed for quite some time.

**Comment by JessRudder** [comment]
@mpapis just took over a very old app and needed ruby 1.9.3.  I spent all afternoon trying to get past the installation issues.  You're recommendation above was the solution I needed.  1000 thanks!!!! 🎉 🎆 💥 🏆

**Comment by dostapn** [comment]
```
$ brew install llvm
$ brew --prefix llvm
/usr/local/opt/llvm
$ echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.bash_profile
$ CC=/usr/local/opt/bin/clang rvm install 2.0
```
