### ISSUE TITLE
Bash 3.2.25 required when recenter version installed

### ISSUE THREAD

**Issue by cw6365** [rvm/rvm#2346]
Hi,

When trying to download RVM it keeps saying BASH 3.2.25 is required, i have 4.0. Surely it is 3.2.25 and above?

Chriss-MacBook-Pro:bash-4.0 chrisward$ curl -L https://get.rvm.io | bash -s stable --autolibs=enabled
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19632  100 19632    0     0  13517      0  0:00:01  0:00:01 --:--:-- 13517
Unknown option: n
Unknown option: 1
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

```
-u            Display method and URL before any response
-U            Display request headers (implies -u)
-s            Display response status code
-S            Display response status chain
-e            Display response headers
-d            Do not display content
-o <format>   Process HTML content in various ways

-v            Show program version
-h            Print this message

-x            Extra debugging output
```

BASH 3.2.25 required (you have 4.0.0(1)-release)
Chriss-MacBook-Pro:bash-4.0 chrisward$

**Comment by doncadavona** [comment]
I still get:

> BASH 3.2.25 required

using this command posted at [https://rvm.io](https://rvm.io):

`\curl -sSL https://get.rvm.io | bash -s stable`

**Comment by dan-munn** [comment]
I am also still trying to install RVM. 

I have bash version 1.9.5-preview20150319 already installed but am struggling to install any later versions of bash and need version BASH 3.2.25 to complete the RVM installation using this command

`\curl -sSL https://get.rvm.io | bash -s stable`

i found this: bash-4.4-beta2.tar.gz [here](https://ftp.gnu.org/gnu/bash/?C=M;O=A) but this has no clear way to install.

I must also mention that i'm relatively new to codeing and am just trying to install the RVM on windows 10

Any help welcome!

**Comment by mpapis** [comment]
@dan-munn if you are using anniversary edition with Ubuntu it should be as easy as `apt-get install bash`

**Comment by dan-munn** [comment]
@mpapis thank you, i discovered this after a bit of digging. Sorry for the late reply.

Turns out i did just need to update windows and the then it was very easy to download the latest version of Bash from there.

Though i am still struggling to download RVM.. i enter the command from the [rvm website](https://rvm.io/rvm/install) (using the development version) and nothing happens. Though it seems like something may be happening due to the bash command line becoming useless and commands entered doing nothing.

Here is a picture of what happens.

![rvm download issue](https://cloud.githubusercontent.com/assets/20098886/17662598/722b1bc8-62de-11e6-94c7-fbaf49ea3510.PNG)

As you can see, not a lot. And this will just stay like this for hours.

**Comment by fcoloni** [comment]
command -V head

**Comment by fcoloni** [comment]
which -a head

**Comment by fcoloni** [comment]
PATH="/usr/bin:$PATH" \curl -sSL https://get.rvm.io | bash
will fix

**Comment by Celfonica** [comment]
C:\Sites\celfonica>curl -sSL https://get.rvm.io | bash -s stable
BASH 3.2.25 required (you have 3.1.17(1)-release)

same here cant solve it on windows

**Comment by abinhho** [comment]
My problem is ~/.bash_profile, 
Because your head is wrong.
If you are using:
```
export PATH=some/other/path:${PATH}
```
Let's change to:
```
export PATH=${PATH}:some/other/path
```
Hope this help!

**Comment by priya-git-prog** [comment]
> C:\Sites\celfonica>curl -sSL https://get.rvm.io | bash -s stable
> BASH 3.2.25 required (you have 3.1.17(1)-release)
> 
> same here cant solve it on windows

**Comment by priya-git-prog** [comment]
> C:\Sites\celfonica>curl -sSL https://get.rvm.io | bash -s stable
> BASH 3.2.25 required (you have 3.1.17(1)-release)
> 
> same here cant solve it on windows

Even I was trying from Command Prompt with Ruby on Rails & getting same error. Please try from GIT Bash :
Priya@DESKTOP-706UDE1 MINGW64 /c/Sites (master)
$  gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

Then
Priya@DESKTOP-706UDE1 MINGW64 /c/Sites (master)
$ curl -sSL https://get.rvm.io | bash -s stable

Finally it asks you to run-
Priya@DESKTOP-706UDE1 MINGW64 /c/Sites (master)
$ source /c/Users/Priya/.rvm/scripts/rvm

Hope this helps :)
