### ISSUE TITLE
Error running 'requirements_debian_libs_install gawk libyaml-dev libsqlite3-dev autoconf libgdbm-dev libncurses5-dev automake libtool'

### ISSUE THREAD

**Issue by zeknox** [rvm/rvm#2358]
Having issues installing ruby on Kali linux.  I've installed RVM and I can validate that with rvm -v.  I've run 'rvm get head' to ensure I'm running latest version of RVM.

<pre>
# rvm install ruby
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_1/i386/ruby-2.0.0-p247.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system............
Installing required packages: gawk, libyaml-dev, libsqlite3-dev, autoconf, libgdbm-dev, libncurses5-dev, automake, libtool.....................................
Error running 'requirements_debian_libs_install gawk libyaml-dev libsqlite3-dev autoconf libgdbm-dev libncurses5-dev automake libtool',
please read /usr/local/rvm/log/1384443871_ruby-2.0.0-p247/package_install_gawk_libyaml-dev_libsqlite3-dev_autoconf_libgdbm-dev_libncurses5-dev_automake_libtool.log
Requirements installation failed with status: 100.
</pre>

I also have run 'rvm requirements' but it will fail as well not installing the required dependencies.

<pre>
# rvm requirements
Checking requirements for debian.
Installing requirements for debian.
Updating system............
Installing required packages: gawk, libyaml-dev, libsqlite3-dev, autoconf, libgdbm-dev, libncurses5-dev, automake, libtool.....................................
Error running 'requirements_debian_libs_install gawk libyaml-dev libsqlite3-dev autoconf libgdbm-dev libncurses5-dev automake libtool',
please read /usr/local/rvm/log/1384444234/package_install_gawk_libyaml-dev_libsqlite3-dev_autoconf_libgdbm-dev_libncurses5-dev_automake_libtool.log
Requirements installation failed with status: 100.
</pre>

**Comment by jslim89** [comment]
@zeknox I think you have miss out this

```
$ gpg --keyserver pgpkeys.mit.edu --recv-key  ED444FF07D8D0BF6
$ gpg -a --export ED444FF07D8D0BF6 | sudo apt-key add -
```

I'm using Debian 7, and it shows

```
W: GPG error: http://http.kali.org kali Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ED444FF07D8D0BF6
```

**Comment by Harshit2110** [comment]
having issues installing ruby. I have installed rvm


# rvm install ruby
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system.............
Error running 'requirements_debian_update_system ruby-2.3.0',
showing last 15 lines of /usr/local/rvm/log/1477661419_ruby-2.3.0/update_system.log
++ case "${TERM:-dumb}" in
++ case "$1" in
++ [[ -t 2 ]]
++ return 1
++ printf %b 'There has been error while updating '\''apt-get'\'', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list
\n'
There has been error while updating 'apt-get', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

++ return 100

**Comment by pkuczynski** [comment]
It looks like the `apt-get` is failing. Please run it outside of rvm and fix the errors. If your problem persist, please create new issue.

**Comment by pkuczynski** [comment]
You can install required dependenies yourself from a different account. There is no other way I am afraid.

**Comment by hemershon** [comment]
Hello, how are you?
I have difficulty installing rvm install 2.4.4 and others, I get this error, I'm using debian buster, anyone know any solution?

```
Error running 'requirements_debian_libs_install g++ autoconf automake bison libc6-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev sqlite3 zlib1g-dev libgmp-dev libreadline6-dev libssl-dev',
please read /home/devs/.rvm/log/1577376041_ruby-2.6.3/package_install_g++_autoconf_automake_bison_libc6-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_sqlite3_zlib1g-dev_libgmp-dev_libreadline6-dev_libssl-dev.log
Requirements installation failed with status: 100.
```

**Comment by DireStraits01** [comment]
> Hello, how are you?
> I have difficulty installing rvm install 2.4.4 and others, I get this error, I'm using debian buster, anyone know any solution?
> 
> ```
> Error running 'requirements_debian_libs_install g++ autoconf automake bison libc6-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev sqlite3 zlib1g-dev libgmp-dev libreadline6-dev libssl-dev',
> please read /home/devs/.rvm/log/1577376041_ruby-2.6.3/package_install_g++_autoconf_automake_bison_libc6-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_sqlite3_zlib1g-dev_libgmp-dev_libreadline6-dev_libssl-dev.log
> Requirements installation failed with status: 100.
> ```
Hello my friend, i have also problem. did you find the answer?

**Comment by hoangpn256** [comment]
> > Hello, how are you?
> > I have difficulty installing rvm install 2.4.4 and others, I get this error, I'm using debian buster, anyone know any solution?
> > ```
> > Error running 'requirements_debian_libs_install g++ autoconf automake bison libc6-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev sqlite3 zlib1g-dev libgmp-dev libreadline6-dev libssl-dev',
> > please read /home/devs/.rvm/log/1577376041_ruby-2.6.3/package_install_g++_autoconf_automake_bison_libc6-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_sqlite3_zlib1g-dev_libgmp-dev_libreadline6-dev_libssl-dev.log
> > Requirements installation failed with status: 100.
> > ```
> 
> Hello my friend, i have also problem. did you find the answer?

Hi @DireStraits01 , @hemershon 

If you read the error log. you will see 

```
The following packages have unmet dependencies:
 libncurses5-dev : Depends: libtinfo5 (= 6.1-1ubuntu1) but 6.1-1ubuntu1.18.04 is to be installed
                   Depends: libncurses5 (= 6.1-1ubuntu1) but 6.1-1ubuntu1.18.04 is to be installed
                   Depends: libtinfo-dev (= 6.1-1ubuntu1) but it is not going to be installed
 libreadline-dev : Depends: libtinfo-dev but it is not going to be installed
 pkg-config : Depends: dpkg-dev but it is not going to be installed

```

That mean your lib is install, so it break pile of command in rvm.
We just re-install right version of package.
Please check it out!

**Comment by egeste** [comment]
Bug closed with no obvious resolution? Cool story.

**Comment by avosa** [comment]
Here's how to solve the same:
```sh 
sudo apt update
sudo apt install gnupg2
gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg --keyserver pgpkeys.mit.edu --recv-key  ED444FF07D8D0BF6
gpg -a --export ED444FF07D8D0BF6 | sudo apt-key add -
cat rvm.sh | bash -s stable --rails # Install stable rails for example 
source ~/.rvm/scripts/rvm # When the installation is complete, source the RVM scripts from the directory they were installed
```

I hope that helps.

**Comment by BenzeneAlcohol** [comment]
I solved it by changing internet.
Maybe the proxy I was using earlier was blocking something - Ubuntu
