### ISSUE TITLE
RVM is no longer creating symlinks under /usr/local/rvm/bin

### ISSUE THREAD

**Issue by spierepf** [rvm/rvm#2456]
Greetings,

I wanted to post this under the Google Group, but that appears to be closed.

I am under the impression that rvm (when installed by root) used to create symbolic links under /usr/local/rvm/bin for ruby and gem.

For some reason, these links have disappeared, and this is causing a problem for some automated testing scripts that I am running.

Is there a CLI way for me to get these symlinks back?

Peter.

**Comment by Wardrop** [comment]
@mpapis This seems to have changed again. `rvm wrapper` no longer works like in your examples. Does RVM include any means to generate symlinks under `rvm_path/bin`?

**Comment by mpapis** [comment]
@Wardrop the wrappers functionality was completely rewritten to be integrated with rubygems, this brings convenience for users, but makes the flow a bit different, you can find more about it here https://github.com/rvm/gem-wrappers

I think the linking functionality could be restored with a gem similar to `gem-wrappers` - but as it's rarely used functionality I did not prioritize it, let me know if you have interest in helping out and creating the `gem-rvm-symlink` gem - I can walk you through the required steps.
