### ISSUE TITLE
Error running 'requirements_centos_libs_install libyaml-devel',

### ISSUE THREAD

**Issue by pradhans0906** [rvm/rvm#2471]
Hello ,Am trying to install ruby on centos 6.4 but am getting below error .

rvm requirements
Checking requirements for redhat.
Installing requirements for redhat.
Updating system.
Installing required packages: libyaml-devel.
Error running 'requirements_centos_libs_install libyaml-devel',
showing last 15 lines of /usr/local/rvm/log/1388234096/package_install_libyaml-devel.log
[2013-12-28 12:34:56] requirements_centos_libs_install
requirements_centos_libs_install ()
{
    __rvm_try_sudo yum install -y "$@" || return $?
}
current path: /root
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/share/centrifydc/bin:/usr/share/centrifydc/sbin:/root/bin:/usr/local/rvm/bin
command(2): requirements_centos_libs_install libyaml-devel
Loaded plugins: product-id, security, subscription-manager
This system is receiving updates from Red Hat Subscription Management.
Repository atomic is listed more than once in the configuration
Repository epel is listed more than once in the configuration
Setting up Install Process
No package libyaml-devel available.
Error: Nothing to do
Requirements installation failed with status: 1.

I have tried multiple solution provided on the internet but nothing is changing the state. could you please have a look on this and advise

**Comment by Sane-Joker** [comment]
Hi,

I am facing the same issue on RHEL 7, below are the logs, can some help be provided please,

Installing required packages: libyaml-devel, libffi-devel.....
Error running 'requirements_centos_libs_install libyaml-devel libffi-devel',
showing last 15 lines of /usr/local/rvm/log/1468250720/package_install_libyaml-devel_libffi-devel.log
            If you don't want/need both architectures anymore then you
            can remove the one with the missing update and everything
            will work.
       
         3. You have duplicate versions of libyaml installed already.
            You can use "yum check" to get yum show these errors.
       
       ...you can also use --setopt=protected_multilib=false to remove
       this checking, however this is almost never the correct thing to
       do as something else is very likely to go wrong (often causing
       much more problems).
       
       Protected multilib versions: libyaml-0.1.3-4.el6_6.i686 != libyaml-0.1.4-11.el7_0.x86_64
+ return 1
+ return 1
Requirements installation failed with status: 1.

**Comment by Hacktivista** [comment]
+1

**Comment by suthanbala** [comment]
+1 With RHEL 7

Anyone found a solution?

**Comment by mpapis** [comment]
@HSDen @Hacktivista @suthanbala this is old issue, please open a new ticket with details (would love to that by extracting your comments, but GH does not have such feature).

**Comment by pkuczynski** [comment]
For whatever reason it seems that @HSDen have RHEL6.6 and RHEL7 package installed at the same time. We can work on this, but as @mpapis mentioned, please create a new ticket
