### ISSUE TITLE
scripts/rvm doesn't work in the fish shell

### ISSUE THREAD

**Issue by rnelson** [rvm/rvm#2516]
The rvm script completely fails to load under fish. Trying to source it results in a few hundred lines of errors and help text. A sample run is available at http://pastie.org/8606634.

fish 2.1.0
OS X 10.9
rvm 1.25.10

**Comment by zevaverbach** [comment]
[Just putting this quick fix here for anyone else who stumbles onto it](https://rvm.io/integration/fish)
