### ISSUE TITLE
.ruby-version not respected in new tab of gnome-terminal

### ISSUE THREAD

**Issue by ethco** [rvm/rvm#2519]
When I am in a rvm-enabled project (/home/ethan/oauthr) in gnome-terminal, when I open a new tab (which opens in the same directory), the .ruby-version seems to be ignored. the ruby is configured to use by default is used instead. if I `cd ..` and then cd back into the project, all is well. 

.ruby-version is `rbx-2.2.2`
.ruby-gemset is `oauthr`
default rvm ruby is 1.9.3p362

relevant bits of `env`, just after opening a new tab:

```
$ env | grep -iE 'rvm|path|home'
rvm_bin_path=/home/ethan/.rvm/bin
GEM_HOME=/home/ethan/.rvm/gems/ruby-1.9.3-p362@oauthr
IRBRC=/home/ethan/.rvm/rubies/ruby-1.9.3-p362/.irbrc
MY_RUBY_HOME=/home/ethan/.rvm/rubies/ruby-1.9.3-p362
rvm_path=/home/ethan/.rvm
rvm_prefix=/home/ethan
PATH=/home/ethan/.rvm/gems/ruby-1.9.3-p362@oauthr/bin:/home/ethan/.rvm/gems/ruby-1.9.3-p362@global/bin:/home/ethan/.rvm/rubies/ruby-1.9.3-p362/bin:/home/ethan/.rvm/bin:/home/ethan/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ethan/vhome/bin:/home/ethan/bin:/home/ethan/bin/snx
PWD=/home/ethan/oauthr
rvm_version=1.25.14 (stable)
HOME=/home/ethan
rvm_ruby_string=ruby-1.9.3-p362
GEM_PATH=/home/ethan/.rvm/gems/ruby-1.9.3-p362@oauthr:/home/ethan/.rvm/gems/ruby-1.9.3-p362@global
rvm_delete_flag=0
```

and after `cd`ing out and back into the project:

```
$ env | grep -iE 'rvm|path|home'
rvm_bin_path=/home/ethan/.rvm/bin
GEM_HOME=/home/ethan/.rvm/gems/rbx-2.2.2@oauthr
IRBRC=/home/ethan/.rvm/rubies/rbx-2.2.2/.irbrc
OLDPWD=/home/ethan
MY_RUBY_HOME=/home/ethan/.rvm/rubies/rbx-2.2.2
rvm_path=/home/ethan/.rvm
rvm_prefix=/home/ethan
PATH=/home/ethan/.rvm/gems/rbx-2.2.2@oauthr/bin:/home/ethan/.rvm/gems/rbx-2.2.2@global/bin:/home/ethan/.rvm/rubies/rbx-2.2.2/bin:/home/ethan/.rvm/bin:/home/ethan/bin:/usr/lib/lightdm/lightdm:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ethan/vhome/bin:/home/ethan/bin:/home/ethan/bin/snx
PWD=/home/ethan/oauthr
rvm_version=1.25.14 (stable)
HOME=/home/ethan
rvm_ruby_string=rbx-2.2.2
GEM_PATH=/home/ethan/.rvm/gems/rbx-2.2.2@oauthr:/home/ethan/.rvm/gems/rbx-2.2.2@global
rvm_nightly_flag=0
rvm_delete_flag=0
```

**Comment by pahnin** [comment]
I'm facing same issue still.

Gnome terminal version: 3.14.2
If I cd into the project folder which has `.ruby-gemset` and `.ruby-version` rvm loads fine, but if I open new tab, rvm won't load the correct gemset.

I'm currently on rvm 1.26.11

variables,

case 1: I'm already in folder, now I opened new tab
```
phanindra@phanindra-Vostro-2520:~/Circle-v2$ env | grep -iE 'rvm|path|home'
rvm_bin_path=/home/phanindra/.rvm/bin
GEM_HOME=/home/phanindra/.rvm/gems/ruby-2.1.1
IRBRC=/home/phanindra/.rvm/rubies/ruby-2.1.1/.irbrc
MY_RUBY_HOME=/home/phanindra/.rvm/rubies/ruby-2.1.1
rvm_stored_umask=0002
rvm_path=/home/phanindra/.rvm
DEFAULTS_PATH=/usr/share/gconf/gnome.default.path
rvm_prefix=/home/phanindra
PATH=/usr/local/heroku/bin:/home/phanindra/.rvm/gems/ruby-2.1.1/bin:/home/phanindra/.rvm/gems/ruby-2.1.1@global/bin:/home/phanindra/.rvm/rubies/ruby-2.1.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/phanindra/.rvm/bin:/home/phanindra/.rvm/bin:/home/phanindra/.rvm/bin
rvm_loaded_flag=1
PWD=/home/phanindra/Circle-v2
MANDATORY_PATH=/usr/share/gconf/gnome.mandatory.path
rvm_version=1.26.11 (latest)
HOME=/home/phanindra
GEM_PATH=/home/phanindra/.rvm/gems/ruby-2.1.1:/home/phanindra/.rvm/gems/ruby-2.1.1@global
WINDOWPATH=7
rvm_user_install_flag=1
```

now I run `cd .` now rvm loads fine

```
phanindra@phanindra-Vostro-2520:~/Circle-v2$ cd .
phanindra@phanindra-Vostro-2520:~/Circle-v2$ env | grep -iE 'rvm|path|home'
rvm_bin_path=/home/phanindra/.rvm/bin
GEM_HOME=/home/phanindra/.rvm/gems/ruby-2.1.1@circle
IRBRC=/home/phanindra/.rvm/rubies/ruby-2.1.1/.irbrc
OLDPWD=/home/phanindra/Circle-v2
MY_RUBY_HOME=/home/phanindra/.rvm/rubies/ruby-2.1.1
rvm_path=/home/phanindra/.rvm
DEFAULTS_PATH=/usr/share/gconf/gnome.default.path
rvm_prefix=/home/phanindra
PATH=/home/phanindra/.rvm/gems/ruby-2.1.1@circle/bin:/home/phanindra/.rvm/gems/ruby-2.1.1@global/bin:/home/phanindra/.rvm/rubies/ruby-2.1.1/bin:/home/phanindra/.rvm/bin:/usr/local/heroku/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/phanindra/Circle-v2
MANDATORY_PATH=/usr/share/gconf/gnome.mandatory.path
rvm_version=1.26.11 (latest)
HOME=/home/phanindra
rvm_ruby_string=ruby-2.1.1
GEM_PATH=/home/phanindra/.rvm/gems/ruby-2.1.1@circle:/home/phanindra/.rvm/gems/ruby-2.1.1@global
WINDOWPATH=7
rvm_delete_flag=0
```

**Comment by csong-r7** [comment]
I have the same issue with rvm 1.26.11. I have to run `cd .` as a workaround as well.

**Comment by jhulford** [comment]
Confirmed still an issue...ubuntu 14.04/guake terminal

<pre>
rvm_bin_path=/home/my_user/.rvm/bin
GEM_HOME=/home/my_user/.rvm/gems/ruby-2.0.0-p247
TMPDIR=/home/my_user/tmp
IRBRC=/home/my_user/.rvm/rubies/ruby-2.0.0-p247/.irbrc
MY_RUBY_HOME=/home/my_user/.rvm/rubies/ruby-2.0.0-p247
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
rvm_path=/home/my_user/.rvm
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
rvm_prefix=/home/my_user
PATH=/home/my_user/.rvm/gems/ruby-2.0.0-p247/bin:/home/my_user/.rvm/gems/ruby-2.0.0-p247@global/bin:/home/my_user/.rvm/rubies/ruby-2.0.0-p247/bin:/home/my_user/.rvm/bin:/home/my_user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/my_user/.rvm/bin:/home/my_user/.rvm/bin
PWD=/home/my_user/workspace/my_project
JAVA_HOME=/usr
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
rvm_version=1.26.11 (latest)
HOME=/home/my_user
GEM_PATH=/home/my_user/.rvm/gems/ruby-2.0.0-p247:/home/my_user/.rvm/gems/ruby-2.0.0-p247@global
XAUTHORITY=/home/my_user/.Xauthority
</pre>

After `cd .`:

<pre>
rvm_bin_path=/home/my_user/.rvm/bin
GEM_HOME=/home/my_user/.rvm/gems/ruby-2.2.2@my_gemset
TMPDIR=/home/my_user/tmp
IRBRC=/home/my_user/.rvm/rubies/ruby-2.2.2/.irbrc
OLDPWD=/home/my_user/workspace/my_project
MY_RUBY_HOME=/home/my_user/.rvm/rubies/ruby-2.2.2
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
rvm_path=/home/my_user/.rvm
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
rvm_prefix=/home/my_user
PATH=/home/my_user/.rvm/gems/ruby-2.2.2@my_gemset/bin:/home/my_user/.rvm/gems/ruby-2.2.2@global/bin:/home/my_user/.rvm/rubies/ruby-2.2.2/bin:/home/my_user/.rvm/bin:/home/my_user/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PWD=/home/my_user/workspace/my_project
JAVA_HOME=/usr
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
rvm_version=1.26.11 (latest)
HOME=/home/my_user
rvm_ruby_string=ruby-2.2.2
GEM_PATH=/home/my_user/.rvm/gems/ruby-2.2.2@my_gemset:/home/my_user/.rvm/gems/ruby-2.2.2@global
rvm_delete_flag=0
XAUTHORITY=/home/my_user/.Xauthority
</pre>

What's even weirder to me, rvm's not even using my default ruby (which is 2.2.2 NOT ruby-2.0.0-p247)  when I open a new terminal window in my project directory.

**Comment by mpapis** [comment]
for anyone still hitting this problem, is login shell enabled in your terminal settings? if that's the case and it still does not work - please open a new ticket, the problem in this one was already fixed and you can not face it unless you either use old rvm or have login shell disabled in the terminal preferences

**Comment by csong-r7** [comment]
I can reproduce this problem on rvm 1.26.11 with login shell enabled.

**Comment by mpapis** [comment]
then as I said - it has to be other problem, please open a new issue with all the details

**Comment by jhulford** [comment]
Changing my guake preferences to "Run command as a login shell" resolved the issue for me. Thanks for the info @mpapis.

**Comment by vipin8169** [comment]
I am facing the same problem.
Executed the following command in a terminal tab:
vipin8169@vipin8169-Inspiron-5558:~/projectRoot/inmonarch_website$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

Now, opened the new tab with ctrl+shift+tab and executed the same command, got some version corresponding to some other project
vipin8169@vipin8169-Inspiron-5558:~/projectRoot/inmonarch_website$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

When opening new tab, I've to cd into the directory to make it work
cd ./

"Run command as a login shell" is already enabled in the terminal preferences

**Comment by vickodin** [comment]
I have read the text above and made the next:

`$ echo "cd ." >> ~/.bash_profile`

Fixed! :smile:

**Comment by pahnin** [comment]
thanks @vickodin

**Comment by usmanasif** [comment]
@vickodin this is a good hackish work around. But this will not solve the problem, my whole team unless they do the same.

**Comment by ziaulrehman40** [comment]
@vickodin this is a good hackish work around. But this will not solve the problem, my whole team unless they do the same.

**Comment by raelgc** [comment]
@ziaulrehman40 This is a problem of old gnome-terminals tab not running as a login shell. 

Later versions of gnome-terminal remove the "new tab" option. Now you can only "open new terminals in tab" or "open new terminals in window". Both properly working.

Gnome-terminal included in Ubuntu 14.04 is the problematic one, in 16.04 is the updated and working one.

**Comment by ziaulrehman40** [comment]
@raelgc I am on 16.04.xx and I am still having this same issue.
RVM does not pick my ruby version to use as current unless i do 'cd .'.
So, i guess is somewhere else maybe.
I checked with a friend and his is working fine even without login shell(as he told me).

**Comment by mpapis** [comment]
@ziaulrehman40 if there are still problems please open a new issue with more details, the original issue was resolved.

**Comment by goyalmunish** [comment]
I had the same issues. But adding following at the top of `~/.tmux.conf` worked:

```
set-option -g default-shell /bin/zsh
```
My environment is:
OS: Mac 10.12.4
tmux 2.4
zsh 5.4.2 (x86_64-apple-darwin16.7.0)
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
