### ISSUE TITLE
RVM doesn't set correct ruby version in new session.

### ISSUE THREAD

**Issue by santochan** [rvm/rvm#2520]
I'm using bash shell on Mac OSX 1.9.1(both iTerm2 and Terminal)

I have .ruby-version and .ruby-gemset in my project directory. I cd the directory it will get correct ruby version and gemset. But when I create a new window/tab(⌘+N / ⌘+T) from this directory, it won't set correct ruby version(it set default version) but set correct gemset.

**Comment by vipin8169** [comment]
I am facing the same problem.
Executed the following command in a terminal tab:
vipin8169@vipin8169-Inspiron-5558:~/projectRoot/inmonarch_website$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

Now, opened the new tab with ctrl+shift+tab and executed the same command, got some version corresponding to some other project
vipin8169@vipin8169-Inspiron-5558:~/projectRoot/inmonarch_website$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

**Comment by vipin8169** [comment]
When opening new tab, I've to cd into the directory to make it work
cd ./
