### ISSUE TITLE
system ruby is used in new terminal tabs opened in home directory 

### ISSUE THREAD

**Issue by ethco** [rvm/rvm#2527]
when I open a new tab in gnome-terminal in my home directory, the system ruby is used instead of the default ruby configured for rvm. 

only occurs when ~/.rvmrc is present; if I move this file, the rvm default ruby is correctly used. 

related to #2519.

**Comment by denisovlev** [comment]
the same issue on Ubuntu 14.04
When I move to the directory `.ruby-gemset` and `.ruby-version` files affect the current gemset. But when I open a new terminal tab with `ctrl+shift+T` in the same directory gemset gets switched to default

What I have already done without an effect:
- [x] rvm get stable --auto-dotfiles
- [x] login shell

In original tab:
```
denisovlev@u14denisov:~/rails/staas$ rvm gemset list

gemsets for ruby-2.1.2 (found in /home/denisovlev/.rvm/gems/ruby-2.1.2)
   (default)
   global
=> staas
```
In newly opened:
```
denisovlev@u14denisov:~/rails/staas$ rvm gemset list

gemsets for ruby-2.1.2 (found in /home/denisovlev/.rvm/gems/ruby-2.1.2)
=> (default)
   global
   staas
```

**Comment by vipin8169** [comment]
Getting the same issue on Ubuntu 14.04
When opening new tab, I've to cd into the directory to make it work
cd ./

**Comment by NazarK** [comment]
added "cd ." as last line to ~/.profile

**Comment by raelgc** [comment]
I'm still affected by this when opening a new Gnome Terminal tab. And, like other users, I have the Gnome Terminal to run "Run Command as a Login Shell".

Wondering if Gnome Terminal does not login when a new tab is opened (only when the a new Gnome Terminal instance is opened).

**Comment by SubhashShah-BTC** [comment]
I have same issue on `ubuntu 14.04 64-bit`.

As mentioned by @NazarK, Adding `cd .` to `~/.profile` fixed the problem.

Is that the proper way of doing it?

**Comment by mpapis** [comment]
@SubhashShah-BTC did you check https://github.com/rvm/rvm/issues/2527#issuecomment-32754553 - it should be a better option

**Comment by raelgc** [comment]
@mpapis Even with the Gnome Terminal marked to run a shell login, this happens.

I know that in latest Gnome Terminal (included in Ubuntu 16.04) they removed this option to open a new tab. It sounds like this option to open a new tab do not run as login shell.

I.e., in theory, this **appears** to be not a `rvm` problem.

**Comment by mpapis** [comment]
well, so for now you will need to use the `cd .` trick in `~/.profile` - V1 is already frozen for changes for long time, I'm slowly working my way to get progress on V2, and in V2 we will get a lot more flexibility to do anything that is needed

**Comment by rhombl4** [comment]
What could be wrong when I place the command "cd ." in .zshrc-file but get no effect on the new terminal? Typing 'cd .' on this new terminal works Ok and the command from rc-file is executed.
