### ISSUE TITLE
in terminal opened inside rvm project, cding out uses system ruby instead of rvm default

### ISSUE THREAD

**Issue by ethco** [rvm/rvm#2531]
this one is weird. 
- open a new terminal tab in a rvm-enabled project (for me, ~/oauthr)
  - rvm correctly uses the ruby for that project
- cd out of the project into a non-rvm directory
  - rvm switches to the system ruby instead of the default ruby configured for rvm

this continues if I then cd back into any rvm project (switches to the project's ruby) and then back out to any non-rvm directory (uses system ruby instead of rvm default ruby) 

this doesn't happen when the terminal is initially opened outside of an rvm-enabled project - it correctly uses the rvm default ruby, switches correctly when cding into a rvm project, and switches back to the rvm default ruby when cding back out.

**Comment by vipin8169** [comment]
Still getting the same problem with "rvm 1.26.11"

**Comment by SubhashShah-BTC** [comment]
Didn't work for me on `Ubuntu 14.04 64-bit`.
