### ISSUE TITLE
loading RVM seems slow

### ISSUE THREAD

**Issue by tisba** [rvm/rvm#2582]
While trying to debug the slow zsh startup, I noticed that

``` bash
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
```

takes a significant amount of time. Using `time /usr/local/bin/zsh -c "source $HOME/.rvm/scripts/rvm"` I noticed that it takes about **1 sec** (+/- 150ms). For a college of mine (@railsbros-dirk) the same command (same zsh and RVM version) takes about 0.15s.

I already reinstalled RVM (`rvm implode`) without any difference.

I'd like to debug this further but I don't know where to start exactly :-/

I'm using
- OS X 10.9.1
- rvm 1.25.15 (master)
- zsh 5.0.5 (via homebrew)
- iTerm2 Build 1.0.0.20140112

**Comment by orangeudav** [comment]
Hmm, i have same problem with speed of `source "$HOME/.rvm/scripts/rvm"` last two days , but after profiled with `time /usr/local/bin/bash -c "rvm_trace_flag=1; source $HOME/.rvm/scripts/rvm" 2>&1 | tee big.log` the problem was disappeared. The log is here https://gist.github.com/orangeudav/80fff5484198f58085bf17447a787042
This is sort of magic i think :) 
ps In one moment i saw error that uname and ps not found ...

```
> rvm --version
rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
> uname -a
Darwin scud.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
> echo $PATH
/Users/orangeudav/.rvm/gems/ruby-2.3.1/bin:/Users/orangeudav/.rvm/gems/ruby-2.3.1@global/bin:/Users/orangeudav/.rvm/rubies/ruby-2.3.1/bin:/Users/orangeudav/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/orangeudav/.rvm/bin
```

**Comment by TheNotary** [comment]
Confirmed, it's like magic,

```
$ rvm version
rvm 1.28.0 (latest) by Wayne E. Seguin

$ time /bin/bash -c "rvm_trace_flag=1; source $HOME/.rvm/scripts/rvm" 2>&1 | tee big.log
```

New terminals are booting up in under half a second (as opposed to >1s before the magic 'diagnostic' command was run).  It seems that it does take 200ms to perform the source command still.  Is there another diagnostic command to improve upon that or is 200ms expected performance?
