### ISSUE TITLE
rvm does not install required packages on FreeBSD 10.0 automatically

### ISSUE THREAD

**Issue by cahlf** [rvm/rvm#2591]
When installing a ruby for the first time, rvm asks the user to type his password in order to download the required packages using the package manager (in case sudo is available and the packages are not yet installed on the system). But after typing the password, rvm just sits there forever and does nothing. The output after invoking `rvm install ruby` is this:

``` bash
Searching for binary rubies, this might take some time.
No binary rubies available for: freebsd/10.0/i386/ruby-2.1.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for freebsd.
Installing requirements for freebsd.
Updating system - please wait
Installing required packages: automake, libtool, bison, readline, libyaml - please wait
carsten password required for 'pkg install automake libtool bison readline libyaml':
```

As stated, nothing happens after typing in the password. No network traffic is taking place. Providing the wrong password results in being asked for the password again.

**Comment by trumpetx** [comment]
this issue was not fixed as of today, but this post saved me many more hours of debugging....
