### ISSUE TITLE
Error while trying to install rvm with '\curl -sSL https://get.rvm.io | bash -s stable --ruby'

### ISSUE THREAD

**Issue by francisalfanta** [rvm/rvm#2623]
I am using CentOS 6.4. I'm trying to install veewee which happens to require rvm https://github.com/jedi4ever/veewee/blob/master/doc/requirements.md
I follow the lead to install rvm by development version using 
$ \curl -sSL https://get.rvm.io | bash
or 
$ \curl -sSL https://get.rvm.io | bash -s stable --ruby
but I got this return error

curl: (6) Couldn't resolve host 'bitbucket.org'

Could not download 'https://bitbucket.org/mpapis/rvm/get/master.tar.gz'.
curl returned status '6'.

I'm new to rvm and ruby and how to get around linux.

Thanks for any help
Francis

**Comment by Yaseer94** [comment]
curl: (7) Failed to connect to get.rvm.io port 443: Network is unreachable

**Comment by Yaseer94** [comment]
i am getting this error

**Comment by mpapis** [comment]
@Yaseer94 it looks like your network configuration error, if you can't figure it out open a new ticket

**Comment by EvyW** [comment]
It works on mint!: 

\curl -sSL https://get.rvm.io | bash --debug
#   Thank you for using RVM!

thank you @mpapis

**Comment by rajeev-khangar** [comment]
I am still getting this error.
 \curl -sSL https://get.rvm.io | bash --debug
curl: (7) Failed to connect to get.rvm.io port 443: Network is unreachable

**Comment by mpapis** [comment]
@rajeev-khangar I was upgrading server, it should be all good now

**Comment by dhbrian** [comment]
Cannot download .tar.gz

curl -sSL https://get.rvm.io | sudo bash -s stable --rails
Downloading https://github.com/rvm/rvm/archive/.tar.gz
curl: (7) 
Failed connect to github.com:443; Operation now in progress
Could not download 'https://github.com/rvm/rvm/archive/.tar.gz'.
curl returned status '7'.
Downloading https://bitbucket.org/mpapis/rvm/get/.tar.gz
curl: (7) 
Failed connect to bitbucket.org:443; Operation now in progress
Could not download 'https://bitbucket.org/mpapis/rvm/get/.tar.gz'.
curl returned status '7'.

Please help. 
Thanks.

**Comment by mpapis** [comment]
@dhbrian I'm getting:
```bash
Downloading https://github.com/rvm/rvm/archive/1.29.1.tar.gz
```
Can you recheck? This could be temporary issue, if it still does not work - please open a new ticket with details about your system.

**Comment by dhbrian** [comment]
Problem fixed with command:
curl -sSL https://get.rvm.io | bash -s stable --rails

Thanks
