### ISSUE TITLE
cygwin reports ps: unknown option -- o

### ISSUE THREAD

**Issue by sam452** [rvm/rvm#2631]
On a new Win7 machine, fresh copy of cygwin and bash install of rvm I'm finding the initialization warnings:

```
Do not know how to check user shell on 'CYGWIN_NT-6.1'.
  * No new notes to display.

ps: unknown option -- o
Try `ps --help' for more information.
ps: unknown option -- o
Try `ps --help' for more information.
RVM reloaded!
```

Running ps --version in cygwin yields

```
ps (cygwin) 1.7.28
```

This is reported after 

```
rvm get head
```

I have pulled the cygwin branch from github and there are no impacts to this message.

It's as if the creators of rvm are using a more recent version of ps than cygwin?

thanx, sam

**Comment by Ajedi32** [comment]
I'm running into this error now too in Git Bash. Looks like my problem is actually #3704...
