### ISSUE TITLE
Add support for JRuby 9000 + Graal

### ISSUE THREAD

**Issue by chrisseaton** [rvm/rvm#2646]
JRuby 9000 (the next major release) includes support for a new JIT compiler in the JVM, called Graal. Graal isn't released yet, so it's a pain to set up. I'd like to add a new version of JRuby, jruby-9000+graal-dev, that includes both the JRuby 9000 snapshot and also a binary of Graal. There are simple binary tarballs for Mac and Linux that we can download.

The patch to rbenv was this https://github.com/sstephenson/ruby-build/pull/514/files.

I'm not sure how to do the same for rvm.

**Comment by javfindly** [comment]
looks like the link http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-9000+graal-linux-x86_64.dev-bin.tar.gz is down. Is there any other mirror or should I build my own? Thanks

**Comment by chrisseaton** [comment]
The version number scheme that JRuby kept changing, so I've made some version-independent downloads that should always work:

* http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-linux-x86_64-bin.tar.gz
* http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-macosx-x86_64-bin.tar.gz

There's no Windows build at the moment. Let me know if those don't work or if you have any other problems.

**Comment by havenwood** [comment]
Thanks! Here are copy/pastable commands with those URLs just for convenience:

OS X:
```sh
rvm mount -r http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-macosx-x86_64-bin.tar.gz -n jruby-dev-graal
```
GNU/Linux:
```sh
rvm mount -r http://lafo.ssw.uni-linz.ac.at/graalvm/jruby-dist-master+graal-linux-x86_64-bin.tar.gz -n jruby-dev-graal
```
