### ISSUE TITLE
Mavericks, cannot install gems because libyaml is missing?

### ISSUE THREAD

**Issue by pzula** [rvm/rvm#2689]
I've tried using RVM since I've upgraded to OSX Mavericks, and I've come across the same issue more than once while trying to install gems.

When using Ruby 2.1.1 as my installation, and running `gem install minitest`, I received the following error:

```
gem install minitest
/Users/pzula/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/yaml.rb:4:in `<top (required)>':
It seems your ruby installation is missing psych (for YAML output).
To eliminate this warning, please install libyaml and reinstall your ruby.
/Users/pzula/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/Users/pzula/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/x86_64-darwin13.0/psych.bundle, 9): Library not loaded: /usr/local/lib/libyaml-0.2.dylib (LoadError)
...........
```

Having read the error message, I thought perhaps I somehow have autolibs turned off, so I went ahead and removed RVM from the system, and reinstalled using the following command:

```
\curl -sSL https://get.rvm.io | bash -s stable --ruby
```

However, even after reinstalling RVM, I am unable to install gems due to the libyaml error. Am I doing something incorrectly? Do I have to install libyaml separately?

**Comment by amboxer21** [comment]
Why the fuck is everyone using rmv? Is everyone that lazy and cant navigate a Linux terminal?
