### ISSUE TITLE
Installing ruby 2.1.1 - get this error    Error running '__rvm_make -B -j1'

### ISSUE THREAD

**Issue by kschadeck** [rvm/rvm#2767]
This is windows running in dev environment on putty. This doesn't happen on 1.9.3 or less. 
here is output:

``` bash
ruby-2.1.1 - #downloading ruby-2.1.1, this may take a while depending on your connection...
ruby-2.1.1 - #extracting ruby-2.1.1 to /home/SW-NETWORK/kschadeck/.rvm/src/ruby-2.1.1...
ruby-2.1.1 - #applying patch /home/SW-NETWORK/kschadeck/.rvm/patches/ruby/changeset_r45225.diff..
ruby-2.1.1 - #applying patch /home/SW-NETWORK/kschadeck/.rvm/patches/ruby/changeset_r45240.diff..
ruby-2.1.1 - #configuring.....................................................
ruby-2.1.1 - #post-configuration.
ruby-2.1.1 - #compiling.............................
Error running '__rvm_make -B -j1',
showing last 15 lines of /home/SW-NETWORK/kschadeck/.rvm/log/1397060655_ruby-2.1.1/make.log
generating enc.mk
compiling dln.c
compiling localeinit.c
creating verconf.h
compiling loadpath.c
generating prelude.c
compiling prelude.c
linking static-library libruby-static.a
verifying static-library libruby-static.a
linking shared-library libruby.so.21
/usr/bin/ld: cannot find -lexecinfo
*** Error code 1

Stop in /home/SW-NETWORK/kschadeck/.rvm/src/ruby-2.1.1.
++ 1397060738.N /scripts/functions/support : __rvm_make()  281 > return 1
There has been an error while running make. Halting the installation.
```

**Comment by makedirectory** [comment]
> ```shell
> [2014-12-19 13:04:52] __rvm_make
> __rvm_make () 
> { 
>     \make "$@" || return $?
> }
> current path: /Users/julio/.rvm/src/ruby-2.0.0-p247
> command(3): __rvm_make -j 1
>     CC = /usr/bin/gcc
>     LD = ld
>     LDSHARED = /usr/bin/gcc -dynamiclib
>     CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration   -fno-common -pipe 
>     XCFLAGS = -include ruby/config.h -include ruby/missing.h -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT
>     CPPFLAGS = -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT -I/opt/local/include   -I. -I.ext/include/x86_64-darwin14.1.0 -I./include -I.
>     DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/opt/local/lib  -install_name /Users/julio/.rvm/rubies/ruby-2.0.0-p247/lib/libruby.2.0.0.dylib -current_version 2.0.0 -compatibility_version 2.0.0  -fstack-protector -Wl,-u,_objc_msgSend  -fstack-protector -Wl,-u,_objc_msgSend  
>     SOLIBS = 
> compiling main.c
> compiling dmydln.c
> ...
> linking shared-object racc/cparse.bundle
> installing default cparse libraries
> compiling readline.c
> readline.c:1886:26: error: use of undeclared identifier 'Function'
>     rl_pre_input_hook = (Function *)readline_pre_input_hook;
>                          ^
> readline.c:1886:36: error: expected expression
>     rl_pre_input_hook = (Function *)readline_pre_input_hook;
>                                    ^
> 2 errors generated.
> make[2]: *** [readline.o] Error 1
> make[1]: *** [ext/readline/all] Error 2
> make: *** [build-ext] Error 2
> ```
> 
> Please guys, help me.

rvm install 2.4.0 --with-openssl-dir=/usr/local/opt/openssl

Replace 2.4.0 with version number

From: https://github.com/rvm/rvm/issues/4608#issuecomment-461897390
