### ISSUE TITLE
Error running '__rvm_make -j 1', showing last 15 lines of /Users/name/.rvm/log/1399578403_ruby-1.9.3-p545/make.log

### ISSUE THREAD

**Issue by testengineer00** [rvm/rvm#2837]
Trying to install ruby 1.9.3 on 10.9.2 and getting this error

name:~ name$ rvm install 1.9.3 --with-gcc=clang
ruby-1.9.3-p545 - #removing src/ruby-1.9.3-p545.. 
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' already are up to date.
Requirements installation successful.
Warning: found user selected compiler 'clang', this will suppress RVM auto detection mechanisms.
Installing Ruby from source to: /Users/name/.rvm/rubies/ruby-1.9.3-p545, this may take a while depending on your cpu(s)...
ruby-1.9.3-p545 - #downloading ruby-1.9.3-p545, this may take a while depending on your connection...
ruby-1.9.3-p545 - #extracting ruby-1.9.3-p545 to /Users/name/.rvm/src/ruby-1.9.3-p545...
ruby-1.9.3-p545 - #applying patch /Users/name/.rvm/patches/ruby/GH-488.patch.
ruby-1.9.3-p545 - #configuring...............................................
ruby-1.9.3-p545 - #post-configuration.
ruby-1.9.3-p545 - #compiling............
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/name/.rvm/log/1399578403_ruby-1.9.3-p545/make.log
-- Other runtime information -----------------------------------------------
- Loaded script: ./miniruby
- Loaded features:
  
  0 enumerator.so

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

make: **\* [.rbconfig.time] Abort trap: 6
++ return 2
There has been an error while running make. Halting the installation.

If I try without clang I get this error...

Error running 'requirements_osx_brew_libs_install gcc46',

ANY help would be appreciated.

**Comment by sathibabu-nyros** [comment]
so I was googling a bit and found that you could try use:

                 rvm install ruby-2.1.1 --without-execinfo
