### ISSUE TITLE
rvm.io site is down

### ISSUE THREAD

**Issue by evolutionxbox** [rvm/rvm#2887]
I can't access it at all. (http://isup.me/rvm.io)
This therefore means that it cannot be install via curl.

**Comment by cyupa** [comment]
Down again 😞

**Comment by pmq20** [comment]
Down again 😞

**Comment by zakir-hyder** [comment]
Down again 😞

**Comment by mpapis** [comment]
fixed, I thought this was working already and yet it fails on me again ...

**Comment by abegehr** [comment]
down :(

**Comment by mpapis** [comment]
@abegehr just checked it works for me, can you provide more details in separate ticket?

**Comment by abegehr** [comment]
Works for me now as well!
