### ISSUE TITLE
Failed downloading ruby-2.0.0-p353

### ISSUE THREAD

**Issue by ghost** [rvm/rvm#2889]
I am trying to install ruby-2.0.0 but i get failed while i am installing.I have tried installing with following given command.Hope you guys can help me with it...

==> rvm install ruby-2.0.0-p353 --debug
ruby-2.0.0-p353 - install
ruby-2.0.0-p353 - #already removed src/ruby-2.0.0-p353
ruby-2.0.0-p353 - #already removed rubies/ruby-2.0.0-p353
Searching for binary rubies, this might take some time.
Remote file does not exist https://rvm.io/binaries/mint/16/x86_64/ruby-2.0.0-p353.tar.bz2
Remote file does not exist http://jruby.org.s3.amazonaws.com/downloads/ruby-2.0.0-p353.tar.bz2
Remote file does not exist http://binaries.rubini.us/mint/16/x86_64/ruby-2.0.0-p353.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/mint/16/x86_64/ruby-2.0.0-p353.tar.bz2
rvm_remote_server_url4 not found
No remote file name found
No binary rubies available for: mint/16/x86_64/ruby-2.0.0-p353.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Free disk space 17486MB, required 390MB.
__rvm_setup_compile_environment_setup ruby-2.0.0-p353
rvm_autolibs_flag=4
__rvm_setup_compile_environment_movable_early ruby-2.0.0-p353
__rvm_setup_compile_environment_system_early ruby-2.0.0-p353
__rvm_setup_compile_environment_requirements ruby-2.0.0-p353
Checking requirements for mint.
requirements code for mint loaded
Found required packages: bash, curl, patch, bzip2, ca-certificates, gawk, g++, gcc, make, libc6-dev, patch, openssl, ca-certificates, libreadline6, libreadline6-dev, curl, zlib1g, zlib1g-dev, libssl-dev, libyaml-dev, libsqlite3-dev, sqlite3, autoconf, libgdbm-dev, libncurses5-dev, automake, libtool, bison, pkg-config, libffi-dev.
Requirements installation successful.
__rvm_setup_compile_environment_movable ruby-2.0.0-p353
__rvm_setup_compile_environment_parse_name ruby-2.0.0-p353
__rvm_setup_compile_environment_system ruby-2.0.0-p353
__rvm_setup_compile_environment_architectures ruby-2.0.0-p353
rvm_architectures(0):.
__rvm_setup_compile_environment_gcc47plus ruby-2.0.0-p353
__rvm_setup_compile_environment_bison ruby-2.0.0-p353
__rvm_setup_compile_environment_flags_docs ruby-2.0.0-p353
__rvm_setup_compile_environment_flags_shared_static ruby-2.0.0-p353
__rvm_setup_compile_environment_flags_threads ruby-2.0.0-p353
__rvm_setup_compile_environment_compatibility_flag ruby-2.0.0-p353
found compiler: /usr/bin/gcc
Installing Ruby from source to: /home/travis/.rvm/rubies/ruby-2.0.0-p353, this may take a while depending on your cpu(s)...
ruby-2.0.0-p353 - #downloading ruby-2.0.0-p353, this may take a while depending on your connection...
No archive, downloading
Running(19): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 --create-dirs -C - -o ruby-2.0.0-p353.tar.bz2.part http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p353.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
Warning: Transient problem: timeout Will retry in 2 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:00:30 --:--:--     0
curl: (28) Connection timed out after 30001 milliseconds
There was an error(28).
Checking fallback: http://ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p353.tar.bz2
Checking fallback: http://www.mirrorservice.org/sites/ftp.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p353.tar.bz2
No fallback URL could be found, try increasing timeout with:

```
echo "export rvm_max_time_flag=20" >> ~/.rvmrc
```

There has been an error fetching the ruby interpreter. Halting the installation.
__rvm_rm_rf already gone: /home/travis/.rvm/tmp/2814*

**Comment by fatimarafiqui** [comment]
If such an error occurs, check for proxy setting or possible internet connectivity issues.

**Comment by rakeshnambiar** [comment]
@mpapis I am facing the same issue with the `curl` command while calling the trigger from GitLab and the curl command starts like below.

`curl --retry 5 --retry-delay 20 -u  trigger_name`

Please let me know in case you have any thought on this.
