### ISSUE TITLE
rvm breaking vim

### ISSUE THREAD

**Issue by ailnlv** [rvm/rvm#2931]
At some point I installed ruby 2.1.1 on OSX using rvm. When rvm started acting up for some reason, I did a `rm -rf .rvm` and reinstalled it. Since some time had passed, I installed ruby 2.1.2 instead of 2.1.1. However, for some reason, when I try to launch vim I get the following error:

```
dyld: Library not loaded: /Users/yo/.rvm/rubies/ruby-2.1.1/lib/libruby.2.1.0.dylib
  Referenced from: /usr/local/bin/vim
  Reason: image not found
[1]    25530 trace trap  vim
```

If I reinstall 2.1.1 with `rvm reinstall 2.1.1 --disable-binary` then the error is fixed, but it reappears when I remove it.

Can anyone help me with this?

**Comment by richkuo** [comment]
i just ran into this

i did a ```'brew uninstall vim'```

and that worked for me - i believe i am now using my native vim

**Comment by gabeio** [comment]
:+1: just fixed vim thanks for the tip :smiley:!
```bash
$ brew reinstall vim
```
Worked like a charm!

**Comment by mbrevda** [comment]
:+1:

**Comment by ChrisDeveloper** [comment]
Thanks @gabeio , `brew reinstall vim` is exactly what I needed.

**Comment by meadowstream** [comment]
@gabeio That worked perfectly :beers:
