### ISSUE TITLE
Network is unreachable

### ISSUE THREAD

**Issue by binarykitchen** [rvm/rvm#2989]
I tried `\curl -sSL https://get.rvm.io | bash -s stable` but it does not work:

```
$ \curl -sSL https://get.rvm.io | bash -s stable
curl: (7) Failed to connect to get.rvm.io port 443: Network is unreachable
```

**Comment by VimalanDhanapal** [comment]
echo ip4 >> ~/.curlrc worked for me, Thank you

**Comment by VnMa** [comment]
echo ipv4 >> ~/.curlrc works for me too. Thanks

**Comment by sunnykasera3107** [comment]
echo ipv4 >> ~/.curlrc works for me too. Thanks

**Comment by karthigashree** [comment]
Anyone help me the same problem occured for me..But the command not working echo ipv4 >> ~/.curlrc
It shows error like this
Warning: /home/karthiga/.curlrc:1: warning: 'ip4' is unknown
Warning: /home/karthiga/.curlrc:2: warning: 'ip4' is unknown
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to get.rvm.io port 443: Network is unreachable

**Comment by srinath-v** [comment]
@karthigashree 
you need  to edit your .curlrc file. I think ip4 has been saved to it. Edit it ti ipv4 and give it a shot.
Should fix things.

**Comment by pamio** [comment]
Nope, not working. Tried editing and also tried appending ipv4 through terminal. Nothing works. Any suggestions on this please ?

**Comment by mpapis** [comment]
the server was down, it's fixed now

**Comment by navinspm** [comment]
same error tried all the things

**Comment by pamio** [comment]
Yep, its working now without having to edit ~/.curlrc file

**Comment by karthigamahe** [comment]
Thank you it was  worked now

**Comment by spurdow** [comment]
echo ipv4 >> ~/.curlrc works for me thanks

and then do curl -L https://get.rvm.io | bash -s stable

**Comment by tushargupta7** [comment]
Thanks a lot...it worked..:)

**Comment by arkyaC** [comment]
echo ipv4 >> ~/.curlrc worked for me.. thanks :+1:

**Comment by Avinash1405** [comment]
curl -sSL https://get.rvm.io | bash -s stable

When I try the above command I am connection refused error
curl: (7) Failed to connect to get.rvm.io port 443: Connection refused

I have tried echo ipv4 >> ~/.curlrc , Even though I am getting same error, Please help me

**Comment by mpapis** [comment]
the site was down, it's fixed, please try again

**Comment by Avinash1405** [comment]
Thanks a lot...it worked

**Comment by manoj83** [comment]
The issue is still occurring.

\curl https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
curl: (7) couldn't connect to host

\curl -sSL https://get.rvm.io | bash -s stable --ruby=jruby --gems=rails,puma
curl: (7) couldn't connect to host

**Comment by ProteanDev** [comment]
maybe check if you're connected to the internet or if your network allows ipv4? Some networks only have ipv6 now. Or maybe the site is just down as of the moment, please try again later.

**Comment by manoj83** [comment]
Yes, I am connected to the internet. It seems server is down, as reported in previous comments

**Comment by manoj83** [comment]
I used following trick to install : 
wget https://github.com/wayneeseguin/rvm/archive/stable.tar.gz
Untar and run ./install from the extracted directory.

**Comment by mpapis** [comment]
@manoj83 we support both ipv4 & 6, the error `7` means `Failed to connect to host.` which suggests the server is not available from your location, please open a new issue with output of:
```bash
curl -sSLI https://get.rvm.io
```

**Comment by venu20895** [comment]
Hello Michal Papis,

I tried "echo ipv4 >> ~/.curlrc" and later I tried with the following command "curl -L https://get.rvm.io/ | bash -s stable".

Now it is not working for me and we are getting end up with "Failed connect to get.rvm.io:443; Connection timed out"

Can one one help me ?
