### ISSUE TITLE
Unknown ruby interpreter version (do not know how to handle): *.

### ISSUE THREAD

**Issue by lpeabody** [rvm/rvm#3013]
I'm trying to reinstall RVM, and I thought I had scrubbed my system of any trace of it. However, when I install RVM now, I get the following error.

```
Unknown ruby interpreter version (do not know how to handle): *.
```

I'm not sure what to do exactly. RVM installs, and you can issue commands, but when you say, for example:

```
rvm install ruby-2.1.1
```

You get the following:

```
[lpeabody@BlueDrop ~] rvm install ruby-2.1.1
Unknown ruby string (do not know how to handle): ruby-2.1.1.
Unknown ruby string (do not know how to handle): ruby-2.1.1.
Searching for binary rubies, this might take some time.
Found remote file https://rvm.io/binaries/osx/10.9/x86_64/ruby-2.1.1.tar.bz2
Checking requirements for osx.
```

Another example:

```
[lpeabody@BlueDrop ~] rvm gemset create hueproject
Unknown ruby string (do not know how to handle): ruby-2.1.1.
ruby-2.1.1 - #gemset created /Users/lpeabody/.rvm/gems/ruby-2.1.1@hueproject
ruby-2.1.1 - #generating hueproject wrappers........
```

I'm not sure what to do besides reinstall and reboot. However, I've done this, and it's still happening. Thoughts?

**Comment by kinjal20** [comment]
rvm pkg install openssl
It shows that rvm pkg is deprecated ......and at the end

                                      rvm reinstall all --force 

when i run this it shows
unknown ruby interpreter version(do not know how to handle):all

now what can solution of it?
