### ISSUE TITLE
Issues installing ruby 2.1.3 using RVM

### ISSUE THREAD

**Issue by ghost** [rvm/rvm#3050]
I had no issues installing ruby 2.1.2 with rvm install ruby 2.1.2, but when I try to install ruby 2.1.3 with  rvm install ruby 2.1.3, the installation stops at the compiling stage (over 24hrs elapsed with no progress). I'm on OS X Lion with Xcode 4.6.3. I'm guessing this is due to a compiler issue?

Output:

ruby-2.1.3 - #removing src/ruby-2.1.3..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.7/i386/ruby-2.1.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/xxx/.rvm/rubies/ruby-2.1.3, this may take a while depending on your cpu(s)...
ruby-2.1.3 - #downloading ruby-2.1.3, this may take a while depending on your connection...
ruby-2.1.3 - #extracting ruby-2.1.3 to /Users/xxx/.rvm/src/ruby-2.1.3....
ruby-2.1.3 - #configuring.....................................................
ruby-2.1.3 - #post-configuration.
ruby-2.1.3 - #compiling........|

Thanks.

**Comment by SyamPhanindraChavva** [comment]
I am using 10.14, I also stuck in the compiling stage for more than 6hrs I have tried this "rvm install 2.2.6 -- --with-setjmp-type=setjmp" still it's not working any help on this, please.I have tried with other versions of ruby as well it also having same issue.
