### ISSUE TITLE
RVM head broke prompt output

### ISSUE THREAD

**Issue by tejanium** [rvm/rvm#3091]
I'm on zsh and here is my prompt setup:

`PROMPT='%F{green}%. ${vcs_info_msg_0_}$ '`

when cd to directory contains `.ruby-version` the `%.` give me `RVM_PROJECT_PATH` on RVM head, but give me current directory in RVM stable.

**Comment by adamstac** [comment]
FWIW updating to the latest oh-my-zsh fixed this issue for me. Thanks @mpapis and everyone in this thread finding the issue and getting it fixed.
