### ISSUE TITLE
Install Ruby 1.9.2 on 10.10 (Yosemite)

### ISSUE THREAD

**Issue by RLovelett** [rvm/rvm#3099]
After upgrading to RVM (`1.25.33 (master)`) as noted in issue [#3906](https://github.com/wayneeseguin/rvm/issues/3096) I am still not able to compile Ruby 1.9.2 (specifically `ruby-1.9.2-p330`) on 10.10.

```
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.10 (14A389)
      Kernel Version: Darwin 14.0.0
      Boot Volume:
      Boot Mode: Normal
      Computer Name:
      User Name: Ryan Lovelett (ryan)
      Secure Virtual Memory: Enabled
      Time since boot: 6:39
```

Running `rvm install 1.9.2` results in an error (`malloc: *** error for object 0x7f8f92802808: incorrect checksum for freed object - object was probably modified after being freed.`). A gist of the [make.log can be found here](https://gist.github.com/anonymous/61f778ff63bc54701b9c).

**EDIT**: Fixed link to other issue. Added the error message for anyone who might search for this issue via the error message.

**Comment by MarcoDeBortoli** [comment]
@mpapis I thought I give my input as well on this despite it comes from rbenv, the principles is the same all in all. [This](https://gist.github.com/MarcoDeBortoli/b680f5853bda4d1a1fc1) is the error I'm currently getting with any 1.9.2 regardless the patch level. Also 1.9.2 is the only one that seems affected, previous versions even down to 1.8.6 compile just fine.

The same error is spat out with a previously compiled (and working) 1.9.2-p330 that I installed and still have on my system from before Yosemite.

I hope it helps.
