### ISSUE TITLE
RVM get stable after new key requirement is confusing

### ISSUE THREAD

**Issue by enebo** [rvm/rvm#3108]
``` text
1.8.7 ~/work/rails/activesupport master 583% rvm get stable
Downloading https://get.rvm.io
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.0.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.0/1.26.0.tar.gz.asc
gpg: Signature made Wed Oct 29 07:52:06 2014 CDT using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
GPG signature verification failed for '/Users/enebo/Developer/.rvm/archives/rvm-1.26.0.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.0/1.26.0.tar.gz.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

they can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

bash: line 415: return: _ret: numeric argument required
Downloading https://bitbucket.org/mpapis/rvm/get/1.26.0.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.0/1.26.0.tar.gz.asc
gpg: Signature made Wed Oct 29 07:52:06 2014 CDT using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
GPG signature verification failed for '/Users/enebo/Developer/.rvm/archives/rvm-1.26.0.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.0/1.26.0.tar.gz.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3

they can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

bash: line 415: return: _ret: numeric argument required
Could not update RVM, get some help at #rvm IRC channel at freenode servers.
```

The phrase 'try downloading the signatures:' does indeed solve the issue, but it sounds more like you trying to diagnose a problem rather than point out rvm needs a new key installed to work.  I suggest something like:

``` text
After version x.y.z of RVM all downloads are verified with a new GPG key.  Please install this
new key using the command: gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
```

Perhaps even a little sentence about a level of trust that this requires (which is why we are manually 
adding the key).

**Comment by dabimahesh** [comment]
I have done these steps but still am unable to install RVM. I get following response after getting keys

gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) mpapis@gmail.com" not changed
gpg: Total number processed: 1
gpg: unchanged: 1

After that if I run following to install RVM but it is still giving same error of signature verification failed.

curl -L https://get.rvm.io | bash -s stable --autolibs=enabled

Let me know if I am missing any step.

**Comment by mpapis** [comment]
@dabimahesh please open a new ticket with all output of the installer

**Comment by DanielJEgan** [comment]
Hi, I'm getting what seems to be the same issue. When  I try the first download suggested I get a key not found error, when I try the second one I get a not changed warning.

The output for each of the two commands and then a retry of the install is given below:

redmine@luke:~$ sudo gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpgkeys: key 409B6B1796C275462A1703113804BB82D39DC0E3 not found on keyserver
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
redmine@luke:~$ command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
redmine@luke:~$ \curl -L https://get.rvm.io | bash -s stable --rails
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0   1032      0 --:--:-- --:--:-- --:--:--  1343
100 22817  100 22817    0     0  67596      0 --:--:-- --:--:-- --:--:-- 67596
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.9.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc
gpg: Signature made Wed 07 Jan 2015 22:25:10 CST using RSA key ID BF04FF17
gpg: Can't check signature: public key not found
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/redmine/.rvm/archives/rvm-1.26.9.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc'!
try downloading the signatures:

    sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

redmine@luke:~$

**Comment by mpapis** [comment]
@DanielJEgan try this:
```bash
command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
```
if it does not help - please open a new ticket

**Comment by samuelnure79** [comment]
La opción 2 que brindo daneb me funciono!

Primero, puse en la terminal la linea de codigo del numeral 2.
y finalmente ejecute la instalacion de rvm: \curl -L https://get.rvm.io | bash -s stable

Solamente. Eso me funciono. Gracias!

**Comment by mattmartini** [comment]
One of the issues that I ran into is that while I was able to import the 
RVM Signing key, it was not trusted and therefor getting the new rvm failed.

What you have to do is trust the key, and more specifically you have to trust
the RVM Signing key, not the mater key.

You can follow the steps below to see how this is done.



    $ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
    gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
    gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
    gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
    gpg: depth: 0  valid:   2  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 2u
    gpg: next trustdb check due at 2017-01-12
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    
    $ gpg --list-key D39DC0E3
    pub   4096R/D39DC0E3 2014-10-28
    uid                  Michal Papis (RVM signing) <mpapis@gmail.com>
    sub   4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]
    
    $ gpg --edit-key D39DC0E3
    gpg (GnuPG) 1.4.19; Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: unknown       validity: unknown
    sub  4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ unknown] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    gpg> key 1
    
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: unknown       validity: unknown
    sub* 4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ unknown] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    gpg> trust
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: unknown       validity: unknown
    sub* 4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ unknown] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    Please decide how far you trust this user to correctly verify other users' keys
    (by looking at passports, checking fingerprints from different sources, etc.)
    
      1 = I don't know or won't say
      2 = I do NOT trust
      3 = I trust marginally
      4 = I trust fully
      5 = I trust ultimately
      m = back to the main menu
    
    Your decision? 4
    
    pub  4096R/D39DC0E3  created: 2014-10-28  expires: never       usage: SC
                         trust: full          validity: unknown
    sub* 4096R/BF04FF17  created: 2014-10-28  expires: 2016-01-05  usage: S
    [ full] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
    
    gpg> quit

**Comment by bismailov** [comment]
I had similar issue on Ubuntu 12.04. I already had ruby 1.9.3 installed, and when I tried `rvm get stable`, system wanted me to get the certificates by `gpg --keyserver hkp://keys.gnupg.net --recv-keys 40..E3`

But gpg kept giving me errors, to fix them I followed the below command list:

    mkdir .gnupg
    chmod 700 .gnupg
    gpg --gen-key

After that the command `gpg --keyserver hkp://keys.gnupg.net --recv-keys 40..E3` worked alright.

**Comment by learningtjrs** [comment]
hello, i just want to say what happened with me. i have faced the same problem as above. i did follow the instructions, i have put it this <gpg --keyserver hkp://keys.gnupg.net --recv-keys ..... > into the terminal and run it. the keys and the permissions was downloaded and everything was successful. i run again <\curl -L https://get.rvm.io | bash -s stable --ruby> and everything was normal, the ruby was installed successfully. of course we have to run the rvm machine and it run successfully. everything was mentioned in the process inside the console (terminal).  i just follow the instructions.

**Comment by tom-cloyd** [comment]
I, too, had this "gpg: keyserver receive failed: public key not found" problem. I'm a psychotherapist who programs a bit, not a professional. Had I not found this discussion thread here it'd have been a showstopper for me. WHY does this problem keep occurring? Why is it not fixed by now? A problem that began two years ago? I don't get it.

Borrowing from above, these commands got rvm installed for me:

```
command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
\curl -L https://get.rvm.io | bash -s stable
```
There's nothing about this at the rvm homepage, though.

**Comment by pkuczynski** [comment]
Hi @tom-cloyd we are working on a new version of the documentation which would clarify many things and in the meantime on a new release or RVM which would also give more clearer messages to the users. You should see changes soon...
