### ISSUE TITLE
GPG key error in scripted installation of RVM

### ISSUE THREAD

**Issue by chrispomeroy** [rvm/rvm#3110]
I'm having a problem adding the new GPG key.  Trying to fix to a scripted installation of RVM which stopped working after this key requirement.

The script fails when I use `curl -sSL https://get.rvm.io | sudo bash -s stable`

even though I placed `gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3` right before it.

I also tried using `--batch --exit-on-status-write-error` flags with gpg

Any ideas?

gpg exists with a status code of 1

The funny thing is, adding the gpg key works fine when I manually paste the line into the terminal, just not in a shell script.

**Comment by chilicuil** [comment]
@howardroark this is how I run the script in *insecure* mode:

    curl -sSL https://get.rvm.io | sed "s/which gp/which xp/g" | bash -s stable --ruby

Not sure if it will make to fail rvm when installing/configuring additional rubies, just use it to install the stable version.

**Comment by wxn0000** [comment]
I'm running rum 1.26.0 on Mac OS Yosemite 10.10.2. When I tried to upgrade rvm, I got the following message:
```
-bash $ rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/xiaoning/.rvm/archives/rvm-installer.asc
gpg: /Users/xiaoning/.gnupg/gpg.conf:237: invalid option
GPG signature verification failed for '/Users/xiaoning/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:
 
    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
 
they can be compared with:
 
    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
 
-bash: return: _ret: numeric argument required
```
Then I try to import the key using gpg, but got this error:
```
-bash $ gpg2 --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
gpg: /Users/xiaoning/.gnupg/gpg.conf:237: invalid option
```
How should I proceed? Thank you for your help!

**Comment by arnlen** [comment]
Hi!

Still encounting this problem, here in a **Vagrant** Ubuntu Precise64 box, trying to install RVM with Ansible (from the official [rvm1-ansible](https://github.com/rvm/rvm1-ansible) repo)

```bash
TASK: [rvm_io.rvm1-ruby | Import GPG keys] ************************************
failed: [default] => {"changed": false, "cmd": ["gpg", "--keyserver", "hkp://keys.gnupg.net", "--recv-keys", "D39DC0E3"], "delta": "0:00:00.791200", "end": "2015-02-23 20:34:27.881423", "rc": 2, "start": "2015-02-23 20:34:27.090223", "warnings": []}
stderr: gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
stdout: gpgkeys: key D39DC0E3 not found on keyserver

FATAL: all hosts have already failed -- aborting
```

**Comment by manojtr** [comment]
This is still not working. 

 Downloading https://get.rvm.io
 Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
 Verifying /usr/local/rvm/archives/rvm-installer.asc
 gpg: Signature made Sun 11 Jan 2015 10:55:55 AM UTC using RSA key ID BF04FF17
 gpg: Can't check signature: public key not found
 Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
 Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

 GPG signature verification failed for '/usr/local/rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
 try downloading the signatures:

     gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

 or if it fails:

     command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

 the key can be compared with:

     https://rvm.io/mpapis.asc
     https://keybase.io/mpapis

**Comment by arnlen** [comment]
Maybe a related issue: https://github.com/rvm/rvm1-ansible/issues/31

**Comment by tokhi** [comment]
Had the same issue, I could resolve it by removing the `.gnupg` directory

``` 
rm -rf ~/.gnupg/
curl -#LO https://rvm.io/mpapis.asc
\curl -sSL https://get.rvm.io | bash -s stable
```

**Comment by varghesethomase** [comment]
@mpapis  Its quiet misleading in your site https://rvm.io/ that you havent added sudo to run the gpg command. It took me quiet long to figure out this thread and to install it. Its good to update it as a newbie always finds it difficult

**Comment by endymion** [comment]
How does it add any security to require me to download a key from rvm.io to verify code that I downloaded from rvm.io?  This security is based on the DNS record, not the signature.  If somebody hijacks rvm.io and posts a malicious version of RVM then they can post their own key for validating their malicious code, and so this feature ends up doing nothing to protect me.  It only created a lot of hassle in setting up a Vagrant VM.

**Comment by howardroark** [comment]
I think it is great that security is a priority with this project.  Though I also think that because everyone now uses automation tools this type of thing becomes moot with a huge percentage of users.  If you just blindly accept the keys you are not doing much good.

I feel the best way to manage this problem is just to match md5 sums against packages before you install them.  At least that way you make it very difficult for someone to spoof.

**Comment by djmaze** [comment]
@endymion To be more accurate: The security is not only based on the DNS record, but on the site's HTTPS certificate as well. So they do not only need to hijack the DNS, but also get the private key used for the certificate. 

The common scenario would be an attacker hijacking the (web)server instead. As rvm.io and get.rvm.io seem to be served from different servers (at least there are different IPs), the GPG approach might add a bit of security. 

But, as has been said before, a better way is to use a separate entity for getting the key (like keys.gnupg.net).

**Comment by mpapis** [comment]
clarifying:

* <https://rvm.io> - cache of <https://www.rvm.io> by fastly (`www` to prevent cache loop)
* <https://get.rvm.io> - the same as <https://www.rvm.io> - forward to `binscripts/installer` on github

**Comment by tensorproduct** [comment]
I'm going to leave a comment to help out anybody who hit the same problem that I did.

On running `gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3` as instructed, I encountered an error message like:

    vagrant@vagrant-ubuntu-trusty-64:~/project$ gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
    gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
    ?: keys.gnupg.net: Host not found
    gpgkeys: HTTP fetch error 7: couldn't connect: Success
    gpg: no valid OpenPGP data found.
    gpg: Total number processed: 0

Nobody in this thread has specifically cited that error message, though I suspect that a few have encountered it.

This appears to be an issue with how gpg resolves aliases. Running `host keys.gnupg.net` shows that it is an alias for pool.sks-keyservers.net. Adding the key by specifying the target of the alias fixes this problem:

    vagrant@vagrant-ubuntu-trusty-64:~$ gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys D39DC0E3
    gpg: directory `/home/vagrant/.gnupg' created
    gpg: new configuration file `/home/vagrant/.gnupg/gpg.conf' created
    gpg: WARNING: options in `/home/vagrant/.gnupg/gpg.conf' are not yet active during this run
    gpg: keyring `/home/vagrant/.gnupg/secring.gpg' created
    gpg: keyring `/home/vagrant/.gnupg/pubring.gpg' created
    gpg: requesting key D39DC0E3 from hkp server pool.sks-keyservers.net
    gpg: /home/vagrant/.gnupg/trustdb.gpg: trustdb created
    gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
    gpg: no ultimately trusted keys found
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)

There are discussions of this problem (here)[https://bugs.launchpad.net/ubuntu/+source/gnupg/+bug/1044156] and (here)[http://comments.gmane.org/gmane.network.tor.relay/6626]. It's not clear to me why it affects some people but not others.

If people must have a one-liner, a general (but ugly) solution is to partially resolve the DNS record before passing it to gpg, like so `gpg --keyserver $(dig +short keys.gnupg.net | head -n 1) --recv-keys D39DC0E3`. I have no idea if this represents a further security vulnerability.

**Comment by ajkochanowicz** [comment]
@AlmogBaku 's fix worked for me

**Comment by tikums** [comment]
`# gpg --verify 1.26.11.tar.gz.asc /usr/local/rvm/archives/rvm-1.26.11.tgz
gpg: Signature made Mon 30 Mar 2015 11:52:13 PM CEST using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"

# gpg --fingerprint mpapis@gmail.com
pub   4096R/D39DC0E3 2014-10-28
      Key fingerprint = 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
uid                  Michal Papis (RVM signing) <mpapis@gmail.com>
sub   4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]`

The key was imported from `keys.gnupg.net` key server.

**Comment by aivils** [comment]
It does not work under vagrant. Under vagrant gpg runs with root ID in the /home/vagrant folder. I follow  "mpapis commented on 6 Nov 2014 " suggestion.
This code works for me:
```ruby
execute "rvm gpg keys" do
  cwd "/root"
  user "root"
  environment "HOME"=>"/root"
  command "curl -#LO https://rvm.io/mpapis.asc && gpg --import mpapis.asc"
  action :run
end
```

**Comment by x-yuri** [comment]
I'm not sure if there's just one issue discussed here, so I thought it may be better to discuss the one mentioned by @blaffoy [here][1].

[1]: https://github.com/protobox/protobox/issues/159

**Comment by adamlwgriffiths** [comment]
Only @blaffoy's snippet worked for me

```
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys D39DC0E3
```

Since this is such a large issue, would you please update the front page? I've never had RVM install without 30m of searching the internet for the fix.

If you cannot install this on stock Ubuntu, then your instructions are for-all-intents-and-purposes incorrect.

**Comment by x-yuri** [comment]
@adamlwgriffiths More succinct [thread][1]. Were you experiencing it under `virtualbox`?

[1]: https://github.com/protobox/protobox/issues/159

**Comment by adamlwgriffiths** [comment]
Thanks, that's exactly my situation (VirtualBox OSX + Ubuntu Guest). It explains a lot of the issues I've been having with my VMs.
Glad to see my lack of faith in virtual box is not unfounded.

**Comment by moizsajid** [comment]
Solution: [http://www.sachingevariya.com/2015/08/requirementsdebianupdatesystem-ruby-222.html?showComment=1457203998281#c5999890352997520478](http://www.sachingevariya.com/2015/08/requirementsdebianupdatesystem-ruby-222.html?showComment=1457203998281#c5999890352997520478)

**Comment by klahnen** [comment]
Simplest way is to force gpg to use port 80:
`gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
`

**Comment by theiapax** [comment]
Guys, excuse my ignorance but I'm not the technical guy that would be normally reading this but I had to.
I need to install a ruby I could use to run some code for a basic website we're building. I'm on OSX 10.10.5, not sure what my co-worker is on.
When I run 'which ruby' I get '/usr/bin/ruby' so I went to RVM to fix it.
When I click on @mpapis public key I cant download it (There is no application set to open the document "mpapis.asc").
What should I download to get the key?

**Comment by mpapis** [comment]
@theiapax run the command from previous reply (@klahnen's)

**Comment by theiapax** [comment]
Thanks @mpapis 
did that, got this '-bash: gpg: command not found'
Thanks for your help

**Comment by theiapax** [comment]
I think I did it with brew install gpg (so simple)... I'm sure I'll be back with some other problems :-)
Thanks

**Comment by jvenezia** [comment]
Thanks @tokhi

**Comment by nazzalra** [comment]
---------------------------------TRY THIS BROTHER------------------------------

first install gpgv2
sudo apt-get install gpgv2

secondly
curl -sSL https://rvm.io/mpapis.asc | gpg --import

**Comment by Startouf** [comment]
I am getting this error on a new install of RVM on Amazon Linux 2, which I did not run into a few months ago

> $ curl -sSL https://get.rvm.io | sudo bash -s stable
...
> GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.5.tgz'

I have tried to 
>     sudo gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
>     command curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -

My libs
gpgv (GnuPG) 2.0.22
libgcrypt 1.5.3

I'm still trying to figure out what is the gpg package name on yum to see if an update works

**Comment by pkuczynski** [comment]
@Startouf we released this version signed by another dev (me) with the second key on the list. You would need to import it via:

`sudo gpg2 --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

**Comment by kissu** [comment]
None of the snippets above works. :(

**Comment by pkuczynski** [comment]
@kissu its all about importing the keys. Try

```
gpg --keyserver hkp://keys.gnupg.net:80 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```

**Comment by pkuczynski** [comment]
@dangol I am working on bringing rvm site to live. Haven't noticed the build is failing. Will ping u as soon as it's done

**Comment by pkuczynski** [comment]
@dangol done. Try now!

**Comment by ndiesslin** [comment]
I just started running into this error also and this fixed resolved it for me
`gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

**Comment by dangol** [comment]
@pkuczynski Seems to be working, at the moment thanks

**Comment by x-yuri** [comment]
[This][1] might help.

[1]: https://github.com/protobox/protobox/issues/159#issuecomment-152840998

**Comment by kissu** [comment]
@pkuczynski Working again, thanks ! 🙏

**Comment by bumpux** [comment]
Still stuck. Mac OS Mojave. Tried various permutations here and elsewhere. Any summary of best solution?

**Comment by geerlingguy** [comment]
In my case, on Ubuntu 16.04, I ran:

```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```

(`gpg` instead of `gpg2`). I'm using the `rvm.rvm` Ansible role for automation, and it seems to be running into this error duing initial server provision: https://github.com/rvm/rvm1-ansible/issues/186

**Comment by peterloeffler** [comment]
seems to work when using master:
`bash /var/chef/cache/rvm-installer-googlepremiumadapter master`
but not with `stable` or `--version ...`

**Comment by rhizome** [comment]
Specifying `--keyserver...` worked for me.

**Comment by dominicsayers** [comment]
@mpapis The message when it fails to install/update only mentions the original key. I believe it should also mention the new key you described in https://github.com/rvm/rvm/issues/3110#issuecomment-446577397

Here is the message I'm seeing when I do `rvm get stable` today:

```bash
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/build/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.
```

I think the third line should be

    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

as you implied in https://github.com/rvm/rvm/issues/3110#issuecomment-446655227

**Comment by pkuczynski** [comment]
@dominicsayers I updated the message in the latest version, which we will release soon. Thanks for pointing out.

**Comment by sblackstone** [comment]
I was encountering a problem with Mojave similar to this issue - I think the problem is that if you're upgrading from an old version of RVM the gpg install directions don't include the key thats now required for rvm proper.

Going to the website and using those keys first fixes everything.

gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
