### ISSUE TITLE
Ruby installing error "Requirements installation failed with status: 100."

### ISSUE THREAD

**Issue by ghost** [rvm/rvm#3129]
I followed [this](http://installfest.railsbridge.org/installfest/linux?back=choose_your_operating_system) installation Guide for RVM, and it worked fine until i tried installing Ruby, i tried to follow the [RVM](https://rvm.io/rubies/installing) guide but the result is the same and now i am stuck !  
Can some one help!

> xxxxxxxxx@home:~$ rvm install ruby-2.0.0-p594
> Searching for binary rubies, this might take some time.
> No binary rubies available for: ubuntu/14.04/x86_64/ruby-2.0.0-p594.
> Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
> Checking requirements for ubuntu.
> Installing requirements for ubuntu.
> Updating system..................
> Error running 'requirements_debian_update_system ruby-2.0.0-p594',
> showing last 15 lines of /home/teeneagle/.rvm/log/1415554193_ruby-2.0.0-p594/update_system.log
> ++ case "${TERM:-dumb}" in
> ++ case "$1" in
> ++ [[ -t 2 ]]
> ++ return 1
> ++ printf %b 'There has been error while updating '\''apt-get'\'', please give it some time and try again later.
> For 404 errors check your sources configured in:
>     /etc/apt/sources.list
>     /etc/apt/sources.list.d/_.list
> \n'
> There has been error while updating 'apt-get', please give it some time and try again later.
> For 404 errors check your sources configured in:
>     /etc/apt/sources.list
>     /etc/apt/sources.list.d/_.list
> ++ return 100
> Requirements installation failed with status: 100.

**Comment by shyamtadori** [comment]
Hi Teeneagle,
I am facing the same issue & i could not fix it. 
Can you please share the link you used to install ruby. (link was missing in your second comment) 

Your Comment : 
Thank you @mpapis , I followed** this** to install Ruby and it worked.

**Comment by Chinmay-Kalyankar** [comment]
its still now working in my case......I had same problem but after apt-get update its showing same error

**Comment by Chinmay-Kalyankar** [comment]
its still now working in my case......I had same problem but after apt-get update its showing same error
![screenshot from 2017-06-12 18-40-38](https://user-images.githubusercontent.com/29373278/27035365-ae25d674-4f9e-11e7-9dd6-5e0ba1b68e4c.png)

**Comment by Nemish550** [comment]
Checking requirements for termux.
Installing requirements for termux.
Installing required packages: bash, curl, patch, bzip2, ca-certificates, gawk, clang, coreutils, curl, gawk, git, gnupg, gpgv, libc++, libclang, libclang-dev, libllvm, libxml2, make, ncurses, ncurses-ui-libs, openssl, openssl-dev, openssl-tool, readline, sqlite, tar, zlib, zlib-dev....
Error running 'requirements_termux_libs_install bash curl patch bzip2 ca-certificates gawk clang coreutils curl gawk git gnupg gpgv libc++ libclang libclang-dev libllvm libxml2 make ncurses ncurses-ui-libs openssl openssl-dev openssl-tool readline sqlite tar zlib zlib-dev',
please read /data/data/com.termux/files/home/.rvm/log/1613531569/package_install_bash_curl_patch_bzip2_ca-certificates_gawk_clang_coreutils_curl_gawk_git_gnupg_gpgv_libc++_libclang_libclang-dev_libllvm_libxml2_make_ncurses_ncurses-ui-libs_openssl_openssl-dev_ope.log
Requirements installation failed with status: 100.

now what to do, please help

**Comment by iioowwu** [comment]
> its still now working in my case......I had same problem but after apt-get update its showing same error
> ![screenshot from 2017-06-12 18-40-38](https://user-images.githubusercontent.com/29373278/27035365-ae25d674-4f9e-11e7-9dd6-5e0ba1b68e4c.png)

Hello. I have same problem. Same text. I am stuck with it. I don't what to do. I am using Termux.

**Comment by vczb** [comment]
I had the same problem, I resolved restoring the default of source.list.

I used this example here

https://gist.github.com/ishad0w/788555191c7037e249a439542c53e170
