### ISSUE TITLE
Unknown ruby interpreter version (do not know how to handle): gems.

### ISSUE THREAD

**Issue by kwadade** [rvm/rvm#3135]
I am trying to update my RVM but I get this error:
"Unknown ruby interpreter version (do not know how to handle): gems."
https://www.dropbox.com/s/nrkldvoyjcaal85/Screenshot%202014-11-13%2010.47.13.png?dl=0

**Comment by kinjal20** [comment]
rvm pkg install openssl
It shows that rvm pkg is deprecated ......and at the end 

                                          rvm reinstall all --force 

when i run this it shows
unknown ruby interpreter version(do not know how to handle):all

now what can solution of it?

**Comment by vcoelho23** [comment]
> next `rvm get head` will fix it

Work for me too thanks!!
