### ISSUE TITLE
Teach rvm about mksh.

### ISSUE THREAD

**Issue by ghost** [rvm/rvm#3142]
We need to teach rvm about the mksh shell. Some useful links for this endeavor are:
1. https://www.mirbsd.org/mksh.htm and
2. https://www.mirbsd.org/htman/i386/man1/mksh.htm

**Comment by mirabilos** [comment]
That `realloc` error sounds like a loop? Maybe nested re-reading itself?

**Comment by zacts** [comment]
Just FYI. I personally no longer use rvm, but I guess I can try to help if I can.

**Comment by zacts** [comment]
@mirabilos chruby has issues with mksh as well, so I may open a ticket there too if I can find the time.
