### ISSUE TITLE
"RVM is not a function" in Elementary OS

### ISSUE THREAD

**Issue by etech0** [rvm/rvm#3157]
Hi!

When trying to use rvm in Elementary OS (Luna), I get RVM is not a function. 

There is no preferences menu. I tried http://stackoverflow.com/questions/18412827/rvm-in-elementary-luna-os but I have to rerun it each time I open a new terminal. Any advice?

Thanks!

**Comment by LuisHCK** [comment]
i managed to make it work running this command echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"' >> ~/.bashrc

**Comment by brad** [comment]
Thanks @LuisHCK! For zsh, this worked for me:
```
echo '[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"' >> ~/.zshrc
```

**Comment by alex-Z-** [comment]
Obvious one, but anyways, after the command mentioned above is executed in terminal, you should restart your terminal app.

**Comment by LuisHCK** [comment]
> Obvious one, but anyways, after the command mentioned above is executed in terminal, you should restart your terminal app.

Or do something like this `source ~/.bashrc`
