### ISSUE TITLE
gemset use => unknown subcommand 'use'

### ISSUE THREAD

**Issue by mpapis** [rvm/rvm#3164]
reporting rare occurrence that `gemset use` is not known subcommand in Zsh, reported by @TheAtomicGoose but as I can not reproduce it and even shorter version works just fine:

``` bash
rvm use @gemset
```

closing the ticket as wontfix.

**Comment by filipefigcorreia** [comment]
I've just been bitten by this issue with RVM 1.26.11. I confirm that it works fine when I do `rvm use @gemset` though.
