### ISSUE TITLE
'Key Not Certified' Warning

### ISSUE THREAD

**Issue by keithrbennett** [rvm/rvm#3166]
When I try to do a 'rvm get stable' I get the warning "gpg: WARNING: This key is not certified with a trusted signature!" below.  Should I care?:

Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/kbennett/.rvm/archives/rvm-installer.asc
gpg: Signature made Wed Nov 26 06:10:08 2014 EST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) mpapis@gmail.com"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/kbennett/.rvm/archives/rvm-installer'

**Comment by leoj3n** [comment]
Note: A trust level less than 5 (ultimate) will fail to eliminate the warning (using `gpg2`).

**Comment by bbugh** [comment]
Came here from google, here are rvm-specific instructions for trusting: https://github.com/rvm/rvm/blob/master/docs/gpg.md
