### ISSUE TITLE
YAML availability on RHEL

### ISSUE THREAD

**Issue by cg2v** [rvm/rvm#3191]
As I noted in #2998, Red Hat does ship YAML libraries for RHEL 6 and 7, but they are not in the "base" repo that is enabled on machines when they are configured for Red Hat's update mechanism (either Red Hat Network or Subscription Manager). Michal asked for more details about that.

Red Hat's old update mechanism is Red Hat Network, machines using RHN can be detected by the presence of /etc/sysconfig/rhn/systemid. The rhn-channel command can be used to list the currently subscribed repositories, the available repositories, and to change the list of subscribed repositories. It must be run as root, and some commands require authenticating to a remote service.

machine with only base repository:
# rhn-channel -l
rhel-x86_64-server-7

machine with more repositories:
# rhn-channel -l
rhel-x86_64-server-7
rhel-x86_64-server-7-debuginfo
rhel-x86_64-server-7-thirdparty-oracle-java
rhel-x86_64-server-optional-7
rhel-x86_64-server-optional-7-debuginfo

Adding a repo:
\$ sudo rhn-channel -a -c rhel-x86_64-server-optional-7
Username: XXXX
Password: 
\$ sudo rhn-channel -l
rhel-x86_64-server-7
rhel-x86_64-server-optional-7

The newer system that everyone is being pushed towards is Red Hat Subscription Management. It can be detected by the presence of PEM files in /etc/pki/tls/consumer

I don't have one of these (but I am considering setting one up to get details for you) Documentation is at
https://access.redhat.com/documentation/en-US/Red_Hat_Subscription_Management/1/html/RHSM/supplementary-repos.html

It might be possible to do the detection for either system using the "yum repolist" command. The output is sent to stderr only, and seems to be truncated based on the terminal width:

# yum repolist
Loaded plugins: aliases, changelog, langpacks, product-id, rhnplugin,
              : subscription-manager, tmprepo, verify, versionlock
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
This system is receiving updates from RHN Classic or Red Hat Satellite.
repo id                                     repo name                     status
epel-x86_64-rhel7                           Fedora EPEL for RHEL 7 Server 8,151
rhel-x86_64-server-7                        Red Hat Enterprise Linux Serv 5,116
rhel-x86_64-server-7-debuginfo              RHEL Server Debuginfo (v. 7 f 2,142
rhel-x86_64-server-7-thirdparty-oracle-java Oracle Java for RHEL Server (    48
rhel-x86_64-server-optional-7               RHEL Server Optional (v. 7 64 4,524
rhel-x86_64-server-optional-7-debuginfo     RHEL Server Optional Debuginf   423
repolist: 20,404

**Comment by cpitman** [comment]
I actually just ran into this with libffi-devel: rvm tries to enable the optional repository via `rhn-channel`, but my system is registered with subscription manager. The workaround was to manually enable the optional repo: `subscription-manager repos --enable rhel-6-server-optional-rpms`.

If you need help testing or more information about subscription-manager, I'd be glad to help.

**Comment by mpapis** [comment]
@cpitman please read this thread and add any notes related to RHSM to #3207

**Comment by kriansa** [comment]
Just my 2 cents in case anyone else needs a workaround. I was having some trouble with that, and I realized that all repos was listed inside /etc/yum.repos.d but disabled by default.

A quick `yum repolist all` will show you all repos, what you need is just enable the optional in your install command, like so:

```
# yum repolist all
...
rhui-REGION-rhel-server-optional/7Server/x86_64  Red Hat Enterprise Linux Server 7 Optional (RPMs)  disabled
...
# yum install libyaml-devel --enablerepo rhui-REGION-rhel-server-optional
```

Probably the names will differ because I'm running it on a EC2 instance, so REGION will be replaced dynamically.

**Comment by mpapis** [comment]
@kriansa I would appreciate if you could spent a bit more time with it and find a dynamic (`list | grep`) way to work with it so this could be automated for everybody - thanks

**Comment by kriansa** [comment]
Sure, @mpapis.

    # yum repolist all | \grep rhel-server-optional | sed -r 's/!([-A-Za-z]+)\/.*/\1/'
    rhui-REGION-rhel-server-optional

I'm not familiar with rvm codebase (nor I'm a bash expert), so I couldn't find a better way to implement that.
