### ISSUE TITLE
The install script does NOT work!

### ISSUE THREAD

**Issue by dallaslu** [rvm/rvm#3198]
\curl -sSL https://get.rvm.io | bash -s stable

Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.4/1.26.4.tar.gz.asc

curl: (22) The requested URL returned error: 404 Not Found

**Comment by SatyenVats** [comment]
I am trying to install rvm using "curl -sSL https://get.rvm.io | bash -s stable" nut getting these errors, can you please have a look.
bash: line 280: awk: command not found
bash: line 280: awk: command not found
Downloading https://github.com/rvm/rvm/archive/.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

Could not download 'https://github.com/rvm/rvm/archive/.tar.gz'.
  curl returned status '22'.

Downloading https://bitbucket.org/mpapis/rvm/get/.tar.gz
curl: (22) The requested URL returned error: 404 NOT FOUND

Could not download 'https://bitbucket.org/mpapis/rvm/get/.tar.gz'.
  curl returned status '22'.

**Comment by SharathKS** [comment]
I am trying to install rvm using "curl -sSL https://get.rvm.io | bash -s stable" but getting this error, can you please have a look and let me the installation steps.
bash: line 280: awk: command not found
bash: line 280: awk: command not found
Downloading https://github.com/rvm/rvm/archive/.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

Could not download 'https://github.com/rvm/rvm/archive/.tar.gz'.
  curl returned status '22'.

Downloading https://bitbucket.org/mpapis/rvm/get/.tar.gz
curl: (22) The requested URL returned error: 404 NOT FOUND

Could not download 'https://bitbucket.org/mpapis/rvm/get/.tar.gz'.
  curl returned status '22'.
