### ISSUE TITLE
RVM on SUSE 11

### ISSUE THREAD

**Issue by ricarcon** [rvm/rvm#3203]
When I try to go through and checking the requirements for RVM, I get an error:
```bash
Installing required packages: libffi-devel, libopenssl-devel..
Error running 'requirements_opensuse_libs_install libffi-devel libopenssl-devel',
showing last 15 lines of /home/rcontre1/.rvm/log/1418402259/package_install_libffi-devel_libopenssl-devel.log
}
current path: /home/rcontre1
PATH=/usr/sbin:/bin:/usr/bin:/sbin:/home/rcontre1/.rvm/bin
command(3): requirements_opensuse_libs_install libffi-devel libopenssl-devel
+ __rvm_try_sudo zypper install -y libffi-devel libopenssl-devel
+ typeset -a command_to_run
+ typeset sudo_path sbin_path missing_paths
+ command_to_run=("$@")
+ ((  UID == 0  ))
+ zypper install -y libffi-devel libopenssl-devel
Loading repository data...
Reading installed packages...
'libffi-devel' not found.
+ return 104
+ return 104
Requirements installation failed with status: 104.
```
I've exhausted my search for answers and thought I would check with the source directly. I tend to try to figure things out on my own, but I've found dead ends and am stuck. Thanks in advance!

**Comment by ricarcon** [comment]
rvm system info
 
system:
 
  system:
    uname:       "Linux RELMANGMT-KIT-D 2.6.32.29-0.3-default #1 SMP 2011-02-25 13:36:59 +0100 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "suse/11.1/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.51(1)-release (x86_64-suse-linux-gnu)"
    zsh:         "/usr/bin/zsh => zsh 4.3.6 (x86_64-suse-linux-gnu)"
 
  rvm:
    version:      "rvm 1.26.4 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "26 days 6 hours 1 minute 28 seconds ago"
    path:         "/home/rcontre1/.rvm"
 
  homes:
    gem:          "not set"
    ruby:         "not set"
 
  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          ""
    rake:         ""
 
  environment:
    PATH:         "/home/rcontre1/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games:/opt/kde3/bin:/usr/lib64/jvm/jre/bin:/usr/lib/mit/bin:/usr/lib/mit/sbin:/home/rcontre1/.rvm/bin:/home/rcontre1/.rvm/bin:/home/rcontre1/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment]
so it worked?

**Comment by ricarcon** [comment]
I don't know... I get this now when I run 'rvm requirements' :

~> sudo rvm requirements
root's password:
Checking requirements for suse.
Installing requirements for suse.
Updating system.......
Error running 'requirements_opensuse_update_system ',
showing last 15 lines of /home/rcontre1/.rvm/log/1421261289/update_system.log
Abort, retry, ignore? [a/r/i] (r): 
Trying again...
Location 'http://linuxset-repository.pdx.intel.com/repository/suse/SLES11/SP1/ia32e/content' is temporarily unaccessible.
 
Abort, retry, ignore? [a/r/i] (a): 
Trying again...
Problem retrieving files from 'SUSE-Linux-Enterprise-Server-11-SP1 11.1.1-1.152'.
Location 'http://linuxset-repository.pdx.intel.com/repository/suse/SLES11/SP1/ia32e/content' is temporarily unaccessible.
 
Please see the above error message for a hint.
Skipping repository 'SUSE-Linux-Enterprise-Server-11-SP1 11.1.1-1.152' because of the above error.
Repository 'GNU Compiler Collection container (SLE-11)' is up to date.
Some of the repositories have not been refreshed because of an error.
+ return 4
+ return 4
Requirements installation failed with status: 4.

**Comment by mpapis** [comment]
make sure this command works:
```bash
zypper --gpg-auto-import-keys refresh
```
and then get back to RVM

**Comment by havenwood** [comment]
Presuming the zypper issue has been resolved and closing. Please open a new issue if problems reoccur.

**Comment by mpapis** [comment]
it all works just fine on my OpenSUSE, should be very similar experience on SUSE boxes.
