### ISSUE TITLE
Rubygems 2.0.15 does not exist error when install Ruby 1.8.7

### ISSUE THREAD

**Issue by cnotechappell** [rvm/rvm#3218]
I'm trying to install ruby 1.8.7 head and I get an error that rubygems 2.0.15 can't be found:

curl: (22) The requested URL returned error: 404 Not Found
The requested url does not exist(22): 'http://production.cf.rubygems.org/rubygems/rubygems-2.0.15.tgz'
Checking fallback: ftp://production.cf.rubygems.org/rubygems/rubygems-2.0.15.tgz
Checking fallback: http://www.mirrorservice.org/sites/production.cf.rubygems.org/rubygems/rubygems-2.0.15.tgz
No fallback URL could be found, try increasing timeout with:

**Comment by adaiguoguo** [comment]
Thanks

**Comment by jameswilson** [comment]
Thanks! 

I had a similar problem reinstalling ruby 1.9.3 using rvm... the error was 

```
ruby-1.9.3-p484 - #downloading rubygems-2.2.3
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
The requested url does not exist(22): 'http://production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz'
```

I downloaded the tar.gz from github, and moved it to `~/.rvm/archives` as suggested by @bulletshot60 and this worked.

**Comment by MrAlexLau** [comment]
@jameswilson - that worked for me, thanks for posting!

**Comment by jasonm23** [comment]
Similar error with install 2.2.0 

```
The requested url does not exist(22): 'http://production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz'
Checking fallback: ftp://production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz
Checking fallback: http://www.mirrorservice.org/sites/production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz
No fallback URL could be found
```

**Comment by vivekck** [comment]
Trying to install ruby 2.1.5 but not able to do. It returns the following error:

The requested url does not exist(22): 'http://production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz'
Checking fallback: ftp://production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz
Checking fallback: http://www.mirrorservice.org/sites/production.cf.rubygems.org/rubygems/rubygems-2.2.3.tgz
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error while trying to fetch rubygems. 
Halting the installation.

**Comment by vivekck** [comment]
Running rvm get head solved my problem.

**Comment by vivekck** [comment]
@jasonm23 Trying running rvm get head

**Comment by vivekck** [comment]
@jasonm23 Trying running **rvm get head**
