### ISSUE TITLE
Rubinius (v2.1.1 and v2.2.10) will not build/compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by LorinRicker** [rvm/rvm#3219]
Wanting to try Rubinius on Ubuntu 14.04 (plain old boring Dell Powerspec desktop), I'm getting this failure to build/compile (first, ensure that RVM is latest-stable release):

$ rvm get stable     # succeeds  with
...
RVM reloaded!
$ rvm version
rvm 1.26.5 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

$ rvm install rbx-2.1.1
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/14.04/x86_64/rbx-2.1.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.1.1@rubinius - #regenerating binstubs..........
rbx-2.1.1 - #downloading rubinius-2.1.1, this may take a while depending on your connection...
** Resuming transfer from byte position 11626162
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  579k  100  579k    0     0   596k      0 --:--:-- --:--:-- --:--:--  596k
mkdir: created directory ‘/home/lorin/.rvm/tmp/rvm_src_12047’
rbx-2.1.1 - #extracting rubinius-2.1.1 to /home/lorin/.rvm/src/rbx-2.1.1....
ruby-2.1.1@rubinius - #bundle install...
rbx-2.1.1 - #configuring............
rbx-2.1.1 - #compiling..............................................................................................................................................
Error running '/home/lorin/.rvm/wrappers/ruby-2.1.1@rubinius/rake install --trace',
showing last 15 lines of /home/lorin/.rvm/log/1419282055_rbx-2.1.1/rake.log
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/bin/rake:23:in `load'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/bin/rake:23:in `<main>'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/bin/ruby_executable_hooks:15:in `eval'
/home/lorin/.rvm/gems/ruby-2.1.1@rubinius/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => install => build:build => vm/vm
Error: sh -c './configure --disable-builddir'

I have also tried using clang:
$ rvm install rbx-2.1.1 -- --cc=clang --cxx=clang++
...but I get identical (failed) results. 

Advice to fix?  Thank you!

**Comment by havenwood** [comment]
Closing since the original question seems answered and it's been a while. Please open a new issue if there are any problems setting or unsetting the `cd` function.
