### ISSUE TITLE
CDPATH not working

### ISSUE THREAD

**Issue by jerzygangi** [rvm/rvm#3225]
Hi @mpapis,

My CDPATH is not working. About a month ago I switched from bash to zsh+OMZ, and I believe this may be when CDPATH stopped working. Having read #1374 and https://rvm.io/support/troubleshooting, I believe RVM may be a part of the issue. Here are some details:

My .zshrc says: `export CDPATH=.:~/Sites`

But when I `echo $CDPATH` (using zsh), I see `.`

Furthermore, when I `export CDPATH=.:~/Sites` on the command line, instead of via my .zshrc file, I can `echo $CDPATH` and I see `.:/Users/jerzy/Sites`, as expected; as a result, `cd` then works as expected.

My .zshrc file is otherwise healthy. I have exported and verified that other shell variables can be set successfully.

To debug, I launched bash (instead of zsh) and sourced in a `.bashrc` file with CDPATH exported inside it. When I echo $CDPATH, it appears set, and I can `cd` successfully. Therefore, I think I can isolate this problem to .zshrc and RVM.

I'm on OS X with rvm 1.26.5 (master).

**Comment by pkuczynski** [comment]
@jerzygangi any feedback? Otherwise we will have to close this issue...
