### ISSUE TITLE
rbx 2.4.1 install errors

### ISSUE THREAD

**Issue by jzakiya** [rvm/rvm#3231]
Attempted to install rbx-2.4.1 on my PCLinuxOS (PCLOS) 32-bit distro and got errors shown below:

https://gist.github.com/jzakiya/08a167a4bd4b8b31ee22

**Comment by jzakiya** [comment]
OK. My distro upgraded llvm to from 3.4.2 to 3.5.0 (upon my request) which seems to have corrected most of the install problems with rbx-2.4.1.

I was able to upgrade from 2.2.10 to 2.4.1, though there were some errors cited in the output.

Here is the gist of the output screen dump of the upgrade.

https://gist.github.com/anonymous/7fcfc590656b876c872e

In spite of the listed errors, the upgrade finished, rbx-2.4.1 was listed under: rvm list
and I am able to do a: rvm use rbx, and run irb sessions.

Is there anything else I need to do to resolve any of the listed errors?

Here is the thread on the rubinious github listserv.

https://github.com/rubinius/rubinius/issues/3255

**Comment by mpapis** [comment]
please also gist:

- `/home/jzakiya/.rvm/log/1421011657/migrate.gemset.global.log`,
- `/home/jzakiya/.rvm/log/1421011657/gemset.pristine-rbx-2.4.1@global.log`,
- `/home/jzakiya/.rvm/log/1421011657/merge.gemset.default.log` and
- `/home/jzakiya/.rvm/log/1421011657/gemset.pristine-rbx-2.4.1.log`

(you can have multiple files in one gist)

**Comment by jzakiya** [comment]
Here is a gist of the four log files.

https://gist.github.com/jzakiya/01899930f9054d9b390d

Just to let you know, today I upgraded rvm to 1.26.9, removed the prior (working) install of rbx-2.4.1, per suggestions of rbx listserv, and then also (per their suggestion) reinstalled rbx with:

rvm install rbx-2.4.1 --rubygems ignore

and got a nice clean install with no error messages, shown below.

jzakiya@localhost ~ $ rvm install rbx-2.4.1 --rubygems ignore
rbx-2.4.1 - #removing src/rbx-2.4.1 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: pclinuxos/2015/i386/rbx-2.4.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.                       
Checking requirements for pclinuxos.
Requirements installation successful.
ruby-2.2.0@rubinius - #regenerating binstubs - please wait
rbx-2.4.1 - #downloading rubinius-2.4.1, this may take a while depending on your connection...
rbx-2.4.1 - #extracting rubinius-2.4.1 to /home/jzakiya/.rvm/src/rbx-2.4.1 - please wait
ruby-2.2.0@rubinius - #bundle install - please wait
rbx-2.4.1 - #configuring - please wait
rbx-2.4.1 - #compiling - please wait
rbx-2.4.1 - #making binaries executable - please wait
rbx-2.4.1 - #gemset created /home/jzakiya/.rvm/gems/rbx-2.4.1@global
rbx-2.4.1 - #importing gemset /home/jzakiya/.rvm/gemsets/global.gems - please wait
rbx-2.4.1 - #generating global wrappers - please wait
rbx-2.4.1 - #gemset created /home/jzakiya/.rvm/gems/rbx-2.4.1
rbx-2.4.1 - #importing gemsetfile /home/jzakiya/.rvm/gemsets/default.gems evaluated to empty gem list
rbx-2.4.1 - #generating default wrappers - please wait
jzakiya@localhost ~ $ rvm list

rvm rubies

   jruby-1.7.18 [ i386 ]
=> rbx-2.4.1 [ i686 ]
   ruby-1.8.7-p374 [ i686 ]
 * ruby-2.2.0 [ i686 ]

# => - current
# =* - current && default
#  * - default

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.
