### ISSUE TITLE
1.26.7 Warning - Unknown ruby string (do not know how to handle): ruby-2.1.4

### ISSUE THREAD

**Issue by nddeluca** [rvm/rvm#3244]
A warning is shown when using ruby 2.1.4 with rvm 1.26.7 and the error appears to have been introduced by the fix in #3234.

Here is a screen of the behavior on version 1.26.7:
![screen shot 2014-12-30 at 11 08 41 am](https://cloud.githubusercontent.com/assets/903469/5580738/a5014444-9014-11e4-8238-a0c3cc913b62.png)

Here is the screenshot on version 1.26.6:
![screen shot 2014-12-30 at 11 07 51 am](https://cloud.githubusercontent.com/assets/903469/5580735/a237e20e-9014-11e4-9d25-e3e7e53671c5.png)

Here is a gist of the commands I ran: https://gist.github.com/nddeluca/e1cd1f2384e644b2b8aa

**Comment by iconara** [comment]
I'm getting this every time I switch to JRuby:

```
$ rvm use jruby-1.7.11@jara
Unknown ruby string (do not know how to handle): jruby-1.7.11.
Using /Users/theo/.rvm/gems/jruby-1.7.11 with gemset jara
```

The error is printed, but it doesn't seem to have any significance.

**Comment by hydrogen18** [comment]
I'm basically getting this anytime I try and do something useful with RVM

```
[ericu-destroyer-of-worlds] community$ rvm version
rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
[ericu-destroyer-of-worlds] community$ rvm use jruby-1.7.9
Using /home/ericu/.rvm/gems/jruby-1.7.9
[ericu-destroyer-of-worlds] community$ rvm list

rvm rubies

=> jruby-1.7.9 [ x86_64 ]
 * ruby-2.2.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

[ericu-destroyer-of-worlds] community$ rvm gemset use community
Using jruby-1.7.9 with gemset community
Unknown ruby string (do not know how to handle): jruby-1.7.9.
[ericu-destroyer-of-worlds] community$ 

```

**Comment by iconara** [comment]
I just updated to 1.26.11 and this error is getting a bit ridiculous… when installing a new version of JRuby RVM prints the error message five times:

![screen shot 2015-05-21 at 10 29 15](https://cloud.githubusercontent.com/assets/73330/7744512/4708e702-ffa4-11e4-93d0-13b4e995422e.png)

**Comment by mpapis** [comment]
@iconara please open a new issue

**Comment by iconara** [comment]
Looks like there are two open duplicates #3292 and #3278 I will add my screenshot there. I commented on this issue since I've commented on it before and assumed that it hadn't been closed since it hasn't been fixed.

**Comment by lortega** [comment]
I'm on 1.26.11 and keeps happening

**Comment by hydrogen18** [comment]
@iconara This message is how you know it's working.
