### ISSUE TITLE
libyaml error while installing 1.9.3

### ISSUE THREAD

**Issue by Jaleelpa** [rvm/rvm#3263]
[root@image ~]# rvm install 1.9.3
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/centos/6/x86_64/ruby-1.9.3-p551.tar.bz2
Checking requirements for centos.
Installing requirements for centos.
Installing required packages: libyaml-devel....
Error running 'requirements_centos_libs_install libyaml-devel',
showing last 15 lines of /usr/local/rvm/log/1421171944_ruby-1.9.3-p551/package_install_libyaml-devel.log
           Requires: libyaml = 0.1.4-1.el6.rf
           Installed: libyaml-0.1.6-1.el6.x86_64 (@epel)
               libyaml = 0.1.6-1.el6
           Available: libyaml-0.1.3-1.el6.rf.x86_64 (rpmforge)
               libyaml = 0.1.3-1.el6.rf
           Available: libyaml-0.1.3-1.4.el6.i686 (base)
               libyaml = 0.1.3-1.4.el6
           Available: libyaml-0.1.3-2.el6.art.x86_64 (atomic)
               libyaml = 0.1.3-2.el6.art
           Available: libyaml-0.1.4-1.el6.rf.x86_64 (rpmforge)
               libyaml = 0.1.4-1.el6.rf
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
++ return 1
++ return 1
Requirements installation failed with status: 1.

Any thoughts?

Thanks

**Comment by mpapis** [comment]
please [gist](https://gist.github.com) `/usr/local/rvm/log/1421171944_ruby-1.9.3-p551/package_install_libyaml-devel.log`

**Comment by Jaleelpa** [comment]
https://gist.github.com/Jaleelpa/5f05b72e89cdc057e5d6

**Comment by mpapis** [comment]
try this https://github.com/wayneeseguin/rvm/issues/3206#issuecomment-70092490 : 
```bash
yum downgrade libyaml
yum install libyaml-devel
```

**Comment by myoung34** [comment]
The original issue looks like a side effect of having rpmforge and epel installed simultaneously, which is not recommended

* http://beginlinux.com/server/centos/centos-6-rpmforgeepel-repositories
* http://serverfault.com/questions/209046/centos-repositories-epel-or-rpmforge-which-one-is-better-and-why
* http://unix.stackexchange.com/questions/50657/is-it-stable-to-use-epel-and-rpmforge-in-the-same-time

**Comment by havenwood** [comment]
@myoung34 Thanks for the links!
