### ISSUE TITLE
Fish fails to load the as-default defined Ruby version

### ISSUE THREAD

**Issue by Moter8** [rvm/rvm#3265]
https://rvm.io/integration/fish

[rvminfo.txt](https://gist.github.com/Moter8/864b10e962f258f3ab77)
[rvmlist.txt](https://gist.github.com/Moter8/2250a3f9a206cdbac54c)

Right after installing RVM/Ruby 2.1.5 I executed `rvm use 2.1.5 --default`. This only gets preserved for bash but not for fish.

The default doesn't seem to be handled at all.

**Comment by havenwood** [comment]
@Moter8 After running `rvm default` does the default work for you in Fish? If so, you could add `rvm default` to your config.fish file:
```bash
echo "rvm default" >> ~/.config/fish/config.fish
```

**Comment by havenwood** [comment]
The [Fish setup page](https://rvm.io/integration/fish#setup) now show how to manually set the default Ruby in the `config.fish` file.
