### ISSUE TITLE
Can't compile rubinius

### ISSUE THREAD

**Issue by brauliobo** [rvm/rvm#3287]
Please check https://github.com/rubinius/rubinius/issues/3304

**Comment by brauliobo** [comment]
seems to be related to llvm 3.5 present on ubuntu

**Comment by brauliobo** [comment]
`llvm-3.5-dev` needs to be installed by rvm

**Comment by brauliobo** [comment]
`libedit-dev` should also be installed to fix `/usr/bin/ld: can't find library -ledit'`

**Comment by brauliobo** [comment]
And finally, compilation will error if compiled with gcc. `--cc=clang --cxx=clang++` must be used.

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.
