### ISSUE TITLE
"Unknown ruby string (do not know how to handle)" when specifying Ruby version w/a gemset

### ISSUE THREAD

**Issue by ctash** [rvm/rvm#3292]
I'm getting an "Unknown ruby string (do not know how to handle)" error when I attempt to specify a Ruby version with a gemset.

``` ShellSession
$ rvm --version
rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

$ rvm list

rvm rubies

=* jruby-1.7.2 [ x86_64 ]
   ruby-1.9.3-p551 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

$ rvm use jruby-1.7.2
Using /Users/my_name/.rvm/gems/jruby-1.7.2

$ rvm use jruby-1.7.2@my_gemset_name
Unknown ruby string (do not know how to handle): jruby-1.7.2.
Using /Users/my_name/.rvm/gems/jruby-1.7.2 with gemset my_gemset_name
```

environment: Mac OS X, bash

**Comment by fallwith** [comment]
I just encountered this as well.

That error will be thrown if the ruby version you specify is not contained in `(rvm_home)/config/known_strings)` (ex: `~/.rvm/config/known_strings`). For now you can update that file and insert your desired version.

It looks like if you are using the latest version of rvm, you will receive that error for all JRubies other than v1.7.19.

To reproduce the error, use any 1.x JRuby that is not 1.7.19:
  ```
  %> rvm instal jruby-1.7.18
  %> rvm use jruby-1.7.18
  %> rvm gemset create mygemset
  %> rvm jruby-1.7.18@mygemset do ls
  ```

**Comment by ctash** [comment]
@fallwith - thanks, that worked

**Comment by iconara** [comment]
I just updated to 1.26.11 and this error remains:

![screen shot 2015-05-21 at 10 29 15](https://cloud.githubusercontent.com/assets/73330/7749903/2109c774-ffd1-11e4-8a5c-6b64dd379c9c.png)

```
~% rvm --version
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

This is on Mac OS X 10.10.4.

**Comment by sam2000** [comment]
I am getting the same when I try to install the latest Jruby using 
rvm install jruby-9.1.2.0
I am getting 
"Unknown ruby string (do not know how to handle): jruby-9.1.2.0."

Here is a copy of what I see on Terminal (OSX 10.11.5)
`rvm install jruby-9.1.2.0
Unknown ruby string (do not know how to handle): jruby-9.1.2.0.
Unknown ruby string (do not know how to handle): jruby-9.1.2.0.
Searching for binary rubies, this might take some time.
Unknown ruby string (do not know how to handle): jruby-9.1.2.0.
Unknown ruby string (do not know how to handle): jruby-9.1.2.0.
Found remote file https://s3.amazonaws.com/jruby.org/downloads/9.1.2.0/jruby-bin-9.1.2.0.tar.gz
Checking requirements for osx.
Requirements installation successful.
jruby-9.1.2.0 - #configure
Unknown ruby string (do not know how to handle): jruby-9.1.2.0.
jruby-9.1.2.0 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 31.0M  100 31.0M    0     0  6440k      0  0:00:04  0:00:04 --:--:-- 6720k
No checksum for downloaded archive, recording checksum in user configuration.
jruby-9.1.2.0 - #validate archive
jruby-9.1.2.0 - #extract
jruby-9.1.2.0 - #validate binary
jruby-9.1.2.0 - #setup
jruby-9.1.2.0 - #gemset created /Users/sumuhanumamaheswarampillai/.rvm/gems/jruby-9.1.2.0@global
jruby-9.1.2.0 - #importing gemset /Users/sumuhanumamaheswarampillai/.rvm/gemsets/jruby/global.gems..
jruby-9.1.2.0 - #generating global wrappers........
jruby-9.1.2.0 - #gemset created /Users/sumuhanumamaheswarampillai/.rvm/gems/jruby-9.1.2.0
jruby-9.1.2.0 - #importing gemsetfile /Users/sumuhanumamaheswarampillai/.rvm/gemsets/default.gems evaluated to empty gem list
jruby-9.1.2.0 - #generating default wrappers........
`

**Comment by sam2000** [comment]
Just noticed  latest versions of Jruby are not listed in available rubies 
The latest is 9.1.2.0
But rvm seems to be stuck at 9.0.5.0

![screen shot 2016-06-12 at 10 38 01](https://cloud.githubusercontent.com/assets/1000132/15990434/19dc337a-308a-11e6-8e97-24d5224e8dcf.png)

**Comment by gbirchmeier** [comment]
I'm seeing this problem with rvm 1.27.0 and `rvm install jruby-1.7.25`, the latest stable versions of both.

My output is nearly identical to @iconara's screenshot, so I'll refrain from posting more of the same.

**Comment by mPanasiewicz** [comment]
Hello, any solution for that problem. I've got the same problem

**Comment by karuppasamy** [comment]
By adding the version (`jruby-xxxx`) which is in the error message into the file `known_strings` will solve the problem. It's a temporary fix only.

**Comment by gacha** [comment]
`rvm get head` fixed this by populating the `known_strings` with the latest jruby versions. The usual `rvm get stable` did not work, it did not have the latest versions.
