### ISSUE TITLE
You're running a version of ruby with no Readline support

### ISSUE THREAD

**Issue by shareef786** [rvm/rvm#3294]
Hi,

I have installed ruby 2.0.0 with rvm, when i run any rake command i am facing the issue

You're running a version of ruby with no Readline support
Please `gem install rb-readline` or recompile ruby --with-readline.

After install the gem also getting same error.

Any help would be appreciated.
Thanks in Advance.

**Comment by havenwood** [comment]
Sorry for the long delay before a response. Try updating RVM with `rvm get stable`, `rvm autlolibs enable` and reinstall Ruby 2.0.0.

**Comment by havenwood** [comment]
Closing since this was an issue with a `readline` package dependency needing to be installed.
