### ISSUE TITLE
Error while runnning bundle install

### ISSUE THREAD

**Issue by rajkiran** [rvm/rvm#3298]
Hi, while i am running bundle install i am getting the following error:

** Person-Mini:empmanagement krishna$ bundle install
Error loading RubyGems plugin "/Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": dlopen(/Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin11.0/openssl.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin11.0/openssl.bundle
  Reason: image not found - /Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin11.0/openssl.bundle (LoadError)
/Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': dlopen(/Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin11.0/digest/sha1.bundle, 9): Library not loaded: /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (LoadError)
  Referenced from: /Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin11.0/digest/sha1.bundle
  Reason: image not found - /Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/x86_64-darwin11.0/digest/sha1.bundle
	from /Users/krishna/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/definition.rb:1:in `<top (required)>'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler.rb:155:in `definition'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/cli/install.rb:77:in `run'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/cli.rb:145:in `install'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/vendor/thor/command.rb:27:in `run'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_command'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/vendor/thor.rb:363:in `dispatch'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/vendor/thor/base.rb:440:in `start'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/cli.rb:9:in `start'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/bin/bundle:20:in `block in <top (required)>'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/lib/bundler/friendly_errors.rb:5:in `with_friendly_errors'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/gems/bundler-1.7.12/bin/bundle:18:in `<top (required)>'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/bin/bundle:23:in `load'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/bin/bundle:23:in `<main>'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/krishna/.rvm/gems/ruby-2.1.5@global/bin/ruby_executable_hooks:15:in `<main>'
**

Please pull me from this issue.

**Comment by gerep** [comment]
Can you please try removing and installing *openssl* again?

```
brew remove openssl
brew install openssl
```

**Comment by havenwood** [comment]
Closing on the presumption this does work after rebuilding Ruby. Please open a new issue if this problem reoccurs.
