### ISSUE TITLE
Possible RVM issue asking to run `bundle install` first

### ISSUE THREAD

**Issue by DaniG2k** [rvm/rvm#3301]
I've posted this as an [issue in Bundler](https://github.com/bundler/bundler/issues/3384) as I thought it was an error with Bundler, but apparently it's not.

When I run `rails c` in development I am getting the message:

    git://github.com/radar/by_star (at master) is not yet checked out. Run `bundle install` first.

No matter how many times I run `bundle install`, I keep getting the same error message.
I've asked for some help on IRC and someone suggested I remove the following lines from **/myapp/bin/rails** (marked with "-"):

    #!/usr/bin/env ruby
    -begin
    -  load File.expand_path("../spring", __FILE__)
    -rescue LoadError
    -end
    APP_PATH = File.expand_path('../../config/application',  __FILE__)
    require_relative '../config/boot'
    require 'rails/commands'

This leads me to think that this is a Spring issue. However, that setup is how spring works, and since I updated RVM recently I think this might be more related to RVM than to Spring (which I haven't changed in a while).

Some useful info:

    $ rails -v
    Rails 4.2.0
    $ bundle exec rails c
    git://github.com/radar/by_star (at master) is not yet checked out. Run `bundle install` first.
    $ rvm info
    Warning! PATH is not properly set up, '/Users/dani/.rvm/gems/ruby-2.2.0/bin' is not at first place,
             usually this is caused by shell initialization files - check them for 'PATH=...' entries,
             it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
             to fix temporarily in this shell session run: 'rvm use ruby-2.2.0'.

    ruby-2.2.0:

      system:
        uname:       "Darwin Danieles-MacBook-Pro-2.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64"
        system:      "osx/10.10/x86_64"
        bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin14)"
        zsh:         "/bin/zsh => zsh 5.0.5 (x86_64-apple-darwin14.0)"

      rvm:
        version:      "rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
        updated:      "1 hour 43 minutes 6 seconds ago"
        path:         "/Users/dani/.rvm"

      ruby:
        interpreter:  "ruby"
        version:      "2.2.0p0"
        date:         "2014-12-25"
        platform:     "x86_64-darwin14"
        patchlevel:   "2014-12-25 revision 49005"
        full_version: "ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]"

      homes:
        gem:          "/Users/dani/.rvm/gems/ruby-2.2.0"
        ruby:         "/Users/dani/.rvm/rubies/ruby-2.2.0"

      binaries:
        ruby:         "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/ruby"
        irb:          "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/irb"
        gem:          "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/gem"
        rake:         "/Users/dani/.rvm/rubies/ruby-2.2.0/bin/rake"

      environment:
        PATH:         "/usr/local/bin:/Users/dani/.rvm/gems/ruby-2.2.0/bin:/Users/dani/.rvm/gems/ruby-2.2.0@global/bin:/Users/dani/.rvm/rubies/ruby-2.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dani/.rvm/bin:/Applications/Postgres.app/Contents/Versions/9.4/bin"
        GEM_HOME:     "/Users/dani/.rvm/gems/ruby-2.2.0"
        GEM_PATH:     "/Users/dani/.rvm/gems/ruby-2.2.0:/Users/dani/.rvm/gems/ruby-2.2.0@global"
        MY_RUBY_HOME: "/Users/dani/.rvm/rubies/ruby-2.2.0"
        IRBRC:        "/Users/dani/.rvm/rubies/ruby-2.2.0/.irbrc"
        RUBYOPT:      ""
        gemset:       ""

Any help is much appreciated!

**Comment by DaniG2k** [comment]
I've tried to reinstall rvm, reinstall ruby, reinstall rails, reinstall all gems, ran bundle install, ran bundle update......still same error message :disappointed:

To reproduce: create a new rails 4.2 project, run `rails c` to make sure spring is started, add a git gem to my Gemfile (like `gem 'by_star', :git => "git://github.com/radar/by_star"`), run `bundle install` and then try to use any spring-related command. This seems to be a git-gem issue with bundler and spring. :confused:

**Comment by treble37** [comment]
Did you try running ["spring stop"](https://github.com/bundler/bundler/issues/3384#issuecomment-73767779) per the commenter?

**Comment by mpapis** [comment]
try after `rvm use ruby-2.2.0`

**Comment by havenwood** [comment]
Closing as presumed-resolved since it appears to be an upstream issue where several folk have mentioned fixing it with a `spring` command.
