### ISSUE TITLE
public key verification - .asc contents not matching

### ISSUE THREAD

**Issue by recunius** [rvm/rvm#3302]
I imported your public key. The fingerprint of the mpapis key I imported is matching the fingerprint on https://keybase.io/mpapis. However, the contents of the armored public key are not:

Steps to Reproduce:
* gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
> gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
> gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
> gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
> gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
> gpg: next trustdb check due at 2020-02-12
> gpg: Total number processed: 1
> gpg:               imported: 1  (RSA: 1)

* gpg2 --list-keys --fingerprint
> pub   4096R/D39DC0E3 2014-10-28
>      Key fingerprint = 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
> uid                  Michal Papis (RVM signing) <mpapis@gmail.com>
> sub   4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]

* gpg2 --armor --export mpapis@gmail.com
> -----BEGIN PGP PUBLIC KEY BLOCK-----
> Version: GnuPG v2.0.22 (GNU/Linux)
> 
> mQINBFRQA8EBEADrLHxW4807EJMzDjhrR5+FRy5/3616nyLlbWFTLnS1/i514L7Z
> LVzbho4eZWjErRWqT1mr+E7dr/c8Ei5J8kUMqm5MoSkCoc5Y7Gp0jKhfDF4Megpd
> X2ZKw7VG+4GZU9gxbm+6ymHeDAFRfQjUoHzCZsdsgnhi1C58kMoY39dFidlk24AG
> E7y8WEg42yzSyJFjK5+qdGuKTBK4UmYM3uxHbxZgBLZ1PQ9DhsToauTqQSJEFzC+
> r4qQeO6CeZAUEhgCt3HnmKE8hdARQelNRICrQc/Gpd3c3Wcpi3zj61cRqTCDBtNJ
> h66bN+b6MilfT1S+9YMqLACXIWRcXPPUUWanmleguzGfngRjr/qf2PF6g2HYsp40
> ....
> 2v5rmXmsv6dPS/qlTJrSiRZzU5l2m/shqK3fAJGrajuNhMlO2D9+utrtuz/jGPvb
> 6mJyiQjoX+wEqSo55Fk9nk0UpWUMTn8Av9vcWTRxK54S6yktfzrZM4sOudImwZuR
> ff8GOW2oiAJntzaQ/OqnUFUWNTN94lCmYE4NdKlX/02/FAilRJdQ+XY7upNs8Cy0
> g9PT4+y3M3FyyATOaugHszu1OAq6
> =QtCH
> -----END PGP PUBLIC KEY BLOCK-----

The beginning of the armored keys match, but by the end of the output they do not.

Am I doing something wrong when comparing or do the full keys not match?

The public key I imported does verify the installer when running these commands
> curl -O https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer
> curl -O https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
> gpg --verify rvm-installer.asc

As a test I've created my own RSA key using "gpg2 --gen-key" of type RSA and RSA and when I export and import the public key on different machines they are identical.

**Comment by mpapis** [comment]
can you [gist](https://gist.github.com) both keys for better comparison? did you trust the key ? - it could influence the output.

**Comment by recunius** [comment]
I trusted the pubic key ultimately (choice 5) but the exported public key remains identical.

Here is the diff of the output in gist: https://gist.github.com/recunius/a59e8d3ccd58fc18fdd2/revisions

**Comment by recunius** [comment]
I just loaded your public key from https://rvm.io/mpapis.asc

If I load that key then the asc matches the one on https://keybase.io/mpapis

So it looks like the on hkp://keys.gnupg.net is different yet provides the same signature?

**Comment by richo** [comment]
Yes, the exported key can include different sigs, updated subkeys, etc. They don't need to be identical.

**Comment by recunius** [comment]
I see. In this case the subkeys are identical but I do see different signers.

From hkp://keys.gnupg.net:
gpg --list-sigs mpapis@gmail.com
pub   4096R/D39DC0E3 2014-10-28
uid                  Michal Papis (RVM signing) <mpapis@gmail.com>
sig       X  CA57AD7C 2014-11-19  [User ID not found]
sig       X  CA57AD7C 2014-12-02  [User ID not found]
sig       X  CA57AD7C 2015-01-11  [User ID not found]
sig          CA57AD7C 2015-02-07  [User ID not found]
sig          75C9B050 2014-12-15  [User ID not found]
sig 3        D39DC0E3 2014-10-28  Michal Papis (RVM signing) <mpapis@gmail.com>
sub   4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]
sig          D39DC0E3 2014-10-28  Michal Papis (RVM signing) <mpapis@gmail.com>

From https://rvm.io/mpapis.asc:
pub   4096R/D39DC0E3 2014-10-28
uid                  Michal Papis (RVM signing) <mpapis@gmail.com>
sig 3        D39DC0E3 2014-10-28  Michal Papis (RVM signing) <mpapis@gmail.com>
sub   4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]
sig          D39DC0E3 2014-10-28  Michal Papis (RVM signing) <mpapis@gmail.com>

It would make sense that gnpug.net would add signers to the key.

Sorry for the bother.

**Comment by mpapis** [comment]
@recunius it's a task for me to import those extra signatures and to push updated version ... now to find instructions for it :)

**Comment by dpelletier** [comment]
Hello, I am somewhat new to gpg, but when adding your key I see a message about 'no ultimately  trusted keys found'.  (See screenshot please).  Also, although I closed the terminal window before capturing the message - I also received a message about the signer could not be verified as the owner??

Thanks in advance

![screenshot from 2015-02-21 17 02 30](https://cloud.githubusercontent.com/assets/1237566/6316930/a2ba0a48-b9ec-11e4-9242-595e2e257e8c.png)

**Comment by mpapis** [comment]
@dpelletier the last line says all: `GPG verified '/home/dmpelletier/.rvm/archives/rvm-installer'` - if you still have doubts - open a new ticket
