### ISSUE TITLE
rhn-channel not found

### ISSUE THREAD

**Issue by ror6ax** [rvm/rvm#3304]
Hi guys,
I want to use rvm on RHEL system which has to rhn subscription(not my decision :) )
Is that even possible?

If not, what am I to do with `You don't have write permissions for the /usr/local/lib/ruby/gems/1.9.1 directory.` problems ?

**Comment by mpapis** [comment]
for RHSM check https://github.com/wayneeseguin/rvm/issues/3207 
for `You don't have write permissions for the /usr/local/lib/ruby/gems/1.9.1 directory` - can you provide more details? especially the commands you used and all output

**Comment by ror6ax** [comment]
#3207 is cryptic to me, sorry. 
1.Can rvm be used without rhn-channel availible?
2.If so, how do I do it?

**Comment by edestecd** [comment]
I'm having issues relate to this as well.
When I try to install rubies on a fresh install of OracleLinux without rhn, it outputs
Unable to locate SystemId file. Is this system registered?
And prompts for a username.  Can we opt out of using rhn or make this smarter?

**Comment by ror6ax** [comment]
@mpapis - I installed rhn and issued `rvm install  2.2.0`, nothing fancy

**Comment by ror6ax** [comment]
I did not look into the code, but since RVM workd on Ububnu - you are not tied to rhn as a transport. Maybe having a switch on rhel-like machines, allowing user to use rvm or not, would be a good thing...

**Comment by mpapis** [comment]
@ror6ax I'm sorry but I can not help you much => http://niczsoft.com/2015/02/changes-in-my-open-source-life/

you can disable autolibs with: `rvm autolibs read-only`

**Comment by ror6ax** [comment]
@mpapis No problem, man. I'm in Wroclaw, btw :)
