### ISSUE TITLE
Report libraries needed in a machine readable format

### ISSUE THREAD

**Issue by docwhat** [rvm/rvm#3310]
When using `rvm --autolibs=read-fail requirements <ruby-version>` the output isn't machine readable.

Can a new flag be added to support machine readers (e.g. Chef, Puppet, etc.)?  @mpapis suggested `--strings`.

## Context

This came up because in the fnichol/chef-rvm cookbook there is a list of dependencies that have to be maintained.  But RVM itself *knows* these requirements and should be able to report them to Chef so it can install them.

See fnichol/chef-rvm/pull/261 for the full context.

**Comment by rys** [comment]
I've had a go at this. I'm not entirely sure if making rvm_log respect the --quiet flag is a good idea (might break some uses of rvm in the wild), but it's needed if you want the only thing to be printed is the missing packages list.

Just waiting for the Travis build to pass and then I'll push to master and let you know the flags you need.

**Comment by rys** [comment]
Update to latest rvm head and then:

`rvm --autolibs=read-fail --list-missing-packages --quiet requirements <ruby-version>`

I didn't like `--strings` since it's too generic.

**Comment by docwhat** [comment]
I'll take it for a spin after dinner. 

The `--quiet` flag seems... Misleading. 

How about `--undecorated` or `--machine-format`?

**Comment by docwhat** [comment]
@rys 

The output looks fine. Can I suggest using newlines instead of spaces? I don't think any *current* packaging systems support spaces in their names, but someday in the future it might. :-/

**Comment by rys** [comment]
I did consider alternatives to quiet, but it fits the existing rvm internal semantics and we had it already, I just plugged it in to more places. It's not used to manipulate the list of packages you want (`--list-missing-packages` is the new flag what gives you that), but to suppress the unrelated output from rvm before and after the package list, so you don't have to ignore those message or parse around them.

I can make it newline at the end of each package, will do that soon.

**Comment by docwhat** [comment]
Can you make --list-missing-package auto include --quiet?

**Comment by docwhat** [comment]
Oh. And for Chef at least, we don't need only missing. Getting the whole list is fine and maybe even desirable.

**Comment by rys** [comment]
I've pushed the commit to make `--list-missing-packages` include `--quiet` as well. Spitting out the full list of build packages will take a little bit more work, and I'll get that done on a different flag.

**Comment by rys** [comment]
I've added `--list-installed-packages` and `--list-all-packages`, the latter combining both missing and installed. Just waiting for the tests to pass on Travis and then I'll merge to master.

**Comment by rys** [comment]
Merged. Give `rvm --autolibs=read-fail --list-all-packages --quiet requirements <ruby-version>` a try.

**Comment by docwhat** [comment]
Looks good, but now all the `--list-<foo>-packages` flags return the `-all-` output (e.g. it includes bash, which is installed).

Also, thanks for removing the `--quiet` requirement.

**Comment by havenwood** [comment]
Closing now that `rvm --autolibs=read-fail --list-all-packages --quiet requirements` is working. Please open a new issue for any addtional feature requests or fixes.
