### ISSUE TITLE
Ruby 2.2.0 and 2.2.1 precompiled binaries

### ISSUE THREAD

**Issue by BrianHawley** [rvm/rvm#3325]
It would help us for there to be Ruby 2.2.0 and 2.2.1 precompiled binaries for the platforms we use: CentOS and various versions of OS X. In particular, the binaries at https://rvm_io.global.ssl.fastly.net/binaries/centos/ and https://rvm_io.global.ssl.fastly.net/binaries/osx/ leave off at 2.1.5. Travis CI only has a comprehensive set of OS X binaries for version 10.9, which they use on their servers, but we also use 10.8 and 10.10.

Could someone make 2.2.0 and 2.2.1 builds for CentOS and OS X on https://rvm_io.global.ssl.fastly.net/binaries/ or provide instructions on how to make and contribute such builds?

We only have CentOS 6.3 here, and I notice that the existing builds tend to have the same set of Ruby versions for each CentOS version, so making builds for other versions might be better done by people who already have them installed. We have machines with OS X 10.10, 10.9, 10.8, and likely 10.7 too, so we'd be better equipped to make precompiled binaries for all of those, with the right instructions.

**Comment by jimmycliff** [comment]
Hi @BrianHawley , 
Have you checked here for instructions to build binaries:
https://github.com/rvm/rvm-binary
I'm not sure how we get the binaries up on https://rvm_io.global.ssl.fastly.net/binaries/. If it is a manual process or if we have a build job that does that.

**Comment by BrianHawley** [comment]
Thanks for the link. It doesn't support the OSes we use but maybe it can be expanded to support them, or I'll just read the source for hints. I'm still interested in how to get the stuff contributed so other people don't have to go through the same issues.

**Comment by jrgifford** [comment]
@bradediger Hi! Maintainer of rvm-binary here.

I don't have it on my work laptop, but I have a branch that I'm working on that will include CentOS 6.3.

OS X is a little tricky, but definitely something that can be investigated.

**Comment by BrianHawley** [comment]
Thanks @jrgifford, be sure to let me know.

IIRC it should be legal to virtualize OS X on another OS X box. I don't know much about vagrant, but if it works on OS X then that might work. If all else fails we can just set aside a stack of Mac Minis, one for each OS X version, and set them up as Jenkins nodes.

**Comment by BrianHawley** [comment]
Changing the above to also include 2.2.1 now that it's out. Faster creation of precompiled binaries...

**Comment by BrianHawley** [comment]
CentOS now seems to have 2.2.0 and 2.2.1 precompiled binaries. 2.0.0-p643 is still missing.

**Comment by jrgifford** [comment]
@BrianHawley Ok, so I didn't add 2.0.0, but I can add that to the build list.

**Comment by BrianHawley** [comment]
@jrgifford thanks, I'll close this issue as soon as 2.0.0-p643 is there. It's the last main 2.0 release.

**Comment by joefiorini** [comment]
FWIW, came across this article about setting up OSX guests in Vagrant.

http://www.skoblenick.com/vagrant/vmware-fusion/creating-an-osx-base-box/

**Comment by havenwood** [comment]
@BrianHawley It was a bit of a yak shave but I've added additional OS X [binaries](https://rvm.io/binaries/osx/) and [checksums](https://github.com/wayneeseguin/rvm/pull/3359) for Ruby versions including 2.0.0-p643, 2.2.0 and 2.2.1.

**Comment by BrianHawley** [comment]
@havenwood thanks! That will help us for where we can upgrade to the latest version. All that's missing is 2.0.0-p643 on CentOS now.

**Comment by joefiorini** [comment]
@havenwood Thanks for uploading this! It's helping me out a lot with [joefiorini/vruby](https://github.com/joefiorini/vruby)!

**Comment by BrianHawley** [comment]
Closing this. I'll make a new issue for the newer versions.
