### ISSUE TITLE
rvm fails on ./configure ruby 2.2.0 with configure: error: something wrong with CFLAGS="-g -O2 "

### ISSUE THREAD

**Issue by joelxxx** [rvm/rvm#3354]
Yosemite 10.10.2
Xcode 6.2 6C131e
$ cc --version
	Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
	Target: x86_64-apple-darwin14.1.0
	Thread model: posix

$ \curl -L https://get.rvm.io | bash -s stable --ruby
.....
Installing Ruby from source to: /Users/JoelS/.rvm/rubies/ruby-2.2.0, this may take a while depending on your cpu(s)...
.....
ruby-2.2.0 - #configuring......
Error running './configure --prefix=/Users/JoelS/.rvm/rubies/ruby-2.2.0 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl --disable-install-doc --enable-shared',
showing last 15 lines of /Users/JoelS/.rvm/log/1426869650_ruby-2.2.0/configure.log
checking for sys/stat.h... no
checking for stdlib.h... no
checking for string.h... no
checking for memory.h... no
checking for strings.h... no
checking for inttypes.h... no
checking for stdint.h... no
checking for unistd.h... no
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... no
checking for cd using physical directory... cd -P
checking whether CFLAGS is valid... no
configure: error: something wrong with CFLAGS="-g -O2 "
There has been an error while running configure. Halting the installation.

Homebrew install of ruby 2.2 went fine but I'd like to use rvm.
$ which ruby
/usr/local/bin/ruby
$ ruby --version
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]

**Comment by havenwood** [comment]
Is your `CC` environment variable set to Homebrew's `apple-gcc42`? Check `printenv CC` and if it it's set remove that line from your dotfiles.

**Comment by joelxxx** [comment]
CC is not set.
Should it be?

$ printenv CC
$ echo $CC

$

**Comment by havenwood** [comment]
Nope, it doesn't need to be set. Seems I was barking up the wrong tree. This just reminded me of a similar issue that cropped up prior to `apple-gcc42` being removed from the list of CC candidates in Ruby 2.1.5. Prefixing or exporting `CC=/usr/bin/gcc` or `CC=clang` was actually a workaround for that issue.

**Comment by joelxxx** [comment]
I tried prefixing and exporting and neither of those worked.
This one seems to be different than what others have run into.

**Comment by d4rky-pl** [comment]
Could you please share `/Users/JoelS/.rvm/log/1426869650_ruby-2.2.0/configure.log` as a gist?

**Comment by joelxxx** [comment]
Thanks d4rky-pl.   Here you go.   
https://gist.github.com/9a227f148f1886889ef7.git

**Comment by davidrekow** [comment]
Also encountering this problem on Yosemite 10.10.3 w/ Xcode 6.3 (6D570).

**Comment by ninjz** [comment]
@joelxxx I can confirm, I ran `CC=/usr/bin/gcc rvm install 2.2.0` and was able to complete the install and bypass this issue. If not using rvm, just prefix with `CC=/usr/bin/gcc` whatever command you are using to install the ruby version.
