### ISSUE TITLE
Bundler is not installed after fresh RVM installation

### ISSUE THREAD

**Issue by renatojf** [rvm/rvm#3366]
I just installed RVM with 

curl -L https://get.rvm.io | bash -s stable

After it, I ran the source command, installed my ruby version and when I entered the project I got this message:

The program 'bundle' is currently not installed. You can install it by typing:
sudo apt-get install bundler

I just formatted my machine and this is the first thing I'm doing in it, so my system is clean, the installation of RVM is clean and still, I can't solve this problem unless I install bundler manually. But if I install it manually, my PATH gets scrambled and I start getting warnings from RVM saying that my PATH isn't right and I should use 'rvm use **version**" all the time.

Can someone help me with this?

**Comment by havenwood** [comment]
Use the command `gem install bundler` to install the Bundler gem.

The `apt-get` gem packages are for use with the system Ruby that's installed through `apt-get`. To install gems for RVM Rubies first select the Ruby with `rvm use ...`, then `gem install ...` without `sudo`. Here's a bit of reading on [RubyGems and RVM](https://rvm.io/rubies/rubygems).

**Comment by renatojf** [comment]
The thing is, according to this https://rvm.io/integration/bundler

There is no need to do anything to make bundler work with RVM

RVM automatically installs rubygems-bundler. I never had to install bundler manually to make it work.

**Comment by havenwood** [comment]
Bundler was introduced as a default global gem in RVM 1.9.1 but is [no longer amongst the default global gems](https://github.com/wayneeseguin/rvm/blob/master/gemsets/global.gems) as of RVM 1.26.11.

**Comment by renatojf** [comment]
Ok. That explains a lot.
Thank you very much.

**Comment by TigerWolf** [comment]
Is there a way to add a script that will install bundler on every new ruby install?

**Comment by rossshannon** [comment]
@TigerWolf As of RVM 1.29.4 (https://github.com/rvm/rvm/releases/tag/1.29.4), `bundler` comes as default again.
