### ISSUE TITLE
A whitespace snuck into rubygems' initialization call.

### ISSUE THREAD

**Issue by digitalextremist** [rvm/rvm#3367]
This was originally posted as jruby/jruby#2753 but was traced by @headius and is outside jruby.

> When GEM_PATH is empty, someone is setting it to a space character.

That lead to `GEM_PATH` being ' ' at the install of `jruby-head` for example, while installing rubygems.

**Comment by d4rky-pl** [comment]
Could not reproduce this error on `rvm 1.26.11 (master)`. Could you please make sure this bug is still present?

**Comment by digitalextremist** [comment]
Hmmm. I'm using `1.26.11` and tried `rvm reinstall jruby-head` now, and got this:

```
Making gemset jruby-head pristine...................................................................
Error running '__rvm_with jruby-head gemset_pristine',
showing last 15 lines of /home/de/.rvm/log/1429922617_jruby-head/gemset.pristine-jruby-head.log
++ _failed+=("${_gem} --version ${_version}")
++ read _gem _version _platforms
++ ((  1 > 0  ))
++ rvm_error '\n'\''command gem pristine --extensions  --version '\'' failed, you need to fix this gems manually.'
++ rvm_pretty_print stderr
++ case "${rvm_pretty_print_flag:=auto}" in
++ case "${TERM:-dumb}" in
++ case "$1" in
++ [[ -t 2 ]]
++ return 1
++ printf %b '\n'\''command gem pristine --extensions  --version '\'' failed, you need to fix this gems manually.\n'

'command gem pristine --extensions  --version ' failed, you need to fix this gems manually.
++ return 1
++ return 1
```

**Comment by d4rky-pl** [comment]
Could you please post the `/home/de/.rvm/log/1429922617_jruby-head/gemset.pristine-jruby-head.log` file as a gist?

**Comment by digitalextremist** [comment]
@d4rky-pl here you go: https://gist.github.com/digitalextremist/0d4c1b25aba65a0a373d

**Comment by pkuczynski** [comment]
Is this still reproducible with `rvm get master`?
