### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by mpapis** [rvm/rvm#3368]
start with http://contributor-covenant.org/
some good points https://adainitiative.org/2014/02/howto-design-a-code-of-conduct-for-your-community/

**Comment by martinisoft** [comment]
Suggest we start with the Contributor Covenant, maybe even add in a little more info on contacting the current maintainers?

**Comment by CoralineAda** [comment]
+1

**Comment by havenwood** [comment]
I propose forking [Rust's Code of Conduct](http://www.rust-lang.org/conduct.html). It is somewhat IRC-focused but that might be appropriate for RVM where the majority of community interaction is via IRC and Github.

Or is there another Code of Conduct that is preferable as a jumping-off point?

**Comment by havenwood** [comment]
@martinisoft Oops, I read what you wrote as "a contributor covenant" when you said "the Contributor Covenant." The Contributor Covenant with information on how to contact maintainers on IRC or via Github sounds good to me!

**Comment by zph** [comment]
Constantly impressed w/ `RVM`'s dedication to looking after users :).

**Comment by CoralineAda** [comment]
Thanks for doing this!

**Comment by havenwood** [comment]
RVM now adheres to the Contributor Code of Conduct. Closed by 86b5579fae2b3a7f2474b39362909697c6b3d128.
