### ISSUE TITLE
ubuntu SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

### ISSUE THREAD

**Issue by CirrusThink** [rvm/rvm#3369]
I am having these issues on both an ubuntu and a centos server. 
I see instructions for osx but not for other platforms is that correct ?

**Comment by havenwood** [comment]
Try [installing the ca-certificates package](https://rvm.io/support/fixing-broken-ssl-certificates#linux) with apt and yum. That should fix missing CA bundle issues.

**Comment by mpapis** [comment]
we also switched to fastly, it could be solved by it

**Comment by CirrusThink** [comment]
The certs we have are not private but public verified. I tried to upgrade to the latest rum but that does not seem to help at this point.
I am seeing this on both CentOS and Ubuntu releases

**Comment by toadle** [comment]
Have you read and seen this: https://github.com/rvm/rvm/issues/3330 ?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
