### ISSUE TITLE
rvm.io doesn't describe how to report bugs.

### ISSUE THREAD

**Issue by shalecraig** [rvm/rvm#3371]
I clicked through pivotal's UI (linked via "tracker"), then realized that it's read-only.

I poked in irc, and had no response.

Can you add a link somewhere under "development" that says "Report a bug"?

I think linking to https://github.com/rvm/rvm/issues/new should be ok, but you probably know better.

**Comment by phillipp** [comment]
Hi,
thanks for opening the issue. I agree that a link to the github issue tracker would be helpful. Would you mind adding the link to the website yourself? :-) You can find the repository and basic instructions for small changes here: https://github.com/rvm/rvm-site

If you need any help please let me know :-)
