### ISSUE TITLE
Startup faster

### ISSUE THREAD

**Issue by mcandre** [rvm/rvm#3376]
As a power user, I want rvm to startup much faster, so that I can have my favorite Ruby CLI tools always on hand when I open a new bash(rc) session. Currently, rvm takes several seconds to load, so I have to choose between a really slow terminal launch, or having my favorite tools on PATH.

**Comment by havenwood** [comment]
One option would be to use the fast and light [chruby](https://github.com/postmodern/chruby#readme) for switching with RVM's [chruby integration](https://rvm.io/workflow/chruby).

**Comment by mcandre** [comment]
Cool, thank you!

**Comment by mcandre** [comment]
Could you provide an example of how to load 2.0 with chruby, where 2.0 was installed via rvm? I can't seem to find the right syntax for this.
