### ISSUE TITLE
rvm install hangs on clon

### ISSUE THREAD

**Issue by ruudgrosmann** [rvm/rvm#3380]
hi,
I have an issue with rvm install ruby-1.8.7. It hangs after a while. It appears this is on the command 'git clone'. This is because it uses the git protocol. When I manually run then command with the https protocol, it performs the clone without problems.

Is there a way that I can use to bypass this git clone git://... ? Can I specify the protocol or manually install the ruby so that rvm picks it up correctly?

thanks in advance, Ruud

**Comment by ruudgrosmann** [comment]
rvm 1.26.11
Linux axafe 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

After having manually cloned the repo, the rvm install command skips the git clone step and freezes again:

rdgon@dechenSZ rvm install  ruby-1.8.7       
Checking requirements for debian.
Requirements installation successful.
Installing Ruby from source to: /export/home/rdgon/.rvm/rubies/ruby-1.8.7-head, this may take a while depending on your cpu(s)...
HEAD is now at d9a2b34 * doc/contributors.rdoc: fix a typo. Patch by @davydovanton
<blinking cursor>

I see no computer load from the rvm install process. There is no debug output.

Any idea what this can be caused by?

Ruud

**Comment by mpapis** [comment]
try in `$rvm_path/config/user`:
```ini
ruby_repo_url=https://github.com/ruby/ruby.git
```

**Comment by chewi** [comment]
@mpapis, did you mean `$rvm_path/config/user/db`? May need to try this myself. But is there any particular reason why you don't use https by default? It's safer and works behind proxies. It's worth noting that Bundler will be switching to https for `:github` entries from v2.

**Comment by ruudgrosmann** [comment]
thanks for your answer. Problem is solved now.
