### ISSUE TITLE
`gemset empty` does not delete ./bundler/gems/* created by bundler git refs

### ISSUE THREAD

**Issue by dholdren** [rvm/rvm#3381]
https://gist.github.com/dholdren/8a6de8541e538181fb8f

If you have a git source in a Gemfile, bundler will checkout the branch/tag/sha into:
`<gem installation path>/bundler`
i.e. `<gemset dir>/bundler`

but when you issue `rvm gemset empty` this directory is not cleaned out.

**Comment by mpapis** [comment]
1. please reopen here: https://github.com/rvm/gem-empty/issues
2. check how rubygems behaves with branch/tag/sha and
 - report a bug for rubygems if it fails
 - dump bundler and be happy with rubygems

_resources: <https://coderwall.com/p/html5w/try-rubygems-2-0>_

**Comment by dholdren** [comment]
I'll re-open on gem-empty.
I tried with latest rubygems and `gem install --file Gemfile` but that gave me other errors...

I still think rvm could handle this. It's already bundler-aware

**Comment by dholdren** [comment]
Opened as: https://github.com/rvm/gem-empty/issues/2

**Comment by mpapis** [comment]
fixed with #3391 and rvm/gem-empty#2 - you still need to update the gem:

    rvm @global do gem update gem-empty

**Comment by dholdren** [comment]
thanks for this @mpapis and @anfleene

Actually the gem is in ~/.rvm/gem-cache/ (I'm on rvm head) and I had to manually delete the 1.0.0 version there after I did another `rvm get head` this morning

That may be another issue: `rvm get head` should clean up your ~/.rvm/gem-cache/ dir
I don't exactly know how I ended up with both versions, and rvm was picking up the older version when I ran `rvm gemset empty`

**Comment by anfleene** [comment]
@mpapis If I update the version requirement will that force an upgrade?

**Comment by mpapis** [comment]
@anfleene the version is only checked when installing new rubies
