### ISSUE TITLE
Docs: Clarify chruby integration step

### ISSUE THREAD

**Issue by mcandre** [rvm/rvm#3383]
The rvm/mrvm/chruby integration doc omits an important step, informing chruby of where rvm's rubies are stored:

https://rvm.io/workflow/chruby

vs.

https://github.com/postmodern/chruby#rvm

Without `RUBIES+=(~/.rvm/rubies/*)`, `chruby 2.0` doesn't work.

Furthermore, if `.ruby-version` / chruby `auto.sh` are to be used, `RUBIES+=($HOME/.rvm/rubies/*)` needs to be written before `source /usr/local/opt/chruby/share/chruby/auto.sh` in any bash configuration scripts.

**Comment by havenwood** [comment]
I think there's some confusion here between the mrvm chruby-integration and migrating RVM-installed Rubies to chruby. The former instructions are for mrvm. The latter are for migrating to chruby.

If you use mrvm you have RVM install and manage Ruby locations for you and use chruby to switch. When you install new Rubies with mrvm they'll automatically be available. It doesn't work with chruby's regular RUBIES env var.

If you just use chruby itself as your switcher then you should follow the chruby instructions. It can point at any location and you can manage RUBIES yourself.

I'll look at improving documentation to make the options more clear.
