### ISSUE TITLE
Ruby precompiled binaries and support for 2.2.2, 2.1.6, and 2.0.0p645

### ISSUE THREAD

**Issue by BrianHawley** [rvm/rvm#3384]
https://www.ruby-lang.org/en/news/2015/04/13/ruby-openssl-hostname-matching-vulnerability/

So it looks like we should be updating MRI again, to [2.2.2](https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-2-2-released/), [2.1.6](https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-1-6-released/) and [2.0.0p645](https://www.ruby-lang.org/en/news/2015/04/13/ruby-2-0-0-p645-released/).

We use OS X and Centos here, but I'm sure other platforms need these too.

**Comment by eddeyang** [comment]
I just installed 2.2.1 and it tells me this version has security vulnerabilities and asks me to upgrade to 2.2.2.

**Comment by DanielKehoe** [comment]
I just installed Ruby with ```$ rvm install ruby``` and got Ruby 2.2.1. The current stable release is 2.2.2 as of six days ago so I think RVM needs to be updated.

**Comment by havenwood** [comment]
@DanielKehoe Until the next stable version of RVM is released you can get the latest definitions by updating RVM with `rvm get master`.

**Comment by zekefast** [comment]
Ruby MRI v`2.2.2` does not listed in `ruby list known rubies`, but still can be installed with `rvm install ruby-2.2.2` with compilation from sources.

Expected Result: MRI ruby v`2.2.2` will be listed in the list of known rubies.

Ruby version: 
```
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```
OS: Debian jessie

```
$ rvm list known rubies
# MRI Rubies
[ruby-]1.8.6[-p420]
[ruby-]1.8.7[-head] # security released on head
[ruby-]1.9.1[-p431]
[ruby-]1.9.2[-p330]
[ruby-]1.9.3[-p551]
[ruby-]2.0.0[-p643]
[ruby-]2.1.4
[ruby-]2.1[.5]
[ruby-]2.2[.1]
[ruby-]2.2-head
ruby-head

# for forks use: rvm install ruby-head-<name> --url https://github.com/github/ruby.git --branch 2.1

# JRuby
jruby-1.6.8
jruby[-1.7.19]
jruby-head
jruby-9.0.0.0.pre1

# Rubinius
rbx-1.4.3
rbx-2.4.1
rbx[-2.5.2]
rbx-head

# Opal
opal

# Minimalistic ruby implementation - ISO 30170:2012
mruby[-head]

# Ruby Enterprise Edition
ree-1.8.6
ree[-1.8.7][-2012.02]

# GoRuby
goruby

# Topaz
topaz

# MagLev
maglev[-head]
maglev-1.0.0

# Mac OS X Snow Leopard Or Newer
macruby-0.10
macruby-0.11
macruby[-0.12]
macruby-nightly
macruby-head

# IronRuby
ironruby[-1.1.3]
```

**Comment by BrianHawley** [comment]
Note that even once the known rubies are updated, this issue is about the availability of *precompiled binaries*. When precompiled binaries of those versions are available in the RVM binaries server, this ticket can be considered resolved. Source support is good, but not enough.

**Comment by wingfire** [comment]
rvm stable is still delivering the ruby version 2.2.1

**Comment by arteezy** [comment]
Is rvm dead? New Rubies have been out for months, yet still no fresh release of rvm.

**Comment by jrgifford** [comment]
No, we're all volunteers and don't always have the time to be on top of
things. I've got builds, just haven't had the opportunity to release
them yet.

**Comment by scalp42** [comment]
@jrgifford any chance to release them please?

**Comment by havenwood** [comment]
OS X binaries are now available for 2.2.2, 2.1.6 and 2.0.0-p645.

**Comment by scalp42** [comment]
@havenwood I can't find them on https://rvm.io/binaries/ubuntu/14.04/x86_64/

**Comment by franklinyu** [comment]
@scalp42 He said "OS X binaries".

**Comment by havenwood** [comment]
OS X binaries are now available for 2.2.3, 2.1.7 and 2.0.0-p647 as well.

**Comment by franklinyu** [comment]
@havenwood Thank you! Using 2.2.3 on Yosemite right now.

**Comment by pkuczynski** [comment]
This issue seems to be solved by now. Please reopen if it's not...
