### ISSUE TITLE
mysql2.bundle image not found

### ISSUE THREAD

**Issue by daBee** [rvm/rvm#3385]
Installed the mysql2 gem without errors. I get the following report upon requiring mysql ("require 'mysql2'"):

    LoadError: dlopen(/Users/rich/.rvm/gems/ruby-head/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle, 9): Library not loaded: libmysqlclient.18.dylib
    Referenced from: /Users/rich/.rvm/gems/ruby-head/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle
    Reason: image not found - /Users/rich/.rvm/gems/ruby-head/gems/mysql2-0.3.18/lib/mysql2/mysql2.bundle
	from /Users/rich/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rich/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/rich/.rvm/gems/ruby-head/gems/mysql2-0.3.18/lib/mysql2.rb:31:in `<top (required)>'
	from /Users/rich/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/rich/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/rich/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):1
	from /Users/rich/.rvm/rubies/ruby-head/bin/irb:11:in `<main>'

**Comment by daBee** [comment]
I have this setup duplicated on another box and it works just fine.  I degraded RVM to the same version on the other box, and the same issue still happens.  The mysql2.bundle is indeed there.  

    HQ:mysql2 rich$ pwd
    /Users/rich/.rvm/gems/ruby-2.1.5/extensions/x86_64-darwin-14/2.1.0-static/mysql2-0.3.18/mysql2

**Comment by daBee** [comment]
Was a bad link.  Used homebrew to fix mysql and all linking.

**Comment by mpapis** [comment]
@daBee good, can you post the commands you used to fix it and then close the ticket?

**Comment by daBee** [comment]
Sure.

brew install mysql

I had some previous issues with homebrew, but it was recommended to me as it apparently has changed.  It fixed all the links that weren't there with my hard individual install of mysql.  

Cheers
