### ISSUE TITLE
Installing RVM on Yosemite 

### ISSUE THREAD

**Issue by Ger123** [rvm/rvm#3390]
I just updated to Yosemite, 10.10.3. I then installed Xcode Command Line Tools. I then configured git. I then installed Homebrew...no problems there. Next I downloaded the gpg tool suite again everything ok. Next I executed the command on your site..gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3.
That seemed to work..the GPG Keychain:
![gpg](https://cloud.githubusercontent.com/assets/4410204/7271151/716c6546-e8d9-11e4-89dc-c0f2786699a0.png)

Next I used the curl command....\curl -sSL https://get.rvm.io | bash -s stable --ruby

and got the following output:
![bash](https://cloud.githubusercontent.com/assets/4410204/7271458/68db4f4e-e8db-11e4-8b96-6665d6117450.png)
Cheers.

**Comment by rebelwarrior** [comment]
curl is trying to sign the url of the command and it's failing. 
try this URL: https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer
it is the one it redirects to. 

Or better yet, go to the https://get.rvm.io/ URL and copy the script write it into a file with an .sh extension. Mark it as an executable and execute it.

**Comment by havenwood** [comment]
You can run the `rvm osx-ssl-certs update all` command to fix OS X certificates for curl or read more about a [manual solution for OS X or other OSes here](https://rvm.io/support/fixing-broken-ssl-certificates).
