### ISSUE TITLE
cant install rvm

### ISSUE THREAD

**Issue by Aonix** [rvm/rvm#3394]
I am very new to ubuntu and trying to start to learn to program in ruby.

I've been stuck for the last day and cant even manage to get ruby installed with rvm.

When I try to add RVM with "\curl -sSL https://get.rvm.io | bash -s stable" I get an error:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    173      0  0:00:01  0:00:01 --:--:--   173
100 22721  100 22721    0     0  11988      0  0:00:01  0:00:01 --:--:--  136k
Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc
gpg: Signature made Mon 30 Mar 2015 22:52:13 BST using RSA key ID BF04FF17
gpg: can't open `/home/max/.gnupg/pubring.gpg'
gpg: keydb_search failed: file open error
gpg: Can't check signature: public key not found
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.26.11.tgz' - 'https://github.com/rvm/rvm/releases/download/1.26.11/1.26.11.tar.gz.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

I then tried the suggested "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3" and yield the result:

gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: can't open `/home/max/.gnupg/pubring.gpg'
gpg: keydb_get_keyblock failed: eof
gpg: no writable keyring found: eof
gpg: error reading `[stream]': general error
gpg: Total number processed: 0

This is probably some nooby fix but I've googled everywhere and cant find any help.

**Comment by starswan** [comment]
Which version of ubuntu are you using?

**Comment by Aonix** [comment]
14.04 LTS

**Comment by starswan** [comment]
Just tried the gpg line you quoted on 14.04 LTS machine and it works fine. Maybe try it again?

**Comment by Aonix** [comment]
I managed to fix it with help from this

http://stackoverflow.com/questions/2182938/gpg-warning-unsafe-ownership-on-configuration-file-gpg-fingerprint-on-ubun

not really sure what this did but it seemed to work :s

rvms installed and ruby and rails are installing currently.

**Comment by d4rky-pl** [comment]
@mpapis I believe this can be safely closed.
