### ISSUE TITLE
Automatically set login shell option for gnome-terminal

### ISSUE THREAD

**Issue by Folis** [rvm/rvm#3395]
After some discussion with @mpapis we decided that it would be nice to automatically set the login shell option for gnome-terminal, so that the infamous "RVM is not a function" message does not appear. I figured out that the setting can be set here:

`~/.gconf/apps/gnome-terminal/profiles/Default/%gconf.xml`

Setting this option should do it:

`<entry name="login_shell" mtime="<unix_timestamp>" type="bool" value="true"/>`

I'd do it myself, but I don't know too much about shell scripting.

**Comment by mpapis** [comment]
fixed !
