### ISSUE TITLE
Extra step on (german) Ubuntu installation necessary

### ISSUE THREAD

**Issue by haslinger** [rvm/rvm#3398]
Disclaimer: I install Ubuntu with german language selection (I've seen that to cause installation issues before)

When I install according to the website standard procedure, close the terminal and open it again,  
```
type rvm | head -n1
``` 
gives NOT the desired (translation of) 
```
rvm is a function
```

The fix I'm using is the old required step: appending adding to the user's ```.bashrc``` the line 
```
source /home/%USERNAME%/.rvm/scripts/rvm
```

I've seen that in 14.04 before, but I was not sure about it. Now I installed a fresh 15.04 and reproduced it reliably with 64bit standard Ubuntu desktop installation.

**Comment by phillipp** [comment]
What does it say for the rvm type? Or is rvm not found? What is the output of `which rvm`?

**Comment by haslinger** [comment]
Wait, you are here as well!? Nice to see you! 
When I remove the source from .bashrc, iIt gives
```
rvm ist /home/stefan/.rvm/bin/rvm
```
consistent to the ```which rvm``` output
```
/home/stefan/.rvm/bin/rvm
```
and putting it in again (and reloading bash) fixes it again.

**Comment by d4rky-pl** [comment]
The language version here is the red herring, it seems that RVM is not installing correctly on Ubuntu. The problem is .bash_profile is not being loaded in Ubuntu so the `[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"` part is never loaded, therefore working incorrectly.

**Comment by mpapis** [comment]
most likely login shell, please retry with `rvm get master`

**Comment by phillipp** [comment]
I can't confirm the bug on docker w/ ubuntu 12.04. My test container was started with `sudo docker run --rm -ti ubuntu /bin/bash`

I ran the script for for en/POSIX locale:
```
apt-get install -y curl
locale # showing POSIX
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable
bash -l -c "type rvm | head -n1" # => rvm is a function
```

I ran this script for for de_DE locale:
```
locale-gen de_DE.UTF-8
export  LANG=de_DE.UTF-8
export  LC_MESSAGES=POSIX
apt-get install -y curl
locale # showing POSIX
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
\curl -sSL https://get.rvm.io | bash -s stable
bash -l -c "type rvm | head -n1" # => rvm is a function
```

Can you try to reproduce that?

**Comment by haslinger** [comment]
@mpapis: Thanks for the feedback (and thanks for all the encouragement at Rossconf)
```rvm get master``` changes the output to
```
stefan@turing:~$ type rvm | head -n1
rvm gehasht ergibt (/home/stefan/.rvm/bin/rvm)
```
to get the english message
```
stefan@turing:~$ LANGUAGE=en_US:en
stefan@turing:~$ type rvm | head -n1
rvm is hashed (/home/stefan/.rvm/bin/rvm)
```
After closing shell and reopening, old behaviour as above.
I try to be more precise and checked same variations. 
It's Ubuntu 15.04, installed on a laptop with Unity Desktop and meanwhile also Ubuntu Mate Desktop, I now also tried with 
- terminator terminal app
- mate-terminal app 
- [Strg]-[F1] consoles (are they called consoles?). 
- ssh localhost 
Same behavior in all four. 
(But as I said, the extra source line in the .bashrc always fixes it.)

**Comment by haslinger** [comment]
@phillipp Never played with docker before, that's gonna be a fun ride ... installing ... keep you updated ...

**Comment by haslinger** [comment]
I now also tried on a 14.04 kvm-VM. So no docker. Everythings fine there as well.

**Comment by haslinger** [comment]
See update three posts above and shame on me...

**Comment by pretzelhands** [comment]
Haha, you had me worrying there for a second.

**Comment by mpapis** [comment]
hmm, was there any manual work involved in setting login shell? - this should be automated as we started with `gnome-terminal` already.

**Comment by haslinger** [comment]
I think, that is a rabbit hole, http://www.tecmint.com/linux-terminal-emulators/ lists 20 (sic!) terminal applications for Ubuntu alone.

**Comment by pretzelhands** [comment]
We surely cannot cover all edge cases, but at least we can automate things for the terminals listed on the site: 

* ~~gnome-terminal~~
* LXTerminal
* XTerm
* Konsole
* zsh/iTerm
