### ISSUE TITLE
Simplify default help output

### ISSUE THREAD

**Issue by madebyjeffrey** [rvm/rvm#3399]
```
$ rvm|wc -l
227
```

rvm outputs more information on a normal invocation than is necessary - for somebody unfamiliar with the use it is actually counter productive.

I would propose the output be limited to commonly used features, for example install and use, and how to get further help — a manpage would be perfect for a longer version like what is present now.

**Comment by havenwood** [comment]
:+1:

**Comment by pkuczynski** [comment]
Fair point. Fixing this in #4039 based on the wider input from #4029.
