### ISSUE TITLE
rvm or zsh not switchng to new default gemset on a new window/tab unless logout-login or reset

### ISSUE THREAD

**Issue by mbrand12** [rvm/rvm#3404]
Using:

Ubuntu 14.04
zsh 5.0.2 with oh-my-zsh
rvm installed using (rvm get head --auto-dotfiles)

.rmvrc, .zshrc, .zlogin and echoes gist [here](https://gist.github.com/mbrand12/5c233672fe9eb42df0e5).

When I use `$ rvm use 2.1.5@new_default  --default ` for example it changes the default gemset,  but upon opening or reopening a new window (or tab) the rvm uses previous gemset (old_default). However, when I use `$ rvm use default` it will switch to a proper one, for that tab.

Both the `$rvm_path/environments/default` and `$rvm_path/config/alias` changes to the new default gemset as well, but upon opening a new tab and using `$ echo $PATH`, `$ echo $GEM_PATH` and `$ echo $GEM_HOME` I get the previous gemset rather than the current default, in that tab. Details are in the gist above.

Only when I logout and then login (or reset) does the gemset changes to the default that has been set. I am not sure where is the problem and how to fix it.

I am not sure weather this is an issue on the rvm side or the zsh (oh-my-zsh) side so I decided to open the issue here first. Any help or pointers are welcome.

**Comment by rebelwarrior** [comment]
Using ubuntu... you're terminal is  opening as a login session, right? http://rvm.io/integration/gnome-terminal
I'm not sure what's happening but it's good to rule things out.

**Comment by mbrand12** [comment]
Yes, the "Run command as a login shell" is checked, at least one more thing ruled out.

**Comment by havenwood** [comment]
I'm curious if this happens with oh-my-zsh plugins disabled? How about with oh-my-zsh disabled, just zsh? There are a myriad of bugs in oh-my-zsh and plugins unfortunately so it might be helpful to narrow it down to the offending plugin if that's the issue.

**Comment by mbrand12** [comment]
Finally got the time to test this more (sorry for the delay).

The good news is that the problem is gone (probably due to the oh-my-zsh updates and fixes). The bad news are I was unable to narrow it down to where the problem was exactly.
