### ISSUE TITLE
Rails -v problem

### ISSUE THREAD

**Issue by piga** [rvm/rvm#3407]
I am using linux mint.
I installed rails, than I made some gemset, then I made some app in the default gemset. The app was working. Than I opened new terminal window and suddenly rails command wasn't working any more.
I tryied rails -v and I recive this message:
The program 'rails' can be found in the following packages:
 * ruby-railties-3.2
 * ruby-railties-4.0

**Comment by phillipp** [comment]
In that new terminal, what is the output of:
`which rvm`

`type rvm | head -n 1` 

and 

`rvm list rubies`?

**Comment by piga** [comment]
darko@darko-Lenovo-G570 ~ $ which rvm
/home/darko/.rvm/bin/rvm
darko@darko-Lenovo-G570 ~ $ rvm list rubies
rvm rubies

   ruby-2.1.1 [ i686 ]
=* ruby-2.2.1 [ i686 ]

**Comment by piga** [comment]
I uninstalled ruby and rails. Then I installed ruby and rails again. And ruby -v and rails -v was OK.
Then I closed the terminal and the same problem started again. 
Thanks

**Comment by piga** [comment]
I found some solution. In every new terminal first I have to run:
source /home/darko/.rvm/scripts/rvm

I found out this when I again install rvm and than I got this message:
"To start using RVM you need to run source /home/darko/.rvm/scripts/rvm
in all your open shell windows, in rare cases you need to reopen all shell windows."

How can I avoid running that command always when I start new terminal?

**Comment by exine** [comment]
Try adding source command to .zshrc/.bashrc

**Comment by piga** [comment]
.zshrc/.bashrc is read-only file. How can I change it? Thanks
