### ISSUE TITLE
Solaris 11.2 requirements fails

### ISSUE THREAD

**Issue by CirrusThink** [rvm/rvm#3409]
Maybe because I am running a newer version then required ?

pkg info entire
          Name: entire
       Summary: entire incorporation including Support Repository Update (Oracle Solaris 11.2.9.5.0).
   Description: This package constrains system package versions to the same
                build.  WARNING: Proper system update and correct package
                selection depend on the presence of this incorporation.
                Removing this package will result in an unsupported system.  For
                more information see:
                https://support.oracle.com/rs?type=doc&id=1672221.1
      Category: Meta Packages/Incorporations
         State: Installed
     Publisher: solaris
       Version: 0.5.11 (Oracle Solaris 11.2.9.5.0)
 Build Release: 5.11
        Branch: 0.175.2.9.0.5.0
Packaging Date: April  4, 2015 08:31:23 PM
          Size: 5.46 kB
          FMRI: pkg://solaris/entire@0.5.11,5.11-0.175.2.9.0.5.0:20150404T203123Z

rvm requirements
Checking requirements for solaris.
dolly password required for 'pkg update bash curl text/gnu-patch git text/gnu-patch developer/gcc-45 system/header developer/build/autoconf developer/build/automake developer/build/libtool system/library/math file/gnu-coreutils':
Sorry, try again.
dolly password required for 'pkg update bash curl text/gnu-patch git text/gnu-patch developer/gcc-45 system/header developer/build/autoconf developer/build/automake developer/build/libtool system/library/math file/gnu-coreutils':
Creating Plan (Solver setup): |
pkg update: No matching version of developer/gcc-45 can be installed:
  Reject:  pkg://solaris/developer/gcc-45@4.5.2-0.175.2.0.0.42.1
  Reason:  No version matching 'require' dependency library/mpfr@2.4.2,5.11-0.175.2.0.0.41.1 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/library/mpfr@2.4.2-0.175.2.0.0.42.1
    Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.41.0 can be installed
      ----------------------------------------
      Reject:  pkg://solaris/system/library@0.5.11-0.175.2.9.0.4.2
      Reason:  No version matching 'require' dependency consolidation/osnet/osnet-incorporation can be installed
      Reason:  No version matching 'require' dependency library/libxml2@2.9.1,5.11-0.175.2 can be installed
        ----------------------------------------
        Reject:  pkg://solaris/library/libxml2@2.9.2-0.175.2.6.0.3.0
        Reason:  No version matching 'require' dependency system/library/math@0.5.11,5.11-0.175.2.0.0.37.0 can be installed
          ----------------------------------------
          Reject:  pkg://solaris/system/library/math@0.5.11-0.175.2.5.0.2.0
          Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.42.2 can be installed
          ----------------------------------------
        Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.42.2 can be installed
        ----------------------------------------
      ----------------------------------------
    ----------------------------------------
  Reason:  No version matching 'require' dependency system/linker@0.5.11,5.11-0.175.2.0.0.41.0 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/system/linker@0.5.11-0.175.2.8.0.2.2
    Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2 can be installed
    ----------------------------------------
No matching version of system/library/math can be installed:
  Reject:  pkg://solaris/system/library/math@0.5.11-0.175.2.5.0.2.0
  Reason:  [already rejected; see above]
No matching version of developer/build/automake can be installed:
  Reject:  pkg://solaris/developer/build/automake@1.11.2-0.175.2.0.0.42.1
  Reason:  No version matching 'require' dependency developer/build/automake-111 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/developer/build/automake-111@1.11.2-0.175.2.0.0.42.1
    Reason:  No version matching 'require' dependency runtime/perl-512@5.12.5,5.11-0.175.2.0.0.41.1 can be installed
      ----------------------------------------
      Reject:  pkg://solaris/runtime/perl-512@5.12.5-0.175.2.9.0.3.0
      Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.42.2 can be installed
      Reason:  No version matching 'require' dependency system/linker@0.5.11,5.11-0.175.2.0.0.42.2 can be installed
      ----------------------------------------
    ----------------------------------------
No matching version of web/curl can be installed:
  Reject:  pkg://solaris/web/curl@7.21.2-0.175.2.7.0.2.0
  Reason:  No version matching 'require' dependency library/zlib@1.2.3,5.11-0.175.2.0.0.42.1 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/library/zlib@1.2.3-0.175.2.0.0.42.1
    Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.41.0 can be installed
    ----------------------------------------
  Reason:  No version matching 'require' dependency shell/ksh93@93.21.0.20110208,5.11-0.175.2.0.0.42.1 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/shell/ksh93@93.21.0.20110208-0.175.2.0.0.42.1
    Reason:  No version matching 'optional' dependency shell/ksh@20110208,5.11-0.175.1.0.0.21.0 can be installed
      ----------------------------------------
      Reject:  pkg://solaris/shell/ksh@20110208-0.175.1.0.0.21.0
      Reason:  No version matching 'require' dependency shell/ksh93@93.21.0.20110208,5.11-0.175.1.0.0.21 can be installed
      ----------------------------------------
    Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.41.0 can be installed
    ----------------------------------------
No matching version of system/header can be installed:
  Reject:  pkg://solaris/system/header@0.5.11-0.175.2.9.0.4.2
  Reason:  No version matching 'require' dependency consolidation/osnet/osnet-incorporation can be installed
No matching version of developer/versioning/git can be installed:
  Reject:  pkg://solaris/developer/versioning/git@1.7.9.2-0.175.2.0.0.42.1
  Reason:  No version matching 'require' dependency shell/ksh93@93.21.0.20110208,5.11-0.175.2.0.0.41.1 can be installed
No matching version of file/gnu-coreutils can be installed:
  Reject:  pkg://solaris/file/gnu-coreutils@8.16-0.175.2.0.0.42.1
  Reason:  No version matching 'require' dependency library/gmp@4.3.2,5.11-0.175.2.0.0.41.1 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/library/gmp@4.3.2-0.175.2.0.0.42.1
    Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.41.0 can be installed
    ----------------------------------------
No matching version of developer/build/autoconf can be installed:
  Reject:  pkg://solaris/developer/build/autoconf@2.68-0.175.2.0.0.42.1
  Reason:  No version matching 'require' dependency shell/ksh93@93.21.0.20110208,5.11-0.175.2.0.0.41.1 can be installed
No matching version of shell/bash can be installed:
  Reject:  pkg://solaris/shell/bash@4.1.17-0.175.2.9.0.3.0
  Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.42.2 can be installed
No matching version of developer/build/libtool can be installed:
  Reject:  pkg://solaris/developer/build/libtool@2.4.2-0.175.2.0.0.42.1
  Reason:  No version matching 'require' dependency developer/base-developer-utilities@0.5.11,5.11-0.175.2.0.0.41.0 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/developer/base-developer-utilities@0.5.11-0.175.2.9.0.2.2
    Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2 can be installed
    ----------------------------------------
No matching version of text/gnu-patch can be installed:
  Reject:  pkg://solaris/text/gnu-patch@2.7.1-0.175.2.4.0.5.0
  Reason:  No version matching 'require' dependency system/library@0.5.11,5.11-0.175.2.0.0.42.2 can be installed
Requirements installation failed with status: 1.

for example the shell/bash I have installed is newer then requirements

 pkg list -fa shell/bash
NAME (PUBLISHER)                                  VERSION                    IFO
shell/bash                                        4.1.17-0.175.2.9.0.3.0     i--
shell/bash                                        4.1.17-0.175.2.5.0.2.0     ---
shell/bash                                        4.1.11-0.175.2.3.0.4.0     ---
shell/bash                                        4.1.11-0.175.2.2.0.8.0     ---
shell/bash                                        4.1.11-0.175.2.2.0.7.0     ---
shell/bash                                        4.1.11-0.175.2.0.0.42.1    ---
shell/bash                                        4.1.9-0.175.1.13.0.1.0     ---
shell/bash                                        4.1.9-0.175.1.0.0.24.0     ---
shell/bash                                        4.1.9-0.175.0.0.0.2.537    ---
shell/bash                                        4.0.28-0.151.0.1           ---

**Comment by havenwood** [comment]
I'm guessing this was related to the system being errantly detected as 32-bit. Closed by https://github.com/rvm/rvm/pull/3459.

Please open a new issue if there are still requirement failures on master.
