### ISSUE TITLE
Installing rbx-2.5.2 on OS X 10.9.5 misses the LLVM dependency in autolibs

### ISSUE THREAD

**Issue by mwlang** [rvm/rvm#3413]
Got the following error when running: rvm install rbx

    >> rvm install rbx
    Searching for binary rubies, this might take some time.
    No binary rubies available for: osx/10.9/x86_64/rbx-2.5.2.
    Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
    Checking requirements for osx.
    ==> Upgrading 7 outdated packages, with result:
    automake 1.15, libksba 1.3.3, libtool 2.4.6, libyaml 0.1.6_1, openssl 1.0.2a-1, openssl-osx-ca 1.0.5, openssl098 0.9.8zf
    ==> Upgrading automake
    ==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring automake-1.15.mavericks.bottle.tar.gz
    ðº  /usr/local/Cellar/automake/1.15: 130 files, 3.2M
    ==> Upgrading libksba
    ==> Installing libksba dependency: libgpg-error
    ==> Downloading https://homebrew.bintray.com/bottles/libgpg-error-1.19.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring libgpg-error-1.19.mavericks.bottle.tar.gz
    ðº  /usr/local/Cellar/libgpg-error/1.19: 17 files, 352K
    ==> Installing libksba
    ==> Downloading https://homebrew.bintray.com/bottles/libksba-1.3.3.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring libksba-1.3.3.mavericks.bottle.tar.gz
    ðº  /usr/local/Cellar/libksba/1.3.3: 12 files, 376K
    ==> Upgrading libtool
    ==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring libtool-2.4.6.mavericks.bottle.tar.gz
    ==> Caveats
    In order to prevent conflicts with Apple's own libtool we have prepended a "g"
    so, you have instead: glibtool and glibtoolize.
    ==> Summary
    ðº  /usr/local/Cellar/libtool/2.4.6: 69 files, 3.8M
    ==> Upgrading libyaml
    ==> Downloading https://homebrew.bintray.com/bottles/libyaml-0.1.6_1.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring libyaml-0.1.6_1.mavericks.bottle.tar.gz
    ðº  /usr/local/Cellar/libyaml/0.1.6_1: 7 files, 352K
    ==> Upgrading openssl
    ==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2a-1.mavericks.bottle.1.tar.gz
    ######################################################################## 100.0%
    ==> Pouring openssl-1.0.2a-1.mavericks.bottle.1.tar.gz
    ==> Caveats
    A CA file has been bootstrapped using certificates from the system
    keychain. To add additional certificates, place .pem files in
      /usr/local/etc/openssl/certs

    and run
      /usr/local/opt/openssl/bin/c_rehash

    This formula is keg-only, which means it was not symlinked into /usr/local.

    Mac OS X already provides this software and installing another version in
    parallel can cause all kinds of trouble.

    Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

    Generally there are no consequences of this for you. If you build your
    own software and it requires this formula, you'll need to add to your
    build variables:

        LDFLAGS:  -L/usr/local/opt/openssl/lib
        CPPFLAGS: -I/usr/local/opt/openssl/include

    ==> Summary
    ðº  /usr/local/Cellar/openssl/1.0.2a-1: 463 files, 18M
    ==> Upgrading openssl-osx-ca
    ==> Downloading https://github.com/raggi/openssl-osx-ca/archive/1.0.5.tar.gz
    ######################################################################## 100.0%
    ==> make install PREFIX='/usr/local/Cellar/openssl-osx-ca/1.0.5' BREW='/usr/local/bin/brew'
    ==> Caveats
    To uninstall remove the openssl-osx-ca line from your crontab. e.g.

        (crontab -l | grep -v openssl-osx-ca) | crontab -
    ==> Summary
    ðº  /usr/local/Cellar/openssl-osx-ca/1.0.5: 4 files, 16K, built in 2 seconds
    ==> Upgrading openssl098
    ==> Downloading https://homebrew.bintray.com/bottles-versions/openssl098-0.9.8zf.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring openssl098-0.9.8zf.mavericks.bottle.tar.gz
    ==> Caveats
    This formula is keg-only, which means it was not symlinked into /usr/local.

    Mac OS X already provides this software and installing another version in
    parallel can cause all kinds of trouble.

    Generally there are no consequences of this for you. If you build your
    own software and it requires this formula, you'll need to add to your
    build variables:

        LDFLAGS:  -L/usr/local/opt/openssl098/lib
        CPPFLAGS: -I/usr/local/opt/openssl098/include

    ==> Summary
    ðº  /usr/local/Cellar/openssl098/0.9.8zf: 367 files, 12M
    Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
    Requirements installation successful.
    ruby-2.1.2 - #gemset created /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius
    ruby-2.1.2 - #generating rubinius wrappers................
    ruby-2.1.2@rubinius - #regenerating binstubs..........
    Updating certificates in '/etc/openssl/cert.pem'.
    rbx-2.5.2 - #downloading rubinius-2.5.2, this may take a while depending on your connection...
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 11.1M  100 11.1M    0     0  3191k      0  0:00:03  0:00:03 --:--:-- 3190k
    No checksum for downloaded archive, recording checksum in user configuration.
    rbx-2.5.2 - #extracting rubinius-2.5.2 to /Users/mwlang/.rvm/src/rbx-2.5.2....
    ruby-2.1.2@rubinius - #bundle install..
    rbx-2.5.2 - #configuring..
    Error running 'env /Users/mwlang/.rvm/wrappers/ruby-2.1.2@rubinius/ruby ./configure --prefix=/Users/mwlang/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl',
    showing last 15 lines of /Users/mwlang/.rvm/log/1430955897_rbx-2.5.2/configure.log
    [2015-05-06 16:45:08] env
    current path: /Users/mwlang/.rvm/src/rbx-2.5.2
    PATH=/Users/mwlang/.rvm/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/opt/local/bin:/opt/local/sbin:/opt/local/lib/mysql5/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin
    command(8): env /Users/mwlang/.rvm/wrappers/ruby-2.1.2@rubinius/ruby ./configure --prefix=/Users/mwlang/.rvm/rubies/rbx-2.5.2 --with-opt-dir=/usr/local/opt/libyaml --with-opt-dir=/usr/local/opt/readline --with-opt-dir=/usr/local/opt/libksba --with-opt-dir=/usr/local/opt/openssl
    Checking /usr/bin/clang: found
    Checking g++: found
    Checking bison: found

    Detected old configuration settings, forcing a clean build
      Checking for 'llvm-config': Error: No such keg: /usr/local/Cellar/llvm
    not found
    ABORT: unable to set up LLVM

    Running 'configure' failed. Please check configure.log for more details.

Resolved LLVM by doing: 

    brew install llvm
    rvm install rbx

However, I'm still getting an error during the compile phase:  Below is the result of the above two commands:

    >> brew install llvm
    ==> Downloading https://homebrew.bintray.com/bottles/llvm-3.5.1.mavericks.bottle.tar.gz
    ######################################################################## 100.0%
    ==> Pouring llvm-3.5.1.mavericks.bottle.tar.gz
    ==> Caveats
    LLVM executables are installed in /usr/local/opt/llvm/bin.
    Extra tools are installed in /usr/local/opt/llvm/share/llvm.

    This formula is keg-only, which means it was not symlinked into /usr/local.

    Mac OS X already provides this software and installing another version in
    parallel can cause all kinds of trouble.

    Generally there are no consequences of this for you. If you build your
    own software and it requires this formula, you'll need to add to your
    build variables:

        LDFLAGS:  -L/usr/local/opt/llvm/lib
        CPPFLAGS: -I/usr/local/opt/llvm/include

    ==> Summary
    ðº  /usr/local/Cellar/llvm/3.5.1: 707 files, 70M
    04:49:24: >> rvm install rbx
    rbx-2.5.2 - #removing src/rbx-2.5.2..
    Searching for binary rubies, this might take some time.
    No binary rubies available for: osx/10.9/x86_64/rbx-2.5.2.
    Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
    Checking requirements for osx.
    Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
    Requirements installation successful.
    ruby-2.1.2@rubinius - #regenerating binstubs..........
    rbx-2.5.2 - #downloading rubinius-2.5.2, this may take a while depending on your connection...
    rbx-2.5.2 - #extracting rubinius-2.5.2 to /Users/mwlang/.rvm/src/rbx-2.5.2....
    ruby-2.1.2@rubinius - #bundle install..
    rbx-2.5.2 - #configuring............
    rbx-2.5.2 - #compiling.........................................................................................................................................................................................................|
    Error running '/Users/mwlang/.rvm/wrappers/ruby-2.1.2@rubinius/rake install --trace',
    showing last 15 lines of /Users/mwlang/.rvm/log/1430956220_rbx-2.5.2/rake.log
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/bin/rake:23:in `load'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/bin/rake:23:in `<main>'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/bin/ruby_executable_hooks:15:in `eval'
    /Users/mwlang/.rvm/gems/ruby-2.1.2@rubinius/bin/ruby_executable_hooks:15:in `<main>'
    Tasks: TOP => install => gems:install

**Comment by franklinyu** [comment]
Did you tried `rvm install rbx-2.5.2` ? It may work according to #3513 . (Note: latest version is 2.5.8)

**Comment by mwlang** [comment]
This is old.  The latest 2.5.8 does work, but if I call rvm install rbx-2.5, it installs successfully and informs me it's not installed.  However, it's there and I confirmed it works.  See below for transcript

~~~
10:11:46:~ >> rvm -v
rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
10:11:47:~ >> rvm install rbx-2.5
Searching for binary rubies, this might take some time.
Found remote file http://binaries.rubini.us/osx/10.9/x86_64/rubinius-2.5.8.tar.bz2
Checking requirements for osx.
==> Upgrading 2 outdated packages, with result:
openssl 1.0.2d_1, homebrew/versions/openssl098 0.9.8zg
==> Upgrading openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl-1.0.2d_1.mavericks.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
ðº  /usr/local/Cellar/openssl/1.0.2d_1: 464 files, 18M
==> Upgrading homebrew/versions/openssl098
==> Downloading https://homebrew.bintray.com/bottles-versions/openssl098-0.9.8zg.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring openssl098-0.9.8zg.mavericks.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X already provides this software and installing another version in
parallel can cause all kinds of trouble.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl098/lib
    CPPFLAGS: -I/usr/local/opt/openssl098/include

==> Summary
ðº  /usr/local/Cellar/openssl098/0.9.8zg: 367 files, 12M
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
rbx-2.5.8 - #configure
rbx-2.5.8 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17.1M  100 17.1M    0     0  5435k      0  0:00:03  0:00:03 --:--:-- 5434k
No checksum for downloaded archive, recording checksum in user configuration.
rbx-2.5.8 - #validate archive
rbx-2.5.8 - #extract
rbx-2.5.8 - #validate binary
rbx-2.5.8 - #setup
rbx-2.5.8 - #gemset created /Users/mwlang/.rvm/gems/rbx-2.5.8@global
rbx-2.5.8 - #importing gemset /Users/mwlang/.rvm/gemsets/global.gems...............................................
rbx-2.5.8 - #generating global wrappers........
rbx-2.5.8 - #gemset created /Users/mwlang/.rvm/gems/rbx-2.5.8
rbx-2.5.8 - #importing gemsetfile /Users/mwlang/.rvm/gemsets/default.gems evaluated to empty gem list
rbx-2.5.8 - #generating default wrappers........
Updating certificates in '/System/Library/OpenSSL/cert.pem'.
rbx-2.5 is not installed.
To install do: 'rvm install rbx-2.5'
~~~

**Comment by franklinyu** [comment]
That's even more confusing. It seems that we need to explicitly provide the entire version number. How did you confirm it working? Is it in `rvm list`?

**Comment by mwlang** [comment]
I switched over to it and used it.  Albeit, I can't just switch with ```rvm use rbx```

~~~
12:52:03:~ >> rvm use rbx
rbx-2.5.2 is not installed.
To install do: 'rvm install rbx-2.5.2'
12:52:07:~ >> rvm use rbx-2.5.8
Using /Users/mwlang/.rvm/gems/rbx-2.5.8
12:52:16:~ >> irb
rbx-2.5.8 :001 > puts "Hello, World!"
Hello, World!
 => nil
rbx-2.5.8 :002 > exit
12:52:30:~ >> rvm list

rvm rubies

   jruby-1.7.19 [ x86_64 ]
=> rbx-2.5.8 [ x86_64 ]
   ree-1.8.7-2012.02 [ i686 ]
   ruby-1.8.6-p420 [ i686 ]
   ruby-1.8.7-head [ i686 ]
   ruby-1.8.7-p374 [ i686 ]
   ruby-1.9.3-p392 [ x86_64 ]
   ruby-2.0.0-p481 [ x86_64 ]
 * ruby-2.1.5 [ x86_64 ]
   ruby-2.2.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
12:53:16:~ >>
~~~

**Comment by franklinyu** [comment]
Oh this is a good news. It means that you can [add a alias](https://rvm.io/rubies/alias), by far the best solution I guess.

**Comment by mwlang** [comment]
Hmmm...I don't use aliases at all...usually, it's enough to type "rvm use 2.1" or "rvm use 2.2" to get whatever latest version installed for me.  Here, rvm is somehow thinking I'm attempting to switch to rbx-2.5.2 even though I don't have it installed (perhaps left over artifact of failed 2.5.2 install way back when I opened this ticket?).

~~~
01:25:14:~ >> rvm alias list
default => ruby-2.1.5
01:25:27:~ >>
~~~

**Comment by franklinyu** [comment]
Yes, maybe. Did you try to uninstall 2.5.2 to see whether it will clean it up?
