### ISSUE TITLE
bundler cannot be found with new ruby 2.0.0

### ISSUE THREAD

**Issue by mdunbavan** [rvm/rvm#3421]
Hi,

I have updated ruby with rvm to 2.0.0 version is ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]

When I type gem bundle install I get this:

ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command bundler

And in my gem list it's not there. Can anyone help at all?

**Comment by ojab** [comment]
bundler is not installed by default since 1.26.11. You should `gem install bundler` after ruby installation.

**Comment by havenwood** [comment]
@mdunbavan Like @ojab said, Bundler is no longer pre-installed as a default gem. The command `gem bundle install` isn't ever going to work though since `gem` doesn't have a `bundle` command. Like already suggested first `gem install bundler` then just `bundle install`, no `gem` prefix.
