### ISSUE TITLE
GPG is a needless complication and doesn't add additional security

### ISSUE THREAD

**Issue by pjump** [rvm/rvm#3429]
Simply having a certificate in my keyring without explicitly trusting it should never be something a trust decision such as should I install this software be based on.
You'd normally need to (L)sign the certificate to mark it as trusted in regards to its accuracy (assuming no web of trust) and trust-sign it to mark it as trusted in regards to the trustworthiness of the private-key holder.
There's  the trustedkeys.gpg keyring where simply inserting a key implies both of those things and then you can use `gpgv` for verification (`gpg --verify` doesn't really play nice in regards to UNIX return codes -- you'll get a zero even if a verification technically fails because the key something is signed with is not trusted).

But I think this whole gpg thing could be simply be skipped altogether, since ultimately I'm trusting the TSL certificate of https://rvm.io/ anyway and all the payload for the installation is retrieved via a secure TLS route (https).

**Comment by mpapis** [comment]
`https://` had major security few times recently - having extra security layer only can help, although I was always hesitant to use this long security route for similar reasons
