### ISSUE TITLE
missing libyaml-devel error

### ISSUE THREAD

**Issue by jzakiya** [rvm/rvm#3432]
I'm trying to install ruby-2.2.2 on PCLOS KDE 64-bit under Virtual Box.
JRuby 1.7.20 install with no problem.

I get this message for ruby-2.2.2:

'There is no '\''libyaml-devel'\'' package available for installation and RVM does not know how to make that happen,
please tell us how to install '\''libyaml-devel'\'' on '\''PCLinuxOS-2015'\'' here: https://github.com/rvm/rvm/issues\n'

The reason for this is because in PCLOS for 64-bits the package name is 'lib64yaml-devel'.
Most of the lib files have prefix  lib64... for the 64-bit ditros, versus the 32-bit builds.

**Comment by havenwood** [comment]
This appears similar to #2371 and related subsequent issues.

**Comment by pkuczynski** [comment]
This has been already solved in #3703
