### ISSUE TITLE
Keyserver specified on main page can be unreachable by gnupg without IPv6

### ISSUE THREAD

**Issue by ivan-kolmychek** [rvm/rvm#3438]
GnuPG can fail to import the key when IPv6 is not available:

```
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: keyserver receive failed: Address family not supported by protocol
```

Workaround: use IPv4-only keyserver (`ipv4.pool.sks-keyservers.net`, for example).

I suggest to leave this issue to hang here in case someone stumbles upon it too and, maybe, add some suggestion about this possibility to installation instructions.

**Comment by ivan-kolmychek** [comment]
Just to track a possible changes of this behavior in future:  
ArchLinux x86_64
```
$ gpg -v
gpg (GnuPG) 2.1.4
libgcrypt 1.6.3
...
```

**Comment by adamlwgriffiths** [comment]
This should really be mentioned in the README ASAP.
The first command to get this project installed fails. Not exactly a good user experience.

**Comment by easoncxz** [comment]
Today I tried to follow the installation instructions on the rvm homepage, and encountered a similar issue:

```
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: keyserver receive failed: No route to host
```
I'm not sure whether it's because my network doesn't support IPv4 yet, or because I'm accessing from within China and hence there being various internet access controls. I assumed there to be syncing between different keyservers and ended up working around this by arbitrarily using MIT's keyserver by `--keyserver hkp://pgp.mit.edu`.

**Comment by Pavel-Sayekat** [comment]
> GnuPG can fail to import the key when IPv6 is not available:
> 
> ```
> $ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
> gpg: keyserver receive failed: Address family not supported by protocol
> ```
> 
> Workaround: use IPv4-only keyserver (`ipv4.pool.sks-keyservers.net`, for example).
> 
> I suggest to leave this issue to hang here in case someone stumbles upon it too and, maybe, add some suggestion about this possibility to installation instructions.

That server is no longer available, bummer. So what now?
