### ISSUE TITLE
paths not set.

### ISSUE THREAD

**Issue by peter-umb** [rvm/rvm#3440]
Trying to run cap deploy but it seems as if my paths are not set.

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
https://github.com/wayneeseguin/rvm/issues/3212

No matter what I do I can't solve the problem. I have been trying for 11 hours....

rvm 1.26.11 ruby 1.9.3p194

$PATH
-bash: /usr/local/rvm/rubies/ruby-1.9.3-p551/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin: No such file or directory

**Comment by exine** [comment]
Could you please do
    echo $GEM_HOME
    echo $GEM_PATH
?

**Comment by digitalfrost** [comment]
Can this ticket be closed?

**Comment by exine** [comment]
Well, no needed info - closing. Please comment on this if this problem occurs again and I'll reopen.
