### ISSUE TITLE
rvm installer fails with syntax error

### ISSUE THREAD

**Issue by shalomie** [rvm/rvm#3441]
Hi,

Trying to install latest rvm and get this:
bash-3.00$ rvm/binscripts/rvm-installer
rvm/binscripts/rvm-installer: line 181: syntax error near unexpected token `"--silent"'

Any idea?

Thanks,
Shalomi

**Comment by shalomie** [comment]
Also tried it in bash 4.1 and got the same error

**Comment by havenwood** [comment]
@shalomie RVM requires bash 3.2.25+ for bash 3 or bash 4.2+.

**Comment by havenwood** [comment]
See: https://rvm.io/rvm/prerequisites
