### ISSUE TITLE
rvm path issue while running `rvm gemset list_all`

### ISSUE THREAD

**Issue by kiranps** [rvm/rvm#3442]
i installed rvm globally in /usr/local/rvm

    rvm gemset list_all

i get an output 

Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.1/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.1'.

    echo $PATH

gives

/usr/local/nvm/versions/node/v0.12.4/bin:/home/XXXX/bin:/usr/local/bin:/home/XXXX/bin:/usr/local/bin:/home/XXXX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin

**Comment by kiranps** [comment]
whenever there is a file "/usr/local/rvm/environment/default" warning appears while running  rvm

**Comment by exine** [comment]
You have nvm installed and it's initializing after rvm. Check your system-wide /etc/profile - you should reorder it so rvm is initialized as the last item.

**Comment by exine** [comment]
Did that fix it?

**Comment by kiranps** [comment]
no

**Comment by kiranps** [comment]
after removing nvm

    $ echo $PATH

    /home/XXXX/bin:/usr/local/bin:/home/XXXX/bin:/usr/local/bin:/home/XXXX/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/rvm/bin


after running the following command

    $ rvm use 2.2.1

    Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.2.1/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.2.1'.

then running the following command

    $ echo $PATH

    /home/XXXX/bin:/usr/local/rvm/gems/ruby-2.2.1/bin:/usr/local/rvm/gems/ruby-2.2.1@global/bin:/usr/local/rvm/rubies/ruby-2.2.1/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games


after running  rvm use 2.2.1 , whenever i run rvm <something> above warning appears. rvm reset solves the problem temporarily untill i run rvm use 2.2.1 or rvm gemset list_all warning starts appearing with rvm

**Comment by havenwood** [comment]
The warning is happening because `/home/XXXX/bin` is prepended to your PATH. You could find where it's being prepended in your dotfiles and append it to your PATH instead or silence the warning by adding a flag to your .rvmrc:
```sh
echo "rvm_silence_path_mismatch_check_flag=1" >> "$HOME/.rvmrc"
```

**Comment by kiranps** [comment]
thanks man
