### ISSUE TITLE
PATH issue with gems

### ISSUE THREAD

**Issue by scottzirkel** [rvm/rvm#3443]
I've seen a few other PATH issues on here, but none seem to fit what I'm seeing.

When I run rvm I get the following error:
````
Warning! PATH is not properly set up, '/Users/scott/.rvm/gems/bin' is not available,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use gems'.
````

I have run `get stable` and checked my .zshrc file, but I don't have anything referencing .rvm/gems/bin.

echo $PATH:
````
/Users/scott/.composer/vendor/bin:/Users/scott/.rvm/gems/ruby-2.2.2/bin:/Users/scott/.rvm/gems/ruby-2.2.2@global/bin:/Users/scott/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/scott/.rvm/bin:/Users/scott/.rvm/bin
````

Any ideas?

**Comment by exine** [comment]
You have .composer/vendor/bin before .rvm/gems/ruby-2.2.2/bin - that's what is causing that error. Initialize RVM after composer initialises its path.

**Comment by scottzirkel** [comment]
Updated it, but I'm getting the same error. Also tried moving composer to the very end, though I didn't expect that to work.

echo $PATH:

````
/Users/scott/.rvm/gems/ruby-2.2.2/bin:/Users/scott/.rvm/gems/ruby-2.2.2@global/bin:/Users/scott/.rvm/rubies/ruby-2.2.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/scott/.rvm/bin:/Users/scott/.composer/vendor/bin:/Users/scott/.rvm/bin
````

**Comment by scottzirkel** [comment]
Took out the GEM_PATH from .zshrc and it works fine. Thought you had to specify this path, but if you leave it out it uses the default path, which is what I wanted.
