### ISSUE TITLE
rvm reset, rvm system commands do not work with fish-shell 

### ISSUE THREAD

**Issue by pik** [rvm/rvm#3446]
See pastebin links for `rvm info` output (stdout & stderr) after starting a new terminal, after switching to an rvm environment and after attempting to reset -- same problem occurs with `rvm system` as well. 

[new terminal](http://pastebin.com/RnxkArSz)
[after activating 2.1.2](http://pastebin.com/3L0yPQ61)
[after reset](http://pastebin.com/TsWkZ24Z)

**Comment by exine** [comment]
Fish isn't supported since it isn't bash-compatible. Please contact maintainer for your wrapper of choice.

If you haven't, please see: https://rvm.io/integration/fish

**Comment by pik** [comment]
> If you haven't, please see https://rvm.io/integration/fish for alternatives where this function might work.

This is precisely what I attempted to use -- it does not work.

**Comment by exine** [comment]
Your best luck is to open issue on wrapper that you use. We provide them for convenience, but we do not support them.
