### ISSUE TITLE
Can't install ruby 2.0.0 on Ubuntu 12.04 with rvm

### ISSUE THREAD

**Issue by rhouse** [rvm/rvm#3449]
Below is the console output from the last of several attempts to install Ruby 2.0.0 on Ubuntu 12.04 using rvm.  I have done numerous Internet searches and tried various suggested remedies, but always resulting in the error messages shown below.  Any help with this will be greatly appreciated.  I'm about to give up on rvm.

$ rvm reinstall 2.0.0
ruby-2.0.0-p645 - #removing src/ruby-2.0.0-p645..
ruby-2.0.0-p645 - #removing rubies/ruby-2.0.0-p645..
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/12.04/x86_64/ruby-2.0.0-p645.
Continuing with compilation. Please read 'rvm help mount' to get more 
    information on binary rubies.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.0.0-p645, 
    this may take a while depending on your cpu(s)...
ruby-2.0.0-p645 - #downloading ruby-2.0.0-p645, this may take a while 
    depending on your connection...
ruby-2.0.0-p645 - #extracting ruby-2.0.0-p645 to 
    /usr/local/rvm/src/ruby-2.0.0-p645....
ruby-2.0.0-p645 - #configuring.............................................
ruby-2.0.0-p645 - #post-configuration..
ruby-2.0.0-p645 - #compiling...............................................
ruby-2.0.0-p645 - #installing..............................
ruby-2.0.0-p645 - #making binaries executable..
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
There was an error while trying to resolve rubygems version for 'latest'. 
Halting the installation.

**Comment by havenwood** [comment]
Try again after installing the ca-certificates package?:
```sh
sudo apt-get -y install ca-certificates
```

**Comment by havenwood** [comment]
There is a bit more about this on the help page for [fixing broken certificates](https://rvm.io/support/fixing-broken-ssl-certificates). Please start a new Issue if you still have certificate issues after installing the `ca-certificates` package.
