### ISSUE TITLE
Feature request: create a list of requirements for installing later

### ISSUE THREAD

**Issue by e2** [rvm/rvm#3455]
It would be useful to have something like e.g

```
rvm requirements missing ruby-2.2.2 jruby-head
```

And get a list (?) of requirements (or commands to install them).

The problem:
I want to automatically install a single-user RVM, but I have no way of installing missing requirements.

My workaround:
1. install RVM as root
2. `rvm requirements`
3. `rvm implode`
4. now, single-user RVM installs for each user succeed, because requirements are installed

This is ok, although if I ever want to check/install requirements, I have to download+install+implode every time.

Also, if requirements are not met, RVM is "half-installed" - and not in a "usable" state (no default Ruby, no ruby selected, no gemsets, installing/using gems means system ruby gems are used, etc.).

There's this for a quick check: https://rvm.io/rvm/prerequisites, though it won't allow building jruby or rbx.

The "clean" solution would be to have a rvm "meta-package" (in Linux) - but this is probably more of a maintenance problem than it's worth (especially considering other ruby types, or versions which need building).

The idea I have is to have a curl script that builds such a metapackage and installs/upgrades it. This could also avoid problems with old/bad versions of zsh or other tools. E.g.

`curl -sSL https://get.rvm.io/build_requirements | bash -s stable --ruby=jruby-head` (which on Debian would create and install a package which depends on the usual stuff + java, mvn, ant).

On the other hand, the simplest functionality is a hosted script that installs the basics for the sake of automation - especially `gawk` and `patch` (which are notoriously missing) - so the basic user installs work without issues. 

I personally only care about automatically install "basic requirements" or "full requirements" (incl. clan, llvm, llvm-dev, etc.). Perhaps this should simply be a new project separate from rvm?

**Comment by havenwood** [comment]
See the new `rvm --autolibs=read-fail --list-missing-packages --quiet requirements` command from #3310.
