### ISSUE TITLE
Could not install and use jruby-9.0.0.0-rc1

### ISSUE THREAD

**Issue by thehappycoder** [rvm/rvm#3458]
1. Installed it with some effort. I had to edit /home/idnet/.rvm/scripts/functions/hooks/jruby function "jruby_ngserver_is_running":
\command \ps auxww | rvm_grep 'org.jruby.main.NailServerMain' >/dev/null
instead of
\command \ps auxww | rvm_grep '[c]om.martiansoftware.nailgun.NGServer' >/dev/null

And got some error messages about gem pristine something...

2. To use jruby I had to install nailgun first

$ ruby --version
error: ng executable not found; run 'make' in /home/idnet/.rvm/rubies/jruby-9.0.0.0.rc1/tool/nailgun

But "make" alone didn't work.

Had to configure first:
cd /home/idnet/.rvm/rubies/jruby-9.0.0.0.rc1/tool/nailgun
./configure
make

3. Then finally use it

$ rvm use jruby-9.0.0.0.rc1

But still, for some reason, jruby doesn't start nailgun automatically (but it's supposed to) and says "connect: Connection refused".

Make sure that nailgun server is running:
$ ps aux | grep "org.jruby.main.NailServerMain"
If not, I run it manually:
$ ( JRUBY_OPTS='' jruby --ng-server 2>&1 > /dev/null )&

**Comment by garysweaver** [comment]
Note that JRuby 9.0.0.0 is available now. At the moment, you need to be using the development version of RVM to access it, but that will change soon I think.

**Comment by havenwood** [comment]
This still requires `rvm get master` at the moment but as mentioned will work soon on stable after the forthcoming release.
