### ISSUE TITLE
rvm solaris to local open source dir

### ISSUE THREAD

**Issue by CirrusThink** [rvm/rvm#3462]
We are in the middle of testing a patch for the ruby 2.1.6 Soalris x64_86 deployment. The path at the moment is ad hoc and we would like to install it via RVM . Is it possible for rvm to select the local dir of the source code to install for a given ruby version ?

**Comment by havenwood** [comment]
I think we already discussed this a while back in the #rvm channel but for posterity see `rvm help mount` or: https://github.com/rvm/rvm/blob/master/help/mount.md
