### ISSUE TITLE
Install rvm and ruby 2.1.5 on RHEL

### ISSUE THREAD

**Issue by samruddhikapileshwar** [rvm/rvm#3476]
I ma trying to install rvm and ruby 2.1.5 on RHEL 5, but I am getting the following error:-

 sudo curl -L get.rvm.io | bash -s stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22721  100 22721    0     0  68090      0 --:--:-- --:--:-- --:--:-- 68090
Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
curl: (23) Failed writing body (0 != 860)

Could not download 'https://github.com/rvm/rvm/archive/1.26.11.tar.gz'.
  curl returned status '23'.

Downloading https://bitbucket.org/mpapis/rvm/get/1.26.11.tar.gz
curl: (23) Failed writing body (0 != 15926)

Could not download 'https://bitbucket.org/mpapis/rvm/get/1.26.11.tar.gz'.
  curl returned status '23'.

I have installed all the required packages for ruby installation. Anyone encountered such an issue? Any help/suggestions would be greatly appreciated. Thanks in advance.

**Comment by bbozo** [comment]
(y) got this too

**Comment by tetreum** [comment]
me too

**Comment by havenwood** [comment]
A single-user install of RVM in the user's home dir is recommended. When you use `sudo` with the install script it does a multi-user install for server admins that isn't recommended. Instead, install with:
```sh
\curl -sSL https://get.rvm.io | bash
```

**Comment by bitclaw** [comment]
I'm not using sudo and I am also getting the same error:

![image](https://cloud.githubusercontent.com/assets/2736635/9559043/e3e152f6-4db2-11e5-9e24-43376bc80820.png)

**Comment by bradallenfisher** [comment]
trying to install rvm as vagrant user i get this

[vagrant@local ~]$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: directory `/home/vagrant/.gnupg' created
gpg: new configuration file `/home/vagrant/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/vagrant/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/vagrant/.gnupg/secring.gpg' created
gpg: keyring `/home/vagrant/.gnupg/pubring.gpg' created
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: /home/vagrant/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

[vagrant@local ~]$ \curl -sSL https://get.rvm.io | bash
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
curl: (23) Failed writing body (0 != 861)

Could not download 'https://github.com/rvm/rvm/archive/master.tar.gz'.
  curl returned status '23'.

Downloading https://bitbucket.org/mpapis/rvm/get/master.tar.gz
curl: (23) Failed writing body (0 != 15926)

Could not download 'https://bitbucket.org/mpapis/rvm/get/master.tar.gz'.
  curl returned status '23'.


I notice that rvm is also not installed in the user's home directory, it is installed in /usr/local/rvm.

Is this a known issue?

Thanks.

**Comment by bradallenfisher** [comment]
uggh! The vagrant box was installing something. SO SORRRY! ignore mumble mumble.

**Comment by hmtanbir** [comment]
Downloading https://github.com/rvm/rvm/archive/1.26.11.tar.gz
curl: (23) Failed writing body (0 != 860)

Could not download 'https://github.com/rvm/rvm/archive/1.26.11.tar.gz'.
  curl returned status '23'.

Downloading https://bitbucket.org/mpapis/rvm/get/1.26.11.tar.gz
curl: (23) Failed writing body (0 != 15926)

Could not download 'https://bitbucket.org/mpapis/rvm/get/1.26.11.tar.gz'.
  curl returned status '23'.

**Comment by bradallenfisher** [comment]
I am fairly certain this error happens when rvm is already installed globally. In which case all you need to do is add the user to the group  rvm.

**Comment by wkoszek** [comment]
I was impacted by this bug too. Unclear to me why it's the case, but I had to do:

```
rm -rf /usr/local/rvm
rm -rf /etc/profile.d/rvm
groupdel rvm
```

I think it's a regression. AFAIR I could have global RVM installed and have individual users install RVM and have them use whichever Ruby they want. At least that would be my expectation.

**Comment by ngolovin** [comment]
Got this error too on cygwin-windows,
actually searching a workaround with wget...

**Comment by kovenko** [comment]
unset rvm_path
unset GEM_HOME
