### ISSUE TITLE
Please add Debian Fork "Devuan" to supported systems

### ISSUE THREAD

**Issue by davidgross** [rvm/rvm#3477]
I was trying out Devuan ([devuan.org](http://devuan.org)), and discovered that RVM does not support Debuan. Devuan is quite new, so this was not a big surprise to me.  I would like to see RVM add support for it, I got it working by copying the debian requirements file and running a s/debian/devuan/g on it, and adding an entry for Devuan in the detect_system script, which was a copy of the debian one a line above again replacing debian with devuan. 

Thanks!

**Comment by davidgross** [comment]
Looks like I am not the only one needing this.

https://github.com/rvm/rvm/issues/3482 appears to have the same solution I had.

**Comment by havenwood** [comment]
Closed by https://github.com/rvm/rvm/pull/3488
