### ISSUE TITLE
Issue: Above files contains `PATH=` with no `$PATH` inside, this can break RVM

### ISSUE THREAD

**Issue by 1one8seven7** [rvm/rvm#3478]
Hello,
I recently installed rvm and got this warning at the end of the install (also ran 'rvm --debug get head'). Can you guide me in fixing the PATH in order for rvm not to break? Thank you...

➜  ~  rvm --debug get head
Downloading https://get.rvm.io
Running(17): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://get.rvm.io -o /Users/patrickwalker/.rvm/archives/rvm-installer
Detected GPG program: ''
No GPG software exists to validate rvm-installer, skipping.
Running(1): Selected RVM branch master
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
Running(1): Running(15): curl --fail --location --max-redirs 10 --connect-timeout 30 --retry-delay 2 --retry 3 -sS https://github.com/rvm/rvm/archive/master.tar.gz -o /Users/patrickwalker/.rvm/archives/rvm-master.tgz
Running(1): No PGP url given, skipping.
Running(1): Running(5): tar xzf /Users/patrickwalker/.rvm/archives/rvm-master.tgz --strip-components 1
step> 'print_install_header' started

Upgrading the RVM installation in /Users/patrickwalker/.rvm/
step< 'print_install_header' finished with status 0 in 0 seconds
step> 'cleanse_old_entities' started
step< 'cleanse_old_entities' finished with status 0 in 0 seconds
step> 'create_install_paths' started
step< 'create_install_paths' finished with status 0 in 0 seconds
step> 'load_custom_flags' started
step< 'load_custom_flags' finished with status 0 in 0 seconds
step> 'save_custom_flags' started
step< 'save_custom_flags' finished with status 0 in 0 seconds
step> 'install_rvm_directories' started
step< 'install_rvm_directories' finished with status 0 in 0 seconds
step> 'install_rvm_files' started
step< 'install_rvm_files' finished with status 0 in 0 seconds
step> 'install_rvm_scripts' started
step< 'install_rvm_scripts' finished with status 0 in 1 seconds
step> 'cleanup_old_help_and_docs_files' started
step< 'cleanup_old_help_and_docs_files' finished with status 0 in 0 seconds
step> 'install_rvm_hooks' started
step< 'install_rvm_hooks' finished with status 0 in 0 seconds
step> 'remove_old_hooks' started
step< 'remove_old_hooks' finished with status 0 in 0 seconds
step> 'install_binaries' started
step< 'install_binaries' finished with status 0 in 0 seconds
step> 'install_gemsets' started
step< 'install_gemsets' finished with status 0 in 0 seconds
step> 'install_patchsets' started
step< 'install_patchsets' finished with status 0 in 1 seconds
step> 'install_man_pages' started
step< 'install_man_pages' finished with status 0 in 0 seconds
step> 'setup_configuration_files' started
step< 'setup_configuration_files' finished with status 0 in 0 seconds
step> 'setup_login_shell' started
step< 'setup_login_shell' finished with status 0 in 0 seconds
step> 'setup_user_profile' started
    RVM PATH line found in /Users/patrickwalker/.mkshrc /Users/patrickwalker/.profile /Users/patrickwalker/.bashrc /Users/patrickwalker/.zshrc.
    RVM sourcing line found in /Users/patrickwalker/.profile /Users/patrickwalker/.bash_profile /Users/patrickwalker/.zlogin.
step< 'setup_user_profile' finished with status 0 in 0 seconds
step> 'cleanse_old_environments' started
step< 'cleanse_old_environments' finished with status 0 in 0 seconds
step> 'migrate_old_gemsets' started
step< 'migrate_old_gemsets' finished with status 0 in 0 seconds
step> 'migrate_defaults' started
step< 'migrate_defaults' finished with status 0 in 0 seconds
step> 'migrate_environments_and_wrappers' started
step< 'migrate_environments_and_wrappers' finished with status 0 in 0 seconds
step> 'restore_missing_environments' started
step< 'restore_missing_environments' finished with status 0 in 0 seconds
step> 'record_ruby_configs' started
step< 'record_ruby_configs' finished with status 0 in 0 seconds
step> 'update_gemsets_install_rvm' started
step< 'update_gemsets_install_rvm' finished with status 0 in 0 seconds
step> 'configure_autolibs' started
step< 'configure_autolibs' finished with status 0 in 0 seconds
step> 'update_yaml_if_needed' started
step< 'update_yaml_if_needed' finished with status 0 in 0 seconds
step> 'cleanup_tmp_files' started
step< 'cleanup_tmp_files' finished with status 0 in 0 seconds
step> 'record_installation_time' started
step< 'record_installation_time' finished with status 0 in 0 seconds
step> 'print_install_footer' started
Upgrade of RVM in /Users/patrickwalker/.rvm/ is complete.
step< 'print_install_footer' finished with status 0 in 0 seconds
step> 'display_thank_you' started

# 1one8seven7,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

step< 'display_thank_you' finished with status 0 in 0 seconds
step> 'display_notes' started
In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

/Users/patrickwalker/.zshrc:56:export PATH="/Users/patrickwalker/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/mysql/bin:/Users/patrickwalker/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/patrickwalker/.rvm/bin"

  * WARNING: Above files contains `PATH=` with no `$PATH` inside, this can break RVM,
    for details check https://github.com/rvm/rvm/issues/1351#issuecomment-10939525
    to avoid this warning append #PATH.

  * No new notes to display.

step< 'display_notes' finished with status 0 in 0 seconds
__rvm_rm_rf already gone: /Users/patrickwalker/.rvm/tmp/62619*

**Comment by havenwood** [comment]
Remove the offending line from your ~/.zshrc file (line 56 as shown above). If you're using RVM instead of rbenv you probably don't want rbenv in your PATH at all.

Here's an example of appending to PATH instead of replacing it:
```sh
PATH="$PATH:/appended:/more/stuff"
```

**Comment by havenwood** [comment]
Please stop by and [visit us on IRC](http://webchat.freenode.net/?channels=rvm) if you'd like some help setting up your PATH.
