### ISSUE TITLE
build working ruby-1.9.2-p330 on OSX 10.10

### ISSUE THREAD

**Issue by rajarajansn** [rvm/rvm#3480]
i had ruby 1.8.6 and wanted to install 1.9.2 but it gave me the below error. Please help

$ rvm install 1.9.2
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/ruby-1.9.2-p330.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.

RVM does not know how to build working ruby-1.9.2-p330 on OSX 10.10,
if you know please let us know by opening a ticket with instructions here:

    https://github.com/wayneeseguin/rvm/issues

$

**Comment by havenwood** [comment]
Closing as a duplicate of https://github.com/rvm/rvm/issues/3099. You may be able to get 1.9.2 to compile with a [pkgsrc](https://pkgsrc.joyent.com/install-on-osx/) gcc. Although also past end-of-life, 1.9.3 has been much more recently patched and compiles for me on OS X.

Ruby 1.9 is past end-of-life and has known security vulnerabilities. It also doesn't receive bug fixes so it increasingly gets more and more difficult to install on various platforms as time goes by. Ruby 2.0 is in maintenance mode. If you can, switch to Ruby 2.1+.
