### ISSUE TITLE
-bash: /root/.rvm/rvm.sh: No such file or directory

### ISSUE THREAD

**Issue by mamatharao** [rvm/rvm#3485]
-bash: /root/.rvm/rvm.sh: No such file or directory error

**Comment by havenwood** [comment]
It's not recommended to install RVM as root. Install RVM as a non-root user without sudo.

**Comment by havenwood** [comment]
Please visit us in the [#RVM channel](http://webchat.freenode.net/?channels=rvm) if you like any assistance installing as a non-root user or finding the bash dotfile that is improperly sourcing.
