### ISSUE TITLE
Jruby 1.7.19 causes build failure which is fixed by >= Jruby 1.7.20

### ISSUE THREAD

**Issue by dg-ratiodata** [rvm/rvm#3486]
Jruby 1.7.19 causes [build failure](https://travis-ci.org/cucumber/aruba/jobs/75084948#L2528) which is fixed by >= Jruby 1.7.20. Any chance to get an update very soon? Or do you even plan to go upto 900 instead, which would be fine for me as well.

**Comment by havenwood** [comment]
Yes, we're hoping to do a release soon. In the meantime you can get the latest RVM with `rvm get master`, which includes definitions for JRuby 9.0.0.0 and 1.7.21.

**Comment by dg-ratiodata** [comment]
Great. Hope the guys at `travis` include your release as fast as possible. :-) I'm not keen to exlude those tests from the test suite.
