### ISSUE TITLE
Bundler::InstallError:

### ISSUE THREAD

**Issue by gauthamk89** [rvm/rvm#3487]
I am facing the below error.

Bundler::InstallError: There was an error while trying to write to Gemfile.lock. It is likely that 
you need to allow write permissions for the file at path: 
/tmp/hadoop-tmp/nm-local-dir/usercache/mapr/filecache/1158/dev.tar/dev/<folder_name>/Gemfile.lock
     lock at /usr/local/rvm/gems/jruby-1.7.20/gems/bundler-1.10.0/lib/bundler/definition.rb:272
     lock at /usr/local/rvm/gems/jruby-1.7.20/gems/bundler-1.10.0/lib/bundler/environment.rb:34
    setup at /usr/local/rvm/gems/jruby-1.7.20/gems/bundler-1.10.0/lib/bundler/runtime.rb:44
    setup at /usr/local/rvm/gems/jruby-1.7.20/gems/bundler-1.10.0/lib/bundler.rb:126
   (root) at /usr/local/rvm/gems/jruby-1.7.20/gems/bundler-1.10.0/lib/bundler/setup.rb:18
  require at org/jruby/RubyKernel.java:1072
   (root) at /usr/local/rvm/rubies/jruby-1.7.20/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1

File permissions are fine. not sure why it is trying to modify the Gemfile.lock as we have bundled all the required files in the tar file. Which is passed as an archive to mapreduce program.

**Comment by havenwood** [comment]
What command are you running? From what directory? A single-user install of RVM is recommended. Do you need a system install?

**Comment by gauthamk89** [comment]
I am runnning a mapreduce job. and the map script has a bundle exec command during which i seem to see this error.

**Comment by havenwood** [comment]
A single-user install of RVM in the user's home directory makes permissions easy. You can run `rvm fix-permissions` to fix permissions on the RVM side of things and if you're using a system install put your user in the rvm group.

I don't understand the Gemfile.lock permissions problem or why it's writing to `/tmp` in the first place. Is this RVM-related or is it a Bundler issue?
