### ISSUE TITLE
RVM stable release not defaulting to Ruby 2.2.2

### ISSUE THREAD

**Issue by mikelorant** [rvm/rvm#3490]
The stable release of RVM still defaults to 2.2.1 in the known_strings, however 2.2.2 has been released since April. Considering 2.2.2 fixes a security vulnerability, using rvm install 2.2 is installing vulnerable version.

**Comment by havenwood** [comment]
It is a good idea to update RVM with `rvm get master` since stable is only updated with new versioned releases of RVM. We are working on a new release.

**Comment by pratik60** [comment]
Just had the same thing...In fact, it installs ruby 2.2.1 and 2.2.2. But defaults to using 2.2.1. Weird!

**Comment by havenwood** [comment]
A release is planned *soon* but 2.2.3 is available now with:
```sh
rvm get master
```

**Comment by jasonm23** [comment]
Get master doesn't solve this.

    rvm use ruby-2.2.2@global --default

No good.

    rvm use ruby-2.2.1@global --default

Works as expected

**Comment by pkuczynski** [comment]
This issue is outdated and should be closed. Latest stable ruby version is 2.3.1
