### ISSUE TITLE
Why are their errors with the Master Branch?

### ISSUE THREAD

**Issue by nitetrik** [rvm/rvm#3496]
I was wondering why their are errors with master branch for Mac OS X?

**Comment by havenwood** [comment]
The OS X tests are timing out on TravisCI.

**Comment by skaes** [comment]
The OS X build started failing after the maven upgrade to maven 3.3.3 https://travis-ci.org/rvm/rvm/builds/71310416. @havenwood can you please figure out what's wrong?

**Comment by havenwood** [comment]
@skaes The OS X tests are taking so long overall on TravisCI that it's exceeding their maximum time limit. It still times out with the maven version reverted: https://travis-ci.org/rvm/rvm/builds/76501780

I haven't had time yet to investigate speeding up the OS X tests in general. @mpapis has mentioned we should be able to improve it, hopefully without caching dependencies which has its own problems.

**Comment by mpapis** [comment]
after adding binaries the tests should speed up a bit, the other thing is updating tests to work with versions that are available on travis, usually series of sed commands like:
```bash
sed -e 's/2\.1\.2/2.2.3/' -e 's/2\.1\.0/2.2.0/' -e 's/2\.0\.0/2.1.0/' -i'' -r fast/
```
it helped in the past, but this is time consuming task

**Comment by mpapis** [comment]
also it should be possible to extend the max test time

**Comment by havenwood** [comment]
It seems using JRuby's mvnw wrapper in #3502 speeds things up enough for OS X builds to consistently pass. Closing since the build is now green.
