### ISSUE TITLE
Cannot build rbx-2.5.2 on ArchLinux

### ISSUE THREAD

**Issue by boxofrox** [rvm/rvm#3497]
`rbx-2.5.2` requires LLVM 3.0-3.5 to install.  The Arch Linux package for LLVM is at 3.6.2-2.  A separate package for LLVM 3.5 was created, `llvm35` and `llvm35-libs`.

When running `rvm install rbx-2.5.2`, rvm tries to install `llvm` instead of `llvm35` and results in a build error. 
#### Expected Behavior

rvm recognizes llvm35 is required by rbx on ArchLinux.

```
 ▶ rvm install rbx-2.5.2
Searching for binary rubies, this might take some time.
No binary rubies available for: arch/libc-2.21/x86_64/rbx-2.5.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for arch.
Requirements installation successful.
ruby-2.1.3 - #gemset created /home/charetjc/.rvm/gems/ruby-2.1.3@rubinius
ruby-2.1.3 - #generating rubinius wrappers - please wait
ruby-2.1.3@rubinius - #regenerating binstubs - please wait
rbx-2.5.2 - #downloading rubinius-2.5.2, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.1M  100 11.1M    0     0  3259k      0  0:00:03  0:00:03 --:--:-- 3258k
No checksum for downloaded archive, recording checksum in user configuration.
rbx-2.5.2 - #extracting rubinius-2.5.2 to /home/charetjc/.rvm/src/rbx-2.5.2 - please wait
ruby-2.1.3@rubinius - #bundle install - please wait
rbx-2.5.2 - #configuring - please wait
Error running 'env /home/charetjc/.rvm/wrappers/ruby-2.1.3@rubinius/ruby ./configure --prefix=/home/charetjc/.rvm/rubies/rbx-2.5.2 ',
showing last 15 lines of /home/charetjc/.rvm/log/1440122512_rbx-2.5.2/configure.log
Checking gcc: found
Checking g++: found
Checking bison: found

Detected old configuration settings, forcing a clean build
  Checking for 'llvm-config': only LLVM 3.0-3.5 is supported
ABORT: unable to set up LLVM

 ▶ sudo pacman -S llvm35
[sudo] password for charetjc:
resolving dependencies...
looking for conflicting packages...
:: llvm35 and llvm are in conflict. Remove llvm? [y/N] y

Packages (3) llvm-3.6.2-2 [removal]  llvm35-libs-3.5.2-1  llvm35-3.5.2-1

Total Download Size:    20.81 MiB
Total Installed Size:  123.86 MiB
Net Upgrade Size:       26.24 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages ...
 llvm35-libs-3.5.2-1-x86_64                      7.4 MiB  3.70M/s 00:02 [########################################] 100%
 llvm35-3.5.2-1-x86_64                          13.4 MiB  6.55M/s 00:02 [########################################] 100%
(2/2) checking keys in keyring                                          [########################################] 100%
(2/2) checking package integrity                                        [########################################] 100%
(2/2) loading package files                                             [########################################] 100%
(2/2) checking for file conflicts                                       [########################################] 100%
(3/3) checking available disk space                                     [########################################] 100%
(1/1) removing llvm                                                     [########################################] 100%
(1/2) installing llvm35-libs                                            [########################################] 100%
(2/2) installing llvm35                                                 [########################################] 100%

 ▶ rvm install rbx-2.5.2
rbx-2.5.2 - #removing src/rbx-2.5.2 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: arch/libc-2.21/x86_64/rbx-2.5.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for arch.
Installing requirements for arch.
Updating system - please wait
Installing required packages: llvm - please wait
Error running 'requirements_arch_libs_install llvm',
showing last 15 lines of /home/charetjc/.rvm/log/1440123129_rbx-2.5.2/package_install_llvm.log
+__rvm_try_sudo:33> command_to_run=( __rvm_sudo -p '%p password required for ''pacman -Sy --needed --noconfirm llvm'': ' /usr/bin/env 'PATH=/home/charetjc/.rvm/gems/ruby-2.1.2@gmi-diamond-tracker/bin:/home/charetjc/.rvm/gems/ruby-2.1.2@global/bin:/home/charetjc/.rvm/rubies/ruby-2.1.2/bin:/home/charetjc/.rvm/bin:/home/charetjc/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/sbin:/usr/sbin' pacman -Sy --needed --noconfirm llvm )
+__rvm_try_sudo:40> __rvm_sudo -p '%p password required for ''pacman -Sy --needed --noconfirm llvm'': ' /usr/bin/env 'PATH=/home/charetjc/.rvm/gems/ruby-2.1.2@gmi-diamond-tracker/bin:/home/charetjc/.rvm/gems/ruby-2.1.2@global/bin:/home/charetjc/.rvm/rubies/ruby-2.1.2/bin:/home/charetjc/.rvm/bin:/home/charetjc/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/sbin:/usr/sbin' pacman -Sy --needed --noconfirm llvm
+__rvm_sudo:2> sudo -p '%p password required for ''pacman -Sy --needed --noconfirm llvm'': ' /usr/bin/env 'PATH=/home/charetjc/.rvm/gems/ruby-2.1.2@gmi-diamond-tracker/bin:/home/charetjc/.rvm/gems/ruby-2.1.2@global/bin:/home/charetjc/.rvm/rubies/ruby-2.1.2/bin:/home/charetjc/.rvm/bin:/home/charetjc/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/sbin:/usr/sbin' pacman -Sy --needed --noconfirm llvm
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
resolving dependencies...
looking for conflicting packages...
:: llvm and llvm35 are in conflict. Remove llvm35? [y/N] error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)

:: llvm and llvm35 are in conflict
+__rvm_try_sudo:40> return 1
+requirements_arch_libs_install:2> return 1
Requirements installation failed with status: 1.

```

**Comment by franklinyu** [comment]
Same problem in OS X.

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.

**Comment by boxofrox** [comment]
Thanks @pkuczynski.  I gave the install another go and ran into other compilation issues.  It seems building rubinius on Arch Linux is fairly broken.  Unfortunately, I don't have time to spare to poke at it, and I'm not entirely sure what to poke at, so I'll understand if Arch Linux is considered an unsupported platform.

I leave behind these gists of my errors building rbx-2.5.2 and rbx-2.5.8.

rbx-2.5.2: https://gist.github.com/boxofrox/030c68dc010fad701018d429ed6a1bc2
rbx-2.5.8: https://gist.github.com/boxofrox/308c5430d29bbe8e886334dfebcc4519

On a side note, I did try rbx-3.67 and it wants the `llvm` package.  A bit ironic.  Here's my gist of that error.

rbx-3.67: https://gist.github.com/boxofrox/d246eedac516e914aa1b2ad04a08be5c

**Comment by pkuczynski** [comment]
What we could do for rbx-2.5.2 and 2.5.8 is to pass additional `-Wno-error` flag for the compilation as described in here: http://stackoverflow.com/questions/11561261/how-to-compile-without-warnings-being-treated-as-errors

Why llvm is ironic? How should that behave on Arch?

We indeed require clang35 package on Arch. Should that be dependant on the Arch version? Which package is newer? After reading a bit it seems that clang is newer - correct? We can change this dependency (or maybe change it only for some newer version of Arch?)

I am happy to continue working on this, but would need someone to pair me with testing... Would you mind helping me?

**Comment by boxofrox** [comment]
> Why is llvm irconic?

By ironic, I mean just as this patch lands to switch from `llvm` to `llvm35`, rbx-3.67 requires `llvm`, which means if this bug was ignored, we'd be fine with the rbx-3.x series.

I'm no expert, but as I understand this, llvm 3.6 is not backward compatible.  Arch maintains the `llvm35` to provide llvm 3.5 for projects that haven't updated to support llvm 3.6, which `rbx-2.x` appears to be.  The `llvm` package on Arch still progress to the latest version of llvm; 3.6 to 3.7 and so on to 3.9.  With `rbx-3.x`, rubinius updated their build/source code to support llvm 3.6+, which means `rbx-3.x` won't build with llvm 3.5 due to the backwards-incompatibility.  If later, another backwards-incompatible version of llvm is released, say 4.0, then Arch maintainers will release `llvm39` to ease the transition for developers.  Specifically, both `llvm` and `llvm39` can be installed at the same time.

Wrt clang, `clang35` is a snapshot of the 3.5 version, which `clang` follows the latest release.  I see Arch's `clang` and `clang35` packages don't rely on `llvm35`, and are effectively stand-alone.

> Would you mind helping me?
Sure.  I can run the compile and report the results.  That doesn't require much time.  I just have little time to devote to troubleshooting, which is a slow process for me.

**Comment by franklinyu** [comment]
| Rubinius | LLVM 3.5 | LLVM 3.6+ |
|----------|----------|-----------|
| 2.x      | :o:      | :x:       |
| 3.x      | :x:      | :o:       |

Is that correct?

**Comment by boxofrox** [comment]
@franklinyu, yes that is correct.

**Comment by boxofrox** [comment]
Well, I spoke too soon a few comments back \[[1]].  Arch packages `llvm` and `llvm35` conflict, so they cannot be installed at the same time.  I erroneously thought I already had `llvm` installed when `pacman -S llvm35` succeeded without issue.

This means an Arch user will have to shuffle their installed packages--if any--in order to build `rbx-2.x`.  I don't think rvm can alleviate this.  Maybe if there were a way for rvm to present pacman's conflict resolution prompt to the user, that would be an improvement.  I do not recommend automatically confirming.

Found the reason \[[2]] for the `rbx-2.x` requirement of `llvm35`; changes to the JIT system in llvm 3.6.

[1]: https://github.com/rvm/rvm/issues/3497#issuecomment-259762107
[2]: https://github.com/rubinius/rubinius/issues/3553

\[1]: https://github.com/rvm/rvm/issues/3497#issuecomment-259762107
\[2]: https://github.com/rubinius/rubinius/issues/3553

**Comment by boxofrox** [comment]
I tried building `rbx-2.5.2` and `rbx-2.5.8` again with `CXXFLAGS=-Wno-error`.  Warnings no longer seem to cause the build to fail, but build errors do occur.  Log files are provided as gists.

rbx-2.5.2: https://gist.github.com/boxofrox/1c8384de00dde8ef5125166870214bb2 (build error)
rbx-2.5.8: https://gist.github.com/boxofrox/888550bca192e1ce7908295f70d049e1 (build error)

**Comment by pkuczynski** [comment]
@boxofrox would you like to try with a fix I prepared? `rvm get branch /bugfix/3497-rbx-2-arch` and then `rvm install ...`

**Comment by boxofrox** [comment]
Will do.  rbx-2.5.2 still complains about static template specialization.  will let rbx-2.5.8 build overnight and finish up rbx.3.0.x tomorrow, then post my results.

**Comment by pkuczynski** [comment]
Please post gist for every version (incl config.log and make.log) and we will try to fix it

**Comment by boxofrox** [comment]
I found a configure.log alongside the rake.log in `~/.rvm/log/123_rbx-2.5.x/`.  I don't see a make.log.  Are you referring to rake.log or is make.log located elsewhere?

**Comment by pkuczynski** [comment]
`Make.log` is created after `configure.log` - unless the process fails. You can gist whole `~/.rvm/log/123_rbx-2.5.x/` folder, so I can see if there are any hints inside...

**Comment by pkuczynski** [comment]
And btw. thanks for all your help! :)

**Comment by boxofrox** [comment]
My pleasure and thanks for taking the time to pursue a fix.

Not exactly sure what you mean by every version, but `rvm list known` shows rbx-1.4.3, rbx-2.5.8, and rbx-3.69, so I've attempted those.  Keeping rbx-2.5.2 in the loop since this issue originated with that version.  If I misinterpreted, please correct me.

rbx-1.4.3: https://gist.github.com/boxofrox/d704aab7b87a76c200a30f42eac755c5 :boom:
rbx-2.5.2: https://gist.github.com/boxofrox/37f9e643134fd4540a4c31b7c041b551 :boom:
rbx-2.5.8: https://gist.github.com/boxofrox/18e9ae2f8840c36cc641db77a2b07345 :boom:
rbx-3.69: https://gist.github.com/boxofrox/7424126387177c128cdb62d65c844529 :tada:

I put all the files from `~/.rvm/log/123_rbx-0.0.0/` in the gists, but still no make.log found, even for the rbx-3.69 install which completed.

rbx-1.4.3 has a nit-pick.  `rvm install rbx-1` does not checkout the `v1.4.3` branch, but rather `v1` which fails, but doesn't stop the build from moving forward, and eventually installs the [latest?] version (as seen in the first gist file).  The second gist file `b-rbx-1.4.3-install-01.txt` shows that rbx-1.4.3 also relies on clang35 and llvm35.  I patched rvm below and tried again.

```diff
diff --git a/scripts/functions/requirements/arch b/scripts/functions/requirements/arch
index c39d463e..5f5aef5d 100644
--- a/scripts/functions/requirements/arch
+++ b/scripts/functions/requirements/arch
@@ -80,6 +80,10 @@ requirements_arch_define()
       undesired_check clang llvm llvm-libs
       requirements_check clang35 llvm35 llvm35-libs patch curl zlib readline autoconf automake diffutils make libtool bison
       ;;
+    (rbx-1.*|rubinius-1.*)
+      undesired_check clang llvm llvm-libs
+      requirements_check clang35 llvm35 llvm35-libs patch curl zlib readline autoconf automake diffutils make libtool bison
+      ;;
     (*-head)
       requirements_check gcc patch curl zlib readline autoconf automake diffutils make libtool bison sqlite git
       ;;
```

gist file `c-rbx-1.4.3-install-02.txt` and those following pertain to the last build attempt.  It failed to link two symbols `llvm::sys::getDefaultTargetTriple()` and `llvm::DataLayout::getStringRepresentation() const`.

As noted before, rbx-2.5.2 fails due to some *static specialization template* error.  Googling that turned up reports that C++ does not support such a use-case in the language spec while Visual Studio will compile such code as is.  If this is correct, then I don't expect rbx-2.5.2 to build on linux without patching that.  The Archlinux distro may have such a patch if I can find it.

rbx-2.5.8 fails to link the same two symbols as rbx-1.4.3.  I built 2.5.8 before 1.4.3, and included an extra gist file `d-misc.txt` where I used `objdump -t` on the `/usr/lib/lib*.a` files to find the missing symbols.

rbx-3.69 finally built :tada:, though I did run into a snag.  If locale is set to LC_LANG=C, then gem files fail to verify.  Switching locale to LC_LANG=en_US.UTF-8 resolved that.

**Comment by boxofrox** [comment]
Arch's build script for rubinius-2.5.2 has no patch for the static template specialization.  The error may be a red herring.

Moving forward, I'll stop testing rbx-2.5.2.  I don't need that specific version, and rbx-2.5.8 should be a compatible replacement if we sort out its link errors.  If you disagree, I'll keep it in the rotation.

**Comment by khalilfazal** [comment]
@boxofrox sorry for joining in late, but how did you get rbx-3.69 to install? I'm currently at the point where rvm is trying to install llvm35. I currently have llvm-3.9.1 installed from pacman.

**Comment by pkuczynski** [comment]
I extended the undesired clang/llvm for rbx-1.* as you suggested. 

I am tempting to ignore the failing builds for rbx-1 and 2.5.2. They are old versions and don't think we need to support them.

For 2.5.8 - if you find anything, I am happy to apply a patch. Just let me know what should be done or create PR.

I will now merge this branch to `master`, so it will be released with the next version or RVM.

**Comment by khalilfazal** [comment]
@boxofrox I got it to work. thanks!
