### ISSUE TITLE
rails install ERROR: While executing gem (NoMethodError)undefined method `ord' for nil:NilClass

### ISSUE THREAD

**Issue by awladliton** [rvm/rvm#3498]
```
Ububtu 14.04
rvm 1.26.11
ruby 2.1.0p0
```

rvm list :

```
rvm rubies

=* ruby-2.1.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

which ruby : /home/awlad/.rvm/rubies/ruby-2.1.0/bin/ruby

which rvm : /home/awlad/.rvm/bin/rvm

which bundle: /usr/bin/bundle

 RubyGems Environment:
- RUBYGEMS VERSION: 2.4.8
- RUBY VERSION: 2.1.0 (2013-12-25 patchlevel 0) [x86_64-linux]
- INSTALLATION DIRECTORY: /home/awlad/.rvm/gems/ruby-2.1.0
- RUBY EXECUTABLE: /home/awlad/.rvm/rubies/ruby-2.1.0/bin/ruby
- EXECUTABLE DIRECTORY: /home/awlad/.rvm/gems/ruby-2.1.0/bin
- SPEC CACHE DIRECTORY: /home/awlad/.gem/specs
- SYSTEM CONFIGURATION DIRECTORY: /home/awlad/.rvm/rubies/ruby-2.1.0/etc
- RUBYGEMS PLATFORMS:
  - ruby
  - x86_64-linux
- GEM PATHS:
  - /home/awlad/.rvm/gems/ruby-2.1.0
  - /home/awlad/.rvm/gems/ruby-2.1.0@global
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/
- SHELL PATH:
  - /home/awlad/.rvm/gems/ruby-2.1.0/bin
  - /home/awlad/.rvm/gems/ruby-2.1.0@global/bin
  - /home/awlad/.rvm/rubies/ruby-2.1.0/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /home/awlad/.rvm/bin
  - /home/awlad/.rvm/bin
  - /home/awlad/.rvm/bin

rvm use 2.1.0 --default then when i run gem install rails -v 4.1.1 I am getting: ERROR:  While executing gem ... (NoMethodError)
    undefined method 'ord' for nil:NilClass

UPDATE:

After creating new gemset "my_gemset"  with ruby 2.1.0 in a project directory when i use this new gemset and trying to install bundle I got :

home/awlad/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bundler (LoadError)
        from /home/awlad/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in`require'
        from /usr/bin/bundle:7:in `<main/>

What am I missing here ? How can I get rid of this issue?

**Comment by havenwood** [comment]
Install the Bundler gem on the Ruby you're using with:
```sh
gem install bundler
```

**Comment by awladnas** [comment]
when I am trying to install bundle i got : home/awlad/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in require': cannot load such file -- bundler (LoadError) from /home/awlad/.rvm/rubies/ruby-2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:inrequire'
from /usr/bin/bundle:7:in `

**Comment by awladliton** [comment]
I already described when I am trying to install bundle I am getting : ERROR: While executing gem ... (NoMethodError)
undefined method 'ord' for nil:NilClass

**Comment by havenwood** [comment]
Having the Bundler gem installed on a Ruby you're not using isn't going to work. Install the Bundler gem on the Ruby you're using.

Just to be clear, I'm saying `gem install bundler` before you `bundle install`.

**Comment by awladliton** [comment]
Ok. lets be clear. I know I am having this error for bundler for specific ruby version is not installed. 
I have two versions of ruby (2.2.0, 2.1.0). If I use rvm use 2.2.0 and then bundler is already installed and working. If I want to use 2.1.0 then I have followed:  
rvm use 2.1.0 then gem install bundle then I have got above error.

**Comment by havenwood** [comment]
Could you confirm what you get for `gem which bundle` and `which bundler` with Ruby 2.1.0?

What version of RubyGems are you on? Same error after updating to latest RubyGems with `rvm rubygems latest` or `gem update --system`? A newer version of RubyGems does ship with Ruby 2.1.7, which is the current Ruby 2.1 version.

**Comment by awladliton** [comment]
rubygems is on latest version. which bundle give me: /usr/bin/bundle and hen I am using rvm use 2.2.1 then which bundle give me: /home/awlad/.rvm/gems/ruby-2.2.1/bin/bundle

**Comment by havenwood** [comment]
What do you get for `gem which bundle` with Ruby 2.1.0?

**Comment by havenwood** [comment]
I'd have expected `/home/awlad/.rvm/gems/ruby-2.1.0/bin/bundle` since you have Bundler installed on Ruby 2.1.0.

**Comment by awladliton** [comment]
I did not install bundler on ruby 2.1.0. When I was trying to install it on ruby 2.1.0 then I got: While executing gem ... (NoMethodError)
    undefined method 'ord' for nil:NilClass

**Comment by awladliton** [comment]
I got for `gem which bundler` with Ruby 2.1.0 : 
ERROR:  Can't find ruby library file or shared library bundler

When trying gem install bundle i got: 
ERROR:  While executing gem ... (NoMethodError)
    undefined method `ord' for nil:NilClass

**Comment by havenwood** [comment]
It looks like a Ruby [bug was fixed](https://bugs.ruby-lang.org/issues/9498#change-45180) where this error crops up when there's an available local DNS resolver without access to the internet. I would strongly suggest using the latest TEENY version of 2.1, which is version 2.1.7 at the moment.

Running `gem install bundler --debug` might help show what's going on but do upgrade to 2.1.7 if you can!

**Comment by awladliton** [comment]
Thanks for your support. I will move to 2.1.7.

**Comment by rahuldavd** [comment]
I have downloaded openssl-0.9.8k_X64.zip and followed link https://github.com/hicknhack-software/rails-disco/wiki/Installing-puma-on-windows#install-the-puma-gem but on trying to install gem install puma -- --with-opt-dir=c:\openssl but it is giving error:-193: %1 is not a valid Win32 application. - C:/Ruby22/lib/ruby/2.2.0/i386-mingw32/openssl.so
i have followed each step but couldn't get to install Puma. Suggest!

**Comment by pkuczynski** [comment]
@Rahuldavd please open separate issue for your problem

**Comment by olleicua** [comment]
> gem install bundler

This doesn't resolve the issue. It's rude to close the thread without waiting to see if the issue is resolved.

**Comment by Rizwanahd** [comment]
$ rvm pkg install openssl
$ rvm remove 2.7.0
$ rvm install 2.7.0 --with-openssl-dir=$HOME/.rvm/usr
$ gem install bundler
