### ISSUE TITLE
Unable to start Rails server or update Ruby and Rails versions on Mac OS X Yosemite

### ISSUE THREAD

**Issue by jacqueline-homan** [rvm/rvm#3500]
![rvm_railsnotworking1](https://cloud.githubusercontent.com/assets/3537889/9572754/5839a4b2-4f81-11e5-8aa4-0cb3d58f0b8e.png)

![rvm_railsnotworking](https://cloud.githubusercontent.com/assets/3537889/9572711/09717cf6-4f81-11e5-9fff-f2e48be458b5.png)

![rvm_railsnotworking2](https://cloud.githubusercontent.com/assets/3537889/9572997/999b68d4-4f84-11e5-8a25-ab25b43b5c47.png)
![rvm_railsnotworkinkg3](https://cloud.githubusercontent.com/assets/3537889/9573001/a248bb4e-4f84-11e5-89c3-b55a1bf6b4e6.png)

 I don't uderstand. It was working just fine yesterday. Now that I am already missing my deadline for a technical article I needed to have done two hours ago, I can't get it to work for me and I needed it for the article I'm doing :(

**Comment by digitalfrost** [comment]
Try
```
gem update --system
```
this should update Rubygems and resolve your initial error.
