### ISSUE TITLE
Can't install Ruby 2.1.6 on Ubuntu 14.04

### ISSUE THREAD

**Issue by santosh** [rvm/rvm#3511]
I am trying to install version 2.1.6 on my Ubuntu and here is the last line of the command `rvm install 2.1.6`:

```sh
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/14.04/x86_64/ruby-2.1.6.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating systemsantosh password required for 'apt-get --quiet --yes update':
```

*[full output here](https://gist.github.com/anonymous/115f6c9e062d74545b23)*

I don't know why rvm is trying to update my system, even if my system is already upadate. Even after that it's not able to install.

**Comment by gcraenen** [comment]
I've got the same problem on Ubuntu 15.04.

**Comment by santosh** [comment]
Sometimes I think Windows was better. :/

**Comment by southwolf** [comment]
@santosh  Installing ruby requires some system library like zlib, libxml, openssl, etc. RVM will perform `apt-get update` & `apt-get install xxx` to get those required libs.

**Comment by pkuczynski** [comment]
Do you still encounter the issue? If so, please provide full log. Current one stops on RVM installing dependencies.

**Comment by santosh** [comment]
As of now, I've switched to Windows, and can't afford VM.

**Comment by pkuczynski** [comment]
Ok. Understood. I am keeping this closed then.
