### ISSUE TITLE
Suggested fix for Mavericks/10.9.5 Rubinius issues

### ISSUE THREAD

**Issue by MatzFan** [rvm/rvm#3513]
I see you have a few open rbx/mavericks related [issues](https://github.com/rvm/rvm/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+rubinius+mavericks) and hope this may help resolve them:

As elsewhere reported `rvm install rbx` fails for me trying to install v2.5.2 as follows:

```
Checking for 'llvm-config': Error: No such keg: /usr/local/Cellar/llvm
not found
ABORT: unable to set up LLVM
```

However, `rvm install rbx-2.5.8` works just fine, even without a homebrew installed llvm

```
$ rvm install rbx-2.5.8
Searching for binary rubies, this might take some time.
Found remote file http://binaries.rubini.us/osx/10.9/x86_64/rubinius-2.5.8.tar.bz2
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
rbx-2.5.8 - #configure
rbx-2.5.8 - #download
rbx-2.5.8 - #validate archive
rbx-2.5.8 - #extract
rbx-2.5.8 - #validate binary
rbx-2.5.8 - #setup
rbx-2.5.8 - #gemset created /Users/me/.rvm/gems/rbx-2.5.8@global
rbx-2.5.8 - #importing gemset /Users/me/.rvm/gemsets/global.gems...............................................
rbx-2.5.8 - #generating global wrappers........
rbx-2.5.8 - #gemset created /Users/me/.rvm/gems/rbx-2.5.8
rbx-2.5.8 - #importing gemsetfile /Users/me/.rvm/gemsets/default.gems evaluated to empty gem list
rbx-2.5.8 - #generating default wrappers........
Macintosh:~ me$
```

Just wondered whether you could bump default rbx to 2.5.8 & fix these other issues? 

OS: 10.9.5 | rvm: 1.26.11 | rvm requirements ok | homebrew up to date & 'ready to brew'

**Comment by franklinyu** [comment]
Thank you for your information about alternative installing command. I did not know that there is binary since the default installation begin with compilation. It is really confusing to compile even when binary is available.

**Comment by franklinyu** [comment]
I am wondering if I can bump the version my self. Currently I found two:

* [/config/known](../blob/5bba5436866056717ff0bb8de8fe50bf6fa96fa8/config/known)
* [/config/known_strings](../blob/5f7e5f31a04e29937e2b82c2719db8d5a0a66380/config/known_strings)

I will try to submit a pull request with these two file updated, although I totally have no idea whether these are the hook for `rbx` to `rbx-2.5.2`. It would be appreciate if you would like to verify them.

**Comment by MatzFan** [comment]
Agree those files look reasonable candidates for determining the rbx default. Can't see a test for bumping default rbx (or other Ruby) but then I'm not familiar with RVM codebase/testing. Happy to do an rbx (re)install with latest RVM build if you do a PR. Be aware that I'm now on 10.10.5 - I like to stay no more than 1 OS behind :wink:

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.

**Comment by pkuczynski** [comment]
Duplicate of #3287
