### ISSUE TITLE
Can't copy gemset

### ISSUE THREAD

**Issue by matas-zanevicius** [rvm/rvm#3517]
I'm working on Linux Mint 17.2 Rafaela fresh install with latest updates.
I've installed rvm, ruby and rails by following this particular guide:
http://railsapps.github.io/installrubyonrails-ubuntu.html

I'd like to use gemsets so I create a gemset 'mygemset' like this

matas@matas ~ $ rvm gemset create mygemset
ruby-2.2.1 - #gemset created /home/matas/.rvm/gems/ruby-2.2.1@mygemset
ruby-2.2.1 - #generating mygemset wrappers........
matas@matas ~ $ rvm gemset list

gemsets for ruby-2.2.1 (found in /home/matas/.rvm/gems/ruby-2.2.1)
=> (default)
   global
   mygemset

Then I want to copy gems from default to mygemset:

matas@matas ~ $ rvm gemset copy default mygemset
Destination gemset 'mygemset' does not yet exist.

rvm gemset list command lists mygemset so it is there, I can do rvm gemset use mygemset and it works. Am I doing something wrong? or is this a bug related to my system? I'm desperate here please advice.

**Comment by matas-zanevicius** [comment]
I figured it out.
rvm gemset copy default 2.2.1@mygemset
does what expected.

**Comment by sharmasomesh8448** [comment]
worked for me too...thanks @matas-zanevicius
