### ISSUE TITLE
kernel_require.rb:54:in `require': cannot load such file -- win32/resolv (LoadError)

### ISSUE THREAD

**Issue by pioz** [rvm/rvm#3519]
I've installed Ruby `v2.2.3-p173` with rvm `v1.26.11` on Windows 10 under Cygwin `v2.871 (x64)`.
The installation went well, but when I run the command `gem install rails` I get the follow error:

```
$ gem install rails
/home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- win32/resolv (LoadError)
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:964:in `default_config_hash'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:982:in `block in lazy_initialize'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:975:in `synchronize'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:975:in `lazy_initialize'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:357:in `block in lazy_initialize'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:355:in `synchronize'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:355:in `lazy_initialize'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:515:in `fetch_resource'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:509:in `each_resource'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/resolv.rb:490:in `getresource'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:92:in `api_endpoint'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/source.rb:46:in `api_uri'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/source.rb:85:in `dependency_resolver_set'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/resolver/best_set.rb:23:in `block in pick_sets'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/source_list.rb:97:in `each'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/source_list.rb:97:in `each_source'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/resolver/best_set.rb:22:in `pick_sets'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/resolver/best_set.rb:28:in `find_all'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/resolver/installer_set.rb:151:in `find_all'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/resolver/installer_set.rb:54:in `add_always_install'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency_installer.rb:473:in `resolve_dependencies'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:238:in `install_gem'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:299:in `block in install_gems'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `each'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:295:in `install_gems'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/commands/install_command.rb:202:in `execute'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:307:in `invoke_with_build_args'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:168:in `process_args'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:138:in `run'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:54:in `run'
        from /home/Enrico/.rvm/rubies/ruby-2.2.3/bin/gem:21:in `<main>'
```

Any idea?

**Comment by brettneese** [comment]
Also having this issue with `ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-cygwin]` Cygwin `1.7.35` (via Babun). 

This page, badly Google Translated, suggests maybe installing Ruby 2.1.6? I'm doing that right now. http://qiita.com/sak_hrr/items/3a02005b44fdaefd3678

**Comment by pioz** [comment]
Let me know if with Ruby 2.1.6 works :D

**Comment by brettneese** [comment]
It did! I had some other issues though - I needed a patch for it
though. Not sure if that's specific to my version/configuration of cygwin
(Babun 1.2.0). Most details here:
http://xjlin0.github.io/tech/2015/04/14/babun-the-new-cygwin-for-ruby-rails-sinatra-and-nodejs/

I'm also having trouble with some weird fork errors when I do some things
but I suspect that's some corporate antivirus software interfering with my
machine. Let me know if you have any issues and I can walk you through them
- I spent upwards of 6 hours on this today.

It would be nice to get this fixed, but I'm afraid I don't know enough ruby
to even begin to postulate at what might be causing it.

**Comment by npalmius** [comment]
I am also having this problem with ruby-2.2.3 under Cygwin64 on Windows 10 with RVM 1.26.11. Downgrading to ruby-2.1.7 works fine, but obviously I would prefer to use 2.2 if possible.

**Comment by pioz** [comment]
Any updates?

**Comment by Studioartcz** [comment]
I have same problem

**Comment by lauryndbrown** [comment]
I ran into this problem as well. Did anyone find  fix?

**Comment by npalmius** [comment]
I'm not sure if this is a good idea, but I managed to fix this issue (for ruby 2.3.0) by copying the `~/.rvm/src/ruby-2.3.0/ext/win32/lib/win32` folder to `~/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/win32`.

On the latest version of Cygwin I then also had to change the `dlload "kernel32"` line in `~/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/win32/resolv.rb` (line 39 in version 2.3.0) to `dlload "kernel32.dll"`.

**Comment by timotei** [comment]
What worked as a better solution was to ensure `libffi-devel` is installed. Then, win32 module is properly installed.

The last part with changing from `dlload "kernel32"` to `dlload "kernel32.dll"` is still needed though. Maybe it should be fixed in ruby itself?

**Comment by pkuczynski** [comment]
This issue has been already resolved in latest Ruby 2.4-preview: https://github.com/ruby/ruby/commit/1f2359000c429669f2ba1afc0ffd3186370181ef

**Comment by pkuczynski** [comment]
I prepared a patch for this issue, but do not have Windows machine to test. Can anybody help me with testing? You need to update rvm:

`rvm get branch /bugfix/issue-3519`

**Comment by pkuczynski** [comment]
I forgot to patch 2.3.1 correctly. @avamore could you please retry:

```
rvm remove 2.3.1
rvm get branch /bugfix/issue-3519
rvm install 2.3.1 --disable-binary
gem install bundler
```

Remember about reinstalling selected ruby version. Getting latest RVM is not enough...

**Comment by avamore** [comment]
Administrator@WIN-1CLD6RTQTL2 ~
$ gem install bundler
ERROR:  Loading command: install (Fiddle::DLError)
        can't load kernel32
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

Administrator@WIN-1CLD6RTQTL2 ~
$

**Comment by pkuczynski** [comment]
Could you gist output of all the commands I listed above?

**Comment by avamore** [comment]
<script src="https://gist.github.com/username/gist-id.js"></script>

**Comment by pkuczynski** [comment]
I think I found the problem. Can you try again:

```
rvm remove 2.3.1
rvm get branch /bugfix/issue-3519
rvm install 2.3.1 --disable-binary
gem install bundler
```

**Comment by avamore** [comment]
Yes! Sucess! I'll continue testing my code now.

**Comment by pkuczynski** [comment]
Happy to help. Will merge to master tomorrow.

**Comment by vegan22** [comment]
Can anyone help me out? I am trying to run a ruby file and get this error... Nothing helps :( 

root@kali:~/supertinder# ruby tinder.rb
/usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- watir-webdriver (LoadError)
	from /usr/local/lib/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from tinder.rb:6:in `<main>'

**Comment by mpapis** [comment]
@vegan22 you need to switch to rvm controlled ruby

to list rubies:
```bash
rvm list
```
and to use one:
```bash
rvm use ruby-2.3.3 # example version, pick one from the list
```

**Comment by vegan22** [comment]
What does it do?
