### ISSUE TITLE
Error compiling multiple rubies on PCBSD 10.2

### ISSUE THREAD

**Issue by Aevin1387** [rvm/rvm#3529]
I tried installing multiple rubies, and this same compilation issue came up. This seems to be an issue only on PCBSD 10.2, FreeBSD 10.2 it installs fine. My guess is that it has to do with libressl being installed. Rubies tested: ruby-1.9.3-p551, ruby-2.0.0-p647, ruby-2.1.7, ruby-2.2.0 through ruby-2.2.3.

From make.log for ruby-2.2.3:

compiling ossl_rand.c
ossl_rand.c:162:9: warning: implicit declaration of function 'RAND_egd' is invalid in C99 [-Wimplicit-function-declaration]
    if(!RAND_egd(RSTRING_PTR(filename))) {
        ^
ossl_rand.c:184:10: warning: implicit declaration of function 'RAND_egd_bytes' is invalid in C99 [-Wimplicit-function-declaration]
    if (!RAND_egd_bytes(RSTRING_PTR(filename), n)) {
         ^
2 warnings generated.
compiling ossl_hmac.c
compiling ossl_ssl.c
ossl_ssl.c:141:5: error: use of undeclared identifier 'SSLv3_method'
    OSSL_SSL_METHOD_ENTRY(SSLv3),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:192:1: note: expanded from here
SSLv3_method
^
ossl_ssl.c:142:5: error: use of undeclared identifier 'SSLv3_server_method'
    OSSL_SSL_METHOD_ENTRY(SSLv3_server),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:192:1: note: expanded from here
SSLv3_server_method
^
ossl_ssl.c:143:5: error: use of undeclared identifier 'SSLv3_client_method'
    OSSL_SSL_METHOD_ENTRY(SSLv3_client),
    ^
ossl_ssl.c:119:69: note: expanded from macro 'OSSL_SSL_METHOD_ENTRY'
#define OSSL_SSL_METHOD_ENTRY(name) { #name, (SSL_METHOD *(*)(void))name##_method }
                                                                    ^
<scratch space>:192:1: note: expanded from here
SSLv3_client_method
^
ossl_ssl.c:210:21: error: invalid application of 'sizeof' to an incomplete type 'const struct <anonymous struct at ossl_ssl.c:115:14> []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2194:23: error: invalid application of 'sizeof' to an incomplete type 'const struct <anonymous struct at ossl_ssl.c:115:14> []'
    ary = rb_ary_new2(numberof(ossl_ssl_method_tab));
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
ossl_ssl.c:2195:21: error: invalid application of 'sizeof' to an incomplete type 'const struct <anonymous struct at ossl_ssl.c:115:14> []'
    for (i = 0; i < numberof(ossl_ssl_method_tab); i++) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ossl_ssl.c:19:35: note: expanded from macro 'numberof'
#define numberof(ary) (int)(sizeof(ary)/sizeof((ary)[0]))
                                  ^~~~~
6 errors generated.
*** Error code 1

**Comment by botp** [comment]
i also observe this behaviour 
1 compiling ruby manually, 
2 and also using rbenv.

**Comment by botp** [comment]
ok, i may have found the culprit.  take note, i am using latest ubuntu tls 14.04.3 (but i think this is also true w freebsd 10 latest).
the catch here is that the openssl libs have been updated to drop support of sslv3, *but unfortunately, ruby is still using it.  even the 2.3.0-dev fails on rbenv, and also even on manual compilation.  it really is a showstopper.  hope the ruby devs are fixing this and backporting asap.

**Comment by botp** [comment]
ok. i tried the latest trunk version fr github and i think they have fixed it(i see code changes in *ssl*.c) .   the compile works fine.  wc it be backported.

**Comment by timuralp** [comment]
This may be helpful to other folks. The specific fix is here: https://bugs.ruby-lang.org/issues/11376. The commit in the Ruby tree is: 801e1fe46d83c856. If you check out the Ruby repository, you can create the patch with: ```git show 801e1fe46d83c856 > no_sslv3.patch``` and then install with:
```
rvm install 2.2.3 --patch ./no_sslv3.patch
```

**Comment by pkuczynski** [comment]
This has been fixed in #3748/#3752 and merged to latest master. Please switch and test: `rvm get master`
