### ISSUE TITLE
RVM overwrites bash exit trap defined in OS X El Capitan

### ISSUE THREAD

**Issue by ayank308** [rvm/rvm#3540]
OS X El Capitan introduced sessions to manage history. History is written to files in ~/.bash_sessions/ instead of ~/.bash_history when bash exits. This is driven by an exit trap that calls shell_session_update(). RVM overwrites this trap, meaning that history isn't saved when the bash session is exited after running RVM.

This occurs with the RVM called in ~/.bashrc:

    $ trap
    trap -- 'shell_session_update' EXIT
    $ source .rvm/scripts/rvm
    $ trap
    $

And with the regular RVM:

    $ trap
    trap -- 'shell_session_update' EXIT
    $ rvm --version
    rvm 1.26.11 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
    $ trap
    $

**Comment by tushar-chauhan** [comment]
I am facing the same issue. I commented
`[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"`, from my _.bash_profile_ and _.profile_ and everything seems to work fine now.
I don't know how important this **Load RVM into a shell session *as a function*** is, but commenting it out works.

**Comment by ayank308** [comment]
Another option is to create .bash_logout with a single line:

    shell_session_update

This will save the history even if the exit trap to do so gets cleared. I've found that ffmpeg also clears the traps.

**Comment by tushar-chauhan** [comment]
@ayank308 That worked too. Thanks!

**Comment by visibletrap** [comment]
@ayank308 Neat

**Comment by januszm** [comment]
@ayank308 Thank you very much!

**Comment by Yanchek99** [comment]
.bash_logout not working for me. Only seems to get hit if i execute 'exit' command before closing Terminal.

**Comment by mlangenberg** [comment]
Any updates on this issue? Can RVM call the original exit trap?
