### ISSUE TITLE
Unable to GPG verify local RVM installer copy

### ISSUE THREAD

**Issue by henderea** [rvm/rvm#3553]
I'm seeing this as part of the output when i try to do any `rvm get` command (both `rvm get stable` and `rvm get head`):
```
gpg: Signature made Mon Apr 13 20:05:41 2015 EDT using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
```

It seems to be happening while it is trying to verify the local RVM installer copy.  Here's the full output from the command:

```
$ rvm get head
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/erichenderson/.rvm/archives/rvm-installer.asc
gpg: Signature made Mon Apr 13 20:05:41 2015 EDT using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/Users/erichenderson/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

-bash: return: _ret: numeric argument required
```

I've tried uninstalling and reinstalling rvm, uninstalling and reinstalling gnupg2 (via homebrew), and clearing out my ~/.gnupg/ directory, none of which made any difference.  I've also run both of the gpg2 commands the output lists, and it says it already has the key and nothing has changed.  I ran them after clearing out the ~/.gnupg/ directory and it did add something on the first one, but the second command was obviously a duplicate, so it said the signature was unchanged.

I noticed this after I defragged my mac, so it's possible something got corrupted.  Is there anything I can clear out and set back up other than the rvm and gnupg2 installations and ~/.gnupg/ folder?

I'm running OS X 10.11.1 El Capitan with System Integrity Protection turned completely off if that makes any difference.  I also have keybase set up on my CLI with mpapis followed.

I can get around the problem for now by uninstalling gnupg2, but I'd like to be able to install it again at some point and have rvm use it.

Thanks for any help you can provide.

**Comment by sikachu** [comment]
I'm sorry for the issue. I merged a PR which changed the content of `rvm-installer` and I thought I was able to get @mpapis to re-sign the installer soon enough. The commit has now been reverted, and future merge will be done under his supervision.
