### ISSUE TITLE
curl detection false negative on Travis occasionally

### ISSUE THREAD

**Issue by cvrebert** [rvm/rvm#3559]
See also https://github.com/travis-ci/travis-ci/issues/5092
Full build log: https://travis-ci.org/twbs/bootstrap/jobs/91534467
Snippet of most relevant part:

```
$ rvm -v
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ echo $PATH
/home/travis/.nvm/versions/node/v4.2.2/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin
$ which curl || true
/usr/bin/curl
$ ls -l /usr/bin/curl || true
-rwxr-xr-x 1 root root 129696 Jan 14  2015 /usr/bin/curl
$ rvm --debug install 2.2
ruby-2.2.3 - install
ruby-2.2.3 - #already removed src/ruby-2.2.3
ruby-2.2.3 - #already removed rubies/ruby-2.2.3
Searching for binary rubies, this might take some time.
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/ruby-2.2.3.tar.bz2
Remote file does not exist http://binaries.rubini.us/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2
Remote file exists https://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2
Found remote file https://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2
rvm_autolibs_flag=4
Checking requirements for ubuntu.
requirements code for ubuntu loaded
Found required packages: bash, curl, patch, bzip2, ca-certificates, gawk, g++, gcc, make, libc6-dev, patch, openssl, ca-certificates, libreadline6, libreadline6-dev, curl, zlib1g, zlib1g-dev, libssl-dev, libyaml-dev, libsqlite3-dev, sqlite3, autoconf, libgdbm-dev, libncurses5-dev, automake, libtool, bison, pkg-config, libffi-dev.
Requirements installation successful.
Free disk space 10622MB, required 100MB.
ruby-2.2.3 - #configure
ruby-2.2.3 - #download
fetch https://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2?rvm=1.26.11 => bin-ruby-2.2.3.tar.bz2
No archive, downloading
RVM requires 'curl'. Install 'curl' first and try again.
There was an error(200).
Checking fallback: ftp://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2?rvm=1.26.11
Checking fallback: http://www.mirrorservice.org/sites/rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2?rvm=1.26.11
No fallback URL could be found, try increasing timeout with:
    echo "export rvm_max_time_flag=20" >> ~/.rvmrc
Downloading https://rubies.travis-ci.org/ubuntu/12.04/x86_64/ruby-2.2.3.tar.bz2 failed.
__rvm_rm_rf already gone: /home/travis/.rvm/rubies/ruby-2.2.3
Mounting remote ruby failed with status 2, trying to compile.
```

**Comment by havenwood** [comment]
The  `__rvm_curl()` function that seems to be triggering this error reads:
```sh
curl_path="" # Just an empty String on systems other than Solaris 10
__rvm_which ${curl_path}curl >/dev/null 2>&1 ||
{
        rvm_error "RVM requires 'curl'. Install 'curl' first and try again."
        return 200
}
```
An that `__rvm_which()` is:
```sh
 __rvm_which () {      
        \command \which "$@" || return $?
}
```
@cvrebert So maybe sanity-check that this is also as expected?:
```sh
\command \which "curl" || echo "problem..."
```

**Comment by cvrebert** [comment]
https://travis-ci.org/twbs/bootstrap/jobs/92384373 :
```
$ \command \which 'curl' || echo 'NO CURL'
/usr/bin/curl
```
But RVM still claims it can't find curl.

**Comment by RX14** [comment]
Happening to me too.

**Comment by BanzaiMan** [comment]
Hello. I added the comment on the Travis issue: https://github.com/travis-ci/travis-ci/issues/5092#issuecomment-170689683

> Hello, so I looked at various reports of this kind in various places. It is quite likely that the `curl` warning message is false, but I am not sure how it can happen.
> 
> In all of the cases (except for one) I have seen, RVM finds a usable archive somewhere, and proceeds to install. But the `rvm` command exits from the `curl`-not-found error before the installation can finish, and the build fails on Travis.

**Comment by BanzaiMan** [comment]
Is RVM manipulating `$PATH` at too many places, and stomping on itself?

**Comment by catkins** [comment]
We're getting this issue too as of the last day or two :crying_cat_face:

**Comment by defsprite** [comment]
We're seeing this as well - yet only on projects that have `node_modules`. Only clue I've found:

- `node_modules/.bin` is on `$PATH`, prior to standard bin directories 
- in our case there is `node_modules/.bin/which`

As `rvm` uses `which` to detect `curl` might this be the issue? (see above and https://github.com/rvm/rvm/blob/master/scripts/functions/support#L262)

Not sure how to verify this though. It should probably work even with that version of `which`.

**Comment by defsprite** [comment]
It might have to do with `node_modules/.bin/which` being on `$PATH`, see https://github.com/travis-ci/travis-ci/issues/5092#issuecomment-171777646

**Comment by pkuczynski** [comment]
Has this issue been already solved or we need to prepare solution? Reading https://github.com/travis-ci/travis-ci/issues/5092#issuecomment-171777646 I guess we could try to modify the PATH and remove `node_modules/.bin` when running RVM on Travis

**Comment by pkuczynski** [comment]
Reported this issue to node-which (https://github.com/npm/node-which/issues/41). Lets see if they will be able to come up with some solution...

**Comment by isaacs** [comment]
Can someone encountering this issue head over to https://github.com/npm/node-which/issues/41 and let me know what your `$PATH` environment variable is and what `ls -laF $(which curl)` reports?  Also, is `which curl` outputting anything?  Exiting with an non-zero error status code?  Anything you can share would be very helpful, since I can't reproduce this on my own system.

Thanks!

**Comment by danielhanold** [comment]
@isaacs I'm encountering the issue and here are the two values you were looking for. Let me know if the rest of the log would be helpful.

```
$ echo $PATH
/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.phpenv/shims:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.phpenv/bin:/home/travis/.rvm/bin

$ ls -laF $(which curl)
-rwxr-xr-x 1 root root 129696 Jan 14  2015 /usr/bin/curl*
```

**Comment by isaacs** [comment]
@danielhanold Migrated over to a more useful location: https://github.com/npm/node-which/issues/41#issuecomment-257360930 (thanks @pkuczynski)

**Comment by isaacs** [comment]
In trying to debug this, I'm running into a weird thing.  Is this a known issue?

```bash
  if
    [[ "${_system_name}" == "OSX" ]] && __rvm_version_compare "${_system_version}" -ge 10.11 &&
    [[ -n "$BASH" ]] && [[ ! -f "${HOME}/.bash_sessions_disable" ]]
  then trap 'shell_session_update' EXIT
  fi
```

That `shell_session_update` function doesn't appear to be defined, so when I run rvm on OS X, I'm getting a lot of unhelpful errors.

**Comment by pkuczynski** [comment]
Seems that node-which does not see a way of fixing this issue (https://github.com/npm/node-which/issues/41), so the only think which can be done is change path on travis to exclude node-which...

**Comment by isaacs** [comment]
@pkuczynski More to the point, I don't see that node-which is actually misbehaving at all, and I'm suspicious that the issue is not about which which is being used.

I suspect (but have not verified) that adding a `hash -r` ahead of the rvm call might make the problem disappear.  The problem might be that the `PATH` doesn't include `/usr/bin`, and then later is updated to include that path, but bash's hash is stale.  This is 100% speculation.  Since I can't reproduce the issue, I can't really investigate it effectively.
