### ISSUE TITLE
stat: cannot stat ‘/<gconf>/ a<entry name='login_shell' mtime='1448126849' type='bool' value='true'/>’: No such file or directory

### ISSUE THREAD

**Issue by TMorgan99** [rvm/rvm#3567]
having trouble statting an unconventional name.

**Comment by SanjayYadav90** [comment]
Hi,
I have the same issue while installing RVM for ruby
Don't know how to solve,
can anyone?

**Comment by XXChester** [comment]
Did you guys ever find  a fix for this? I had to re-install my Os today and having a lot of problems with rvm. When I run 'rvm get stable' it runs and then outputs the above line twice. After that, installing rubies, gems etc all have problems. I am hoping if I fix the highest level problem, the children will work.

**Comment by pkuczynski** [comment]
@XXChester could you please gist output of following commands:

`\curl -sSL https://get.rvm.io | bash -s master`
`rvm info`

**Comment by XXChester** [comment]
`brandon@ox:~$ \curl -sSL https://get.rvm.io | bash -s master
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Installing RVM to /home/brandon/.rvm/
stat: cannot stat ‘/<gconf>/ a<entry name='login_shell' mtime='1479484041' type='bool' value='true'/>’: No such file or directory
stat: cannot stat ‘/<gconf>/ a<entry name='login_shell' mtime='1479484041' type='bool' value='true'/>’: No such file or directory
    RVM PATH line found in /home/brandon/.mkshrc /home/brandon/.profile /home/brandon/.bashrc /home/brandon/.zshrc.
    RVM sourcing line found in /home/brandon/.profile /home/brandon/.bashrc /home/brandon/.bash_profile /home/brandon/.zlogin.
Installation of RVM in /home/brandon/.rvm/ is almost complete:

  * To start using RVM you need to run `source /home/brandon/.rvm/scripts/rvm`
    in all your open shell windows, in rare cases you need to reopen all shell windows.

# Brandon.McCulligh,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io
brandon@ox:~$ rvm info

ruby-2.3.0:

  system:
    uname:       "Linux ox 3.13.0-101-generic #148-Ubuntu SMP Thu Oct 20 22:08:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "debian/jessie_sid/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "6 seconds ago"
    path:         "/home/brandon/.rvm"

  ruby:
    interpreter:  ""
    version:      ""
    date:         ""
    platform:     ""
    patchlevel:   ""
    full_version: ""

  homes:
    gem:          "/home/brandon/.rvm/gems/ruby-2.3.0"
    ruby:         "/home/brandon/.rvm/rubies/ruby-2.3.0"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/home/brandon/.rvm/gems/ruby-2.3.0/bin:/home/brandon/.rvm/gems/ruby-2.3.0@global/bin:/home/brandon/.rvm/rubies/ruby-2.3.0/bin:/home/brandon/.rvm/bin:/home/brandon/gopath:/home/brandon/gopath/bin:/home/brandon/gopath:/home/brandon/gopath/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/bin/aws/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/bin/aws/bin"
    GEM_HOME:     "/home/brandon/.rvm/gems/ruby-2.3.0"
    GEM_PATH:     "/home/brandon/.rvm/gems/ruby-2.3.0:/home/brandon/.rvm/gems/ruby-2.3.0@global"
    MY_RUBY_HOME: "/home/brandon/.rvm/rubies/ruby-2.3.0"
    IRBRC:        "/home/brandon/.rvm/rubies/ruby-2.3.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""


brandon@ox:~$ 
`

**Comment by TMorgan99** [comment]
I don't know much about this anymore.  It seems to be fixed, at least for me.  But it was kinda weird at the time.

**Comment by mpapis** [comment]
Looks like fixed.

Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
