### ISSUE TITLE
List of known Rubies is very outdated

### ISSUE THREAD

**Issue by stomar** [rvm/rvm#3568]
For the latest/stable release 1.26.11, `rvm list known` shows a **very** outdated list of known Rubies; newest: are e.g.

* MRI 2.2.1
* JRuby 9.0.0.0.pre1

But we already have 2.2.3 and JRuby 9.0.4.0!

Installation works nevertheless by explicitly specifying the version, but this conveys the impression RVM is not maintained anymore.

It's also annoying that currently when using the latest versions, a simple `rvm use 2.2` e.g. leads to an "is not installed" error, since RVM tries to switch to an older version (here 2.2.1).  :disappointed:

**Comment by sikachu** [comment]
Thanks for reporting in. This is a known issue, and we're in the process of wrapping up the new release of RVM which will have those releases in it.

In the meantime, you can do `rvm get master` to install the edge version of RVM which has those known rubies in it.

I'm going to close this issue. Thank you for using RVM.

**Comment by stomar** [comment]
@sikachu Have there ever been any thoughts about decoupling the list of known rubies from stable releases? Couldn't the list be updated separately?

**Comment by sikachu** [comment]
@stomar I honestly don't know, as I just recently joined the team. However, I will take this to discuss with the team if this mean we could do more patch releases, that only update known rubies, more often.

**Comment by stomar** [comment]
:+1:
