### ISSUE TITLE
RVM site down?

### ISSUE THREAD

**Issue by qaswm** [rvm/rvm#3576]
Hello I am getting the following error when trying to visit the site:

Error 503 Connection refused

Connection refused

Guru Mediation:

Details: cache-fra1231-FRA 1450169634 3079647057

Varnish cache server

**Comment by rpCal** [comment]
Same problem

**Comment by garymg18** [comment]
The same error.

**Comment by garymg18** [comment]
Seems like rvm's very popular. ;-)

**Comment by rpCal** [comment]
Even I have problem with install rvm:
$ curl -L https://get.rvm.io | bash -s stable --autolibs=enabled
curl: (7) Failed to connect to get.rvm.io port 443: Połączenie odrzucone

**Comment by MassiveHiggsField** [comment]
Same here

**Comment by imjacobclark** [comment]
+1

**Comment by Exorcist** [comment]
+

**Comment by WebDevTmas** [comment]
+4 (4 vagrants using rvm are not installing ^^ )

**Comment by imjacobclark** [comment]
For a temp fix, you can do:

```shell
curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer | bash -s stable
```

Which is essentially what https://get.rvm.io aliases too anyway.

**Comment by jrgifford** [comment]
Hi! I'm investigating, and I'll keep everyone up-to-date on what's going
on.

**Comment by indrasantosa** [comment]
+1

**Comment by mpapis** [comment]
fixed

**Comment by csolg** [comment]
The site is down.

**Comment by andriiash** [comment]
+1

**Comment by jfbookingbug** [comment]
+1

**Comment by mpapis** [comment]
fixed

**Comment by charl** [comment]
I hate posting to an old issue but this appears to be happening again:

```
# curl -vvv https://get.rvm.io
* Rebuilt URL to: https://get.rvm.io/
* Hostname was NOT found in DNS cache
*   Trying 97.107.133.48...
*   Trying 2600:3c03::f03c:91ff:fedb:6957...
* Immediate connect fail for 2600:3c03::f03c:91ff:fedb:6957: Network is unreachable
* connect to 97.107.133.48 port 443 failed: Connection refused
* Failed to connect to get.rvm.io port 443: Connection refused
* Closing connection 0
curl: (7) Failed to connect to get.rvm.io port 443: Connection refused
```

**Comment by Nada-Aboueata** [comment]
@charl  yes it looks that its happening again :( 

`curl -SSL https://get.rvm.io | bash -s stable ruby
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 2600:3c03::f03c:91ff:fedb:6957: Network is unreachable
`

**Comment by mpapis** [comment]
fixed

**Comment by philstach3** [comment]
The site is down again, getting a 503 error.

**Comment by mpapis** [comment]
Few hours later I got an email about linode maintenance went wrong - I guess it was the cause, sorry for the inconvenience.
