### ISSUE TITLE
Syntax error on OS X Mavericks under some circumstances

### ISSUE THREAD

**Issue by BanzaiMan** [rvm/rvm#3578]
Under some circumstances, we are getting a bash syntax error on Mavericks after `rvm get head`. The same code works on Yosemite.

Compare [Yosemite](https://travis-ci.org/travis-ci/travis-rubies/jobs/97276184) and [Mavericks](https://travis-ci.org/travis-ci/travis-rubies/jobs/97276189#L67) builds.

A more comprehensive debug build was run here: https://travis-ci.org/travis-ci/travis-rubies/builds/97285349 but I do not see any possible culprit for the said syntax error.

The code that triggers the syntax error is here: https://github.com/travis-ci/travis-rubies/blob/c75812f774aecf8bce6557e5f688906baa66b38e/build.sh#L59-L60

```shell
rvm get head
rvm reload
```

**Comment by BanzaiMan** [comment]
@mpapis any clue on this one?

**Comment by mpapis** [comment]
@BanzaiMan did anything change in how rvm is loaded? can you point me to code that loads rvm in the workers?

**Comment by BanzaiMan** [comment]
@mpapis https://travis-ci.org/BanzaiMan/travis_production_test/jobs/107917586#L111-L113

```shell
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
```

**Comment by mpapis** [comment]
can you add before the `rvm get head`:
```bash
rvm_reload_flag=1 source '/Users/travis/.rvm/scripts/rvm'
```

**Comment by BanzaiMan** [comment]
https://travis-ci.org/travis-ci/travis-rubies/jobs/162031919

Looks like the script dies just by `source`ing `$rvm_path/scripts/rvm`.

**Comment by BanzaiMan** [comment]
With the release of Sierra, though, I think we'll just drop building on Mavericks.
