### ISSUE TITLE
Request for RVM to support debian/8/armhf/ruby-2.2.3

### ISSUE THREAD

**Issue by renatolond** [rvm/rvm#3581]
Hello!
I'm using a Raspberry Pi 2 and there are no binary rubies available for this configuration. I was able to compile one, but it took quite a while. Is there some way to contribute the binaries to rvm?

**Comment by na-g** [comment]
@renatolond, there is some discussion of the general problem of getting binaries for the Raspberry Pi 2 in issue #3145.

**Comment by pkuczynski** [comment]
Duplicate of #3145
