### ISSUE TITLE
Error installing passenger rack requires Ruby version >= 2.2.2

### ISSUE THREAD

**Issue by seafoodbuffet** [rvm/rvm#3583]
Here's a lot of my attempt to install passenger, I'm not sure why I'm getting this behavior. In particular, just installing the dependency it's complaining about (rack) seems to allow the installation to proceed, but trying to install passenger directly without first install rack doesn't work.

Furthermore, if I try to install passenger using the system ruby/gem 1.8.7/1.3.7 (ancient I know), everything seems to work just fine. Am I running into a version of ruby thing or an RVM thing?

```
[root@localhost ~]# which rvm
/usr/local/rvm/bin/rvm
[root@localhost ~]# rvm -v
rvm 1.26.11 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
[root@localhost ~]# gem -v
2.2.2
[root@localhost ~]# rvm ruby-2.1.2 do gem install -V -v 4.0.53 --no-rdoc --no-ri passenger
GET https://api.rubygems.org/specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/specs.4.8.gz
200 OK
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=passenger
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rack
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=daemon_controller
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rake
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=json
200 OK
ERROR:  Error installing passenger:
	rack requires Ruby version >= 2.2.2.
[root@localhost ~]# rvm ruby-2.1.2 do gem install rack
Fetching: rack-1.6.4.gem (100%)
Successfully installed rack-1.6.4
Parsing documentation for rack-1.6.4
Installing ri documentation for rack-1.6.4
Done installing documentation for rack after 1 seconds
1 gem installed
[root@localhost ~]# rvm ruby-2.1.2 do gem install -V -v 4.0.53 --no-rdoc --no-ri passenger
GET https://api.rubygems.org/specs.4.8.gz
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/specs.4.8.gz
200 OK
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=passenger
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rack
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=daemon_controller
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rake
200 OK
Downloading gem passenger-4.0.53.gem
GET https://api.rubygems.org/gems/passenger-4.0.53.gem
302 Moved Temporarily
GET https://rubygems.global.ssl.fastly.net/gems/passenger-4.0.53.gem
Fetching: passenger-4.0.53.gem (100%)
200 OK
... lots of debug stuff snipped
Building native extensions.  This could take a while...
... more debug stuff
Successfully installed passenger-4.0.53
1 gem installed
[root@localhost ~]# 
```

**Comment by nthapaliya** [comment]
I am running into this as well. The problem 'disappears' if you bump your ruby version to 2.2.2, but I have no idea why. Running Centos6, trying to install passenger v4.0.60.

**Comment by ilude** [comment]
I ran into this on Ruby 2.1.4 needed to update rubygems

# gem install rubygems-update
# update_rubygems

**Comment by peterept** [comment]
Updating rubygems to 2.3 resolves it and is back compatible with Ruby 2.1.8:

Fixed here:
https://github.com/rubygems/rubygems/commit/0936ca6929172d28b15220dfef8526a9645a90ce

**Comment by seafoodbuffet** [comment]
I haven't tested this but I'm going to close this on the presumption that it's a rubygems issue, not a passenger issue.

**Comment by rucha09** [comment]
if you get error like below 
 While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /Library/Ruby/Gems/2.0.0 directory

Then use following command

# sudo gem install rubygems-update
# sudo update_rubygems

**Comment by cku-github** [comment]
I had the same issue with rhel7.5 and using the newer passenger-5.2.3 version.
Running the command 
sudo yum install -y nginx passenger || sudo yum-config-manager --enable cr && sudo yum install -y nginx passenger
the log threw the following error:
Error: Package: passenger-5.2.3-1.el7.x86_64 (passenger)
           Requires: rubygem(rack)
manually installing ruby and rubygems-rake didn't help.
It worked after I manually installed epel:
sudo yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

possibly my earlier rubygems-rake install also helped then.
