### ISSUE TITLE
nested Gemfile issue

### ISSUE THREAD

**Issue by ruudgrosmann** [rvm/rvm#3588]
hello, I'm not sure I drop this question at the right spot. Hope you can point me in the right direction.

I have a ruby project managed with rvm in which I have bin directory and some ruby scripts.
Inside the project directory, I have directory test, in which I have cucumber based tests. I use another ruby version and another gemset for these tests. This works OK, until I try to call a ruby script from the cucumber tests that is inside the bin directory of the main project.

Clearly, this script is called using the Gemfile.lock of the test directory instead the Gemfile.lock of the main project. Because there are many version conflict between the two, manual harmonising the version numbers is not the way to go.

I call the script from the test software with

wrapper = '/home/rdgon/.rvm/wrappers/ruby-1.9.3-p551@rails32/ruby2'
 cmd= "#{wrapper} #{railsdir}/bin/import_xml "
system cmd

The wrapper indicates the use of ruby 1.9.3, patch 551.
As said, the error message indicates that not #{railsdir}/Gemfile.lock is used, but #{railsdir}/test/cucumber/Gemfile.lock instead. The test-rubyversion is used for invoking the main project script (patch 547):

/home/rdgon/.rvm/gems/ruby-1.9.3-p547@global/gems/bundler-1.6.2/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find multi_json-1.11.0 in any of the sources (Bundler::GemNotFound)

What is the way to resolve this situation from my test software? How can I force the system command to use the proper gemset?

thanks in advance, Ruud

**Comment by white-monkey** [comment]
I have a related problem, I noticed that the `BUNDLE_GEMFILE` environment variable is not modified when I run a Ruby script from within another Ruby script, even though the correct versions of Ruby and gemset are selected by RVM.

A simple workaround should be to modify that variable and make it point to the correct Gemfile when you call your Ruby script (this is not tested):

    wrapper = 'BUNDLE_GEMFILE="/home/rdgon/CORRECT_LOCATION/Gemfile" /home/rdgon/.rvm/wrappers/ruby-1.9.3-p551@rails32/ruby2'

In my case I have a shell script calling the Ruby script so I simply unset the variable.

Still, I'd be interested in knowing about the proper way of handling that issue (which might not even be an RVM issue, by the way).

**Comment by ruudgrosmann** [comment]
white-monkey!
You are my hero. Indeed your suggestion solved my problem. I was really stuck on this, I already had implemented a workaround by not using the script itself, but the objects the script uses.

But it is not satisfying to have open questions like this. I now know how to tackle this in the future. Thanks again, Ruud
