### ISSUE TITLE
rvm.io domain seems to have expired (and squatted on)

### ISSUE THREAD

**Issue by parasquid** [rvm/rvm#3593]
```
~$ whois rvm.io

Domain : rvm.io
Status : Expired/Grace
Expiry : 2015-12-29

NS 1   : ns1dhl.name.com
NS 2   : ns2btz.name.com
NS 3   : ns3gmt.name.com
NS 4   : ns4lqx.name.com

Owner  : Division by Zero, LLC
Owner  : 3454 Stevenson Ct
Owner  : North Tonawanda
Owner  : New York
Owner  : US

Check for 'rvm.ac' --- http://www.nic.ac/go/whois/rvm.ac
Check for 'rvm.sh' --- http://www.nic.sh/go/whois/rvm.sh
```

Going to the website also is giving me some content usually seen on domains that have been squatted.

**Comment by Jasonbit** [comment]
Yup, I just filed an issue on the site project. :(

**Comment by jrgifford** [comment]
That's odd! According to the DNS record, we renewed it until 2017. So this should probably be a temporary thing, pending the propagation.

**Comment by parasquid** [comment]
Seems to be up again; yeah it could have been a propagation issue.

Thanks again (now to get rid of the *ahem* alternative ruby version manager I had to install to get my new machine running with ruby ;)
