### ISSUE TITLE
Cant install rubinius using RVM

### ISSUE THREAD

**Issue by ollieatkinson** [rvm/rvm#3598]
```
error: 'this' pointer cannot be null in well-defined C++ code; pointer may be assumed to always convert to true [-Werror,-Wundefined-bool-conversion]
      assert(this && (!reference_p() || (type_id() > InvalidType && type_id() < LastObjectType)));
             ^~~~ ~~
/usr/include/assert.h:93:25: note: expanded from macro 'assert'
    (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __FILE__, __LINE__, #e) : (void)0)
```

This is the install command I used:

```
$ rvm install rbx -- --llvm-config /usr/local/opt/llvm35/bin/llvm-config-3.5 
```

I attached the whole log file.

[rake.txt](https://github.com/rvm/rvm/files/81037/rake.txt)
---

OSX El Capitan
10.11.2 (15C50)

MacBook Pro (13-inch, Mid 2012)
Processor: 2.9 GHz Intel Core i7
Memory: 8 GB 1600 MHz DDR3

**Comment by pkuczynski** [comment]
This has been just fixed. Feel free to test with `rvm get master` and re-open when needed.

**Comment by ollieatkinson** [comment]
confirmed working

1. Update bash if you get `dyld: Library not loaded: /usr/local/opt/readline`
2. `rvm get master`
3. Install LLVM 3.8, rbx required 3.6+ `brew install llvm38`
4. Install rbx with llvm38 config `rvm install rbx-3.66 -- --llvm-config /usr/local/opt/llvm38/bin/llvm-config-3.8`

Thanks 👍

**Comment by pkuczynski** [comment]
Duplicate of #3287
