### ISSUE TITLE
Print info message without presence of .rvmrc

### ISSUE THREAD

**Issue by ybakos** [rvm/rvm#3602]
Thanks for all things rvm.

This is a feature request to make the printing of the info message when switching rubies/gemsets the default when using **.ruby-version** and **.ruby-gemset**. Currently, we have to also have a **.rvmrc** in order to see the message. This doesn't feel right.

Users should see "Using /path/to/ruby with gemset NAME" when `cd`ing into a directory that has _only_ a **.ruby-version** and **.ruby-gemset**.

See https://github.com/rvm/rvm/issues/2406.

**Comment by mpapis** [comment]
did you try this: `echo rvm_use_flag=2 >> ~/.rvmrc` - it will add `rvm_use_flag=2` to the `~/.rvmrc` - and the info should be shown always from this point on

**Comment by ybakos** [comment]
Ah, a user-scoped **.rvmrc**, I see. Thank you.
However, the message isn't colorized as it is when using a project-scoped **.rvmrc**. Any idea why or how I might fix this? (If this is irrelevant for rvm v2, please ignore.)

**Comment by pkuczynski** [comment]
This is fixed in latest rvm (master)
