### ISSUE TITLE
Release rvm-1.26.12

### ISSUE THREAD

**Issue by ojab** [rvm/rvm#3603]
Last rvm release was almost a year ago, rubies in stable are _very_ outdated. Stable release maybe?

**Comment by arg** [comment]
:+1:

**Comment by jimcavoli** [comment]
Big +1 stable rubies are lagging *really* badly. MRI and Rubinius stand out for sure. I'm using head which helps with MRI, but even still, rbx has been lagging  pretty bad.

**Comment by dnrce** [comment]
Huge +1 now that the Rails 5 beta is out and requires a minimum of Ruby 2.2.2.

**Comment by Jesterovskiy** [comment]
As I understand, https://github.com/rvm/rvm/milestones/rvm-1.26.12 this PRs must be done before release

**Comment by raelgc** [comment]
#3548 was the last one remaining, user reported it's working now after patch. #3512 is tagged as `after-release`.

So, it sounds good for a release.

**Comment by ojab** [comment]
Hooray!
