### ISSUE TITLE
GPG key expired - is it expected? How to handle properly?

### ISSUE THREAD

**Issue by thbar** [rvm/rvm#3605]
Today while doing `rvm get stable` on a test machine I got this message:

```
gpg: Signature faite le Mar 14 avr 02:05:41 2015 CEST avec la clef RSA d'identifiant BF04FF17
gpg: Bonne signature de « Michal Papis (RVM signing) <mpapis@gmail.com> »
gpg: Remarque : cette clef a expiré.
Empreinte de clef principale : 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
   Empreinte de la sous-clef : 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
```

I did a bit of search / due diligence (not being a GPG expert!) and noticed 2 things:
- the key still appear to be the same mentioned on the [RVM security page](https://rvm.io/rvm/security)
- the key still seem to match what is currently advertised on @mpapis [keybase profile](https://keybase.io/mpapis) (click on the key to view full).

How is the warning supposed to be handled, if anyone knows already? Thanks!

**Comment by rys** [comment]
The signing key doesn't expire until March 8th 2017. Is the date on your machine incorrect?

**Comment by envygeeks** [comment]
What signing key are you on about @rys? The aforementioned key @thbar is talking about is expired:
```
jordon ~ % gpg key.asc 
pub  4096R/D39DC0E3 2014-10-28 Michal Papis (RVM signing) <mpapis@gmail.com>
sub  4096R/BF04FF17 2014-10-28 [expires: 2016-01-05]
```

Which seems to align with: https://github.com/rvm/rvm/blob/46ff2691d82442b5d85f2f47ff1668e278e1f48a/scripts/functions/cli#L232

So where are your keys coming from?

**Comment by thbar** [comment]
@rys date and time is indeed correct. It's automatically set up via `time.euro.apple.com` (MacBook Air).

I've never come across this expiry since using RVM, so I wonder what's happening.

Making an hypothesis: I installed RVM on a number of machines (dev or production), but this one is probably the first on which I setup the RVM signing mechanism (released in 1.26.0 if I believe [this page](https://rvm.io/rvm/security)). I think amongst people around me, I was in the first to actually enable that feature.

Investigating on that hypothesis, I notice that:

* key is marked as expiring on 2016-01-05.
* `~/.gnupg/pubring.gpg/` has a file creation date `15 nov  2014`.
* I don't think I called `rvm get stable` since november 2015.

I'm hinting that maybe, this is the *local version of the key* (gpg client) which may be reported as more than 1-year old, and so considered expired.

If this is the case, it could be that I'm just one of the first people to actually meet, but also notice and report, the problem.

That's it for now :smile:

**Comment by thbar** [comment]
To clarify: by "test machine" I actually meant that I was updating on this machine, first, before proceeding to others. I can then see why @rys would ask if the date is correct, too, in the case of a "VM test machine"!

I will look again at my local files in more detail later, because I cannot remember if the gpg setup was done before the RVM need for it, or before, on this specific machine, so I may have things upside down here, and I didn't check all the dates nor put everything in perspective, yet.

**Comment by thbar** [comment]
No time to test yet in practice but it seems very likely to be the
explanation:

https://mobile.twitter.com/rvm_io/status/685571255307759617
Le dim. 17 janv. 2016 à 12:31, Jordon Bedwell <notifications@github.com> a
écrit :

**Comment by bvogel** [comment]
@thbar that fixed it for me

**Comment by chumaitoe** [comment]
Hello!  As @rys pointed out above, the signing key has expired by now:

```
SAN-1MAYERS-M> gpg2 --verify ~/.rvm/archives/rvm-installer.asc
gpg: assuming signed data in '/Users/mayers/.rvm/archives/rvm-installer'
gpg: Signature made Mon Feb 20 06:05:42 2017 PST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
SAN-1MAYERS-M> 
```

I'm getting this expired key notice when running `rvm get latest` on OSX, today.

**Comment by mpapis** [comment]
try `gpg2 --refresh-keys D39DC0E3`

**Comment by chumaitoe** [comment]
Thanks, Michal.  It works, sorta...

```
SAN-1MAYERS-M> gpg2 --refresh-keys D39DC0E3
gpg: refreshing 1 key from hkp://keys.gnupg.net
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 2 new user IDs
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 34 new signatures
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 1 new subkey
gpg: Total number processed: 1
gpg:           new user IDs: 2
gpg:            new subkeys: 1
gpg:         new signatures: 34
gpg: no ultimately trusted keys found
SAN-1MAYERS-M> 
```

So when I update rvm:

```
SAN-1MAYERS-M> rvm get latest
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/mayers/.rvm/archives/rvm-installer.asc
gpg: Signature made Mon Feb 20 06:05:42 2017 PST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/mayers/.rvm/archives/rvm-installer'
```

So not quite a clean run yet.  I am getting the update, it's just very noisy and would confuse a newer user.

**Comment by mpapis** [comment]
@chumaitoe did you trust the key? If not try:
```bash
echo 409B6B1796C275462A1703113804BB82D39DC0E3:6: | gpg2 --import-ownertrust
```
We will be adding this extra step with this new instruction https://github.com/rvm/rvm/pull/3945/files

**Comment by chumaitoe** [comment]
Yes, that is the happy magic!

```
SAN-1MAYERS-M> rvm get latest
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/mayers/.rvm/archives/rvm-installer.asc
gpg: Signature made Mon Feb 20 06:05:42 2017 PST using RSA key ID BF04FF17
gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [ultimate]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [ultimate]
gpg:                 aka "[jpeg image of size 5015]" [ultimate]
GPG verified '/Users/mayers/.rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/1.29.1.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc
gpg: Signature made Sun Feb 19 12:02:47 2017 PST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [ultimate]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [ultimate]
gpg:                 aka "[jpeg image of size 5015]" [ultimate]
GPG verified '/Users/mayers/.rvm/archives/rvm-1.29.1.tgz'

Upgrading the RVM installation in /Users/mayers/.rvm/
    RVM PATH line found in /Users/mayers/.mkshrc /Users/mayers/.profile /Users/mayers/.bashrc /Users/mayers/.zshrc.
    RVM sourcing line found in /Users/mayers/.profile /Users/mayers/.bash_profile /Users/mayers/.zlogin.
Upgrade of RVM in /Users/mayers/.rvm/ is complete.

# Mike Ayers,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:


  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/mayers/.bash_profile':

      source ~/.profile

  * No new notes to display.

RVM reloaded!
SAN-1MAYERS-M> 
```

The warning occurs because I use Bourne (also known as "correct"  :-p ) syntax, i.e.
`. ${HOME}/.profile`

**Comment by mpapis** [comment]
@chumaitoe please open a new ticket for the `.` warning, I thought we handled it already - or if you feel like it maybe submit a PR for it?

@pkuczynski we got two things to do:
1. auto refresh keys
2. add trusting to instructions

I will leave this ticket open so it reminds us about it.

**Comment by pkuczynski** [comment]
`.` supposed to be fixed in master: https://github.com/rvm/rvm/commit/50005a9fb16ed9eb77355d2a9bd3d83b29d63d4e

@chumaitoe can you check what `grep -E '(source|\.).+profile' /Users/mayers/.bash_profile` outputs?

**Comment by pkuczynski** [comment]
@mpapis where would u like to add auto keys refresh?

**Comment by mpapis** [comment]
autorefresh - before we check file signatures - refresh only rvm developers keys, nothing more - for me it's mostly speed concern

**Comment by chumaitoe** [comment]
```
san-1mayers-m> grep -E '(source|\.).+profile' /Users/mayers/.bash_profile
. ${HOME}/.profile
san-1mayers-m> 
```

Apologies for the delay.  The nature of my job has me working in bursts.  So if I

`rvm get master`

I should expect to not see the warning, correct?

**Comment by mpapis** [comment]
indeed there should be no warning with rvm master

**Comment by chumaitoe** [comment]
Confirm that master is a clean run:

```
SAN-1MAYERS-M> rvm get master
Downloading https://get.rvm.io
No GPG software exists to validate rvm-installer, skipping.
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /Users/mayers/.rvm/
    RVM PATH line found in /Users/mayers/.mkshrc /Users/mayers/.profile /Users/mayers/.bashrc /Users/mayers/.zshrc.
    RVM sourcing line found in /Users/mayers/.profile /Users/mayers/.bash_profile /Users/mayers/.zlogin.
Upgrade of RVM in /Users/mayers/.rvm/ is complete.

# Mike Ayers,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

RVM reloaded!
SAN-1MAYERS-M> 
```

Very nice!

**Comment by chumaitoe** [comment]
I should add GPG to be complete...

**Comment by chumaitoe** [comment]
Hmmm... I have gpg.  Oh, well, I can investigate that separately.  I consider this issue fixed, for what that's worth.

**Comment by chumaitoe** [comment]
@mpapis  Do I not qualify towards the "feedback needed" tag?  Is there anything I can do to help get this fix released?  Thanks for all your help!

**Comment by ageis** [comment]
@mpapis Even after setting the trust level to ultimate, the key is still expired. 
```
gpg: Signature made Thu 22 Jun 2017 06:18:38 PM CEST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
```
Assuming RVM is in `/usr/local/rvm` then where is the GNUPGHOME/keyring located? so I can update the key.

**Comment by mpapis** [comment]
@ageis try `gpg2 --refresh-keys mpapis`

**Comment by mpapis** [comment]
@chumaitoe we already know what to do https://github.com/rvm/rvm/issues/3605#issuecomment-294729851 - now for anyone in RVM V1 to find time to work on it, I'm focusing on RVM V2 work as much as possible.

**Comment by ageis** [comment]
@mpapis got it, didn't realize it was in root's keyring, thought there might be a custom one somewhere. Thanks! updated expiry looks good.

**Comment by Bregor** [comment]
> @ageis try `gpg2 --refresh-keys mpapis`


```
gpg: Signature made Sun Apr  1 00:47:44 2018 MSK
gpg:                using RSA key 62C9E5F4DA300D94AC36166BE206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
```

**Comment by pkuczynski** [comment]
Should be fixed by now. Closing...
