### ISSUE TITLE
problem installing any version of ruby

### ISSUE THREAD

**Issue by Debonian** [rvm/rvm#3612]
whenever i try to install any version of ruby i just get these errors

Error running 'requirements_debian_libs_install gawk libreadline6-dev zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config',
showing last 15 lines of /usr/local/rvm/log/1453665704_ruby-2.3.0/package_install_gawk_libreadline6-dev_zlib1g-dev_libssl-dev_libyaml-dev_libsqlite3-dev_autoconf_libgdbm-dev_libncurses5-dev_automake_libtool_bison_pkg-config.log
E: Package 'gawk' has no installation candidate
E: Unable to locate package libreadline6-dev
E: Unable to locate package zlib1g-dev
E: Unable to locate package libssl-dev
E: Unable to locate package libyaml-dev
E: Unable to locate package libsqlite3-dev
E: Package 'autoconf' has no installation candidate
E: Unable to locate package libgdbm-dev
E: Package 'libncurses5-dev' has no installation candidate
E: Package 'automake' has no installation candidate
E: Package 'libtool' has no installation candidate
E: Package 'bison' has no installation candidate
E: Package 'pkg-config' has no installation candidate
++ return 100
++ return 100
Requirements installation failed with status: 100.

**Comment by josuetex** [comment]
+1

**Comment by EdDeAlmeidaJr** [comment]
It seems to me you just don't have the packages needes to compile/build software in your installation. 

Would you mind to try

    **sudo apt-get install build-essential**

and then report here if the error continues?

**Comment by pkuczynski** [comment]
@Debonian we possibly recognize your OS incorrectly. Can you re-try with latest RVM?

**Comment by pkuczynski** [comment]
Closing as this is an old issue and unlikely anyone will respond. Feel free to reopen if the issue persists.

**Comment by ivanfretes** [comment]
Install the [libssl1.1_1.1.0f-3+deb9u2_amd64.deb](https://packages.debian.org/stretch/amd64/libssl1.1/download) package and try again rvm install ruby
