### ISSUE TITLE
Issue installing rem 2.0.0 and 2.3.0

### ISSUE THREAD

**Issue by moisesprojects** [rvm/rvm#3614]
Never mind I followed the error instructions and reinstalled.  All good!  Thanks!

I am now getting the following error when trying to install rem 2.0.0.  Now I get:

It appears Homebrew is already installed. If your intent is to reinstall you
should do the following before running this installer again:
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall)"
The current contents of /usr/local are bin McAfee repost share .git
Requirements installation failed with status: 1.

I get the following error: 

curl: (22) The requested URL returned error: 503 backend read error
Something went wrong during Homebrew installation,
can not find 'brew' command, please report a bug: http://bit.ly/rvm-issues
Requirements installation failed with status: 1.

I am also getting a 502 gateway error now

**Comment by jrgifford** [comment]
Try again - github has been down for the past few hours.

**Comment by moisesprojects** [comment]
Thanks - now I am getting the following:

The current contents of /usr/local are bin McAfee repost share .git
Requirements installation failed with status: 1.

**Comment by moisesprojects** [comment]
It's back up - but maybe a bit unstable still

**Comment by jrgifford** [comment]
OK, well then I'd wait for a bit more. Until it's considered back up and stable, this is going to be more than a little difficult to debug. :disappointed:

**Comment by moisesprojects** [comment]
Ok - thanks!

**Comment by pkuczynski** [comment]
@mpapis this issue can be closed I guess...

**Comment by mpapis** [comment]
Thanks @pkuczynski
