### ISSUE TITLE
Can't install RVM on Windows 7 with Cygwin or Babun

### ISSUE THREAD

**Issue by paroliav** [rvm/rvm#3623]
Hi Michal,

Not sure why the armor-keys failed, but I keep getting this error when I do rvm get head
How do I solve this issue?

VivekP@wres23894 ~
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804B                                                                                                                                                             B82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: DBG: armor-keys-failed (KEY 0x409B6B1796C275462A1703113804BB82D39DC0E3 BEGI                                                                                                                                                             N
) ->0
gpg: DBG: armor-keys-failed (KEY 0x409B6B1796C275462A1703113804BB82D39DC0E3 END
) ->0
gpg: key D39DC0E3: "Michal Papis (RVM signing) mpapis@gmail.com" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

VivekP@wres23894 ~
$ rvm get head
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts                                                                                                                                                             /rvm-installer.asc
Verifying /home/VivekP/.rvm/archives/rvm-installer.asc
gpg: can't open `/home/VivekP/.rvm/archives/rvm-installer.asc'
gpg: verify signatures failed: file open error
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures                                                                                                                                                              when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the si                                                                                                                                                             gnatures).

GPG signature verification failed for '/home/VivekP/.rvm/archives/rvm-installer'                                                                                                                                                              - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-ins                                                                                                                                                             taller.asc'!
try downloading the signatures:

```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A170311380                                                                                                                                                             4BB82D39DC0E3
```

or if it fails:

```
command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
```

the key can be compared with:

```
https://rvm.io/mpapis.asc
https://keybase.io/mpapis
```

-bash: return: _ret: numeric argument required

//Cheers
Vivek

**Comment by ylluminate** [comment]
Ever get past this?

**Comment by Ajedi32** [comment]
Same issue:

```
$ curl -sSL https://get.rvm.io | bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
gpg: can't open `/cygdrive/c/Users/ajedi32/.rvm/archives/rvm-1.27.0.tgz.asc'
gpg: verify signatures failed: file open error
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/cygdrive/c/Users/ajedi32/.rvm/archives/rvm-1.27.0.tgz' - 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
    
```

What I find interesting is that the error seems to be saying the file can't be found, even though I checked and it definitely exists in the folder right now.

**Comment by Ajedi32** [comment]
Ah, now _this_ is interesting... it seems I'm not using the Cygwin version of gpg:

```
$ which gpg
/cygdrive/c/Program Files/Git/usr/bin/gpg
```

**Comment by Ajedi32** [comment]
Okay, so I just installed the `gnupg` package in the Cygwin installer, restarted the terminal, and that fixed the problem.

**Comment by pkuczynski** [comment]
This issue is similar to #3213, which discovered, that user might have in path some other `gpg` version than the one coming from Cygwin's `gnupg` package. Such `gpg` would not understand Cygwin's paths and fail to verify the downloaded file.

**Comment by pkuczynski** [comment]
@Ajedi32 I prepared a bugfix for this issue:

`rvm get /bugfix/issue-3623-cygwin-gnupg`

Then to test it you would need to temporarily remove `gnupg` from Cygwin and make sure that `which gpg` points to the `/cygdrive/c/Program Files/Git/usr/bin/gpg` as before.

And then run again:

`rvm get /bugfix/issue-3623-cygwin-gnupg`

Thanks in advance for helping me to test the fix.

**Comment by pkuczynski** [comment]
@ylluminate and @paroliav maybe you can help with the test too?

**Comment by Ajedi32** [comment]
I can't run `rvm get`, as that would require me to already have RVM installed, and in my case it's the installation of RVM itself that's failing.

**Comment by pkuczynski** [comment]
You can run `curl -sSL https://get.rvm.io | bash -s branch /bugfix/issue-3623-cygwin-gnupg` instead of `rvm get`

**Comment by Ajedi32** [comment]
Yep, that worked. Install of RVM succeeded, then when I installed Ruby through RVM it automatically installed Cygwin's gpg.

**Comment by pkuczynski** [comment]
Perfect. Then I can merge this branch and close this issue.
