### ISSUE TITLE
.ruby-version not respected in new tab of gnome-terminal

### ISSUE THREAD

**Issue by csong-r7** [rvm/rvm#3630]
This is a continuation of https://github.com/rvm/rvm/issues/2519. When running rvm 1.26.11 with login shell enabled, opening a new terminal tab in a directory that contains a Ruby project loads the default Ruby instead of one specified by .ruby-version.

```
$ ruby -v
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
$ cat .ruby-version 
2.0.0-p481
$ cd .
$ ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [x86_64-linux]
```

**Comment by vipin8169** [comment]
I am facing the same problem.
Executed the following command in a terminal tab:
vipin8169@vipin8169-Inspiron-5558:~/projectRoot/inmonarch_website$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]

Now, opened the new tab with ctrl+shift+tab and executed the same command, got some version corresponding to some other project
vipin8169@vipin8169-Inspiron-5558:~/projectRoot/inmonarch_website$ ruby -v
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]

When opening new tab, I've to cd into the directory to make it work
cd ./

"Run command as a login shell" is already enabled in the terminal preferences

**Comment by jogaco** [comment]
Same problem with:

- Ubuntu 14.04,

- Terminal Profile Preferences with "Run command as login shell" marked

- default user shell bash shell

- rvm version 1.27.0

- .ruby-gemset + .ruby-version files present

When opening the new tab, the global gemset is on the PATH variable, instead of the local gemset

If I run `cd .`, the correct gemset is picked up

**Comment by raelgc** [comment]
The problem is in Gnome Terminal. While opening a new tab, it's not running a new login.

On 16.04 this is fixed, as the new tab option was removed: you can only open a new terminal (optionally in a tab, but always a new terminal).

**Comment by jogaco** [comment]
Thanks for the info!

**Comment by sigu** [comment]
sorry I am resurrecting this but I made a simple work around for this. The command goes to the parent directory then back to the directory. RVM will be picked up correctly
1. Add the following function  to your `.bashrc` file
``` bash
cd_up_then_back_in () {
  current="$PWD"
  cd ..
  cd $current
}
```
2. Execute the function from `.profile` file as the last line (this is to ensure that rvm is fully loaded to the path before running the command)
``` bash 
# I have included this line to show you where to put the function :-). It should be already present in the file
 [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 
# now call our function 
 cd_up_then_back_in
```

**Comment by heisee** [comment]
Got the same problem with Ubuntu 18.10 
Applied the above solution from @sigu. Works. :+1:

**Comment by simontol** [comment]
`if [ -f '.ruby-gemset' ]; then cd .; fi`
Is enough for me.
Also I put it in .bash_profile fo KDE Konsole
