### ISSUE TITLE
Error running 'requirements_osx_brew_libs_install openssl098',

### ISSUE THREAD

**Issue by saikrishnagaddipati** [rvm/rvm#3632]
Tried to install ruby 1.8.7 in my osx yosemite, but it throws the following error
 rvm install ruby-1.8.7-p374 
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/ruby-1.8.7-p374.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Installing requirements for osx.
Updating system....
Installing required packages: openssl098....
Error running 'requirements_osx_brew_libs_install openssl098',
showing last 15 lines of /Users/sai.krishna/.rvm/log/1456269305_ruby-1.8.7-p374/package_install_openssl098.log
++ case "$1" in
++ [[ -t 1 ]]
++ return 1
++ printf %b 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation\n'
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
++ case "$_system_version" in
++ return 1
Requirements installation failed with status: 1.

did anyone face the similar problem

**Comment by rys** [comment]
Are you able to update to the latest RVM master (```rvm get head```)? OpenSSL 0.9.8 is broken and so homebrew removed support for it recently. We updated rvm shortly after, to match, so if you get the latest rvm you should be able to cleanly build 1.8.7 again.

**Comment by saikrishnagaddipati** [comment]
Thank you rys. It worked for me.

**Comment by hashmee** [comment]
@rys worked for me too
