### ISSUE TITLE
`rvm pkg install openssl' is deprecated. 

### ISSUE THREAD

**Issue by zw963** [rvm/rvm#3637]
In some case e.g. update my system, will cause my rvm ruby broken, the most often happen is
openssl, so, in this case, I can resolve it with:

```sh
$ rvm pkg install openssl --verify-downloads 2
```
It work in most case, But, seem like this command is deprecated.

where is the equivalent ?

Thanks.

**Comment by zw963** [comment]
current system is Linux. Thanks.

**Comment by zw963** [comment]
Close, another question instead.
Thanks

**Comment by cerdiogenes** [comment]
Have you discovered the equivalent command?

**Comment by zw963** [comment]
@cerdiogenes ,It not really resolve my problem,  we still need recompile ruby to make openssl work.

```sh
rvm pkg install openssl --verify-downloads 2
```
above just offer another openssl library, we still need re compile ruby against this version openssl.

my solution is, copy old openssl so file to a directory which included in $RD_LIBRARY_PATH.

all worked file.

**Comment by cerdiogenes** [comment]
I used the following solution:

`rvm install ruby-2.2.1 --patch https://gist.githubusercontent.com/mislav/055441129184a1512bb5/raw --with-gcc=clang`

I also use another compiler because gcc is segfaulting.
