### ISSUE TITLE
No command 'rvm' found, but there are 20 similar ones

### ISSUE THREAD

**Issue by kamajifoo** [rvm/rvm#3638]
I have Linux Mint 17.2. I've installed RVM but it doesn't run. I've tried adding the line in the .bashrc but nothing. Indeed i can't run it from the folder where it was installed. (/usr/share). Please help.

I remember that at the end of the log when I install it, says something about some permission files, but i guess something is wrong, i think isn't the better way. I don't really have any idea why.

**Comment by raelgc** [comment]
Do you mind to try the [Ubuntu package](https://github.com/rvm/ubuntu_rvm)?

**Comment by kamajifoo** [comment]
I don't really knew if it was the package or the instructions, but now I have RVM !
I downloaded the package but was the same thing above, so I followed the next instructions in your page and now it works !!.

At terminal window, click Edit > Profile Preferences, click on Title and Command tab and check Run command as login shell.

My shell don't show menu bar, right clicking can enable the menu. I went to "log off", then log in again and when i wrote "rvm list known"... it works. THANK YOU very much. I had Linux Mint 13 and I did'nt have any problems, I don't know why this new features, anyway I hope to work fine again.

**Comment by raelgc** [comment]
Thank you for the feedback, @kamajifoo!

**Comment by raelgc** [comment]
@kinjal20 Please:

1. Try follow the [Ubuntu package instructions](https://github.com/rvm/ubuntu_rvm).
2. Stop enter the same comment in several different issues in this repo. If you're not sure if you have the same issue as other users, create a new issue. This will make easier for us understand your issue and help you.

**Comment by kinjal20** [comment]
Thank you I tried it and solved previous error but now getting error as below:

command : rvm pkg install openssl
error:  rvm pkg is deprecated ......and at the end

                                  rvm reinstall all --force 
when i run this it shows
error: unknown ruby interpreter version(do not know how to handle):all

so now what should be solution, I stuck at this point?

**Comment by letu81** [comment]
echo "source /etc/profile.d/rvm.sh" >> ~/.bash_profile

vi ~/.bashrc ###then save

if [ -f ~/.bash_profile ]; then
    . ~/.bash_profile
fi

**Comment by r00tvj** [comment]
1. echo "source /etc/profile.d/rvm.sh" >> ~/.bash_profile
2. . ~/.bash_profile
