### ISSUE TITLE
how do i uninstall rvm on kali im getting this bug

### ISSUE THREAD

**Issue by necony286** [rvm/rvm#3639]
there was an error with metasploit and kali rolling so i had to install rvm, it got fiexed. now i want to remove it...
i cant use this to remove it:
$ rvm uninstall 1.8.6
Removing /Users/wayne/.rvm/rubies/ruby-1.8.6-p399...
but when i open my terminal i get this:
bash: /root/.rvm/scripts/rvm: No such file or directory
bash: /root/.rvm/scripts/rvm: No such file or directory
bash: /root/.rvm/scripts/rvm: No such file or directory
bash: /root/.rvm/scripts/rvm: No such file or directory

**Comment by saikrishnagaddipati** [comment]
I am facing the same problem.. necony did you find any solution?

**Comment by necony286** [comment]
well i find out it will stop appearing in the terminal if u edit ur .bashrc file 
delete the end source /root/.rvm/scripts/rvm 
and save it. re open terminal

**Comment by pkuczynski** [comment]
In the future run `rvm implode` to get rid of rvm
