### ISSUE TITLE
Compile a portable ruby with RVM. (not broken by external dependencies)

### ISSUE THREAD

**Issue by zw963** [rvm/rvm#3640]
What I want is:

When my linux is update, or from one linux distribution switch to another distribution, rvm is not 
be broken by some external package update/change. e.g.  openssl, readline, yaml.

from this blog: http://yehudakatz.com/2012/06/05/tokaido-status-update-implementation-details/
I think this is possible, maybe from two way:

1.  use static compilation. I think this way we need compile all dependency library with
     static enable,  e.g. `--static, --enable-static, --disable-shared`, and link those `???.a`
     files to ruby binary.

2. rvm detect system dynamic libary, and copy them into some directory, and then compile
    use normal way, when run ruby binary, always add those directory into `$LD_LIBRARY_PATH`.
    
I think the second way is easy implemented, in fact, my old rvm ruby version, which compile from
another linux distribution,  still can work, because I copy `libssl.so.1`, `libcrypto.so.1` etc file into
current linux home directory ~/linux/lib64, and add this directory to $LD_LIBRARY_PATH.

I want to know is there one RVM official way to do this ?

**Comment by zw963** [comment]
I notice this project by  @mpapis 
https://github.com/sm/sm-libraries

Is current rvm use this project to compile ruby ?
is there any special arguments to archive this?

Thanks

**Comment by zw963** [comment]
Here is another project.
https://github.com/phusion/traveling-ruby

is there exist a rvm plugins for use `traveling-ruby` ?

Thanks

**Comment by mpapis** [comment]
`sm` is used for building OSX binaries, but rvm2 will replace/merge both rvm and sm - with the benefit of having it in ruby.

for traveling ruby:
```bash
rvm mount -r http.../path/to/ruby.tgz
```

**Comment by mpapis** [comment]
the problem with static builds is: they wont get security updates when you update your system.

that said you can still try to compile static rubies, it's rarely used option and some systems don't even provide libraries for static binding, but if you get such system it should be possible to pass `-- --static` to the installation command .

closing as in RVM 1 there is limited support, but it's nothing that was maintained, and because of split of code between two tools `rvm` and `sm` - it's hard to make it work. it should be a lot simpler in RVM 2.

**Comment by zw963** [comment]
Thank a lot for reply, and rvm mount is help me a lot.
use rvm mount -r http://...traveling-ruby-20150210-2.1.5-linux-x86_64.tar.gz, ruby can be install successfully,  but,  in my terminal, it show like this:

```
$ ╭─ 22:50  zw963 ⮀ ~ ⮀ ➦ traveling-ruby-20150210
```
this info not display ruby version.

I have try following command, all not work.

```sh
$ rvm mount -r ./traveling-ruby-20150210-2.1.5-linux-x86_64.tar.gz -n ruby-2.1.5
$ rvm mount -r ./traveling-ruby-20150210-2.1.5-linux-x86_64.tar.gz ruby-2.1.5
```

Thanks.

**Comment by zw963** [comment]
Hi,  I publish a little bash script in this gist.
https://gist.github.com/zw963/b72c425317869781d03a

Just for man who want to install ruby with RVM from traveling ruby convenient.

this script add a bash function named `rvmm`. (rvm mount)

install RVM with traveling-ruby is simple enough to just two step.

1. goto https://d6r77u77i8pq3.cloudfront.net/ select needed version.
   e.g. traveling-ruby-20150715-2.2.2-linux-x86.tar.gz, just remember `20150715-2.2.2`

2. rvmm 20150715-2.2.2

done! this will install a new platfrom-independent version ruby into favorite RVM.

in my terminal, it look like this:
 ╭─ 00:25  zw963 ⮀ ~ ⮀ ➦ ruby-2.1.5-20150210
it easily to distinguish normally rvm installed ruby version with rvm mounted version.

**Comment by mpapis** [comment]
you could extend `rvm mount` to include `-t` as for traveling :)
