### ISSUE TITLE
pg.rb:4:in `require': incompatible library version

### ISSUE THREAD

**Issue by pejuko** [rvm/rvm#3645]
I have system wide installation of ruby 2.3 and if I install pg gem under ruby-2.2.4 with rvm I'm getting this error. ldd says:

```
ldd ~/.rvm/gems/ruby-2.2.4/gems/pg-0.18.4/ext/pg_ext.so   
        linux-vdso.so.1 (0x00007fff1cbad000)
        libruby.so.2.3 => /usr/lib/libruby.so.2.3 (0x00007fb9da57b000)
```

so, as you can see, the pg extension is linked with system wide ruby 2.3 and not with ruby-2.2.4.

I'm using rvm head (rvm 1.26.11 (master))

**Comment by a-barbieri** [comment]
Same here. rvm 1.26.11 (latest). ruby-2.2.4. pg-0.18.4

**Comment by mpapis** [comment]
looks like you might have broken `PATH`, make sure your shell initialization files do not overwrite it.

as next step in either fresh session or after `rvm use 2.2.4` make sure `PATH` starts with  the same paths as `GEM_PATH` does (+`/bin`)

next uninstall all gems you previously installed: `rvm gemset empty`

now you should be able to install gems without conflicts

**Comment by pebra** [comment]
Not working for me as well, this is my PATH. Did also run ```rvm gemset empty``` after checking my paths.
```
echo $GEM_PATH
/home/pebra/.rvm/gems/ruby-2.2.4:/home/pebra/.rvm/gems/ruby-2.2.4@global

echo $PATH
/home/pebra/.rvm/bin:/home/pebra/.rvm/gems/ruby-2.2.4/bin:/home/pebra/.rvm/gems/ruby-2.2.4@global/bin:/home/pebra/.rvm/rubies/ruby-2.2.4/bin:[...
]
```

**Comment by mpapis** [comment]
there it is, `/home/pebra/.rvm/bin` is first in `PATH` try: `rvm use 2.2.4` to fix it - otherwise `default` ruby will be used with `2.2.4` gems.

**Comment by pebra** [comment]
> make sure PATH starts with the same paths as GEM_PATH does (+/bin)
```
echo $GEM_PATH                                                                                                                                                                                    
/home/pebra/.rvm/gems/ruby-2.2.4:/home/pebra/.rvm/gems/ruby-2.2.4@global
echo $PATH
/home/pebra/.rvm/gems/ruby-2.2.4/bin:/home/pebra/.rvm/gems/ruby-2.2.4@global/bin:/home/pebra/.rvm/rubies/ruby-2.2.4/bin:/home/pebra/.rvm/bin
```
After checking this I ran ```rvm gemset empty``` ```gem install bundler``` and ```bundle install``` unfortunately the problem still occurs =( Paths looking ok now don't they?

**Comment by mpapis** [comment]
looks like it might be a bug in `ruby-2.2` could you check with #3643 and confirm that temporary moving the file conflicting to a site fixes it?

**Comment by pebra** [comment]
I completely removed rvm, installed ruby 2.2.4p230 from source and my application got back to a working state. So maybe it is indeed a rvm issue?

**Comment by mpapis** [comment]
@pebra can you paste steps you used to compile from source so I could compare them with what happens in rvm?

**Comment by pebra** [comment]
Pretty much stuck to the instructions from the ruby website:
```
./configure
make
sudo make install
which ruby  # => /usr/local/bin/ruby
export GEM_HOME=MY_HOME/.gem
```

**Comment by mpapis** [comment]
is there any chance you could give me `ruby -rrbconfig -e 'puts RbConfig::CONFIG.sort.map{|k,v| "#{k}: #{v}" }'` from the both rvm installed version and your own? (maybe [gist](https://gist.github.com) it as they will be long)

**Comment by pebra** [comment]
Sorry my last comment was not true. I realized I'm now actually using a ruby version that was installed via yaourt so the procedure was like [https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ruby2.2](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ruby2.2). Lines 48 to 56 might be interesting there. However I can check the output of the command you provided.

**Comment by pebra** [comment]
Here is the output you asked for: https://gist.github.com/pebra/1896fcd26410dc934c1e685ea079c49f

**Comment by mpapis** [comment]
that's a hell of nonstandard instructions, but I can not find something specific that would make it not work, rvm itself does not passes extra flags that would tell ruby to link against the macports ruby, that's why I asked to half manual experiment in https://github.com/rvm/rvm/issues/3643#issuecomment-206265129 - to find out if this is reproducible without rvm with the same flags - I do not have time to reproduce this use case myself, that's why I need help with it.

**Comment by pebra** [comment]
Sure, I'll try it out. Thanks for investigating!

**Comment by dieze** [comment]
Update to ruby 2.3.1 <https://bugs.ruby-lang.org/issues/9760#note-14>

**Comment by SoxFace** [comment]
I'm getting the same error for $ rails c

pg 9.6
ruby 2.3.1p112
Rails 4.2.7

Can someone offer any insights on my paths? I've used rmv to install rails but I'm not too strong on /bin and paths etc.

I've ran `rvm gemset empty` `gem install bundler` and` bundle install` and no joy.

```
$ echo $GEM_PATH
/Users/131432/.rvm/gems/ruby-2.3.1@LtiOutcomes:/Users/131432/.rvm/gems/ruby-2.3.1@global
```
```
$ echo $PATH
/Users/131432/.rbenv/shims:/Users/131432/.rbenv/shims:/Users/131432/.rvm/gems/ruby-2.3.1@LtiOutcomes/bin:/Users/131432/.rvm/gems/ruby-2.3.1@global/bin:/Users/131432/.rvm/rubies/ruby-2.3.1/bin:/Users/131432/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Applications/Postgres.app/Contents/Versions/latest/binsource
```

**Comment by jusmat** [comment]
@SoxFace I suggest upgrading ruby to 2.3.3 as your path seems to be correctly set. After doing that I was able to solve this issue by running `rvm gemset empty` followed by `gem install bundler` and `bundle install`

**Comment by SoxFace** [comment]
Thank you so much @jusmat - it worked, I can now access the rails console.

`rvm install ruby-2.3.3`
`rvm gemset empty`
`gem install bundler`
`bundle install`

**Comment by gautamworah96** [comment]
this works!

> Thank you so much @jusmat - it worked, I can now access the rails console.

rvm install ruby-2.3.3
rvm gemset empty
gem install bundler
bundle install

**Comment by dave-oz** [comment]
Everything sounds great, the fixes are working but why this is caused in the first place? 
I need to make sure that this is not gonna affect our production server again. I don't think that this is completely fixed if it's gonna happen again randomly out of nowhere. 
I didn't even have time to do 'ldd' on `lib/pg_ext.so` since I had to bring the production back up quickly.
`gem pristine pg` or 'gem pristine --all' in that matter also works to fix this. 

The error I got was
```
App 22902 output: Error: The application encountered the following error: incompatible library version - /usr/local/rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg_ext.so (LoadError)
App 22902 output:     /usr/local/rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg.rb:5:in `require'
App 22902 output:     /usr/local/rvm/gems/ruby-2.6.3/gems/pg-1.2.3/lib/pg.rb:5:in `<top (required)>'
App 22902 output:     /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `require'
App 22902 output:     /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:81:in `block (2 levels) in require'
App 22902 output:     /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `each'
App 22902 output:     /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:76:in `block in require'
App 22902 output:     /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `each'
App 22902 output:     /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/runtime.rb:65:in `require'
App 22902 output:     /usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler.rb:114:in `require'
```
