### ISSUE TITLE
Unknown ruby interpreter version (do not know how to handle):  2.2.4.

### ISSUE THREAD

**Issue by rbatta** [rvm/rvm#3646]
Hi, I'm working on a repo that we recently upgraded from 2.0.0 to 2.2.4. I'm on a new Mac and git cloned the repo with `.ruby-version` already pointing to 2.2.4. 

Every time I `cd` into that directory, I get the above error:
```
Unknown ruby interpreter version (do not know how to handle):  2.2.4.
```

It does NOT properly create my gemset by reading the `.ruby-gemset` file when cd'ing into the dir.

I have tried `rvm get head` but that has no impact. Only turns the error red upon first directory change.  I've also tried `rvm uninstall 2.2.4` then `rvm install 2.2.4` but that also doesn't seem to work.

I've another repo that uses 2.2.4, and that works perfectly as expected. The other repo also has `.ruby-version` and `.ruby-gemset` files, so the gemset is properly created.

The other issues I've found on here / SO relate to what seems to be slightly different issues and not the actual ruby version...but I did try them. I'm reluctant to work on the app in this state (unless it's only a warning message, but doesn't explain the gemset not being created) and push any changes that might affect other teammates.

Any help would be appreciated; thanks.

**Comment by rbatta** [comment]
As soon as I posted this, found the issue. It was a spare space in the `.ruby-version` file. :\ Closing.

**Comment by kinjal20** [comment]
rvm pkg install openssl
It shows that rvm pkg is deprecated ......and at the end

                                      rvm reinstall all --force 

when i run this it shows
unknown ruby interpreter version(do not know how to handle):all

now what can solution of it?
