### ISSUE TITLE
jruby should default to 9.0.5.0

### ISSUE THREAD

**Issue by perlun** [rvm/rvm#3648]
I have a `.ruby-version` file in my project that looks like this:

```
$ cat .ruby-version
jruby
```

When I cd to this folder, I get the following:

```
$ cd foo
Unknown ruby string (do not know how to handle): jruby-9.0.4.0.
jruby-9.0.4.0 is not installed.
To install do: 'rvm install jruby-9.0.4.0'
```

I do have 9.0.5.0 installed, but it seems to prefer 9.0.4.0 for some random reason. I just did `rvm get head`, but it didn't help. Tried to poke around in this repo but couldn't find any obvious place where `jruby` is pointed at `9.0.4.0`. Any ideas/suggestions? TIA.

**Comment by JulianNicholls** [comment]
Do you also have a Gemfile which specifies a Ruby version?

**Comment by perlun** [comment]
Nope, I couldn't find any references to that there:

```
$ grep jruby Gemfile*
$ grep 9.0.4 Gemfile*
```

`java` is being referenced (since some packages installed are special jruby versions).

FWIW: I get the same behavior if I create a blank directory with just a `.ruby-version` file with the same content.

**Comment by rys** [comment]
I think it's because we have jruby_version set to 9.0.4.0 in the db. I'll test and if that fixes it I'll submit to master.
