### ISSUE TITLE
Installing ruby 2.1.5 using rvm on linux mint (ROSA) version

### ISSUE THREAD

**Issue by ramthakur1991** [rvm/rvm#3650]
Hi 

I'm getting the following error while installing ruby 2.1.5 using rvm 

``` bash
error running '__rvm_make -j4',
showing last 15 lines of /home/mss/.rvm/log/1458716707_ruby-2.1.5/make.log
make[2]: *** [md5init.o] Error 1
make[2]: Leaving directory `/home/mss/.rvm/src/ruby-2.1.5/ext/digest/md5'
make[1]: *** [ext/digest/md5/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling date_strftime.c
compiling date_strptime.c
installing default date_core libraries
installing default bigdecimal libraries
linking shared-object bigdecimal.so
make[2]: Leaving directory `/home/mss/.rvm/src/ruby-2.1.5/ext/bigdecimal'
linking shared-object date_core.so
make[2]: Leaving directory `/home/mss/.rvm/src/ruby-2.1.5/ext/date'
make[1]: Leaving directory `/home/mss/.rvm/src/ruby-2.1.5'
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.
```

I have tried various way like 
1) `rvm install 2.1.5 -C --with-openssl-dir=$HOME/.rvm/usr/ssl/openssl.cnf`
2) `rvm install 2.1.5 -C --with-readline-dir=$HOME/.rvm/usr`

but getting same error each and every time 

I also tried the following command to reset the RVM and then try to install the ruby but getting the same error .

if anyone can help me out this issue . Any kind of help is appreciable

Thanks

**Comment by mpapis** [comment]
looks like it might require backporting some patches, please see if using `--patch ...` with any of the files in: `ls $rvm_path/patches/ruby`

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Comment by ramthakur1991** [comment]
@mpapis, sorry for late reaply. 
I just figure out this issue and solved it 

once again sorry for late reply 
and Thanks for your reply

**Comment by ladykat** [comment]
Hello folks, what is the solution that you have found? kindly share.

**Comment by mpapis** [comment]
@ladykat please open a new ticket with all the details suggested in the template
