### ISSUE TITLE
I have search methods of this for a afternoon,but I can't 

### ISSUE THREAD

**Issue by cjxs** [rvm/rvm#3652]
Last login: Mon Mar 28 16:34:56 on ttys000

Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
    https://github.com/rvm/rvm/issues/3212

**Comment by mpapis** [comment]
check your shell initialization files for `PATH=` any occurrences that do not include `$PATH` should or `+(` should be removed (or just commented out).

**Comment by runofthemill** [comment]
@cjxs see voltaaage's comment on that thread for solution: https://github.com/rvm/rvm/issues/3212#issuecomment-177415287

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
