### ISSUE TITLE
RVM was not able to detect system type on Netrunner Rolling

### ISSUE THREAD

**Issue by Fensterbank** [rvm/rvm#3654]
On Netrunner Rolling I cannot install rvm.
> No binary rubies available for: unknown/libc-2.23/x86_64/ruby-2.3.0.

Netrunner Rolling is full Arch/Manjaro-compatible (based on it) and uses pacman.

```
$ head -n 100 /etc/*release
==> /etc/lsb-release <==
DISTRIB_ID=Netrunner
DISTRIB_RELEASE=2016.01-RC
DISTRIB_CODENAME=Rolling
DISTRIB_DESCRIPTION="Netrunner Rolling"

==> /etc/manjaro-release <==
Manjaro Linux

==> /etc/os-release <==
NAME="Netrunner Rolling"
ID=netrunner rolling
PRETTY_NAME="Netrunner Rolling Edition"
ANSI_COLOR="1;32"
HOME_URL="http://www.netrunner.com/"
```

I think the same things need to be done like in #1779 when Manjaro detection was added.

**Comment by mpapis** [comment]
we can add detection - you could use the mentioned issue to add the support and open a PR for it.

but... it will not make binaries available, arch and other rolling releases do not provide stable release that will keep libraries in proper versions needed for the installed ruby - any update could break the existing ruby installation.

it is possible that RVM2 will be able to hook into system and reinstall rubies if the crucial libraries versions are bumped, for RVM1 we do not plan any new features.

closing the issues, feel free to open PR with the fixed detection of the distribution, in worst case the code should find it as arch, right?

**Comment by Fensterbank** [comment]
Thanks for the reply.
I fixed it for me by taking a look in the debug messages and installing the right requirements for compilation.
Due to the missing OS detection it cannot automatically install the requirements for ruby compilation, but I don't think it's a big problem and ruby developer using Arch based systems should be able to handle this. ;-)
Yes, simply detect it as Arch could even help.
If I have the time, I will think about making a PR.

**Comment by pkuczynski** [comment]
@Fensterbank if you would list missing requirements, I could easily add them to RVM...
