### ISSUE TITLE
Ruby 2.3.0

### ISSUE THREAD

**Issue by nirvikk** [rvm/rvm#3658]
I am having problem switching to version 2.3.0 using:
rvm use --default 2.3.0

Every time I have to execute the command.

**Comment by Erusy** [comment]
Did you try:
`$ rvm --default use 2.3.0`

**Comment by nirvikk** [comment]
most definitely I did

**Comment by mpapis** [comment]
can we see output from `rvm list`?

**Comment by xTheSeeker** [comment]
I had the same issue. I resolved adding this in my ~/.bashrc:

```
alias login="/bin/bash --login"
login
rvm use 2.3.0
```

and this is like look my ~/.profile:

```
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" 
```
