### ISSUE TITLE
GPG signature verification failed 

### ISSUE THREAD

**Issue by RanaZubair** [rvm/rvm#3660]
Got this error during installing on my ubuntu desktop. 

"GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.27.0.tgz' - 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc'!
try downloading the signatures:

    sudo gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"

How to resolve this error...

**Comment by raelgc** [comment]
Hi @RanaZubair. 

Do you mind to try the [Ubuntu package](https://github.com/rvm/ubuntu_rvm)?

**Comment by raelgc** [comment]
If it works, please, remember to give feedback and close this issue.

If it doesn't work, we can help you too :)

**Comment by RanaZubair** [comment]
I use this link. RVM is now working perfectly but don't know what was the issue. I was getting this error... But now everything works perfectly.. Thanks for your help...

**Comment by raelgc** [comment]
Nice to hear it's working now! Thanks for the feedback.

**Comment by XavierHll55** [comment]
Thanks _**raelgc**_! Ubuntu Package = Problem  Solved.

**Comment by aravindgpd** [comment]
GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.27.0.tgz' - 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc'!
try downloading the signatures:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

in my fedora please help

**Comment by raelgc** [comment]
Hi @aravindgpd. Had you tried to run the suggested command?

**Comment by aravindgpd** [comment]
Yes but command is suitable for Ubuntu not for fedora can you help me for fedora terminal commands

**Comment by aravindgpd** [comment]
Command is not working in Fedora machine

**Comment by warlock20** [comment]
@aravindgpd Install rvm in your machine using dnf..

**Comment by nazzalra** [comment]
---------------------------------TRY THIS BROTHER------------------------------

first install gpgv2
sudo apt-get install gpgv2

secondly
curl -sSL https://rvm.io/mpapis.asc | gpg --import

**Comment by phuongthengoc** [comment]
@nazzalra: thank bro... You just save my computer.

**Comment by augustocbx** [comment]
Try
`gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`
