### ISSUE TITLE
Error when install ruby-2.3.0 with ubuntu 12.10

### ISSUE THREAD

**Issue by nguyenngoc2505** [rvm/rvm#3661]
I am trying to install `ruby-2.3.0` in ubuntu 12.10, But it has an error
```ruby
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/12.10/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system..ngoc password required for 'apt-get --quiet --yes update': 
......................................
Error running 'requirements_debian_update_system ruby-2.3.0',
showing last 15 lines of /home/ngoc/.rvm/log/1460083128_ruby-2.3.0/update_system.log
++ 1460083240.500161019 /scripts/functions/logging : rvm_pretty_print()  78 > case "${TERM:-dumb}" in
++ 1460083240.503363549 /scripts/functions/logging : rvm_pretty_print()  81 > case "$1" in
++ 1460083240.507021444 /scripts/functions/logging : rvm_pretty_print()  11 > [[ -t 2 ]]
++ 1460083240.511677340 /scripts/functions/logging : rvm_pretty_print()  83 > return 1
++ 1460083240.516706779 /scripts/functions/logging : rvm_error()  117 > printf %b 'There has been error while updating '\''apt-get'\'', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list
\n'
There has been error while updating 'apt-get', please give it some time and try again later.
404 errors should be fixed for rvm to proceed. Check your sources configured in:
    /etc/apt/sources.list
    /etc/apt/sources.list.d/*.list

++ 1460083240.523916408 /scripts/functions/requirements/ubuntu : requirements_debian_update_system(return 100
Requirements installation failed with status: 100.
```

Have someone help me solve this problem?
Thanks,

**Comment by raelgc** [comment]
Hi @nguyenngoc2505 and thanks for reporting this issue.

In a first look, sounds like your `apt` is facing some issues while updating.

Can you, please, post the output of `sudo apt-get update` ?

**Comment by nguyenngoc2505** [comment]
Hi @raelgc, Thank for your look. This is my output when running `sudo apt-get update`
https://gist.github.com/nguyenngoc2505/da843b52bfa3146ba0c6fc11f0d9f422
I've searched about them, but have not solved yet.

**Comment by raelgc** [comment]
A lot of `404` errors during `apt-get`. Because Quantal 12.10 is no more supported.

If you want to use a Ubuntu version for more than 9 months, you must use a LTS version (12.04, 14.04 or 16.04).

Or keep upgrading to the latest (if you want use bleeding-edge-but-not-so-stable software).

I'm closing this because `rvm` is acting as expected, interrupting the process when `apt update` return errors (while the message could be more friendly).

**Comment by DerWanderer** [comment]
FYI, I ran into the same issue on 16.04, but just commented out lines for extras.ubuntu.com in /etc/apt/sources.list (just two lines) and the installation ran smoothly.  I agree; the message could be more friendly.

**Comment by jrgifford** [comment]
@DerWanderer That's odd! Can you post the 2 lines in `/etc/apt/sources.list` for extras.ubuntu.com? I'm curious about how/why it's causing problems, because the extras repo is updated for each version of ubuntu.

**Comment by DerWanderer** [comment]
Here you go:

#deb http://extras.ubuntu.com/ubuntu xenial main
#deb-src http://extras.ubuntu.com/ubuntu xenial main

They were resulting in 404 errors.

**Comment by sachinsreedar92** [comment]
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/

**Comment by pkuczynski** [comment]
@sachinsreedar92 could you please open a new issue and provide all the details mentioned in the issue template?
