### ISSUE TITLE
ruby 2.3.1 install fails without error

### ISSUE THREAD

**Issue by perlun** [rvm/rvm#3686]
I am having a very weird error where I cannot install Ruby 2.3.1 properly.

```shell
$ rvm --version
rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
```

...and that's all I get. _It does not get installed_.

The same error occurs with 2.3.0.

Any suggestions?

**Comment by perlun** [comment]
Tried removing all of my `rvm` installation and reinstalling. It still fails. 😢 JRuby versions work fine to install (but they need no compilation etc so it's of course much simpler by nature)

**Comment by perlun** [comment]
I looked at the list of pre-built binaries here: https://rvm.io/binaries/osx/10.11/x86_64/

2.2.3 works fine. So it seems like it's the compilation parts that fail, unfortunately very silently.

**Comment by perlun** [comment]
Still broken. Anyone has any idea on what to do about this? FWIW, I tried to do the install with `--debug` active:

```shell
$ rvm install --debug ruby-2.3.1
ruby-2.3.1 - install
ruby-2.3.1 - #already removed src/ruby-2.3.1
ruby-2.3.1 - #already removed rubies/ruby-2.3.1
Searching for binary rubies, this might take some time.
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.11/x86_64/ruby-2.3.1.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/ruby-2.3.1.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.11/x86_64/ruby-2.3.1.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.11/x86_64/ruby-2.3.1.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/ruby-2.3.1.tar.bz2
Remote file does not exist https://rubies.travis-ci.org/osx/10.11/x86_64/ruby-2.3.1.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Free disk space 353416MB, required 440MB.
__rvm_setup_compile_environment_setup ruby-2.3.1
rvm_autolibs_flag=4
__rvm_setup_compile_environment_movable_early ruby-2.3.1
__rvm_setup_compile_environment_system_early ruby-2.3.1
__rvm_setup_compile_environment_requirements ruby-2.3.1
Checking requirements for osx.
requirements code for osx loaded
requirements lib type set to osx_brew
brew seems to be writable
Found required packages: autoconf, automake, libtool, pkg-config, libyaml, readline, libksba, openssl.
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/plundberg/.rvm/gems/jruby-9.1.1.0/bin:/Users/plundberg/.rvm/gems/jruby-9.1.1.0@global/bin:/Users/plundberg/.rvm/rubies/jruby-9.1.1.0/bin:/Users/plundberg/.nvm/versions/node/v5.9.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/plundberg/bin:/Users/plundberg/git/ecraft/ecraft.uxfactory.bin:/usr/local/mongodb/bin:/Users/plundberg/.rvm/bin
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libyaml )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/readline )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libksba )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/openssl )
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
__rvm_setup_compile_environment_movable ruby-2.3.1
__rvm_setup_compile_environment_parse_name ruby-2.3.1
__rvm_setup_compile_environment_system ruby-2.3.1
__rvm_setup_compile_environment_architectures ruby-2.3.1
rvm_architectures(0):.
__rvm_setup_compile_environment_gcc47plus ruby-2.3.1
__rvm_setup_compile_environment_bison ruby-2.3.1
__rvm_setup_compile_environment_flags_docs ruby-2.3.1
__rvm_setup_compile_environment_flags_shared_static ruby-2.3.1
__rvm_setup_compile_environment_flags_threads ruby-2.3.1
__rvm_rm_rf already gone: /Users/plundberg/.rvm/tmp/1461*
```

**Comment by Raviindorey** [comment]
I was looking for binaries myself just now, that's how I ended up reading your post. Well I'm sorry to say that we can't do anything about it. Binaries for ruby-2.3.1 is not available at this moment. Maybe all we have to do is wait. I'll continue to use older version for a while.

**Comment by Raviindorey** [comment]
But still if you really really want to install ruby-2.3.1at this moment then you'll have to do it **WITHOUT** RVM. 
Download ruby: https://www.ruby-lang.org/en/downloads/
then just: 
$ ./configure
$ make
$ sudo make install

**Comment by bianjp** [comment]
`rvm get latest` or `rvm get head` solved the problem.

If you see another error saying "Downloaded archive checksum did not match", run `rvm cleanup archives` and retry.

**Comment by perlun** [comment]
I'm still getting this, unfortunately:

```
$ rvm install ruby-2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
rvm --version
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
[10:40:43] plundberg@ecvaawplun5:~/git/ecraft/blog.ecraft.io (master)
$ rvm --version
rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

**Comment by perlun** [comment]
Anyone has any ideas whatsoever? This is really really frustrating and I have no idea on how to solve it unfortunately. :cry: I'll gladly help with debugging this if anyone can point me in the right direction.

**Comment by perlun** [comment]
I think I've managed to work around it now!

```
rvm install ruby-2.3.1 --disable-binary -j 8
```

This actually got the compilation started etc. I tried removing the `-j 8` part, but then I get the same behavior as before, i.e. the compilatin never starts. So it seems like the "detect number of CPU threads" functionality is, for whatever reason, breaking it on my machine.

@siegel - could you try if that makes it work for you as well?

**Comment by BreaGaudioso** [comment]
+1

**Comment by pkuczynski** [comment]
We just uploaded 2.3.1 binaries for OSX El Capitan.

```
rvm get master
rvm install 2.3.1
```

should solve your problem.

**Comment by perlun** [comment]
Thanks. It also seems to properly compile from source now (without having to manually give the "no binaries" parameter).

**Comment by jbacklund** [comment]
It doesn't find the binaries for me. Also running on OS X El Capitan:

```shell
ecvaawjback:ecraft.rentals-app jakobbacklund$ rvm get master
Downloading https://get.rvm.io
No GPG software exists to validate rvm-installer, skipping.
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /Users/jakobbacklund/.rvm/
    RVM PATH line found in /Users/jakobbacklund/.profile.
    RVM PATH line not found for Bash or Zsh, rerun this command with '--auto-dotfiles' flag to fix it.
    RVM sourcing line found in /Users/jakobbacklund/.profile /Users/jakobbacklund/.bash_profile /Users/jakobbacklund/.zlogin.
Upgrade of RVM in /Users/jakobbacklund/.rvm/ is complete.

# Jakob Backlund,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

RVM reloaded!
ecvaawjback:ecraft.rentals-app jakobbacklund$ rvm install 2.3.1 --binary
Searching for binary rubies, this might take some time.
Requested binary installation but no rubies are available to download, consider skipping --binary flag.
```

**Comment by pkuczynski** [comment]
We dropped binaries, as our build was causing some other issues, which we trying to solve. Please build from source now.

**Comment by perlun** [comment]
Alright. Good to get that noted, because the facts here (when looking at this with @jbacklund) didn't seem to match my world view there for a moment.

**Comment by ayercm** [comment]
I'm trying to make 2.3.1 on Sierra but the compiler is not working:

Colins-Work-MacBook:ruby-2.3.1 colinayer2$ ./configure
checking for ruby... /usr/local/bin/ruby
config.guess already exists
config.sub already exists
checking build system type... x86_64-apple-darwin16.0.0
checking host system type... x86_64-apple-darwin16.0.0
checking target system type... x86_64-apple-darwin16.0.0
checking for clang... clang
checking for gcc... (cached) clang
**checking whether the C compiler works... no**
configure: error: in `/Users/colinayer2/Software/ruby-2.3.1':
configure: error: C compiler cannot create executables
See `config.log' for more details

**Comment by pkuczynski** [comment]
Could you please create separate ticket for Sierra and paste you config.log there?

**Comment by ayercm** [comment]
@pkuczynski I fixed may issue upgrading to Xcode Version 8.1 beta (8T29o) which I should have tried long before all the other things I tried. Should I still create that separate ticket for Sierra?

**Comment by pkuczynski** [comment]
No, not really. I will remember that upgrade to 8.1 helps when I will be building binaries for Sierra.

**Comment by perlun** [comment]
Very strange: this has now _reappeared_ with rvm head:

```$ rvm install 2.4.1
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.4.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
```

When I added the `-j 8` it started downloading and compiling it...

Can we reopen the original issue or should we file a new one about it?

**Comment by pkuczynski** [comment]
Please open a new issue. You might refer this one and suggest its similar.

**Comment by ouye111** [comment]
I have the seem issue.

**Comment by perlun** [comment]
@ouye111 please report a new issue about, the ones I reported are closed by now.

**Comment by Aspect9** [comment]
Great Thread =) Praise Be!

**Comment by KoMiToRaY** [comment]
thx a lot @pkuczynski
