### ISSUE TITLE
Missing binaries for ruby 2.3.x

### ISSUE THREAD

**Issue by TomFreudenberg** [rvm/rvm#3689]
Hi,

when looking at https://rvm.io/binaries there are currently no binaries for ruby 2.3.x.

Is there some reason why not supporting 2.3.x but having only 2.2.x binaries there?

Thanks for a short hint, I need 2.3 (Array bsearch_index) but cannot compile ruby sources on that machine.

Tom

**Comment by raelgc** [comment]
Hi @TomFreudenberg. Not sure which is your operating system, but I'm adding [some binaries for Ubuntu](https://github.com/rvm/rvm/pull/3694).

**Comment by TomFreudenberg** [comment]
Hi Rael @raelgc 

thanks for doing and notification. Ubuntu is one I am using as well but mostly I am looking for the Mac OSX binaries. Maybe they will get attached also in the next time.

Cheers
Tom

**Comment by msx2** [comment]
@mpapis Any chance for OSX binaries with ruby 2.3.1? 😬

**Comment by TomFreudenberg** [comment]
+1 (that would be great)

**Comment by pkuczynski** [comment]
Having OSX binaries would also solve #3729, #3686, #3671 and #3656

**Comment by pkuczynski** [comment]
We just uploaded 2.3.1 binaries for OSX El Capitan.

```
rvm get master
rvm install 2.3.1
```

should solve your problem.

**Comment by TomFreudenberg** [comment]
@pkuczynski ( Piotr )

Thanks for doing that!
