### ISSUE TITLE
Ubuntu 16.04 binaries

### ISSUE THREAD

**Issue by raelgc** [rvm/rvm#3693]
Add the following binaries for Ubuntu 16.04:

* 2.0.0-p648
* 2.1.9
* 2.2.5
* 2.3.0

**Comment by joshuaspence** [comment]
Any chance of adding 2.1.5 as well? We use Ubuntu 12.04, 14.04 and want to start using 16.04 but there is no common Ruby 2.1.x binary for these distributions at the moment.

**Comment by raelgc** [comment]
@joshuaspence I'm working on this!
