### ISSUE TITLE
Error While installing Ruby through RVM on Ubuntu 14.04.4 LTS 

### ISSUE THREAD

**Issue by webhacking** [rvm/rvm#3698]
Hi. i am trying to install Ruby with Rails through  rvm. But is not working .. I am using this command `rvm requirements` .. and i am consulted this [document](http://tecadmin.net/install-ruby-on-rails-on-ubuntu/). How can i fixed this problem ..? Thank you for reading.

Here is my command : 
```
rvm requirements
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system...
Installing required packages: libyaml-dev, sqlite3, libgmp-dev, libgdbm-dev, libncurses5-dev....
Error running 'requirements_debian_libs_install libyaml-dev sqlite3 libgmp-dev libgdbm-dev libncurses5-dev',
showing last 15 lines of /usr/local/rvm/log/1465982191/package_install_libyaml-dev_sqlite3_libgmp-dev_libgdbm-dev_libncurses5-dev.log
Package libgmp-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libyaml-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libyaml-dev' has no installation candidate
E: Package 'sqlite3' has no installation candidate
E: Package 'libgmp-dev' has no installation candidate
E: Package 'libgdbm-dev' has no installation candidate
E: Package 'libncurses5-dev' has no installation candidate
+ return 100
+ return 100
Requirements installation failed with status: 100.

```

**Comment by raelgc** [comment]
Something is wrong with your `apt`, maybe configuration.

All those packages listed as `has no installation candidate` do exist in 14.04:

* [libyaml-dev](http://packages.ubuntu.com/trusty/libyaml-dev)
* [sqlite3](http://packages.ubuntu.com/trusty/sqlite3)
* [libgmp-dev](http://packages.ubuntu.com/trusty/libgmp-dev)
* [libgdbm-dev](http://packages.ubuntu.com/trusty/libgdbm-dev)
* [libncurses5-dev](http://packages.ubuntu.com/trusty/libncurses5-dev)

Additionally, please try install `rvm` using the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm).

**Comment by webhacking** [comment]
@raelgc 👍

**Comment by mmiakashs** [comment]
@webhacking I am facing the same problems, specifically for the packages libgdbm-dev and libgmp-dev. Could you please suggest how you solve this problem if you solved this? Thanks

**Comment by raelgc** [comment]
@mmiakashs After update your system packages (with `sudo apt update && sudo apt dist-upgrade`) try install `rvm` using the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm).

**Comment by mmiakashs** [comment]
@raelgc  Thanks for your comment. I solved the problem. I had an issue in the apt configuration. I followed your previous comment.
