### ISSUE TITLE
Support the Ruby version twiddle-waka

### ISSUE THREAD

**Issue by afeld** [rvm/rvm#3705]
(that is the funnest GitHub issue title I have ever made)

Hi! I'm interested in supporting a range of Ruby versions in my application, so I was going to specify something like the following in my Gemfile:

```ruby
ruby '~> 2.3.0'
```

When I navigated out of and back into the directory, however, I got the following warning:

```
Unknown ruby interpreter version (do not know how to handle): ~>2.3.0.
```

Would love to have parity with Bundler! More info:

http://bundler.io/gemfile_ruby.html

**Comment by mpapis** [comment]
unfortunately RVM v1 is written in shell an implementing pessimistic operator is out of question ... unless you know of fast shell implementation for it?

this is planned feature for RVM v2 which will be in Ruby, but till it's available - I do not think we can do anything with what we have right now - closing the ticket.

**Comment by afeld** [comment]
Bummer. Thanks for the quick response!
