### ISSUE TITLE
Ruby 2.3.1 for Centos 6.6

### ISSUE THREAD

**Issue by avogeltanz** [rvm/rvm#3712]
I would like a binary available for Centos 6.6. I am willing to build the binary and checksums. Any information on how to proceed would be greatly appreciated.

**Comment by raelgc** [comment]
Hi @avogeltanz, I can help you giving you some guidance about this.

Can you send me your email to rael.gc@gmail.com? So I can contact you!

**Comment by avogeltanz** [comment]
@raelgc sent! Thank you for the quick response!
