### ISSUE TITLE
bundler compliance when specifying ruby version in Gemfile

### ISSUE THREAD

**Issue by mathieujobin** [rvm/rvm#3717]
First, thanks for making rvm, it's the best tool to manage ruby version. I use it for many years and recommend it to anyone using or getting into ruby.

I am using this feature where I can specify the ruby version in the Gemfile like:

``` ruby
ruby '2.2.5'
```

both bundler and rvm supports it, so it's awesome. rvm auto switch in development, and bundler enforce it on deployed environments

but when deploying to ubuntu images, without rvm, using ubuntu packages instead (not my choice)
the package 'ruby22' may or may not be the version I think it will.

so bundler actually supports operator as for gems like:

``` ruby
ruby '~> 2.2.4'
```

or `>=`, etc.

so, that fix my problem on deployed environments.
but rvm won't switch anymore when I cd into my project ;(

getting this error

```
$ cd ../project/
Unknown ruby interpreter version (do not know how to handle): ~>2.2.4.
```

**Comment by pkuczynski** [comment]
This sounds like a good idea, but consider following situation: RVM have both 2.2.4 and 2.2.5 installed and you specify in your gemfile `ruby '~> 2.2.4` - which version RVM should default to? Oldest compatible or newest? Bundler only makes sure that current ruby is in a compatible version, but RVM needs to be more specific...

**Comment by mathieujobin** [comment]
I honestly hadn't not thought about this case. you right, I think I would probably print a warning and choose the oldest compatible ones, since it is more likely to be the one that's been working before the latest got installed. once new ruby has all the gems for my apps and I have ran my test, I can delete the old ruby ;)

**Comment by danielpclark** [comment]
My thoughts on

>  which version RVM should default to?

I think if the current default ruby version loaded lies within the rule `ruby '~> 2.2.4'` then use that version.  I'm thinking CI environments choose this beforehand anyways.

Otherwise, in my opinion, prefer the highest patch version since patches include fixes and security related updates.

**Comment by mathieujobin** [comment]
workaround in the mean time...

```
$ rvm alias create '~>2.2.6' ruby-2.2.7                                     
Creating alias ~>2.2.6 for ruby-2.2.7... 
```

**Comment by mathieujobin** [comment]
its bundler that should support simply using `2.4`

so stupid they refused the working patch

**Comment by usmonster** [comment]
Hello! I'm not sure why this was closed? Can it please be reopened, or can you point to another open issue I can follow on the subject? Otherwise I'll just create yet another issue about this... Thanks!

**Comment by mathieujobin** [comment]
if bundler would simply support this https://github.com/bundler/bundler/issues/6327

this would no longer be an issue
in the mean time, rvm aliases is a good workaround

**Comment by usmonster** [comment]
After the discussion on the above referenced ticket (bundler/bundler#633), I'm now more convinced that the improvement should be made in RVM.

> consider following situation: RVM have both 2.2.4 and 2.2.5 installed and you specify in your gemfile `ruby '~> 2.2.4` - which version RVM should default to? Oldest compatible or newest?

The answer proposed in [bundler/bundler#6330](https://github.com/bundler/bundler/pull/6330#issuecomment-441582689) is to use the version specified in the Gemfile.lock instead of the Gemfile.

If there's no Gemfile.lock present, then I'd go with the intuitive behavior that was [previously proposed](https://github.com/rvm/rvm/issues/3717#issuecomment-281157804): use the current ruby if it matches the version specifier, or switch to the latest matching version available, otherwise error.

@mathieujobin, @pkuczynskim would you please consider reopening this? Thanks!

**Comment by pkuczynski** [comment]
@usmonster you are welcome to come up with a PR for this

**Comment by usmonster** [comment]
@pkuczynski, thanks for the swift response! If you confirm that what I describe is acceptable behavior, I can create a new issue describing the feature, and feel free to add a "help wanted" or "good first issue" label. I'd be happy to propose a PR when I get a chance unless someone else would like to do so first.

**Comment by mathieujobin** [comment]
I don't think taking the version in the Gemfile.lock is the right approach since developers are not necessarily on the same version that was last use when the Gemfile.lock was updated.

I see the ruby version specification in the Gemfile has a constraint to ensure the app does not run on a not supported version.

now for deployed environment, its easy to add the auto selection via the deployment script.

probably arise with local setups with developers have multiple rubies installed. have multiple service to work on. some are locked on 2.3, others on 2.4, some developers upgrade their rubies sooner than others. 

I see this feature in rvm as a smarter autoselect within the constraint.
best would be if `rvm` was able to read the actual condition which I believe than be of 3 forms

* `~> 2.x.y`
* `>= 2.x.y`
* `>= 2.x.y, < 2.z`

personally, I have been happy setting up local aliases.
so I am not going to reopen myself.
