### ISSUE TITLE
Warning: openssl is a keg-only and another version is linked to opt

### ISSUE THREAD

**Issue by K1oride** [rvm/rvm#3724]
It shows up almost the same issue in #2318 while the solution does not work for me
`$ rvm use ruby --install --default
ruby-2.3.0 is not installed - installing.
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Somehow it happened there is no executable 'openssl',
run 'brew doctor' and make sure latest '' is installed properly.
RVM autolibs is now configured with mode '4' =>
  'Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X).',
please run`rvm autolibs enable`to let RVM do its job or run and read`rvm autolibs [help]`
or visit https://rvm.io/rvm/autolibs for more information.
Requirements installation failed with status: 12.`

the Command-Line tools is properly installed

**Comment by K1oride** [comment]
After deleting the empty folder under `/usr/local/Cellar/openssl/` and  reinstalling openssl with `brew install openssl`, the problem got solved.

**Comment by tlubz** [comment]
I know this is closed, but I had the same error when installing 2.3.1, and i solved it by issuing a `brew install openssl --force`, which fixed the problem and did not require me to manually delete any brew-managed folders manually.

from my `package_install_openssl.log`:

```
...
command(2): requirements_osx_brew_libs_install openssl
++ brew unlink openssl
Unlinking /usr/local/Cellar/openssl/1.0.2j... 0 symlinks removed
++ brew install openssl
Warning: openssl is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
```

The version that was previously in opt was `1.0.2j`, but it was not a symlink. The new version installed was `1.0.2k`

**Comment by jstray** [comment]
Same problem here on Mac OS 10.11.6. `brew upgrade openssl` fixed it.

**Comment by navjeetc** [comment]
`brew upgrade openssl` fixed the same problem for me also on macOs Sierra

**Comment by anandaroop** [comment]
`brew upgrade openssl` also fixes the problem on Yosemite 10.10.5

**Comment by TheBokiya** [comment]
I can confirm that `brew install openssl --force` fixes the issue on El Capitan.

**Comment by pkuczynski** [comment]
As quite a few people report that enforcing brew to install newer openssl help them to solve the ruby build issue, we will try to provide a solution for it...
