### ISSUE TITLE
bash: line 825: shell_session_update: command not found

### ISSUE THREAD

**Issue by azizur** [rvm/rvm#3725]
When I install rvm using ` \curl -sSL https://get.rvm.io | bash -s stable --ruby`

I am getting the following errors:

`~/.rvm/bin/rvm: line 66: shell_session_update: command not found`
and
`bash: line 825: shell_session_update: command not found`

**Comment by mpapis** [comment]
try `master` instead of stable

**Comment by yakimant** [comment]
@mpapis any forecast on new stable release?
Thank you!
