### ISSUE TITLE
ubuntu unable to install 1.8.6

### ISSUE THREAD

**Issue by dassio** [rvm/rvm#3726]
i am trying to install ruby1.8.6 on ubuntu using rvm 1.27.0 (master) , but aways got the error:

/home/danny/.rvm/src/ruby-1.8.6-p420/lib/shellwords.rb:30:in `shellwords': Argument must be a string (ArgumentError)
	from /home/danny/.rvm/src/ruby-1.8.6-p420/lib/mkmf.rb:25
	from ./ext/extmk.rb:37:in `require'
	from ./ext/extmk.rb:37
make: *** [all] Error 1

**Comment by pkuczynski** [comment]
Which version of ubuntu?

**Comment by raelgc** [comment]
Hi @dassio and thank you for raising this.

Do you mind to try our [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by pkuczynski** [comment]
No feedback. Closing for now. Please reopen when still valid.
