### ISSUE TITLE
求救  安装cocoapods 一直出现这个情况 提示我要大于2.2.2 

### ISSUE THREAD

**Issue by Heavengirl** [rvm/rvm#3727]
ruby-2.2.3 - #installing...........
Error running '__rvm_make install',
showing last 15 lines of /Users/Diana/.rvm/log/1470904362_ruby-2.2.3/install.log
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /Users/Diana/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              minitest-5.4.3.gem
                              power_assert-0.2.2.gem
                              test-unit-3.0.8.gem
./tool/rbinstall.rb:728:in `chmod': Operation not permitted @ chmod_internal - /Users/Diana/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/doc/activesupport-5.0.0/ (Errno::EPERM)
    from ./tool/rbinstall.rb:728:in`block in <main>'
    from ./tool/rbinstall.rb:757:in `call'
    from ./tool/rbinstall.rb:757:in`block in <main>'
    from ./tool/rbinstall.rb:754:in `each'
    from ./tool/rbinstall.rb:754:in`<main>'
make: **\* [do-install-nodoc] Error 1
++ return 2
There has been an error while running make install. Halting the installation

**Comment by pkuczynski** [comment]
Could you please rewrite title of the issue in english?

Could you gist output of following commands:

```
rvm get head
rvm debug
rvm install 2.2.3
```

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
