### ISSUE TITLE
Failed to install ruby with rvm on OSX El Capitan

### ISSUE THREAD

**Issue by madman3** [rvm/rvm#3729]
I'm trying to install the latest version of ruby on my machine running EL Capitan and here's the error I keep getting. Tried different solutions on the web and couldn't resolve it.

 \curl -sSL https://get.rvm.io | bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Upgrading the RVM installation in /Users/Suniltejs/.rvm/
    RVM PATH line found in /Users/Suniltejs/.mkshrc /Users/Suniltejs/.profile /Users/Suniltejs/.bashrc /Users/Suniltejs/.zshrc.
    RVM sourcing line found in /Users/Suniltejs/.profile /Users/Suniltejs/.bash_profile /Users/Suniltejs/.zlogin.
Upgrade of RVM in /Users/Suniltejs/.rvm/ is complete.

# madman3,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.11/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Installing requirements for osx.
Updating system.....
Installing required packages: openssl.......
Error running 'requirements_osx_brew_libs_install openssl',
showing last 15 lines of /Users/Suniltejs/.rvm/log/1471272535_ruby-2.3.0/package_install_openssl.log
++ /scripts/functions/logging : rvm_pretty_print()  81 > case "$1" in
++ /scripts/functions/logging : rvm_pretty_print()  82 > [[ -t 1 ]]
++ /scripts/functions/logging : rvm_pretty_print()  82 > return 1
++ /scripts/functions/logging : rvm_warn()  139 > printf %b 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation\n'
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
++ /scripts/functions/requirements/osx_brew : requirements_osx_brew_libs_install()  63 > case "$_system_version" in
++ /scripts/functions/requirements/osx_brew : requirements_osx_brew_libs_install()  70 > return 1
Requirements installation failed with status: 1.

**Comment by pkuczynski** [comment]
We just uploaded 2.3.1 binaries for OSX El Capitan.

```
rvm get master
rvm install 2.3.1
```

should solve your problem.

**Comment by mhmenon910** [comment]
@madman3  How did you solved this issue ?  Iam having same problem in MAC OSX El captain , i have even tried following way as per @pkuczynski , bt no luck!
rvm get master
rvm install 2.3.1

It would be helpful if anybody can point me solution to this.
Thanks

**Comment by madman3** [comment]
@pkuczynski I basically installed an older version as a clean install from
the scratch again. Maybe that could help.
