### ISSUE TITLE
Installing RVM issue

### ISSUE THREAD

**Issue by andydickens** [rvm/rvm#3730]
I have never done this before and it is my first time with Linux. This is the stuff I typed into the shell and the stuff it spat back out. I looked at a previous thread where a user had my issue, but he did not start his own ticket.

[what I typed in first] gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

[what i typed in second] gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

[what I typed in third] curl -sSL https://rvm.io/mpapis.asc | gpg --import -
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

**Comment by raelgc** [comment]
Hi @andydickens and thank you for reporting this issue.

Which Linux distribution and version are you using?

**Comment by andydickens** [comment]
@raelgc Ubuntu 16.04.1 LTS  I think it is this one. That is what it said when I downloaded it.

**Comment by raelgc** [comment]
Thanks for the feedback, @andydickens!

Can you, please, try our [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm) instructions?

**Comment by raelgc** [comment]
@andydickens, any results? :)

**Comment by andydickens** [comment]
@raelgc before I could try my Windows crashed separately and broke. It looped a forced restart thing for hours. When I can fix that and reinstall linux I'm going to try again. :(

**Comment by pkuczynski** [comment]
@andydickens any more feedback? otherwise we would have to close this issue...

**Comment by andydickens** [comment]
Oh sorry I forgot about this. Just close it. My roommate broke my laptop and I've been arguing with him for weeks about how to replace it. So I don't even have access to my Linux. So I hadn't thought about this in a while.
