### ISSUE TITLE
ruby 2.3.1 (MRI) is not "known" by `rvm get stable`

### ISSUE THREAD

**Issue by mattscilipoti** [rvm/rvm#3732]
When I list known versions, via `rvm list known` it indicates that 2.3.0 is the latest release.  2.3.1 was released on 04/26/2016.  Is there a reason for this oversight?

The (annotated) output:
```
$ rvm list known
# MRI Rubies
[ruby-]1.8.6[-p420]
...
[ruby-]2.2[.4]
[ruby-]2.3[.0]
[ruby-]2.2-head
ruby-head
...
```

I'll start researching how to update this and how to contribute an OSX binary.

**Comment by mattscilipoti** [comment]
Note: this was performed using `rvm get latest`.  
```
$ rvm --version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

**Comment by mattscilipoti** [comment]
https://rvm.io/rvm/upgrading indicates that `rvm get latest` has been repaced by `rvm get stable`.  That leaves me at `rvm 1.27.0`.

**Comment by mattscilipoti** [comment]
More findings: config/known, on master branch, indicates `[ruby-]2.3[.1]`.  It was added on Apr 28, 2016 via https://github.com/rvm/rvm/commit/2f8549f30991e55a198d5be86d1800f646268528#diff-278dcece756e75611dd08c63d01cc4b2.

Maybe "stable" hasn't been updated for a while?

**Comment by mattscilipoti** [comment]
Confirmed: Last commit to "stable" was March 29, 2016: https://github.com/rvm/rvm/tree/stable

I'm not sure what the release process is.  Is there a reason for not pushing to "stable"?  Is there anything I can do to help?

**Comment by pkuczynski** [comment]
Run 

```
rvm get master
rvm install ruby-2.2.3
```

and this will solve your problem. We are working on getting current RVM master to stable, but it needs some extra time...
