### ISSUE TITLE
Clang error when trying to run an old Ruby version

### ISSUE THREAD

**Issue by CodeBlackwell** [rvm/rvm#3733]
I'm not sure if this is an rvm but I figured I would start here. I am seeing errors when trying to setup a database on an old version of Ruby/Rails. Appears to be attempting some sort of compilation with Ruby inline. Here is the stack trace.

```
clang: error: optimization flag '-fno-tree-dce' is not supported
rake aborted!
error executing "cc -dynamic -bundle -undefined suppress -flat_namespace -Werror   -fno-common -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl/include -O2 -fno-tree-dce -fno-optimize-sibling-calls  -fno-common -pipe -fno-common   -I /Users/tonywinglau/.rvm/rubies/ruby-1.8.7-head/lib/ruby/1.8/i686-darwin15.5.0  -I /Users/tonywinglau/.rvm/rubies/ruby-1.8.7-head/include -L/Users/tonywinglau/.rvm/rubies/ruby-1.8.7-head/lib -o \"/Users/tonywinglau/.ruby_inline/Inline_RawParseTree_ab80.bundle\" \"/Users/tonywinglau/.ruby_inline/Inline_RawParseTree_ab80.c\"  ": 256
Renamed /Users/tonywinglau/.ruby_inline/Inline_RawParseTree_ab80.c to /Users/tonywinglau/.ruby_inline/Inline_RawParseTree_ab80.c.bad
```
Here is the project I am trying to work on https://github.com/CodeBlackwell/better .

I was able to install Ruby 1.8.7 fine with rvm, this is when running with db:setup.

**Comment by Viperey** [comment]
Got this very same problem.
OS X 10.12

```
> clang --version
Apple LLVM version 8.0.0 (clang-800.0.42)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by Viperey** [comment]
Solved it temporally by adding the following line:

```
          Config::CONFIG['CFLAGS'].slice! "-fno-tree-dce"
```
to the lib/inline.rb file just **before** this line (~ line 600, depends on the version):

```
cmd = [ Config::CONFIG['LDSHARED'],
```

**Comment by pkuczynski** [comment]
Is there any reason why you would use such old version of Ruby?

**Comment by Viperey** [comment]
A logical reason? No. Just a business decision.

**Comment by pkuczynski** [comment]
https://www.ruby-lang.org/en/downloads/

* Stable releases: 2.3.1, 2.2.5
* In security maintenance phase (will EOL soon!): 2.1.10
* Not maintained anymore (EOL): 2.0.0-p648

1.8.7 is well outdated and not supported by anyone. Maybe you should consider upgrade or elaborate more on reasoning if you want us to put an effort in patching...

**Comment by pkuczynski** [comment]
By the way, PR are always welcome...

**Comment by mockdeep** [comment]
In order to work on older projects we don't have the option of simply upgrading ruby versions immediately. The above linked project is an example, in order to bring it up to date we first need to be able to install the older version of ruby and ensure that we're keeping things working as we test and upgrade.

**Comment by pkuczynski** [comment]
@Viperey which file exactly you modified? I don't see a `lib/inline.rb` in Ruby 1.8.7 sources...

**Comment by Viperey** [comment]
@pkuczynski my bad. The change is in the ParseTree library.
In deed, the error doesn't seem to be related with rvm, so I guess this issue should be closed.

**Comment by Viperey** [comment]
I forgot to mention...
Thanks for the support!
;)
