### ISSUE TITLE
Support ruby version operators in a Gemfile `ruby` restriction

### ISSUE THREAD

**Issue by darrenleeweber** [rvm/rvm#3737]
We have an app with a Gemfile that contains `ruby '~> 2.3.0'` and we have an rvm version installed that should be compatible with that, i.e. 

```
$ rvm --version
rvm 1.26.10 (1.26.10) ...
$ rvm list
=* ruby-2.3.1 [ x86_64 ]
```

When running various bundle commands for this app, there is a warning that might be coming from `rvm`, like

```
rake stderr: Unknown ruby interpreter version (do not know how to handle): ~>2.3.0.
```

Can `rvm` support the bundle version operators?
- see http://bundler.io/gemfile_ruby.html
  - ruby versions can be specified using version operators
    
    ```
    Version operators for specifying a Ruby version are also available.
    The set of supported version operators is that of Rubygems (gem version operators).
    (ie. <, >, <=, >=, ~>, =)
    ```

**Comment by ericcj** [comment]
apparently there's not an obvious fix https://github.com/rvm/rvm/issues/3717 but i worked around this by adding the specifc version in the comment variant, e.g. #ruby=2.3.1 from https://rvm.io/workflow/projects#project-file-gemfile

**Comment by mpapis** [comment]
RVM 1.x can not support pessimistic version matching, it would require having ruby installed or other third party library. As @ericcj mentioned use the comment version - it has higher priority. Pessimistic version matching most likely will be supported in RVM 2.x.

**Comment by coezbek** [comment]
Just a question if some very limited support could be added for the "~>" operator, by truncating the listed Ruby version.

The following for instance indicates that the author of the Gemfile intended this project to work with 2.7.0 and any TEENY version updates such as 2.7.1:

`ruby "~>2.7.0" `

In RVM, I believe this would be expressed by stating:

`rvm use 2.7`

Couldn't RVM pattern match this?

For instance put below the other pattern substitutions for the Gemfile ruby string:

For instance assuming that $rvm_ruby_string is `'~>2.7.1'`

```
pattern="~>([[:digit:]]\.[[:digit:]])\.[[:digit:]]+"
[[ $rvm_ruby_string =~ $pattern ]] && \
    rvm_ruby_string="${BASH_REMATCH[1]}"

echo $rvm_ruby_string

```
Should return 2.7
