### ISSUE TITLE
Ruby Enterprise Edition Installs 404ing

### ISSUE THREAD

**Issue by mmarod** [rvm/rvm#3740]
It appears that all of the ree sources are down except for https://code.google.com/archive/p/rubyenterpriseedition/downloads which is not one of the mirrors used by rvm. The link found on http://www.rubyenterpriseedition.com/download.html is 404'ing as well as the other main mirrors. I have been experiencing this since last Friday.

Here is the output of when I try to rvm install.

```
$ rvm install ree-1.8.7-2012.02
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/14.04/x86_64/ree-1.8.7-2012.02.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Installing Ruby Enterprise Edition from source to: /home/shareposts/.rvm/rubies/ree-1.8.7-2012.02
ree-1.8.7-2012.02 - #fetching (ruby-enterprise-1.8.7-2012.02)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
The requested url does not exist(22): 'https://rubyenterpriseedition.googlecode.com/files/ruby-enterprise-1.8.7-2012.02.tar.gz'
Checking fallback: ftp://rubyenterpriseedition.googlecode.com/files/ruby-enterprise-1.8.7-2012.02.tar.gz
Checking fallback: https://www.mirrorservice.org/sites/rubyenterpriseedition.googlecode.com/files/ruby-enterprise-1.8.7-2012.02.tar.gz
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error while trying to fetch the source. 
Halting the installation.
```

I'm not sure if this is an rvm issue where rvm needs to update its mirrors or if it is an issue with the mirrors themselves.

**Comment by brpocock** [comment]
+1. just adding a note that I'm seeing this, as well.

**Comment by wli6** [comment]
the ree file changed,

 you can update the link in the config/db

https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rubyenterpriseedition/ruby-enterprise-1.8.7-2012.02.tar.gz

**Comment by wli6** [comment]
change 
ree_1.8.7_url=https://rubyenterpriseedition.googlecode.com/files
to 
ree_1.8.7_url=https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/rubyenterpriseedition as well

**Comment by havenwood** [comment]
@wli6 I'll update the other URL as well. Thanks for the info!
