### ISSUE TITLE
Errors when install rubies

### ISSUE THREAD

**Issue by eailfly** [rvm/rvm#3742]
When I install rubies use `rvm install`, in the last , I got this error message:

```
Error running 'env GEM_HOME=/home/eailfly/.rvm/gems/ruby-2.3-head@global GEM_PATH= /home/eailfly/.rvm/rubies/ruby-2.3-head/bin/ruby -d /home/eailfly/.rvm/src/rubygems-6599b57abdc8f78a5e24de4ef946aeb2914ccec4/setup.rb --no-document',
showing last 15 lines of /home/eailfly/.rvm/log/1472786696_ruby-2.3-head/rubygems.install.log
Exception `LoadError' at /home/eailfly/.rvm/rubies/ruby-2.3-head/lib/ruby/2.3.0/rubygems.rb:1241 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/eailfly/.rvm/rubies/ruby-2.3-head/lib/ruby/2.3.0/rubygems.rb:1250 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /home/eailfly/.rvm/rubies/ruby-2.3-head/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- did_you_mean
Exception `LoadError' at /home/eailfly/.rvm/rubies/ruby-2.3-head/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- did_you_mean
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - bundler/lib
```

And `rvm list` shows the rubies is installed, just when `rvm use`, it's show this message:
`Gemset '' does not exist, 'rvm ruby-2.3-head do rvm gemset create ' first, or append '--create'.`
What's happening here?

**Comment by Dorian** [comment]
Same here with `ruby-head`

**Comment by pkuczynski** [comment]
Could you both gist your `rubygems.install.log`?

**Comment by Dorian** [comment]
Sure: https://gist.github.com/62093f904633dabbf0f3e027436ffc05

BTW, I did `rvm reinstall ruby-head --rubygems ignore` and it worked

**Comment by eailfly** [comment]
Sorry, I reinstall my OS, so the issue is gone. Let's focus on @Dorian 's problem

**Comment by Dorian** [comment]
@pkuczynski FYI `rvm reinstall ruby-head --rubygems 2.6.8` just worked fine

**Comment by cgorshing** [comment]
Google led me here. You might have others visit here for the same reason. I got this error as well running `rvm install 2.2-head --disable-binary` (I was having some openssl errors prior that I'm trying to get around, this is the reason for the --disable-binary). 

rubygems.install.log -> https://gist.github.com/cgorshing/32eff6e6afcc0c1b573e6e0f2a4be4b5

`rvm reinstall 2.2-head --disable-binary --rubygems 2.6.8` worked for me as well.

**Comment by benhoxie** [comment]
Same here from goole and updating ruby gems and running that line worked. Thanks for commenting @cgorshing .

**Comment by pkuczynski** [comment]
I just upgraded rubygems in RVM to version 2.6.8, which should solve this issue. If someone is still experiencing it, please try with `rvm get head`

**Comment by albertnetymk** [comment]
`rvm get head` gets me rubygem 2.6.11, but `rvm reinstall ruby-head` still fails for me.

`rvm reinstall ruby-head --rubygems 2.6.11` works, though.

**Comment by docwhat** [comment]
- Ubuntu 17.04
- rvm 1.29.2
- pre-installed ruby-2:
    - version 2.4.0
    - rubygems: 2.6.12

When installing `ruby-head` I get the same error.  Using the `--rubygems 2.6.12` flag works.

Is this an RVM issue or a Ruby issue?
