### ISSUE TITLE
command failed core_ext/kernel_require:rb:55 in 'require':cannot be load such file --compass (LoadError)

### ISSUE THREAD

**Issue by shakyakrishna** [rvm/rvm#3743]
My ruby was working completely fine .. and compass gems was working perfectly until i upgraded my ruby version from 1.9.1 to 2.3.1 and i blow up everything...I have very few knowledge about ruby could any one help me how to solve these problem..will appreciate it much been stuck from more than two days
![selection_006](https://cloud.githubusercontent.com/assets/7625677/18195164/79b92e36-712d-11e6-8ea3-f2addc07127b.png)
![selection_008](https://cloud.githubusercontent.com/assets/7625677/18195165/79bbc2c2-712d-11e6-9686-5c7486d20e26.png)

![selection_009](https://cloud.githubusercontent.com/assets/7625677/18195245/a0dc5ed4-712d-11e6-8fd5-fe0ce279944d.png)

P.s.-I have tried several solution from internet but none seems to be helping.. I have install ruby with rvm and also there is no any folder .rvm in my home folder after curl execution during installation which is weird.

**Comment by pkuczynski** [comment]
What kind of os and zsh do you use?

**Comment by shakyakrishna** [comment]
os-ubuntu/nix
zsh-ohmyzsh

**Comment by mpapis** [comment]
Is this still a problem, can you check `echo $rvm_path`?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
