### ISSUE TITLE
rvm: ubuntu default bash config destination

### ISSUE THREAD

**Issue by ghost** [rvm/rvm#3747]
Hi, when first installed Ruby on RVM, the ruby command is not detected. It founds that the `source ~/.rvm/scripts/rvm` is found in the ~/.bash_profile. However, for Ubuntu linux (afaik), use
 .profile -o- .bashrc as their goto bash config. So, I suggest to add platform flag when install rvm, so it knows which platform it will be installed, and puts every configs where it's supposed to do.

**Comment by raelgc** [comment]
Hi @itsabear and thank you for reporting this.

Probaby you can try our [dedicated Ubuntu package](https://github.com/rvm/ubuntu_rvm): it solves a lot of common configuration problems.

**Comment by itsabear** [comment]
@raelgc Thanks. I never knew that package is available before.

**Comment by raelgc** [comment]
@itsabear Indeed, maybe we should mention this package in the install page.

**Comment by itsabear** [comment]
@raelgc that is a great idea.

**Comment by pkuczynski** [comment]
Added ubuntu package to the readme and created a ticket to add to rvm.io https://github.com/rvm/rvm-site/issues/295#

**Comment by pkuczynski** [comment]
Added on rvm.io with following PR: https://github.com/rvm/rvm-site/pull/306
