### ISSUE TITLE
Error running __rvm_make -j4

### ISSUE THREAD

**Issue by Pierre-Staszak** [rvm/rvm#3748]
Hello,

I try to install ruby 2.1.0 using rvm install, but I keep having this error during the compilation process

Error running '__rvm_make -j4',
showing last 15 lines of /home/stasza_p/.rvm/log/1473143941_ruby-2.1.0/make.log
constdefs.c:1715:50: note : in expansion of macro ‘INTEGER2NUM’
     rb_define_const(rb_mSockConst, "EAI_SYSTEM", INTEGER2NUM(EAI_SYSTEM));
                                                                                 ^~~~~~~~~~~
make[2] : on quitte le répertoire « /home/stasza_p/.rvm/src/ruby-2.1.0/ext/openssl »
make[1]: *** [exts.mk:187: ext/openssl/all] Error 2
make[1]: *** Attente des tâches non terminées....
linking shared-object strscan.so
make[2] : on quitte le répertoire « /home/stasza_p/.rvm/src/ruby-2.1.0/ext/strscan »
linking shared-object socket.so
make[2] : on quitte le répertoire « /home/stasza_p/.rvm/src/ruby-2.1.0/ext/socket »
linking shared-object ripper.so
make[2] : on quitte le répertoire « /home/stasza_p/.rvm/src/ruby-2.1.0/ext/ripper »
make[1] : on quitte le répertoire « /home/stasza_p/.rvm/src/ruby-2.1.0 »
make: *** [uncommon.mk:180: build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.

Can you help me to fix this madness ? Thanks

**Comment by pkuczynski** [comment]
Can you try please with latest RVM:

```
rvm get master
rvm install ruby-2.1.0
```

**Comment by sylvainbx** [comment]
I had the exact same issue when installing ruby-2.1.2 on ArchLinux. I tried to update rvm as you suggested but this doesn't solved the problem.

**Comment by pkuczynski** [comment]
Solution mentioned by @sylvainbx fixed this issue, as well as #3752, so I will include this patch in RVM...

**Comment by pkuczynski** [comment]
@sylvainbx I prepared a patch. Would you find some time to test it?

```
rvm get branch /bugfix/issue-3748
rvm install x.x.x
```

where `x.x.x` is a version of your choice earlier than 2.3.0

**Comment by pkuczynski** [comment]
@Pierre-Staszak maybe you could have a look too?

**Comment by Pierre-Staszak** [comment]
@sylvainbx @pkuczynski Thanks ! I will try it today and tell if it works

**Comment by sylvainbx** [comment]
Ok I've just tried as you suggested and installed ruby 2.1.0 and everything was fine during the install. Ruby 2.1.0 now run flawlessly. Thanks for the fix !

**Comment by pkuczynski** [comment]
Fixed in master. You can switch back `rvm get master`
