### ISSUE TITLE
Error running '__rvm_make -j8'

### ISSUE THREAD

**Issue by AkechiShiro** [rvm/rvm#3752]
I have this Error when running `rvm install 1.9.3` or `rvm install 2.1.5` here's my complete output for `rvm install 2.1.5`

Here is my [make.log](https://gist.github.com/AkechiShiro/88e45242f8660ce41dad7997af1b69d7)

Error running '__rvm_make -j8',
showing last 15 lines of /home/akechi/.rvm/log/1473625068_ruby-2.1.5/make.log
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5/ext/stringio'
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5/ext/dl/callback'
linking shared-object strscan.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5/ext/strscan'
linking shared-object thread.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5/ext/thread'
linking shared-object socket.so
linking shared-object nkf.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5/ext/nkf'
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5/ext/socket'
linking shared-object ripper.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5/ext/ripper'
make[1]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.5'
make: **\* [uncommon.mk:180: build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.

I'd like to note that I'm on ArchLinux since I searched with no luck before opening this issue.

**Comment by pkuczynski** [comment]
Can you try please with latest RVM:

```
rvm get master
rvm install ruby-2.1.0
```

**Comment by AkechiShiro** [comment]
Alright I tried what I asked got the master then `rvm install ruby-2.1.0` I got the same output, same error here it is and here is the specific [make.log](https://gist.github.com/AkechiShiro/564563346d2d17982c69faac03add377)
ruby-2.1.0 - #removing src/ruby-2.1.0..
Searching for binary rubies, this might take some time.
No binary rubies available for: arch/libc-2.24/x86_64/ruby-2.1.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for arch.
Requirements installation successful.
Installing Ruby from source to: /home/akechi/.rvm/rubies/ruby-2.1.0, this may take a while depending on your cpu(s)...
ruby-2.1.0 - #downloading ruby-2.1.0, this may take a while depending on your connection...
ruby-2.1.0 - #extracting ruby-2.1.0 to /home/akechi/.rvm/src/ruby-2.1.0....
ruby-2.1.0 - #applying patch /home/akechi/.rvm/patches/ruby/2.1.0/changeset_r44327.diff.
ruby-2.1.0 - #applying patch /home/akechi/.rvm/patches/ruby/2.1.0/libyaml.patch.
ruby-2.1.0 - #applying patch /home/akechi/.rvm/patches/ruby/GH-488.patch.
ruby-2.1.0 - #applying patch /home/akechi/.rvm/patches/ruby/changeset_r45225.diff.
ruby-2.1.0 - #applying patch /home/akechi/.rvm/patches/ruby/changeset_r45240.diff.
ruby-2.1.0 - #configuring....................................................
ruby-2.1.0 - #post-configuration..
ruby-2.1.0 - #compiling..............................................................-
Error running '__rvm_make -j8',
showing last 15 lines of /home/akechi/.rvm/log/1473964197_ruby-2.1.0/make.log
linking shared-object dl/callback.so
linking shared-object strscan.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.0/ext/strscan'
linking shared-object stringio.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.0/ext/stringio'
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.0/ext/dl/callback'
linking shared-object socket.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.0/ext/socket'
linking shared-object nkf.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.0/ext/nkf'
linking shared-object ripper.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.0/ext/ripper'
make[1]: Leaving directory '/home/akechi/.rvm/src/ruby-2.1.0'
make: *** [uncommon.mk:180: build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.

**Comment by AkechiShiro** [comment]
Also I have to specify I installed successfully before the doing `rvm get master` ruby 2.0.0 and it's working but 1.9.3, 2.1.0 or 2.1.5 gives me that error about my 8 cpu's threads so I don't really know what is going on !
Thanks for the provided help so far !

**Comment by pkuczynski** [comment]
Did you tried solution mentioned in #3748?

**Comment by AkechiShiro** [comment]
It works flawlessly thank you very much !

**Comment by pkuczynski** [comment]
@AkechiShiro I prepared a patch. Would you find some time to test it?

```
rvm get branch /bugfix/issue-3748
rvm install x.x.x
```

where `x.x.x` is a version of your choice earlier than 2.3.0

**Comment by AkechiShiro** [comment]
Here is my output with the rvm from the bugfix
`ruby-2.1.5 - #extracting ruby-2.1.5 to /home/akechi/.rvm/src/ruby-2.1.5....`
`Patch 'openssl3' not found.`
`There has been an error applying the specified patches. Halting the installation.`

**Comment by AkechiShiro** [comment]
There is also a different output with ruby 1.9.3 which was the same as before
Error running '__rvm_make -j8',
showing last 15 lines of /home/akechi/.rvm/log/1477311399_ruby-1.9.3-p551/make.log
             ^~~~~~~~~~
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-1.9.3-p551/ext/sdbm'
linking shared-object stringio.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-1.9.3-p551/ext/stringio'
linking shared-object socket.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-1.9.3-p551/ext/socket'
linking shared-object nkf.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-1.9.3-p551/ext/nkf'
linking shared-object dl/callback.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-1.9.3-p551/ext/dl/callback'
linking shared-object ripper.so
make[2]: Leaving directory '/home/akechi/.rvm/src/ruby-1.9.3-p551/ext/ripper'
make[1]: Leaving directory '/home/akechi/.rvm/src/ruby-1.9.3-p551'
make: *** [uncommon.mk:178: build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.

**Comment by pkuczynski** [comment]
I added openssl3 patch to all rubies 2.1.x now. Please retry with `2.1.5`

**Comment by pkuczynski** [comment]
Can you also check if you have active-tcl8.6 installed? Looking at your previous make.log it was also causing some trouble...

**Comment by AkechiShiro** [comment]
You're talking about this package [tcl](https://www.archlinux.org/packages/extra/x86_64/tcl/) I have it installed and updated.
warning: tcl-8.6.6-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) tcl-8.6.6-1

**Comment by pkuczynski** [comment]
I will wait for your make.log and advice you more afterwards.

**Comment by AkechiShiro** [comment]
Here is the [make.log](https://gist.github.com/AkechiShiro/52158f933ca20d73c2dcf591bb6ce33d) for the installation of ruby 1.9.3 as for this error concerning ruby 2.1.5
Installing Ruby from source to: /home/akechi/.rvm/rubies/ruby-2.1.5, this may take a while depending on your cpu(s)...
ruby-2.1.5 - #downloading ruby-2.1.5, this may take a while depending on your connection...
ruby-2.1.5 - #extracting ruby-2.1.5 to /home/akechi/.rvm/src/ruby-2.1.5....
Patch 'openssl3' not found.
There has been an error applying the specified patches. Halting the installation.

**Comment by pkuczynski** [comment]
I just checked and openssl3 is found for 2.1.5 after getting latest version from this branch. Are you sure you run:

```
rvm get branch /bugfix/issue-3748
rvm remove 2.1.5
rvm install 2.1.5
```

You should see following output (first line would be different it you using other platform then OS X):

```
Checking requirements for osx_brew.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/pkuczynski/.rvm/rubies/ruby-2.1.5, this may take a while depending on your cpu(s)...
ruby-2.1.5 - #downloading ruby-2.1.5, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.4M  100 11.4M    0     0  2756k      0  0:00:04  0:00:04 --:--:-- 2757k
ruby-2.1.5 - #extracting ruby-2.1.5 to /Users/pkuczynski/.rvm/src/ruby-2.1.5....
ruby-2.1.5 - #applying patch /Users/pkuczynski/.rvm/patches/ruby/2.1.5/openssl3.patch.
...
```

Applying the openssl patch is crucial important. Otherwise it won't work.

**Comment by AkechiShiro** [comment]
It works it's a bit weird the first time I had the bugfixed version of rvm and tried and the patch was not found this time it worked thanks now there is just the 1.9.3 that I can't seem to install thanks for the support so far.

**Comment by pkuczynski** [comment]
So you can install 2.1.5. That's great!

To get support with 1.9.3 please gist fresh output of:

```
rvm debug
rvm --trace install 1.9.3 --disable-binary
````

**Comment by AkechiShiro** [comment]
Here it is [Output](https://gist.github.com/AkechiShiro/f1ae4e5690627459374400fbf09a0757)

**Comment by pkuczynski** [comment]
Get latest version from branch and try again. Should work now for 1.9.3 too :)
