### ISSUE TITLE
the global gemset in rvm

### ISSUE THREAD

**Issue by BardiaAfshin** [rvm/rvm#3755]
Is there any significance to this gemset in rvm? Can one just delete all gems in global, or the global gemset all together and rvm will function as expected for other gemsets?

**Comment by mpapis** [comment]
@global gemset in most cases will be linked with rubys default gems location, if you delete the gems by calling `gem uninstall ...` then only gems that were additionally installed can be removed, gems that were provided with ruby can not be removed because of their configuration.
