### ISSUE TITLE
rvm 1.27.0: attempting to ignore warnings for all files results in error (__rvmrc_full_path_to_file)

### ISSUE THREAD

**Issue by shotgundebugging** [rvm/rvm#3758]
After I `cd` into the directory of a Rails projects, I get the following warning:

> RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
> you can ignore these warnings with 'rvm rvmrc warning ignore /path/to/my/project'.
> To ignore the warning for all files run 'rvm rvmrc warning ignore all Gemfiles'.

After attempting `rvm rvmrc warning ignore all Gemfiles`, I get:

> Do not know how to handle 'all/Gemfiles', please report: https://bit.ly/rvm-issues ~ __rvmrc_full_path_to_file

`--debug` output:

> Do not know how to handle 'all/Gemfiles', please report: https://bit.ly/rvm-issues ~  __rvmrc_full_path_to_file
>__rvm_rm_rf already gone: /path/to/.rvm/tmp/1237*

**Comment by pkuczynski** [comment]
Can you try with latest RVM

`rvm get master`

**Comment by shotgundebugging** [comment]
Alright, it's fixed. Thanks!

What commit fixed it?

**Comment by pkuczynski** [comment]
Unfortunately I don't know, but its good that it had been fixed :)
