### ISSUE TITLE
rvm-installer fails installation when cygwin was installed with `--no-admin` flag

### ISSUE THREAD

**Issue by bertramn** [rvm/rvm#3762]
Would it be possible to add a "raw flags" option or like to rvm-installer? Running the following will just open a cygwin installer window error that this program is not allowed by administrators (in our case a windows group policy setting).

```sh
curl -sSL https://get.rvm.io | bash -s stable --ruby
```

The RVM installer needs to execute cygwin setup as below which atm is just missing the `-no-admin` flag:

```sh
setup-x86_64.exe --no-admin
```

**Comment by pkuczynski** [comment]
I could add this fairly easily, but wouldn't it break other people who have admin rights and wan't to run Cygwin this way?

**Comment by pkuczynski** [comment]
So I checked and I can fairly easily detect if Cygwin has been run with admin privileges:

```
  net session > /dev/null 2>&1
  if [ $? -eq 0 ];
  then __noadmin=""
  else __noadmin="--no-admin"
  fi
```

However I am not a Windows user, so not sure how much would that affect users who run as admins and do not need to append --no-admin switch.

Anybody keen to test that?

**Comment by bertramn** [comment]
Hmm not sure if net session gives a clue as to how the cygwin home was installed. This is what the command yields on a cygwin terminal on a no-admin install:

```sh
$ net session
System error 5 has occurred.

Access is denied.
```
I think this switch needs to be set manually somehow so that users with a non-admin installation can toggle it.

**Comment by pkuczynski** [comment]
Yes, it will give you this error - thats how we recognize if you are an admin. But when you run full set of commands below, it will display nice graceful message:

```
net session > /dev/null 2>&1
  if [ $? -eq 0 ];
  then echo "admin"
  else echo "not admin"
  fi
```

I will prepare test version for you tonight if you willing to test? I have limited ability to do it myself :(

**Comment by pkuczynski** [comment]
Can you try

```
rvm get branch /feature/no-admin
```

and let me know if it works?

**Comment by bertramn** [comment]
I updated rvm to the branch and then tried `rvm --debug install ruby-2.2.5` with success. My test setup was Windows 7 x64 with a unpriviledged user account and cygwin installed using the `--no-admin` flag under that users account. Thanks for the effort!

**Comment by pkuczynski** [comment]
Great! So I merged this change to master. Get the latest rvm and enjoy:

```
rvm get master
```

**Comment by bertramn** [comment]
Thanks a million for the quick turn around.

**Comment by pkuczynski** [comment]
You welcome! :)
