### ISSUE TITLE
rvm install failure on Mac 10.11.6; miniruby built for Mac OS X 10.12

### ISSUE THREAD

**Issue by shlifs** [rvm/rvm#3764]
Trying to install the latest stable RVM version on Mac OS X 10.11.6 &mdash;`rmv install 2.3.1` &mdash; fails with "Error running '__rvm_make -j 1'". and the following error:
`dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/sharonl/.rvm/src/ruby-2.3.1/./miniruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib`
The same is true for Ruby v2.3.0 and v2.2.5.

**Comment by HangingClowns** [comment]
same problem. please help!

**Comment by Adales** [comment]
xcode-select --install

I had installed, but reinstalling helped to get exactly this error.

**Comment by pkuczynski** [comment]
@shlifs let us know if reinstalling Xcode helped?

**Comment by shlifs** [comment]
@Adales @pkuczynski Indeed, reinstalling Xcode (`xcode-select --install`) resolved the rvm Ruby installation problem. (It's weird though, because I only installed Xcode ~2 days ago.) Thanks for the super quick response Adales!

**Comment by pkuczynski** [comment]
Good to hear that! :)
