### ISSUE TITLE
initialize problems with zsh and 1.27.0 (master) 

### ISSUE THREAD

**Issue by Patterner** [rvm/rvm#3766]
1> source .rvm/scripts/rvm

.rvm/scripts/initialize:48: __rvm_cleanse_variables: function definition file not found
.rvm/scripts/initialize:50: command not found: rvm_error

zsh 5.2, debian stretch

**Comment by pkuczynski** [comment]
Did you tried simply restarting terminal?

**Comment by Patterner** [comment]
Yes, multiple times. still happening.
