### ISSUE TITLE
rvm remove does not remove ruby completely

### ISSUE THREAD

**Issue by AntonTrapp** [rvm/rvm#3772]
## Description

``` bash
rvm remove 2.2.1 && rvm reload && rvm list
```

still shows the removed version with `2.2.1 [ missing bin/ruby ]`
## Environment info
- RVM version: 1.27.0
- Operating System: OS X
- Version/Release: 10.11.6 El Capitan
- Shell: iTerm2 / Termial / bash
## Expected behavior

The removed version is removed and does not show any more ;)
## Actual behavior

The removed version is removed but still listed
## Steps to reproduce
1. Install a ruby version
2. Remove it
3. List rubies

**Comment by pkuczynski** [comment]
Can u please post output of `rvm list`?

**Comment by AntonTrapp** [comment]
Sure.

rvm list:

```
rvm rubies

   ruby-2.1.2 [ x86_64 ]
   ruby-2.2.1 [ missing bin/ruby ]
   ruby-2.3.0 [ x86_64 ]

# Default ruby not set. Try 'rvm alias create default <ruby>'.

# => - current
# =* - current && default
#  * - default
```

rvm remove 2.2.1:
```
ruby-2.2.1 - #removing rubies/ruby-2.2.1.........................................
```

rvm reload:
```
RVM reloaded!
```

... can be repeated from the rvm list above :)

**Comment by pkuczynski** [comment]
Could you please gist also:

`ls ~/.rvm/rubies/ruby-2.2.1/`
`rvm --trace remove 2.2.1`

**Comment by AntonTrapp** [comment]
```
ls ~/.rvm/rubies/ruby-2.2.1/
lib/
```

`rvm --trace remove 2.2.1` generated a long error file, dug into it and found some permission denied problems (claide, cocoapods-* and flourflusher) in the 2.2.1 lib directory. removed that as root and the 2.2.1 was gone :)

No idea why... unless you have an idea and want to investigate I would close this case as pretty-sure-not-reproducable and thank you for your support!

**Comment by pkuczynski** [comment]
We have a check if removing files failed. Not sure why it did not worked, but I think we can close it as this seems to be the edge case

**Comment by ak15** [comment]
> ```
> ls ~/.rvm/rubies/ruby-2.2.1/
> lib/
> ```
> 
> 
> `rvm --trace remove 2.2.1` generated a long error file, dug into it and found some permission denied problems (claide, cocoapods-* and flourflusher) in the 2.2.1 lib directory. removed that as root and the 2.2.1 was gone :)
> 
> 
> No idea why... unless you have an idea and want to investigate I would close this case as pretty-sure-not-reproducable and thank you for your support!

Same, Had to remove ruby version 2.3.1 as root
OS - macOS Catalina v. 10.15.2
