### ISSUE TITLE
Can't Install rubies on Linux mint rafaela

### ISSUE THREAD

**Issue by kkoci** [rvm/rvm#3775]
## Environment info
- RVM version: 1.27.0
- Operating System: Linux mint Rafaela (Ubuntu 14.04)
- Version/Release: Rafaela
- Shell: bash
## Expected behavior

Install rubies
## Actual behavior

Can't install due to openssl issue
## Steps to reproduce
1. rvm install ruby-x.x.x

Hi, since some days ago I can't install ANY ruby version from rvm, this is roughly what I could find on my make.log:

> linking shared-object objspace.so
> make[2]: Leaving directory `/usr/share/rvm/src/ruby-2.3.1/ext/objspace'
> make[2]: Entering directory`/usr/share/rvm/src/ruby-2.3.1/ext/openssl'
> compiling ossl_pkey_ec.c
> In file included from ossl.h:57:0,
>                  from ossl_pkey_ec.c:5:
> /usr/local/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
>  #error "This file is obsolete; please update your software."
>   ^
> In file included from ossl.h:221:0,
>                  from ossl_pkey_ec.c:5:
> openssl_missing.h:78:35: error: macro "EVP_MD_CTX_create" passed 1 arguments, but takes just 0
>  EVP_MD_CTX _EVP_MD_CTX_create(void);
>                                    ^
> In file included from /usr/local/include/openssl/x509.h:23:0,
>                  from /usr/local/include/openssl/x509v3.h:14,
>                  from ossl.h:58,
>                  from ossl_pkey_ec.c:5:
> openssl_missing.h:82:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
>  void EVP_MD_CTX_init(EVP_MD_CTX *ctx);
>       ^
> openssl_missing.h:90:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
>  void EVP_MD_CTX_destroy(EVP_MD_CTX *ctx);
>       ^
> ossl_pkey_ec.c: In function ‘ossl_ec_new’:
> ossl_pkey_ec.c:140:24: error: dereferencing pointer to incomplete type
>   if (EVP_PKEY_type(pkey->type) != EVP_PKEY_EC) {
>                         ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_initialize’:
> ossl_pkey_ec.c:174:13: error: dereferencing pointer to incomplete type
>      if (pkey->pkey.ec)
>              ^
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:52:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:185:13: note: in expansion of macro ‘SafeRequire_EC_KEY’
>              SafeRequire_EC_KEY(arg, other_ec);
>              ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:52:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:185:13: note: in expansion of macro ‘SafeRequire_EC_KEY’
>              SafeRequire_EC_KEY(arg, other_ec);
>              ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_get_group’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:259:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:259:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_set_group’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:300:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:300:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_get_private_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:332:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:332:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_set_private_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:351:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:351:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_get_public_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:400:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:400:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_set_public_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:423:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:423:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_is_public_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:450:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:450:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_is_private_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:465:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:465:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_to_string’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:479:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:479:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_to_text’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:580:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:580:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_generate_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:603:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:603:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_check_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:623:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:623:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_dh_compute_key’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:644:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:644:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_dsa_sign_asn1’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:674:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:674:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c: In function ‘ossl_ec_key_dsa_verify_asn1’:
> ossl_pkey_ec.c:28:29: error: dereferencing pointer to incomplete type
>      if (EVP_PKEY_type((pkey)->type) != EVP_PKEY_EC) { \
>                              ^
> ossl_pkey_ec.c:40:5: note: in expansion of macro ‘GetPKeyEC’
>      GetPKeyEC((obj), pkey); \
>      ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:699:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> ossl_pkey_ec.c:41:17: error: dereferencing pointer to incomplete type
>      (key) = pkey->pkey.ec; \
>                  ^
> ossl_pkey_ec.c:45:5: note: in expansion of macro ‘Get_EC_KEY’
>      Get_EC_KEY((obj), (key)); \
>      ^
> ossl_pkey_ec.c:699:5: note: in expansion of macro ‘Require_EC_KEY’
>      Require_EC_KEY(self, ec);
>      ^
> make[2]: *_\* [ossl_pkey_ec.o] Error 1
> make[2]: Leaving directory `/usr/share/rvm/src/ruby-2.3.1/ext/openssl'
> make[1]: *** [ext/openssl/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> installing default nkf libraries
> linking shared-object nkf.so
> make[2]: Leaving directory`/usr/share/rvm/src/ruby-2.3.1/ext/nkf'
> make[1]: Leaving directory `/usr/share/rvm/src/ruby-2.3.1'
> make: **\* [build-ext] Error 2
> ++ return 2

Any ideas?

I did upgrade my openssl to 1.1.0, but no cigar :(

Thanks in advance!

**Comment by raelgc** [comment]
Hi @kkoci and thanks for reporting this.

Do you mind to try our [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by pkuczynski** [comment]
@kkoci any feedback with dedicated ubuntu package? Otherwise we will have to close this issue...

**Comment by kkoci** [comment]
Hi @pkuczynski Sorry, I was a bit busy, I'm going to try it right now, and write you back, Thank You

**Comment by pkuczynski** [comment]
Ok, waiting for your feedback...

**Comment by kkoci** [comment]
Hi @pkuczynski 

Did everything explained on the buntu dedicated package repo.

Tried installing 2.3.1 this is the traceback, same as before:

> rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: mint/17.2/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for mint.
Requirements installation successful.
Installing Ruby from source to: /usr/share/rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0  90821      0  0:02:38  0:02:38 --:--:--  141k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-2.3.1 - #extracting ruby-2.3.1 to /usr/share/rvm/src/ruby-2.3.1....
ruby-2.3.1 - #configuring..........................................................
ruby-2.3.1 - #post-configuration..
ruby-2.3.1 - #compiling............................................................................................................
Error running '__rvm_make -j2',
showing last 15 lines of /home/kristian/.rvm/log/1477264549_ruby-2.3.1/make.log
     Get_EC_KEY((obj), (key)); \
     ^
ossl_pkey_ec.c:699:5: note: in expansion of macro ‘Require_EC_KEY’
     Require_EC_KEY(self, ec);
     ^
make[2]: *** [ossl_pkey_ec.o] Error 1
make[2]: Leaving directory `/usr/share/rvm/src/ruby-2.3.1/ext/openssl'
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default nkf libraries
linking shared-object nkf.so
make[2]: Leaving directory `/usr/share/rvm/src/ruby-2.3.1/ext/nkf'
make[1]: Leaving directory `/usr/share/rvm/src/ruby-2.3.1'
make: *** [build-ext] Error 2
++ return 2

Really don't know what to do :(

**Comment by kkoci** [comment]
Seems to be related to openssl, I could be wrong, but what can I do in that case?

**Comment by pkuczynski** [comment]
Could you please gist your full `.rvm/log/1477264549_ruby-2.3.1/make.log`

**Comment by kkoci** [comment]
Done [https://gist.github.com/kkoci/e92af8fcf1c085aa00ffb96212d12716](here)

I think it has something to do with openssl, but I can be wrong tho :/

**Comment by pkuczynski** [comment]
Indeed it's failing on open ssl compilation with message 
```
/usr/local/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."
```

Is your system up to date?

**Comment by pkuczynski** [comment]
I assume that you tried with dedicated ubuntu package?

**Comment by kkoci** [comment]
Yes, just followed the instructions from the repository

Not really up to date, have to upgrade few things tho

But still not sure if could fix it, gonna try

**Comment by kkoci** [comment]
Nothing

Already updated everything

Same error as before

Should I reinstall rvm again?

I don't know, really

**Comment by fbretel** [comment]
@kkoci you probably have openssl-1.1.0, which is not compatible with ruby-2.3.1 at the moment. See:
https://github.com/openssl/openssl/commit/865b55ac8e32e9815d20b55fb05e66b61558cf6d
https://bugs.ruby-lang.org/issues/12324

**Comment by pkuczynski** [comment]
@kkoci could you check which version of openssl you have?

**Comment by kkoci** [comment]
Can't install 2.1.1 either

My version is: 1.0.1f-1ubuntu2.21

**Comment by pkuczynski** [comment]
Could you please gist output of:

```
rvm get head
rvm info
rvm install 2.3.1
```

together with `install.log` and `make.log`

**Comment by jonblack** [comment]
Not sure if this is helpful, but the same applies to Debian Sid (unstable) which has libssl-dev 1.1.0c-2.

**Comment by tsolar** [comment]
This happened to me too, using Debian Sid. A workaround was: as root run `apt install libssl1.0-dev` and then `rvm install x.x.x --autolibs=0`

**Comment by jonblack** [comment]
Another workaround is to install ruby 2.4.0-preview3 which contains a fix for the openssl issue, if you're able to use a preview release.

**Comment by kkoci** [comment]
Hi @jonblack Yes, it installs the 2.4.0-preview3 indeed, but then I try to install 2.3.1 for example, and nothing, same error, gonna find the logs @pkuczynski asked me days ago

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
