### ISSUE TITLE
Unknown ruby interpreter version

### ISSUE THREAD

**Issue by strarsis** [rvm/rvm#3777]
## Description

When using .ruby-gemset and .ruby-version files, 
`rvm use` in containing directory results in error:

```
Unknown ruby interpreter version (do not know how to handle): ..
```
## Environment info
- RVM version: rvm 1.27.0 (master)
- Operating System: Debian
- Version/Release: Jessie (8.0)
- Shell: bash
## Expected behavior

rvm switches to the ruby gemset and ruby version indicated 
in the .ruby-gemset and .ruby-versions files.
## Actual behavior

Error message:

```
Unknown ruby interpreter version (do not know how to handle): ..
```
## Steps to reproduce
1. For this test, create a new directory, e.g. 'test/' and change cwd to it (cd into it).
2. Create file '.ruby-gemset' inside with following content:
   
   ```
    test-set
   ```
3. Create file '.ruby-version' inside with following content:
   
   ```
    ruby-2.2.3
   ```
4. Invoke `rvm use`.

**Comment by pkuczynski** [comment]
Did you tried to set your `rvmrc` file as described in https://rvm.io/workflow/rvmrc?

**Comment by strarsis** [comment]
I am using a .ruby-version and a .ruby-gemset file in the project directory:
.ruby-version:
````
ruby-2.2.3
````

.ruby-gemset:
````
test-gemset
````

At some point, rvm proposed to update the config files from .rvmrc to .ruby-version and .ruby-gemset.

**Comment by mpapis** [comment]
This is most likely fixed in latest version of RVM, please try again after `rvm get master`.

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
