### ISSUE TITLE
Expired SSL certificate in 2.2.5 binary

### ISSUE THREAD

**Issue by brukatv** [rvm/rvm#3778]
## Description
I can confirm this issue exists in 2.2.3 and 2.2.5 binaries. Have not tested with other rubies.

rubygems.org must have updated their certificates recently because any attempts to contact https://rubygems.org fail with certificate errors:

```
$ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```

To solve it I first had to update openssl (which was not trivial). 

I uninstalled rvm completely, re-installed everything, error persisted. 

Tried installing rubies from source using `--disable-binary` and the issue was fixed. So the binaries need to be updated. See thread at rubygems here: https://github.com/rubygems/rubygems/issues/1745

## Environment info

  - RVM version: 1.27
  - Operating System: OSX yosemite
  - Version/Release: 2.2.5
  - Shell: bash

**Comment by mpapis** [comment]
I'm sorry this is not RVM problem, but RVM can help you to fix it, you need to run:
```bash
rvm osx-ssl-certs update all
```
and then you can make sure it is done every day:
```bash
rvm osx-ssl-certs cron install
```

**Comment by brukatv** [comment]
@mpapis tried that, didn't do anything. The certificates are up-to-date. Only installing rubies from source worked. I agree it's not really an RVM issue but unfortunately the only solution goes through RVM.

**Comment by mpapis** [comment]
hmm, I wonder if we could change the `osx-ssl-certs` to include latest rubygems cert like rubygems does, can you manually install the rubygems certificate in OSX certificates store (I do not know where that is, not using OSX), then run the `update all` again - and check if this solves the problem (before I put time on developing solution that could not be it.

**Comment by brukatv** [comment]
Duplicate. Moving conversation to #3779
