### ISSUE TITLE
Feedback when switching gemset with/without use

### ISSUE THREAD

**Issue by fredrb** [rvm/rvm#3780]
## Description
When switching gemset you can do it in two ways:
- `rvm use 2.x.x@gemset`
- `rvm 2.x.x@gemset`

Both result in the same gemset selected. However the later doesn't give any user feedback. 

```
> rvm use 2.3.1@test
Using /home/fredrb/.rvm/gems/ruby-2.3.1 with gemset test
> rvm 2.3.1@default
> rvm 2.3.1@test
...
```
It would be nice to have the same output for either formats.

## Environment info

  - RVM version: 1.27.0
  - Operating System: Linux
  - Version/Release: 
  - Shell: zsh

## Expected behavior
`Using ${version} with ${gemset}` message when switching gemset with `rvm 2.x.x@gemset`

## Actual behavior
No user feedback when switching gemset with `rvm 2.x.x@gemset`

## Steps to reproduce
 1. rvm use 2.3.1@test
 2. rvm 2.3.1@default

**Comment by pkuczynski** [comment]
Fixed
