### ISSUE TITLE
Couldn't installing ruby 2.3.1 in macOS

### ISSUE THREAD

**Issue by essank** [rvm/rvm#3781]
## Description

My command is: 
```
rvm install ruby-2.3.1
```

and I got this error: 
```
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file ruby-2.3.1.tar.bz2.part: Permission denied
  0 13.7M    0  2759    0     0   6428      0  0:37:25 --:--:--  0:37:25 21223
curl: (23) Failed writing body (0 != 2759)
There was an error(23).
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.1.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file ruby-2.3.1.tar.bz2.part: Permission denied
  0 13.7M    0 16149    0     0   8836      0  0:27:13  0:00:01  0:27:12  8843
curl: (23) Failed writing body (0 != 16149)
There was an error(23).
Failed download
There has been an error fetching the ruby interpreter. Halting the installation.
```
## Environment info

  - RVM version: rvm 1.27.0
  - Operating System: macOS
  - Version/Release: sierra

**Comment by mpapis** [comment]
most likely reasons for that to happen are:

1. lack of disk space - please check and clean space if necessary
2. lack of permissions - add your user to `rvm` group and logout+login (`rvm group add rvm $USER`)
3. broken permissions - run `rvm fix-permissions`

**Comment by essank** [comment]
It's working, Thanks!

**Comment by essank** [comment]
after I installed it. I got this error:
command
```
sudo gem update
```
This is the error
```
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Error loading RubyGems plugin "/Users/usernam/.gem/ruby/2.3.0/gems/executable-hooks-1.3.2/lib/rubygems_plugin.rb": cannot load such file -- executable-hooks/wrapper (LoadError)
```

**Comment by interglobalmedia** [comment]
@mpapis I'm having problems finding my Ruby interpreter on my computer as well. Screwing up anything that has to do with Ruby ie Jekyll etc. I typed in the command `rvm group add rvm $USER` as per your suggestion above, and then was asked for a password. What password is it looking for, and is that safe to do so? I don't want to give any passwords out just like that, especially when I don't know the end receiver. Thanks!

**Comment by mpapis** [comment]
@interglobalmedia RVM uses `sudo` or `su` depending on the system, in your case it's most likely `sudo` and the default configuration is to use user password on OSX, it's as much safe as you trust RVM developers ... I guess you do by running our code on your machine ;)

**Comment by interglobalmedia** [comment]
@mpapis Thanks for the clarification! I have 2.4.0 running right now.  Fist installed stable version of rvm and then had to re-install ruby. Then I reinstalled the bundler. Working well for Jekyll now, but still have the Ruby Interpreter issue. So I guess if I fix the permissions I should be good to go? Again, thanks for all your help!

**Comment by interglobalmedia** [comment]
@mpapis Thanks Michael! Fixed finally!
