### ISSUE TITLE
~/.rvm/bin/rvm: line 66: shell_session_update: command not found

### ISSUE THREAD

**Issue by selfagency** [rvm/rvm#3782]
## Description

This is on a brand new install of MacOS Sierra

## Environment info

  - RVM version: whatever's the latest
  - Operating System: MacOS
  - Version/Release: 10.12
  - Shell: Bash

## Expected behavior

To not see this: `/Users/ds/.rvm/bin/rvm: line 66: shell_session_update: command not found`

## Actual behavior

I see this: `/Users/ds/.rvm/bin/rvm: line 66: shell_session_update: command not found`

## Steps to reproduce
 1. Install Mac OS Sierra
 2. Install RVM
 3. Run `rvm`

**Comment by pkuczynski** [comment]
Have you restarted your terminal after installing RVM? Can you check which bash version do you use (`echo $BASH_VERSION`)

**Comment by selfagency** [comment]
Yes, I have. My bash version is 3.2.57(1)-release. I also have the same problem using fish with the Fisherman NVM wrapper.

**Comment by pkuczynski** [comment]
That's interesting. Could you please gist result of following commands:

`type rvm | head -1`
`rvm debug`

and if you executing some rvm command include `--trace` param

`rvm --trace COMMAND`

**Comment by selfagency** [comment]
Here ya go
https://gist.github.com/f989a3a9923c2eaf240019d62d908400

**Comment by pkuczynski** [comment]
Can you test it with `rvm get master`. This issue has been solved in master, but has not been released yet.

**Comment by selfagency** [comment]
that did it!

**Comment by selfagency** [comment]
Here ya go
https://gist.github.com/f989a3a9923c2eaf240019d62d908400
