### ISSUE TITLE
OSX - Error running 'requirements_osx_brew_libs_install' on rvm install 2.3.1

### ISSUE THREAD

**Issue by haimsc** [rvm/rvm#3783]
## Environment info

  - RVM version: 1.27.0
  - Operating System: macOS Sierra
  - Version/Release: 10.12

## Description
I'm trying to install Ruby 2.3.1 with RVM. I'm getting the error shown below. The results from "brew doctor" are also attached.
[brew_doctor.txt](https://github.com/rvm/rvm/files/538161/brew_doctor.txt)

rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Installing requirements for osx.
Updating system.....
Installing required packages: automake...
Error running 'requirements_osx_brew_libs_install automake',
showing last 15 lines of /Users/haims/.rvm/log/1476859854_ruby-2.3.1/package_install_automake.log
++ case "$1" in
++ [[ -t 1 ]]
++ return 1
++ printf %b 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation\n'
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
++ case "$_system_version" in
++ return 1
Requirements installation failed with status: 1.

**Comment by haimsc** [comment]
Problem solved! It seems to be related to a problem with Homebrew on OSX Sierra, so I had to update Homebrew.

These are the steps that worked for me:
sudo chown -R $(whoami) /usr/local
cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
sudo chmod 0755 /usr/local
sudo chown root:wheel /usr/local

I then ran brew doctor, and fixed the "unlinked kegs" reported by brew doctor:

brew link autoconf
brew link ... <same for other kegs>

Finally I ran
brew tap --repair

And I was able to install Ruby 2.3.1 with rvm.

**Comment by acelsosoares** [comment]
> Problem solved! It seems to be related to a problem with Homebrew on OSX Sierra, so I had to update Homebrew.
> 
> These are the steps that worked for me:
> sudo chown -R $(whoami) /usr/local
> cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
> sudo chmod 0755 /usr/local
> sudo chown root:wheel /usr/local
> 
> I then ran brew doctor, and fixed the "unlinked kegs" reported by brew doctor:
> 
> brew link autoconf
> brew link ...
> 
> Finally I ran
> brew tap --repair
> 
> And I was able to install Ruby 2.3.1 with rvm.

I just ran brew cleanup and then i could install ruby with rvm

**Comment by pedroMiranda7410** [comment]
Running just 'brew cleanup' just solved all my problems too

> > Problem solved! It seems to be related to a problem with Homebrew on OSX Sierra, so I had to update Homebrew.
> > These are the steps that worked for me:
> > sudo chown -R $(whoami) /usr/local
> > cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
> > sudo chmod 0755 /usr/local
> > sudo chown root:wheel /usr/local
> > I then ran brew doctor, and fixed the "unlinked kegs" reported by brew doctor:
> > brew link autoconf
> > brew link ...
> > Finally I ran
> > brew tap --repair
> > And I was able to install Ruby 2.3.1 with rvm.
> 
> I just ran brew cleanup and then i could install ruby with rvm

Just running the 'brew cleanup' command, solved all my problems too
