### ISSUE TITLE
Can't download rvm; curl returned status '23'

### ISSUE THREAD

**Issue by Mersion** [rvm/rvm#3785]
```
C:\Users\Me> bash rvm-installer stable
Downloading https://github.com/rvm/rvm/archive.1.27.0.tar.gz
curl: (23) Failed writing body (0 != 762)

Could not download 'https://github.com/rvm/rvm/archive.1.27.0.tar.gz'
curl returned status '23'

Downloading https://bitbucket.org/mpapis/rvm/get/1.27.0.tar.gz
curl: (23) Failed writing body (0 != 13992)

Could not download 'https://bitbucket.org/mpapis/rvm/get/1.27.0.tar.gz'
curl returned status '23'
```
I'm trying to install rvm but i can't. I've tried different solutions but without success. Please help me find a solution.

**Comment by pkuczynski** [comment]
I can see you are using Windows? Why don't you install RVM on cygwin?

**Comment by Mersion** [comment]
On cygwin i get:
`$ bash rvm-installer stable 
bash: rvm-installer: No such file or directory`

**Comment by pkuczynski** [comment]
Can you please run `curl -L https://get.rvm.io | bash -s master`

**Comment by Mersion** [comment]
![bez nazwy](https://cloud.githubusercontent.com/assets/23041908/19689724/997c06ec-9ace-11e6-9afa-628af1d26171.png)

**Comment by pkuczynski** [comment]
Please gist output of `curl -L https://get.rvm.io | bash -s master --trace`

**Comment by pkuczynski** [comment]
It looks like there is permission problem...

**Comment by Mersion** [comment]
I have send link to you on email.

**Comment by Mersion** [comment]
gist.github.com gist.github.com  
                
              
               
                 
                  Dnia 25 października 2016 16:33 Piotr Kuczynski &lt;notifications@github.com&gt; napisał(a):
                 
                 
                   It looks like there is permission problem...

**Comment by Mersion** [comment]
https://gist.github.com/Mersion/f11555e729e15c5451812a0c34c777e3/revisions

**Comment by pkuczynski** [comment]
Can you try `curl -LN https://get.rvm.io | bash -s master --trace`

**Comment by Mersion** [comment]
Sorry, nothing changed. ;<

**Comment by pkuczynski** [comment]
Can you run in your console:

`curl --fail --location --max-redirs 10 --conne                                                                                                                ct-timeout 30 --retry-delay 2 --retry 3 -sS https://github.com/rvm/rvm/archive/m                                                                                                                aster.tar.gz -o /home/Zachu/.rvm/archives/rvm-master.tgz`

**Comment by Mersion** [comment]
`curl: (23) Faile writing body 0 !=1370` Cmd windows
`curl: (23) Faile writing body 0 !=762`   Cygwin64

**Comment by pkuczynski** [comment]
Than it is clearly problem with curl not being able to write the file (reading curl documentation _Write error. Curl couldn't write data to a local filesystem or similar._). Can you check if you have enough permission to write to `/home/Zachu/` and if `/home/Zachu/.rvm` exists?

**Comment by pkuczynski** [comment]
Could you please also print output of:

```
less ~/.bashrc
echo $rvm_path
echo $GEM_HOME
```

**Comment by Mersion** [comment]
```
$ less ~/.bashrc
/home/Zachu/.bashrc: No such file or directory
$ echo $rvm_path

$ echo $GEM_HOME

```

**Comment by Mersion** [comment]
```
$ ps -p $$
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     6100    6588    6100       7932  pty0      197610 13:46:55 /usr/bin/bash

$ which bash
/usr/bin/bash
```

**Comment by pkuczynski** [comment]
And:

```
ls -al /home/Zachu/
ls -al /home/Zachu/.rvm
```

**Comment by Mersion** [comment]
```
$ ls -al /home/Zachu/
razem 1 #together 1
drwxr-xr-x+ 1 Zachu None   0 10-25 17:06 .
drwxrwxrwt+ 1 Zachu None   0 10-24 23:41 ..
-rw-------  1 Zachu None 407 10-25 22:18 .bash_history
drwxr-xr-x+ 1 Zachu None   0 10-24 23:41 .rvm

$ ls -al /home/Zachu/.rvm
razem 0 #together 0
drwxr-xr-x+ 1 Zachu None 0 10-24 23:41 .
drwxr-xr-x+ 1 Zachu None 0 10-25 17:06 ..
drwxr-xr-x+ 1 Zachu None 0 10-24 23:41 archives
drwxr-xr-x+ 1 Zachu None 0 10-24 23:41 src


```

**Comment by pkuczynski** [comment]
And any error on

`curl -sSL https://get.rvm.io`

**Comment by Mersion** [comment]
I think there aren't any errors. Only errors that appears are in comments or quotation marks. I leave you a link to gisthub if u want to see. https://gist.github.com/Mersion/b344713b8ced666daba992778b1bd744

**Comment by pkuczynski** [comment]
Fair enough. Now `curl -sS https://github.com/rvm/rvm/archive/master.tar.gz` please...

**Comment by Mersion** [comment]
```
$ curl -sS https://github.com/rvm/rvm/archive/master.tar.gz
<html><body>You are being <a href="https://codeload.github.com/rvm/rvm/tar.gz/master">redirected</a>.</body></html>

```

**Comment by pkuczynski** [comment]
`curl --location --max-redirs 10 -sS https://github.com/rvm/rvm/archive/master.tar.gz`

**Comment by Mersion** [comment]
It displays some unreadable characters and leave me with a list of numbers each followed by semicolon.

**Comment by pkuczynski** [comment]
And this one:

`curl --location --max-redirs 10 -sS https://github.com/rvm/rvm/archive/master.tar.gz -o /home/Zachu/.rvm/archives/rvm-master.tgz`

vs

`curl --location --max-redirs 10 -sS https://github.com/rvm/rvm/archive/master.tar.gz > /home/Zachu/.rvm/archives/rvm-master.tgz`

**Comment by Mersion** [comment]
The first leaves.
`curl: (23) Failed writing body (0 != 1370)`
Second displays nothing.

**Comment by pkuczynski** [comment]
Can you now check if it saved the file correctly: `ls -al /home/Zachu/.rvm/archives/`

**Comment by Mersion** [comment]
```
$ ls -al /home/Zachu/.rvm/archives/
together 1256
drwxr-xr-x+ 1 Zachu None       0 10-26 16:56 .
drwxr-xr-x+ 1 Zachu None       0 10-24 23:41 ..
-rw-r--r--  1 Zachu None 1283351 10-26 17:10 rvm-master.tgz

```
How can i check? Sorry for being newbie.

**Comment by pkuczynski** [comment]
No worries about being newbie :) Our aim is to make RVM work for everyone! Seems that there is some problem with `curl -o` on Windows. I assume that you have Polish Windows?

**Comment by Mersion** [comment]
yep

**Comment by Mersion** [comment]
curl.exe is on appdata which is fixed to read only maybe that's a problem?

**Comment by pkuczynski** [comment]
No, this makes no difference. Let's now check this:

```
rm /home/Zachu/.rvm/archives/*
ls -al /home/Zachu/.rvm/archives/
curl --location --max-redirs 10 https://github.com/rvm/rvm/archive/master.tar.gz -o /home/Zachu/.rvm/archives/rvm-master.tgz
ls -al /home/Zachu/.rvm/archives/
```

**Comment by Mersion** [comment]
```
$ ls -al /home/Zachu/.rvm/archives/
razem 0
drwxr-xr-x+ 1 Zachu None 0 10-26 17:31 .
drwxr-xr-x+ 1 Zachu None 0 10-24 23:41 ..

$ curl --location --max-redirs 10 https://github.com/rvm/rvm/archive/master.tar.gz -o /home/Zachu/.rvm/archives/rvm-master.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   115    0   115    0     0    136      0 --:--:-- --:--:-- --:--:--   136
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file /home/Zachu/.rvm/archives/rvm-master.tgz:
Warning: No such file or directory
curl: (23) Failed writing body (0 != 1370)

$ ls -al /home/Zachu/.rvm/archives/
razem 0
drwxr-xr-x+ 1 Zachu None 0 10-26 17:31 .
drwxr-xr-x+ 1 Zachu None 0 10-24 23:41 ..

```

**Comment by Mersion** [comment]
```
$ rm /home/Zachu/.rvm/archives/*
rm: nie można usunąć '/home/Zachu/.rvm/archives/*': No such file or directory

```
First time when i ran it probably removed it becasue nothing has been displayed.

**Comment by pkuczynski** [comment]
Can you try this one:

`curl -sSL https://raw.githubusercontent.com/rvm/rvm/bugfix/issue-3785/binscripts/rvm-installer | bash -s master`

**Comment by Mersion** [comment]
It looks that it worked! You are the best! :+1:

**Comment by mkuzmin** [comment]
GPG signature has been broken again
https://github.com/rvm/rvm/pull/3550

**Comment by pkuczynski** [comment]
Good catch, will fix this with @mpapis in the morning...

**Comment by wruixue** [comment]
That also solved my problem thank you
