### ISSUE TITLE
rvm needs to be signed again - get stable is broken

### ISSUE THREAD

**Issue by brenguy** [rvm/rvm#3799]
## Description
Brendans-MacBook-Pro:~ brendanledoux$ rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/brendanledoux/.rvm/archives/rvm-installer.asc
gpg: Signature made Wed Nov  2 04:02:51 2016 CDT using RSA key ID BF04FF17
gpg: BAD signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/Users/brendanledoux/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

-bash: return: _ret: numeric argument required

## Environment info

  - RVM version:
  - Operating System:
  - Version/Release:
  - Shell:

## Steps to reproduce
 1.
 2.
 3.

**Comment by pkuczynski** [comment]
Fixed. Sorry for the inconvenience...
