### ISSUE TITLE
JRuby installation with offline rvm installation

### ISSUE THREAD

**Issue by Amand** [rvm/rvm#3800]
## Description

Installed rvm offline (version- rvm 1.27.0 (manual)). Installation seems to be working fine except that it fails to install jruby with error-
jruby-9.0.5.0 - #importing gemsetfile /usr/local/rvm/gemsets/default.gems evaluated to empty gem list
jruby-9.0.5.0 - #generating default wrappers..............
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:411)
	at java.lang.Thread.run(Thread.java:745)

error: ng executable not found; run 'make' in /usr/local/rvm/rubies/jruby-9.0.5.0/tool/nailgun

If rvm is installed through curl-
curl -sSL https://get.rvm.io | bash -s stable

jruby installation works fine with no issues.

## Steps to reproduce

- Install is done as sudo
- I followed the instructions from https://rvm.io/rvm/offline to install rvm. 
- rvm install jruby : Installation showed number of errors all related to error: ng executable not found; run 'make' in /usr/local/rvm/rubies/jruby-9.0.5.0/tool/nailgun
- rvm shows jruby installed -
# rvm list
rvm rubies
=* jruby-9.0.5.0 [ x86_64 ]

## Expected behavior
Jruby shoud get installed successfully

## Environment info

```
rvm info 

jruby-9.0.5.0:

  system:
    uname:       "Linux ip-10-205-201-22.dqa.capitalone.com 2.6.32-642.4.2.el6.x86_64 #1 SMP Mon Aug 15 02:06:41 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "redhat/6/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)"
    zsh:         "/bin/zsh => zsh 4.3.11 (x86_64-redhat-linux-gnu)"

  rvm:
    version:      "rvm 1.27.0 (manual) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "1 hour 21 minutes 56 seconds ago"
    path:         "/usr/local/rvm"

  ruby:
    interpreter:  "jruby"
    version:      "9.0.5.0"
    date:         "jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [linux-amd64]"
    platform:     "linux-amd64"
    patchlevel:   "TM"
    full_version: "jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [linux-amd64]"

  homes:
    gem:          "/usr/local/rvm/gems/jruby-9.0.5.0"
    ruby:         "/usr/local/rvm/rubies/jruby-9.0.5.0"

  binaries:
    ruby:         "/usr/local/rvm/rubies/jruby-9.0.5.0/bin/ruby"
    irb:          "/usr/local/rvm/rubies/jruby-9.0.5.0/bin/irb"
    gem:          "/usr/local/rvm/rubies/jruby-9.0.5.0/bin/gem"
    rake:         "/usr/local/rvm/rubies/jruby-9.0.5.0/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/jruby-9.0.5.0/bin:/usr/local/rvm/gems/jruby-9.0.5.0@global/bin:/usr/local/rvm/rubies/jruby-9.0.5.0/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin:/usr/local/bin:/opt/oracle/instantclient_12_1"
    GEM_HOME:     "/usr/local/rvm/gems/jruby-9.0.5.0"
    GEM_PATH:     "/usr/local/rvm/gems/jruby-9.0.5.0:/usr/local/rvm/gems/jruby-9.0.5.0@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/jruby-9.0.5.0"
    IRBRC:        "/usr/local/rvm/rubies/jruby-9.0.5.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by pkuczynski** [comment]
Can you try with master branch (`-s master`).

Can you make sure you have all dependencies installed?
`java-1.8.0-openjdk-devel java-devel`

**Comment by Amand** [comment]
Yes, I do have all the dependencies installed. If on the same server, I install jruby with rvm installed using curl (online), it all works fine. It doesn't look like an issue with dependencies, it does complain about port already is use. Though it starts java process on 2113 port after starting the installation.

jruby-9.0.5.0 - #gemset created /usr/local/rvm/gems/jruby-9.0.5.0@global
Regenerating jruby-9.0.5.0 wrappers..............
/usr/local/rvm/rubies/jruby-9.0.5.0/bin/ruby
/usr/local/rvm/rubies/jruby-9.0.5.0/bin/gem
/usr/local/rvm/rubies/jruby-9.0.5.0/bin/irb
/usr/local/rvm/rubies/jruby-9.0.5.0/bin/ri
/usr/local/rvm/rubies/jruby-9.0.5.0/bin/rdoc
/usr/local/rvm/rubies/jruby-9.0.5.0/bin/rake
/usr/local/bin/erb
/usr/local/rvm/rubies/jruby-9.0.5.0/bin/testrb
java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:382)
	at java.net.ServerSocket.bind(ServerSocket.java:375)
	at java.net.ServerSocket.<init>(ServerSocket.java:237)
	at java.net.ServerSocket.<init>(ServerSocket.java:128)
	at com.martiansoftware.nailgun.NGServer.run(NGServer.java:411)
	at java.lang.Thread.run(Thread.java:745)

Does offline rvm installtion support jruby install? I didn't see any documentation on that. Also, there are no artifacts for jruby in https://ftp.ruby-lang.org/pub.

I will try with master branch and will update the results.

**Comment by pkuczynski** [comment]
Any update on this?

**Comment by mpapis** [comment]
Closing as there was no feedback in 2 over weeks, feel free to reopen when you can provide the requested information.

**Comment by BrianHawley** [comment]
@mpapis this is still happening, with rvm master. Seen with jruby 9.1.17.0 and 9.2.0.0.

**Comment by BrianHawley** [comment]
Process to fix the issue, with multiuser rvm at master, and jruby-9.2.0.0 as an example:
```sh
rvm install jruby-9.2.0.0
# At this point the above error has occurred in gemset import, and a related issue in wrappers.
`cd /usr/local/rvm/rubies/jruby-9.2.0.0/tool/nailgun && ./configure && make`
rvm gemset import /usr/local/rvm/gemsets/jruby/global.gems  # this will work now
rvm wrappers regenerate  # so will this
```
