### ISSUE TITLE
Ruby won't complete Install with Error

### ISSUE THREAD

**Issue by leahsherrell** [rvm/rvm#3801]
## Description

Ruby Install Halted

## Steps to reproduce

1. rvm reloaded
2. run `rvm install 2.3.1`

## Expected behavior
Ruby is downloaded completely

## Actual behavior

https://gist.github.com/leahsherrell/33d05cb815845deb57d0df8fa1a92bc3

## Environment info

```
  system:
    uname:       "Darwin Leahs-MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64"
    system:      "osx/10.12/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:         "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"

  rvm:
    version:      "rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "23 minutes 10 seconds ago"
    path:         "/Users/leahsherrell/.rvm"

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/deployd/bin:/Users/leahsherrell/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by pkuczynski** [comment]
Please gist `/Users/leahsherrell/.rvm/log/1478571096_ruby-2.3.1/install.log`

**Comment by leahsherrell** [comment]
https://gist.github.com/leahsherrell/c65670b1e9cb4f60a3034eab7c51a3f1

**Comment by leahsherrell** [comment]
Are you able to help with this? Am I providing the correct information?

**Comment by pkuczynski** [comment]
You are missing some packages. Do you have homebrew installed?

**Comment by leahsherrell** [comment]
I do have homebrew installed. I ran what you suggested and it was installing, then seemed to be stuck. I closed out of Terminal reran your suggestion, then:

https://gist.github.com/leahsherrell/8f80516bdaefb370ccadfc1ec135de70

**Comment by leahsherrell** [comment]
Same original error when I try to install Ruby though.

**Comment by leahsherrell** [comment]
Anything else to try?

**Comment by anthonymanker** [comment]
I am having the exact same problem

**Comment by pkuczynski** [comment]
@anthonymanker can you post your install.log as well?

**Comment by pkuczynski** [comment]
@leahsherrell which version of openssl you have installed?

**Comment by anthonymanker** [comment]
@pkuczynski there is no install.log at `/Users/williammanker/.rvm/log/1480651839_ruby-2.3.3`

Here are contents: 

`ACA80ADF:1480651839_ruby-2.3.3 williammanker$ ls
config.log		extract.log	postconfigure.log
configure.log		make.log		remove.src.log`

here is make.log:

https://gist.github.com/anthonymanker/ba7137ae309a780435740c706a8faa15

here is the error I'm getting:

https://gist.github.com/anthonymanker/f86952d73fdf7ebe48b58d8edada2ce3

**Comment by mpapis** [comment]
I'm guessing this might be fixed by one of the patches we included recently, please try after:
```bash
rvm get master
```

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, feel free to provide requested information so we can continue working on it.
