### ISSUE TITLE
Compilation fails when running rvm install ruby-2.3.1 on Sierra

### ISSUE THREAD

**Issue by Raspinfly** [rvm/rvm#3802]
## Description
I am getting the error below installing Ruby 2.3.1 on Sierra using RVM.  

## Steps to reproduce

_Here is what I have tried so far with different errors_

## **1. If I run rvm install ruby-2.3.1**
I get:
ruby-2.3.1 - #removing src/ruby-2.3.1..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Warning: found user selected compiler '/usr/local/bin/gcc-4.9', this will suppress RVM auto detection mechanisms.
Installing Ruby from source to: /Users/Luis/.rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
ruby-2.3.1 - #extracting ruby-2.3.1 to /Users/Luis/.rvm/src/ruby-2.3.1....
ruby-2.3.1 - #configuring......
Error running './configure --prefix=/Users/Luis/.rvm/rubies/ruby-2.3.1 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl --disable-install-doc --enable-shared',
showing last 15 lines of /Users/Luis/.rvm/log/1478615517_ruby-2.3.1/configure.log
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for cd using physical directory... cd -P
checking whether CFLAGS is valid... no
configure: error: something wrong with CFLAGS="-g -O2 "
There has been an error while running configure. Halting the installation.

## **2.  If I run CC=/usr/bin/gcc rvm install 2.3.1**
It goes further but it fails during compilation as shown below:
ruby-2.3.1 - #removing src/ruby-2.3.1..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Warning: found user selected compiler '/usr/bin/gcc', this will suppress RVM auto detection mechanisms.
Installing Ruby from source to: /Users/Luis/.rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
ruby-2.3.1 - #extracting ruby-2.3.1 to /Users/Luis/.rvm/src/ruby-2.3.1....
ruby-2.3.1 - #configuring...........................................................
ruby-2.3.1 - #post-configuration.
ruby-2.3.1 - #compiling............................................
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/Luis/.rvm/log/1478616125_ruby-2.3.1/make.log
                                      ^
etc.c:788:56: error: passing 'void' to parameter of incompatible type 'VALUE' (aka 'unsigned long')
    rb_hash_aset(result, ID2SYM(rb_intern("machine")), rb_str_new_cstr(u.machine));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:803:30: note: expanded from macro 'rb_str_new_cstr'
#define rb_str_new_cstr(str) __extension__ (    \
                             ^~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:520:39: note: passing argument to parameter here
VALUE rb_hash_aset(VALUE, VALUE, VALUE);
                                      ^
1 warning and 6 errors generated.
make[2]: *** [etc.o] Error 1
make[1]: *** [ext/etc/all] Error 2
make: *** [build-ext] Error 2
++ return 2
There has been an error while running make. Halting the installation.

**## 3. The entire log file:**

**********************
[2016-11-08 07:49:08] __rvm_make
__rvm_make () 
{ 
    \make "$@" || return $?
}
current path: /Users/Luis/.rvm/src/ruby-2.3.1
GEM_HOME=/Users/Luis/.rvm/gems/ruby-2.2.4
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/Luis/.rvm/gems/ruby-2.2.4/bin:/Users/Luis/.rvm/gems/ruby-2.2.4@global/bin:/Users/Luis/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Luis/.rvm/bin
GEM_PATH=/Users/Luis/.rvm/gems/ruby-2.2.4:/Users/Luis/.rvm/gems/ruby-2.2.4@global
command(3): __rvm_make -j 1
++ make -j 1
	CC = /usr/bin/gcc
	LD = ld
	LDSHARED = /usr/bin/gcc -dynamiclib
	CFLAGS = -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wunused-variable -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wshorten-64-to-32 -Wimplicit-function-declaration -Wdivision-by-zero -Wdeprecated-declarations -Wextra-tokens   -fno-common -pipe 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT
	CPPFLAGS = -I/usr/local/opt/libyaml/include -I/usr/local/opt/readline/include -I/usr/local/opt/libksba/include -I/usr/local/opt/openssl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   -I. -I.ext/include/x86_64-darwin16 -I./include -I.
	DLDFLAGS = -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -L/usr/local/opt/libyaml/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/openssl/lib -install_name /Users/Luis/.rvm/rubies/ruby-2.3.1/lib/libruby.2.3.0.dylib -current_version 2.3.0 -compatibility_version 2.3.1  -fstack-protector -Wl,-u,_objc_msgSend -framework CoreFoundation  -fstack-protector -Wl,-u,_objc_msgSend -framework CoreFoundation  
	SOLIBS = -lpthread -ldl -lobjc 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.1.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
translating probes probes.d
. ./vm_opts.h
compiling main.c
compiling dmydln.c
compiling miniinit.c
compiling dmyext.c
compiling miniprelude.c
compiling array.c
compiling bignum.c
compiling class.c
compiling compar.c
compiling complex.c
compiling dir.c
compiling dln_find.c
compiling encoding.c
compiling enum.c
compiling enumerator.c
compiling error.c
compiling eval.c
compiling load.c
compiling proc.c
compiling file.c
compiling gc.c
compiling hash.c
compiling inits.c
compiling io.c
compiling marshal.c
compiling math.c
compiling node.c
compiling numeric.c
compiling object.c
compiling pack.c
compiling parse.c
compiling process.c
compiling random.c
compiling range.c
compiling rational.c
compiling re.c
compiling regcomp.c
compiling regenc.c
compiling regerror.c
compiling regexec.c
compiling regparse.c
compiling regsyntax.c
compiling ruby.c
compiling safe.c
compiling signal.c
compiling sprintf.c
compiling st.c
compiling strftime.c
compiling string.c
compiling struct.c
compiling symbol.c
compiling time.c
compiling transcode.c
compiling util.c
compiling variable.c
compiling version.c
compiling compile.c
compiling debug.c
compiling iseq.c
compiling vm.c
compiling vm_dump.c
compiling vm_backtrace.c
compiling vm_trace.c
compiling thread.c
thread.c:1079:27: warning: implicit conversion loses integer precision: 'long' to '__darwin_suseconds_t' (aka 'int') [-Wshorten-64-to-32]
        tp->tv_usec = ts.tv_nsec / 1000;
                    ~ ~~~~~~~~~~~^~~~~~
1 warning generated.
compiling cont.c
compiling enc/ascii.c
compiling enc/us_ascii.c
compiling enc/unicode.c
compiling enc/utf_8.c
compiling enc/trans/newline.c
compiling ./missing/explicit_bzero.c
compiling ./missing/setproctitle.c
compiling dmyenc.c
linking miniruby
config.status: creating ruby-runner.c
generating encdb.h
encdb.h updated
rbconfig.rb updated
generating enc.mk
making srcs under enc
make[1]: Nothing to be done for `srcs'.
generating transdb.h
transdb.h updated
compiling dln.c
compiling localeinit.c
creating verconf.h
verconf.h updated
compiling loadpath.c
compiling prelude.c
linking static-library libruby.2.3.0-static.a
verifying static-library libruby.2.3.0-static.a
linking shared-library libruby.2.3.0.dylib
generating makefile exts.mk
configuring -test-/array/resize
configuring -test-/bignum
configuring -test-/bug-3571
configuring -test-/bug-5832
configuring -test-/bug_reporter
configuring -test-/class
configuring -test-/debug
configuring -test-/dln/empty
configuring -test-/exception
configuring -test-/fatal
configuring -test-/file
configuring -test-/float
configuring -test-/funcall
configuring -test-/gvl/call_without_gvl
configuring -test-/hash
configuring -test-/iseq_load
configuring -test-/iter
configuring -test-/load/dot.dot
configuring -test-/marshal/compat
configuring -test-/marshal/internal_ivar
configuring -test-/marshal/usr
configuring -test-/method
configuring -test-/notimplement
configuring -test-/num2int
configuring -test-/path_to_class
configuring -test-/popen_deadlock
configuring -test-/postponed_job
configuring -test-/printf
configuring -test-/proc
configuring -test-/rational
configuring -test-/recursion
configuring -test-/st/foreach
configuring -test-/st/numhash
configuring -test-/st/update
configuring -test-/string
configuring -test-/struct
configuring -test-/symbol
configuring -test-/time
configuring -test-/tracepoint
configuring -test-/typeddata
configuring -test-/vm
configuring -test-/wait_for_single_fd
configuring bigdecimal
configuring cgi/escape
configuring continuation
configuring coverage
configuring date
configuring dbm
header: ndbm.h
library: libc
configuring digest
configuring digest/bubblebabble
configuring digest/md5
configuring digest/rmd160
configuring digest/sha1
configuring digest/sha2
configuring etc
configuring fcntl
configuring fiber
configuring fiddle
configuring gdbm
Failed to configure gdbm. It will not be installed.
configuring io/console
Failed to configure io/console. It will not be installed.
configuring io/nonblock
configuring io/wait
configuring json
configuring json/generator
configuring json/parser
configuring mathn/complex
configuring mathn/rational
configuring nkf
configuring objspace
configuring openssl
Failed to configure openssl. It will not be installed.
configuring pathname
configuring psych
configuring pty
configuring racc/cparse
configuring rbconfig/sizeof
configuring readline
readline nor libedit not found
Failed to configure readline. It will not be installed.
configuring ripper
configuring sdbm
configuring socket
configuring stringio
configuring strscan
configuring syslog
Failed to configure syslog. It will not be installed.
configuring thread
configuring tk
............
check struct members..
check libraries....
Use ActiveTcl libraries (if available).
Search tclConfig.sh and tkConfig.sh....................................
Valid [tclConfig.sh, tkConfig.sh] are found in [["/System/Library/Frameworks/Tcl.framework", "/System/Library/Frameworks/Tk.framework"], ["/usr/lib", "/usr/lib"], ["/System/Library/Frameworks/Tcl.framework/Versions/Current", "/System/Library/Frameworks/Tk.framework/Versions/Current"], ["/System/Library/Frameworks/Tcl.framework/Versions/8.5", "/System/Library/Frameworks/Tk.framework/Versions/8.5"], ["/System/Library/Frameworks/Tcl.framework/Versions/8.4", "/System/Library/Frameworks/Tk.framework/Versions/8.4"]]
Use [tclConfig.sh, tkConfig.sh] == ["/System/Library/Frameworks/Tcl.framework/tclConfig.sh", "/System/Library/Frameworks/Tk.framework/tkConfig.sh"]
Use MacOS X Frameworks.

Find Tcl/Tk libraries. Make tcltklib.so which is required by Ruby/Tk.
configuring tk/tkutil
configuring zlib
Failed to configure zlib. It will not be installed.
compiling resize.c
linking shared-object -test-/array/resize.bundle
compiling big2str.c
compiling bigzero.c
compiling div.c
compiling init.c
compiling intpack.c
compiling mul.c
compiling str2big.c
linking shared-object -test-/bignum.bundle
compiling bug.c
linking shared-object -test-/bug-3571/bug.bundle
compiling bug.c
linking shared-object -test-/bug-5832/bug.bundle
compiling bug_reporter.c
linking shared-object -test-/bug_reporter/bug_reporter.bundle
compiling class2name.c
compiling init.c
linking shared-object -test-/class.bundle
compiling init.c
compiling inspector.c
compiling profile_frames.c
linking shared-object -test-/debug.bundle
compiling empty.c
linking shared-object -test-/dln/empty.bundle
compiling dataerror.c
compiling enc_raise.c
compiling ensured.c
compiling init.c
linking shared-object -test-/exception.bundle
compiling rb_fatal.c
linking shared-object -test-/fatal/rb_fatal.bundle
compiling fs.c
compiling init.c
compiling stat.c
linking shared-object -test-/file.bundle
compiling init.c
compiling nextafter.c
linking shared-object -test-/float.bundle
compiling passing_block.c
linking shared-object -test-/funcall/funcall.bundle
compiling call_without_gvl.c
linking shared-object -test-/gvl/call_without_gvl.bundle
compiling delete.c
compiling init.c
linking shared-object -test-/hash.bundle
compiling iseq_load.c
linking shared-object -test-/iseq_load/iseq_load.bundle
compiling break.c
compiling init.c
compiling yield.c
linking shared-object -test-/iter.bundle
compiling dot.dot.c
linking shared-object -test-/load/dot.dot/dot.dot.bundle
compiling usrcompat.c
linking shared-object -test-/marshal/compat.bundle
compiling internal_ivar.c
linking shared-object -test-/marshal/internal_ivar.bundle
compiling usrmarshal.c
linking shared-object -test-/marshal/usr.bundle
compiling arity.c
compiling init.c
linking shared-object -test-/method.bundle
compiling bug.c
linking shared-object -test-/notimplement.bundle
compiling num2int.c
linking shared-object -test-/num2int/num2int.bundle
compiling path_to_class.c
linking shared-object -test-/path_to_class/path_to_class.bundle
make[2]: Nothing to be done for `all'.
compiling postponed_job.c
linking shared-object -test-/postponed_job.bundle
compiling printf.c
linking shared-object -test-/printf.bundle
compiling init.c
compiling receiver.c
compiling super.c
linking shared-object -test-/proc.bundle
compiling rat.c
linking shared-object -test-/rational.bundle
compiling recursion.c
linking shared-object -test-/recursion.bundle
compiling foreach.c
linking shared-object -test-/st/foreach.bundle
compiling numhash.c
linking shared-object -test-/st/numhash.bundle
compiling update.c
linking shared-object -test-/st/update.bundle
compiling coderange.c
compiling cstr.c
compiling ellipsize.c
compiling enc_associate.c
compiling enc_str_buf_cat.c
compiling fstring.c
compiling init.c
compiling modify.c
compiling nofree.c
compiling normalize.c
compiling qsort.c
compiling set_len.c
linking shared-object -test-/string.bundle
compiling duplicate.c
compiling init.c
compiling member.c
linking shared-object -test-/struct.bundle
compiling init.c
compiling type.c
linking shared-object -test-/symbol.bundle
compiling init.c
compiling new.c
linking shared-object -test-/time.bundle
compiling gc_hook.c
compiling tracepoint.c
linking shared-object -test-/tracepoint.bundle
compiling typeddata.c
linking shared-object -test-/typeddata/typeddata.bundle
compiling at_exit.c
linking shared-object -test-/vm/at_exit.bundle
compiling wait_for_single_fd.c
linking shared-object -test-/wait_for_single_fd/wait_for_single_fd.bundle
compiling bigdecimal.c
linking shared-object bigdecimal.bundle
installing default bigdecimal libraries
compiling escape.c
linking shared-object cgi/escape.bundle
compiling continuation.c
linking shared-object continuation.bundle
compiling coverage.c
linking shared-object coverage.bundle
compiling date_core.c
compiling date_parse.c
compiling date_strftime.c
compiling date_strptime.c
linking shared-object date_core.bundle
installing default date_core libraries
compiling dbm.c
linking shared-object dbm.bundle
compiling digest.c
linking shared-object digest.bundle
installing digest libraries
installing default digest libraries
compiling bubblebabble.c
linking shared-object digest/bubblebabble.bundle
compiling md5init.c
compiling md5.c
linking shared-object digest/md5.bundle
compiling rmd160init.c
compiling rmd160.c
linking shared-object digest/rmd160.bundle
compiling sha1init.c
compiling sha1.c
linking shared-object digest/sha1.bundle
compiling sha2init.c
compiling sha2.c
linking shared-object digest/sha2.bundle
installing default sha2 libraries
generating constant definitions
compiling etc.c
etc.c:775:20: error: variable has incomplete type 'struct utsname'
    struct utsname u;
                   ^
etc.c:775:12: note: forward declaration of 'struct utsname'
    struct utsname u;
           ^
etc.c:779:11: warning: implicit declaration of function 'uname' is invalid in C99 [-Wimplicit-function-declaration]
    ret = uname(&u);
          ^
etc.c:784:56: error: passing 'void' to parameter of incompatible type 'VALUE' (aka 'unsigned long')
    rb_hash_aset(result, ID2SYM(rb_intern("sysname")), rb_str_new_cstr(u.sysname));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:803:30: note: expanded from macro 'rb_str_new_cstr'
#define rb_str_new_cstr(str) __extension__ (    \
                             ^~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:520:39: note: passing argument to parameter here
VALUE rb_hash_aset(VALUE, VALUE, VALUE);
                                      ^
etc.c:785:57: error: passing 'void' to parameter of incompatible type 'VALUE' (aka 'unsigned long')
    rb_hash_aset(result, ID2SYM(rb_intern("nodename")), rb_str_new_cstr(u.nodename));
                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:803:30: note: expanded from macro 'rb_str_new_cstr'
#define rb_str_new_cstr(str) __extension__ (    \
                             ^~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:520:39: note: passing argument to parameter here
VALUE rb_hash_aset(VALUE, VALUE, VALUE);
                                      ^
etc.c:786:56: error: passing 'void' to parameter of incompatible type 'VALUE' (aka 'unsigned long')
    rb_hash_aset(result, ID2SYM(rb_intern("release")), rb_str_new_cstr(u.release));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:803:30: note: expanded from macro 'rb_str_new_cstr'
#define rb_str_new_cstr(str) __extension__ (    \
                             ^~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:520:39: note: passing argument to parameter here
VALUE rb_hash_aset(VALUE, VALUE, VALUE);
                                      ^
etc.c:787:56: error: passing 'void' to parameter of incompatible type 'VALUE' (aka 'unsigned long')
    rb_hash_aset(result, ID2SYM(rb_intern("version")), rb_str_new_cstr(u.version));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:803:30: note: expanded from macro 'rb_str_new_cstr'
#define rb_str_new_cstr(str) __extension__ (    \
                             ^~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:520:39: note: passing argument to parameter here
VALUE rb_hash_aset(VALUE, VALUE, VALUE);
                                      ^
etc.c:788:56: error: passing 'void' to parameter of incompatible type 'VALUE' (aka 'unsigned long')
    rb_hash_aset(result, ID2SYM(rb_intern("machine")), rb_str_new_cstr(u.machine));
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:803:30: note: expanded from macro 'rb_str_new_cstr'
#define rb_str_new_cstr(str) __extension__ (    \
                             ^~~~~~~~~~~~~~~~~~~~
../.././include/ruby/intern.h:520:39: note: passing argument to parameter here
VALUE rb_hash_aset(VALUE, VALUE, VALUE);
                                      ^
1 warning and 6 errors generated.
make[2]: *** [etc.o] Error 1
make[1]: *** [ext/etc/all] Error 2
make: *** [build-ext] Error 2
++ return 2

## Environment info

_Paste below the output of_

```
rvm info 


ruby-2.2.4:

  system:
    uname:       "Darwin Luis-MacPro.domain 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64"
    system:      "osx/10.12/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:         "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"

  rvm:
    version:      "rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "6 hours 28 minutes 11 seconds ago"
    path:         "/Users/Luis/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.2.4p230"
    date:         "2015-12-16"
    platform:     "x86_64-darwin15"
    patchlevel:   "2015-12-16 revision 53155"
    full_version: "ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]"

  homes:
    gem:          "/Users/Luis/.rvm/gems/ruby-2.2.4"
    ruby:         "/Users/Luis/.rvm/rubies/ruby-2.2.4"

  binaries:
    ruby:         "/Users/Luis/.rvm/rubies/ruby-2.2.4/bin/ruby"
    irb:          "/Users/Luis/.rvm/rubies/ruby-2.2.4/bin/irb"
    gem:          "/Users/Luis/.rvm/rubies/ruby-2.2.4/bin/gem"
    rake:         "/Users/Luis/.rvm/rubies/ruby-2.2.4/bin/rake"

  environment:
    PATH:         "/Users/Luis/.rvm/gems/ruby-2.2.4/bin:/Users/Luis/.rvm/gems/ruby-2.2.4@global/bin:/Users/Luis/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Luis/.rvm/bin"
    GEM_HOME:     "/Users/Luis/.rvm/gems/ruby-2.2.4"
    GEM_PATH:     "/Users/Luis/.rvm/gems/ruby-2.2.4:/Users/Luis/.rvm/gems/ruby-2.2.4@global"
    MY_RUBY_HOME: "/Users/Luis/.rvm/rubies/ruby-2.2.4"
    IRBRC:        "/Users/Luis/.rvm/rubies/ruby-2.2.4/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

```

Any help will be greatly appreciated.

Thank you.

**Comment by pkuczynski** [comment]
Have you installed `gcc-4.9` yourself? Seems to be conflicting with RVM auto detecting mechanism...

**Comment by Raspinfly** [comment]
I installed gcc using Homebrew a while back.  brew list shows gcc49.

**Comment by pkuczynski** [comment]
Can you temporarily remove it and see if that helps?

**Comment by Raspinfly** [comment]
Ok,  I removed it but apparently I have some config that is looking for it.  I am fairly new to this so not suere where to look.

Here are the errors I got:

## $rvm install ruby-2.3.1
ruby-2.3.1 - #removing src/ruby-2.3.1..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
You requested building with '/usr/local/bin/gcc-4.9' but it is not in your path.

--Then I tried--

## $ CC=/usr/bin/gcc rvm install ruby-2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Warning: found user selected compiler '/usr/bin/gcc', this will suppress RVM auto detection mechanisms.
Installing Ruby from source to: /Users/Luis/.rvm/rubies/ruby-2.3.1, this may take a while depending on your cpu(s)...
ruby-2.3.1 - #downloading ruby-2.3.1, this may take a while depending on your connection...
ruby-2.3.1 - #extracting ruby-2.3.1 to /Users/Luis/.rvm/src/ruby-2.3.1....
ruby-2.3.1 - #configuring...
Error running './configure --prefix=/Users/Luis/.rvm/rubies/ruby-2.3.1 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl --disable-install-doc --enable-shared',
showing last 15 lines of /Users/Luis/.rvm/log/1478618015_ruby-2.3.1/configure.log
checking target system type... x86_64-apple-darwin16.1.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/bin/gcc accepts -g... yes
checking for /usr/bin/gcc option to accept ISO C89... none needed
checking whether we are using the GNU C++ compiler... no
checking whether /usr/local/bin/g++-4.9 accepts -g... no
checking how to run the C preprocessor... /usr/local/bin/cpp-4.9
configure: error: in `/Users/Luis/.rvm/src/ruby-2.3.1':
configure: error: C preprocessor "/usr/local/bin/cpp-4.9" fails sanity check
See `config.log' for more details
There has been an error while running configure. Halting the installation.

**Comment by Raspinfly** [comment]
If you have any ideas that would help me a great deal.

Thank you.

**Comment by pkuczynski** [comment]
Print here output of `export`

**Comment by Raspinfly** [comment]
##export

declare -x ARCHFLAGS="-Wno-error=unused-command-line-argument-hard-error-in-future"
declare -x Apple_PubSub_Socket_Render="/private/tmp/com.apple.launchd.hMMY98Vfvm/Render"
declare -x CC="/usr/local/bin/gcc-4.9"
declare -x CPP="/usr/local/bin/cpp-4.9"
declare -x CXX="/usr/local/bin/g++-4.9"
declare -x GEM_HOME="/Users/Luis/.rvm/gems/ruby-2.2.4"
declare -x GEM_PATH="/Users/Luis/.rvm/gems/ruby-2.2.4:/Users/Luis/.rvm/gems/ruby-2.2.4@global"
declare -x HOME="/Users/Luis"
declare -x IRBRC="/Users/Luis/.rvm/rubies/ruby-2.2.4/.irbrc"
declare -x LANG="en_US.UTF-8"
declare -x LOGNAME="Luis"
declare -x MY_RUBY_HOME="/Users/Luis/.rvm/rubies/ruby-2.2.4"
declare -x OLDPWD="/Users/Luis/Projects"
declare -x PATH="/Users/Luis/.rvm/gems/ruby-2.2.4/bin:/Users/Luis/.rvm/gems/ruby-2.2.4@global/bin:/Users/Luis/.rvm/rubies/ruby-2.2.4/bin:/usr/local/bin:/usr/local/sbin:~/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Luis/.rvm/bin"
declare -x PS1="\\u@\\h \\W\\[\\033[32m\\]\$(parse_git_branch)\\[\\033[00m\\] \$ "
declare -x PWD="/Users/Luis/Projects/mytennisstats"
declare -x RUBY_VERSION="ruby-2.2.4"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.2tKeRNZfm1/Listeners"
declare -x TERM="xterm-256color"
declare -x TERM_PROGRAM="Apple_Terminal"
declare -x TERM_PROGRAM_VERSION="387"
declare -x TERM_SESSION_ID="6ECF02D2-276C-4D81-AF3A-CA6851CFEBD8"
declare -x TMPDIR="/var/folders/wt/xj1qyl1x2v56x_f3b4njd11c0000gn/T/"
declare -x USER="Luis"
declare -x XPC_FLAGS="0x0"
declare -x XPC_SERVICE_NAME="0"
declare -x __CF_USER_TEXT_ENCODING="0x1F5:0x0:0x0"
declare -x _system_arch="x86_64"
declare -x _system_name="OSX"
declare -x _system_type="Darwin"
declare -x _system_version="10.12"
declare -x install_flag="1"
declare -x reinstall_flag="1"
declare -x rvm_alias_expanded
declare -x rvm_bin_flag
declare -x rvm_bin_path="/Users/Luis/.rvm/bin"
declare -x rvm_delete_flag
declare -x rvm_docs_type
declare -x rvm_file_name
declare -x rvm_gemstone_package_file
declare -x rvm_gemstone_url
declare -x rvm_hook
declare -x rvm_niceness
declare -x rvm_nightly_flag
declare -x rvm_only_path_flag
declare -x rvm_path="/Users/Luis/.rvm"
declare -x rvm_prefix="/Users/Luis"
declare -x rvm_proxy
declare -x rvm_quiet_flag
declare -x rvm_recommended_ruby="rvm install ruby-2.3.1"
declare -x rvm_ruby_alias
declare -x rvm_ruby_bits
declare -x rvm_ruby_configure
declare -x rvm_ruby_file
declare -x rvm_ruby_global_gems_path
declare -x rvm_ruby_make
declare -x rvm_ruby_make_install
declare -x rvm_ruby_mode
declare -x rvm_ruby_string="ruby-2.3.1"
declare -x rvm_ruby_url
declare -x rvm_script_name
declare -x rvm_sdk
declare -x rvm_silent_flag
declare -x rvm_sticky_flag
declare -x rvm_system_flag
declare -x rvm_use_flag
declare -x rvm_user_flag
declare -x rvm_version="1.27.0 (latest)"
declare -x rvm_wrapper_name

**Comment by pkuczynski** [comment]
So clearly your env variables are pointing to removed gcc. Have you restarted the terminal after removing `gcc49`? If no, please restart terminal and try to install again.

If it still fails, run
```
unset CC
unset CPP
unset CXX
brew doctor
```
and try again `rvm install ...`

**Comment by Raspinfly** [comment]
That did the trick!  By running the unset ...

Thank you very much for your help!

**Comment by pkuczynski** [comment]
You welcome :)
