### ISSUE TITLE
Support relocateability

### ISSUE THREAD

**Issue by probonopd** [rvm/rvm#3804]
## Description

rvm creates a `$HOME/.rvm` directory which is not relocateable, because it contains hardcoded references to the expanded `$HOME/.rvm`path.

To make the directory relocateable (= movable in the filesystem) it would be nice if only relative paths could be used.

## Steps to reproduce

 1. `curl -sSL https://get.rvm.io | bash -s stable --ruby`
 2. `source $HOME/.rvm/scripts/rvm`
 3. `gem install travis`

## Expected behavior

I can move `$HOME/.rvm/` to a different location, e.g., to `/mnt/thumbdrive/rvm` and be able to call `/mnt/thumbdrive/rvm/wrappers/ruby-2.3.0/travis` and it runs

## Actual behavior

It does not work because paths are hardcoded to the original `$HOME/.rvm/scripts/rvm`.

### Example

Instead of the following `$HOME/.rvm/wrappers/ruby-2.3.0/`

```
#!/usr/bin/env bash

if
  [[ -s "/home/me/.rvm/gems/ruby-2.3.0/environment" ]]
then
  source "/home/me/.rvm/gems/ruby-2.3.0/environment"
  exec travis "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/me/.rvm/gems/ruby-2.3.0/environment'" >&2
  exit 1
fi
```

there could be 

```
#!/usr/bin/env bash
HERE=$(dirname $(readlink -f "${0}"))
if
  [[ -s "${HERE}/../../gems/ruby-2.3.0/environment" ]]
then
  source "${HERE}/../../gems/ruby-2.3.0/environment"
  exec travis "$@"
else
  echo "ERROR: Missing RVM environment file: '${HERE}/../../gems/ruby-2.3.0/environment'" >&2
  exit 1
fi
```

Similarly, 

```
HERE=$(dirname $(readlink -f "${0}"))
export PATH="${HERE}/../gems/ruby-2.3.0/bin:${HERE}/../gems/ruby-2.3.0@global/bin:${HERE}/../rubies/ruby-2.3.0/bin:$PATH"
export GEM_HOME='${HERE}/../gems/ruby-2.3.0'
export GEM_PATH='${HERE}/../gems/ruby-2.3.0:${HERE}/../gems/ruby-2.3.0@global'
export MY_RUBY_HOME='${HERE}/../rubies/ruby-2.3.0'
export IRBRC='${HERE}/../rubies/ruby-2.3.0/.irbrc'
unset MAGLEV_HOME
unset RBXOPT
export RUBY_VERSION='ruby-2.3.0'
```

and so on.

**Comment by Cinderhaze** [comment]
I just ran into (what I think) is this problem.  I don't have my command output here, but I tried to do `rvm install ruby-2.3.3 --binary` on osx and it failed the validation step looking for /home/travis/.rvm/$somefile

I reverted to installing from source, but it effectively means that the binary packages that are built for osx are useless for newcomers.

**Comment by pkuczynski** [comment]
Please refer to rvm-binary repo for information how to build movable ruby binaries...

**Comment by probonopd** [comment]
> Please refer to rvm-binary repo for information how to build movable ruby binaries...

Is there any reason _not_ to make this the default for all builds?

**Comment by pkuczynski** [comment]
It should be default. I think this particular build was not exactly done correctly
