### ISSUE TITLE
Windows stuck on importing gem set

### ISSUE THREAD

**Issue by dillonraphael** [rvm/rvm#3811]
I successfully installed rvm inside babun (based on Cygwin). When I get to the point of running rvm install 2.3.1 it gets stuck on importing gem set. I left it over night and still no response.

**Comment by pkuczynski** [comment]
Press enter and see it it moves forward?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
