### ISSUE TITLE
Missing cygwin32-readline package on Windows

### ISSUE THREAD

**Issue by pkuczynski** [rvm/rvm#3812]
## Description

When installing Ruby 2.3.1 on Windows with Babun, it fails due misisng `cygwin32-readline` package.

## Steps to reproduce

 1. Windows with Babun
 2. `rvm get head`
 3. `rvm install 2.3.1`

## Expected behavior

Successful install

## Actual behavior

```
[~] → pact install readline
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache
Package readline is already installed, skipping
[~] → pact install cygwin32-readline
Working directory is /setup
Mirror is http://mirrors.kernel.org/sourceware/cygwin/
setup.ini taken from the cache

Installing cygwin32-readline
Package cygwin32-readline not found or ambiguous name, exiting
[~] → rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: cygwin/unknown/i386/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for cygwin.
Installing requirements for cygwin.
Updating system.
Installing required packages: cygwin32-readline..
Error running 'requirements_cygwin_libs_install cygwin32-readline',
showing last 15 lines of /home/brandon/.rvm/log/1479233898_ruby-2.3.1/package_install_cygwin32-readline.log
++ rvm_debug '__manager: detecting administrative permissions'
++ ((  0  ))
++ return 0
++ net session
++ '[' 0 -eq 0 ']'
++ __manager_admin_mode=
++ [[ i386 == \x\8\6\_\6\4 ]]
++ __manager=setup-x86.exe
++ rvm_debug '__manager: setup-x86.exe '
++ ((  0  ))
++ return 0
++ __packages_list=cygwin32-readline
++ setup-x86.exe -q -P cygwin32-readline
/home/brandon/.rvm/scripts/functions/requirements/cygwin: line 26: setup-x86.exe: command not found
++ return 127
Requirements installation failed with status: 127.
```

**Comment by pkuczynski** [comment]
@Log1x could you please paste output of `rvm info`?

**Comment by jidrone** [comment]
I have the same error, this is the output of rvm info

system:

  system:
    uname:       "CYGWIN_NT-6.1-WOW WKS0000573569 2.6.0(0.304/5/3) 2016-08-31 14:27 i686 Cygwin"
    system:      "cygwin/unknown/i386"
    bash:        "/usr/bin/bash => GNU bash, version 4.3.46(7)-release (i686-pc-cygwin)"
    zsh:         "/usr/bin/zsh => zsh 5.1.1 (i686-pc-cygwin)"

  rvm:
    version:      "rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "7 minutes 27 seconds ago"
    path:         "/home/duartjor/.rvm"

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/home/duartjor/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/home/duartjor/.local/bin:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/1E/NomadBranch:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/WirelessCommon:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/xampp/mysql/bin:/cygdrive/c/xampp/php:/cygdrive/c/Program Files (x86)/GnuWin32/bin:/cygdrive/c/ProgramData/ComposerSetup/bin:/cygdrive/c/Ruby23-x64/bin:/cygdrive/c/Users/duartjor/.babun:/cygdrive/c/Users/duartjor/AppData/Roaming/Composer/vendor/bin:/:/home/duartjor/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by mallick7** [comment]
Hey folks,

Even i ran into similar kind of error, please help me.

step 1: rvm install 2.1.5
$ rvm install 2.1.5
Searching for binary rubies, this might take some time.
No binary rubies available for: cygwin/unknown/x86_64/ruby-2.1.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for cygwin.
Installing requirements for cygwin.
Updating system.
Installing required packages: cygwin32-readline..
Error running 'requirements_cygwin_libs_install cygwin32-readline',
showing last 15 lines of /home/smallick/.rvm/log/1481031108_ruby-2.1.5/package_install_cygwin32-readline.log
    ${__manager} -q -P "${__packages_list// /,}" || return $?
}
current path: /home/smallick
PATH=/usr/local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windo                 ws/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Ruby21-x64/bin:/home/smal                 lick/.rvm/bin
command(2): requirements_cygwin_libs_install cygwin32-readline
++ typeset __packages_list __manager
++ [[ x86_64 == \x\8\6\_\6\4 ]]
++ __manager=setup-x86_64.exe
++ rvm_debug '__manager: setup-x86_64.exe'
++ ((  0  ))
++ return 0
++ __packages_list=cygwin32-readline
++ setup-x86_64.exe -q -P cygwin32-readline
-bash: setup-x86_64.exe: command not found
++ return 127
Requirements installation failed with status: 127.

I followed your steps
$ rvm get head

$ cygcheck -l readline

post "rvm get head" neither found the cygwin32-readline in my package anywhere nor the above error for readline.

now getting a different error below with rvm install 2.3.1

$ rvm install 2.3.1
Searching for binary rubies, this might take some time.
No binary rubies available for: cygwin/unknown/x86_64/ruby-2.3.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for cygwin.
Installing requirements for cygwin.
Updating system.
Installing required packages: libcrypt-devel..
Error running 'requirements_cygwin_libs_install libcrypt-devel',
showing last 15 lines of /home/smallick/.rvm/log/1481112238_ruby-2.3.1/package_install_libcrypt-devel.log
++ rvm_debug '__manager: detecting administrative permissions'
++ ((  0  ))
++ return 0
++ net session
++ '[' 2 -eq 0 ']'
++ __manager_admin_mode=--no-admin
++ [[ x86_64 == \x\8\6\_\6\4 ]]
++ __manager=setup-x86_64.exe
++ rvm_debug '__manager: setup-x86_64.exe --no-admin'
++ ((  0  ))
++ return 0
++ __packages_list=libcrypt-devel
++ setup-x86_64.exe --no-admin -q -P libcrypt-devel
-bash: setup-x86_64.exe: command not found
++ return 127
Requirements installation failed with status: 127.

Please let me know if i missed anything.

**Comment by kiba** [comment]
Hi. RVM can't find readline, so I changed it to libreadline-devel, and it works.

Is this a valid solution for window 10 and cygwin? Or am I screwing something subtle by doing that?

**Comment by pkuczynski** [comment]
This issue has been fixed. @kiba thanks for the hint! Test it after calling `rvm get master`
