### ISSUE TITLE
Static builds fail on 2.3.0 on Trusty build on Travis-CI Intermittently 

### ISSUE THREAD

**Issue by vishrutshah** [rvm/rvm#3814]
https://github.com/Azure/autorest is using travis-ci via trusty builds to run tests for Ruby version 2.3.0. We have been using this since while but it fails intermittently while installing ruby version 2.3.0. 

Failure Build: https://travis-ci.org/Azure/autorest/builds/176475008
Success Build: https://travis-ci.org/Azure/autorest/builds/176475090
Travis-CI configuration for reference: https://github.com/Azure/autorest/blob/master/.travis.yml

As we have been facing this issue intermittently, I am not sure how to best provide you logs and reproduction steps but we'd really appreciate if you can have a quick look and guide us towards the resolution. Thanks!

**Comment by pkuczynski** [comment]
I checked couple of failed of builds and none of them failed due RVM error, so I am not sure why have you raised this issue with us?

**Comment by vishrutshah** [comment]
@pkuczynski Thanks you very much for the quick response. Could you please help me understand what did you look for in those builds that determines it's not regarding rvm. It'd help me also open the issue at right place may be on travis-ci and we can close this one. 

Thanks!

**Comment by pkuczynski** [comment]
In the build log there was no errors on `rvm use...` line. You should open it somewhere else.
