### ISSUE TITLE
Can't install binary ruby 2.3.2 on mac

### ISSUE THREAD

**Issue by meal** [rvm/rvm#3815]
## Description

Can't install binary ruby 2.3.2 on mac

## Steps to reproduce

 1. `rvm get head`
 2. `rvm install 2.3.2`

## Expected behavior

Should install binary ruby as there is one available

## Actual behavior

Built from source:

https://gist.github.com/meal/a05b4af6d1a529ffc1342febfcbab63a

## Environment info

```
ruby-2.3.2:

  system:
    uname:       "Darwin prosiak 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64"
    system:      "osx/10.12/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:         "/usr/local/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0.0)"

  rvm:
    version:      "rvm 1.27.0 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "6 minutes 1 second ago"
    path:         "/Users/meal/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.3.2p217"
    date:         "2016-11-15"
    platform:     "x86_64-darwin16"
    patchlevel:   "2016-11-15 revision 56796"
    full_version: "ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-darwin16]"

  homes:
    gem:          "/Users/meal/.rvm/gems/ruby-2.3.2"
    ruby:         "/Users/meal/.rvm/rubies/ruby-2.3.2"

  binaries:
    ruby:         "/Users/meal/.rvm/rubies/ruby-2.3.2/bin/ruby"
    irb:          "/Users/meal/.rvm/rubies/ruby-2.3.2/bin/irb"
    gem:          "/Users/meal/.rvm/rubies/ruby-2.3.2/bin/gem"
    rake:         "/Users/meal/.rvm/rubies/ruby-2.3.2/bin/rake"

  environment:
    PATH:         "/Users/meal/.rvm/gems/ruby-2.3.2/bin:/Users/meal/.rvm/gems/ruby-2.3.2@global/bin:/Users/meal/.rvm/rubies/ruby-2.3.2/bin:/Users/meal/.rvm/bin:/Users/meal/.nvm/versions/node/v6.9.1/bin:/Users/meal/gocode/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin"
    GEM_HOME:     "/Users/meal/.rvm/gems/ruby-2.3.2"
    GEM_PATH:     "/Users/meal/.rvm/gems/ruby-2.3.2:/Users/meal/.rvm/gems/ruby-2.3.2@global"
    MY_RUBY_HOME: "/Users/meal/.rvm/rubies/ruby-2.3.2"
    IRBRC:        "/Users/meal/.rvm/rubies/ruby-2.3.2/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by pkuczynski** [comment]
Are you doing this on travis build machine? Then you would have to report the problem to Travis, as we do not have binary build for macOS Sierra (https://rvm_io.global.ssl.fastly.net/binaries/osx/10.12/x86_64/)

**Comment by meal** [comment]
No, I'm running this on my local machine. Why is rvm trying to fetch binary file from travis in this case?

**Comment by andrewjkerr** [comment]
There seems to a hardcoded path involved somewhere as I got a similar error message:
> Libraries missing for ruby-2.3.3: /Users/travis/.rvm/rubies/ruby-2.3.3/lib/libruby.2.3.0.dylib. Refer to your system manual for installing libraries

FWIW, 2.3.3 installed for me after compiling, but downloading the binary did not work because of the above error.

**Comment by emakryo** [comment]
This happens with 2.4.0-rc1. This issue should be reopened, right?

**Comment by pkuczynski** [comment]
This is fixed in master: `rvm get master`

**Comment by lydia-gu** [comment]
Thanks. Works for me. My Mac version is Sierra ver.10.12.6

```
$ rvm get master
$ rvm install 2.3.2
$ rvm use 2.3.2
```

**Comment by aamarill** [comment]
@lydia-gu I was getting the same error! 
`Patch 'random_c_using_NR_prefix' not found.`

But `rvm get master` solved my issue as well. Many thanks! 👏

**Comment by juliettech13** [comment]
Same error, `rvm get master` fixed it! Thanks!!
