### ISSUE TITLE
Something went wrong during Homebrew installation...failed with status: 1

### ISSUE THREAD

**Issue by madhuaddanki** [rvm/rvm#3827]
I am trying to setup ruby on rails  in my macMini I am getting error like this

commands I run :

 1.curl -L get.rvm.io | bash -s stable
 2.source ~/.rvm/scripts/rvm
 3.rvm requirements
 4.ruby: /usr/bin/apt-get install build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion

error:

Something went wrong during Homebrew installation,
can not find 'brew' command, please report a bug: https://bit.ly/rvm-issues
Requirements installation failed with status: 1.

**Comment by pkuczynski** [comment]
Can you post here output of `rvm info`?

**Comment by madhuaddanki** [comment]
1. curl -L get.rvm.io | bash -s stable_

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   184  100   184    0     0    206      0 --:--:-- --:--:-- --:--:--   206
100 22921  100 22921    0     0   9254      0  0:00:02  0:00:02 --:--:-- 24384
Downloading https://github.com/rvm/rvm/archive/1.27.0.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.27.0/1.27.0.tar.gz.asc',
but no GPG software exists to validate it, skipping.
Upgrading the RVM installation in /Users/wifibees/.rvm/
    RVM PATH line found in /Users/wifibees/.mkshrc /Users/wifibees/.profile /Users/wifibees/.bashrc /Users/wifibees/.zshrc.
    RVM sourcing line found in /Users/wifibees/.profile /Users/wifibees/.bash_profile /Users/wifibees/.zlogin.
Upgrade of RVM in /Users/wifibees/.rvm/ is complete.
# wifibees,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.
In case of problems: https://rvm.io/help and https://twitter.com/rvm_io
Upgrade Notes:
  * No new notes to display.

2. source ~/.rvm/scripts/rvm
3. rvm requirements

Checking requirements for osx.
About to install Homebrew, press `Enter` for default installation in `/usr/local`,
type new path if you wish custom Homebrew installation (the path needs to be writable for user)
: 

4. ruby: /usr/bin/apt-get install build-essential openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev automake libtool bison subversion


  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0     71      0 --:--:--  0:00:01 --:--:--    71
100   139    0   139    0     0     65      0 --:--:--  0:00:02 --:--:--    65
100  194k  100  194k    0     0  25320      0  0:00:07  0:00:07 --:--:-- 49740

Something went wrong during Homebrew installation,
can not find 'brew' command, please report a bug: https://bit.ly/rvm-issues
Requirements installation failed with status: 1.

**Comment by pkuczynski** [comment]
I need the output of `rvm info`. When raising the issue you probably noticed the desired format for creating new tickets? Please follow all required steps described there. I am closing this one, as I can't read much out of it and your further comments are useless...

**Comment by amruthas04** [comment]
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/14.3/x86_64/ruby-2.7.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
About to install Homebrew in the default location `/usr/local`.

It is possible to select a custom location, however it is not recommended and some things might not work.
You should do it only if you do not have write rights to `/usr/local`.

Press ENTER to install Homebrew in the default location `/usr/local`
or type a custom path (needs to be writable for the current user)
: 
curl: (22) The requested URL returned error: 404
Something went wrong during Homebrew installation,
can not find 'brew' command, please report a bug: https://github.com/rvm/rvm/issues
Requirements installation failed with status: 1.
