### ISSUE TITLE
certificate verify failed when installing Rails

### ISSUE THREAD

**Issue by JohnMerlino2** [rvm/rvm#3829]
For the first time, I am trying ruby-2.3.0. I installed it from rvm. After installation, I try to install Rails:

$ rvm-prompt
ruby-2.3.0@mygemset

$ rvm osx-ssl-certs update all
Updating certificates for /etc/openssl/cert.pem: Updating certificates in '/etc/openssl/cert.pem'.
Updated.
Updating certificates for /usr/local/etc/openssl/cert.pem: Already up to date.

$ rvm rubygems latest
Installed rubygems 2.5.1 is newer than 2.4.8 provided with installed ruby, skipping installation, use --force to force installation.

$ gem install rails
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

I am able to access the url https://api.rubygems.org/specs.4.8.gz on the browser without any issues. So why is this happening? I am on Mac OSX 10.9.5

**Comment by JohnMerlino2** [comment]
When I installed ruby 2.2 before installing ruby 2.3, then the error does not occur. Is there any explanation for this?

**Comment by pkuczynski** [comment]
We update ruby gems dependency. Can you please retry with `rvm get head`?

**Comment by pkuczynski** [comment]
Closing due lack of feedback from the reporter
