### ISSUE TITLE
Integrating RVM with Bash on Ubuntu on Windows 10

### ISSUE THREAD

**Issue by ikuzoma** [rvm/rvm#3830]
The following instructions in https://rvm.io/integration/gnome-terminal does not work for Bash on Ubuntu on Windows 10 due to lack of "Edit ▸ Profile Preferences" in ui terminal. 

Screenshot of ui terminal: http://joxi.ru/EA49dWEhDbRkNr

Command of terminal: 'source ~/.rvm/scripts/rvm' does not work permanently

Is there any commands of terminal to input to check the checkbox on 'Run command as login shell'?

**Comment by pkuczynski** [comment]
Thise instructions are only required if running Gnome terminal due the bug in Gnome. Please try installing our dedicated ubuntu package: https://github.com/rvm/ubuntu_rvm

**Comment by ikuzoma** [comment]
Maybe it will help to understand my problem - I used this instructions to use bash on Ubuntu on Windows: https://gorails.com/setup/windows/10
I do not have a problem with installing rvm - I have a problem with...
1. I open the bash (terminal) and install rvm
2. then I input the command 'source ~/.rvm/scripts/rvm' to make rvm as a function
3. I checked the result with: type rvm | head -n 1
4. And I have a respond: rvm is a function
5. Everything is perfect - everything works
6. then I close the bash (terminal) window
7. then I open the bash (terminal) window
8. I try to check again: type rvm | head -n 1
9. But the result of respond is: rvm is /home/master/.rvm/bin/rvm
So, rvm is not a function
And I must again input the command: 'source ~/.rvm/scripts/rvm' to make rvm as a function

I don`t have another bash (terminal) on my windows 10 and this bash (terminal) does not have Profile Preferences, so I can`t edit profile to check the checkbox 'Run command as login shell'

Maybe this question is not to you, but to Microsoft
Thank you, anyway

**Comment by waglebr** [comment]
@ikuzoma I had the same issue, but it's actually very simple to solve, you just need to edit the Bash shortcut on Windows: 

1. Right click the Bash shortcut and click in "Properties"
2. In the field "Target", add "--login" to the end of the path, so it should become something like this "C:\Windows\System32\bash.exe ~ --login"
3. Click "Ok" and that's it!

Next time you open the Bash it will be the login shell. :D

**Comment by ikuzoma** [comment]
Cool, but I do not have these properties on my Bash as you told.
Image of my properties: https://i.stack.imgur.com/7HPM2.png

**Comment by waglebr** [comment]
Hi Illia,

I really mean the properties of the shortcut that you use to open Bash:
http://imgur.com/a/Q803o and http://imgur.com/a/VJV2q

Hope it helps, cheers!
Wagle

**Comment by ikuzoma** [comment]
It works. Thanks a lot for your help.

**Comment by Scotchester** [comment]
Thanks, @waglebr. Your post helped me out tonight!

**Comment by waglebr** [comment]
Glad to help, @Scotchester! ;)

**Comment by waglebr** [comment]
Glad to help, @Scotchester! ;)

**Comment by pkuczynski** [comment]
Added a note to the documentation: https://github.com/rvm/rvm-site/pull/304

**Comment by Scotchester** [comment]
Looks good; thanks @pkuczynski!

**Comment by nyoman** [comment]
SUPER! WAGLEBR It works for me. Thanks
