### ISSUE TITLE
 rvm install <anyruby> fails with configure: error: cannot run C compiled programs. 

### ISSUE THREAD

**Issue by mices** [rvm/rvm#3843]
I tried installing build-essential, g++ now getting this error from ~/.rvm/log/configure.log

[2016-12-17 14:17:50] ./configure
current path: /home/myusername/.rvm/src/ruby-2.3.3
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/myusername/.rvm/bin
command(4): ./configure --prefix=/home/myusername/.rvm/rubies/ruby-2.3.3 --disable-install-doc --enable-shared
checking for ruby... false
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... configure: error: in `/home/myusername/.rvm/src/ruby-2.3.3':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by pkuczynski** [comment]
First of all, could you please follow our requirements for raising new issues? This helps a lot! I am closing this one, so feel free to reopen with a proper description and requested gists.
