### ISSUE TITLE
`rvm use` fails on macOS when invoked from inside shell script 

### ISSUE THREAD

**Issue by AndrewSB** [rvm/rvm#3845]
## Description
I've written a script that tries to install `rvm` on `macOS` if the machine doesn't already have it. You can see the contents of the script [here](https://github.com/AndrewSB/dotfiles/blob/871d1e2724805b975006d9f6af2063bb96b0ae05/machine-setup-functions.sh#L65). The selected line is where the script errors out.

The error I get is:
```
RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.

/Users/asb/.rvm/bin/rvm: line 66: shell_session_update: command not found
```

I believe the problem is that I'm trying to execute `rvm use` from inside a shell script instead of directly entering in the command from a terminal? Because `rvm use` succeeds if directly entered in instead

## Steps to reproduce

 1. Be on macOS 10.12.1, but this probably repros on other versions as well
 2. Clone GitHub.com/AndrewSB/dotfiles
 3. execute `./ensure_machine_setup.sh` in Terminal.app

## Expected behavior

`rvm` installs the latest ruby

## Actual behavior

* [script output](https://gist.github.com/AndrewSB/730189c9db9ac66380be8b0af4f5be6d)
* [script output with `--trace` enabled](https://gist.github.com/AndrewSB/4fdfce3f0e490ce114076bf09beced12)

## Environment info

```
system:

  system:
    uname:       "Darwin Andrews-MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Wed Oct 19 20:31:56 PDT 2016; root:xnu-3789.21.4~4/RELEASE_X86_64 x86_64"
    system:      "osx/10.12/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:         "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"

  rvm:
    version:      "rvm 1.28.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "7 minutes 52 seconds ago"
    path:         "/Users/asb/.rvm"

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/Users/asb/go/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/asb/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by mpapis** [comment]
looks like you are sourcing wrong file, https://gist.github.com/AndrewSB/4fdfce3f0e490ce114076bf09beced12#file-rvm-use-output-L100 - it tells that the sourcing did not include RVM, try:
```bash
source $HOME/.rvm/scripts/rvm
```

**Comment by AndrewSB** [comment]
@mpapis I'll try that and see if it changes anything.

FYI: my `$HOME/.profile` is:
```
➜  ~ cat .profile

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
```

I'll try running the script on a machine without rvm and update you. Thanks!

**Comment by seanbrecke** [comment]
@mpapis: just tried running the command on a new machine. 
`rvm` did install successfully, but since the script no longer `source`s my `~/.profile` (see https://github.com/AndrewSB/dotfiles/commit/861bee86fd3c6c862a6ee72a3bea4567960d5582). I now get output saying
```
./machine-setup-functions.sh: line 64: rvm: command not found
```

If I `source ~/.profile` in the same shell, and try running the script again, I get the original issue
```
RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.
```

**Comment by mpapis** [comment]
try removing the backquotes from line 64:
```diff
- `rvm use ruby --install --default`
+ rvm use ruby --install --default
```

**Comment by seanbrecke** [comment]
Made the change and got the same output
```
RVM is not a function, selecting rubies with 'rvm use ...' will not work.

You need to change your terminal emulator preferences to allow login shell.
Sometimes it is required to use `/bin/bash --login` as the command.
Please visit https://rvm.io/integration/gnome-terminal/ for an example.
```

**Comment by mpapis** [comment]
in what shell is it ran? rvm would prevent being sourced in shells other then bash/zsh, expect problems with sh and bash in sh mode

**Comment by AndrewSB** [comment]
It's been run in both bash & zsh (I'm on zsh, @seanbrecke is on bash) on
the latest macOS. It's invoked by running `./script-that-calls-rvm`

**Comment by mpapis** [comment]
here it is <https://github.com/AndrewSB/dotfiles/blob/871d1e2724805b975006d9f6af2063bb96b0ae05/ensure-machine-setup.sh#L1>:
```bash
#!/bin/sh
```
change it to bash and it should be better

**Comment by AndrewSB** [comment]
Just tried that, I'll run it on a new machine later today. Thank you so
much for taking a look😊

**Comment by AndrewSB** [comment]
@mpapis that did end up working 😄
