### ISSUE TITLE
RVM incorrectly tries to install llvm 3.5 when trying to install Rubinius 3

### ISSUE THREAD

**Issue by abnud1** [rvm/rvm#3848]
## Description

I'm using Arch linux and when issueing `rvm install rbx` rvm then tries to install llvm35 and clang35, well this fails because I have llvm package installed but this is not the issue.  

I installed llvm35 and clang35 manually and reissued the command, after git clone finishes I get an error in executing ./configure, the message says it clearly : only llvm 3.6+ is supported by rubinius 3.  

I remove llvm35 and clang35 and reinstall llvm and clang packages but rvm keeps trying to install llvm35 even though it won't work with rubinius 3. 

## Steps to reproduce

 1. rvm install rbx
 
 

## Expected behavior

It should continue on building rubinius without trying to install llvm35 nor clang35 and build successfully .

## Actual behavior

It errors with conflicting packages and even If I install llvm35 and clang35 manually then rubinius won't build.

* [command](https://gist.github.com/abnud1/ae852ee5447f45a718a6bfca64b1504e)
* [config.log](https://gist.github.com/abnud1/7f991d9daf23d9295e44d39051801acc) - only for issues with `install`

## Environment info

ruby-2.3.3:

  system:
    uname:       "Linux abd 4.8.15-2-ck-broadwell #1 SMP PREEMPT Sat Dec 17 11:40:02 EST 2016 x86_64 GNU/Linux"
    system:      "arch/libc-2.24/x86_64"
    bash:        "/usr/bin/bash => GNU bash, version 4.4.5(1)-release (x86_64-unknown-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.28.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "28 minutes 47 seconds ago"
    path:         "/home/abd/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.3.3p222"
    date:         "2016-11-21"
    platform:     "x86_64-linux"
    patchlevel:   "2016-11-21 revision 56859"
    full_version: "ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-linux]"

  homes:
    gem:          "/home/abd/.rvm/gems/ruby-2.3.3"
    ruby:         "/home/abd/.rvm/rubies/ruby-2.3.3"

  binaries:
    ruby:         "/home/abd/.rvm/rubies/ruby-2.3.3/bin/ruby"
    irb:          "/home/abd/.rvm/rubies/ruby-2.3.3/bin/irb"
    gem:          "/home/abd/.rvm/rubies/ruby-2.3.3/bin/gem"
    rake:         "/home/abd/.rvm/gems/ruby-2.3.3/bin/rake"

  environment:
    PATH:         "/home/abd/.rvm/gems/ruby-2.3.3/bin:/home/abd/.rvm/gems/ruby-2.3.3@global/bin:/home/abd/.rvm/rubies/ruby-2.3.3/bin:/home/abd/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/opt/mpich/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/abd/.cabal/bin"
    GEM_HOME:     "/home/abd/.rvm/gems/ruby-2.3.3"
    GEM_PATH:     "/home/abd/.rvm/gems/ruby-2.3.3:/home/abd/.rvm/gems/ruby-2.3.3@global"
    MY_RUBY_HOME: "/home/abd/.rvm/rubies/ruby-2.3.3"
    IRBRC:        "/home/abd/.rvm/rubies/ruby-2.3.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by pkuczynski** [comment]
@abnud1 I fixed the issue and RVM will require `llvm`, `llvm-libs` and `clang` for Rubinius 3.x, and at respective *35 packages for Rubinius 2.x.

However, I would like to implement a feature, where RVM checks if llvm35 is not installed when trying to install rbx-3.x - as llvm and llvm35 conflict and would cause build fail. See some more details in #3497. Would you like to help me with testing?
