### ISSUE TITLE
rvm get stable --auto-dotfile fails

### ISSUE THREAD

**Issue by dimidd** [rvm/rvm#3853]
When running `rvm get stable --auto-dotfile` I suddenly get the usage message for `rvm-installer`.

    Downloading https://get.rvm.io
    Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
    Verifying /home/centos/.rvm/archives/rvm-installer.asc
    gpg: Signature made Wed 02 Nov 2016 09:59:26 PM IST using RSA key ID BF04FF17
    gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
    gpg: WARNING: This key is not certified with a trusted signature!
    gpg:          There is no indication that the signature belongs to the owner.
    [..]
    Usage
    
      rvm-installer [options] [action]

I'm using version 1.28.0.

**Comment by pkuczynski** [comment]
Interesting :) I confirm this bug exists. Will have a look at it...

**Comment by pkuczynski** [comment]
Ok, problem solved. Try with `--auto-dotfiles` with "s" at the end :)
