### ISSUE TITLE
Ruby 2.3.x and older are not compatible with OpenSSL 1.1.x on Debian

### ISSUE THREAD

**Issue by shell-permission** [rvm/rvm#3862]
Hi,
I have the following problem with installing Ruby 2.3.3

``
root@kali:~#rvm install 2.3.3 Searching for binary rubies, this might take some time. No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.3.3. Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies. Checking requirements for debian. Installing requirements for debian. Updating system. Installing required packages: libreadline6-dev.. Requirements installation successful. Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)... ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection... ######################################################################## 100.0% ruby-2.3.3 - #extracting ruby-2.3.3 to /usr/local/rvm/src/ruby-2.3.3.... ruby-2.3.3 - #configuring.......................................................... ruby-2.3.3 - #post-configuration.. ruby-2.3.3 - #compiling.......................................................................... Error running '__rvm_make -j2', showing last 15 lines of /usr/local/rvm/log/1482942641_ruby-2.3.3/make.log memset(ctx, 0, sizeof(HMAC_CTX)); ^~~~~~~~ Makefile:301: recipe for target 'openssl_missing.o' failed make[2]: *** [openssl_missing.o] Error 1 make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/openssl' exts.mk:210: recipe for target 'ext/openssl/all' failed make[1]: *** [ext/openssl/all] Error 2 make[1]: *** Waiting for unfinished jobs.... installing default nkf libraries linking shared-object nkf.so make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3/ext/nkf' make[1]: Leaving directory '/usr/local/rvm/src/ruby-2.3.3' uncommon.mk:203: recipe for target 'build-ext' failed make: *** [build-ext] Error 2 ++ return 2 There has been an error while running make. Halting the installation.
``

root@kali:~# rvm info system
```
  system:
    uname:       "Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux"
    system:      "debian/Kali_Linux_Rolling/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)"
    zsh:         "/usr/bin/zsh => zsh 5.2 (x86_64-debian-linux-gnu)"
```

root@kali:~# cat /proc/cpuinfo
```
processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x6000626
cpu MHz		: 1996.275
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch vmmcall arat
bugs		: fxsave_leak sysret_ss_attrs
bogomips	: 3992.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 22
model		: 48
model name	: AMD A8-6410 APU with AMD Radeon R5 Graphics
stepping	: 1
microcode	: 0x6000626
cpu MHz		: 1996.275
cache size	: 2048 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm rep_good nopl extd_apicid eagerfpu pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch vmmcall arat
bugs		: fxsave_leak sysret_ss_attrs
bogomips	: 3992.55
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:
```

**Comment by pkuczynski** [comment]
Looks like an OpenSSL issue. Could you please gist `/usr/local/rvm/log/1482942641_ruby-2.3.3/make.log`

**Comment by allavena** [comment]
I'm having the same issue. Using Debian testing.  OpenSsl fails to compile. 

See below or gist: https://gist.github.com/allavena/4010ccbfef638fb4f6be0e30bed239f9 for the end of make.log


linking shared-object mathn/rational.so
make[2]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3/ext/mathn/rational'
make[2]: Entering directory '/home/andre/.rvm/src/ruby-2.3.3/ext/nkf'
compiling nkf.c
In file included from nkf.c:62:0:
nkf-utf8/nkf.c: In function ‘module_connection’:
nkf-utf8/nkf.c:5710:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (nkf_enc_unicode_p(output_encoding))
     ^~
nkf-utf8/nkf.c:5713:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  if (x0201_f == NKF_UNSPECIFIED) {
  ^~
linking shared-object json/ext/parser.so
linking shared-object date_core.so
make[2]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3/ext/json/parser'
make[2]: Entering directory '/home/andre/.rvm/src/ruby-2.3.3/ext/objspace'
compiling object_tracing.c
make[2]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3/ext/date'
make[2]: Entering directory '/home/andre/.rvm/src/ruby-2.3.3/ext/openssl'
compiling ossl_ocsp.c
In file included from ossl.h:57:0,
                 from ossl_ocsp.c:11:
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."
  ^~~~~
In file included from ossl.h:222:0,
                 from ossl_ocsp.c:11:
openssl_missing.h:78:35: error: macro "EVP_MD_CTX_create" passed 1 arguments, but takes just 0
 EVP_MD_CTX *EVP_MD_CTX_create(void);
                                   ^
In file included from /usr/include/openssl/x509.h:23:0,
                 from /usr/include/openssl/x509v3.h:14,
                 from ossl.h:58,
                 from ossl_ocsp.c:11:
openssl_missing.h:82:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
 void EVP_MD_CTX_init(EVP_MD_CTX *ctx);
      ^
openssl_missing.h:90:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
 void EVP_MD_CTX_destroy(EVP_MD_CTX *ctx);
      ^
ossl_ocsp.c: In function ‘ossl_ocspbres_add_status’:
ossl_ocsp.c:716:35: error: dereferencing pointer to incomplete type ‘OCSP_SINGLERESP {aka struct ocsp_single_response_st}’
  sk_X509_EXTENSION_pop_free(single->singleExtensions, X509_EXTENSION_free);
                                   ^~
ossl_ocsp.c: In function ‘ossl_ocspcid_get_serial’:
ossl_ocsp.c:974:33: error: dereferencing pointer to incomplete type ‘OCSP_CERTID {aka struct ocsp_cert_id_st}’
     return asn1integer_to_num(id->serialNumber);
                                 ^~
ossl_ocsp.c:975:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:301: recipe for target 'ossl_ocsp.o' failed
make[2]: *** [ossl_ocsp.o] Error 1
make[2]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3/ext/openssl'
exts.mk:210: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
installing default nkf libraries
compiling objspace_dump.c
compiling objspace.c
linking shared-object json/ext/generator.so
make[2]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3/ext/json/generator'
linking shared-object objspace.so
make[2]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3/ext/objspace'
linking shared-object nkf.so
make[2]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3/ext/nkf'
make[1]: Leaving directory '/home/andre/.rvm/src/ruby-2.3.3'
uncommon.mk:203: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2

**Comment by mpapis** [comment]
could you check if `ruby-2.4.0` and `ruby-head` build for you?

**Comment by pkuczynski** [comment]
This is most likely caused by latest openssl 1.1.0, which is incompatible with ruby 2.3.x and older (not sure about 2.4). @allavena @shell-permission could you please check which version of openssl you have and check if you can install ruby 2.4.0?

**Comment by agimenez** [comment]
This patch worked for me as a workaround. Newer Debian versions still keep the old 1.0 libssl version:

```diff
--- /home/agimenez/.rvm/scripts/functions/requirements/debian.org	2017-02-04 16:50:19.294582865 +0100
+++ /home/agimenez/.rvm/scripts/functions/requirements/debian	2017-02-04 16:50:44.934930888 +0100
@@ -124,7 +124,7 @@
 {
   requirements_check "$@" \
     make libc6-dev patch openssl ca-certificates libreadline6 \
-    libreadline6-dev curl zlib1g zlib1g-dev libssl-dev libyaml-dev \
+    libreadline6-dev curl zlib1g zlib1g-dev libssl1.0-dev libyaml-dev \
     libsqlite3-dev sqlite3 autoconf libgmp-dev \
     libgdbm-dev libncurses5-dev automake libtool bison pkg-config libffi-dev
 }
```

**Comment by allavena** [comment]
Sorry, I missed the earlier question.

I have openssl 1.1.0c-2 installed (current in debian testing) - No trace of
openssl 1.0 installed (although libssl1.0-dev is available)

Ruby 2.4 builds and works fine.  (This was ruby-2.4.0-preview3).


Thanks
André

**Comment by pkuczynski** [comment]
Note: `libssl1.0-dev` is available starting from Debian Stretch (testing)

**Comment by pkuczynski** [comment]
I prepared a patch for this issue. @shell-permission @allavena could you please test it:

```
rvm get branch /bugfix/3862-openssl11-debian
rvm install ruby-2.3.3
```

**Comment by allavena** [comment]
The patch worked for me. I was able to install ruby-2.3.3 from that branch.

Even better, I earlier had puma-3.6 failing during compile (on open-ssl
related issue). THis time, it installed fine (though I didn't check, there
is a possibility I could have had a version already compiled of the gem
running around?)

Thanks for the patch.

André

**Comment by mame82** [comment]
I have still issues compiling 2.3.3 on Kali Linux, which seam to be caused by openssl:

```
root@kali:~/metasploit-framework# rvm install ruby-2.3.3
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system.
Installing required packages: bash, curl, patch, bzip2, gawk, libssl-dev, make, libc6-dev, patch, openssl, libreadline6, libreadline6-dev, curl, zlib1g, zlib1g-dev, libyaml-dev, libsqlite3-dev, sqlite3, libgmp-dev, libgdbm-dev, libncurses5-dev, bison, pkg-config, libffi-dev, libgmp-dev, libreadline6-dev....
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.7M  100 13.7M    0     0   341k      0  0:00:41  0:00:41 --:--:--  394k
ruby-2.3.3 - #extracting ruby-2.3.3 to /usr/local/rvm/src/ruby-2.3.3....
ruby-2.3.3 - #configuring..........................................................
ruby-2.3.3 - #post-configuration..
ruby-2.3.3 - #compiling.........................................................................
Error running '__rvm_make -j4',
showing last 15 lines of /usr/local/rvm/log/1486632154_ruby-2.3.3/make.log
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet...
installing default nkf libraries
compiling date_parse.c
installing default date_core libraries
compiling object_tracing.c
linking shared-object objspace.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/objspace“ wird verlassen
linking shared-object date_core.so
linking shared-object nkf.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/date“ wird verlassen
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/nkf“ wird verlassen
make[1]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3“ wird verlassen
uncommon.mk:203: die Regel für Ziel „build-ext“ scheiterte
make: *** [build-ext] Fehler 2
++ return 2
There has been an error while running make. Halting the installation.

```

Relevant output in make.log
```

root@kali:~/metasploit-framework# tail -n 80  /usr/local/rvm/log/1486632154_ruby-2.3.3/make.log
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/mathn/complex“ wird betreten
compiling complex.c
linking shared-object mathn/complex.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/mathn/complex“ wird verlassen
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/mathn/rational“ wird betreten
compiling rational.c
linking shared-object mathn/rational.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/mathn/rational“ wird verlassen
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/nkf“ wird betreten
compiling nkf.c
In file included from nkf.c:62:0:
nkf-utf8/nkf.c: In function ‘module_connection’:
nkf-utf8/nkf.c:5710:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (nkf_enc_unicode_p(output_encoding))
     ^~
nkf-utf8/nkf.c:5713:2: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
  if (x0201_f == NKF_UNSPECIFIED) {
  ^~
linking shared-object json/ext/parser.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/json/parser“ wird verlassen
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/objspace“ wird betreten
compiling objspace_dump.c
compiling objspace.c
linking shared-object json/ext/generator.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/json/generator“ wird verlassen
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/openssl“ wird betreten
compiling ossl_pkey_rsa.c
In file included from ossl.h:57:0,
                 from ossl_pkey_rsa.c:12:
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."
  ^~~~~
In file included from ossl.h:222:0,
                 from ossl_pkey_rsa.c:12:
openssl_missing.h:78:35: error: macro "EVP_MD_CTX_create" passed 1 arguments, but takes just 0
 EVP_MD_CTX *EVP_MD_CTX_create(void);
                                   ^
In file included from /usr/include/openssl/x509.h:23:0,
                 from /usr/include/openssl/x509v3.h:14,
                 from ossl.h:58,
                 from ossl_pkey_rsa.c:12:
openssl_missing.h:82:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
 void EVP_MD_CTX_init(EVP_MD_CTX *ctx);
      ^
openssl_missing.h:90:6: error: expected declaration specifiers or ‘...’ before ‘(’ token
 void EVP_MD_CTX_destroy(EVP_MD_CTX *ctx);
      ^
ossl_pkey_rsa.c: In function ‘ossl_rsa_new’:
ossl_pkey_rsa.c:65:24: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
  if (EVP_PKEY_type(pkey->type) != EVP_PKEY_RSA) {
                        ^~
ossl_pkey_rsa.c: In function ‘rsa_generate’:
ossl_pkey_rsa.c:103:14: error: storage size of ‘cb’ isn’t known
     BN_GENCB cb;
              ^~
ossl_pkey_rsa.c:103:14: warning: unused variable ‘cb’ [-Wunused-variable]
ossl_pkey_rsa.c: In function ‘ossl_rsa_is_private’:
ossl_pkey_rsa.c:291:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:301: die Regel für Ziel „ossl_pkey_rsa.o“ scheiterte
make[2]: *** [ossl_pkey_rsa.o] Fehler 1
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/openssl“ wird verlassen
exts.mk:210: die Regel für Ziel „ext/openssl/all“ scheiterte
make[1]: *** [ext/openssl/all] Fehler 2
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet...
installing default nkf libraries
compiling date_parse.c
installing default date_core libraries
compiling object_tracing.c
linking shared-object objspace.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/objspace“ wird verlassen
linking shared-object date_core.so
linking shared-object nkf.so
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/date“ wird verlassen
make[2]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3/ext/nkf“ wird verlassen
make[1]: Verzeichnis „/usr/local/rvm/src/ruby-2.3.3“ wird verlassen
uncommon.mk:203: die Regel für Ziel „build-ext“ scheiterte
make: *** [build-ext] Fehler 2
++ return 2

```

As the fixing branch is merged back into master, I thought I don't have to do additional steps beside running ``rvm install 2.3.3`` or should I?

**Comment by mame82** [comment]
Here's the system info with installed ruby-2.4.0, but 2.3.3 is needed to get metasploit working:

```
root@kali:~/metasploit-framework# rvm info system

ruby-2.4.0:

  system:
    uname:       "Linux kali 4.9.0-kali1-amd64 #1 SMP Debian 4.9.6-3kali2 (2017-01-30) x86_64 GNU/Linux"
    system:      "debian/Kali_Linux_Rolling/x86_64"
    bash:        "/bin/bash => GNU bash, Version 4.4.11(1)-release (x86_64-pc-linux-gnu)"
    zsh:         "/bin/zsh => zsh 5.3.1 (x86_64-debian-linux-gnu)"

```

**Comment by pkuczynski** [comment]
@mame82 please create a separate ticket for Kali Linux not being able to install ruby 2.3.3. I think I know what might be the problem, but I want to keep as a separate task.

**Comment by bermannoah** [comment]
@pkuczynski do you know if this fix ever got merged? Having the same issue on my machine. Happy to create a ticket if the original poster didn't. Thanks!

**Comment by ninp0** [comment]
+1

**Comment by ShamoX** [comment]
+1

**Comment by pkuczynski** [comment]
Yes, this got merged, but does not help in Kali case. I am working on a fix. Please follow #3958

**Comment by bermannoah** [comment]
@pkuczynski thanks! Will do.

**Comment by finkbg** [comment]
rvm get branch /bugfix/3862-openssl11-debian results in 

> Could not download 'https://github.com/rvm/rvm/archive/bugfix/3862-openssl11-debian.tar.gz'.
>   curl returned status '22'.

**Comment by pkuczynski** [comment]
This is already merged to master. Run ‘rvm get master’

**Comment by cheald** [comment]
This same class of error appears to exist on Ubuntu 18.04. I've managed to install Ruby 2.2 and 2.3 by modifying the `ubuntu` requirements script with:

```
requirements_ubuntu_define_libssl()
{
  case "$1" in
    (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*)
        requirements_check libssl1.0-dev
        ;;
    (*)
        requirements_check libssl-dev
        ;;
  esac
}```

**Comment by pkuczynski** [comment]
@cheald so you mean that for older versions of ruby we should install an older version of libssl, right?

**Comment by pkuczynski** [comment]
Looking at https://packages.ubuntu.com/search?keywords=libssl1.0-dev&searchon=names&suite=all&section=all it seems that this package was introduced in ubuntu artful, which is version 17.10+ (https://wiki.ubuntu.com/Releases)

**Comment by cheald** [comment]
@pkuczynski Correct, similar to how it's done in the Debian deps. It looks like it'll only be needed as far back as Artful, as you've found.

**Comment by pkuczynski** [comment]
Fixed in https://github.com/rvm/rvm/pull/4326. Would you like to test it @cheald?

**Comment by cheald** [comment]
I just did another fresh 17.10 install, and Ruby 2.2.5 installed without a hitch. Thank you!

**Comment by dionysius** [comment]
Confirm working on Ubuntu 18.04 after explicitly running `rvm get master`

```
Checking requirements for ubuntu.
Removing undesired packages: libssl-dev....
Installing requirements for ubuntu.
Updating system..
Installing required packages: libssl1.0-dev....
Requirements installation successful.
```

**Comment by MiloudaB** [comment]
Have the same issue for ubuntu 20.04, ruby 2.7.* build
