### ISSUE TITLE
Can't install Ruby 2.3.0 on OS X 10.11.6

### ISSUE THREAD

**Issue by d-kang** [rvm/rvm#3863]
I'm running into an install issue for Ruby 2.3.3 and can't discern what exactly the issue is. 

I've searched and searched google and have attempted to fix it but haven't been able to figure it out. Any help is greatly appreciated. 

This the output of the error:

$ rvm install ruby-2.3
Searching for binary rubies, this might take some time.
Found remote file https://rubies.travis-ci.org/osx/10.11/x86_64/ruby-2.3.3.tar.bz2
Checking requirements for osx_brew.
Error: Can't create update lock in /usr/local/var/homebrew/locks!
Fix permissions by running:
  sudo chown -R $(whoami) /usr/local/var/homebrew
Error: Can't create update lock in /usr/local/var/homebrew/locks!
Fix permissions by running:
  sudo chown -R $(whoami) /usr/local/var/homebrew
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
ruby-2.3.3 - #configure
ruby-2.3.3 - #download
ruby-2.3.3 - #validate archive
ruby-2.3.3 - #extract
ruby-2.3.3 - #validate binary
Libraries missing for ruby-2.3.3: /Users/travis/.rvm/rubies/ruby-2.3.3/lib/libruby.2.3.0.dylib,/usr/local/opt/gdbm/lib/libgdbm.4.dylib. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, trying to compile.
Checking requirements for osx_brew.
Error: Can't create update lock in /usr/local/var/homebrew/locks!
Fix permissions by running:
  sudo chown -R $(whoami) /usr/local/var/homebrew
Error: Can't create update lock in /usr/local/var/homebrew/locks!
Fix permissions by running:
  sudo chown -R $(whoami) /usr/local/var/homebrew
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/dk/.rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
ruby-2.3.3 - #extracting ruby-2.3.3 to /Users/dk/.rvm/src/ruby-2.3.3....
ruby-2.3.3 - #configuring......................................................|
ruby-2.3.3 - #post-configuration.
ruby-2.3.3 - #compiling...........
Error running '__rvm_make -j 1',
showing last 15 lines of /Users/dk/.rvm/log/1483417164_ruby-2.3.3/make.log
compiling ./missing/setproctitle.c
compiling dmyenc.c
linking miniruby
config.status: creating ruby-runner.c
generating encdb.h
dyld: lazy symbol binding failed: Symbol not found: _clock_gettime
  Referenced from: /Users/dk/.rvm/src/ruby-2.3.3/./miniruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/dk/.rvm/src/ruby-2.3.3/./miniruby (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib

make: *** [encdb.h] Trace/BPT trap: 5
++ return 2
There has been an error while running make. Halting the installation.

**Comment by d-kang** [comment]
Nevermind, I was able to install ruby 2.3.3 and 2.4.0 using rbenv instead of rvm. It required me to delete all traces of rvm. After the switch I was finally able to install ruby with rbenv after entering 'xcode-select --install' which seems to have been the actual reason I wasnt able to install ruby in the first place

**Comment by pkuczynski** [comment]
Looking at the errors it seems that you had an issue with homebrew:

```
Error: Can't create update lock in /usr/local/var/homebrew/locks!
```

This did not allowed us to install relevant libraries.

**Comment by musashinm** [comment]
I was facing the same problem... Just run `xcode-select --install` and I was able to install Ruby 2.3.3 with RVM. ;)
