### ISSUE TITLE
Error running Scenario: <Scenario>: Cucumber Gem isn't installed for ruby-2.2.6-p396 SDK

### ISSUE THREAD

**Issue by parag90** [rvm/rvm#3864]
I have updated my ruby from 2.0.0 to 2.2.6 and then my RubyMine stopped working. 
It seems that it is not able to find bundler 

DELC02PQ5TNG8WN:cucumber pajain$ echo $GEM_HOME
/Users/pajain/.rvm/gems/ruby-2.2.6

DELC02PQ5TNG8WN:cucumber pajain$ echo $GEM_PATH
/Users/pajain/.rvm/gems/ruby-2.2.6:/Users/pajain/.rvm/gems/ruby-2.2.6@global

DELC02PQ5TNG8WN:cucumber pajain$ echo $PATH
/Users/pajain/.rvm/gems/ruby-2.2.6/bin:/Users/pajain/.rvm/gems/ruby-2.2.6@global/bin:/Users/pajain/.rvm/rubies/ruby-2.2.6/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/pajain/apache-maven-3.3.3/bin:/Users/pajain/office/ADB:/Users/pajain/Downloads:/Users/pajain/.rvm/bin

DELC02PQ5TNG8WN:cucumber pajain$ which bundle
/Users/pajain/.rvm/gems/ruby-2.2.6/bin/bundle

DELC02PQ5TNG8WN:cucumber pajain$ gem env
Failed to load /Users/pajain/.gemrc because it doesn't contain valid YAML hash
RubyGems Environment:

RUBYGEMS VERSION: 2.6.8
RUBY VERSION: 2.2.6 (2016-11-15 patchlevel 396) [x86_64-darwin15]
INSTALLATION DIRECTORY: /Users/pajain/.rvm/gems/ruby-2.2.6
USER INSTALLATION DIRECTORY: /Users/pajain/.gem/ruby/2.2.0
RUBY EXECUTABLE: /Users/pajain/.rvm/rubies/ruby-2.2.6/bin/ruby
EXECUTABLE DIRECTORY: /Users/pajain/.rvm/gems/ruby-2.2.6/bin
SPEC CACHE DIRECTORY: /Users/pajain/.gem/specs
SYSTEM CONFIGURATION DIRECTORY: /Users/pajain/.rvm/rubies/ruby-2.2.6/etc
RUBYGEMS PLATFORMS:
ruby
x86_64-darwin-15
GEM PATHS:
/Users/pajain/.rvm/gems/ruby-2.2.6
/Users/pajain/.rvm/gems/ruby-2.2.6@global
GEM CONFIGURATION:
:update_sources => true
:verbose => true
:backtrace => false
:bulk_threshold => 1000
REMOTE SOURCES:
https://rubygems.org/
SHELL PATH:
/Users/pajain/.rvm/gems/ruby-2.2.6/bin
/Users/pajain/.rvm/gems/ruby-2.2.6@global/bin
/Users/pajain/.rvm/rubies/ruby-2.2.6/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Users/pajain/apache-maven-3.3.3/bin
/Users/pajain/office/ADB
/Users/pajain/Downloads
/Users/pajain/.rvm/bin
DELC02PQ5TNG8WN:gems pajain$ ls -l /Users/pajain/.rvm/gems/ruby-2.2.6/bin/bundle
-rwxr-xr-x 1 pajain SEA\Domain Users 501 Jan 3 17:23 /Users/pajain/.rvm/gems/ruby-2.2.6/bin/bundle
DELC02PQ5TNG8WN:gems pajain$ ls -l /Users/pajain/.rvm/gems/ruby-2.2.6@global/bin/bundle
-rwxr-xr-x 1 pajain SEA\Domain Users 501 Jan 3 17:20 /Users/pajain/.rvm/gems/ruby-2.2.6@global/bin/bundle
DELC02PQ5TNG8WN:gems pajain$

@mpapis I had --no-document entry in .gemrc file which I removed it but still issue exists

**Comment by pkuczynski** [comment]
Please post `.gemrc`. You could also try to install from scratch: `rvm implode` to remove RVM, and then start a new RVM installation.

**Comment by parag90** [comment]
@pkuczynski 
DELC02PQ5TNG8WN:cucumber pajain$ cat ~/.gemrc
cat: /Users/pajain/.gemrc: No such file or directory

I did tried reinstalling ruby but not the whole rvm

**Comment by pkuczynski** [comment]
So try with whole RVM.

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
