### ISSUE TITLE
Error installing Ruby 2.1.5 // make[1]: *** [ext/openssl/all] Error 2

### ISSUE THREAD

**Issue by fnkypanda** [rvm/rvm#3871]
## Description

When installing Ruby 2.1.5 I get a make error, which seems to be related with openssl
```
root@kali:# rvm --trace install 2.1.5 
Error running '__rvm_make -j4',
showing last 15 lines of /usr/local/rvm/log/1483932523_ruby-2.1.5/make.log
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.1.5/ext/openssl'
exts.mk:192: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling callback-8.c
installing default callback libraries
installing default nkf libraries
linking shared-object nkf.so
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.1.5/ext/nkf'
linking shared-object dl/callback.so
make[2]: Leaving directory '/usr/local/rvm/src/ruby-2.1.5/ext/dl/callback'
make[1]: Leaving directory '/usr/local/rvm/src/ruby-2.1.5'
uncommon.mk:180: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ 1483932633.901242096 /scripts/functions/support : __rvm_make()  383 > return 2
There has been an error while running make. Halting the installation.
```

## Steps to reproduce

1. Installed RVM and master got error 
then 
2. Ran apt-get dist-upgrade && update 
Still same error 

## Expected behavior

Ruby has successfully downloaded

## Actual behavior

* **rvm --trace install 2.1.5** >> https://gist.github.com/fnkypanda/d83423ade5fdf5cb47f6a673079f5954
* **config.log** >> https://gist.github.com/fnkypanda/8798a4e65ba523a4d5386cd335f38a28 
* **make.log** >> https://gist.github.com/fnkypanda/e9460efa7c1de5e8a423cc82fcdb1fd0

## Environment info

```
system:

  system:
    uname:       "Linux Romulus 4.4.0-kali1-amd64 #1 SMP Debian 4.4.6-1kali1 (2016-03-18) x86_64 GNU/Linux"
    system:      "debian/Kali_Linux_Rolling/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.4.5(1)-release (x86_64-pc-linux-gnu)"
    zsh:         "/usr/bin/zsh => zsh 5.3.1 (x86_64-debian-linux-gnu)"

  rvm:
    version:      "rvm 1.28.0 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "1 hour 56 minutes 50 seconds ago"
    path:         "/usr/local/rvm"

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by pkuczynski** [comment]
This seems to be similar to #3548, however in that case openssl3 patch solved the issue. Could you check wich version of openssl do you have installed?

**Comment by iamehiz** [comment]
how will i solve mine because i am trying to install ruby-2.3.3 it is giving the same error

**Comment by pkuczynski** [comment]
@iamehiz which platform? Which version of openssl do u have?

**Comment by fnkypanda** [comment]
@pkuczynski Hi -- I have OpenSSL 1.1.0c  10 Nov 2016

**Comment by iamehiz** [comment]
@pkuczynski im using  `openssl version: OpenSSL 1.1.0c  10 Nov 2016`

**Comment by fnkypanda** [comment]
Hello -- do you know a workaround or patch that I can configure in order to make this work? I've even installed RVM on a clean Kali 2.0 host to test if there may be something wrong with my environment, but same error was showing.

**Comment by mpapis** [comment]
Can someone try it again with latest rvm and ruby - we have added few fixes.

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, feel free to provide requested information so we can continue working on it.
