### ISSUE TITLE
 rvm install ruby-1.9.2 on osx 10.12.2

### ISSUE THREAD

**Issue by OccamTech** [rvm/rvm#3876]
Pravins-3:Instant-Encounter nitinkapoor$ rvm install ruby-1.9.2
Warning, new version of rvm available '1.28.0', you are using older version '1.27.0'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-1.9.2-p330.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.

RVM does not know how to build working ruby-1.9.2-p330 on OSX 10.12,
if you know please let us know by opening a ticket with instructions here:

    https://github.com/rvm/rvm/issues

**Comment by pkuczynski** [comment]
Unfortunately, we do not support such old versions of ruby. Maybe you can upgrade at least to 1.9.3 or newer?
