### ISSUE TITLE
rvm function load slows down new terminals, esp on slow internet

### ISSUE THREAD

**Issue by SeanFelipe** [rvm/rvm#3882]
My personal workflow involves opening and closing a lot of terminal shells, so I'm sensitive to the amount of time it takes to spawn the shell, run my profile scripts and pass me into the shell prompt.

I've been working overseas and I notice that the terminal spawn process is slower -- about 3-5 seconds of latency. Removing the call to $HOME/.rvm/scripts/rvm remedies the issue. I'm wondering then -- is there a network call going out in this script? Or potentially some other source of latency?

This is OSX ElCapitan and rvm 1.27.0. Thanks!

**Comment by havenwood** [comment]
Using RVM's chruby integration is one option for a speedy terminal. See #3376.

**Comment by mpapis** [comment]
@SeanFelipe please check if `export rvm_autoupdate_flag=0` before the sourcing does change anything.

**Comment by SeanFelipe** [comment]
@mpapis that helped! thanks. @havenwood I'll check that out.

Thanks for the quick reply !!
