### ISSUE TITLE
Installing rbx-3.70 fails on PCLinuxOS 64-bit

### ISSUE THREAD

**Issue by pkuczynski** [rvm/rvm#3895]
## Description

Installing rbx-3.70 fail on PCLinuxOS 64-bit.

Issue reported by @jzakiya during testing solution for #3703

## Steps to reproduce

`rvm install rbx-3.70`

## Expected behavior

Rubinus 3.70 is installed.

## Actual behavior

Installation fails: https://gist.github.com/jzakiya/23e843d28cf4cc488f90fecc9528924f

Additional info: https://gist.github.com/jzakiya/fbb9dda8bacce173d2de88dff542c88f

**Comment by pkuczynski** [comment]
I prepared a patch for you. Could you please test it:

```
rvm get branch /bugfix/3895-pclinuxos-rbx
rvm install rbx-3.70
```

**Comment by jzakiya** [comment]
It went through much of the install process until failing.

https://gist.github.com/jzakiya/acfd3e4841d48cc2c2fe99fc595415ea

**Comment by pkuczynski** [comment]
Could you please gist `/home/jzakiya/.rvm/log/1485528013_rbx-3.70/rake.log`?

**Comment by jzakiya** [comment]
I've attached it.

**Comment by pkuczynski** [comment]
Attaching to email does not work. You need to gist it and send link to this gist.

**Comment by jzakiya** [comment]
Here's gist of rake, it;s 4171 lines long.

https://gist.github.com/jzakiya/5860d8d388db429f60beeae73fd0906e

**Comment by pkuczynski** [comment]
Could you please try again and gist both output and new `rake.log`

```
rvm get branch /bugfix/3895-pclinuxos-rbx
rvm install rbx-3.70 --trace
```

**Comment by jzakiya** [comment]
Install didn't succeed. Here's rake.log gist.

https://gist.github.com/jzakiya/8e6ffc1aa02fb4b819d02b1498d3e8f0

**Comment by pkuczynski** [comment]
@jzakiya this gist is gone. Do you still use PCLinuxOS?

**Comment by jzakiya** [comment]
Yes, I still use PCLinuxOS (PCLOS).
I cleaned out a bunch of old gists used to do debugging.

Do you need me to do something?

Jabari

**Comment by pkuczynski** [comment]
Yeah, we could finish this PR and make RVM compile rbx. So to continue this work I would need you to run

```
rvm get branch /bugfix/3895-pclinuxos-rbx
rvm install rbx-3.70 --debug
```

And gist the output and the log file which will break.

**Comment by jzakiya** [comment]
OK.  FYI rubinius (https://runbinius.com) is now up to rbx-3.86 so I used
that instead of rbx-3.70.

https://gist.github.com/jzakiya/c43ee76499f34666c90202524d50e5ee

**Comment by pkuczynski** [comment]
Yeah, sounds good! But I can’t open the gist url. Get 404

**Comment by jzakiya** [comment]
OK

This gist is from installing on a PCLOS KDE5 system in a Virtual Box VM
running on a PCLOS KDE4 host.

https://gist.github.com/jzakiya/b98d6019e6cded37475f151f90c32590

Here is the first gist again, which was created on the PCLOS KDE4
(non-supported now) host system.

https://gist.github.com/jzakiya/c43ee76499f34666c90202524d50e5ee

**Comment by pkuczynski** [comment]
So it works in the first case, and fails in the second, right?

**Comment by jzakiya** [comment]
You  know, I didn't even pay attention to the fact that the KDE5 system
build worked (yes, the KDE4 system failed) .  It's not that big a deal to
get it to run on the KDE4 system since it's not supported anymore (unless
you just want to as a challenge). Here is a gist of output created when I
ran rbx-3.86 on the KDE5 system.

https://gist.github.com/jzakiya/d7d17bf96638143974015deef37df32f

**Comment by pkuczynski** [comment]
Honestly, I have enough challenges with other tickets and features, so maybe we should just close this one and if someone needs rbx on old PCLOS, we can then work it out :)

**Comment by jzakiya** [comment]
I agree.  Thanks for getting rubinius to install on the current PCLOS KDE5.

Jabari
