### ISSUE TITLE
İnstalling Ruby-2.4.0 Problem 

### ISSUE THREAD

**Issue by Reeqz** [rvm/rvm#3898]
Hi ı have a issue. İ am new on Linux, and my english is a little bad. I read #3680 #3675 but my problem is contionues.  I am use Kali Linux 4.6.0 

I run this code
`rvm install ruby-2.4.0`

But I am facing such a problem
`rvm install ruby-2.4.0
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.4.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating systemreuses password required for 'apt-get --quiet --yes update': 
reuses password required for 'apt-get --quiet --yes update': 
reuses password required for 'apt-get --quiet --yes update': 
....
Installing required packages: gawk, libreadline6-dev, zlib1g-dev, libssl-dev, libyaml-dev, libsqlite3-dev, autoconf, libgdbm-dev, libncurses5-dev, automake, libtool, bison, pkg-config........
Error running 'requirements_debian_libs_install gawk libreadline6-dev zlib1g-dev libssl-dev libyaml-dev libsqlite3-dev autoconf libgdbm-dev libncurses5-dev automake libtool bison pkg-config',
showing last 15 lines of /home/reuses/.rvm/log/1485734041_ruby-2.4.0/package_install_gawk_libreadline6-dev_zlib1g-dev_libssl-dev_libyaml-dev_libsqlite3-dev_autoconf_libgdbm-dev_libncurses5-dev_automake_libtool_bison_pkg-config.log
E: Package 'gawk' has no installation candidate
E: Unable to locate package libreadline6-dev
E: Unable to locate package zlib1g-dev
E: Unable to locate package libssl-dev
E: Unable to locate package libyaml-dev
E: Unable to locate package libsqlite3-dev
E: Package 'autoconf' has no installation candidate
E: Unable to locate package libgdbm-dev
E: Package 'libncurses5-dev' has no installation candidate
E: Package 'automake' has no installation candidate
E: Package 'libtool' has no installation candidate
E: Package 'bison' has no installation candidate
E: Package 'pkg-config' has no installation candidate
++ return 100
++ return 100
Requirements installation failed with status: 100.
reuses@kali:~$ `

-Thank You | Like i said, my english is bad sorry for spelling mistakes.

**Comment by pkuczynski** [comment]
Clearly, there is some problem with your `apt` settings. Can you try to manually run `apt-get install automake` for example?

**Comment by Reeqz** [comment]
I worked this way: `apt-get install automake` İs this true ? İf true

`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package automake is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source`

Is the 'automake' value there variable? I dont understand.

--Thank You for  your interest

**Comment by pkuczynski** [comment]
Can you try to run following commands:

```
rvm get master
rvm install ruby-2.4.0
```

And gist the output for me.

**Comment by alanswanht** [comment]
I have a similar issue with a different dependency, openssl.

    $ rvm install ruby-2.4.0
    Searching for binary rubies, this might take some time.
    Found remote file https://rubies.travis-ci.org/osx/10.12/x86_64/ruby-2.4.0.tar.bz2
    Checking requirements for osx.
    Updating Homebrew...
    Installing requirements for osx.
    Updating system.....
    Installing required packages: openssl.
    Somehow it happened there is no executable 'openssl',
    run 'brew doctor' and make sure latest '' is installed properly.
    RVM autolibs is now configured with mode '4' =>
      'Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X).',
    please run `rvm autolibs enable` to let RVM do its job or run and read `rvm autolibs [help]`
    or visit https://rvm.io/rvm/autolibs for more information.
    Requirements installation failed with status: 12.
    $ which openssl
    /usr/bin/openssl

**Comment by pkuczynski** [comment]
@alanswanht could you please run `rvm autolibs enable`, then fix all the issues listed by `brew doctor` and then try again? In case it still fails please open a new issue, as this one was for a different platform

**Comment by pkuczynski** [comment]
Closing this issue due lack of feedback from @Reeqz (please reopen if issue persist).

**Comment by alanswanht** [comment]
@pkuczynski  I ran `rvm autolibs enable` but it didn't do anything for me because (I'm thinking) `mode '4'` is already 'enable'.
However, I managed to solve my issue with `brew install openssl --force` so I will not open a new issue.

**Comment by pkuczynski** [comment]
A couple of people reported the issue with openssl install with brew and that they need to force it. I will prepare a patch which does that, so in the future, it would not be required...

**Comment by simongareste** [comment]
@pkucznynski : A bit more info on the @alanswanht issue: when running with --trace, you see

```
+++ 1486571846.N /scripts/functions/requirements/osx_brew : requirements_osx_brew_lib_installed_prebrew --prefix openssl
++ 1486571847.N /scripts/functions/requirements/osx_brew : requirements_osx_brew_lib_installed_prefbrew_lib_prefix=/usr/local/Cellar/openssl/1.0.2k
++ 1486571847.N /scripts/functions/requirements/osx_brew : requirements_osx_brew_lib_installed_pref[[ -n /usr/local/Cellar/openssl/1.0.2k ]]
++ 1486571847.N /scripts/functions/requirements/osx_brew : requirements_osx_brew_lib_installed_pref[[ -d /usr/local/Cellar/openssl/1.0.2k ]]
++ 1486571847.N /scripts/functions/requirements/osx_brew : requirements_osx_brew_lib_installed_prefreturn 1
++ 1486571847.N /scripts/functions/requirements/osx_brew : requirements_osx_brew_after_update_certsrvm_requiremnts_fail_always 2 'Somehow it happened there is no executable '\''openssl'\'',
```

So (didn't check more in depth) it seems that it's looking for the latest openssl, which wasn't installed. brew upgrade openssl fixed it.

**Comment by pkuczynski** [comment]
@simongareste this should be fixed with this PR https://github.com/rvm/rvm/pull/3920
