### ISSUE TITLE
Trouble installing ruby-1.9.3-p194

### ISSUE THREAD

**Issue by lowang-trover** [rvm/rvm#3899]
## Description

When I type in `rvm install ruby-1.9.3-p194-perf`, it throws an error. I condensed the log hence the ellipses. Please look at [this gist](https://gist.github.com/lowang-trover/2355a2609607d8f9cfc0bef8361d7a93) for the full log.

Note: I got this error before when I try to brew install bundler and do other bundler commands. I suspect this error might have to do with rvm, gems, and paths but I'm not entirely sure. Please let me know if you need more info.

## Steps to reproduce

_List all of your specific environment settings, actions taken, and commands run — everything required to replicate the problem._
- Running on osx El Capitan
 1. ... add `export PATH="$PATH:$HOME/source/directory_name/devbin` to ~/.profile
 2. ... `\curl -L https://get.rvm.io | bash -s stable`
 3. ... `source /Users/lowang.rvm/scripts/rvm`
4. ... `rvm install ruby-1.9.3-p194-perf`

## Expected behavior

Get rvm to install ruby-1.9.3-p194 for Mac OS 10.11 El Capitan

## Actual behavior

https://gist.github.com/lowang-trover/2355a2609607d8f9cfc0bef8361d7a93

## Environment info

```
system:

  system:
    uname:       "Darwin BELC02Q4G3UG8WN.sea.corp.expecn.com 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64"
    system:      "osx/10.11/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)"
    zsh:         "/bin/zsh => zsh 5.0.8 (x86_64-apple-darwin15.0)"

  rvm:
    version:      "rvm 1.28.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "1 hour 22 minutes ago"
    path:         "/Users/lowang/.rvm"

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/lowang/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by mpapis** [comment]
the patches apply fine for me, there might be some leftovers, try:
```bash
rvm get head
rvm cleanup sources
rvm remove ruby-1.9.3-p194-perf
```
can you gist `/Users/lowang/.rvm/log/1485902354_ruby-1.9.3-p194-perf/rubygems.install.log`

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
