### ISSUE TITLE
df: ‘/home/myapp/.rvm’: No such file or directory

### ISSUE THREAD

**Issue by jdzak** [rvm/rvm#3910]
## Description

RVM fails to install. When I run `curl -L https://get.rvm.io | bash -s stable --autolibs=disable` I get the error, `df: ‘/home/myapp/.rvm’: No such file or directory`.

## Steps to reproduce

 1. run `curl -L https://get.rvm.io | bash -s stable --autolibs=disable`

## Expected behavior

RVM should install

## Actual behavior

 I get the error, `df: ‘/home/myapp/.rvm’: No such file or directory`.

## Environment info

Can't, rvm isn't installed.

**Comment by jdzak** [comment]
This commit may be related. https://github.com/rvm/rvm/commit/71a89a208f74b1c977cbd776fb364f0219cd1d69

**Comment by kalinchuk** [comment]
Same issue. Started happening recently.

**Comment by pkuczynski** [comment]
@jdzak indeed this possibly broke it, but not sure yet why...

**Comment by jyanko** [comment]
I started seeing this 'df' error after lunch today.  

Prior to lunch, had gotten it installed by doing the following...

```
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

$ \curl -sSL https://get.rvm.io | sudo bash -s stable
```

...after lunch, was going to deal with adding user(s) to the 'rvm' group.   For some reason, decided to do rvm implode and start over.   

That's when I discovered the inability to install rvm from either stable or a specific version...

```
$ cat /etc/redhat-release
CentOS release 6.8 (Final)

$ \curl -sSL https://get.rvm.io | bash -s stable
df: `/home/jyanko/.rvm': No such file or directory
df: no file systems processed

$ \curl -sSL https://get.rvm.io | bash -s -- --version 1.27.0
df: `/home/jyanko/.rvm': No such file or directory
df: no file systems processed

$ \curl -sSL https://get.rvm.io | sudo bash -s -- --version 1.27.0
df: `/usr/local/rvm': No such file or directory
df: no file systems processed
```

**Comment by PhenomHTPC** [comment]
I had the same issue while trying to install RVM on my Mac today. I went to the IRC and got help from @havenwood. This is how we got it to at least install

1. Navigate to your home directory. 
2. curl -sSL https://github.com/rvm/rvm/tarball/stable -o ~/rvm-stable.tar.gz
3. mkdir ~/rvm && cd ~/rvm && tar --strip-components=1 -xzf ~/rvm-stable.tar.gz
4. ./install
5. Profit

However I am still unable to add a gpg key. Which means I still can not perform an update. The issue may be relating to the keys failing to be verified? 

Thanks to Havenwood for you help!

**Comment by tsangha** [comment]
@PhenomHTPC 

as you mentioned, I now see a .rvm and a rvm. 

If i try to do 'rvm install 2.3', i get 'find: /Users/T/rvm/rubies: No such file or directory', 
but if I look in /.rvm/, I see a rubies folder...any ideas?

**Comment by PhenomHTPC** [comment]
@tsangha

hmm I did "rvm install ruby-2.4.0" and it seemed to install ruby just fine. 

Maybe try that?

**Comment by havenwood** [comment]
Closing for now since 556c42a temporarily reverts the installer changes causing this issue.
