### ISSUE TITLE
get.rvm.io points at master install script, which is currently broken

### ISSUE THREAD

**Issue by dferrantelli** [rvm/rvm#3911]
## Description

get.rvm.io points at master install script, which is currently broken (exits with error code 1 and no text) the exit line with trace lands on the noexec test on line 790

## Steps to reproduce

attempt to install rvm using get.rvm.io

## Expected behavior

rvm will install

## Actual behavior

./rvm-install -trace
+ ./rvm-installer.sh : rvm_install_parse_params()  566 > rvm_trace_flag=1
+ ./rvm-installer.sh : rvm_install_parse_params()  567 > flags=(-x "${flags[@]}" "$token")
+ ./rvm-installer.sh : rvm_install_parse_params()  568 > forwarded_flags+=("$token")
+ ./rvm-installer.sh : rvm_install_parse_params()  558 > ((  0 > 0  ))
+ ./rvm-installer.sh : rvm_install_parse_params()  733 > ((  0 > 0 && 0 == 0  ))
+ ./rvm-installer.sh : rvm_install_parse_params()  737 > true latest
+ ./rvm-installer.sh : rvm_install_parse_params()  738 > true master
+ ./rvm-installer.sh : rvm_install_parse_params()  740 > [[ -z '' ]]
+ ./rvm-installer.sh : rvm_install_parse_params()  741 > sources=("${DEFAULT_SOURCES[@]}")
+ ./rvm-installer.sh : rvm_install_parse_params()  744 > rvm_src_path=/home/rails/.rvm/src
+ ./rvm-installer.sh : rvm_install_parse_params()  745 > rvm_archives_path=/home/rails/.rvm/archives
+ ./rvm-installer.sh : rvm_install_parse_params()  746 > rvm_releases_url=https://rvm.io/releases
+ ./rvm-installer.sh : rvm_install()  899 > rvm_install_validate_volume_mount_mode
+ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  786 > typeset partition
+ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  787 > typeset mount_noexec_mode
++ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  789 > df -P /home/rails/.rvm
++ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  789 > tail -1
++ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  789 > cut '-d ' -f 1
+ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  789 > partition=/dev/vda1
++ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  790 > mount
++ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  790 > grep -q '/dev/vda1 .*noexec.*'
+ ./rvm-installer.sh : rvm_install_validate_volume_mount_mode()  790 > mount_noexec_mode=

**Comment by havenwood** [comment]
This should be resolved with the temporary revert of the related installer code in 556c42a. Thanks for the report!
