### ISSUE TITLE
I can't install a ruby version

### ISSUE THREAD

**Issue by alexsoares** [rvm/rvm#3917]
## Description

I made the mistake of to execute 'rvm_pkg' command, and now everytime i need install a new version of ruby, the installation stay stopped witch de bellow message:
Installing requirements for rvm_pkg.
Updating system.
Installing required custom packages: libtool..

## Steps to reproduce

 1. run 'rvm autolibs rvm_pkg'
 2. run any rvm install ruby version
 Just It

## Expected behavior

The version of ruby installed with success

## Actual behavior

The terminal stay stopped in:
Installing requirements for rvm_pkg.
Updating system.
Installing required custom packages: libtool..

## Environment info

ruby-2.3.0@global:

  system:
    uname:       "Linux ajsoares 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    system:      "mint/18/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.42(1)-release (x86_64-pc-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.28.0 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "7 minutes 7 seconds ago
    path:         "/usr/share/rvm"
    autolibs:     "[rvm_pkg] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.3.0p0"
    date:         "2015-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2015-12-25 revision 53290"
    full_version: "ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]"

  homes:
    gem:          "/home/ajsoares/.rvm/gems/ruby-2.3.0@global"
    ruby:         "/usr/share/rvm/rubies/ruby-2.3.0"

  binaries:
    ruby:         "/usr/share/rvm/rubies/ruby-2.3.0/bin/ruby"
    irb:          "/usr/share/rvm/rubies/ruby-2.3.0/bin/irb"
    gem:          "/usr/share/rvm/rubies/ruby-2.3.0/bin/gem"
    rake:         "/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin/rake"

  environment:
    PATH:         "/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/usr/share/rvm/rubies/ruby-2.3.0/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@infocad/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-1.9.3-p551/bin:/home/ajsoares/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@infocad/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-1.9.3-p551/bin:/home/ajsoares/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@blog/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@blog/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@infocad/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@blog/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0/bin:/home/ajsoares/.rvm/gems/ruby-2.3.0@global/bin:/home/ajsoares/.rvm/gems/ruby-1.9.3-p551/bin:/home/ajsoares/.rvm/gems/ruby-1.9.3-p551@global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/rvm/bin"
    GEM_HOME:     "/home/ajsoares/.rvm/gems/ruby-2.3.0@global"
    GEM_PATH:     "/home/ajsoares/.rvm/gems/ruby-2.3.0@global"
    MY_RUBY_HOME: "/usr/share/rvm/rubies/ruby-2.3.0"
    IRBRC:        "/usr/share/rvm/rubies/ruby-2.3.0/.irbrc"
    RUBYOPT:      ""
    gemset:       "global"

**Comment by pkuczynski** [comment]
Try to run `rvm autolibs enable` and then install ruby.

**Comment by joshcano** [comment]
I have the same issue, it was resolved by using `rvm autolibs enable` thank you

**Comment by pkuczynski** [comment]
Seems that this is sorted. Closing due lack of feedback from the issuer.
