### ISSUE TITLE
How to reboot GitLab 6.3.1? 

### ISSUE THREAD

**Issue by xch0911** [rvm/rvm#3918]
## Expected behavior
do this `sudo /etc/init.d/gitlab start`
then
Starting unicorn: /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 8 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/git/.gem/ruby/1.9.1:/usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/gems/1.9.1', execute `gem env` for more information
	from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:324:in `to_spec'
	from /usr/local/rvm/rubies/ruby-1.9.3-p392/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:64:in `gem'
	from /usr/local/rvm/gems/ruby-1.9.3-p392/bin/bundle:22:in `<main>' [failure]
Starting sidekiq:                                          [failure]

## Environment info
do `gem env`
then
`[root@10-10-20-73 /]# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.8
  - RUBY VERSION: 1.9.3 (2013-02-22 patchlevel 392) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/rvm/gems/ruby-1.9.3-p392
  - RUBY EXECUTABLE: /usr/local/rvm/rubies/ruby-1.9.3-p392/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/rvm/gems/ruby-1.9.3-p392/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/rvm/rubies/ruby-1.9.3-p392/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/rvm/gems/ruby-1.9.3-p392
     - /usr/local/rvm/gems/ruby-1.9.3-p392@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://ruby.taobao.org/"]
  - REMOTE SOURCES:
     - https://ruby.taobao.org/
  - SHELL PATH:
     - /usr/local/git/bin
     - /usr/local/rvm/gems/ruby-1.9.3-p392/bin
     - /usr/local/rvm/gems/ruby-1.9.3-p392@global/bin
     - /usr/local/rvm/rubies/ruby-1.9.3-p392/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /usr/local/rvm/bin
     - /root/bin
     - /etc/gradle-2.1/bin`

**Comment by pkuczynski** [comment]
This does not look like a RVM issue. It looks like your `GEM_PATH=` is pointing to some incorrect folders...
