### ISSUE TITLE
Replace StartCom https certificate with LetsEncrypt

### ISSUE THREAD

**Issue by rpolasek** [rvm/rvm#3921]
## Description

i have a trouble to execute "rvm get head". it always finishes with error message "Could not download rvm-installer, get some help at #rvm IRC channel at freenode servers." and return error code is 60.

## Steps to reproduce

execute "rvm get head" on gentoo

## Actual behavior

can't update rvm - not only gentoo ca-certificates distrusts StartCom, which rvm uses at the moment.

## Environment info

ruby-2.4.0:

  system:
    uname:       "Linux pc4 4.4.39-gentoo #1 SMP Thu Jan 12 14:18:02 CET 2017 x86_64 Intel(R) Core(TM)2 Quad CPU Q8200 @ 2.33GHz GenuineIntel GNU/Linux"
    system:      "gentoo/base-2.3/x86_64"
    bash:        "/bin/bash => GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)"
    zsh:         " => not installed"

  rvm:
    version:      "rvm 1.28.0 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "1 month 6 days 22 hours 44 minutes 16 seconds ago"
    path:         "/home/rpolasek/.rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.4.0p0"
    date:         "2016-12-24"
    platform:     "x86_64-linux"
    patchlevel:   "2016-12-24 revision 57164"
    full_version: "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]"

  homes:
    gem:          "/home/rpolasek/.rvm/gems/ruby-2.4.0"
    ruby:         "/home/rpolasek/.rvm/rubies/ruby-2.4.0"

  binaries:
    ruby:         "/home/rpolasek/.rvm/rubies/ruby-2.4.0/bin/ruby"
    irb:          "/home/rpolasek/.rvm/rubies/ruby-2.4.0/bin/irb"
    gem:          "/home/rpolasek/.rvm/rubies/ruby-2.4.0/bin/gem"
    rake:         "/home/rpolasek/.rvm/rubies/ruby-2.4.0/bin/rake"

  environment:
    PATH:         "/home/rpolasek/.rvm/gems/ruby-2.4.0/bin:/home/rpolasek/.rvm/gems/ruby-2.4.0@global/bin:/home/rpolasek/.rvm/rubies/ruby-2.4.0/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4:/usr/x86_64-pc-linux-gnu/avr/gcc-bin/4.9.4:/opt/android-sdk-update-manager/tools:/opt/android-sdk-update-manager/platform-tools:/usr/games/bin:/opt/verilator/bin:/home/rpolasek/.rvm/bin:/home/rpolasek/bin:/home/rpolasek/.rvm/bin:/home/rpolasek/bin/go:/opt/esp8266/esp-open-sdk/xtensa-lx106-elf/bin"
    GEM_HOME:     "/home/rpolasek/.rvm/gems/ruby-2.4.0"
    GEM_PATH:     "/home/rpolasek/.rvm/gems/ruby-2.4.0:/home/rpolasek/.rvm/gems/ruby-2.4.0@global"
    MY_RUBY_HOME: "/home/rpolasek/.rvm/rubies/ruby-2.4.0"
    IRBRC:        "/home/rpolasek/.rvm/rubies/ruby-2.4.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment]
we will look into switching to letsencrypt

**Comment by mpapis** [comment]
done
