### ISSUE TITLE
Output of `rvm info` is no longer YAML compatible.

### ISSUE THREAD

**Issue by lunaru** [rvm/rvm#3924]
## Description

In rvm 1.29 the output of `rvm info` is no longer YAML compatible.

## Steps to reproduce

Run `rvm info` and note there is a key called `remote path`, but YAML cannot have spaces in keys.

## Expected behavior

I'm actually not sure if the intention is for `rvm info` to have a YAML compatible output, but it seems this way as there are gems in the wild that run YAML.load() on the resulting stdout output of `rvm info`. For example, the RVM gem does this: https://github.com/rvm/rvm-gem/search?utf8=%E2%9C%93&q=YAML

It would be good to get a definitive yes or no on this.

**Comment by lunaru** [comment]
It also seems that the output of `rvm info`'s `updated` field is missing a `"` at the end of the line.

**Comment by pkuczynski** [comment]
I didn't know anybody expected it to be yaml comptible. I will fix it next week when I am back from my holiday. Apologies for the inconvenience

**Comment by lunaru** [comment]
Thanks for fixing this guys!
