### ISSUE TITLE
RVM 1.29.0 reports missing required packages (but they are already installed)

### ISSUE THREAD

**Issue by thbar** [rvm/rvm#3927]
## Description

I have a server where RVM is configured in autolibs 2 (read-fail), and where the required packages are explicitely installed via Ansible. Today while trying to install Ruby 2.4.0, RVM complains about missing required packages, which are actually not missing but installed.

## Steps to reproduce

On Ubuntu 16 LTS, with RVM 1.29.0 (or master), on a single-user (not sudoer) deploy :

1. Configure rvm for autolibs read-fail
2. `rvm install ruby-2.4.0`

## Expected behavior

I'd expect ruby to just install.

## Actual behavior

I get the [following error](https://gist.github.com/thbar/1cf091793e808be4aab675cb38ac9a5c).

Note that if I switch back to RVM 1.28.0 (using `\curl -sSL https://get.rvm.io | bash -s -- --version 1.28.0`), `rvm install` will start downloading correctly etc.

**Comment by wgrrrr** [comment]
I am experiencing this same error in this same situation on Ubuntu 16.04 (Xenial) and RVM 1.29.0. I have also checked that all packages are installed by using autolibs=3, taking note of all installed packages by Apt, configuring Ansible to install the exact packages, switching back to autolibs=2 and trying again. Still, I get errors about required packages not being installed.

**Comment by raelgc** [comment]
Same happens if you install using the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by thbar** [comment]
@raelgcthe the production server I'm targeting is using the [rvm ansible role](https://github.com/rvm/rvm1-ansible) and I prefer not to tweak it. That said I'll be able to temporarily try using the package in a Vagrant VM soon. I'll report back on the output.

**Comment by ChrisPetr0** [comment]
Seeing this with Ubuntu 14.04 as well, all packages installed, autolibs not seeing installed packages

**Comment by mpapis** [comment]
can I see `dpkg --print-architecture` - it's most likely related to 32bit and 0834daa2ed7e77469fb312fbe805878b1128fa9c we probably need to restore the `requirements_debian_arch`

**Comment by VladRassokhin** [comment]
Same on ubutnu-14.04.
Steps to reproduce:
```bash
vagrant init ubuntu/trusty64
vagrant up && vagrant ssh
```
Inside vagrant maniche:
```
# Install rvm (omitted)
rvm autolibs read-fail
rvm install ruby-2.4.0 # Fails
# Install libs recommended by previous command
sudo apt-get install -y bash curl patch bzip2 gawk g++ gcc libssl-dev make libc6-dev patch openssl curl zlib1g zlib1g-dev libyaml-dev libsqlite3-dev sqlite3 libgmp-dev libgdbm-dev libncurses5-dev bison pkg-config libffi-dev libgmp-dev libreadline6-dev
rvm install ruby-2.4.0 # Would fail anyway.
```

Maybe it's time to setup some CI?

**Comment by mpapis** [comment]
@VladRassokhin https://travis-ci.org/rvm/rvm/builds - what do you get from `dpkg --print-architecture`

**Comment by VladRassokhin** [comment]
@mpapis 
```
$  dpkg --print-architecture
amd64
```

**Comment by mpapis** [comment]
please try with:
```bash
rvm get branch /bugfix/3927_explicit_architecture_check
```

**Comment by VladRassokhin** [comment]
With rvm from that branch and `rvm autolibs read-file`, `rvm install ruby`  works fine. Thanks!
