### ISSUE TITLE
"Warning! PATH is not properly set up" when using RVM with tmux

### ISSUE THREAD

**Issue by BjornMelgaard** [rvm/rvm#3929]
```
set -g default-command "$SHELL -l"
set -g default-shell "$SHELL"
```
didnt work for me, what I do:
start without tmux

```
$ echo $PATH 
/home/bjorn/.rvm/gems/ruby-2.4.0/bin:/home/bjorn/.rvm/gems/ruby-2.4.0@global/bin:/home/bjorn/.rvm/rubies/ruby-2.4.0/bin:/home/bjorn/.cabal/bin:/usr/local/heroku/bin:/home/bjorn/.node_modules/bin:/home/bjorn/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/bjorn/.rvm/bin

$ tmux 
$ tmux show-options -g G def
default-command "/bin/zsh -l"
default-shell "/bin/zsh"
$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
$ zsh
$ echo $PATH 
...all great again
```

[My tmux and others dotfiles at that moment](https://github.com/BjornMelgaard/dotfiles/blob/master/tmux.conf)

temporal solution: in zshrc
`[[ $TMUX != "" ]] && rvm use default > /dev/null 2>&1`

[rvm infos](http://pastebin.com/jXubP6tz)

**Comment by mpapis** [comment]
can you show your `zshrc`?

**Comment by BjornMelgaard** [comment]
Yes, it in my dotfiles, but [without this line](https://github.com/BjornMelgaard/dotfiles/blob/master/zshrc#L35), its temporal solution as I have written

[zshenv](https://github.com/BjornMelgaard/dotfiles/blob/master/zshenv)

**Comment by mpapis** [comment]
`zshenv` file in which you load RVM (`source "$HOME/.rvm/scripts/rvm"`) is the first sourced file in the process of initializing ZSH, you should move this line to `zshrc` after you finish setting up `PATH` and `source`'ing other files.

**Comment by BjornMelgaard** [comment]
Ok, that indeed worked, I thought that my nvim will not find rvm after that, but no, thank you very much :1st_place_medal:

**Comment by crivotz** [comment]
I had a bit of headaches also for this question (post update to Debian Stretch)

In my case, I use [zprezto](https://github.com/sorin-ionescu/prezto) and I solved it with edit `.zprofile`

```zsh
# Set the list of directories that Zsh searches for programs.
path=(
  $path:$home/.rvm/bin
  /usr/local/{bin,sbin}
  $path
)
# RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
```
