### ISSUE TITLE
Feature Request: Testing for gems in gemsets

### ISSUE THREAD

**Issue by danielpclark** [rvm/rvm#3931]
I've been reading Rubygems/Bundler/RVM code for a few months now.  What I'm looking for is something equivalent to `Dir.mktmpdir` for gemsets - `RVM.mktmpgemset`.  So an RVM helper for test suites for clean gemsets.  The code would look something like:

```ruby
def test_gem_builds_extension
  RVM.mktmpgemset do |gemset, env|
    RVM.gem_install mygem, gemset # install from local gemfile built from Gem::Package.build

    # pseudo code
    assert_includes env["GEM_HOME"], mygem

    # set mygem_path variable here
    assert File.exist? "#{mygem_path}/target/release/mygem.so" # compiled extension
  end
  # RVM removes gemset after block
end
```

I'm open to the implementation details.  But what I really need is a clean environment to perform gem install and/or bundle install to verify content.

TravisCI uses RVM so I believe gemsets would be an ideal tool for this.

**Comment by mpapis** [comment]
something like:
```bash
rvm use --create tempgemset
do_your_tests
rvm use @default
rvm gemest delete tempgemset
```
?
RVM is a shell tool, adding ruby code would require extra effort.

**Comment by danielpclark** [comment]
Yes, that's the outline.  If you'd like I could write some code for this and follow any feedback/direction you give.

**Comment by mpapis** [comment]
I wonder if https://github.com/rvm/rvm-with could be extended to include a `temporary_gemset` flag?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
