### ISSUE TITLE
libffi-devel required with latest RVM  with master branch

### ISSUE THREAD

**Issue by mukteshkrmishra** [rvm/rvm#3932]
I got the latest rvm using rvm get master.

But when I try to installl ruby it says it requires libffi-devel.

Though as per https://github.com/rvm/rvm/issues/2583 it is no longer required.

Please help.
(PS: I installed libffi-devel manually to solve this dependency).

## Environment info
  system:
    uname:        "Linux ip-10-205-193-244.dqa.capitalone.com 2.6.32-642.11.1.el6.x86_64 #1 SMP Wed Oct 26 10:25:23 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "CentOS"
    version:      "6"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)"
    zsh:          "/bin/zsh => zsh 4.3.11 (x86_64-redhat-linux-gnu)"
    remote path:  "centos/6/x86_64"

  rvm:
    version:      "rvm 1.29.1 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "3 minutes 38 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         ""

  environment:
    PATH:         "/usr/java/jdk1.8.0_60//bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by pkuczynski** [comment]
Could you remove the `libffi-devel` and provide the output or rvm install, so we can trace the problem?

**Comment by mukteshkrmishra** [comment]
The above output is w/o libffi-devel only. I installed that package manually after wards to remove failure (as a remediation).

**Comment by mpapis** [comment]
@mukteshkrmishra do you mean that the package is required for proper Ruby installation but RVM does not install it automatically? Which Ruby versions do require it?

**Comment by mpapis** [comment]
This should be fixed with #4170.
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
