### ISSUE TITLE
Help Section of the https://rvm.io/ page to points to irc.freenode.net not github

### ISSUE THREAD

**Issue by CJ718** [rvm/rvm#3939]
## Description

 Please cleanup the Help Section of the https://rvm.io/ page to point to gihub, not irc.freenode.net 
Current Help Section info:
"You can find the RVM team on IRC in
#rvm on irc.freenode.net
If we do not respond right away, leave a message and a contact to you like email or twitter."

Thank you

## Steps to reproduce

 1. ...n/a
 2. ...n/a
 3. ...n/a

## Expected behavior

link to github
## Actual behavior
#rvm on irc.freenode.net

* [command](https://gist.github.com/...) - n/a
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)- n/a
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info
n/a

n/a

**Comment by mpapis** [comment]
Removed IRC in RVM itself 8d48e00

**Comment by mpapis** [comment]
Removed on the site rvm/rvm-site@0a91a6f
