### ISSUE TITLE
Error "PATH not properly set..."

### ISSUE THREAD

**Issue by CJ718** [rvm/rvm#3940]
## Description

 I've gotten everything installed, RVM (version 1.29.1), Ruby 2.4.0 and Rails 5.0....... Everything seems to work fine but I continually get the same error msg when trying to initiate RVM: ~$ rvm -v Warning! PATH is not properly set up, '/usr/share/rvm/gems/ruby-2.4.0/bin' is not at first place.

## Steps to reproduce

 1. ...open terminal
 2. ...rvm -v
 3. ...Warning! PATH is not properly set up, '/usr/share/rvm/gems/ruby-2.4.0/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.4.0'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]

## Expected behavior

rvm 1.9.2
## Actual behavior

Warning! PATH is not properly set up, '/usr/share/rvm/gems/ruby-2.4.0/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.4.0'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
* [command](https://gist.github.com/...) - 
id
uid=1001(cjc71830) gid=1001(cjc71830) groups=1001(cjc71830),27(sudo),1003(rvm)

ls -ld /usr/share/rvm
drwxrwsr-x 25 root rvm 4096 Feb 24 12:26 /usr/share/rvm
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

rvm info
Warning! PATH is not properly set up, '/usr/share/rvm/gems/ruby-2.4.0/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.4.0'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.

ruby-2.4.0:

  system:
    uname:        "Linux cjc13-HP-EliteBook-8460p 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "16.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote path:  "ubuntu/16.04/x86_64"

  rvm:
    version:      "rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "3 hours 50 minutes 24 seconds ago"
    path:         "/usr/share/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.0p0"
    date:         "2016-12-24"
    platform:     "x86_64-linux"
    patchlevel:   "2016-12-24 revision 57164"
    full_version: "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]"

  homes:
    gem:          "/usr/share/rvm/gems/ruby-2.4.0"
    ruby:         "/usr/share/rvm/rubies/ruby-2.4.0"

  binaries:
    ruby:         "/usr/share/rvm/rubies/ruby-2.4.0/bin/ruby"
    irb:          "/usr/share/rvm/rubies/ruby-2.4.0/bin/irb"
    gem:          "/usr/share/rvm/rubies/ruby-2.4.0/bin/gem"
    rake:         "/usr/share/rvm/gems/ruby-2.4.0/bin/rake"

  environment:
    PATH:         "/home/cjc71830/bin:/home/cjc71830/.local/bin:/usr/share/rvm/gems/ruby-2.4.0/bin:/usr/share/rvm/gems/ruby-2.4.0@global/bin:/usr/share/rvm/rubies/ruby-2.4.0/bin:/home/cjc71830/bin:/home/cjc71830/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/usr/share/rvm/bin"
    GEM_HOME:     "/usr/share/rvm/gems/ruby-2.4.0"
    GEM_PATH:     "/usr/share/rvm/gems/ruby-2.4.0:/usr/share/rvm/gems/ruby-2.4.0@global"
    MY_RUBY_HOME: "/usr/share/rvm/rubies/ruby-2.4.0"
    IRBRC:        "/usr/share/rvm/rubies/ruby-2.4.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by raelgc** [comment]
@CJ718 Can you, please, try the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by CJ718** [comment]
Hi Rael, Thanks for the quick response. I've been trying this over and over to no avail. I removed rvm via terminal then removed all instances of RVM that I could find. Logged out then back in, then followed your instructions:
cjc13@cjc13-HP-EliteBook-8460p:~$ rvm -v
   No command 'rvm' found, but there are 26 similar ones
   rvm: command not found
cjc13@cjc13-HP-EliteBook-8460p:~$ ruby -v
   The program 'ruby' is currently not installed. You can install it by typing:
   sudo apt install ruby
cjc13@cjc13-HP-EliteBook-8460p:~$ rails -v
   The program 'rails' is currently not installed. You can install it by typing:
    sudo apt install ruby-railties
cjc13@cjc13-HP-EliteBook-8460p:~$ sudo apt-add-repository -y ppa:rael-gc/rvm
   [sudo] password for cjc13:
   gpg: keyring `/tmp/tmpkpxlfy1z/secring.gpg' created
   gpg: keyring `/tmp/tmpkpxlfy1z/pubring.gpg' created
   gpg: requesting key F4E3FBBE from hkp server keyserver.ubuntu.com
   gpg: /tmp/tmpkpxlfy1z/trustdb.gpg: trustdb created
   gpg: key F4E3FBBE: public key "Launchpad PPA for Rael" imported
   gpg: Total number processed: 1
   gpg:               imported: 1  (RSA: 1)
   OK
cjc13@cjc13-HP-EliteBook-8460p:~$ sudo apt-get update
   Hit:1 http://us.archive.ubuntu.com/ubuntu xenial InRelease
   Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                                                          
   Hit:3 http://archive.canonical.com/ubuntu xenial InRelease                                                                           
   Hit:4 http://ppa.launchpad.net/appgrid/stable/ubuntu xenial InRelease                        
   Get:5 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
   Hit:6 http://ppa.launchpad.net/giuspen/ppa/ubuntu xenial InRelease                
   Hit:7 http://ppa.launchpad.net/rael-gc/rvm/ubuntu xenial InRelease                 
   Fetched 204 kB in 0s (297 kB/s)                                                    
   Reading package lists... Done
cjc13@cjc13-HP-EliteBook-8460p:~$ sudo apt-get install rvm
   Reading package lists... Done
   Building dependency tree      
   Reading state information... Done
   rvm is already the newest version (1.29.1-1).
   0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded. 

Then I log out and log back in and now I get:

cjc13@cjc13-HP-EliteBook-8460p:~$ rvm -v
   No command 'rvm' found, but there are 26 similar ones
   rvm: command not found

It's usually at this point when I start trying everything and any just to get the program to acknowledge it's there.
Help please....
Thanks
Carl

**Comment by CJ718** [comment]
I closed it by accident

**Comment by CJ718** [comment]
I also just noticed the 'strikethroughs' and have no idea where they came from. Apologies.

**Comment by raelgc** [comment]
Make sure you followed the gnome-terminal instructions to make it work as a shell login.

**Comment by CJ718** [comment]
If you are referring to the : terminal, edit, profile preferences, run
command as login shell instructions, yes, I did. Even deselected it
un-installed, re-installed, re-check 'run command as login script'.
Thanks again

**Comment by roberts1000** [comment]
I ran into this warning/error as well.  I just built two fresh Ubuntu 16.04.2 guest on a desktop and laptop.  Both machines use VirtualBox 5.1.18, Ubuntu 16.04.2 and RVM 1.29.1.  The installation worked flawlessly for my desktop.  My laptop is writing this warning any time I use the `rvm` command.  I've compared the dot files between the desktop and laptop and there doesn't seem to be any relevant differences.

I did have one weird issue on the laptop installation.  Some of the dot files had a bunch of random characters inserted before or after the RVM lines (I can't remember if it was before or after).  It was a string of several hundred characters (it contained alot of `@` characters and some other characters) on a single line.

```
$ which rvm
/home/dev/.rvm/bin/rvm
```

```
env | grep PATH
PATH=/home/dev/bin:/home/dev/.local/bin:/home/dev/.rvm/gems/ruby-2.3.3/bin:/home/dev/.rvm/gems/ruby-2.3.3@global/bin:/home/dev/.rvm/rubies/ruby-2.3.3/bin:/home/dev/bin:/home/dev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dev/.rvm/bin:/snap/bin:/home/dev/.rvm/bin:/home/dev/.rvm/bin
```

FWIW I get an error when I run the recommended `rvm get stable command`

```
$ rvm get stable -- auto-dotfiles

Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /home/dev/.rvm/archives/rvm-installer.asc
gpg: Signature made Mon 20 Feb 2017 09:05:42 AM EST using RSA key ID BF04FF17
gpg: Fatal: /home/dev/.gnupg/trustdb.gpg: invalid trustdb
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/dev/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.

-bash: return: _ret: numeric argument required
```
