### ISSUE TITLE
Add binaries for CentOS 7

### ISSUE THREAD

**Issue by ephracis** [rvm/rvm#3942]
Right now there are only binary rubies on https://rvm.io/binaries/centos for 6.4 and older. But CentOS 7 has been out for more than two and a half years. Compiling ruby from scratch takes a lot of time and having binaries available would speed up a lot of scripts for us.

Please consider adding binaries for CentOS 7.

**Comment by raelgc** [comment]
Hi @ephracis. Thanks for raising this.

Usually this will consume a good time for someone not using the goal OS. Do you consider helping us with this task? Case yes, we can guide you.

**Comment by ephracis** [comment]
Absolutely! Tell me what to do.

**Comment by jrgifford** [comment]
@ephracis OK, here's the scoop!

head over here: https://github.com/rvm/rvm-binary

Edit the config.yml to add the image you want under "distributions": https://github.com/rvm/rvm-binary/blob/master/config.yml#L7

A good resource for vagrant boxes is the [boxcutter project](https://vagrantcloud.com/boxcutter).

Run a test build for your CentOS image to make sure it works, submit a PR adding the config changes and then ping us here on this issue again - one of us will upload the binaries to rvm.io and get it into the next release!

**Comment by jrgifford** [comment]
If you have any questions, ask us here!

**Comment by raelgc** [comment]
In case you'll use your own CentOS 7 environment (so, you don't need a VM):

Go to a new folder and...

1. install ruby version with `--movable`
2. then run `rvm prepare <version>` (of course, replacing `<version>`)
3. create a PR adding the checksums to required files (like described in `prepare` output)

Like @jrgifford said, ping us here again to upload the binaries to rvm.io

**Comment by ephracis** [comment]
Did you get my ping, @raelgc and @jrgifford?

How often do you guys usually release? :)

**Comment by luto** [comment]
I would also be interested in a rvm-binary release containing binaries for CentOS 7 :)

**Comment by jnoss** [comment]
+1, I also agree this would be nice to have

**Comment by raelgc** [comment]
Some binaries were already added by @ephracis. You need to update your RVM to get them. For new binaries (like `2.4.0`), contributions are welcome.

**Comment by hammady** [comment]
@raelgc I commented on the above [PR](https://github.com/rvm/rvm-binary/issues/30) that the binaries are not there yet, any clue?

**Comment by Stono** [comment]
Yeah this would be nice, tired of constant compiles :-)

**Comment by hammady** [comment]
will be available soon @Stono

**Comment by Stono** [comment]
Wonderful :-) Thank you for your work

**Comment by nilarte** [comment]
This helps big time.
Thanks guys.

**Comment by Stono** [comment]
Hola, any update on this?

**Comment by hammady** [comment]
I'm working on it.

**Comment by hammady** [comment]
I'm done. How can I upload the binaries?
I have also created scripts to automate parallel builds using docker swarm
if anyone is interested.

**Comment by duhanebel** [comment]
@hammady have you found a way to upload the binaries you've created? I'm having a similar problem with macOS 10.13 and can't find a way.

**Comment by TomFreudenberg** [comment]
@duhanebel Hi Fabio would you like to deliver OSX binaries?

I am looking for binaries 2.3.latest, 2.4.latest and 2.5.latest (best for 10.12 and 10.13)

Cheers
Tom

**Comment by duhanebel** [comment]
I ended up switching to http://rubies.travis-ci.org which has most of what we needed

**Comment by TomFreudenberg** [comment]
Hi @duhanebel Fabio

thanks for that link.

The problem in my case is, that people from travis have build with fixed path for dynamic libraries:

<pre>
user$ otool -L vendor/ruby/lib/*

vendor/ruby/lib/libruby.2.1.0.dylib:
        /Users/travis/.rvm/rubies/ruby-2.1.0/lib/libruby.2.1.0.dylib (compatibility version 2.1.0, current version 2.1.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
vendor/ruby/lib/libruby.2.1.dylib:
        /Users/travis/.rvm/rubies/ruby-2.1.0/lib/libruby.2.1.0.dylib (compatibility version 2.1.0, current version 2.1.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
vendor/ruby/lib/libruby.dylib:
        /Users/travis/.rvm/rubies/ruby-2.1.0/lib/libruby.2.1.0.dylib (compatibility version 2.1.0, current version 2.1.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)


user$ otool -L vendor/ruby/lib/ruby/2.1.0/x86_64-darwin17.0/psych.bundle

vendor/ruby/lib/ruby/2.1.0/x86_64-darwin17.0/psych.bundle:
        /Users/travis/.rvm/rubies/ruby-2.1.0/lib/libruby.2.1.0.dylib (compatibility version 2.1.0, current version 2.1.0)
        /usr/local/opt/libyaml/lib/libyaml-0.2.dylib (compatibility version 3.0.0, current version 3.5.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
</pre>

I changed this fixed path once for ruby like:

```bash
install_name_tool -change /Users/travis/.rvm/rubies/ruby-2.1.0/lib/libruby.2.1.0.dylib @loader_path/../lib/libruby.2.1.0.dylib ruby
```

now with that

<pre>
user$ otool -L vendor/ruby/bin/ruby

vendor/ruby/bin/ruby:
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1451.0.0)
        @loader_path/../lib/libruby.2.1.0.dylib (compatibility version 2.1.0, current version 2.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
</pre>

Ruby works ... but that is a mess to change all the day after installation.

How do you handle that?

**Comment by ephracis** [comment]
I consider this closed as the binaries for CentOS 7 are present at https://rvm.io/binaries/centos/7/x86_64/

My only wish now is for 2.5 to be added but I think that should be a different issue.
