### ISSUE TITLE
Could ruby version be added to "RVM used your Gemfile for selecting Ruby, it is all fine..."

### ISSUE THREAD

**Issue by joshco** [rvm/rvm#3943]
RVM shows this notice:
https://github.com/rvm/rvm/blob/5070f21752da92beef7a9b4593d33010853cb8e7/scripts/functions/rvmrc_warning#L160

> RVM used your Gemfile for selecting Ruby, it is all fine - Heroku does that too,
> you can ignore these warnings with 'rvm rvmrc warning ignore /vagrant/hero/Gemfile'.
> To ignore the warning for all files run 'rvm rvmrc warning ignore allGemfiles'.

It would be useful if it reported the ruby version it has selected.

**Comment by mpapis** [comment]
try `export rvm_use_flag=2`, if it works add it to your `~/.rvmrc`

**Comment by joshco** [comment]
That works for me.
