### ISSUE TITLE
After update from rvm 1.28.0 to 1.29.1 ignoring env variables in .versions.conf

### ISSUE THREAD

**Issue by Fudoshiki** [rvm/rvm#3944]
I use capistrano-rails

On server in shared folder placed .versions.conf file 
Deploying when installed 1.28.0 works fine, but with 1.29.1 don't apply this file

**Comment by svyatov** [comment]
Same thing for us, but we're using `.ruby-env` file. RMV does not read variables from this file anymore.

**Comment by mpapis** [comment]
files with environment variables now require trusting, you got few options:

1. ignore trusting with `export rvm_trust_rvmrcs_flag=1` in shell configuration or global `rvmrc`
2. `rvm rvmrc trust /path/to/your/file`
3. copy trusting line from your local `$rvm_path/user/rvmrcs` to the remote

Setting up the `3` might be biggest effort - but should be worth the added security.

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
