### ISSUE TITLE
Can't start rails server

### ISSUE THREAD

**Issue by SivaSM** [rvm/rvm#3947]
When I am doing to start the new application I can't start the rails server. When I start server, I am getting this error. Anyone can please give the correct solution for this?
![screenshot from 2017-03-01 11-40-42](https://cloud.githubusercontent.com/assets/19306411/23449328/f2638314-fe7b-11e6-8fa0-3b524df26ccb.png)

**Comment by raelgc** [comment]
Hi @SivaSM.

Please, don't delete all required issues fields while opening an issue.

Your issue is related to `pg` (PostgreSQL) gem version incompatibility, it's not related to RVM at all.

**Comment by SivaSM** [comment]
Hi @raelgc,

I didn't delete all required issues. Latest code after import from git-hub and trying to run the server in local system this error will show.
