### ISSUE TITLE
`rvm get stable` fails because installer script was signed using now-expired gpg key

### ISSUE THREAD

**Issue by mvastola** [rvm/rvm#3956]
I am unable to upgrade (without using command line switches to override signature verification) to the latest stable version of rvm because the script was signed using a gpg subkey that expired yesterday.

For reference:
```
mvastola@vastdesk:~# rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Mon 20 Feb 2017 09:05:42 AM EST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [full]
gpg: Verified 4 messages signed by "Michal Papis (RVM signing) <mpapis@gmail.com>" (key: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3, policy: auto) in the past 1 month, 10 days.  The most recent message was verified 12 minutes, 12 seconds ago.
gpg: Warning: if you think you've seen more than 4 messages signed by this
key, then this key might be a forgery!  Carefully examine the email
address for small variations (e.g., additional white space).  If the key
is suspect, then use 'gpg --tofu-policy bad
"409B6B1796C275462A1703113804BB82D39DC0E3"' to mark it as being bad.

gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Could not update RVM, get some help at #rvm IRC channel at freenode servers.
```

To confirm, I ran:
```
mvastola@vastdesk:~/tmp$ wget https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc 
--2017-03-09 15:56:26--  https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.0.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 833 [text/plain]
Saving to: ‘rvm-installer.asc’

rvm-installer.asc                                    100%[=====================================================================================================================>]     833  --.-KB/s    in 0s      

2017-03-09 15:56:26 (117 MB/s) - ‘rvm-installer.asc’ saved [833/833]

mvastola@vastdesk:~/tmp$ wget https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer
--2017-03-09 15:56:29--  https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.192.133, 151.101.0.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.192.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24062 (23K) [text/plain]
Saving to: ‘rvm-installer’

rvm-installer                                        100%[=====================================================================================================================>]  23.50K  --.-KB/s    in 0.01s

2017-03-09 15:56:29 (1.82 MB/s) - ‘rvm-installer’ saved [24062/24062]

mvastola@vastdesk:~/tmp$ gpg2 rvm-installer.asc
gpg: assuming signed data in 'rvm-installer'
gpg: Signature made Mon 20 Feb 2017 09:05:42 AM EST
gpg:                using RSA key 0xE206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [full]
gpg: Verified 1 message signed by "Michal Papis (RVM signing) <mpapis@gmail.com>" (key: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3, policy: auto) in the past 36 seconds.
gpg: Warning: we've only seen a single message signed by this key!
gpg: Warning: if you think you've seen more than 1 message signed by this key,
then this key might be a forgery!  Carefully examine the email address
for small variations (e.g., additional white space).  If the key is
suspect, then use 'gpg --tofu-policy bad
"409B6B1796C275462A1703113804BB82D39DC0E3"' to mark it as being bad.

gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
```

Suggested fix: Upload a new signature to https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc which signs the same script with the new key.

**Comment by mpapis** [comment]
have you tried `gpg2 --refresh-keys`? we are working on better instructions #3945

**Comment by mvastola** [comment]
@mpapis huh? 
The issue isn't that I don't have the key.. The issue is that the key you used to sign this file expired.

```
mvastola@vastdesk:~/tmp$ gpg2 --verify rvm-installer.asc 
gpg: assuming signed data in 'rvm-installer'
gpg: Signature made Mon 20 Feb 2017 09:05:42 AM EST
gpg:                using RSA key 0xE206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [full]
[ ... SNIP ... ]
```

Also:
```
mvastola@vastdesk:~/tmp$ gpg2 --edit-key 0xE206C29FBF04FF17
pub  rsa4096/0x3804BB82D39DC0E3
     created: 2014-10-28  expires: never       usage: SC
     validity: full
sub  rsa2048/0x85BB5679C71866D7
     created: 2015-11-02  expires: never       usage: E
sub  rsa4096/0xE206C29FBF04FF17
     created: 2014-10-28  expired: 2017-03-08  usage: S
[  full  ] (1). Michal Papis (RVM signing) <mpapis@gmail.com>
```
Particularly:
```
sub  rsa4096/0xE206C29FBF04FF17
     created: 2014-10-28  expired: 2017-03-08  usage: S
```

**Comment by mvastola** [comment]
And yes, I did do that. No difference.

**Comment by TangRufus** [comment]
Try `curl -sSL https://rvm.io/mpapis.asc | gpg --import -`

**Comment by mvastola** [comment]
@TangRufus, there we go!
It looks like the issue is the subkey was -- in fact -- updated but was never pushed to any gpg keyservers. So refreshing the keys did nothing.

I'm going to see if I can send the this key to keyservers myself. Otherwise @mpapis should.

**Comment by mvastola** [comment]
There we go! [Now](https://pgp.mit.edu/pks/lookup?search=0xE206C29FBF04FF17&op=vindex) `gpg2 --refresh-keys` should work for anyone with this problem. 

Despite this happening only once every few years, it might be a good idea to code in a retry on the `gpg2 --verify`, but with running `gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3` if the first one fails.

Going to close this, since it's working now though and (though users might run into my initial error) there's no real way to fix that for them.

**Comment by mpapis** [comment]
Added an entry to my calendar to update the expiration date earlier next time.

**Comment by mvastola** [comment]
@mpapis, I guess that would be helpful, but the bigger issue is that you forgot to send your key to the keyservers.  And though (IIRC), the instructions on [rvm.io](http://rvm.io) were at one point to get the key from the URL https://rvm.io/mpapis.asc at one, nowadays they say to use a certain keyserver (likely because it is more secure) which left me with no source for an updated key.

In any case though, users who aren't familiar with got won't even realize that they need to get an updated key, which is why I suggest working that into the `rvm get` script. 

One last idea: instead of simply adding it to your calendar, a much more robust solution could be to run a check inside `sign_releases.sh` to fail if the key expires in the next 6-ish months. Just a thought..

**Comment by mpapis** [comment]
@mvastola if it was just forgotten... I'm so overloaded with tasks... but I'm working on my schedule to bring more time back to RVM.

We are working on the instructions for users - I do not dare running `gpg2 --refresh-keys` for users, it has to be their thing, it can be ~~cron script (not a recommendation)~~, manual habit, or extra tool. But automation in security is not always a good solution. Human element is the most important part nowdays, maybe AI will solve this in future, but for now it's our own responsibility 

As for the idea about the signing script - the next expiry is in 2 years, I hope till then we can all move to RVM 2 ;) the problems there will be different.

**Comment by mvastola** [comment]
@mpapis, oh, don't misunderstand me: that wasn't a criticism of you. This is open source.. as far as I'm concerned, it's not my place (or anyone's for that matter) to tell you you need to spend more time on this project. Anyone who leads a project inevitably set some expectations for their userbase, but none of them involves dedicating their lives to the project. In the end, you're guaranteed as much as you put in. 

I only meant to point out that the actual issue here (i.e. the thing you didn't do in time) was *upload* the key. You created the new key on 2/25/17, before the old one expired (on 3/8/17) which would have been fine for seamless use had it been uploaded.

I don't personally agree with you about automatic key retrieval being disadvantageous (though to be clear, I would only advocate for calling `--recv-keys` on the particular key in question rather than `--refresh-keys` on the entire public keychain), however I agree that a notice on the terminal providing instructions on solving the problem manually is a satisfactory workaround.

There's nothing about updating a gpg key from a keyserver that benefits from any sort of manual scrutiny.  (Any existing trust levels are preserved and trust signatures are merged.) I imagine there's a very minute chance of hash collisions with IDs that probably creates the chance for a conflict between a local key and a different keyserver key, but I'm sure `gpg` already handles these cases securely as it is.  

I just don't see my proposal as any different than the aspects of `rvm` (which are equally automated) that verify the integrity of ruby(gems) source packages by fetching their sha512 sums and then hashing the tar file once downloaded. This just uses a different backend (gpg) for the verification which provides a second function. If the issue is just the idea of screwing with the user's personal keyring, another idea is to use `gpg2 --homedir /usr/local/rvm/etc/gpg ...` to segregate things.

This is all just my 2¢ and it's ultimately your call, but thought I'd share my thoughts.

Regardless, thanks for making this fantastic project a reality. :+1:

**Comment by mpapis** [comment]
@mvastola, the warning idea sounds good, would you be able to open a PR with it?

**Comment by mvastola** [comment]
You mean in `sign_releases.sh`? Probably, but not sure when I could promise it. (Definitely by the next time your key expires though! :-p)

**Comment by mpapis** [comment]
@mvastola not the script, I meant the messages that show up when rvm does key checks - we can extend the messages there to include `--recv-keys` and the update via file with `--import`.
