### ISSUE TITLE
Third Party App RVM Ruby Gem Load Error

### ISSUE THREAD

**Issue by daBee** [rvm/rvm#3959]
I have a third party application (Launchbar on El Capitan) that I'm using to call a ruby script.  I am using 2.2.5, so it > minimum version.  Launchbar goes to load a gem called `clipboard`, but throws an error.  

My ruby shebang is legit, and tested to show that it should grab the right ruby:

`#!/Users/rich/.rvm/rubies/default/bin/ruby`

This is validated in the error as well.  It simply cannot load the gem, and I have no clue why.  

**Reproduction**
Run the Launchbar script with the single parameter.  It launches the ruby script expecting to use the system clipboard (through the gem `clipboard` to paste into a text file.  It throws an error in the console, pasted below.  

I'm expecting to run the Launchbar script with the single parameter.  It launches the ruby script expecting to use the system clipboard (through the gem `clipboard`, and on with its pasting into a text file.

**Actual**

Run the Launchbar script with the single parameter.  It stops with the console error:

		2017-03-21 4:35:40.808 PM LaunchBar[354]: RF Send to Fixes (com.viaduct-productions.LaunchBar.action.SendToFixes): Script Error: </Users/rich/.rvm/rubies/default/bin/ruby /Users/rich/Library/Application Support/LaunchBar/Actions/RF_SendToFixes.lbaction/Contents/Scripts/default.rb OK, this is trial number three>
		/Users/rich/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- clipboard (LoadError)
			from /Users/rich/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
			from /Users/rich/Library/Application Support/LaunchBar/Actions/RF_SendToFixes.lbaction/Contents/Scripts/default.rb:12:in `<main>'

**Environment**
		ruby-2.2.5:

			system:
				uname:        "Darwin HQ.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Jan  9 23:07:29 PST 2017; root:xnu-3248.60.11.2.1~1/RELEASE_X86_64 x86_64"
				name:         "OSX"
				version:      "10.11"
				architecture: "x86_64"
				bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)"
				zsh:          "/bin/zsh => zsh 5.0.8 (x86_64-apple-darwin15.0)"
				remote path:  "osx/10.11/x86_64"

			rvm:
				version:      "rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
				updated:      "22 days 3 hours 22 minutes 56 seconds ago"
				path:         "/Users/rich/.rvm"
				autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

			ruby:
				interpreter:  "ruby"
				version:      "2.2.5p319"
				date:         "2016-04-26"
				platform:     "x86_64-darwin15"
				patchlevel:   "2016-04-26 revision 54774"
				full_version: "ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin15]"

			homes:
				gem:          "/Users/rich/.rvm/gems/ruby-2.2.5"
				ruby:         "/Users/rich/.rvm/rubies/ruby-2.2.5"

			binaries:
				ruby:         "/Users/rich/.rvm/rubies/ruby-2.2.5/bin/ruby"
				irb:          "/Users/rich/.rvm/rubies/ruby-2.2.5/bin/irb"
				gem:          "/Users/rich/.rvm/rubies/ruby-2.2.5/bin/gem"
				rake:         "/Users/rich/.rvm/gems/ruby-2.2.5/bin/rake"

			environment:
				PATH:         "/Users/rich/.rvm/gems/ruby-2.2.5/bin:/Users/rich/.rvm/gems/ruby-2.2.5@global/bin:/Users/rich/.rvm/rubies/ruby-2.2.5/bin:/usr/local/opt/postgresql-9.5/bin:/usr/local/sbin:/usr/sbin:/usr/X11/bin:/usr/local/bin:/usr/bin:/opt/local/bin:/opt/local/sbin:/users/rich/.rvm/rubies/default:/Users/rich/.rvm/gems/ruby-2.2.5/bin:/Users/rich/.rvm/gems/ruby-2.2.5@global/bin:/Users/rich/.rvm/rubies/ruby-2.2.5/bin:/usr/local/opt/postgresql-9.5/bin:/usr/local/sbin:/usr/sbin:/usr/X11/bin:/usr/local/bin:/usr/bin:/opt/local/bin:/opt/local/sbin:/users/rich/.rvm/rubies/default:/Users/rich/.rvm/gems/ruby-2.2.5/bin:/Users/rich/.rvm/gems/ruby-2.2.5@global/bin:/Users/rich/.rvm/rubies/ruby-2.2.5/bin:/Users/rich/.rvm/bin:/usr/local/opt/postgresql-9.5/bin:/usr/local/sbin:/usr/sbin:/usr/X11/bin:/usr/local/bin:/usr/bin:/opt/local/bin:/opt/local/sbin:/users/rich/.rvm/rubies/default:/usr/local/opt/postgresql-9.5/bin:/usr/local/sbin:/usr/sbin:/usr/X11/bin:/usr/local/bin:/usr/bin:/opt/local/bin:/opt/local/sbin:/users/rich/.rvm/rubies/default:/usr/local/opt/postgresql-9.5/bin:/usr/local/sbin:/usr/sbin:/usr/X11/bin:/usr/local/bin:/usr/bin:/opt/local/bin:/opt/local/sbin:/users/rich/.rvm/rubies/default:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin"
				GEM_HOME:     "/Users/rich/.rvm/gems/ruby-2.2.5"
				GEM_PATH:     "/Users/rich/.rvm/gems/ruby-2.2.5:/Users/rich/.rvm/gems/ruby-2.2.5@global"
				MY_RUBY_HOME: "/Users/rich/.rvm/rubies/ruby-2.2.5"
				IRBRC:        "/Users/rich/.rvm/rubies/ruby-2.2.5/.irbrc"
				RUBYOPT:      ""
				gemset:       ""

**Comment by pkuczynski** [comment]
Could you please check if the gem is installed globally for ruby 2.2.5:

`ls ~/.rvm/gems/ruby-2.2.5/gems/`

**Comment by daBee** [comment]
It is indeed.  `clipboard-1.1.1`

**Comment by mpapis** [comment]
change the shebang to:

```bash
#!/Users/rich/.rvm/wrappers/default/ruby
```
