### ISSUE TITLE
Unable to save project-specific irb history

### ISSUE THREAD

**Issue by ToadJamb** [rvm/rvm#3968]
## Description

I am not able to use project-specific irb history files because rvm hard codes the history file path and name.

## Steps to reproduce

1. create `~/.irbrc`
``` # ~/.irbrc
IRB.conf[:HISTORY_FILE] = File.expand_path(Dir.pwd, '.irb-history')
```

2.
```
$ cd ~
$ cd my-project
$ irb
> puts 'hello'
> exit
```

## Expected behavior

I expect to see `puts 'hello'` and `exit` as the last 2 entries in `~/my-project/.irb-history`.

## Actual behavior

I see `puts 'hello'` and `exit` as the last 2 entries in `~/.irb-history`.

## Environment info

Irrelevant. The offending code is in `scripts/irbrc.rb` on master. I looked right before creating this issue.

## Proposed solution

The easiest solution is to modify the readline setup to use IRB.conf[:HISTORY_FILE] if it exists (and maybe set it if it does not). This would also require that the user's `irbrc` file be loaded before readline is set up. It seems like the readline setup could happen last, with the rvm-specific settings still being loaded prior to the user's irbrc. Basically, the setup order would change to: rvm configuration (so it stays ahead of user's irbrc), load user's irbrc, then configure readline.

**Comment by mpapis** [comment]
please check `$rvm_path/scripts/irbrc.rb`... maybe we need to update this file?

**Comment by ToadJamb** [comment]
I'm happy so submit a patch if it will help facilitate conversation. I have made the proposed changes locally, but obviously I'll have to make those changes every time I update rvm.

**Comment by mpapis** [comment]
@ToadJamb please show the changes, it looks like the `irbrc.rb` rvm is providing could be much simplified.

**Comment by ToadJamb** [comment]
@mpapis I opened a pull request: https://github.com/rvm/rvm/pull/3969

I didn't take time to evaluate what could be simplified. I just saw that it appeared to be doing 3 distinct things and modified the order of those 3 operations, combined with a minor change to support the use of `IRB.conf[:HISTORY_FILE]`.
