### ISSUE TITLE
RVM Not installing on Ubuntu 16.04, x64

### ISSUE THREAD

**Issue by t0dd** [rvm/rvm#3977]
Ruby 2.3.1p112 is currently installed

After installing the mpapis public key I ran

\curl -sSL https://get.rvm.io | bash -s stable

and the following error occurs: 
mktemp: failed to create file via template ‘/usr/share/rvm-exec-test.XXXXXX’: Permission denied

attempted to run
sudo \curl -sSL https://get.rvm.io | bash -s stable

same error occurred.

**Comment by raelgc** [comment]
Hi @t0dd and thanks for reporting this issue.

Please, can you try [our Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by t0dd** [comment]
That worked! Thank you!

**Comment by kohrVid** [comment]
This is still an issue in newer versions of Debian. The instructions in [this SO answer](https://unix.stackexchange.com/a/394986) worked for me even though the installation isn't supposed to be run using root access (the `chown` command can be used to change the owners of the relevant rvm and bundler folders as a workaround when installing gems as a standard user later). Also noticed that this doesn't seem to be fully compatible with the Stretch's version OpenSSL so the following command had to be run when installing older rubies:

    rvm pkg install openssl

**Comment by AndreG-P** [comment]
I ran into the same problem. In my case, I had rvm installed previously and missed to unset the old `rvm_path`. I found that solution in the [same SO thread](https://unix.stackexchange.com/a/440584) posted by @kohrVid.

So my solution was
``` bash
~$ unset rvm_path
~$ curl -sSL https://get.rvm.io | bash -s stable
```

On Ubuntu 17.10
RVM stable version: 1.29.4

**Comment by Aetherus** [comment]
As @AndreG-P said, unsetting `rvm_path` works. I also unset all the variables starting with `rvm_` before installing new rvm.

**Comment by dmitryfry** [comment]
> I ran into the same problem. In my case, I had rvm installed previously and missed to unset the old `rvm_path`. I found that solution in the [same SO thread](https://unix.stackexchange.com/a/440584) posted by @kohrVid.
> 
> So my solution was
> 
> ```shell
> ~$ unset rvm_path
> ~$ curl -sSL https://get.rvm.io | bash -s stable
> ```
> 
> On Ubuntu 17.10
> RVM stable version: 1.29.4

thx!

**Comment by hiro-riveros** [comment]
> I ran into the same problem. In my case, I had rvm installed previously and missed to unset the old `rvm_path`. I found that solution in the [same SO thread](https://unix.stackexchange.com/a/440584) posted by @kohrVid.
> 
> So my solution was
> 
> ```shell
> ~$ unset rvm_path
> ~$ curl -sSL https://get.rvm.io | bash -s stable
> ```
> 
> On Ubuntu 17.10
> RVM stable version: 1.29.4

2020 and still working! 🎉
