### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by oldfritter** [rvm/rvm#3984]
when you run
```
curl -sSL https://get.rvm.io | bash -s stable
```
if you got this notice
```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html
```

ca-certificates  need to be installed
ubuntu 
```
   apt-get install ca-certificates 
```

**Comment by pkuczynski** [comment]
Added to the documentation https://github.com/rvm/rvm-site/commit/07677e9492e496928e202b9f42210c3c62a3608e

Thanks!

**Comment by chrissyast** [comment]
I have this same problem on Windows 7. How does one get ca-certificates on Windows?
