### ISSUE TITLE
Problem installing Ruby

### ISSUE THREAD

**Issue by sophiaaar** [rvm/rvm#3995]
Below is the output from 'rvm install ruby-2.4.0 --debug'

> ruby-2.4.0 - install
Log prefix: /Users/sophia/.rvm/log/1492529475_ruby-2.4.0/
Log filesystem: local,
Log max name length: 250
Log file: /Users/sophia/.rvm/log/1492529475_ruby-2.4.0/remove.src.log
[2017-04-18 16:31:15] __rvm_rm_rf
__rvm_rm_rf () 
{ 
    __rvm_rm_rf_verbose "$@"
}
current path: /Users/sophia
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sophia/.rvm/bin
command(2): __rvm_rm_rf /Users/sophia/.rvm/src/ruby-2.4.0
ruby-2.4.0 - #removing src/ruby-2.4.0..
ruby-2.4.0 - #already removed rubies/ruby-2.4.0
Searching for binary rubies, this might take some time.
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.12/x86_64/ruby-2.4.0.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/ruby-2.4.0.tar.bz2
Travis binaries for OSX are not movable and can't be used outside of Travis environment. Skip that source.
No remote file name found
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/osx/10.12/x86_64/ruby-2.4.0.tar.bz2
Remote file does not exist https://s3.amazonaws.com/jruby.org/downloads/ruby-2.4.0.tar.bz2
Travis binaries for OSX are not movable and can't be used outside of Travis environment. Skip that source.
No remote file name found
No binary rubies available for: osx/10.12/x86_64/ruby-2.4.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Free disk space 673340MB, required 440MB.
__rvm_setup_compile_environment_setup ruby-2.4.0
rvm_autolibs_flag=enable
__rvm_setup_compile_environment_movable_early ruby-2.4.0
__rvm_setup_compile_environment_system_early ruby-2.4.0
__rvm_setup_compile_environment_requirements ruby-2.4.0
Checking requirements for osx.
requirements code for osx loaded
requirements lib type set to osx_brew
brew seems to be writable
Found required packages: autoconf, automake, libtool, pkg-config, coreutils, libyaml, readline, libksba, openssl@1.1.
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sophia/.rvm/bin
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libyaml )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/readline )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/libksba )
rvm_configure_flags+=( --with-opt-dir=/usr/local/opt/openssl@1.1 )
Certificates in '/usr/local/etc/openssl@1.1/cert.pem' are already up to date.
Requirements installation successful.
__rvm_setup_compile_environment_movable ruby-2.4.0
__rvm_setup_compile_environment_parse_name ruby-2.4.0
__rvm_setup_compile_environment_system ruby-2.4.0
__rvm_setup_compile_environment_architectures ruby-2.4.0
rvm_architectures(0):.
__rvm_setup_compile_environment_gcc47plus ruby-2.4.0
__rvm_setup_compile_environment_bison ruby-2.4.0
__rvm_setup_compile_environment_flags_docs ruby-2.4.0
__rvm_setup_compile_environment_flags_shared_static ruby-2.4.0
__rvm_setup_compile_environment_flags_threads ruby-2.4.0
__rvm_setup_compile_environment_compatibility_flag ruby-2.4.0
found compiler: gcc
Installing Ruby from source to: /Users/sophia/.rvm/rubies/ruby-2.4.0, this may take a while depending on your cpu(s)...
ruby-2.4.0 - #downloading ruby-2.4.0, this may take a while depending on your connection...
fetch https://cache.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.bz2 => ruby-2.4.0.tar.bz2
Archive checksum matched, not downloading
Downloaded archive checksum matched.
Log file: /Users/sophia/.rvm/log/1492529475_ruby-2.4.0/extract.log
[2017-04-18 16:31:30] __rvm_package_extract
__rvm_package_extract () 
{ 
    rvm_debug __rvm_package_extract:$#: "$@";
    \typeset __tempdir __path __file __return;
    __return=0;
    __tempdir="$( TMPDIR="${rvm_tmp_path}" mktemp -d -t rvm-tmp.XXXXXXXXX )";
    __rvm_package_extract_run "$1" "$__tempdir" || __return=$?;
    if (( __return == 0 )); then
        for __path in "$__tempdir"/*;
        do
            __file="${__path##*/}";
            if [[ -n "${__file}" && -e "$2/${__file}" ]]; then
                \command \rm -rf "$2/${__file}" || __return=$?;
            fi;
            \command \mv -f "${__path}" "$2/" || __return=$?;
        done;
    fi;
    if [[ -n "$__tempdir" ]]; then
        \command \rm -rf "$__tempdir";
    fi;
    return $__return
}
current path: /Users/sophia/.rvm/src
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sophia/.rvm/bin
command(3): __rvm_package_extract /Users/sophia/.rvm/archives/ruby-2.4.0.tar.bz2 /Users/sophia/.rvm/tmp/rvm_src_26665
ruby-2.4.0 - #extracting ruby-2.4.0 to /Users/sophia/.rvm/src/ruby-2.4.0.....
__rvm_rm_rf already gone: /Users/sophia/.rvm/src/ruby-2.4.0
Patch name 'optional', expanded_name(s) ''.
Patch name 'default', expanded_name(s) ''.
Patch name 'osx', expanded_name(s) ''.
All found patches(0): .
Log file: /Users/sophia/.rvm/log/1492529475_ruby-2.4.0/configure.log
[2017-04-18 16:31:33] ./configure
current path: /Users/sophia/.rvm/src/ruby-2.4.0
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sophia/.rvm/bin
command(5): ./configure --prefix=/Users/sophia/.rvm/rubies/ruby-2.4.0 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl@1.1 --disable-install-doc --enable-shared
ruby-2.4.0 - #configuring..............................................................
Error running './configure --prefix=/Users/sophia/.rvm/rubies/ruby-2.4.0 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl@1.1 --disable-install-doc --enable-shared',
showing last 15 lines of /Users/sophia/.rvm/log/1492529475_ruby-2.4.0/configure.log
checking whether dtrace needs post processing... no
checking for __builtin_setjmp... (cached) no
checking for _setjmpex as a macro or function... no
checking for _setjmp as a macro or function... yes
checking for sigsetjmp as a macro or function... yes
checking for setjmp type... _setjmp
checking for prefix of external symbols... _
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking if make is GNU make... /usr/local/lib/ruby/gems/2.4.0/gems/make-0.3.1/bin/make:4:in `<top (required)>': undefined local variable or method `make' for main:Object (NameError)
	from /usr/local/bin/make:22:in `load'
	from /usr/local/bin/make:22:in `<main>'
no
checking for safe null command for make... configure: error: no candidate for safe null command
There has been an error while running configure. Halting the installation.
__rvm_rm_rf already gone: /Users/sophia/.rvm/tmp/26665*

## Description

I was following the instructions from this page http://railsapps.github.io/installrubyonrails-mac.html and I did it from a fresh install of rvm

Looks similar to https://github.com/rvm/rvm/issues/3978

## Environment info

system:

  system:
    uname:        "Darwin Sophias-MacBook-Pro.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote path:  "osx/10.12/x86_64"

  rvm:
    version:      "rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "38 minutes 9 seconds ago"
    path:         "/Users/sophia/.rvm"
    autolibs:     "[enable] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/local/bin/ruby"
    irb:          "/usr/local/bin/irb"
    gem:          "/usr/local/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/sophia/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by pkuczynski** [comment]
If you suggest that this is similar to #3978, did you tried to install xcode build tools?

**Comment by sophiaaar** [comment]
Yes, Xcode is up to date and the command line tools are installed. I've opened up Xcode to complete the installation

**Comment by pkuczynski** [comment]
Could you please gist `/Users/sophia/.rvm/log/1492529475_ruby-2.4.0/configure.log`?

**Comment by sophiaaar** [comment]
here you go https://gist.github.com/sophiaaar/227593e80c36015d0986bd861e81a1b5

**Comment by pkuczynski** [comment]
```
make --version
which make
```

Do you use Homebrew?

**Comment by sophiaaar** [comment]
Yes I use Homebrew

**Comment by pkuczynski** [comment]
Show me:

```
make --version
which make
brew list | grep automake
```

**Comment by pkuczynski** [comment]
I assume you restarted terminal after installing XCode...

**Comment by sophiaaar** [comment]
Sophias-MacBook-Pro:~ sophia$ make --version
/usr/local/lib/ruby/gems/2.4.0/gems/make-0.3.1/bin/make:4:in `<top (required)>': undefined local variable or method `make' for main:Object (NameError)
	from /usr/local/bin/make:22:in `load'
	from /usr/local/bin/make:22:in `<main>'


Sophias-MacBook-Pro:~ sophia$ which make
/usr/local/bin/make

Sophias-MacBook-Pro:~ sophia$ brew list | grep automake
automake

and yes I restarted the terminal. I've restarted my machine multiple times during this process

**Comment by pkuczynski** [comment]
Ok, so I guess this is your problem, that for whatever reason it tries to use make from make gem: `/usr/local/lib/ruby/gems/2.4.0/gems/make-0.3.1/`

Could you please remove this folder and try again with the build?

**Comment by sophiaaar** [comment]
no luck :/ I deleted the folder, and even uninstalled then reinstalled make with brew, and the same error appears. :(

**Comment by pkuczynski** [comment]
What does `make --version` say now?

**Comment by sophiaaar** [comment]
Sophias-MacBook-Pro:~ sophia$ make --version
/usr/local/bin/make:22:in `load': cannot load such file -- /usr/local/lib/ruby/gems/2.4.0/gems/make-0.3.1/bin/make (LoadError)
	from /usr/local/bin/make:22:in `<main>'

**Comment by sophiaaar** [comment]
the last main had < >

**Comment by pkuczynski** [comment]
Remove file `/usr/local/bin/make` and run `brew install automake`

**Comment by sophiaaar** [comment]
it worked! I now have Ruby :) Thanks so much for helping me!

**Comment by pkuczynski** [comment]
You welcome :) This was not an RVM issue. It must have been something wrong with your system, especially make utility.

**Comment by vishnu-vv** [comment]
My system was using make from `/Users/vishnu_vv/.rvm/gems/ruby-2.4.0/bin/make`.
I tried uninstalling the gem make by running `gem uninstall make`.
And then tried `rvm install 2.5.0`.
It worked 👍 

Thanks.
