### ISSUE TITLE
Cannot install Rails 5 

### ISSUE THREAD

**Issue by pareshsolanki29** [rvm/rvm#3996]
pareshs-MBP:~ pareshsolanki$ rvm install 2.4.0
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.12/x86_64/ruby-2.4.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx_brew.
Installing requirements for osx_brew.
Updating system.........
Installing required packages: autoconf, automake, libtool, pkg-config, coreutils, libyaml, readline, libksba, openssl@1.1....
Error running 'requirements_osx_brew_libs_install autoconf automake libtool pkg-config coreutils libyaml readline libksba openssl@1.1',
showing last 15 lines of /Users/pareshsolanki/.rvm/log/1492631929_ruby-2.4.0/package_install_autoconf_automake_libtool_pkg-config_coreutils_libyaml_readline_libksba_openssl@1.1.log
++ case "$1" in
++ [[ -t 1 ]]
++ return 1
++ printf %b 'There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation\n'
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
++ case "$_system_version" in
++ return 1
Requirements installation failed with status: 1.

**Comment by pkuczynski** [comment]
First of all in the future please comply with the format of the reported issue. Otherwise its hard to help.

Your problem seems to be with installing required packaged. Please try to run manually following command:

`brew install autoconf automake libtool pkg-config coreutils libyaml readline libksba openssl@1.1`

And fix all the issues which may arise. Then retry installing ruby 2.4.0

**Comment by pareshsolanki29** [comment]
Hello Piotr, this command didnt work I still have an error
``````
pareshs-MBP:~ pareshsolanki$ brew install autoconf automake libtool pkg-config coreutils libyaml readline libksba openssl@1.1
Error: No available formula with the name "autoconf" 
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
`````````

Thank You.

**Comment by pkuczynski** [comment]
Are you sure that you have latest brew installed? What does following commands output?

```
brew --version
brew search autoconf
```

In my case:

```
$ brew --version
Homebrew 1.1.13
Homebrew/homebrew-core (git revision be82; last commit 2017-04-19)

$ brew search autoconf
autoconf ✔                              autoconf-archive                        autoconf@2.13                           autoconf@2.64
```

**Comment by pareshsolanki29** [comment]
I tried the command i am missing autoconf

`````
pareshs-MBP:~ pareshsolanki$ brew --version
Homebrew 1.1.13-3571-gb6b98f48
Homebrew/homebrew-core (git revision b6b98; last commit 2017-04-19)
pareshs-MBP:~ pareshsolanki$ brew search autoconf
No formula found for "autoconf".
Closed pull requests:
autoconf-archive 2017.03.21 (https://github.com/Homebrew/homebrew-core/pull/11422)
tesseract: fix missing build dependency to autoconf-archive (https://github.com/Homebrew/homebrew-core/pull/8984)
profanity: depend on autoconf-archive (https://github.com/Homebrew/homebrew-core/pull/5980)
autoconf-archive 2016.09.16 (https://github.com/Homebrew/homebrew-core/pull/4890)
pareshs-MBP:~ pareshsolanki$ 
````````

**Comment by pkuczynski** [comment]
Hmm, you have a strange version of Homebrew. Maybe you should reinstall Homebrew before continue?

**Comment by mpapis** [comment]
@pareshsolanki29 did Homebrew remove `autoconf` in master?

**Comment by pkuczynski** [comment]
@mpapis I checked. They did not. It must be a problem with @pareshsolanki29 installation of hombrew as mine version shows different git hash.

You can also verify on some online searches:
* http://brewformulas.org/search?search%5Bterm%5D=autoconf
* http://braumeister.org/search/autoconf
* http://searchbrew.com

**Comment by pareshsolanki29** [comment]
Thanks Piotr, works perfect now.
