### ISSUE TITLE
Cannot run first script in RubyMine and still get PATH not set up properly error

### ISSUE THREAD

**Issue by zbomani03** [rvm/rvm#3998]
## Description

Cannot run first script in RubyMine and still get `PATH is not properly set up` error

Following steps of Cucumber and cheese book.  I have outlined the steps taken to fix but not solved. 

## Steps to reproduce

1. Installed Xcode 8 on Mac OS 10.12. and command line tools.
2. Installed RVM using `curl -L https://get.rvm io | bash -s stable`
3. `rvm list known` returns list of rubies available, however,

I keep getting:
```
Warning! PATH is not properly set up, '/Users/zbomani/.rvm/gems/ruby-2.1.10/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.1.10'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
```

4. I follow the fix steps above and ran `rvm get stable --auto-dotfiles`.  and ran `rvm use ruby-2.1.10` which returns `Using /Users/zbomani/.rvm/gems/ruby-2.1.10`

## Expected behavior

I expect the error to go away in my terminal session, and I expect my first script to execute successfully in RubyMine

I installed ruby 2.4.0
`ruby -v` is `2.4.0`

```
require 'rubygems'
require 'watir-webdriver'
browser = Watir::Browser.new :firefox
browser.goto 'http://www.apple.com'
```

## Actual behavior
When I execute the script it keeps returning the following error:

[RubyMineError.pdf](https://github.com/rvm/rvm/files/950039/RubyMineError.pdf)

```
/Users/zbomani/.rvm/rubies/ruby-2.2.6/bin/ruby -e $stdout.sync=true;$stderr.sync=true;load($0=ARGV.shift) /Users/zbomani/RubymineProjects/learn_watir/first_script.rb
/Users/zbomani/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- watir-webdriver (LoadError)
	from /Users/zbomani/.rvm/rubies/ruby-2.2.6/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/zbomani/RubymineProjects/learn_watir/first_script.rb:2:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'

Process finished with exit code 1
```

**Comment by mpapis** [comment]
You are using:
  `/Users/zbomani/.rvm/rubies/ruby-2.2.6/bin/ruby`,

try instead:
  `/Users/zbomani/.rvm/wrappers/ruby-2.2.6/ruby`

it will load the proper environment and should fix issue with `PATH is not properly set up`.

**Comment by zbomani03** [comment]
Awesome sauce….Thank you.
