### ISSUE TITLE
rb_thread_fd_close patch for ruby 2.3.4

### ISSUE THREAD

**Issue by masterkain** [rvm/rvm#4008]
https://www.ruby-lang.org/en/news/2017/03/30/ruby-2-3-4-released/

ruby 2.3.4 has a known problem about rb_thread_fd_close.

some mainstream (ubuntu) package maintaners are applying this patch in their packages, should we do this as well?

**Comment by mpapis** [comment]
yes we should, could you open a PR with the patch? let us know if you need any guidance.
