### ISSUE TITLE
Error while installing Ruby on Cygwin

### ISSUE THREAD

**Issue by victorlcampos** [rvm/rvm#4011]
Hi Guys,
First, sorry for my English, it's not my first language.

I'm trying install ruby (2.3.3, 2.4.1, 2.3.4) using rvm  on Windows but I'm getting a lot of errors (probably my fault).

Here the logs:

https://gist.github.com/victorlcampos/aa3bd837382e5d2095ca49e91e208179

When I run rvm install 2.4.1 the error occurs on install part

**Comment by pkuczynski** [comment]
Can you check which version of gcc do you have installed?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
