### ISSUE TITLE
Failing to install ruby 2.3.4 on rvm 1.29.1 due to openssl issue

### ISSUE THREAD

**Issue by ardahaal** [rvm/rvm#4012]
## Description

Hello. I cannot install ruby 2.3.4 with rvm 1.29.1 (branch master) on antergos (arch). I've got two versions of openssl - 1.1.0.e-1 and 1.0.2.k-3. I've spent on this few hours already and cannot find proper solution. In addition I have to use ruby 2.3.4 for proper deployment in one of my current projects.

## Instalation with openssl 1.1

* [rvm install 2.3.4 --debug](https://gist.github.com/ardahaal/05bdfe2534421fcd9442698607336be0)
* [make.log](https://gist.github.com/ardahaal/71f1121e2eb9d7c7d7f703772925fdeb)

## Instalation with openssl 1.0

* [rvm install 2.3.4 --with-openssl-dir=/usr/include/openssl-1.0 --debug](https://gist.github.com/ardahaal/d964527dfdb164c5911c6a0b27a238f2)
* [make.log](https://gist.github.com/ardahaal/9bfbf5570dfe267c6720d2445f6789d7)

Any ideas? Pretty please?

**Comment by ljachymczyk** [comment]
Same thing here.

**Comment by sxlijin** [comment]
Same issue with `rvm install 2.3.3` and OpenSSL 1.1.0e:

~~~
In file included from ossl.h:57:0,
                 from ossl_hmac.c:12:
/usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
 #error "This file is obsolete; please update your software."
  ^~~~~
~~~

**Comment by ardahaal** [comment]
@sxlijin Thank you kindly. Worked like a charm!
