### ISSUE TITLE
unable to install latest master

### ISSUE THREAD

**Issue by jongross** [rvm/rvm#4015]
## Description

I am unable to install the latest version due to an error about '.github/: unable to update time for .github'.

## Steps to reproduce

issue a 'rvm get stable'

## Expected behavior

I would expect to upgrade to the latest version

## Actual behavior

* [command](https://gist.github.com/jongross/e1782f53f0255df68b6ed7b15534343f)

## Environment info

$ rvm info

ruby-2.4.0-rc1:

  system:
    uname:       "Darwin SEA-ML-GROSS1 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64"
    system:      "osx/10.12/x86_64"
    bash:        "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:         "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"

  rvm:
    version:      "rvm 1.28.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]"
    updated:      "3 months 22 days 22 hours 47 minutes 30 seconds ago"
    path:         "/usr/local/rvm"

  ruby:
    interpreter:  "ruby"
    version:      "2.4.0rc1"
    date:         "2016-12-12"
    platform:     "x86_64-darwin16"
    patchlevel:   "2016-12-12 trunk 57064"
    full_version: "ruby 2.4.0rc1 (2016-12-12 trunk 57064) [x86_64-darwin16]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.4.0-rc1"
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.0-rc1"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.0-rc1/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.4.0-rc1/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.4.0-rc1/bin/gem"
    rake:         "/usr/local/rvm/gems/ruby-2.4.0-rc1/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.4.0-rc1/bin:/usr/local/rvm/gems/ruby-2.4.0-rc1@global/bin:/usr/local/rvm/rubies/ruby-2.4.0-rc1/bin:/usr/local/rvm/bin:/Users/gross/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.4.0-rc1"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.4.0-rc1:/usr/local/rvm/gems/ruby-2.4.0-rc1@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.4.0-rc1"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.4.0-rc1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by pkuczynski** [comment]
Could you please gist result of `rvm get master --debug`

**Comment by jongross** [comment]
you bet:

https://gist.github.com/jongross/00b26de7be8d8f8b23486e2f26de729f

**Comment by pkuczynski** [comment]
Here comes your problem:

```
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
Running(1): No PGP url given, skipping.
Running(1): Running(5): tar xzf /usr/local/rvm/archives/rvm-master.tgz --strip-components 1
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
```

Can you run the download process manually and see it it works?

```
curl -O https://github.com/rvm/rvm/archive/master.tar.gz
ls -al master.*
tar xzf master.tar.gz
```

**Comment by jongross** [comment]
Ah.

`$ curl -O https://github.com/rvm/rvm/archive/master.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   115    0   115    0     0    717      0 --:--:-- --:--:-- --:--:--   718

gross@SEA-ML-GROSS1: ~
$ cat master.tar.gz
<html><body>You are being <a href="https://codeload.github.com/rvm/rvm/tar.gz/master">redirected</a>.</body></html>

gross@SEA-ML-GROSS1: ~`

Appears curl isn't following the redirect.

**Comment by pkuczynski** [comment]
So your problem is fixed?

**Comment by jongross** [comment]
Yes, doing a manual upgrade fixed it.  I'm still a bit puzzled as to how it got jacked up in the first place, but it's working now.

Thanks for the assist

**Comment by pkuczynski** [comment]
Hmm, not sure either. For your future reference, using `rvm get master` usually helps ;)

**Comment by vwal** [comment]
`curl -LO https://github.com/rvm/rvm/archive/master.tar.gz` works (follows the redirect) .. but still a manual update, of course.

**Comment by benoist** [comment]
I noticed I had a .curlrc file with "-w \n" in it. After removing the update started working again
