### ISSUE TITLE
Install Ruby 2.1.5 error :  Error running '__rvm_make -j2'

### ISSUE THREAD

**Issue by pentestgou1** [rvm/rvm#4019]
-  rvm get master (did not help)
## Description

Can't get ruby 2.1.5 with RVM on Kali 2017.1 (Clean & updated image)

## Steps to reproduce

**1. root@kali:~# getent group rvm
rvm: x: 1000:root**
**2. root@kali:# source /etc/profile.d/rvm.sh
3. Restart**
**4. root@kali:~# rvm install 2.1.5**
ruby-2.1.5 - #removing src/ruby-2.1.5..
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/Kali_Linux_Rolling/x86_64/ruby-2.1.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system.
Installing required packages: libreadline6-dev..
Requirements installation successful.
Installing Ruby from source to: /usr/local/rvm/scripts/rubies/ruby-2.1.5, this may take a while depending on your cpu(s)...
ruby-2.1.5 - #downloading ruby-2.1.5, this may take a while depending on your connection...
ruby-2.1.5 - #extracting ruby-2.1.5 to /usr/local/rvm/scripts/src/ruby-2.1.5....
ruby-2.1.5 - #applying patch /usr/local/rvm/scripts/patches/ruby/2.1.5/openssl3.patch.
ruby-2.1.5 - #configuring.....................................................
ruby-2.1.5 - #post-configuration..
ruby-2.1.5 - #compiling..............................................................................-
**Error running '__rvm_make -j2',**
showing last 15 lines of /usr/local/rvm/scripts/log/1494420232_ruby-2.1.5/make.log
 ^
Makefile:280: recipe for target 'ossl_pkey_rsa.o' failed
make[2]: *** [ossl_pkey_rsa.o] Error 1
make[2]: Leaving directory '/usr/local/rvm/scripts/src/ruby-2.1.5/ext/openssl'
exts.mk:192: recipe for target 'ext/openssl/all' failed
make[1]: *** [ext/openssl/all] Error 2
make[1]: *** Waiting for unfinished jobs....
compiling callback-8.c
installing default callback libraries
linking shared-object dl/callback.so
make[2]: Leaving directory '/usr/local/rvm/scripts/src/ruby-2.1.5/ext/dl/callback'
make[1]: Leaving directory '/usr/local/rvm/scripts/src/ruby-2.1.5'
uncommon.mk:180: recipe for target 'build-ext' failed
make: *** [build-ext] Error 2
++ return 2
**There has been an error while running make. Halting the installation.**

## Expected behavior

having a ruby 2.1.5 operational afther using : 
1. rvm install 2.1.5
2. rvm use 2.1.5
3. apt-get install libsqlite3-dev libxslt-dev libxml2-dev zlib1g-dev gcc

## Actual behavior
Error during install of ruby 2.1.5. 

## Environment info

rvm info

system:

  system:
    uname:        "Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.18-1kali1 (2017-04-04) x86_64 GNU/Linux"
    name:         "Debian"
    version:      "Kali_Linux_Rolling"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.11(1)-release (x86_64-pc-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.3.1 (x86_64-debian-linux-gnu)"
    remote_path:  "debian/Kali_Linux_Rolling/x86_64"

  rvm:
    version:      "rvm 1.29.1 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "11 minutes 9 seconds ago"
    path:         "/usr/local/rvm/scripts"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/scripts/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by pkuczynski** [comment]
This is most likely connected with #3958. Could you please try:

```
rvm get branch /bugfix/3958-kali
rvm install 2.1.5
```

**Comment by pkuczynski** [comment]
Closing due lack of feedback. Most likely fixed in #3958
