### ISSUE TITLE
Your Ruby version is 2.0.0, but your Gemfile specified 2.1.2

### ISSUE THREAD

**Issue by JohnMerlino2** [rvm/rvm#4024]
I initially asked the question here:

http://stackoverflow.com/questions/43402916/your-ruby-version-is-2-0-0-but-your-gemfile-specified-2-1-2

But none of the provided solutions worked for me.

I do not even have ruby  2.0.0 installed on my system, yet I get the following error:

$ bundle exec passenger-status
Your Ruby version is 2.0.0, but your Gemfile specified 2.1.2

I updated bundler, and when I run rvm-prompt, I get this:

$ rvm-prompt
ruby-2.1.2@core

Why is this error misleading me? The error is wrong and it is not helping me resolve the issue.

**Comment by pkuczynski** [comment]
Can you check and post back:

```
which ruby
ruby --version
rvm info
```

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Comment by AgentAntelope** [comment]
I'm also seeing this issue.
$ which ruby
/Users/fellsunderland/.rvm/rubies/ruby-2.2.3/bin/ruby
$  ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin16]
$  rvm info

ruby-2.2.3:

  system:
    uname:        "Darwin Fells-Work-Machine.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/usr/local/bin/bash => GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote path:  "osx/10.12/x86_64"

  rvm:
    version:      "rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "1 month 26 days 17 hours 45 minutes 34 seconds ago"
    path:         "/Users/fellsunderland/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.2.3p173"
    date:         "2015-08-18"
    platform:     "x86_64-darwin16"
    patchlevel:   "2015-08-18 revision 51636"
    full_version: "ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin16]"

  homes:
    gem:          "/Users/fellsunderland/.rvm/gems/ruby-2.2.3"
    ruby:         "/Users/fellsunderland/.rvm/rubies/ruby-2.2.3"

  binaries:
    ruby:         "/Users/fellsunderland/.rvm/rubies/ruby-2.2.3/bin/ruby"
    irb:          "/Users/fellsunderland/.rvm/rubies/ruby-2.2.3/bin/irb"
    gem:          "/Users/fellsunderland/.rvm/rubies/ruby-2.2.3/bin/gem"
    rake:         "/Users/fellsunderland/.rvm/gems/ruby-2.2.3/bin/rake"

  environment:
    PATH:         "/Users/fellsunderland/.rvm/gems/ruby-2.2.3/bin:/Users/fellsunderland/.rvm/gems/ruby-2.2.3@global/bin:/Users/fellsunderland/.rvm/rubies/ruby-2.2.3/bin:/Users/fellsunderland/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/npm/bin:/Users/fellsunderland/code/gopath/bin:/Users/fellsunderland/code/Pokemon-Terminal:/usr/local/bin/cerebro/bin"
    GEM_HOME:     "/Users/fellsunderland/.rvm/gems/ruby-2.2.3"
    GEM_PATH:     "/Users/fellsunderland/.rvm/gems/ruby-2.2.3:/Users/fellsunderland/.rvm/gems/ruby-2.2.3@global"
    MY_RUBY_HOME: "/Users/fellsunderland/.rvm/rubies/ruby-2.2.3"
    IRBRC:        "/Users/fellsunderland/.rvm/rubies/ruby-2.2.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

$  bundle exec rails server
Your Ruby version is 2.0.0, but your Gemfile specified 2.2.3

**Comment by mpapis** [comment]
show us:
which bundle
head -n 1 (which bundle)

**Comment by AgentAntelope** [comment]
After some investigation it turns out this is definitely not an rvm issue; I had a global rails bin that caused this confusion. 👍
