### ISSUE TITLE
Simplify and cleanup of `rvm help` output

### ISSUE THREAD

**Issue by afischer** [rvm/rvm#4029]
## Description

Currently, running `rvm` or `rvm help` will [`cat` the readme with some additional information](https://github.com/rvm/rvm/blob/767fa24888fcf65e01b49c9a1e0fd811e48752c2/scripts/help#L58-L67). This can be overwhelming, as the readme contains information not pertinent to rvm usage (including image tags or badges, etc.) and is formatted as a markdown document. Different column sizes make text wrapping odd in smaller terminals, and the large amount of information printed often requires scrolling.

## Steps to reproduce

 1. Open a shell with `rvm` installed.
 2. Run `rvm`
 3. The usage documentation will be printed.

## Expected behavior

Running `rvm` should simply list the usage for the command. The output should ideally be limited to 80 columns wide (or, to be fancy, using something like `tput cols`. 

Running `git` provides a good example of what (I believe)  should emulate.

## Actual behavior

* [command](https://gist.githubusercontent.com/afischer/cc6ae68309b27e04db0f27004908a0d4/raw/3d0d1225336c127382ba6d65658cdf4567cdecc8/gistfile1.txt)
* [possible example output](https://gist.githubusercontent.com/afischer/f20cf71ab8212e61acceb26a5b9c0943/raw/8c8c9f7429fee6287102a566e31f224df7d62df7/gistfile1.txt)

## Environment info

```
ruby-2.4.1:

  system:
    uname:        "Darwin Frankenstein.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote_path:  "osx/10.12/x86_64"

  rvm:
    version:      "rvm 1.29.1 (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "24 minutes 33 seconds ago"
    path:         "/Users/afischer/.rvm"
    autolibs:     "[enable] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.1p111"
    date:         "2017-03-22"
    platform:     "x86_64-darwin16"
    patchlevel:   "2017-03-22 revision 58053"
    full_version: "ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]"

  homes:
    gem:          "/Users/afischer/.rvm/gems/ruby-2.4.1"
    ruby:         "/Users/afischer/.rvm/rubies/ruby-2.4.1"

  binaries:
    ruby:         "/Users/afischer/.rvm/rubies/ruby-2.4.1/bin/ruby"
    irb:          "/Users/afischer/.rvm/rubies/ruby-2.4.1/bin/irb"
    gem:          "/Users/afischer/.rvm/rubies/ruby-2.4.1/bin/gem"
    rake:         "/Users/afischer/.rvm/rubies/ruby-2.4.1/bin/rake"

  environment:
    PATH:         "/Users/afischer/.rvm/gems/ruby-2.4.1/bin:/Users/afischer/.rvm/gems/ruby-2.4.1@global/bin:/Users/afischer/.rvm/rubies/ruby-2.4.1/bin:/Users/afischer/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    GEM_HOME:     "/Users/afischer/.rvm/gems/ruby-2.4.1"
    GEM_PATH:     "/Users/afischer/.rvm/gems/ruby-2.4.1:/Users/afischer/.rvm/gems/ruby-2.4.1@global"
    MY_RUBY_HOME: "/Users/afischer/.rvm/rubies/ruby-2.4.1"
    IRBRC:        "/Users/afischer/.rvm/rubies/ruby-2.4.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by pkuczynski** [comment]
Fair point. Prepared a fix based on your input (with some minor modifications)
