### ISSUE TITLE
Permission denied error on any RVM installs

### ISSUE THREAD

**Issue by Syntaf** [rvm/rvm#4035]
## Description

I am attempting to install Ruby on Rails using [this](http://railsapps.github.io/installrubyonrails-ubuntu.html) guide, however RVM is quite confusing. After downloading RVM, I tried doing the following:

`rvm install ruby`

which gave me the error you see in 'actual behavior'

## Steps to reproduce

I simply followed the guide

## Expected behavior

I literally just want to use RoR

## Actual behavior

> gdev@gdev-old:~$ rvm install ruby
> Searching for binary rubies, this might take some time.
> No binary rubies available for: ubuntu/16.10/x86_64/ruby-2.4.0.
> Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
> Checking requirements for ubuntu.
> Installing requirements for ubuntu.
> Updating systemgdev password required for 'apt-get --quiet --yes update': ..-
> ..
> Installing required packages: libreadline6-dev....
> Requirements installation successful.
> Installing Ruby from source to: /usr/share/rvm/rubies/ruby-2.4.0, this may take a while depending on your cpu(s)...
> ruby-2.4.0 - #downloading ruby-2.4.0, this may take a while depending on your connection...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file ruby-2.4.0.tar.bz2.part: Permission denied
>   0 11.9M    0  2759    0     0   4695      0  0:44:37 --:--:--  0:44:37  4700
> curl: (23) Failed writing body (0 != 2759)
> There was an error(23).
> Checking fallback: https://ftp.ruby-lang.org/pub/ruby/2.4/ruby-2.4.0.tar.bz2
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0Warning: Failed to create the file ruby-2.4.0.tar.bz2.part: Permission denied
>   0 11.9M    0 16149    0     0  13362      0  0:15:40  0:00:01  0:15:39 13357
> curl: (23) Failed writing body (0 != 16149)
> There was an error(23).

**Comment by Syntaf** [comment]
The issue was caused by not logging out and in

**Comment by platinumzeke** [comment]
Would you mind elaborating on this? What did you not log out of and log back into? I'm having the same issue with cloud 9 and I can't get past this.

**Comment by kelvinjhwong** [comment]
I just spent hours struggling with this, and finally found a solution here: https://stackoverflow.com/questions/26242712/installing-rvm-getting-error-there-was-an-error23

Hopefully this helps, if anybody else is still struggling with the issue!

**Comment by rachitydv** [comment]
@kelvinjhwong the link worked for me :)

**Comment by michaelschufi** [comment]
If you are on WSL 2 and you have this issue. (Applying the commands in this [Stackoverflow answer](https://stackoverflow.com/a/26370637), not sure if needed) and restarting the WSL 2 with the windows shell command
```powershell
wsl --shutdown  Ubuntu-20.04 ; wsl -d Ubuntu-20.04
```
fixed the problem for me.
Also, don't forget to start a shell with `bash --login`.

**Comment by ycwei5** [comment]
I resloved it by    rvm install ruby-3.0.3 --with-openssl-dir=`brew --prefix openssl
