### ISSUE TITLE
PATH not found - What does this mean and what do I need to do?

### ISSUE THREAD

**Issue by gitchegumee1** [rvm/rvm#4041]
Anytime I try to issue a basic rvm command I get the prompt below. It happens anytime that I write rvm get stable, rvm list rubies, etc. Please help! I tried to reinstall rvm, delete rubies and reinstall them but nothing is working. Appreciate your help. 

Warning! PATH is not properly set up, '/Users/sharp.christensen/.rvm/gems/ruby-2.3.0/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.3.0'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.

**Comment by raelgc** [comment]
@gitchegumee1, in order we can help you, please, can you fill all the requested info while opening a rvm bug?

**Comment by pkuczynski** [comment]
Can you post `echo $PATH`?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
