### ISSUE TITLE
Issue while installing RVM

### ISSUE THREAD

**Issue by pdixit123** [rvm/rvm#4046]
Issue while installing RVM

    rvm get master

@mpapis :- I tried to enter all possible commands mentioned on your previous post, however not all of them worked. Here's the extract.

[root@pa-rhel7-test ~]# yum install createrepo
Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-manager
There was an error communicating with RHN.
Red Hat Satellite or RHN Classic support will be disabled.
Error communicating with server. The message was:
Unable to connect to the host and port specified
No package createrepo available.
Error: Nothing to do
[root@pa-rhel7-test ~]# cd /etc/re
redhat-release  resolv.conf
[root@pa-rhel7-test ~]# gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
[root@pa-rhel7-test ~]# \curl -sSL https://get.rvm.io | bash
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

# pmpuser,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

[root@pa-rhel7-test ~]# \curl -sSL https://get.rvm.io | bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.29.1.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc
gpg: Signature made Sun 19 Feb 2017 12:02:47 PM PST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg:                 aka "Michal Papis <michal.papis@toptal.com>"
gpg:                 aka "[jpeg image of size 5015]"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-1.29.1.tgz'

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

# pmpuser,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
Searching for binary rubies, this might take some time.
No binary rubies available for: centos/7/x86_64/ruby-2.4.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for centos.
Installing requirements for centos.
Installing required packages: libyaml-devel..
Error running 'requirements_centos_libs_install libyaml-devel',
showing last 15 lines of /usr/local/rvm/log/1495429972_ruby-2.4.0/package_install_libyaml-devel.log
++ /scripts/functions/utility : __rvm_try_sudo()  353 > typeset -a command_to_run
++ /scripts/functions/utility : __rvm_try_sudo()  354 > typeset sudo_path sbin_path missing_paths
++ /scripts/functions/utility : __rvm_try_sudo()  355 > command_to_run=("$@")
++ /scripts/functions/utility : __rvm_try_sudo()  356 > ((  UID == 0  ))
++ /scripts/functions/utility : __rvm_try_sudo()  391 > yum install -y libyaml-devel
Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-
              : manager
There was an error communicating with RHN.
Red Hat Satellite or RHN Classic support will be disabled.
Error communicating with server. The message was:
Unable to connect to the host and port specified
No package libyaml-devel available.
Error: Nothing to do
++ /scripts/functions/utility : __rvm_try_sudo()  391 > return 1
++ /scripts/functions/requirements/centos : requirements_centos_libs_install()  31 > return 1
Requirements installation failed with status: 1.
[root@pa-rhel7-test ~]# ^C
[root@pa-rhel7-test ~]# rvm install 1.9.3
Searching for binary rubies, this might take some time.
No binary rubies available for: centos/7/x86_64/ruby-1.9.3-p551.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for centos.
Installing requirements for centos.
Installing required packages: libyaml-devel..
Error running 'requirements_centos_libs_install libyaml-devel',
showing last 15 lines of /usr/local/rvm/log/1495430057_ruby-1.9.3-p551/package_install_libyaml-devel.log
++ typeset -a command_to_run
++ typeset sudo_path sbin_path missing_paths
++ command_to_run=("$@")
++ ((  UID == 0  ))
++ yum install -y libyaml-devel
Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-
              : manager
There was an error communicating with RHN.
Red Hat Satellite or RHN Classic support will be disabled.
Error communicating with server. The message was:
Unable to connect to the host and port specified
No package libyaml-devel available.
Error: Nothing to do
++ return 1
++ return 1
Requirements installation failed with status: 1.
[root@pa-rhel7-test ~]# rvm get head
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Mon 20 Feb 2017 06:05:42 AM PST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg:                 aka "Michal Papis <michal.papis@toptal.com>"
gpg:                 aka "[jpeg image of size 5015]"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

# pmpuser,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

RVM reloaded!
[root@pa-rhel7-test ~]# rvm reload
RVM reloaded!
[root@pa-rhel7-test ~]# rvm install 1.9.3
Searching for binary rubies, this might take some time.
No binary rubies available for: centos/7/x86_64/ruby-1.9.3-p551.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for centos.
Installing requirements for centos.
Installing required packages: libyaml-devel..
Error running 'requirements_centos_libs_install libyaml-devel',
please read /usr/local/rvm/log/1495430101_ruby-1.9.3-p551/package_install_libyaml-devel.log
Requirements installation failed with status: 1.
[root@pa-rhel7-test ~]# rvm get head
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Mon 20 Feb 2017 06:05:42 AM PST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg:                 aka "Michal Papis <michal.papis@toptal.com>"
gpg:                 aka "[jpeg image of size 5015]"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

# pmpuser,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

RVM reloaded!
[root@pa-rhel7-test ~]# rvm reload
RVM reloaded!
[root@pa-rhel7-test ~]# rvm --debug requirements ruby-1.9.3
rvm_autolibs_flag=4
Checking requirements for centos.
requirements code for centos loaded
Found required packages: bash, curl, patch, glibc-headers, autoconf, gcc-c++, glibc-devel, patch, readline, readline-devel, zlib, zlib-devel, libffi-devel, openssl-devel, make, bzip2, automake, libtool, bison, sqlite-devel.
Installing requirements for centos.
Log prefix: /usr/local/rvm/log/1495430153/
Log filesystem: ext4
Log max name length: 250
Log file: /usr/local/rvm/log/1495430153/package_install_libyaml-devel.log
[2017-05-21 22:15:53] requirements_centos_libs_install
requirements_centos_libs_install ()
{
    __rvm_try_sudo yum install -y "$@" || return $?
}
current path: /root
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/rvm/bin:/home/pmpuser/.local/bin:/home/pmpuser/bin
command(2): requirements_centos_libs_install libyaml-devel
Installing required packages: libyaml-devel..
Error running 'requirements_centos_libs_install libyaml-devel',
please read /usr/local/rvm/log/1495430153/package_install_libyaml-devel.log
Requirements installation failed with status: 1.
__rvm_rm_rf already gone: /usr/local/rvm/tmp/11757*
[root@pa-rhel7-test ~]# rvm --debug requirements ruby-1.9.3 2>&1 | tee.big.log
bash: tee.big.log: command not found
[root@pa-rhel7-test ~]# rvm --trace requirements ruby-1.9.3 2>&1 | tee.big.log
bash: tee.big.log: command not found
[root@pa-rhel7-test ~]# rvm --trace requirements ruby-1.9.3 2>&1 | tee.big.log
bash: tee.big.log: command not found
[root@pa-rhel7-test ~]#
[root@pa-rhel7-test ~]#
[root@pa-rhel7-test ~]# rvm --trace requirements ruby-1.9.3 2>&1 | tee.big.log
bash: tee.big.log: command not found
[root@pa-rhel7-test ~]# rem get head
bash: rem: command not found
[root@pa-rhel7-test ~]# rvm get ehad
Ruby enVironment Manager 1.29.1 (master) (c) 2009-2017 Michal Papis, Piotr Kuczynski, Wayne E. Seguin

# rvm get

Update RVM

## Usage

  rvm get {stable|latest|latest-x.y|x.y.z|head|master|branch|help} [--auto-dotfiles] [--autolibs=X]

## Options

  stable     - install the latest RVM stable release

  latest     - install the latest RVM release

  latest-minor
             - install the latest minor RVM release for currently installed version

  latest-x.y - install the latest RVM release matching the x.y* pattern

  x.y.z      - install a specific RVM release

  head
  master     - install the latest RVM development version

  --auto-dotfiles
             - automatically update shell profile files.

  --autolibs=X
             - update autolibs mode to `X`, read more: `rvm autolibs`

  help       - Output this message.

## Branches

    branch <branch>
    branch /<branch>
    branch <repo>/
    branch <repo>/<branch>

## Defaults

    branch: master
    repo:   rvm

## Examples

    rvm get branch shoes   # will fetch branch shoes from rvm/rvm repo
    rvm get branch mpapis/ # will fetch branch master from mpapis/rvm repo

For additional documentation please visit https://rvm.io

[root@pa-rhel7-test ~]# rvm get head
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/wayneeseguin/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made Mon 20 Feb 2017 06:05:42 AM PST using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg:                 aka "Michal Papis <michal.papis@toptal.com>"
gpg:                 aka "[jpeg image of size 5015]"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

# pmpuser,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

RVM reloaded!
[root@pa-rhel7-test ~]# rem reload
bash: rem: command not found
[root@pa-rhel7-test ~]# rvm reload
RVM reloaded!
[root@pa-rhel7-test ~]# rvm install
Can not use or install 'all' rubies.
[root@pa-rhel7-test ~]# rvm install 1.9.3
Searching for binary rubies, this might take some time.
No binary rubies available for: centos/7/x86_64/ruby-1.9.3-p551.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for centos.
Installing requirements for centos.
Installing required packages: libyaml-devel..
Error running 'requirements_centos_libs_install libyaml-devel',
please read /usr/local/rvm/log/1495430399_ruby-1.9.3-p551/package_install_libyaml-devel.log
Requirements installation failed with status: 1.
[root@pa-rhel7-test ~]# rvm --force install 1.9.2
Searching for binary rubies, this might take some time.
No binary rubies available for: centos/7/x86_64/ruby-1.9.2-p330.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for centos.
Installing requirements for centos.
Installing required packages: libyaml-devel..
Error running 'requirements_centos_libs_install libyaml-devel',
please read /usr/local/rvm/log/1495430460_ruby-1.9.2-p330/package_install_libyaml-devel.log
Requirements installation failed with status: 1.
[root@pa-rhel7-test ~]# 2sudo yum install -y libyaml-devel
bash: 2sudo: command not found
[root@pa-rhel7-test ~]# sudo yum install -y libyaml-devel
Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-manager
There was an error communicating with RHN.
Red Hat Satellite or RHN Classic support will be disabled.
Error communicating with server. The message was:
Unable to connect to the host and port specified
No package libyaml-devel available.
Error: Nothing to do
[root@pa-rhel7-test ~]# head -n 100 /etc/yum.repos.d/{epel.repo,epel-testing.repo}
==> /etc/yum.repos.d/epel.repo <==
[epel]
name=Extra Packages for Enterprise Linux 6 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-6&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

[epel-debuginfo]
name=Extra Packages for Enterprise Linux 6 - $basearch - Debug
#baseurl=http://download.fedoraproject.org/pub/epel/6/$basearch/debug
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-debug-6&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
gpgcheck=1

[epel-source]
name=Extra Packages for Enterprise Linux 6 - $basearch - Source
#baseurl=http://download.fedoraproject.org/pub/epel/6/SRPMS
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=epel-source-6&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
gpgcheck=1

==> /etc/yum.repos.d/epel-testing.repo <==
[epel-testing]
name=Extra Packages for Enterprise Linux 6 - Testing - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/testing/6/$basearch
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=testing-epel6&arch=$basearch
failovermethod=priority
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

[epel-testing-debuginfo]
name=Extra Packages for Enterprise Linux 6 - Testing - $basearch - Debug
#baseurl=http://download.fedoraproject.org/pub/epel/testing/6/$basearch/debug
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=testing-debug-epel6&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
gpgcheck=1

[epel-testing-source]
name=Extra Packages for Enterprise Linux 6 - Testing - $basearch - Source
#baseurl=http://download.fedoraproject.org/pub/epel/testing/6/SRPMS
mirrorlist=https://mirrors.fedoraproject.org/metalink?repo=testing-source-epel6&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
gpgcheck=1
[root@pa-rhel7-test ~]# yum repolist all
Loaded plugins: product-id, rhnplugin, search-disabled-repos, subscription-manager
There was an error communicating with RHN.
Red Hat Satellite or RHN Classic support will be disabled.
Error communicating with server. The message was:
Unable to connect to the host and port specified
repo id                                                                                      repo name                                                                                                                        status
*epel/x86_64                                                                                 Extra Packages for Enterprise Linux 6 - x86_64                                                                                   enabled: 11,662
epel-debuginfo/x86_64                                                                        Extra Packages for Enterprise Linux 6 - x86_64 - Debug                                                                           disabled
epel-source/x86_64                                                                           Extra Packages for Enterprise Linux 6 - x86_64 - Source                                                                          disabled
epel-testing/x86_64                                                                          Extra Packages for Enterprise Linux 6 - Testing - x86_64                                                                         disabled
epel-testing-debuginfo/x86_64                                                                Extra Packages for Enterprise Linux 6 - Testing - x86_64 - Debug                                                                 disabled
epel-testing-source/x86_64                                                                   Extra Packages for Enterprise Linux 6 - Testing - x86_64 - Source                                                                disabled
repolist: 11,662
[root@pa-rhel7-test ~]# sudo yum-config-manager --enable epel
sudo: yum-config-manager: command not found
[root@pa-rhel7-test ~]# yum-config-manager --enable epel
bash: yum-config-manager: command not found
[root@pa-rhel7-test ~]# sudo yum-config-manager --enable epel
sudo: yum-config-manager: command not found
[root@pa-rhel7-test ~]# rvm requirements
Checking requirements for centos.
Installing requirements for centos.
Installing required packages: libyaml-devel..
Error running 'requirements_centos_libs_install libyaml-devel',
please read /usr/local/rvm/log/1495430606/package_install_libyaml-devel.log
Requirements installation failed with status: 1.

**Comment by pkuczynski** [comment]
This issue is not following our requested format. It is very hard to read and help you. Please create a new issue in a format we require. Run only following commands:

```
rvm get master
rvm install 1.9.2
```
