### ISSUE TITLE
rvm install 2.3.3

### ISSUE THREAD

**Issue by RMCollins175** [rvm/rvm#4052]
hi guys, sorry, i'm a complete beginner to this stuff. I'm following a beginner course on udemy on Ruby. its asked me to download rvm and then install 2.3.3. so this is what i type into the terminal and receive:

rvm install 2.3.3
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
About to install Homebrew, press `Enter` for default installation in `/usr/local`,
type new path if you wish custom Homebrew installation (the path needs to be writable for user)

then when i enter, it installs homebrew and ask me for a password which i do not know....

**Comment by pkuczynski** [comment]
This is the password required for sudo. Did you try your own password? You might also want to install homebrew based on instructions on their side and only afterward continue with RVM install.

**Comment by RMCollins175** [comment]
what is the password? ok ill try installing home-brew. what is home-brew by the way?

**Comment by RMCollins175** [comment]
its just not letting me input any keys

**Comment by pkuczynski** [comment]
Homebrew is a package manager. Install it from here: https://brew.sh

**Comment by RMCollins175** [comment]
same problem. asking me for a password, where i cannot type anything...? weird.

**Comment by pkuczynski** [comment]
type the password and hit enter. the fact that it does not show anything on the screen is ok

**Comment by RMCollins175** [comment]
thanks a lot . all sorted. mindscrambled though!
