### ISSUE TITLE
JRuby-9 fresh install fails gem executable-hooks "make not found"

### ISSUE THREAD

**Issue by pjfitzgibbons** [rvm/rvm#4058]
## Description
Error logged on jruby install:
```
jruby-9.1.10.0 - #importing gemset /usr/local/rvm/gemsets/jruby/global.gems....................
Error running 'gemset_import_list jruby-openssl jruby-launcher gem-wrappers rubygems-bundler rake rvm',
showing last 15 lines of /usr/local/rvm/log/1496934910_jruby-9.1.10.0/gemsets.import.global.log
current directory: /usr/local/rvm/rubies/jruby-9.1.10.0/lib/ruby/gems/shared/gems/executable-hooks-1.3.2/ext/wrapper_installer
make "DESTDIR=" clean
sh: 1: make: not found
```

## Steps to reproduce
Install RVM on fresh Docker image `openjdk:latest (8u131-jdk)`
$ `rvm install jruby-9.1.10.0`

## Expected behavior
Successful install of ruby gem "executable-hooks"

## Actual behavior
Above

## Environment info
https://gist.github.com/pjfitzgibbons/6c86b8221ee7782363418c9f016781e4

**Comment by pkuczynski** [comment]
Could you please also gist `/usr/local/rvm/log/1496934910_jruby-9.1.10.0/gemsets.import.global.log` and show me what `make --version` shows?

Am I correct that you are using Alpine Linux v3.5? We did not have the support for it yet, so I would have to add it...

Note to myself:
* https://wiki.alpinelinux.org/wiki/Alpine_Linux_package_management
* https://pkgs.alpinelinux.org/packages

**Comment by pjfitzgibbons** [comment]
HI @pkuczynski 
Here is another gist, this time on the current ubuntu docker image (16.04 I believe).
The gemsets.import.global.log and the bash session are included in the gist.

https://gist.github.com/pjfitzgibbons/79c64b099407db41500a82cd2de8d47a

**Comment by mpapis** [comment]
Looks like `make` is required for `jruby` installation, I think we will need to update the requirements for all systems to include `make`.

**Comment by pkuczynski** [comment]
Indeed it seems that on those docker images you are missing `make`! I will create a PR which list make as the requirement for all OS, as it's not only related to `jruby`

**Comment by pkuczynski** [comment]
@pjfitzgibbons could you try again after `rvm get branch /bugfix/jruby-require-make`?

**Comment by pkuczynski** [comment]
@pjfitzgibbons we merged the changes. You can now try after `rvm get master`
