### ISSUE TITLE
get.rvm.io install script doesn't detect gnupg

### ISSUE THREAD

**Issue by lindenstaub** [rvm/rvm#4059]
Hello! Just installed RVM on a freshly installed and updated Debian 8 Jessie machine. 

RVM will successfully install, but the following message about no GPG software comes up. This is after succesfully running `gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`, so there is a gpg command available on the computer.

```
$ \curl -sSL https://get.rvm.io | bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.29.1.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.1/1.29.1.tar.gz.asc',
but no GPG software exists to validate it, skipping.
```

I had gnupg installed, but not gnupg2. After `apt-get install gnupg2` I am able to install RVM with signature verification.

I would expect a script to either break or ask for user confirmation before continuing if it is not able to verify a signature. Is there a reason it's not falling back to `gpg` if `gpg2` isn't available?

**Comment by pkuczynski** [comment]
We indeed removed gpg support in d44f6867ed0a681c05f012261e8fdd142cac5e6c as we run into some issues with old gpg. I suggest we update the message from

`but no GPG software exists to validate it, skipping.`

to

`but no GPGv2 software exists to validate it. We will continue with the installation, but we suggest you install it in the future, as that provides more security.`

The other option would be to ask the user if he want's to continue or stop the installation asking him to install GPGv2 before he tries again. @mpapis what you think?

**Comment by mpapis** [comment]
just a warning, security is very important and we should point it out, but installing our software is even more important - unattended installation would not work if we break the process.

**Comment by pkuczynski** [comment]
@lindenstaub do you think updating the message would be good enough? Or we should bring back gpg support?

**Comment by lindenstaub** [comment]
I think gpg2 is becoming the default soon (at least in Debian 9, coming out pretty soon), so if you do bring support for gpg back it would probably only have to be temporary. I don't know how other distros are dealing with gpg/gpg2. If that's too much trouble, a prominent message at the end of the install process (so it doesn't get buried by all the other messages, or ruby compiling, etc) could be a good compromise.

**Comment by markeissler** [comment]
On Ubuntu 16.04 it appears there are both `gpgv2` and `gnupg2` packages available just to make things more confusing I guess:

```sh
mark@DESKTOP-JTBHTC4:~$ sudo apt-cache search gnupg2
devscripts - scripts to make the life of a Debian Package maintainer easier
gnupg - GNU privacy guard - a free PGP replacement
gnupg2 - GNU privacy guard - a free PGP replacement (new v2.x)
mark@DESKTOP-JTBHTC4:~$ sudo apt-cache search gpgv2
devscripts - scripts to make the life of a Debian Package maintainer easier
gpgv2 - GNU privacy guard - signature verification tool (new v2.x)
```
Installing `gpgv2` doesn't help. But installing `gnupg2` does fix this as @lindenstaub mentioned.

**Comment by ChallahuAkbar** [comment]
Just to add to this: in Ubuntu 17.04, the default `gnupg` package has been updated to GnuPG v2.1, so the `gpg` command is now GnuPGv2. The `gnupg2` program still exists, but only as a dummy transitional symlink to the regular `gpg` command. Perhaps it would be better to test the version number rather than simply ignore it if `gpg2` isn't available (if `gpg2` isn't found then parse the output of `gpg --version`). Hope this helps.

**Comment by tomPorter** [comment]
On OSX El Cap, using brew where I have gpg2 installed, I still get this message.  ls -la /usr/local/bin/gpg  -> ../Cellar/gnupg/2.1.23/bin/gpg

Note that gpg2 does not exist.

**Comment by ToRumford** [comment]
Try curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
