### ISSUE TITLE
Fail to install ruby 2.3.3 on Windows 7x64 with Cygwin

### ISSUE THREAD

**Issue by bendulum** [rvm/rvm#4070]
Windows is running inside a VirtualBox. I tried several times and also re-installing Cygwin.
Cygwin and Cygwin\bin directories as well as Cygwin's `setup-x86_64.exe` are all in the PATH.

I installed RVM, as described [here](https://vaporsoft.net/setting-up-rvm-with-cygwin/) like so:
`gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`
`\curl -sSL https://get.rvm.io | bash -s stable`
`source /home/Bendulum/.rvm/scripts/rvm`
`rvm install ruby`

I tried all of the steps below, then again, after running `rvm get master`.

`rvm requirements` returns "Requirements installation successful."
`rvm list` shows `ruby-2.4.0 [ x86_64 ]` being installed
Now running `rvm install 2.3.3` yields:
```
$ rvm install 2.3.3
-bash: __rvm_remote_version: command not found
ruby-2.3.3 - #removing src/ruby-2.3.3..
Searching for binary rubies, this might take some time.
No binary rubies available for: cygwin/unknown/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for cygwin.
Requirements installation successful.
Installing Ruby from source to: /home/Bendulum/.rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
ruby-2.3.3 - #extracting ruby-2.3.3 to /home/Bendulum/.rvm/src/ruby-2.3.3....
ruby-2.3.3 - #applying patch /home/Bendulum/.rvm/patches/ruby/2.3.3/random_c_using_NR_prefix.patch.
ruby-2.3.3 - #configuring..........................................................
ruby-2.3.3 - #post-configuration..
ruby-2.3.3 - #compiling............
Error running '__rvm_make -j1',
please read /home/Bendulum/.rvm/log/1497887241_ruby-2.3.3/make.log
There has been an error while running make. Halting the installation.
```

Always getting the `__rvm_make -j1` error. For both Ruby 2.3.3 and 2.3.1.
I tried various "fixes" that I found on the internet:

`rvm autolibs disable`
`rvm cleanup all`

As well as this patch from [here](https://stackoverflow.com/a/33702346/3248285) and even [this one](https://github.com/rvm/rvm/issues/3748#issuecomment-251306656).

I put the contents of `make.log` into a [Pastebin](https://pastebin.com/AaEQdfMj). I'm not good at interpreting it...

Any ideas what I'm doing wrong and what else I can try to get it running? Thanks.

**Comment by kunzig940** [comment]
Same here for Ruby 2.3.4 as well.

**Comment by nasrob** [comment]
I have the same issue with ruby 2.3.1 on windows 8.

**Comment by pkuczynski** [comment]
This has been already fixed. Please run `rvm get master`

**Comment by mgrigajtis** [comment]
This isn't fixed.  Still happens in Cygwin.
