### ISSUE TITLE
rvm-installer installs neither ruby nor homebrew

### ISSUE THREAD

**Issue by toh-ableton** [rvm/rvm#4073]
## Description

The [installation instructions](https://rvm.io/rvm/install) claim that `--ruby` [installs a ruby](https://rvm.io/rvm/install#any-other-system) and `--autolibs=homebrew` [installs homebrew if necessary](https://rvm.io/rvm/autolibs#letting-rvm-take-care-of-it-all-4). 

This is not the case, nothing except rvm is installed.

## Steps to reproduce

Install rvm:
 1. Create a new user account
 2. Run ` \curl -sSL https://get.rvm.io | bash -s -- stable --ruby --autolibs=homebrew`
 3. `source ~/.rvm/scripts/rvm`

Then test the installation:
 1. Run `brew`
 2. Run `rvm list`

## Expected behavior

`brew` and a `ruby` are installed:
```bash
$ brew
Example usage:
<...>

$ rvm list

rvm rubies

=* ruby-2.4.0 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

## Actual behavior

* [`\curl -sSL https://get.rvm.io | bash -s -- stable --ruby --autolibs=homebrew`](https://gist.github.com/toh-ableton/03f1ac5ec5849ca1ab30a25bd1cea963)

There is no `config.log` or `make.log`.

```bash
tohs-Mac:~ toh$ brew
-bash: brew: command not found
tohs-Mac:~ toh$ rvm list

rvm rubies


# No rvm rubies installed yet. Try 'rvm help install'.

```

**Debug mode**:

Debug mode seems broken, the installer script isn't even able to extract rvm from the tgz:

* [`\curl -sSL https://get.rvm.io | bash -s -- stable --ruby --autolibs=homebrew --debug`](https://gist.github.com/toh-ableton/20fd1b38d3c17551ab1138f7a153b8a3)

There is no `config.log` or `make.log` (as before).

## Environment info

```
$ rvm info

system:

  system:
    uname:        "Darwin tohs-Mac.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote path:  "osx/10.12/x86_64"

  rvm:
    version:      "rvm 1.29.1 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]"
    updated:      "3 minutes 38 seconds ago"
    path:         "/Users/toh/.rvm"
    autolibs:     "[homebrew] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/toh/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by toh-ableton** [comment]
(Note that manually installing homebrew and then ruby using `rvm install ruby` works just fine).

**Comment by mpapis** [comment]
we pushed few fixes that will influence the result, please try:
```bash
\curl -sSL https://get.rvm.io | bash -s master --ruby --autolibs=homebrew --debug
```
and gist the result

**Comment by pkuczynski** [comment]
Closing due lack of feedback. Please reopen if needed...

**Comment by wruixue** [comment]
> ### 解决方法：
> 安装[Homebrew](https://brew.sh/)然后`rvm install ruby`手动使用ruby 。

This solves the problem
