### ISSUE TITLE
Can't update RVM / get head / get stable

### ISSUE THREAD

**Issue by marseille** [rvm/rvm#4079]
Hello,

I'm trying update RVM on ubuntu 14.04

Following the instructions --- I went to the ubuntu dedicated install page, followed the instructions, installed the package. I had trouble installing a ruby for awhile, but that may have gone by installing gnupg2 (I can't be sure).

when I execute rvm get head or rvm get stable I run into errors. I do have access to installing rubies it appears, and I can use it for what I need (it appears), but the fact I can't update RVM is concerning.

Here is the output the commands I ran.

rvm get stable
https://gist.github.com/anonymous/652bfffd12715b56a64f1f06d849bf14

rvm get head
https://gist.github.com/anonymous/0c0941a5697f57a1c02257b9dc52e02c

gnupg2 + the same
https://gist.github.com/anonymous/a14f72ea390cd9eabaa7889a87d5639a

I've read a lot of github issues, and posts trying a lot of different key adding methods, but to no avail. Let me know if there is anything I can do about this, or a workaround for the moment.

**Comment by mpapis** [comment]
this looks like gibberish files were downloaded, try:
```bash
curl -sSL https://get.rvm.io | bash -s master --debug
```
It will show additional information about the problem and what is being executed

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Comment by mpapis** [comment]
my bad ;)

**Comment by pkuczynski** [comment]
Closing due lack of feedback. Please reopen if needed...
