### ISSUE TITLE
ruby 2.3.0 fails to install under fedora 26

### ISSUE THREAD

**Issue by ANeilan** [rvm/rvm#4080]
## Description

Ruby 2.3.0 fails to install under fedora 26

## Steps to reproduce

 1. rvm install ruby-2.3.0
 2. rvm installs some dependencies
 3. fails to install

## Expected behavior

ruby-2.3.0 compiles and installs

## Actual behavior

* [command](https://gist.github.com/ANeilan/ad0e63819d6f794db132541aaed1266e)
* [config.log](https://gist.github.com/ANeilan/46f4b651e172c511175a225d95ec44a8) - only for issues with `install`
* [make.log](https://gist.github.com/ANeilan/4c7815abe02b10d91c1c2213e5a4956f) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/ANeilan/abb093c9accc28fdc779a8948ae0fc95)
* [config.log](https://gist.github.com/ANeilan/11437bf93042c10e473c671e6cc9d126) - only for issues with `install`
* [make.log](https://gist.github.com/ANeilan/1c2ccd54647d777be515dd3608013b5a) - only for issues with `install`

## Environment info

system:

  system:
    uname:        "Linux fedora 4.11.6-301.fc26.x86_64 #1 SMP Tue Jun 20 16:17:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Fedora"
    version:      "26"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 4.4.12(1)-release (x86_64-redhat-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.3.1 (x86_64-redhat-linux-gnu)"
    remote_path:  "fedora/26/x86_64"

  rvm:
    version:      "1.29.2 (master)"
    updated:      "27 minutes 24 seconds ago"
    path:         "/home/aneilan/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/home/aneilan/bin:/usr/local/sbin:/usr/sbin:/home/aneilan/bin:/home/aneilan/.rvm/bin:/home/aneilan/.local/bin/:/home/aneilan/.rvm/bin:/home/aneilan/.rvm/bin:/home/aneilan/.local/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by ANeilan** [comment]
figured out from 
https://github.com/rbenv/ruby-build/issues/1092

that the build issue stems from build problems with GCC-7

downgrading to GCC-6 (from Fedora 25) allowed the build to succeed

**Comment by cben** [comment]
See also #4057, specifically https://github.com/rvm/rvm/issues/4057#issuecomment-318718121 contains recipe with GCC 7.
