### ISSUE TITLE
RVM installation issues for sierra mac OSX 10.12.5

### ISSUE THREAD

**Issue by siva-wal** [rvm/rvm#4081]
When I do install `rvm requirements` it gives error as follows

```
Installing requirements for osx.
Updating system..........
Installing required packages: apple-gcc42.......There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://github.com/Homebrew/homebrew/wiki/Installation
..
Error running 'requirements_osx_brew_libs_install apple-gcc42',
please read /Users/sevantinag/.rvm/log/1498567524/package_install_apple-gcc42.log
Requirements installation failed with status: 1.
```

When I do `brew install apple-gcc42` I am getting following error

```
apple-gcc42: This formula either does not compile or function as expected on macOS
versions newer than Mavericks due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

Could you let me know where I went wrong?

**Comment by AndresCL** [comment]
Same problem here. Did you solve it?

**Comment by sivagollapalli** [comment]
@AndresCL Sorry, I could not get that solved. So, I started using through `docker`.

**Comment by AndresCL** [comment]
I solved it. I had problems with my PATH variable related with XAMPP, it was making RVM fail.
Check this: https://stackoverflow.com/questions/21498991/head-usage-unknown-option-1-n-error-possibly-ruby-related

**Comment by mpapis** [comment]
I'm not sure how to fix it, we could provide a warning about the path, would that be enough?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Comment by harishdixit1** [comment]
I am getting the below error while running "rvm requirements"

Error running 'requirements_osx_brew_libs_install apple-gcc42',

Can someone please help?

**Comment by harishdixit1** [comment]
Did anyone get a chance to look?
