### ISSUE TITLE
undler

### ISSUE THREAD

**Issue by ericgoedtel** [rvm/rvm#4082]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by ericgoedtel** [comment]
Wow, sorry about this.

**Comment by pkuczynski** [comment]
No worries...
