### ISSUE TITLE
Automatic builds for https://rvm.io/binaries/

### ISSUE THREAD

**Issue by andvgal** [rvm/rvm#4087]
That's not just a problem report. I'd like to **help you** setup a system which would automatically ensure that latest minor ruby release binary versions are available for all supported OSes, their versions and architectures. I do not see any plan for that in scope of RVM 2.0.

Overall approach:
* There should be a single script to ensure "Expected Behavior" below
* It should contain a list of Vagrant boxes for clean builds
* The logic:
  * Boot each box one by one
  * Determine platform triplet for https://rvm.io/binaries/
  * Detect the latest minor ruby versions (X.Y.*) from RVM itself
  * For each ruby version + platform triplet missing on https://rvm.io/binaries/
    * Build ruby from source
    * Run automatic acceptance tests
      * we can start with basic smoke tests
    * Upload to https://rvm.io/binaries/
      * intermediate location for manual inspection can be used.

It's a trivial to setup infrastructure to ensure all users of officially supported by RVM platforms can use binary rubies with no need to compile anything.

We can mitigate various issues related to build dependency version incompatibilities,  ensuring proper patches or workarounds are applied.

Related: futoin/cid-tool#7

Formality below:
## Description

Automatic creation of binaries for https://rvm.io/binaries/

## Steps to reproduce

Just go to https://rvm.io/binaries/ and find missing binary builds for various platforms and/or latest minor versions of Ruby.

## Expected behavior

1. For each supported OS/platform triplet, there must be a binary build of ruby for each latest minor version (1.8.x, 1.9.x, ... 2.3.x, 2.4.x, ...)
2. Upon release of ruby patch version, it must get automatically updated for all binaries.

## Actual behavior

See Steps to reproduce

## Environment info

Any

**Comment by jrgifford** [comment]
I assume you've seen this project: https://github.com/rvm/rvm-binary

We've got the process setup, what would make it "better" would be to run it against something lighter weight than virtualbox and vagrant. I played with the idea of putting the build process in a container about 2 years ago, but that didn't work well.

Could explore containers, or look into using something like terraform with AWS to spin up the instance for just the amount of time required (a t2.medium is 5 cents an hour. 0.05 * 30 builds * 2x /month = $3.)

**Comment by andvgal** [comment]
Sorry, I did not notice that project. So, you already have the system partially done.

I am sure we can pursue a bare metal dedicated sponsorship for such mature project as RVM not to be constrained by resources.

Some hint: MacStadium . They are known to provide sponsorship for OpenSource projects and it's possible to use Mac Mini SDD to run clean Vagrant boxes one-by-one for continuous builds & tests for almost all systems including macOS itself.

Repeated bootstrap of linked VBox images in Vagrant on SSD drive takes about a minutes or so. That should be a fraction of time required for builds and tests.

**Comment by mpapis** [comment]
Hey, I was experimenting with doing OSX builds on Travis CI, but the results we unpredictable :(

I'm adding you to our slack and to GH team, let's continue discussion on slack :)

**Comment by andvgal** [comment]
Work on the document has been started: https://docs.google.com/document/d/1PzLLPmO1v1tQybVHLNDRJd8fliBsupSnFgMnXxmtWqk/edit?usp=sharing

Requirements require review before continuing on design.

**Comment by jm3** [comment]
@jrgifford @andvgal looks like rvm-binaries is abandoned as well. can you advise what the shortest path is to compile a set of binary OSX rubies for modern versions e.g. 2.6.*, 2.7.0, etc?

**Comment by pkuczynski** [comment]
rvm-binaries are not abandoned and we try to keep building packages.
