### ISSUE TITLE
Adding a cask for homebrew

### ISSUE THREAD

**Issue by Dorian** [rvm/rvm#4088]
Doing `brew install rvm` would be sweet.

https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

Not sure how complicated this would be, but it would be super-sweet.

**Comment by mpapis** [comment]
Adding a new package for each system increases maintenance costs, read: time - which is scarce.

Unless you want to take care of preparing the package and to take care of maintaining and releasing it - I'm afraid we can not spare time for it.

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
