### ISSUE TITLE
How to prevent nailgun from being started or use a different port

### ISSUE THREAD

**Issue by estolfo** [rvm/rvm#4089]
## Description

Hello,

I'm having issues in my continuous integration testing environment with nailgun automatically being started after ``rvm use jruby`` is called. Namely, there is something already running on the port the nailgun server is attempted to be started on. What solution do you recommend?

I've done some research and some people suggest editing the hook script. I thought I could also do one of the following:

1. stop the nailgun server
2. prevent it from being started
3. start it on another port

I was wondering if there was a way I could achieve one of the above from a bash script, as my tests run on different operating systems and depending on knowing where the hook script is located would be a fragile solution.

Thank you in advance
Emily

**Comment by mpapis** [comment]
starting of nailgun is controlled with https://github.com/rvm/rvm/blob/master/hooks/after_use_jruby it can be disabled with:

```bash
chmod -x $rvm_path/hooks/after_use_jruby
```

If you would like this script (and https://github.com/rvm/rvm/blob/master/scripts/functions/hooks/jruby) can be modified to support the port flag

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Comment by BrianHawley** [comment]
@mpapis the problem was detection of the running server. See #4412.
