### ISSUE TITLE
cannot load such file -- zlib

### ISSUE THREAD

**Issue by morganp** [rvm/rvm#4090]
## Description

gem install does not work, exiting with a zlib error. 

Also trying to upgrade to master to check out the latest rvm fails looking like the same error but with debug gives: https://gist.github.com/morganp/2896d077eaed5916628715d310130e77#file-with-debug-log

## Steps to reproduce

    gem install bundler

## Expected behavior
  
  Gem is installed

## Actual behavior

    ERROR:  Loading command: install (LoadError)
    	cannot load such file -- zlib
    ERROR:  While executing gem ... (NoMethodError)
        undefined method `invoke_with_build_args' for nil:NilClass

Log of rvm get master : https://gist.github.com/morganp/2896d077eaed5916628715d310130e77

## Environment info

ruby-2.4.0@VerilogRename:

  system:
    uname:        "Darwin edimac750773.ad.cirrus.com 15.6.0 Darwin Kernel Version 15.6.0: Tue Apr 11 16:00:51 PDT 2017; root:xnu-3248.60.11.5.3~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.11"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)"
    zsh:          "/bin/zsh => zsh 5.0.8 (x86_64-apple-darwin15.0)"
    remote_path:  "osx/10.11/x86_64"

  rvm:
    version:      "1.29.2 (master)"
    updated:      "5 minutes 51 seconds ago"
    path:         "/Users/morgan/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.0p0"
    date:         "2016-12-24"
    platform:     "x86_64-darwin15"
    patchlevel:   "2016-12-24 revision 57164"
    full_version: "ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]"

  homes:
    gem:          "/Users/morgan/.rvm/gems/ruby-2.4.0@VerilogRename"
    ruby:         "/Users/morgan/.rvm/rubies/ruby-2.4.0"

  binaries:
    ruby:         "/Users/morgan/.rvm/rubies/ruby-2.4.0/bin/ruby"
    irb:          "/Users/morgan/.rvm/rubies/ruby-2.4.0/bin/irb"
    gem:          "/Users/morgan/.rvm/rubies/ruby-2.4.0/bin/gem"
    rake:         "/Users/morgan/.rvm/rubies/ruby-2.4.0/bin/rake"

  environment:
    PATH:         "/Users/morgan/.rvm/gems/ruby-2.4.0@VerilogRename/bin:/Users/morgan/.rvm/gems/ruby-2.4.0@global/bin:/Users/morgan/.rvm/rubies/ruby-2.4.0/bin:/Users/morgan/.rvm/bin:/Users/morgan/perl5/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:.:/Users/morgan/dotfiles/bin"
    GEM_HOME:     "/Users/morgan/.rvm/gems/ruby-2.4.0@VerilogRename"
    GEM_PATH:     "/Users/morgan/.rvm/gems/ruby-2.4.0@VerilogRename:/Users/morgan/.rvm/gems/ruby-2.4.0@global"
    MY_RUBY_HOME: "/Users/morgan/.rvm/rubies/ruby-2.4.0"
    IRBRC:        "/Users/morgan/.rvm/rubies/ruby-2.4.0/.irbrc"
    RUBYOPT:      ""
    gemset:       "VerilogRename"

**Comment by morganp** [comment]
Ran `brew doctor` and removed the unexpected dylibs:

```
   Unexpected dylibs:
  /usr/local/lib/libcrypto.0.9.8.dylib
  /usr/local/lib/libcrypto.1.0.0.dylib
  /usr/local/lib/libcrypto.dylib
  /usr/local/lib/libklcsagt.dylib
  /usr/local/lib/libklcskca.dylib
  /usr/local/lib/libklcsnagt.dylib
  /usr/local/lib/libklcsrt.dylib
  /usr/local/lib/libklcsstd.dylib
  /usr/local/lib/libklcstr.dylib
  /usr/local/lib/libklmspack.0.1.0.dylib
  /usr/local/lib/libklmspack.0.dylib
  /usr/local/lib/libklmspack.dylib
  /usr/local/lib/libssl.0.9.8.dylib
  /usr/local/lib/libssl.1.0.0.dylib
  /usr/local/lib/libssl.dylib
  /usr/local/lib/libz.1.2.5.dylib
  /usr/local/lib/libz.1.2.6.dylib
  /usr/local/lib/libz.1.dylib
  /usr/local/lib/libz.dylib
```

Then ran:

    rvm requirements

Which installed gcc49

```
Warning! PATH is not properly set up, '/Users/morgan/.rvm/gems/ruby-2.4.0@VerilogRename/bin' is not at first place.
         Usually this is caused by shell initialization files. Search for 'PATH=...' entries.
         You can also re-add RVM to your profile by running: 'rvm get stable --auto-dotfiles'.
         To fix it temporarily in this shell session run: 'rvm use ruby-2.4.0@VerilogRename'.
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
Checking requirements for osx.
Installing requirements for osx.
Updating system.........
Installing required packages: gcc49.......
Certificates in '/usr/local/etc/openssl@1.1/cert.pem' are already up to date.
Requirements installation successful.
```

gem install is working again.

**Comment by amitmojumder** [comment]
My default version of ruby is - `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]`
I am also Getting the same error for `sudo gem install sass`
```
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```
Any idea how can I get rid of that?

**Comment by maaikeleo** [comment]
∞Ubuntu

RVM have dedicated Ubuntu package, so please follow instructions posted here: https://github.com/rvm/ubuntu_rvm

If you need a different (newer) version of RVM, after installing base version of RVM check the Upgrading section.
∞Any other system

Install RVM (development version):

\curl -sSL https://get.rvm.io | bash

Install RVM stable with ruby:

\curl -sSL https://get.rvm.io | bash -s stable --ruby

**Comment by marin-zaimov** [comment]
I'm having the same issue on Mac high sierra when running 'gem install bundler'

I had the same brew issues @morganp described, but following his steps, did not help.
Brew and rvm requirements report no errors.

`Checking requirements for rvm_pkg.

Warning, you are using 'rvm autolibs rvm_pkg', this is rarely used and can produce errors,
make sure to report any problems to https://github.com/rvm/rvm/issues

Requirements installation successful.`

Any ideas where I can look next?

**Comment by marin-zaimov** [comment]
`rvm pkg install zlib` fixed my issue
