### ISSUE TITLE
rvm issue

### ISSUE THREAD

**Issue by junaid-malik-confiz** [rvm/rvm#4091]
Hello,

We are experiencing slow execution of same ruby version(2.1.2p95) on different system. Please find the files of command `ruby -rrbconfig -e 'puts RbConfig::CONFIG.map{|k,v| k+":\t"+v}' | sort`. There is only difference of `--enable-shared`. I tried to install ruby by disabling `--enable-share` using different ways but it didn't wok for me.

- slow - https://gist.github.com/junaid-malik-confiz/2b6695f4a90b8641d82f7d0c90cf9139
- fast - https://gist.github.com/junaid-malik-confiz/c46bcef4460dd8d08f701a417b2ea416

**Version of RVM :** 
-----------------------------------------------
```bash
# rvm -v
rvm 1.29.2 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io/]
```

Regards,
Junaid

**Comment by mpapis** [comment]
try `rvm install 2.1.2 -C --disable-shared`

**Comment by junaid-malik-confiz** [comment]
Hello mpapis,

It is still not working, please check the output of following command 'ruby -rrbconfig -e 'puts RbConfig::CONFIG.map{|k,v| k+":\t"+v}' | sort'. Here is the url https://gist.github.com/junaid-malik-confiz/345ee6260318a484f5d1fd9095ff0a95

I use the command 'rvm install 2.1.2 -C --disable-shared'

Regards,
Junaid

**Comment by mpapis** [comment]
You can build now with:
```bash
rvm install 2.1.2 --disable-shared
```
