### ISSUE TITLE
rvm is all kinds of broken under ksh

### ISSUE THREAD

**Issue by begrif** [rvm/rvm#4094]
I'm using Ubuntu 16.04, and I installed the Ubuntu package version of rvm (`rvm_1.29.1-1_all.deb`).

My login shell is ksh, provided by ksh93 ("Version AJM 93u+ 2012-08-01"), installed from the standard Ubuntu packages.

Very little of rvm works under this shell. For starters, `/etc/profile.d/rvm.sh` checks for $BASH_VERSION and $ZSH_VERSION and then finding neither, does nothing.

If I manually try a `source /usr/share/rvm/scripts/rvm` I start to find all sorts of bash and/or zsh specific syntax that doesn't work in ksh.  But there are a few sprinklings of $KSH_VERSION in the files.

**Is the state of affairs that ksh had been supported and no longer is? Or will someday be supported but not yet? Or some third choice?**

As an example of syntax that is causing problems: This version of ksh is very unhappy with formations like `${=variable}`.

```
#!/bin/ksh

if false
then
${=foo}
fi

echo "Reached end"
```

Will never print "Reached end" because of the fatal syntax error on line 5.

**Comment by darkn3rd** [comment]
As a rvm user, I have found that rvm always required a recent version of bash (haven't tried zsh), so I suggest running the installer using bash 4.

**Comment by mpapis** [comment]
Unfortunately there is no way to run RVM under limited shells like `ksh`, for RVM2 I'm planning to make it  one of the options, hold tight ;)
