### ISSUE TITLE
man rvm causing grep errors

### ISSUE THREAD

**Issue by Jahhein** [rvm/rvm#4095]
When I run `man rvm` I get a crazy grep output error. I have provided a gist below. I run a ZSH shell, however `man rvm` works fun under bash.

According to the documents/source code, a man page is available to be read.

  * [x] rvm get master was done.
  * [x] updated various other ways. GPG key was accepted.

## Description

Running `man rvm` gives me the output posted in the gist below.

## NOTE: Although I have GEM_PATH and RVM_PATH pointing toward a Settings directory, all files in that directory are symlinked to my $HOME directory.

$ env
TERM_SESSION_ID=OMITTED
SSH_AUTH_SOCK=OMITTED
Apple_PubSub_Socket_Render=OMITTED
COLORFGBG=15;0
ITERM_PROFILE=Tomorrow Night Eighties
XPC_FLAGS=0x0
LANG=en_US.UTF-8
PWD=OMITTED
SHELL=/usr/local/bin/zsh
SECURITYSESSIONID=OMITTED
TERM_PROGRAM_VERSION=3.0.15
TERM_PROGRAM=iTerm.app
PATH=/usr/local/opt/curl/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/opt/fzf/bin:/Users/OMITTED/.rvm/bin
TERM=xterm-256color
HOME=/Users/OMITTED
TMPDIR=/var/folders/7v/cmsw3q_95cs8t9mgq536gb0w0000gn/T/
USER=OMITTED
XPC_SERVICE_NAME=0
LOGNAME=OMITTED
ITERM_SESSION_ID=w0t2p0:CC49465F-A488-43B0-BB7D-EA6A700012B7
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x0
SHLVL=1
OLDPWD=/Users/OMITTED/Developer
ZSH=/Users/OMITTED/Developer/Settings/zsh/oh-my-zsh
UPDATE_ZSH_DAYS=1
PAGER=less
LESS=-R
LC_CTYPE=en_US.UTF-8
LSCOLORS=Gxfxcxdxbxegedabagacad
ARCHFLAGS=-arch x86_64
LOCATE_PATH=/var/db/locate.database
SSH_KEY_PATH=OMITTED
EDITOR=atom
TERM_EDITOR=nvim
WORKSPACE=/Users/OMITTED/Developer
REPOSITORIES=/Users/OMITTED/Developer/Repositories
WIKIS=/Users/OMITTED/Developer/Wikis
GISTS=/Users/OMITTED/Developer/Gists
ARCHIVES=/Users/OMITTED/Developer/Archives
TMPDIRECTORY=/Users/OMITTED/Developer/Temporary
SETTINGS=/Users/OMITTED/Developer/Settings
ZSH_CONFIG=/Users/OMITTED/Developer/Settings/zsh
HELPDIR=/usr/local/share/zsh/help
BASH_CONFIG=/Users/OMITTED/Developer/Settings/bash
JAVA_HOME=/Library/Java/Home
GEM_PATH=/Users/OMITTED/Developer/Settings/.gem
RVM_PATH=/Users/OMITTED/Developer/Settings/.rvm/bin
PY27_PATH=/Library/Frameworks/Python.framework/Versions/2.7/bin
PY35_PATH=/Library/Frameworks/Python.framework/Versions/3.5/bin
MANPATH=/usr/local/man:
GOPATH=/usr/local/opt/go/libexec/bin
YARN_PATH=/usr/local/Cellar/yarn/0.24.6/bin
NVIDIA_CUDA=/Developer/NVIDIA/CUDA-6.0/bin
CURL_PATH=/usr/local/opt/curl/bin
WAKATIME_HOME=/Users/OMITTED/Developer/Settings
ZNT_REPO_DIR=/usr/local/share/zsh-navigation-tools
ZNT_CONFIG_DIR=/Users/OMITTED/.config/znt
HOMEBREW_GITHUB_API_TOKEN=OMITTED
HOMEBREW_ANALYTICS_DEBUG=OMITTED
WAKATIME_KEY=OMITTED
VT_API_KEY=OMITTED
rvm_prefix=/Users/OMITTED
rvm_path=/Users/OMITTED/.rvm
rvm_bin_path=/Users/OMITTED/.rvm/bin
_system_type=Darwin
_system_name=OSX
_system_version=10.12
_system_arch=x86_64
rvm_version=1.29.2 (master)
_=/usr/bin/env

## Expected behavior

A man page for rvm.

## Actual behavior

https://gist.github.com/Jahhein/8ef36da31f276098183e093b90d98f96

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

system:

  system:
    uname:        "Darwin OMITTED 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/usr/local/bin/bash => GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)"
    zsh:          "/usr/local/bin/zsh => zsh 5.3.1 (x86_64-apple-darwin16.6.0)"
    remote_path:  "osx/10.12/x86_64"

  rvm:
    version:      "1.29.2 (master)"
    updated:      "2 hours 53 minutes 26 seconds ago"
    path:         "/Users/OMITTED/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/local/bin/ruby"
    irb:          "/usr/local/bin/irb"
    gem:          "/usr/local/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/usr/local/opt/curl/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/opt/fzf/bin:/Users/OMITTED/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     "/Users/OMITTED/Developer/Settings/.gem"
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by Jahhein** [comment]
This issue can be closed. A function of man was the reason for the error. Apologies for the unnecessary issue.

**Comment by mpapis** [comment]
:)
