### ISSUE TITLE
brew install coreutils failed 10.9.5

### ISSUE THREAD

**Issue by mehdi691** [rvm/rvm#4098]
## Description

I failed to install the requirement pkg coreutils for Mac OSX 10.9.5 with the command brew install coreutils.

## Steps to reproduce

 1. rvm reinstall ruby_2.4.1
 2. brew install coreutils
 

## Expected behavior

<!- I want to install coreutils pkg

## Actual behavior
Last 15 lines from /Users/Mehdi/Library/Logs/Homebrew/coreutils/03.make:
 src/ginstall -c -m 644 'man/vdir.1' '/usr/local/Cellar/coreutils/8.27/share/man/man1/gvdir.1'
 src/ginstall -c -m 644 'man/wc.1' '/usr/local/Cellar/coreutils/8.27/share/man/man1/gwc.1'
  src/ginstall -c src/unexpand '/usr/local/Cellar/coreutils/8.27/bin/./gunexpand'
 src/ginstall -c -m 644 'man/whoami.1' '/usr/local/Cellar/coreutils/8.27/share/man/man1/gwhoami.1'
  src/ginstall -c src/uniq '/usr/local/Cellar/coreutils/8.27/bin/./guniq'
 src/ginstall -c -m 644 'man/yes.1' '/usr/local/Cellar/coreutils/8.27/share/man/man1/gyes.1'
  src/ginstall -c src/unlink '/usr/local/Cellar/coreutils/8.27/bin/./gunlink'
  src/ginstall -c src/vdir '/usr/local/Cellar/coreutils/8.27/bin/./gvdir'
  src/ginstall -c src/wc '/usr/local/Cellar/coreutils/8.27/bin/./gwc'
  src/ginstall -c src/whoami '/usr/local/Cellar/coreutils/8.27/bin/./gwhoami'
  src/ginstall -c src/yes '/usr/local/Cellar/coreutils/8.27/bin/./gyes'
  src/ginstall -c src/ginstall '/usr/local/Cellar/coreutils/8.27/bin'
make[2]: *** [install-am] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 10.9.
We (and Apple) do not provide support for this old version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
echo export PATH="/usr/local/bin:$PATH" >> ~/.bash_profile

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

macbook-pro-de-mehdi:~ Mehdi$ rvm info

ruby-2.4.1:

  system:
    uname:        "Darwin macbook-pro-de-mehdi.home 13.4.0 Darwin Kernel Version 13.4.0: Mon Jan 11 18:17:34 PST 2016; root:xnu-2422.115.15~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.9"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.53(1)-release (x86_64-apple-darwin13)"
    zsh:          "/bin/zsh => zsh 5.0.2 (x86_64-apple-darwin13.0)"
    remote_path:  "osx/10.9/x86_64"

  rvm:
    version:      "1.29.2 (master)"
    updated:      "1 minute 58 seconds ago"
    path:         "/Users/Mehdi/.rvm"
    autolibs:     "[homebrew] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.0.0p481"
    date:         "2014-05-08"
    platform:     "universal.x86_64-darwin13"
    patchlevel:   "2014-05-08 revision 45883"
    full_version: "ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]"

  homes:
    gem:          "/Users/Mehdi/.rvm/gems/ruby-2.4.1"
    ruby:         "/Users/Mehdi/.rvm/rubies/ruby-2.4.1"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/Users/Mehdi/.rvm/gems/ruby-2.4.1/bin/rake"

  environment:
    PATH:         "/Users/Mehdi/.rvm/gems/ruby-2.4.1/bin:/Users/Mehdi/.rvm/gems/ruby-2.4.1@global/bin:/Users/Mehdi/.rvm/rubies/ruby-2.4.1/bin:/Users/Mehdi/.rvm/gems/ruby-2.4.1/bin:/Users/Mehdi/.rvm/gems/ruby-2.4.1@global/bin:/Users/Mehdi/.rvm/rubies/ruby-2.4.1/bin:/Users/Mehdi/.rvm/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
    GEM_HOME:     "/Users/Mehdi/.rvm/gems/ruby-2.4.1"
    GEM_PATH:     "/Users/Mehdi/.rvm/gems/ruby-2.4.1:/Users/Mehdi/.rvm/gems/ruby-2.4.1@global"
    MY_RUBY_HOME: "/Users/Mehdi/.rvm/rubies/ruby-2.4.1"
    IRBRC:        "/Users/Mehdi/.rvm/rubies/ruby-2.4.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by ziomio** [comment]
+1

**Comment by mpapis** [comment]
I fail to find the RVM connection to this problem, can you shed some light on how it is connected?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
