### ISSUE TITLE
.io domain name may be poorly managed

### ISSUE THREAD

**Issue by pruby** [rvm/rvm#4099]
Issues with the management of the .io TLD were published today:

https://thehackerblog.com/the-io-error-taking-control-of-all-io-domains-with-a-targeted-registration/

As the RVM project asks users to download and execute bash scripts from a .io domain, they could have been impacted by this issue if the wrong person had discovered it. The security of the .io management undermines all your own protections - an attacker could almost certainly have issued and used an SSL certificate using this vulnerability.

Please consider pinning the security of the installation process to a more reliable source than the domain name, for example by adding --pinnedpubkey to curl or validating a checksum of the script before execution. Alternatively, you could make the https://rvm.io/rvm/security instructions the default.

**Comment by mpapis** [comment]
I'm against switching the domain. The security issue is fixed, from this point in time any TLD can have issues, we just do not know which one will be next.

We will investigate the check `--pinnedpubkey`, although I'm not sure how much work it will require as we are using now https://letsencrypt.org/ with automated keys update every few months.

**Comment by raelgc** [comment]
@pruby Additionally, if you're using Ubuntu, you can optionally use the [dedicated package](https://github.com/rvm/ubuntu_rvm), which contains all the required files.

**Comment by pkuczynski** [comment]
Closing...
