### ISSUE TITLE
Problems installing ruby on ubuntu 17.04

### ISSUE THREAD

**Issue by WillianLucio** [rvm/rvm#4107]
Hello.

I am following the commands presented in this url: https://rvm.io/rvm/install

First
`\ Curl -sSL https://get.rvm.io | Bash`

Result of the first command
```
William William @-HP-ENVY-TS-14-Sleekbook: ~ $ gpg --keyserver hkp: recv-keys //keys.gnupg.net 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
Gpg: Total number processed: 2
Gpg: unchanged: 2
```

Second
`\ Curl -sSL https://get.rvm.io | Bash`

Result of the second command
```
Willian @ willian-HP-ENVY-TS-14-Sleekbook: ~ $ curl -sSL https://get.rvm.io | Bash
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Installing RVM to /home/willian/.rvm/
    RVM PATH line found in /home/willian/.mkshrc/home/willian/.profile/home/willian/.bashrc/home/willian/.zshrc.
    RVM sourcing line found in /home/willian/.profile/home/willian/.bash_profile/home/willian/.zlogin.
Installation of RVM in /home/willian/.rvm/ is almost complete:

  * To start using RVM you need to run `source / home / willian / .rvm / scripts / rvm`
    In all your open shell windows, in rare cases you need to reopen all shell windows.
```

Third
`\ Curl -sSL https://get.rvm.io | Bash -s stable --ruby`

Result third command
```
Willian @ willian-HP-ENVY-TS-14-Sleekbook: ~ $ curl -sSL https://get.rvm.io | Bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.29.2.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc',
But in GPG software exists to validate it, skipping.

Upgrading the RVM installation in /home/willian/.rvm/
    RVM PATH line found in /home/willian/.mkshrc/home/willian/.profile/home/willian/.bashrc/home/willian/.zshrc.
    RVM sourcing line found in /home/willian/.profile/home/willian/.bash_profile/home/willian/.zlogin.
Upgrade of RVM in /home/willian/.rvm/ is complete.

# Willian,
#
# Thank you for using RVM!
# We sincerely hope that RVM helps you make your life easier and more enjoyable !!!
#
# ~ Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * No new notes to display.

Main: line 880: __rvm_print_headline: command not found
```

I am using Ubuntu 17.04.

I'm starting to learn ruby now, so if I made a mistake I'll be forgiven.

can anybody help me?

**Comment by jrgifford** [comment]
I think that the issue is you're typing `Bash`. Commands are case sensitive -  it should be `bash` instead. Can you give that a try?

**Comment by WillianLucio** [comment]
Hi @jrgifford , thank you very much for the tip.

I am Brazilian and I speak Portuguese, and I had to assemble the text of this issue by Google Translate, so the bash was in a capital letter. But when I ran the command it was tiny.

**Comment by jrgifford** [comment]
@WillianLucio ah, ok! Hmm. Not sure. I just tried it on 17.04 a few moments ago, and it seemed to work. If you open up a new terminal, what does `type rvm | head -1` output?

**Comment by WillianLucio** [comment]
@jrgifford  I was able to do the installation.
I talked to a person in a Brazilian ruby group and he helped me in the installation.

I executed the commands
`source /home/willian/.rvm/scripts/rvm`
and
`/bin/bash --login`

After that I was able to perform the installation with the commands 
`rvm install 2.3.0`

I did not understand the reason for these commands, but it worked.
I'm grateful for your attention in solving my problem.

hug

**Comment by jrgifford** [comment]
You're welcome! Looks like you might need to set your terminal to use bash as a login shell: https://rvm.io/integration/gnome-terminal

**Comment by kyleowens10** [comment]
This issue looks like it stems from #4068 still.

Workaround here pointing to stable:

`\curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/stable/binscripts/rvm-installer | bash -s stable`

**Comment by WillianLucio** [comment]
Many thanks to all who have given their time to help me. I hope someday I will have enough knowledge to help other people in the same way that I have been helped.

I was able to solve my problem, I'll close the issue.

Thank you very much.
