### ISSUE TITLE
Can't install RVM with GPG or GPG2

### ISSUE THREAD

**Issue by eman6576** [rvm/rvm#4111]
Hello,

I have tried to install RVM on a machine running the latest OSX with no luck. When using the gpg command for installing the key, I receive an error saying the host doesn't exist. I also tried using gpg2 but also get an issue with signiture vertification failed.

**Comment by mpapis** [comment]
Is this error still happening? Does `ping keys.gnupg.net` work?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
