### ISSUE TITLE
install

### ISSUE THREAD

**Issue by gitpetr** [rvm/rvm#4114]
Здравствуйте!
Установил Дебиан 9.
Нужен Руби.
Зашел на rvm.io
As a first step install mpapis public key used to verify installation package to ensure security.

sudo 

gpg: directory '/root/.gnupg' created
gpg: new configuration file '/root/.gnupg/dirmngr.conf' created
gpg: new configuration file '/root/.gnupg/gpg.conf' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Серверы ключей недоступны
 
 

gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

gpg: directory '/root/.gnupg' created
gpg: new configuration file '/root/.gnupg/dirmngr.conf' created
gpg: new configuration file '/root/.gnupg/gpg.conf' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: Серверы ключей недоступны
 

Прочитал ниже на сайте

Note: hkp://keys.gnupg.net can sometimes timeout you may want to use different keyserver, for example:

    hkp://pgp.mit.edu

попробовал так
sudo gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 105BD0E739499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: key 3804BB82D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 2
 

Дальше
sudo \curl -sSL https://get.rvm.io | bash
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
 
Upgrading the RVM installation in /home/best/.rvm/
    RVM PATH line found in /home/best/.mkshrc /home/best/.profile /home/best/.bashrc /home/best/.zshrc.
    RVM sourcing line found in /home/best/.profile /home/best/.bash_profile /home/best/.zlogin.
Upgrade of RVM in /home/best/.rvm/ is complete.
 
Upgrade Notes:
 
  * No new notes to display.
 
 
 
\curl -sSL https://get.rvm.io | bash -s stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.29.2.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc',
but no GPG software exists to validate it, skipping.
 
Upgrading the RVM installation in /home/best/.rvm/
    RVM PATH line found in /home/best/.mkshrc /home/best/.profile /home/best/.bashrc /home/best/.zshrc.
    RVM sourcing line found in /home/best/.profile /home/best/.bash_profile /home/best/.zlogin.
Upgrade of RVM in /home/best/.rvm/ is complete.
 
# best,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.
 
In case of problems: https://rvm.io/help and https://twitter.com/rvm_io
 
Upgrade Notes:
 
  * No new notes to display.
 
main: строка 880: __rvm_print_headline: команда не найдена
 

#############
И что делать?

**Comment by raelgc** [comment]
Hi @gitpetr and thanks for raising this issue.

Please: provide all required info (you removed all info fields we requested).

Then, sorry if this is a bit hard, but, please, use English. We're a global team and English is our common language (it's not the native language for a lot of us too).

**Comment by raelgc** [comment]
Ok, I'll close this as the required info is not provided. @gitpetr, feel free to re-open adding the missing info.
