### ISSUE TITLE
WARNING: You have '~/.profile' file…

### ISSUE THREAD

**Issue by benjino** [rvm/rvm#4119]
## Description

I'm getting the following "Upgrade Notes:"

* WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/my_user_name/.bash_profile':

      source ~/.profile

I'm using this to for installation instructions and have had success with hit before but have a new MacBook Pro now and am doing it on that: http://installfest.railsbridge.org/installfest/osx_rvm#install-rvm

## Steps to reproduce

Below is what I've entered in the steps for installation and the result is saying rvm : not found

Bens-MacBook-Pro:~ my_user_name$ curl -L get.rvm.io | bash -s stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   194  100   194    0     0     39      0  0:00:04  0:00:04 --:--:--    39
100 24028  100 24028    0     0   4491      0  0:00:05  0:00:05 --:--:-- 98073
Downloading https://github.com/rvm/rvm/archive/1.29.2.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Upgrading the RVM installation in /Users/bens_photo/.rvm/
    RVM PATH line found in /Users/my_user_name/.mkshrc /Users/bens_photo/.profile /Users/bens_photo/.bashrc /Users/my_user_name/.zshrc.
    RVM sourcing line found in /Users/my_user_name/.profile /Users/my_user_name/.zlogin.
    RVM sourcing line not found for Bash, rerun this command with '--auto-dotfiles' flag to fix it.
Upgrade of RVM in /Users/my_user_name/.rvm/ is complete.

# Ben Siegfried,
#
#   Thank you for using RVM!
#   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
#
# ~Wayne, Michal & team.

In case of problems: https://rvm.io/help and https://twitter.com/rvm_io

Upgrade Notes:

  * WARNING: You have '~/.profile' file, you might want to load it,
    to do that add the following line to '/Users/my_user_name/.bash_profile':

      source ~/.profile

  * No new notes to display.

Bens-MacBook-Pro:~ my_user_name$ .bash_profile source ~/.profile
-bash: .bash_profile: command not found
Bens-MacBook-Pro:~ my_user_name$ type rvm | head -1
-bash: type: rvm: not found
Bens-MacBook-Pro:~ my_user_name$ 

## Actual behavior

I should be getting behavior that the rails fest installation says, but do not understand why I am getting "rvm: not found" and don't know what to enter to fix that.

**Comment by benjino** [comment]
update 20170812: I got it figured out, don't help now.

**Comment by SweatyKeys** [comment]
I have the same error. Could you share what you figured out?

**Comment by benjino** [comment]
For my solution, I added "~/.profile" to the file "/Users/bens_photo/.bash_profile"

That would differ for you because you would have a different User (bens_photo) I do.

So navigate to that file named ".bash_profile" and add "~/.profile" to the file. I added mine to the last line of the file.

**Comment by SweatyKeys** [comment]
thank you

**Comment by mpapis** [comment]
The `~/.profile` warning is just a warning, it is not causing any problem, the right command to load RVM after installation is:

```bash
source $HOME/.rvm/scripts/rvm
```

**Comment by benjino** [comment]
Thanks.

The error is essentially saying that I need to add "~/.profile" to the .bash_profile file. I opened that file, added "~/.profile" to a new line, saved it, and that fixed the problem.

**Comment by iitians** [comment]
Sorry im new to these. Can you explain the commands or steps in detail for the same. Im having the same issue.
