### ISSUE TITLE
Cant install 2.3.3 on ArchLinux "__rvm_make -j2"

### ISSUE THREAD

**Issue by durkh3im** [rvm/rvm#4125]
## Description

Hi! im triying to install Ruby 2.3.3 on my ArchLinux but i cant. I read a lot of fixes but no one help me

## Steps to reproduce

 1. sudo rvm get master
 2. sudo rmv info

>   system:
>     uname:        "Linux linuxdev 4.12.4-1-ARCH #1 SMP PREEMPT Fri Jul 28 18:54:18 UTC 2017 x86_64 GNU/Linux"
>     name:         "Arch"
>     version:      "libc-2.25"
>     architecture: "x86_64"
>     bash:         "/usr/bin/bash => GNU bash, versión 4.4.12(1)-release (x86_64-unknown-linux-gnu)"
>     zsh:          " => not installed"
>     remote_path:  "arch/libc-2.25/x86_64"
> 
>   rvm:
>     version:      "1.29.2 (master)"
>     updated:      "7 seconds ago"
>     path:         "/home/matias/.rvm"
>     autolibs:     "[disable] Limit RVM automation as much as possible."
> 
>   homes:
>     gem:          "not set"
>     ruby:         "not set"
> 
>   binaries:
>     ruby:         ""
>     irb:          ""
>     gem:          ""
>     rake:         ""
> 
>   environment:
>     PATH:         "/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/matias/.rvm/bin:/home/matias/.rvm/bin"
>     GEM_HOME:     ""
>     GEM_PATH:     ""
>     MY_RUBY_HOME: ""
>     IRBRC:        ""
>     RUBYOPT:      ""
>     gemset:       ""
> 

 3. sudo rvm install 2.3.3

> Searching for binary rubies, this might take some time.
> No binary rubies available for: arch/libc-2.25/x86_64/ruby-2.3.3.
> Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
> Installing Ruby from source to: /home/matias/.rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
> ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 13.7M  100 13.7M    0     0  7047k      0  0:00:02  0:00:02 --:--:-- 6845k
> ruby-2.3.3 - #extracting ruby-2.3.3 to /home/matias/.rvm/src/ruby-2.3.3....
> ruby-2.3.3 - #applying patch /home/matias/.rvm/patches/ruby/2.3.3/random_c_using_NR_prefix.patch.
> ruby-2.3.3 - #configuring..........................................................
> ruby-2.3.3 - #post-configuration..
> ruby-2.3.3 - #compiling............................................................................................................................................................................................|
> Error running '__rvm_make -j2',
> please read /home/matias/.rvm/log/1503151354_ruby-2.3.3/make.log
> There has been an error while running make. Halting the installation.

LOG 

> In file included from ossl.h:57:0,
>                  from ossl_pkey_dsa.c:12:
> /usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
>  #error "This file is obsolete; please update your software."

3. Try with 
sudo pacman -S gcc5
sudo pacman -S openssl-1.0
CC=gcc-5 rvm install 2.3.3 --with-openssl-dir=/usr/lib/openssl-1.0

> Installing Ruby from source to: /home/matias/.rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
> ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
> ruby-2.3.3 - #extracting ruby-2.3.3 to /home/matias/.rvm/src/ruby-2.3.3....
> ruby-2.3.3 - #applying patch /home/matias/.rvm/patches/ruby/2.3.3/random_c_using_NR_prefix.patch.
> ruby-2.3.3 - #configuring..........................................................
> ruby-2.3.3 - #post-configuration..
> ruby-2.3.3 - #compiling......................................................................................
> Error running '__rvm_make -j2',
> please read /home/matias/.rvm/log/1503151716_ruby-2.3.3/make.log
> There has been an error while running make. Halting the installation.

LOG

> In file included from ossl.h:57:0,
>                  from ossl_pkey_dsa.c:12:
> /usr/include/openssl/asn1_mac.h:10:2: error: #error "This file is obsolete; please update your software."
>  #error "This file is obsolete; please update your software."

**Comment by mpapis** [comment]
1. does `ruby-2.3.3` or `2.4.1` work? 
2. what versions of `openssl` are available for installation on your system?

**Comment by mpapis** [comment]
will be fixed with #4033

**Comment by VinothiniBalakrishnan** [comment]
getting the same issue. Please let me know the fix. Trying to install ruby 2.3.1 2@mpais

**Comment by mpapis** [comment]
@VinothiniBalakrishnan `rvm get master` and try again

**Comment by VinothiniBalakrishnan** [comment]
Really that helps a lot. Now issue fixed. Thanks a lot.

**Comment by danielricecodes** [comment]
I'm having the same issue too.   Ubuntu 18.04 w/ latest RVM version (aka `rvm get master`).  Ruby 2.5.1 installed just fine for what its worth.
