### ISSUE TITLE
A RVM installation of mine is failing to update gems due to openssl problems

### ISSUE THREAD

**Issue by jmfgdev** [rvm/rvm#4126]
A RVM installation of mine is returning a suggestion that I rebuild ruby or rebuild openssl and reinstall ruby, I'm trying to fix the installation now.

I'm trying to get a program running with Ruby 2.4.1 on Centos 7,
the gems will not update due to this error.

Beyond what gem suggests what could be wrong with my installation to have openssl errors? I have another server which worked just fine, even doing rvm implode and reinstalling didn't fix it.

**Comment by mpapis** [comment]
please provide `rvm info`, the commands that are failing and their output.

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
