### ISSUE TITLE
rvm requirements fails on SLES 12 sp2

### ISSUE THREAD

**Issue by rutte** [rvm/rvm#4127]
## Description
Unable to install ruby 2.4.1 on SLES 12 sp2

## Steps to reproduce
 1. Install SLES 12 sp2
 2. Install rvm
 3. rvm requirements

## Expected behavior
Fails to install packages libffi-devel and sqlite3-devel

## Actual behavior
rvm requirements
Checking requirements for suse.
Installing requirements for suse.
Updating system....
Installing required packages: libffi-devel, sqlite3-devel....
Error running 'requirements_opensuse_libs_install libffi-devel sqlite3-devel',
please read /home/wserv/.rvm/log/1503228140/package_install_libffi-devel_sqlite3-devel.log
Requirements installation failed with status: 104.

## Environment info

system:

  system:
    uname:        "Linux wcomp50 4.4.74-92.32-default #1 SMP Thu Jul 27 15:07:08 UTC 2017 (eba0211) aarch64 aarch64 aarch64 GNU/Linux"
    name:         "SuSE"
    version:      "12.2"
    architecture: "aarch64"
    bash:         "/bin/bash => GNU bash, version 4.3.42(1)-release (aarch64-suse-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "suse/12.2/aarch64"

  rvm:
    version:      "1.29.2 (master)"
    updated:      "26 minutes 11 seconds ago"
    path:         "/home/wserv/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/home/wserv/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/wserv/.rvm/bin:/home/wserv/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment]
can you [gist](https://gist.github.com) the log file `/home/wserv/.rvm/log/1503228140/package_install_libffi-devel_sqlite3-devel.log`?

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.
