### ISSUE TITLE
rvm.io SSL certificate date invalid

### ISSUE THREAD

**Issue by benjackwhite** [rvm/rvm#4129]
## Description

Our CI build for ruby projects started failing with today with certificate validation errors. Upon visiting rvm.io or get.rvm.io Chrome refuses to load the page with error code `ERR_CERT_DATE_INVALID`

## Steps to reproduce

Visit https://get.rvm.io

```
> curl https://get.rvm.io/
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

## Expected behavior

Explained

## Actual behavior

Explained

**Comment by benjackwhite** [comment]
For what its worth our temporary fix is to just pull the install file directly from Github but our concern was whether this is something more serious than just a certificate allowed to go out of date.

The file that https://get.rvm.io redirect to: https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer

**Comment by jahio** [comment]
Hey @benjackwhite - just an FYI, there's also [issue 320 open for this under rvm/rvm-site](https://github.com/rvm/rvm-site/issues/320) too; may I suggest you copy-pasta your bug report (well formed, by the way!) there for posterity? I'm doing comments on both to "link" them, but I think the more meaningful discussion on solving this will be both there and via our slack channel at [rvm-io.slack.com](https://rvm-io.slack.com). Thanks for reporting it!

**Comment by jahio** [comment]
Quick update: seems fixed in my own tests here after @mpapis bounced `nginx` manually. More details in the other ticket. I'm seeing this as solved; Ben, can you check again on your end? Try in a separate browser and/or via `curl` if it's still failing for you and you're sure your browser/os has the CA cert chain available to it. 99% sure it's good to go, just want that last 1%! 😜

**Comment by benjackwhite** [comment]
Hey @jahio. Nice work! All looks good from here for all domains. Thanks for being on top of it! 😃

**Comment by mpapis** [comment]
Indeed it was lack of nginx restart, I have written a new script to ensure this is solved https://github.com/rvm/rvm-site-setup/commit/6dd0db5ebaee3f9a686e2e895a0dd3b161345d6c
