### ISSUE TITLE
I need helping installing Install RVM

### ISSUE THREAD

**Issue by simpleaiden** [rvm/rvm#4131]
I am trying to set up RVM and getting this message "but no GPG software exists to validate it, skipping."

how can I get it validate it?

Thank you

Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.2/1.29.2.tar.gz.asc',
but no GPG software exists to validate it, skipping.

Upgrading the RVM installation in /Users/aidenlee/.rvm/
    RVM PATH line found in /Users/aidenlee/.mkshrc /Users/aidenlee/.profile /Users/aidenlee/.bashrc /Users/aidenlee/.zshrc.
    RVM sourcing line found in /Users/aidenlee/.profile /Users/aidenlee/.bash_profile /Users/aidenlee/.zlogin.
Upgrade of RVM in /Users/aidenlee/.rvm/ is complete.

**Comment by raelgc** [comment]
Hi @simpleaiden.

Please, in order we can help you, can you feel all the info we requested? 

-----------------------------------------------
```
## Description

<!-- Briefly describe the nature of your problem. -->


## Steps to reproduce

<!-- List all of your specific environment settings, actions taken, and commands run — everything required to replicate the problem. -->

 1. ...
 2. ...
 3. ...

## Expected behavior

<!-- Briefly explain what you expected to see. -->

## Actual behavior

<!-- Please include a gist (https://gist.github.com) with the output of the command(s) you ran. -->

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

<!-- When the above output does not seem to include a meaningful error message, you might want to additionally attach the output of the same command(s) run with the `--debug` switch. -->

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

<!-- Paste below the output of the `rvm info` command. -->
```

**Comment by mpapis** [comment]
looks like installation worked just fine, without performing gpg validation, please check #4059 for similar problems - might be related

**Comment by mpapis** [comment]
might be fixed with #4152, please try again with:
```bash
rvm get master
```

**Comment by mpapis** [comment]
Closing as there was no feedback in over 2 weeks, please feel free to reopen when you can provide the requested information.

**Comment by damiong28** [comment]
You need to actually install gpg2 which will verify the public keys. This can be done with homebrew by running `brew install gpg2` once you've done this try installing again.
