### ISSUE TITLE
Check installation completion

### ISSUE THREAD

**Issue by fhvd89** [rvm/rvm#4138]
After installing RVM, I entered "rvm | head -n 1" to see if installation was completed.

All I get is: 

<a href="https://www.bountysource.com/teams/rvm?utm_source=RVM&utm_medium=shield&utm_campaign=raised"><img src="https://api.bountysource.com/badge/team?team_id=506&style=raised" align="center"></a>

What does this mean? And how do I see if it has been installed?

**Comment by mpapis** [comment]
you need to literally type `type rvm | head -n 1`
