### ISSUE TITLE
Unable to install ruby 2.3 in Ubuntu 16.04

### ISSUE THREAD

**Issue by chari407** [rvm/rvm#4141]
I am unable to install ruby 2.3. Here is the error I am getting

`:~$ rvm install 2.3
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.3.tar.bz2
Checking requirements for ubuntu.
Requirements installation successful.
ruby-2.3.3 - #configure
ruby-2.3.3 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 24.8M    0     0    0     0      0      0 --:--:--  0:00:07 --:--:--     0Warning: Failed to create the file bin-ruby-2.3.3.tar.bz2.part: Permission 
Warning: denied
  0 24.8M    0  2759    0     0    386      0 18:46:38  0:00:07 18:46:31   714
curl: (23) Failed writing body (0 != 2759)
There was an error(23).
Checking fallback: ftp://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.3.tar.bz2?rvm=1.29.2
Checking fallback: https://www.mirrorservice.org/sites/rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.3.tar.bz2?rvm=1.29.2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

Downloading https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/16.04/x86_64/ruby-2.3.3.tar.bz2 failed.
Mounting remote ruby failed with status 2, trying to compile.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /usr/share/rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 13.7M    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0Warning: Failed to create the file ruby-2.3.3.tar.bz2.part: Permission denied
  0 13.7M    0  2759    0     0    634      0  6:19:26  0:00:04  6:19:22   674
curl: (23) Failed writing body (0 != 2759)
There was an error(23).
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/2.3/ruby-2.3.3.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0Warning: Failed to create the file ruby-2.3.3.tar.bz2.part: Permission denied
  0 13.7M    0 16149    0     0   5617      0  0:42:49  0:00:02  0:42:47  5617
curl: (23) Failed writing body (0 != 16149)
There was an error(23).
Failed download
There has been an error fetching the ruby interpreter. Halting the installation.
`
Can someone help me please... !!

**Comment by raelgc** [comment]
I can see a permission denied error. Probably RVM is not able to save the binary.

Can you, please, remove with a `rvm implode` and then try install the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm)?

**Comment by mpapis** [comment]
Also https://stackoverflow.com/a/9398360 - please uninstall the old and nonworking package from Ubuntu, follow instruction on rvm.io.

Closing as invalid, please let us know if you get more problems.
