### ISSUE TITLE
Rvm install ruby stucks on #configuration - please wait

### ISSUE THREAD

**Issue by liuzhen2008** [rvm/rvm#4155]
I just installed latest rvm via brew.

and then i ran rvm install ruby to download latest ruby

but it looks like it is stuck on  #configuration - please wait

**Comment by mpapis** [comment]
does adding `--debug` flag help? show us the output and full command used.

**Comment by pkuczynski** [comment]
Closing due lack of feedback. @liuzhen2008 please re-open if you have some more information...
