### ISSUE TITLE
__rvm_load_project_config:62: bad pattern: #*

### ISSUE THREAD

**Issue by Nerian** [rvm/rvm#4156]
Hello,

I get a   `__rvm_load_project_config:62: bad pattern: #*` warning when I cd into a project whose Gemfile defines a Ruby version.

Steps to reproduce:

Create a folder with a Gemfile with this contents:
```
source 'https://rubygems.org'

ruby '2.4.1'
```

Open a new terminal, and cd into the folder. You should get the warning. I noticed that I only get the warning the first time I cd into the folder – per terminal session.

I believe this is related to this issue:  https://github.com/rvm/rvm/issues/4056

Probably this lines are important:  

https://github.com/rvm/rvm/commit/bcd80d8a2b8568da93c9359665c8839af1c192a6#diff-9679cb21f908aa64828d90d6e2f3e32aR123

https://github.com/rvm/rvm/blob/master/scripts/functions/rvmrc_project#L61

I am using the latest master rvm. 

```
ruby-2.4.1:

  system:
    uname:        "Darwin MacBook-Pro-de-Gonzalo.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/usr/local/bin/bash => GNU bash, versión 4.4.12(1)-release (x86_64-apple-darwin16.3.0)"
    zsh:          "/usr/local/bin/zsh => zsh 5.4.1 (x86_64-apple-darwin16.7.0)"
    remote_path:  "osx/10.12/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "13 minutes 39 seconds ago"
    path:         "/Users/Nerian/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.1p111"
    date:         "2017-03-22"
    platform:     "x86_64-darwin16"
    patchlevel:   "2017-03-22 revision 58053"
    full_version: "ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]"

  homes:
    gem:          "/Users/Nerian/.rvm/gems/ruby-2.4.1"
    ruby:         "/Users/Nerian/.rvm/rubies/ruby-2.4.1"

  binaries:
    ruby:         "/Users/Nerian/.rvm/rubies/ruby-2.4.1/bin/ruby"
    irb:          "/Users/Nerian/.rvm/rubies/ruby-2.4.1/bin/irb"
    gem:          "/Users/Nerian/.rvm/rubies/ruby-2.4.1/bin/gem"
    rake:         "/Users/Nerian/.rvm/gems/ruby-2.4.1/bin/rake"

  environment:
    PATH:         "/Users/Nerian/.rvm/gems/ruby-2.4.1/bin:/Users/Nerian/.rvm/gems/ruby-2.4.1@global/bin:/Users/Nerian/.rvm/rubies/ruby-2.4.1/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/Users/Nerian/bin:/usr/bin:/bin:/usr/sbin:/usr/local/bin:/sbin:/opt/X11/bin:/Users/Nerian/.rvm/bin"
    GEM_HOME:     "/Users/Nerian/.rvm/gems/ruby-2.4.1"
    GEM_PATH:     "/Users/Nerian/.rvm/gems/ruby-2.4.1:/Users/Nerian/.rvm/gems/ruby-2.4.1@global"
    MY_RUBY_HOME: "/Users/Nerian/.rvm/rubies/ruby-2.4.1"
    IRBRC:        "/Users/Nerian/.rvm/rubies/ruby-2.4.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by tl3shi** [comment]
how to suppress this warning?

**Comment by mpapis** [comment]
it's fixed: `rvm get master`

**Comment by ErvalhouS** [comment]
`rvm get master` makes a wrapper readme open everytime I change directories.

**Comment by mpapis** [comment]
@ErvalhouS please open a new ticket, I should be able to fix it in 24hgiven I get all required information.

**Comment by belgoros** [comment]
I have the same issue after updating the RVM yesterday. Any ideas ?

**Comment by belgoros** [comment]
`rvm get master` worked and fixed the issue. Thank you @mpapis

**Comment by bbugh** [comment]
I was still getting this problem as well after running `rvm get master`. It turns out that it was an environment/node/nvm problem. If you find this issue from a web search, this comment might help you: https://github.com/rvm/rvm/issues/2385#issuecomment-398093195
