### ISSUE TITLE
enterprise proxy whitelist questions

### ISSUE THREAD

**Issue by jjmiv** [rvm/rvm#4157]
I am using rvm but wanted to know what URLs I need to have whitelisted in the enterprise proxy.  I am aware of rvm.io but what URLs should I include that rvm might access in order to get dependencies.  rubygems.org is working already but want to make sure I have things covered.  is there a way to config rvm to use specific URLs for things over others?

thanks!

**Comment by mpapis** [comment]
check this files:
- https://github.com/rvm/rvm/blob/master/config/db
- https://github.com/rvm/rvm/blob/master/config/md5
- https://github.com/rvm/rvm/blob/master/config/remote
- https://github.com/rvm/rvm/blob/master/config/sha512

I guess you could run a simple grep like:
```bash
# grep -roE "http[s]?://[^/]+/.*$" $rvm_path/config | sed -Ee 's/.*(https?:\/\/[^\/]+)\/.*/\1/' | sort -uV
https://bitbucket.org
https://cache.ruby-lang.org
https://dl.fedoraproject.org
https://download-codeplex.sec.s-msft.com
https://ftp.gnu.org
https://ftp.ruby-lang.org
https://github.com
https://llvm.org
https://prdownloads.sourceforge.net
https://rubygems.org
https://rvm_io.global.ssl.fastly.net
https://s3.amazonaws.com
https://storage.googleapis.com
https://www.openssl.org
http://downloads.sourceforge.net
http://ftp.gnome.org
http://ftp.novell.com
http://macruby.jp
http://macruby.macosforge.org
http://pkgconfig.freedesktop.org
http://pyyaml.org
http://rubyforge.org
http://seaside.gemtalksystems.com
```

**Comment by pkuczynski** [comment]
I think we can close this one. @jjmiv feel free to re-open if you have further questions.
