### ISSUE TITLE
IRB history gets saved in the RUBY_HOME instead of HOME

### ISSUE THREAD

**Issue by martijn** [rvm/rvm#4158]
## Description

After updating rvm 1.29.1 to 1.29.3 history gets saved in ` ~/.rvm/rubies/ruby-2.x.x/.irbrc_history` or `/usr/local/rvm/rubies/ruby-2.x.x/.irbrc_history` instead of `~/irb-history`.

We've witnessed this on all our system-wide CentOS 7 installations as wel as local macOS installations.

This is troublesome in a system installation because it leaks history between users and the file is owned by the user who created it, leading to irb errors for other users.

## Steps to reproduce

- Install rvm 1.29.3

- Select an rvm ruby

- Start irb

- Enter some statements

- Quit irb

- Notice history gets saved in the ruby directory instead of the home directory

## Expected behavior

When running rvm with the default settings I expect history to be saved in ~/.irb-history as it was with 1.29.1 (did not test 1.29.2).

## Actual behavior

History gets saved in ~/.rvm/rubies/ruby-2.x.x/.irbrc_history / /usr/local/rvm/rubies/ruby-2.x.x/.irbrc_history

**Comment by mpapis** [comment]
please try with `rvm get branch /bugfix/4158-restore-irb-history-to-home`

**Comment by martijn** [comment]
Sorry for the delay.  I can confirm the fix works in all our environments. Thanks for the swift response @mpapis!

**Comment by bvogel** [comment]
Shouldn't both of this lines be
```
IRB.conf[:SAVE_HISTORY] ||= 100
IRB.conf[:HISTORY_FILE] ||= File.join(ENV["HOME"], ".irb-history")
```
otherwise all user configuration would be lost?

**Comment by pkuczynski** [comment]
@mpapis what you think?
