### ISSUE TITLE
Issue installing 2.1.4 on Travis CI

### ISSUE THREAD

**Issue by mckaz** [rvm/rvm#4164]
As stated, this is happening with Travis CI, so the error/log can be viewed here: https://travis-ci.org/plum-umd/rdl/jobs/275253641

Basically, just for version 2.1.4, I'm getting the error message:
`Requested binary installation but no rubies are available to download, consider skipping --binary flag. 

Gemset '' does not exist, 'rvm ruby-2.1.4 do rvm gemset create ' first, or append '--create'.`

I am not certain that this is an issue with RVM or if it's more general to Travis.

**Comment by pkuczynski** [comment]
Changing to `rvm install 2.1.4 --default` should help
