### ISSUE TITLE
JRUBY 1.7.22 install fails on Ubuntu

### ISSUE THREAD

**Issue by bappelt** [rvm/rvm#4166]
Previously successful installations of JRUBY 1.7.22 are now failing.

## Expected behavior

"rvm install jruby-1.7.22" should succeed

## Actual behavior

[Output of command here](https://gist.github.com/bappelt/1c8140d848413149dc47bccef5c4a6f8)

Install seems to fail due to attempt to run non-existent /usr/share/rvm/src/jruby-1.7.22/mvnw

[contents of mvnw.log](https://gist.github.com/bappelt/e89872b127b47ab8c7fc4eb265259d84)

## Environment info

root@ubuntu-512mb-nyc3-01:~# rvm info

system:

  system:
    uname:        "Linux ubuntu-512mb-nyc3-01 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "16.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/16.04/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "25 minutes 15 seconds ago"
    path:         "/usr/share/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment]
please try `rvm get branch /bugfix/4166_jruby_17_installation` - it worked for me :)

**Comment by bappelt** [comment]
That seems to have fixed it. Thanks!
