### ISSUE TITLE
Wrapper fails to find testrb file

### ISSUE THREAD

**Issue by drathore1** [rvm/rvm#4180]
## Description

I recently install ruby 2.4.1 , installation went fine but when trying to create wrapper to run as service it returns error. 

running rvm wrapper for 2.4.1 returns error:

rvm wrapper ruby-2.4.1 test-serv
Regenerating ruby-2.4.1 wrappers........
which: no testrb in (/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/local/rvm/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin)
Could not find file 'testrb' nor '/usr/local/rvm/wrappers/ruby-2.4.1/testrb'.

## Environment info

rvm info

ruby-2.4.1:

  system:
    uname:        "Linux oak-vcs2559.xxx.xxxx.com 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Apr 21 10:35:19 CDT 2015 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Scientific"
    version:      "6"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)"
    zsh:          "/bin/zsh => zsh 4.3.10 (x86_64-koji-linux-gnu)"
    remote_path:  "scientific/6/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "2 minutes 2 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.1p111"
    date:         "2017-03-22"
    platform:     "x86_64-linux"
    patchlevel:   "2017-03-22 revision 58053"
    full_version: "ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.4.1"
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.1"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.1/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.4.1/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.4.1/bin/gem"
    rake:         "/usr/local/rvm/rubies/ruby-2.4.1/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/gems/ruby-2.4.1@global/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/local/rvm/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.4.1"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.4.1:/usr/local/rvm/gems/ruby-2.4.1@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.4.1"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.4.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment]
please try with:
```bash
rvm get branch /feature/4180-simplified_wrapper
rvm reload
rvm wrapper path unicorn # replace with your binary name
```

**Comment by german-e-mas** [comment]
I am getting this error as well, using ruby-2.2.0

```
Creating alias current for ruby-2.2.0@gems....
Regenerating ruby-2.2.0 wrappers........
Could not find file 'testrb' nor '/home/german/.rvm/wrappers/ruby-2.2.0/testrb'.
```

After using the first two lines, the warning message is gone. Is the third line (`rvm wrapper path unicorn`) needed?

**Comment by mpapis** [comment]
@german-e-mas the last line is required only on server when you want to use one of the gems in a service.

**Comment by bicepjai** [comment]
I have this issue happening out of no where

**Comment by IndigoHomme** [comment]
I used the first line: rvm get branch /feature/4180-simplified_wrapper
and got:

Downloading https://github.com/rvm/rvm/archive/feature/4180-simplified_wrapper.tar.gz
curl: (22) The requested URL returned error: 404 Not Found

**Comment by mpapis** [comment]
@IndigoHomme this is already merged, master or stable should both work, if you are still having problems - please open a new issue
