### ISSUE TITLE
Unable to Install Ruby on OpenSuSE Tumbleweed

### ISSUE THREAD

**Issue by japellerano** [rvm/rvm#4181]
## Description

Cannot install ruby on Tumbleweed. 

The issue is when OpenSuSE Tumbleweed reports the system name and version number differently than what is in the requirements. The issue is reported as libdb-4_5 is not installed, but libdb-4_8 is installed and is fixed in issue:  #3305

The output from my Tumbleweed system:
```
james@ithilien:~/Dev/rvm> echo ${_system_name}
OpenSuSE
james@ithilien:~/Dev/rvm> echo ${_system_version}
20170913
```

The file in question is: rvm/scripts/functions/requirements/opensuse

## Steps to reproduce

OpenSuSE Tumbleweed

 1. Install stable or head version of rvm
 2. Install ruby-2.X
 
## Expected behavior

Expected RVM to install ruby and the dependencies to compile ruby.

## Actual behavior

* [command](https://gist.github.com/japellerano/142b5e1752e94807695ef26db79fd893)

## Environment info

james@ithilien:~/Dev/rvm> rvm info

system:

  system:
    uname:        "Linux ithilien 4.13.1-1-default #1 SMP PREEMPT Sun Sep 10 12:02:44 UTC 2017 (0d725b5) x86_64 x86_64 x86_64 GNU/Linux"
    name:         "OpenSuSE"
    version:      "20170913"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.12(1)-release (x86_64-suse-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.3.1 (x86_64-suse-linux-gnu)"
    remote_path:  "opensuse/20170913/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "1 day 47 minutes 7 seconds ago"
    path:         "/home/james/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/home/james/bin:/usr/local/bin:/usr/bin:/bin:/home/james/.rvm/bin:/home/james/.rvm/bin:/home/james/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

Thank you for the help. Let me know how I can help.

**Comment by pkuczynski** [comment]
We made some fixes in#4177. Have you tried after `rvm get master`?

**Comment by japellerano** [comment]
#4177  works for me. Thank you.

**Comment by pkuczynski** [comment]
Awesome!
