### ISSUE TITLE
'rvm requirements' lists dependencies and completes sucessfully but does not install anything

### ISSUE THREAD

**Issue by Kallaste** [rvm/rvm#4182]
## Description

I just installed RVM for the first time on Slackware Linux. I am a new user, so sorry if I am missing something. I did a single user installation.

I ran `rvm requirements`, and even though there are several dependencies and it tells me it completed successfully, nothing is getting installed. Here is the output:

```
bash-4.3$ rvm requirements
Checking requirements for unknown.
Install: 
press any key to continue
Install: build-essential libreadline zlib1g libyaml libc6 libgdbm ncurses
press any key to continue
Requirements installation successful.
```
However, it does not pause after the last "press any key to continue" in order to install the listed libraries, and if I run it again, it keeps showing these same dependencies. 

I would expect RVM to either install the dependencies or tell me to install them myself through my distribution. Am I missing a simple explanation?

**Comment by pkuczynski** [comment]
You don't need to run `rvm requirements`. Instead, after installing rvm, run `rvm install XXX` where XXX is a version of ruby you want to install. Eg. `rvm install 2.4.1`. Hope that helps? If you encounter any problems, please re-open this issue...

**Comment by Kallaste** [comment]
Alright, thank you. I actually did install ruby without any issues. I was just confused as to why it would be telling me there were requirements and that they were installed when that was not the case. Am I misunderstanding the output? It seems to clearly say those packages are required and were installed.

**Comment by pkuczynski** [comment]
I think you misunderstood the output. RVM to be able to compile and install ruby, does usually install some dependencies if they not already in the system.
