### ISSUE TITLE
rvm install ruby-2.3.4 fails  - Error running '__rvm_make -j4'

### ISSUE THREAD

**Issue by melostbr** [rvm/rvm#4186]
## Description

I'm trying to install ruby-2.3.4 but I keep receiving the same error `Error running '__rvm_make -j4'`. I've already run the `rvm get master` command, but the error is the same.

`Linux melost 4.12.0-1-amd64 #1 SMP Debian 4.12.6-1 (2017-08-12) x86_64 GNU/Linux`

## Steps to reproduce

Run `rvm install ruby-2.3.4`

## Expected behavior

That ruby-2.3.4 was installed successfully

## Actual behavior

* [`rvm install ruby-2.3.4` output](https://gist.github.com/melostbr/16f1a34b7353a100c6b0201f400face2#file-output_rvm_install)
* [`rvm install ruby-2.3.4 --debug` output](https://gist.github.com/melostbr/1e1e8faddadeb71a7c90c0161ff8722e#file-output_rvm_install_with_debug)
* [`rvm debug` output](https://gist.github.com/melostbr/33c27caeeeb43019d0ea0d72567852b8#file-output_rvm_debug)
* [output of make.log](https://gist.github.com/melostbr/6196a73a94fd1471d6933438e02b3ebf#file-make-log)

## Environment info

* [`rvm info` output](https://gist.github.com/melostbr/9d87cd0834140331f3ec507ab119982d#file-output_rvm_info)

**Comment by mpapis** [comment]
looks like RVM is not able to read your system version, this problem is solved already when the version can be read, but in your case it's not possible please show us output of:
```bash
awk -F'=' '$1=="VERSION_ID"{gsub(/"/,"");print $2}' /etc/os-release | \command \awk -F. '{print $1}' | head -n 1

head -n 100 /etc/*-release
```

**Comment by melostbr** [comment]
Thank you for the attention @mpapis! The output of the requested command is:
```
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by pkuczynski** [comment]
@melostbr that's strange. Could you post output of following commands:

* `for i in /etc/*version; do echo "$i"; echo ; cat "$i"; echo ; done ;`
* `for i in /etc/*-release; do echo "$i"; echo ; cat "$i"; echo ; done ;`

This will help me to solve your problem. Do you know which version of operating system you have?

**Comment by melostbr** [comment]
@pkuczynski these are the outputs:
```
☻  for i in /etc/*version; do echo "$i"; echo ; cat "$i"; echo ; done ;                                                                                                                                                                                        
/etc/debian_version

buster/sid
```
```
☻  for i in /etc/*-release; do echo "$i"; echo ; cat "$i"; echo ; done ;                                                                
/etc/os-release

PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by pkuczynski** [comment]
Thanks! That's very helpful. I prepared a patch for you. Could you please try:

```
rvm get branch /feature/debian-buster
rvm info
rvm install ruby-2.3.4
```

If it does not help, please run the last command again with `--debug` switch and post all the logs, as you did in bug desc...

**Comment by melostbr** [comment]
Thank you! Here are the logs:

[rvm get branch /feature/debian-buster](https://gist.github.com/melostbr/eeed95d377b32dc846649c2538dc2cd3)
[rvm info](https://gist.github.com/melostbr/e15f1c4abdc9bdde9c387d4dd23eebe9)
[rvm install ruby-2.3.4 --debug](https://gist.github.com/melostbr/a1eea8a9e89f21408d2f1982b8d67953)

**Comment by melostbr** [comment]
@mpapis I'm sorry, but why is this issue closed? The problem is still happening =(

**Comment by pkuczynski** [comment]
it was mistake @melostbr, don't worry about it. I am just working on another fix...

**Comment by pkuczynski** [comment]
@melostbr please try again

```
rvm get branch /feature/debian-buster
rvm install ruby-2.3.4
```

Took me a while but should work well now :)

**Comment by melostbr** [comment]
@pkuczynski Now the problem is really solved! Thank you very much for your help!

**Comment by pkuczynski** [comment]
I am glad I could help. I will merge the pr and from now on, until the version is released, this fix will be available after `rvm get master`

**Comment by benwtr** [comment]
I just ran into this too. The real problem is that it's not reliable or recommended to get VERSION or VERSION_ID from `/etc/os-release`. 

The `os-release(5)` man page literally says _don't do this_:
> Note that operating system vendors may choose not to provide version information, for example to accommodate for rolling releases. In this case, VERSION and VERSION_ID may be unset. Applications should not rely on these fields to be set.

**Comment by mpapis** [comment]
@benwtr please open a new ticket describing your problem, this particular problem here was solved, if you are running into something similar please describe it in another ticket
