### ISSUE TITLE
Question on how RVM works on Jenkins

### ISSUE THREAD

**Issue by amesandy** [rvm/rvm#4190]
## Description

will the use of RVM on Jenkins create a new rom every time?

## Steps to reproduce

1.I have an rvm with corresponding gems
2.I have the ram plugin on Jenkins
3.Every time I run my Jenkins job it looks like it creates a new rvm, because all my gem configuration overrides.

Is that expected?

**Comment by mpapis** [comment]
Can you provide a bit more details, are there any outputs we could analyze?

**Comment by pkuczynski** [comment]
Closing due lack of feedback
