### ISSUE TITLE
kali ruby 2.3.0 Error running '__rvm_make -j4',

### ISSUE THREAD

**Issue by maddoctor87** [rvm/rvm#4191]
## Description

Error running '__rvm_make -j4',

rvm install 2.3.0
ruby-2.3.0 - #removing src/ruby-2.3.0..
Searching for binary rubies, this might take some time.
No binary rubies available for: kali/kali-rolling/x86_64/ruby-2.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.0, this may take a while depending on your cpu(s)...
ruby-2.3.0 - #downloading ruby-2.3.0, this may take a while depending on your connection...
ruby-2.3.0 - #extracting ruby-2.3.0 to /usr/local/rvm/src/ruby-2.3.0....
ruby-2.3.0 - #applying patch /usr/local/rvm/patches/ruby/ruby_2_3_gcc7.patch.
ruby-2.3.0 - #applying patch /usr/local/rvm/patches/ruby/changeset_r53419.diff.
ruby-2.3.0 - #applying patch /usr/local/rvm/patches/ruby/2.3.0/random_c_using_NR_prefix.patch.
ruby-2.3.0 - #configuring..........................................................
ruby-2.3.0 - #post-configuration..
ruby-2.3.0 - #compiling...........................................................................................................................................................................................|
Error running '__rvm_make -j4',
please read /usr/local/rvm/log/1506281255_ruby-2.3.0/make.log
There has been an error while running make. Halting the installation.

[make.log](https://github.com/rvm/rvm/files/1327836/make.log)

## Steps to reproduce

rvm get master 

rvm install 2.3.0

## Environment info

rvm info

ruby-2.4.2:

  system:
    uname:        "Linux madhack 4.12.0-kali1-amd64 #1 SMP Debian 4.12.6-1kali6 (2017-08-30) x86_64 GNU/Linux"
    name:         "Kali"
    version:      "kali-rolling"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, versione 4.4.12(1)-release (x86_64-pc-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.4.1 (x86_64-debian-linux-gnu)"
    remote_path:  "kali/kali-rolling/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "3 hours 18 minutes 28 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[0] Limit RVM automation as much as possible."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.2p198"
    date:         "2017-09-14"
    platform:     "x86_64-linux"
    patchlevel:   "2017-09-14 revision 59899"
    full_version: "ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.4.2"
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.2"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.4.2/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.4.2/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.4.2/bin/gem"
    rake:         "/usr/local/rvm/rubies/ruby-2.4.2/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.4.2/bin:/usr/local/rvm/gems/ruby-2.4.2@global/bin:/usr/local/rvm/rubies/ruby-2.4.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/rvm/bin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.4.2"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.4.2:/usr/local/rvm/gems/ruby-2.4.2@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.4.2"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.4.2/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment]
I thought we had this problem sorted out, can you try if `ruby-2.3.4` installs properly? We might need to backport some code.

**Comment by maddoctor87** [comment]
rvm install 2.3.4
ruby-2.3.4 - #removing src/ruby-2.3.4..
Searching for binary rubies, this might take some time.
No binary rubies available for: kali/kali-rolling/x86_64/ruby-2.3.4.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.4, this may take a while depending on your cpu(s)...
ruby-2.3.4 - #downloading ruby-2.3.4, this may take a while depending on your connection...
ruby-2.3.4 - #extracting ruby-2.3.4 to /usr/local/rvm/src/ruby-2.3.4....
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/ruby_2_3_gcc7.patch.
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/2.3.4/fix_rb_thread_fd_close.patch.
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/2.3.4/random_c_using_NR_prefix.patch.
ruby-2.3.4 - #configuring......................................................-
ruby-2.3.4 - #post-configuration..
ruby-2.3.4 - #compiling..............................................................................................................................-
Error running '__rvm_make -j4',
please read /usr/local/rvm/log/1507016118_ruby-2.3.4/make.log
There has been an error while running make. Halting the installation.
root@madhack:~# 
[make.log](https://github.com/rvm/rvm/files/1351493/make.log)

**Comment by schovi** [comment]
Having same problem with installing 2.4.0 on osx high sierra (fresh rvm installation).

**Comment by schovi** [comment]
```
ruby-2.4.2:

  system:
    uname:        "Darwin Saskia.local 17.2.0 Darwin Kernel Version 17.2.0: Mon Sep 18 15:44:59 PDT 2017; root:xnu-4570.20.55~19/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/usr/local/bin/zsh => zsh 5.4.2 (x86_64-apple-darwin17.0.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "1 hour 8 minutes 44 seconds ago"
    path:         "/Users/schovi/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.2p198"
    date:         "2017-09-14"
    platform:     "x86_64-darwin17"
    patchlevel:   "2017-09-14 revision 59899"
    full_version: "ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]"

  homes:
    gem:          "/Users/schovi/.rvm/gems/ruby-2.4.2"
    ruby:         "/Users/schovi/.rvm/rubies/ruby-2.4.2"

  binaries:
    ruby:         "/Users/schovi/.rvm/rubies/ruby-2.4.2/bin/ruby"
    irb:          "/Users/schovi/.rvm/rubies/ruby-2.4.2/bin/irb"
    gem:          "/Users/schovi/.rvm/rubies/ruby-2.4.2/bin/gem"
    rake:         "/Users/schovi/.rvm/rubies/ruby-2.4.2/bin/rake"

  environment:
    PATH:         "/Users/schovi/.rvm/gems/ruby-2.4.2/bin:/Users/schovi/.rvm/gems/ruby-2.4.2@global/bin:/Users/schovi/.rvm/rubies/ruby-2.4.2/bin:/Users/schovi/.rvm/bin:/usr/local/sbin:/usr/local:/usr/local/npm_packages/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Users/schovi/.bin"
    GEM_HOME:     "/Users/schovi/.rvm/gems/ruby-2.4.2"
    GEM_PATH:     "/Users/schovi/.rvm/gems/ruby-2.4.2:/Users/schovi/.rvm/gems/ruby-2.4.2@global"
    MY_RUBY_HOME: "/Users/schovi/.rvm/rubies/ruby-2.4.2"
    IRBRC:        "/Users/schovi/.rvm/rubies/ruby-2.4.2/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by pkuczynski** [comment]
It looks like an openssl problem. Could you please check which version of openssl do you have installed?

**Comment by schovi** [comment]
@pkuczynski LibreSSL 2.2.7 (via homebrew)

**Comment by schovi** [comment]
@pkuczynski after some googling with openssl this works `rvm install 2.4.0 --with-openssl-dir=/usr/local/opt/openssl`

**Comment by pkuczynski** [comment]
@schovi how did you got homebrew on kali linux?

**Comment by pkuczynski** [comment]
Ah @schovi I just noticed you have OSX. Please uninstall LibreSSL and it should all work without any additional params.

**Comment by pkuczynski** [comment]
@maddoctor87 we would need to know which version of `libssl` and `openssl` you have installed?

**Comment by pkuczynski** [comment]
Ok, I found some other comments from @maddoctor87 

```
dpkg-query -l | grep openssl
ii libevent-openssl-2.1-6:amd64 2.1.8-stable-4 amd64 Asynchronous event notification library (openssl)
ii openssl 1.1.0f-5 amd64 Secure Sockets Layer toolkit - cryptographic utility
ii perl-openssl-defaults:amd64 3 amd64 version compatibility baseline for Perl OpenSSL packages
ii python-openssl 16.2.0-1 all Python 2 wrapper around the OpenSSL library

DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
```

**Comment by pkuczynski** [comment]
So @maddoctor87 ruby 2.3.0 is not compatible with openssl 1.1.

**Comment by pkuczynski** [comment]
I at first prepared a patch, but then when testing it on kali-rolling from docker I noticed it's not really needed if you use `rvm get master`. Could you please confirm?

**Comment by maddoctor87** [comment]
rvm get master
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made sab 09 set 2017 21:49:18 CEST
gpg:                using RSA key E206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [sconosciuto]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [sconosciuto]
gpg:                 aka "[jpeg image of size 5015]" [sconosciuto]
gpg: ATTENZIONE: questa chiave non è certificata con una firma fidata!
gpg:          Non ci sono indicazioni che la firma appartenga al proprietario.
Impronta digitale della chiave primaria: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
    Impronta digitale della subchiave: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

Upgrade Notes:

  * No new notes to display.

RVM reloaded!


rvm install 2.3.4
ruby-2.3.4 - #removing src/ruby-2.3.4..
Searching for binary rubies, this might take some time.
No binary rubies available for: kali/kali-rolling/x86_64/ruby-2.3.4.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.4, this may take a while depending on your cpu(s)...
ruby-2.3.4 - #downloading ruby-2.3.4, this may take a while depending on your connection...
ruby-2.3.4 - #extracting ruby-2.3.4 to /usr/local/rvm/src/ruby-2.3.4....
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/ruby_2_3_gcc7.patch.
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/2.3.4/fix_rb_thread_fd_close.patch.
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/2.3.4/random_c_using_NR_prefix.patch.
ruby-2.3.4 - #configuring......................................................-
ruby-2.3.4 - #post-configuration..
ruby-2.3.4 - #compiling........................................................-
Error running '__rvm_make -j4',
please read /usr/local/rvm/log/1507062529_ruby-2.3.4/make.log
There has been an error while running make. Halting the installation.

dpkg-query -l | grep openssl
ii  libevent-openssl-2.1-6:amd64              2.1.8-stable-4                       amd64        Asynchronous event notification library (openssl)
ii  openssl                                   1.1.0f-5                             amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  perl-openssl-defaults:amd64               3                                    amd64        version compatibility baseline for Perl OpenSSL packages
ii  python-openssl                            16.2.0-1                             all          Python 2 wrapper around the OpenSSL library



same

**Comment by pkuczynski** [comment]
And `apt list | grep ssl` please?

**Comment by schovi** [comment]
@pkuczynski Can't uninstall. Too many dependencies on it.

**Comment by pkuczynski** [comment]
Do not uninstall. Show me what's installed so I can figure out how to fix it :)

**Comment by pkuczynski** [comment]
Especially I am interested in libssl

**Comment by amiralkizaru** [comment]
Hey 
Im having the same problem , 
https://ghostbin.com/paste/dkjvo

**Comment by pkuczynski** [comment]
@amiralkizaru I would need content of `/home/ayoub/.rvm/log/1507637353_ruby-2.3.0/make.log` and output of `rvm info`

**Comment by maddoctor87** [comment]
rvm get master
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/local/rvm/archives/rvm-installer.asc
gpg: Signature made sab 09 set 2017 21:49:18 CEST
gpg:                using RSA key E206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [sconosciuto]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [sconosciuto]
gpg:                 aka "[jpeg image of size 5015]" [sconosciuto]
gpg: ATTENZIONE: questa chiave non è certificata con una firma fidata!
gpg:          Non ci sono indicazioni che la firma appartenga al proprietario.
Impronta digitale della chiave primaria: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
    Impronta digitale della subchiave: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/local/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

Upgrading the RVM installation in /usr/local/rvm/
Upgrade of RVM in /usr/local/rvm/ is complete.

Upgrade Notes:

  * No new notes to display.

RVM reloaded!


rvm install 2.3.4
ruby-2.3.4 - #removing src/ruby-2.3.4..
Searching for binary rubies, this might take some time.
No binary rubies available for: kali/kali-rolling/x86_64/ruby-2.3.4.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Installing Ruby from source to: /usr/local/rvm/rubies/ruby-2.3.4, this may take a while depending on your cpu(s)...
ruby-2.3.4 - #downloading ruby-2.3.4, this may take a while depending on your connection...
ruby-2.3.4 - #extracting ruby-2.3.4 to /usr/local/rvm/src/ruby-2.3.4....
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/ruby_2_3_gcc7.patch.
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/2.3.4/fix_rb_thread_fd_close.patch.
ruby-2.3.4 - #applying patch /usr/local/rvm/patches/ruby/2.3.4/random_c_using_NR_prefix.patch.
ruby-2.3.4 - #configuring......................................................-
ruby-2.3.4 - #post-configuration..
ruby-2.3.4 - #compiling........................................................-
Error running '__rvm_make -j4',
please read /usr/local/rvm/log/1507062529_ruby-2.3.4/make.log
There has been an error while running make. Halting the installation.

dpkg-query -l | grep openssl
ii  libevent-openssl-2.1-6:amd64              2.1.8-stable-4                       amd64        Asynchronous event notification library (openssl)
ii  openssl                                   1.1.0f-5                             amd64        Secure Sockets Layer toolkit - cryptographic utility
ii  perl-openssl-defaults:amd64               3                                    amd64        version compatibility baseline for Perl OpenSSL packages
ii  python-openssl                            16.2.0-1                             all          Python 2 wrapper around the OpenSSL library



same

**Comment by ifmacedo** [comment]
It is getting error till now (2020)!!!

**Comment by pkuczynski** [comment]
@ifmacedo maybe its missing some dependencies. Would you like to debug/research it and propose the changes?
