### ISSUE TITLE
? help with rvm

### ISSUE THREAD

**Issue by oussamagtp** [rvm/rvm#4195]
gtp@gtp-HP-EliteBook-8440p:~$ rvm --default use ruby-2.4.1@metasploit-framework
Gemset 'metasploit-framework' does not exist, 'rvm ruby-2.4.1 do rvm gemset create metasploit-framework' first, or append '--create'.

**Comment by pkuczynski** [comment]
Run `rvm --default use ruby-2.4.1` instead.
