### ISSUE TITLE
Error running '__rvm_make -j8

### ISSUE THREAD

**Issue by kristiyandobrev** [rvm/rvm#4197]
## Description

Trying to install `rvm 2.4.2` but receiving `Error running '__rvm_make -j8'`

## Steps to reproduce

`rvm install "ruby-2.4.2"`

## Expected behavior

Version `2.4.2` is installed

## Actual behavior

[output](https://gist.github.com/kristiyandobrev/f55978220d4838342ff112307ecde1bb)
[make.log](https://gist.github.com/kristiyandobrev/238727709627c4f4970f476055d2d898)

## Environment info

- MacOS High Sierra 10.13.1 Beta

**Comment by pkuczynski** [comment]
I would also need to see content of `/Users/myuser/.rvm/log/1507097325_ruby-2.4.2/make.log`. Could u please gist it?

**Comment by kristiyandobrev** [comment]
I have managed to solve the issue. The problem was that I had several XCode versions installed on my Mac by looking into this line in the `make.log`: `/bin/sh: /Applications/Xcode: No such file or directory
`.
