### ISSUE TITLE
Install of 2.4.2 fails on MacOS Sierra -- zlib error?

### ISSUE THREAD

**Issue by gwijthoff** [rvm/rvm#4206]
## Description

I'm installing Ruby 2.4.2 using RVM, and receive the following error messages during an install using `$ rvm install 2.4.2`:

    Making gemset ruby-2.4.2 pristine - please wait

    'command gem pristine --extensions bigdecimal --version 1.3.0 gem-wrappers --version 1.3.2 io-console --version 0.4.6 json --version 2.0.4 openssl --version 2.0.5 psych --version 2.2.2' failed, you need to fix this gems manually.
    Error running '__rvm_with ruby-2.4.2 gemset_pristine',
    please read /Users/myname/.rvm/log/1507820191_ruby-2.4.2/gemset.pristine-ruby-2.4.2.log
    
    Making gemset ruby-2.4.2@global pristine - please wait
    
    'command gem pristine --extensions bigdecimal --version 1.3.0 io-console --version 0.4.6 json --version 2.0.4 openssl --version 2.0.5 psych --version 2.2.2' failed, you need to fix this gems manually.
    Error running '__rvm_with ruby-2.4.2@global gemset_pristine',
    please read /Users/myname/.rvm/log/1507820191_ruby-2.4.2/gemset.pristine-ruby-2.4.2@global.log

I'm not sure, but the relevant parts of the referenced [error log](https://gist.github.com/gwijthoff/8a3e485537787604ac8d1bd4991ea889) seem to point to zlib:

```
bigdecimal-1.3.0 +gemset_pristine:20> gem pristine --extensions bigdecimal --version 1.3.0
ERROR:  Loading command: pristine (LoadError)
    cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
+gemset_pristine:21> _failed+=( 'bigdecimal --version 1.3.0' )  
```

I receive a similar error when running `gem install bundler` that also references zlib, even though `zlib.h` is where it's supposed to be in `/usr/include/`:

```
Error loading RubyGems plugin "/Users/grantwythoff/.rvm/gems/ruby-2.4.2/gems/gem-wrappers-1.3.2/lib/rubygems_plugin.rb": cannot load such file -- zlib (LoadError)
ERROR:  Loading command: install (LoadError)
	cannot load such file -- zlib
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

## Environment info 

```
ruby-2.4.2:

  system:
    uname:        "Darwin GrantsMBP.home 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote_path:  "osx/10.12/x86_64"

  rvm:
    version:      "1.29.3 (latest)"
    updated:      "4 days 2 hours 33 minutes 43 seconds ago"
    path:         "/Users/myname/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.2p198"
    date:         "2017-09-14"
    platform:     "x86_64-darwin16"
    patchlevel:   "2017-09-14 revision 59899"
    full_version: "ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]"

  homes:
    gem:          "/Users/myname/.rvm/gems/ruby-2.4.2"
    ruby:         "/Users/myname/.rvm/rubies/ruby-2.4.2"

  binaries:
    ruby:         "/Users/myname/.rvm/rubies/ruby-2.4.2/bin/ruby"
    irb:          "/Users/myname/.rvm/rubies/ruby-2.4.2/bin/irb"
    gem:          "/Users/myname/.rvm/rubies/ruby-2.4.2/bin/gem"
    rake:         "/Users/myname/.rvm/rubies/ruby-2.4.2/bin/rake"

  environment:
    PATH:         "/Users/myname/.rvm/gems/ruby-2.4.2/bin:/Users/myname/.rvm/gems/ruby-2.4.2@global/bin:/Users/myname/.rvm/rubies/ruby-2.4.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/opt/X11/bin:/Library/TeX/texbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/texbin:/Users/myname/.rvm/bin"
    GEM_HOME:     "/Users/myname/.rvm/gems/ruby-2.4.2"
    GEM_PATH:     "/Users/myname/.rvm/gems/ruby-2.4.2:/Users/myname/.rvm/gems/ruby-2.4.2@global"
    MY_RUBY_HOME: "/Users/myname/.rvm/rubies/ruby-2.4.2"
    IRBRC:        "/Users/myname/.rvm/rubies/ruby-2.4.2/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by gwijthoff** [comment]
Found a fix as referenced in #3389 that involves installing zlib using brew and then re-installing ruby while pointing to that zlib directory. As someone in that thread pointed out, this shouldn't be necessary. Not sure why the problem arose.

```
$ brew install zlib
$ rvm remove 2.4.2
$ rvm install 2.4.2 —with-zlib-dir=/usr/local/Cellar/zlib/1.2.11
```

**Comment by cijacob** [comment]
Hi I ve the same error and I tried your solution, but doesn t work. I ve search and try all the problem persist. => 'command gem pristine --extensions bigdecimal --version 1.3.0 io-console --version 0.4.6 json --version 2.0.4 openssl --version 2.0.5 psych --version 2.2.2' failed, you need to fix this gems manually.
. I can t install rails for problem about zlib but it is install: 
my ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]. I can t understand, please can you help me? 
Thanks a lot

**Comment by siulcode** [comment]
@gwijthoff tip works for me. 

`$ gem install rake
Fetching: rake-12.3.1.gem (100%)
Successfully installed rake-12.3.1
Parsing documentation for rake-12.3.1
Installing ri documentation for rake-12.3.1
Done installing documentation for rake after 0 seconds
1 gem installed`

**Comment by rodrigobdz** [comment]
A more generic way:

```sh
brew install zlib
rvm reinstall 2.4.2 --with-openssl-dir=$(brew --prefix openssl) --with-zlib-dir=$(brew --prefix zlib)
```
