### ISSUE TITLE
RVM ignores hash bang in ruby shell scripts

### ISSUE THREAD

**Issue by duffyjp** [rvm/rvm#4207]
## Description

RVM ignores hash bang in ruby shell scripts.

## Steps to reproduce

Assuming the following script:

whichruby.rb
```ruby
#!/usr/bin/ruby

puts `ruby -v`
puts `which ruby`
```

Where the RVM default ruby is NOT the system ruby.
```bash
$ rvm list

rvm rubies

   ruby-2.2.3 [ x86_64 ]
=* ruby-2.3.1 [ x86_64 ]
   ruby-2.4.0 [ x86_64 ]
   ruby-2.4.1 [ x86_64 ]
```

Executing the script uses the RVM default ruby.

```bash
$ ./whichruby.rb 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
/Users/duffyjp/.rvm/rubies/ruby-2.3.1/bin/ruby
```

Even when you're REALLY explicit.
```bash
$ /usr/bin/ruby whichruby.rb 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
/Users/duffyjp/.rvm/rubies/ruby-2.3.1/bin/ruby
```

Despite what you would assume:
```
$ /usr/bin/ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
```

Okay, that may be by design and there is a workaround:
```
time rvm system do ruby whichruby.rb 
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
/usr/bin/ruby

real	0m0.556s
user	0m0.262s
sys	0m0.258s
```

Except that's almost a half second to wait vs using whatever is current.
```
time ruby whichruby.rb 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
/Users/jpd800/.rvm/rubies/ruby-2.3.1/bin/ruby

real	0m0.121s
user	0m0.077s
sys	0m0.029s
```

## Expected behavior

`/usr/bin/ruby -v` and `/usr/bin/ruby whichruby.rb` should both report the same thing (the system ruby found at /usr/bin/ruby).

## Actual behavior

Despite full path being given, RVM is not bypassed.  Workaround is slow and not portable.  I want the same ruby script to work on systems without RVM.

## Environment info

```
🌶  scripts 13:47$ rvm info

ruby-2.3.1:

  system:
    uname:        "Darwin jalapeno 17.0.0 Darwin Kernel Version 17.0.0: Thu Aug 24 21:48:19 PDT 2017; root:xnu-4570.1.46~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "13 minutes 30 seconds ago"
    path:         "/Users/duffyjp/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.3.1p112"
    date:         "2016-04-26"
    platform:     "x86_64-darwin16"
    patchlevel:   "2016-04-26 revision 54768"
    full_version: "ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]"

  homes:
    gem:          "/Users/duffyjp/.rvm/gems/ruby-2.3.1"
    ruby:         "/Users/duffyjp/.rvm/rubies/ruby-2.3.1"

  binaries:
    ruby:         "/Users/duffyjp/.rvm/rubies/ruby-2.3.1/bin/ruby"
    irb:          "/Users/duffyjp/.rvm/rubies/ruby-2.3.1/bin/irb"
    gem:          "/Users/duffyjp/.rvm/rubies/ruby-2.3.1/bin/gem"
    rake:         "/Users/duffyjp/.rvm/gems/ruby-2.3.1/bin/rake"

  environment:
    PATH:         "/Users/duffyjp/.rvm/gems/ruby-2.3.1/bin:/Users/duffyjp/.rvm/gems/ruby-2.3.1@global/bin:/Users/duffyjp/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/duffyjp/.rvm/bin"
    GEM_HOME:     "/Users/duffyjp/.rvm/gems/ruby-2.3.1"
    GEM_PATH:     "/Users/duffyjp/.rvm/gems/ruby-2.3.1:/Users/duffyjp/.rvm/gems/ruby-2.3.1@global"
    MY_RUBY_HOME: "/Users/duffyjp/.rvm/rubies/ruby-2.3.1"
    IRBRC:        "/Users/duffyjp/.rvm/rubies/ruby-2.3.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by duffyjp** [comment]
It was pointed out to me that my `whichruby.rb` test is flawed, as it's shelling out to ruby which is using the PATH as usual, hence getting the RVM ruby.

It should be 
```
puts RUBY_VERSION
```

This indeed returns 2.3.3 which is my system ruby.

All is not totally well however, as I'm still getting STDERR output from my RVM 2.3.1 ruby:

```bash
🌶  scripts 10:33$ rvm use system
Now using system ruby.

🌶  scripts 10:33$ ./whichruby.rb 
2.3.3
/usr/bin/ruby

🌶  scripts 10:33$ rvm use 2.3.1
Using /Users/duffyjp/.rvm/gems/ruby-2.3.1

🌶  scripts 10:33$ ./whichruby.rb 
Ignoring capybara-webkit-1.14.0 because its extensions are not built.  Try: gem pristine capybara-webkit --version 1.14.0
2.3.3
/Users/duffyjp/.rvm/rubies/ruby-2.3.1/bin/ruby
```

**Comment by BrianHawley** [comment]
`rvm use` also sets the GEM_HOME and GEM_PATH environment variables, which are used by ruby, and which aren't affected by your shebang line. Since the extensions of the gems in GEM_PATH aren't installed for the system ruby, they won't load properly.

**Comment by pkuczynski** [comment]
This is nothing to do with RVM. All we do is modify the path to load designed rvm version. As you correctly noted shell will be using PATH to find ruby. Solution for your problem would be to run ‘rvm use system’ as a first command in your script. 

Does this solve your problem?

**Comment by duffyjp** [comment]
Hi @pkuczynski,
I need this script to be portable to any system with or without rvm.  So `rvm use system` is not a practical solution in my case.

Your comment about the PATH modification was enlightening however.  I guess I never realized that despite passing the absolute path, the ruby executable used would still be the first one found in PATH.  That doesn't make any sense, but hey.  Tacking the path I want on the front again seems to do the trick.

whichruby.rb
```ruby
#!/usr/bin/ruby
ENV['PATH'] = '/usr/bin:' + ENV['PATH']

puts `ruby -v`
puts `which ruby`
```

```
# Ubuntu
$ ./whichruby.rb 
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
/usr/bin/ruby
```

I still have the problem where my script is using the GEM_PATH for the current rvm ruby and therefore spitting out errors for certain gems.


```
# Mac
$ ./whichruby.rb 
Ignoring capybara-webkit-1.14.0 because its extensions are not built.  Try: gem pristine capybara-webkit --version 1.14.0
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
/usr/bin/ruby
```

The script I'm actually using is a ruby-based `ls` replacement.  It color codes files based on git status.   This is a convenient situation as I already need an alias in my .bash_profile.  Dropping stderr sweeps the errors under the rug.

.bash_profile
```bash
alias ls='~/scripts/lsg.rb 2>/dev/null'
```

| Before | After |
|--------|------|
<img width="724" alt="screen shot 2017-12-20 at 9 29 24 am" src="https://user-images.githubusercontent.com/382216/34214586-88bfc4f2-e568-11e7-885a-948030a8d48b.png"> | <img width="635" alt="screen shot 2017-12-20 at 9 29 42 am" src="https://user-images.githubusercontent.com/382216/34214589-8bdd1022-e568-11e7-9da5-63ee9beef9a4.png">

Any idea how to get rid of those `Ignoring capybara-webkit-1.14.0 because its extensions are not built.` type messages properly?
