### ISSUE TITLE
OSx Sierra 10.13 `Error running '__rvm_make -j 1'`

### ISSUE THREAD

**Issue by chase1745** [rvm/rvm#4219]
## Description

I am trying to install Ruby 2.4.1 on macOS High Sierra 10.13, after changing the name of my home folder (big mistake apparently) and having issues all across the board, so I tried to basically start over and uninstall rvm and Ruby and now am having issues reinstalling.

## Steps to reproduce

`rvm install 2.4.1`
and am getting the error:

    ruby-2.3.1 - #compiling........
    Error running '__rvm_make -j 1',
    please read /Users/chase/.rvm/log/1509422611_ruby-2.3.1/make.log
    There has been an error while running make. Halting the installation.

##  Behavior

* [command](https://gist.github.com/chase1745/3bddb725237f7d5af0c355dad3094b37)
* [config.log](https://gist.github.com/chase1745/4aaa837fa7f641c5d2bb3f6cb2a20c8f) - only for issues with `install`
* [make.log](https://gist.github.com/chase1745/11fe0352d1e516ee99614778e6878132.) - only for issues with `install`

**Comment by pkuczynski** [comment]
Try `xcode-select --install` and then re-run rvm command. Let me know if that helped?

**Comment by chase1745** [comment]
So the issue did end up being with xcode. I tried running`xcode-select --install` and would get `xcode-select: error: command line tools are already installed, use "Software Update" to install updates`, but apparently there was an update available that I wasn't notified of and had to go to the app store and update xcode and then re run `xcode-select --install` and it worked.

**Comment by pkuczynski** [comment]
I am glad I could help :)

**Comment by martinverdejo** [comment]
I'm having the same problem installing 2.3.4. I have `xcode-select --install` and I don't see (yet) any software updates on the app store.

[make.log](https://github.com/rvm/rvm/files/1676757/make.log)
