### ISSUE TITLE
New JRuby download URLs 9.1.14.0+

### ISSUE THREAD

**Issue by headius** [rvm/rvm#4223]
JRuby's download URLs are changing! We will soon stop hosting our release artifacts on S3 due, and instead would prefer that all downloads come from Maven servers.

To that end, we have started pushing additional checksums with our "jruby-dist" artifact so these download URLs can be considered canonical.

This change affects JRuby 9.1.14.0 and higher. Previous releases will remain on S3 until it goes away.

There are three changes needed in RVM:

The base URL for the binary release tarball changes to `https://repo1.maven.org/maven2/org/jruby/jruby-dist/<version>/jruby-dist-<version>-bin.tar.gz`

The base URL for the source release tarball changes to `https://repo1.maven.org/maven2/org/jruby/jruby-dist/<version>/jruby-dist-<version>-src.tar.gz`

And as you see here, the structure of the tarball file changed from `jruby-bin-<version>.tar.gz` to `jruby-dist-<version>-bin.tar.gz` due to Maven requirements.

We do not know when our S3 will go away, so the sooner you can update how you fetch these files, the better!

**Comment by headius** [comment]
cc @enebo

**Comment by headius** [comment]
Note we are still pushing the S3 artifacts for as long as we have the bucket, but switching sooner would be best.

**Comment by headius** [comment]
Link jruby/jruby#4829

**Comment by pkuczynski** [comment]
Got it! I am on it...

**Comment by pkuczynski** [comment]
@headius am I correct, that all the md5 hashes changed after the move to maven? For example:

https://repo1.maven.org/maven2/org/jruby/jruby-dist/1.7.12/jruby-dist-1.7.12-bin.tar.gz.asc.md5 - `0c5f4dba3539b4957919b64f3b66c92c`

and in RVM:

`jruby-bin-1.7.12.tar.gz=2073aa6dfc7c701ef7c3d3143d181582`

**Comment by enebo** [comment]
@pkuczynski I cannot remember but I think there was only one (it is possible there was a second it was a little chaotic last month dealing with S3 outtage).  This PR is really asking for a new URL from anything released from 9.1.14.0 onwards but if you wanted to extend things back I  think you can back to 1.7.3 (I think internally something changed in our jruby-dist packaging around that time)? with the exception of that bad fingerprint.

**Comment by ioquatix** [comment]
This is breaking all JRuby builds on travis that use rvm.

**Comment by headius** [comment]
I've pushed a PR that I think switches RVM over to the new URLs.
