### ISSUE TITLE
`rvm_remote_server_url3` is ignored when attempting to install a binary package

### ISSUE THREAD

**Issue by JoeNyland** [rvm/rvm#4229]
## Description

`rvm_remote_server_url3` is ignored when attempting to install a binary package.

## Steps to reproduce

 1. Verify that https://myserver.com/ruby/binaries/osx/10.13/x86_64/ruby-2.4.2.tar.bz2 exists
 1. `echo "rvm_remote_server_url3=https://myserver.com/ruby/binaries" >> ~/.rvm/user/db`
 1. `rvm install --binary 2.4.2`

## Expected behavior

RVM installs the binary package from my server.

## Actual behavior

RVM does not attempt to check my server for binary packages.
https://gist.github.com/JoeNyland/7a53b361ef8db3a6dd46a741cfbd8ab4

## Environment info

```
system:

  system:
    uname:        "Darwin Joes-MBP 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/usr/local/bin/bash => GNU bash, version 4.4.12(1)-release (x86_64-apple-darwin16.3.0)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "24 minutes 47 seconds ago"
    path:         "/Users/joenyland/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/joenyland/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by JoeNyland** [comment]
I feel like I'm missing something obvious here, but I can't see it. Using https://github.com/rvm/rvm/blob/master/help/prepare.md#hosting-binaries-build-server as reference, this should "just work" 😕

**Comment by pkuczynski** [comment]
I am working in this area as part of #4223. Stay tuned...

**Comment by JoeNyland** [comment]
I no longer host my own rubies, so I'm not hitting this any more. Given how long it's been open, I'm guessing it's no longer an issue...
