### ISSUE TITLE
Ruby install fails centOS 7

### ISSUE THREAD

**Issue by cmaurice504** [rvm/rvm#4239]
## Description

Can't install Ruby for multiuser using rvm install command it fails when trying to install the required packages. I get the message "Requirements Installation failed with status: 1. "

## Steps to reproduce

 1. rvm install 2.4.2

## Expected behavior

I expected Ruby to install successfully.

## Actual behavior

* [command](https://gist.github.com/cmaurice504/99cbc6c7e5890ada82f2da5d119f23c7#file-gistfile1-txt)
* [config.log](https://gist.github.com/cmaurice504/cd17725814719797cba379e7047ffb20#file-gistfile1-txt) 

**Debug mode**:
* [command]
* [config.log]
* [make.log]

## Environment info

system:

  system:
    uname:        "Linux tulib1d01 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 13 10:46:25 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "CentOS"
    version:      "7"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "centos/7/x86_64"

  rvm:
    version:      "1.29.3 (latest)"
    updated:      "1 hour 46 minutes 14 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         ""

  environment:
    PATH:         "/home/cmaurice/.composer/vendor/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/rvm/bin:/home/cmaurice/.rvm/bin:/home/cmaurice/.local/bin:/home/cmaurice/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by pkuczynski** [comment]
Your issue is clearly listed here:

```
Loaded plugins: product-id, replace, search-disabled-repos, subscription-manager
This system is registered with an entitlement server, but is not receiving updates. You can use subscription-manager to assign subscriptions.
No package patch available.
No package bison available.
No package bzip2 available.
No package gcc-c++ available.
No package libffi-devel available.
No package libtool available.
No package patch available.
No package readline-devel available.
No package sqlite-devel available.
No package zlib-devel available.
No package glibc-headers available.
No package glibc-devel available.
No package libyaml-devel available.
No package openssl-devel available.
```

Does your CentOS installation enable installing new software? It seems it does not...

**Comment by pkuczynski** [comment]
Did you tried solution described here: https://access.redhat.com/solutions/253273

**Comment by mpapis** [comment]
Closing as there was no feedback in 2 weeks, feel free to reopen when you can provide the requested information.

**Comment by zw963** [comment]
those error feedback is very easy understood，i guess when first
run，Internet is not connect.

2018年2月7日 上午5:26，"Michal Papis" <notifications@github.com>写道：

Closing as there was no feedback in 2 weeks, feel free to reopen when you
can provide the requested information.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rvm/rvm/issues/4239#issuecomment-363569966>, or mute
the thread
