### ISSUE TITLE
uninstall with ubuntu 16.04

### ISSUE THREAD

**Issue by mikevitz** [rvm/rvm#4245]
I install the ppa version of ubuntu as per the instructions for repository install.  

When I run rvm install I get 
$ rvm install ruby-2.4.2
No command 'rvm' found, but there are 26 similar ones
rvm: command not found

I tried many methods to get this to work, including adding a sourcing script to my bashrc file, checking permissions are present, and more.  Nothing works.  I decide to uninstall and try again from scratch:

I try with
$ rvm implode
No command 'rvm' found, but there are 26 similar ones
rvm: command not found

I try with apt:
$ sudo apt-get remove rvm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  rvm
0 upgraded, 0 newly installed, 1 to remove and 128 not upgraded.
After this operation, 4,209 kB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 221118 files and directories currently installed.)
Removing rvm (1.29.3-1) ...
bash: rvm: command not found
dpkg: error processing package rvm (--remove):
 subprocess installed pre-removal script returned error exit status 127
Errors were encountered while processing:
 rvm
E: Sub-process /usr/bin/dpkg returned an error code (1)

How can I remove this software?

Many thanks.

**Comment by mikevitz** [comment]
I was able to solve with anew command I had not known before!  apt has a reinstall feature
I used

sudo apt-get install --reinstall rvm
then source and things. Then
rvm implode

Issue can be closed after five minutes!

**Comment by raelgc** [comment]
I'm glad it worked. Just a friendly reminder to logout/login again after install.
