### ISSUE TITLE
gpg: WARNING: This key is not certified with a trusted signature

### ISSUE THREAD

**Issue by ddon** [rvm/rvm#4250]
## Description

Installed RVM for the first time on MacOS using instruction from rvm.io home page, and during installation got following WARNING:

gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.

## Steps to reproduce

$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 
$ curl -sSL https://get.rvm.io | bash -s stable

## Expected behavior

Was not expecting to see a warning  "This key is not certified with a trusted signature"

## Actual behavior

$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: directory '/Users/ddon/.gnupg' created
gpg: keybox '/Users/ddon/.gnupg/pubring.kbx' created
gpg: /Users/ddon/.gnupg/trustdb.gpg: trustdb created
gpg: key 105BD0E739499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: key 3804BB82D39DC0E3: 75 signatures not checked due to missing keys
gpg: key 3804BB82D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 2

$ curl -sSL https://get.rvm.io | bash -s stable
Downloading https://github.com/rvm/rvm/archive/1.29.3.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.3/1.29.3.tar.gz.asc
gpg: Signature made Sun Sep 10 23:59:21 2017 EEST
gpg:                using RSA key E206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/Users/ddon/.rvm/archives/rvm-1.29.3.tgz'

Installing RVM to /Users/ddon/.rvm/
    Adding rvm PATH line to /Users/ddon/.profile /Users/ddon/.mkshrc /Users/ddon/.bashrc /Users/ddon/.zshrc.
    Adding rvm loading line to /Users/ddon/.profile /Users/ddon/.bash_profile /Users/ddon/.zlogin.
Installation of RVM in /Users/ddon/.rvm/ is almost complete:

## Environment info

$ rvm info

system:

  system:
    uname:        "Darwin Dmitri-Dons-MacMini.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.3 (latest)"
    updated:      "8 minutes 17 seconds ago"
    path:         "/Users/ddon/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/local/bin/ruby"
    irb:          "/usr/local/bin/irb"
    gem:          "/usr/local/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/usr/local/sbin:/usr/local/Cellar/php71/7.1.11_22/bin:~/Library/Android/sdk/tools:~/Library/Android/sdk/platform-tools:/usr/local/mysql/bin:/Users/ddon/.rvm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by mpapis** [comment]
Please read https://github.com/rvm/rvm/blob/master/docs/gpg.md especially point 3 in `For users`.

@pkuczynski should we add this to our instruction on rvm.io?

**Comment by mountbee** [comment]
bit:~ bit$ rvm install ruby-2.5.1
Found old RVM 1.28.0 - updating.
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/bit/.rvm/archives/rvm-installer.asc
gpg: Signature made Sun Apr  1 04:47:44 2018 WIB using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [ultimate]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [ultimate]
gpg:                 aka "[jpeg image of size 5015]" [ultimate]
GPG verified '/Users/bit/.rvm/archives/rvm-installer'
Unknown option: n
Unknown option: 1
Usage: head [-options] <url>...
    -m <method>   use method for the request (default is 'HEAD')
    -f            make request even if head believes method is illegal
    -b <base>     Use the specified URL as base
    -t <timeout>  Set timeout value
    -i <time>     Set the If-Modified-Since header on the request
    -c <conttype> use this content-type for POST, PUT, CHECKIN
    -a            Use text mode for content I/O
    -p <proxyurl> use this as a proxy
    -P            don't load proxy settings from environment
    -H <header>   send this HTTP header (you can specify several)

    -u            Display method and URL before any response
    -U            Display request headers (implies -u)
    -s            Display response status code
    -S            Display response status chain
    -e            Display response headers
    -d            Do not display content
    -o <format>   Process HTML content in various ways

    -v            Show program version
    -h            Print this message

    -x            Extra debugging output
BASH 3.2.25 required (you have 4.4.23(1)-release)
Could not update RVM, get some help at #rvm IRC channel at freenode servers.
bit:~ bit$ echo $BASH_VERSION
4.4.23(1)-release


I got this when trying to update

**Comment by JamesHagerman** [comment]
Perhaps RVM could consider updating the installation steps to point users to a working keyserver. Perhaps https://pgp.mit.edu/? The certificate on https://keys.gnupg.net/ is invalid and that the HTTP version of the site throws a 502 when you search for a key.

That plus seeing scary notifications such as `no ultimately trusted keys found` just makes things worse.

Anyway, Step 3 on [https://github.com/rvm/rvm/blob/master/docs/gpg.md](https://github.com/rvm/rvm/blob/master/docs/gpg.md) asks users to trust the key associated with mpapis@gmail.com. Please do add that step to rvm.io's "more secure" instructions. Or just point people to the `gpg.md` directly. Or both.

Just out of curiosity, what is the reasoning behind asking users to use keys from both mpapis@gmail.com and piotr.kuczynski@gmail.com?

**Comment by JamesHagerman** [comment]
Oops, Maybe I should have posted that under https://github.com/rvm/rvm/issues/4449 instead...

**Comment by pkuczynski** [comment]
@JamesHagerman changes have been applied to rvm.io, as you suggested.

**Comment by lmakarov** [comment]
For anyone else trying to get rid of this issue - the instructions to trust the keys are here:
https://rvm.io/rvm/security

In a nutshell (suitable for use in a Dockerfile):

```
# Import and trust rvm keys
# mpapis@gmail.com
curl -sSL https://rvm.io/mpapis.asc | gpg --batch --import -; \
echo 409B6B1796C275462A1703113804BB82D39DC0E3:6: | gpg --batch --import-ownertrust; \
# piotr.kuczynski@gmail.com
curl -sSL https://rvm.io/pkuczynski.asc | gpg --batch --import -; \
echo 7D2BAF1CF37B13E2069D6956105BD0E739499BDB:6: | gpg --batch --import-ownertrust
```

Then, install rvm as usual:

```
$ curl -sSL https://get.rvm.io | bash -s stable
Downloading https://github.com/rvm/rvm/archive/1.29.7.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.7/1.29.7.tar.gz.asc
gpg: Signature made Thu 03 Jan 2019 10:01:48 PM UTC
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [ultimate]
GPG verified '/home/docker/.rvm/archives/rvm-1.29.7.tgz'
...
```

No more scary warnings from `gpg` 👍

**Comment by kyb3rfett** [comment]
This occurs because your PGP system does not trust the key to do so, run: 
```bash
gpg --edit-key <key> trust
````
