### ISSUE TITLE
Ruby 2.3.5 fails to install rubygems-bundler Mac High Sierra

### ISSUE THREAD

**Issue by duffyjp** [rvm/rvm#4251]
## Description

rvm install 2.3.5 has an error installing rubygems-bundler, as a result gem isn't working.

```
ruby-2.3.5 - #importing gemset /Users/oxm327/.rvm/gemsets/global.gems.........................there was an error installing gem rubygems-bundler
....................
```

## Steps to reproduce

Mac OS High Sierra

```bash
rvm get master
rvm install 2.3.5
```

> rvm get master
> Downloading https://get.rvm.io
> Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
> Verifying /Users/oxm327/.rvm/archives/rvm-installer.asc
> gpg: Signature made Sat Sep  9 14:49:18 2017 CDT
> gpg:                using RSA key E206C29FBF04FF17
> gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
> gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
> gpg:                 aka "[jpeg image of size 5015]" [unknown]
> gpg: WARNING: This key is not certified with a trusted signature!
> gpg:          There is no indication that the signature belongs to the owner.
> Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
>      Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
> GPG verified '/Users/oxm327/.rvm/archives/rvm-installer'
> Downloading https://github.com/rvm/rvm/archive/master.tar.gz
> Upgrading the RVM installation in /Users/oxm327/.rvm/
>     RVM PATH line found in /Users/oxm327/.mkshrc /Users/oxm327/.profile /Users/oxm327/.bashrc /Users/oxm327/.zshrc.
>     RVM sourcing line found in /Users/oxm327/.profile /Users/oxm327/.bash_profile /Users/oxm327/.zlogin.
> Upgrade of RVM in /Users/oxm327/.rvm/ is complete.
> 
> Upgrade Notes:
> 
>   * RVM 1.30 simplifies behavior of 'rvm wrapper' subcommand
> 
> 
> RVM reloaded!
> 
> MacBook:~ oxm327$ rvm install 2.3.5
> Searching for binary rubies, this might take some time.
> No binary rubies available for: osx/10.13/x86_64/ruby-2.3.5.
> Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
> Checking requirements for osx.
> Certificates bundle '/usr/local/etc/openssl/cert.pem' is already up to date.
> Requirements installation successful.
> Installing Ruby from source to: /Users/oxm327/.rvm/rubies/ruby-2.3.5, this may take a while depending on your cpu(s)...
> ruby-2.3.5 - #downloading ruby-2.3.5, this may take a while depending on your connection...
> ruby-2.3.5 - #extracting ruby-2.3.5 to /Users/oxm327/.rvm/src/ruby-2.3.5....
> ruby-2.3.5 - #configuring...........................................................
> ruby-2.3.5 - #post-configuration.
> ruby-2.3.5 - #compiling...............................................................
> ruby-2.3.5 - #installing.........
> ruby-2.3.5 - #making binaries executable..
> ruby-2.3.5 - #downloading rubygems-2.6.14
> ruby-2.3.5 - #extracting rubygems-2.6.14.....
> ruby-2.3.5 - #removing old rubygems........
> $LANG was empty, setting up LANG=en_US.US-ASCII, if it fails again try setting LANG to something sane and try again.
> ruby-2.3.5 - #installing rubygems-2.6.14...........................
> ruby-2.3.5 - #gemset created /Users/oxm327/.rvm/gems/ruby-2.3.5@global
> ruby-2.3.5 - #importing gemset /Users/oxm327/.rvm/gemsets/global.gems.........................**there was an error installing gem rubygems-bundler**
> ....................
> ruby-2.3.5 - #generating global wrappers.......
> ruby-2.3.5 - #gemset created /Users/oxm327/.rvm/gems/ruby-2.3.5
> ruby-2.3.5 - #importing gemsetfile /Users/oxm327/.rvm/gemsets/default.gems evaluated to empty gem list
> ruby-2.3.5 - #generating default wrappers.......
> ruby-2.3.5 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
> Install of ruby-2.3.5 - #complete 
> Ruby was built without documentation, to build it run: rvm docs generate-ri

## Environment info

$ rvm info           

> ruby-2.3.5:
> 
>   system:
>     uname:        "Darwin MacBook.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64"
>     name:         "OSX"
>     version:      "10.13"
>     architecture: "x86_64"
>     bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
>     zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
>     remote_path:  "osx/10.13/x86_64"
> 
>   rvm:
>     version:      "1.29.3 (master)"
>     updated:      "11 minutes 33 seconds ago"
>     path:         "/Users/oxm327/.rvm"
>     autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."
> 
>   ruby:
>     interpreter:  "ruby"
>     version:      "2.3.5p376"
>     date:         "2017-09-14"
>     platform:     "x86_64-darwin17"
>     patchlevel:   "2017-09-14 revision 59905"
>     full_version: "ruby 2.3.5p376 (2017-09-14 revision 59905) [x86_64-darwin17]"
> 
>   homes:
>     gem:          "/Users/oxm327/.rvm/gems/ruby-2.3.5"
>     ruby:         "/Users/oxm327/.rvm/rubies/ruby-2.3.5"
> 
>   binaries:
>     ruby:         "/Users/oxm327/.rvm/rubies/ruby-2.3.5/bin/ruby"
>     irb:          "/Users/oxm327/.rvm/rubies/ruby-2.3.5/bin/irb"
>     gem:          "/Users/oxm327/.rvm/rubies/ruby-2.3.5/bin/gem"
>     rake:         "/Users/oxm327/.rvm/rubies/ruby-2.3.5/bin/rake"
> 
>   environment:
>     PATH:         "/Users/oxm327/.rvm/gems/ruby-2.3.5/bin:/Users/oxm327/.rvm/gems/ruby-2.3.5@global/bin:/Users/oxm327/.rvm/rubies/ruby-2.3.5/bin:/Users/oxm327/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
>     GEM_HOME:     "/Users/oxm327/.rvm/gems/ruby-2.3.5"
>     GEM_PATH:     "/Users/oxm327/.rvm/gems/ruby-2.3.5:/Users/oxm327/.rvm/gems/ruby-2.3.5@global"
>     MY_RUBY_HOME: "/Users/oxm327/.rvm/rubies/ruby-2.3.5"
>     IRBRC:        "/Users/oxm327/.rvm/rubies/ruby-2.3.5/.irbrc"
>     RUBYOPT:      ""
>     gemset:       ""
> 
> 
>

**Comment by duffyjp** [comment]
Exact procedure Monday morning worked as expected.

**Comment by pkuczynski** [comment]
Could you please check if #4287 fixed the issue? It should. Check with `rvm get master`
