### ISSUE TITLE
rvm installation on Ubuntu for managing different rails applications

### ISSUE THREAD

**Issue by knzudgt** [rvm/rvm#4252]
I need to install `rvm` on a new Ubuntu machine.
I would use `rvm` to switch to different ruby versions and gemsets required by different Ruby on Rails applications.

When a couple of years ago I installed rvm on my current Ubuntu machine, I did it with the following command:

$ \curl -L https://get.rvm.io | bash -s stable --rails --autolibs=enable

I notice now that the rvm website suggests to Ubuntu users to install rvm using the dedicated Ubuntu package.
However the [documentation at RailsApp](http://www.google.com/url?q=http%3A%2F%2Frailsapps.github.io%2Finstallrubyonrails-ubuntu.html&sa=D&sntz=1&usg=AFQjCNHETNwpDKde5yEw_W0g2tppzPTXXw), where I initially found the advice of installing rvm, does not consider this option but instead uses the above curl command, as if it were a better choice. I wonder which one of the two options (curl command or PPA and package) is preferable, and why.

Also in 2015 there was documentation like the above RailsApp page that suggested to use the curl command with the `--rails` option instead of the `--ruby` option.
This suggestion was removed in the RailsApp documentation, and the `--ruby` option has instead taken its place.
I could not find much information on these options. What do these options do? 
What I understand is that they only install respectively the last stable rails gem and the last stable ruby. If this is all they do, I suppose they are optional indeed, since Ruby can be installed later, and every Rails application has its own rails version in the Gemfile.

**Comment by DanielKehoe** [comment]
I maintain the [documentation at RailsApp](http://railsapps.github.io/installrubyonrails-ubuntu.html) and I'd like to know if it's better to install RVM using the Ubuntu package or the curl command. I'll update the documentation accordingly.

**Comment by pkuczynski** [comment]
The preferred way of installing RVM on ubuntu is using dedicated package. Check https://github.com/rvm/ubuntu_rvm
