### ISSUE TITLE
uth token

### ISSUE THREAD

**Issue by AvishaManik** [rvm/rvm#4257]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by mpapis** [comment]
This does not include any information, closing, please feel free to reopen if you can describe the problem
