### ISSUE TITLE
Could not update RVM (rvm get master)

### ISSUE THREAD

**Issue by HarryHartmann** [rvm/rvm#4274]
## Description

rvm get master Exiting with failure status due to previous errors, Could not extract RVM sources.

## Steps to reproduce
(1) reboot system
(2) log in
(3) rvm get master

## Expected behavior
success (no error)

## Actual behavior
terminating with error
hry@hry-ThinkPad-T430s:~$ rvm get master
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /usr/share/rvm/archives/rvm-installer.asc
gpg: Signature made Sat 09 Sep 2017 03:49:18 PM EDT using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/share/rvm/archives/rvm-installer'
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
tar: .github: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Could not extract RVM sources.
Downloading https://bitbucket.org/mpapis/rvm/get/master.tar.gz
tar: .github: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Could not extract RVM sources.
Could not update RVM, please report to https://github.com/rvm/rvm/issues

# test utime
hry@hry-ThinkPad-T430s:~$ touch tst.txt
hry@hry-ThinkPad-T430s:~$ ls -lisa tst.txt
4072721 0 -rw-rw-r-- 1 hry hry 0 Jan  3 18:29 tst.txt
hry@hry-ThinkPad-T430s:~$ utime 100000 200000 tst.txt
hry@hry-ThinkPad-T430s:~$ ls -lisa tst.txt
4072721 0 -rw-rw-r-- 1 hry hry 0 Jan  3  1970 tst.txt

**Debug mode**:
hry@hry-ThinkPad-T430s:~$ rvm --debug get master
Downloading https://get.rvm.io
Running(17): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://get.rvm.io -o /usr/share/rvm/archives/rvm-installer
Detected GPG program: '/usr/bin/gpg2'
Running(15): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -sSI https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Running(17): curl --fail --location --max-redirs 10 --max-time 1800 --connect-timeout 30 --retry-delay 2 --retry 3 -s https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc -o /usr/share/rvm/archives/rvm-installer.asc
Verifying /usr/share/rvm/archives/rvm-installer.asc
gpg: Signature made Sat 09 Sep 2017 03:49:18 PM EDT using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/usr/share/rvm/archives/rvm-installer'
Selected RVM branch master
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
Running(13): curl --fail --location --max-redirs 10 --connect-timeout 30 --retry-delay 2 --retry 3 -sS https://github.com/rvm/rvm/archive/master.tar.gz
No PGP url given, skipping.
Running(6): tar xzf /usr/share/rvm/archives/rvm-master.tgz --no-same-owner --strip-components 1
tar: .github: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Could not extract RVM sources.
Downloading https://bitbucket.org/mpapis/rvm/get/master.tar.gz
Running(13): curl --fail --location --max-redirs 10 --connect-timeout 30 --retry-delay 2 --retry 3 -sS https://bitbucket.org/mpapis/rvm/get/master.tar.gz
No PGP url given, skipping.
Running(6): tar xzf /usr/share/rvm/archives/rvm-master.tgz --no-same-owner --strip-components 1
tar: .github: Cannot utime: Operation not permitted
tar: Exiting with failure status due to previous errors
Could not extract RVM sources.
Could not update RVM, please report to https://github.com/rvm/rvm/issues
__rvm_rm_rf already gone: /usr/share/rvm/tmp/4071*

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

hry@hry-ThinkPad-T430s:~$ rvm info

ruby-2.5.0@my-new-gemset:

  system:
    uname:        "Linux hry-ThinkPad-T430s 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "16.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/16.04/x86_64"

  rvm:
    version:      "1.29.3 (latest)"
    updated:      "46 minutes 18 seconds ago"
    path:         "/usr/share/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.0p0"
    date:         "2017-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2017-12-25 revision 61468"
    full_version: "ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]"

  homes:
    gem:          "/home/hry/.rvm/gems/ruby-2.5.0@my-new-gemset"
    ruby:         "/usr/share/rvm/rubies/ruby-2.5.0"

  binaries:
    ruby:         "/usr/share/rvm/rubies/ruby-2.5.0/bin/ruby"
    irb:          "/usr/share/rvm/rubies/ruby-2.5.0/bin/irb"
    gem:          "/usr/share/rvm/rubies/ruby-2.5.0/bin/gem"
    rake:         "/usr/share/rvm/rubies/ruby-2.5.0/bin/rake"

## environment:

    PATH:         "/home/hry/.rvm/gems/ruby-2.5.0@my-new-gemset/bin:/home/hry/.rvm/gems/ruby-2.5.0@global/bin:/usr/share/rvm/rubies/ruby-2.5.0/bin:/usr/share/rvm/bin:/home/hry/.rvm/gems/ruby-2.5.0@my-new-gemset/bin:/home/hry/.rvm/gems/ruby-2.5.0@global/bin:/home/hry/.linuxbrew/bin:/home/hry/.rbenv/plugins/ruby-build/bin:/home/hry/.rbenv/shims:/home/hry/.rbenv/bin:/opt/chef/embedded/bin:/home/hry/.linuxbrew/bin:/home/hry/.rvm/gems/ruby-2.5.0@my-new-gemset/bin:/home/hry/.rvm/gems/ruby-2.5.0@global/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin"
    GEM_HOME:     "/home/hry/.rvm/gems/ruby-2.5.0@my-new-gemset"
    GEM_PATH:     "/home/hry/.rvm/gems/ruby-2.5.0@my-new-gemset:/home/hry/.rvm/gems/ruby-2.5.0@global"
    MY_RUBY_HOME: "/usr/share/rvm/rubies/ruby-2.5.0"
    IRBRC:        "/usr/share/rvm/rubies/ruby-2.5.0/.irbrc"
    RUBYOPT:      ""
    gemset:       "my-new-gemset"
=====================================================================

## PROBLEM TRIGGER:
file: /usr/share/rvm/archives/rvm-installer:478
  rm -rf ${rvm_src_path}/rvm/*

(1)doesn't clean up good enough:
all dot-files and dot-dirs are remaining behind (not removed)
files like: .gems, .github_changelog_generator, .gitignore, .gitmodules, .travis.yml
dirs like: .github

(2) sudo is needed if there are dirs with insufficient permission flags for current user.

Next line, file: /usr/share/rvm/archives/rvm-installer:479
__rvm_debug_command $rvm_tar_command xzf ${rvm_archives_path}/${_file} ${rvm_tar_options:-} --strip-components 1 || .....

is the line where the error pops up: if in ${rvm_src_path} are some leftovers,  files with owner-id different  from user-id (i.e. root), then the tar is throwing an error ( permissions) end rvm-installer terminates with "Could not extract RVM sources.". 
  
## suggested fix
replace line 478 in file: /usr/share/rvm/archives/rvm-installer:478 with following lines:
```
CMD_CLEANUP_SRC="rm -rf ${rvm_src_path}/rvm/* ${rvm_src_path}/rvm/..?* ${rvm_src_path}/rvm/.[!.]*"

$CMD_CLEANUP_SRC \
|| {
     _return=$?
     log "Could not remove old RVM sources.\nTry: sudo $CMD_CLEANUP_SRC\nThen: retry your task again\n"
     return $_return
}

```

**Comment by rocaluis** [comment]
Test: `$ rvm get master` fails to download, update rvm
[#4274](https://github.com/rvm/rvm/issues/4274)

Default Ruby:
2.4.1

OS:
Fedora 27

Attempt to Reproduce:
1.  Restart System
2.  Log in
3.  Open terminal window
4.  At prompt input: `rvm get master`

 Actual Results:
1.  `rvm get master`
    Return: [gist](https://gist.github.com/rocaluis/ee82c02a39da2c5e191a27369fa5379f)
2.  `rvm &#x2013;debug get master`
    Return: [gist](https://gist.github.com/rocaluis/6a2b7710a4811e89edc037f39040dcfe)

Expected Results
terminate with error
  ```
  ...
      tar: .github: Cannot utime: Operation not permitted
      tar: Exiting with failure status due to previous errors
      Could not extract RVM sources.
      Could not update RVM, please report to https://github.com/rvm/rvm/issues
```
Additional Info
Issue #4274 attempt <span class="timestamp-wrapper"><span class="timestamp">&lt;2018-03-15 Thu 14:58&gt;</span></span>
