### ISSUE TITLE
rvm install of 2.4.3 error with '__rvm_make -j8'

### ISSUE THREAD

**Issue by sylverfyst** [rvm/rvm#4278]
## Description

rvm install isn't installing a clean version of 2.4.3, I'm getting the error "Error running '__rvm_make -j8' 

## Steps to reproduce

macOS Sierra   

 1. rvm get master
 2. rvm install ruby-2.4

## Expected behavior

Clean Install of ruby-2.4.3

## Actual behavior

* [command](https://gist.github.com/sylverfyst/4ee40c9e4805aa18822da5ea8d32d169)
* [make.log](https://gist.github.com/sylverfyst/37e3752769053305dfa53e2ac6433db0) 

## Environment info

jruby-9.1.5.0:

  system:
    uname:        "Darwin WNJ790271DVSATB 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.12"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)"
    zsh:          "/bin/zsh => zsh 5.2 (x86_64-apple-darwin16.0)"
    remote_path:  "osx/10.12/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "11 minutes 40 seconds ago"
    path:         "/Users/metzbr1/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "jruby"
    version:      "9.1.5.0"
    date:         "jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.111-b14 on 1.8.0_111-b14 +jit [darwin-x86_64]"
    platform:     "darwin-x86_64"
    patchlevel:   "TM"
    full_version: "jruby 9.1.5.0 (2.3.1) 2016-09-07 036ce39 Java HotSpot(TM) 64-Bit Server VM 25.111-b14 on 1.8.0_111-b14 +jit [darwin-x86_64]"

  homes:
    gem:          "/Users/metzbr1/.rvm/gems/jruby-9.1.5.0"
    ruby:         "/Users/metzbr1/.rvm/rubies/jruby-9.1.5.0"

  binaries:
    ruby:         "/Users/metzbr1/.rvm/rubies/jruby-9.1.5.0/bin/ruby"
    irb:          "/Users/metzbr1/.rvm/rubies/jruby-9.1.5.0/bin/irb"
    gem:          "/Users/metzbr1/.rvm/rubies/jruby-9.1.5.0/bin/gem"
    rake:         "/Users/metzbr1/.rvm/gems/jruby-9.1.5.0/bin/rake"

  environment:
    PATH:         "/Users/metzbr1/.rvm/gems/jruby-9.1.5.0/bin:/Users/metzbr1/.rvm/gems/jruby-9.1.5.0@global/bin:/Users/metzbr1/.rvm/rubies/jruby-9.1.5.0/bin:/Users/metzbr1/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/HP_Fortify/HP_Fortify_SCA_and_Apps_16.11/bin:/Applications/HP_Fortify/HP_Fortify_SCA_and_Apps_16.11/bin:/Users/metzbr1/.rvm/bin:/Applications/HP_Fortify/HP_Fortify_SCA_and_Apps_16.11/bin:/Users/metzbr1/.rvm/bin:/Applications/HP_Fortify/HP_Fortify_SCA_and_Apps_16.11/bin"
    GEM_HOME:     "/Users/metzbr1/.rvm/gems/jruby-9.1.5.0"
    GEM_PATH:     "/Users/metzbr1/.rvm/gems/jruby-9.1.5.0:/Users/metzbr1/.rvm/gems/jruby-9.1.5.0@global"
    MY_RUBY_HOME: "/Users/metzbr1/.rvm/rubies/jruby-9.1.5.0"
    IRBRC:        "/Users/metzbr1/.rvm/rubies/jruby-9.1.5.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by jordan-realfoto** [comment]
+1

**Comment by mpapis** [comment]
could you try: `rvm install ruby-2.4 -j 1`?

**Comment by mpapis** [comment]
Closing as there was no feedback in 2 weeks, feel free to reopen when you can provide the requested information.
