### ISSUE TITLE
Trying to install ruby no rails / RVM on SUSE Enterprise

### ISSUE THREAD

**Issue by SvrNbee** [rvm/rvm#4280]
We are trying to install the single user RVM of ruby on rails on a SUSE enterprise machine. Unfortunately we are encountering problems.
According to https://rvm.io/rvm/install we prepared a single user and run rvm 2.1. The installation starts and then halts - because some providers are missing.

Here is the logfile.
"[2018-01-15 14:33:21] requirements_opensuse_libs_install
requirements_opensuse_libs_install ()
{
    __rvm_try_sudo zypper install -y "$@" || return $?
}
current path: /home/ccsb
PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/ccsb/.rvm/bin:/home/ccsb/.rvm/bin
command(7): requirements_opensuse_libs_install bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++
++ __rvm_try_sudo zypper install -y bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++
++ typeset -a command_to_run
++ typeset sudo_path sbin_path missing_paths
++ command_to_run=("$@")
++ ((  UID == 0  ))
++ case "$rvm_autolibs_flag_number" in
++ is_a_function __rvm_sudo
++ typeset -f __rvm_sudo
++ missing_paths=
++ for sbin_path in /sbin /usr/sbin /usr/local/sbin
++ [[ -d /sbin ]]
++ [[ :/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/ccsb/.rvm/bin:/home/ccsb/.rvm/bin: != *\:\/\s\b\i\n\:* ]]
++ missing_paths+=:/sbin
++ for sbin_path in /sbin /usr/sbin /usr/local/sbin
++ [[ -d /usr/sbin ]]
++ [[ :/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/ccsb/.rvm/bin:/home/ccsb/.rvm/bin: != *\:\/\u\s\r\/\s\b\i\n\:* ]]
++ missing_paths+=:/usr/sbin
++ for sbin_path in /sbin /usr/sbin /usr/local/sbin
++ [[ -d /usr/local/sbin ]]
++ [[ :/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/ccsb/.rvm/bin:/home/ccsb/.rvm/bin: != *\:\/\u\s\r\/\l\o\c\a\l\/\s\b\i\n\:* ]]
++ missing_paths+=:/usr/local/sbin
++ [[ -n :/sbin:/usr/sbin:/usr/local/sbin ]]
++ command_to_run=(/usr/bin/env PATH="${PATH}${missing_paths}" "${command_to_run[@]}")
++ command_to_run=(__rvm_sudo -p "%p password required for '$*': " "${command_to_run[@]}")
++ __rvm_sudo -p '%p password required for '\''zypper install -y bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++'\'': ' /usr/bin/env PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/ccsb/.rvm/bin:/home/ccsb/.rvm/bin:/sbin:/usr/sbin:/usr/local/sbin zypper install -y bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++
++ command sudo -p '%p password required for '\''zypper install -y bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++'\'': ' /usr/bin/env PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/ccsb/.rvm/bin:/home/ccsb/.rvm/bin:/sbin:/usr/sbin:/usr/local/sbin zypper install -y bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++
++ sudo -p '%p password required for '\''zypper install -y bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++'\'': ' /usr/bin/env PATH=/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/games:/home/ccsb/.rvm/bin:/home/ccsb/.rvm/bin:/sbin:/usr/sbin:/usr/local/sbin zypper install -y bison gdbm-devel libffi-devel readline-devel sqlite3-devel gcc-c++
Loading repository data...
Reading installed packages...
Package 'sqlite3-devel' not found.
'libffi-devel' not found in package names. Trying capabilities.
No provider of 'libffi-devel' found.
'readline-devel' not found in package names. Trying capabilities.
No provider of 'readline-devel' found.
++ return 104
++ return 104"

Guess that sqlite3-devel, libffi-devel as well as readline-devel are missing.

Really new to using SUSE-Enterprise. How can we add these packages? Anyone got an idea and can help?

**Comment by mpapis** [comment]
try:
```bash
zypper search libffi-devel
```
this will show you if there are any packages matching that name, for me for example it's `libffi-devel-gcc5`

second part if the package is found run:
```bash
zypper info --provides libffi-devel-gcc5
```
change the package name to what it showed to you in earlier command,

show us all results

**Comment by mpapis** [comment]
Closing as there was no feedback in 2 weeks, feel free to reopen when you can provide the requested information.
