### ISSUE TITLE
Add support for TruffleRuby

### ISSUE THREAD

**Issue by ylluminate** [rvm/rvm#4297]
There's some need to integrate interactivity to allow users to accept or decline a license as per [this](https://github.com/oracle/truffleruby/issues/1062).

What's the preferred method for integrating such a license acceptance gate into an RVM Ruby formula?

**Comment by pkuczynski** [comment]
Lookup the source code or RVM and create a PR :)

**Comment by ylluminate** [comment]
It seems to me that a lot of other projects that need Java and other such Oracle components via a traditional click-through gate (eg OTN) implement shell based acceptance Y/N gates at download.  Obviously no one is getting prosecuted or running into legal problems [over there](https://launchpad.net/~webupd8team/+archive/ubuntu/java), so I would hope that the same thing can be done here.  I guess some of the project members are in a quandary due to their positions and need to remain aloof, but such things really do hinder the project on a large scale moving forward.

So yeah, we definitely need to get a nice independent PR going for Truffle here in this regard to help everyone out...

**Comment by havenwood** [comment]
[Direct downloads](https://github.com/oracle/graal/releases) of GraalVM Community Edition (CE) without a click-through are now available for Linux. Once direct downloads of GraalVM CE are available for macOS, TruffleRuby support should be straightforward to add for macOS and Linux.

Here's a [little script showing installation](https://gist.github.com/havenwood/38c36e48acea50d420a11a4ca5455ad7) for Linux and a work-in-progress commit adding [installation support for ruby-install](https://github.com/havenwood/ruby-install/compare/deprecate-maglev...truffleruby).

**Comment by eregon** [comment]
Should support for TruffleRuby be added to RVM(1) aka this repo or RVM2?
I'm not very familiar with the development of RVM2.

**Comment by havenwood** [comment]
@eregon Here, RVM(1), is the right place. :-)

**Comment by eregon** [comment]
I started looking at this, but I have a one general question.

TruffleRuby is distributed as binary archives per platform/architecture:
* https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc2/truffleruby-1.0.0-rc2-linux-amd64.tar.gz
* https://github.com/oracle/truffleruby/releases/download/vm-1.0.0-rc2/truffleruby-1.0.0-rc2-macos-amd64.tar.gz

Those contain everything we need.
Additionally we also want to trigger a "post-install" hook after extracting the tarball and copying to the target directory. This hook currently rebuilds the openssl C extension, to adapt to the target system libssl version and configuration.

So the question is: is that a "binary ruby" from the point of view of RVM?
It seems that JRuby uses that way with `rvm_remote_server_url1=https://s3.amazonaws.com/jruby.org`.
It looks like the current logic for binary rubies expects all tarballs to be under the same URL path, which is not true with GitHub releases (where the version is a component of the URL, see the URLs above).
Also, it'd seem weird to me to try https://github.com/oracle/truffleruby/releases/download when looking for binary rubies of other implementations.

So I'm thinking we'd rather behave like a source install, except almost everything is already built.
RVM devs: Does that make sense?

**Comment by eregon** [comment]
Fixed by https://github.com/rvm/rvm/pull/4406 and https://github.com/rvm/rvm/commit/70ff3d0af27e55a2b70f66216e5d1919c5bcd840 on master.

You can now install TruffleRuby with:
```bash
rvm get master
rvm install truffleruby
```
(for Linux & macOS x86_64)
