### ISSUE TITLE
rvm requirements fails with Homebrew 1.5.4

### ISSUE THREAD

**Issue by mramsden** [rvm/rvm#4303]
## Description

Unable to run rvm requirements due to a dependency on the now deprecated `homebrew/versions`. An error is occurring in the homebrew tap.

## Steps to reproduce

1. Run standard install `curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles`
2. Enable autolibs `~/.rvm/bin/rvm get stable --autolibs=enable`
3. Enable autodotfiles `~/.rvm/bin/rvm get stable --auto-dotfiles`
4. Link libraries to homebrew `~/.rvm/bin/rvm autolibs homebrew`
5. Run requirements `~/.rvm/bin/rvm requirements`

Requirements now fails trying to install `homebrew/versions`.

The same occurs after running `rvm get master`.

## Expected behavior

Automated installation of ruby dependencies.

## Actual behavior

```
$ bash -c "~/.rvm/bin/rvm requirements"
Checking requirements for osx_brew.
Installing requirements for osx_brew.
Updating system..........
Installing required custom packages: homebrew/versions.
Error running 'requirements_osx_brew_install_custom homebrew/versions',
please read /Users/devices/.rvm/log/1518442306/install_custom.log
Requirements installation failed with status: 1.
```

install_custom.log:

```
[2018-02-12 13:28:43] requirements_osx_brew_install_custom
requirements_osx_brew_install_custom ()
{
    \typeset __tap;
    for __tap in "$@";
    do
        brew tap "${__tap}" || return $?;
    done
}
current path: /Users/devices/appfactory-ansible-ios-role
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/devices/.rvm/bin
command(2): requirements_osx_brew_install_custom homebrew/versions
+ typeset __tap
+ for __tap in '"$@"'
+ brew tap homebrew/versions
Error: homebrew/versions was deprecated. This tap is now empty as all its formulae were migrated.
+ return 1
```

## Environment info

```
system:

  system:
    uname:        "Darwin UK03014.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "2 minutes 45 seconds ago"
    path:         "/Users/devices/.rvm"
    autolibs:     "[homebrew] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/devices/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by malrase** [comment]
Also found this. I tested locally by editing the following file to replace `homebrew/versions` with `homebrew/core` and it seemed to work:
https://github.com/rvm/rvm/blob/master/scripts/functions/requirements/osx_brew#L240

I'm not sure if that's the actual long-term fix though?

**Comment by mramsden** [comment]
Ah that would make sense as a quick solution. I found this with an old provisioning script that we have were we had to remove it as a dependency. Agreed that it's not great that we need to hack things around a bit without understanding the guts of RVM.

**Comment by mramsden** [comment]
Okay you set me onto an interesting path with that link. This unblocked me for the time being as I was able to help out RVM. I'm running on macOS 10.13.2 with the latest homebrew. Before you run `rvm requirements` you should `brew install gcc49`. This will install the version of GCC that rvm is after and now when you run requirements it will happily install the rest of the library. Based on https://github.com/rvm/rvm/blob/c20852ea9cfce5e14c994d035cf8f0d0dbf07797/scripts/functions/requirements/osx_brew#L226 you may need to adjust the version of gcc you install.

**Comment by pkuczynski** [comment]
Could u please run:

```
brew remove gcc49
rvm get branch /drop-homebrew-versions
rvm requirements
```

That should fix the issue. Thanks for helping with testing.

**Comment by mramsden** [comment]
I’ll give it a shot tomorrow morning when I have access to the machine this is on.

**Comment by mramsden** [comment]
@pkuczynski That looks like it did the trick.

I've tried it against a different machine since I don't have access on the original one I saw the issue on. Just an additional testing note on this, I had an older install on the machine I used so had to run `brew untap homebrew/versions` in order to make `rvm requirements` attempt the setup again.

Other than that though it looks like it's done the trick and `gcc@6` is installing.

**Comment by pkuczynski** [comment]
Awesome. We will merge it then!

**Comment by jogiranjith** [comment]
it failed for me again 
Checking requirements for osx.
Installing requirements for osx.
Updating system......
Installing required custom packages: homebrew/versions.
Error running 'requirements_osx_brew_install_custom homebrew/versions',
please read /Users/ranjith/.rvm/log/1520668925/install_custom.log
Requirements installation failed with status: 1.

**Comment by mramsden** [comment]
@jogiranjith Have you tried running `rvm get head`. It looks like this fix hasn't landed in stable yet.

**Comment by seguelador** [comment]
`rvm get head` works for me. Thanks @mramsden

**Comment by rdammkoehler** [comment]
'rvm get head' also worked for me. Solution still not on stable I guess.

**Comment by harishdixit1** [comment]
I am also getting the similar error when I run "rvm requirements" command.
Can someone please help with this? I tried above solutions but it did not work. 

$ rvm requirements
Checking requirements for osx.
Installing requirements for osx.
Updating system.........
Installing required custom packages: homebrew/dupes.
Error running 'requirements_osx_brew_install_custom homebrew/dupes',
please read ///install_custom.log
Requirements installation failed with status: 1.

dupes is deprecated but rvm requirements always looking for this not for core.
