### ISSUE TITLE
Error running './configure

### ISSUE THREAD

**Issue by fifiteen82726** [rvm/rvm#4308]
## Description
After I migrating my Macbook to the new one, I encounter an error during reinstalling `rvm`

## Steps to reproduce

```rb
⋊> rvm install 2.3.3
```

## Environment 

 1. OSX 10.13.3
 2. rvm version: rvm `1.29.3` (master) by Michal Papis, Piotr Kuczynski
 3. system ruby: ruby `2.5.0p0`
 4. fish shell, version `2.5.0`
## Expected behavior

Install ruby `2.3.3` via `rvm`  perfectly.

## Actual behavior

```rb
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.13/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/Coda/.rvm/rubies/ruby-2.3.3, this may take a while depending on your cpu(s)...
ruby-2.3.3 - #downloading ruby-2.3.3, this may take a while depending on your connection...
ruby-2.3.3 - #extracting ruby-2.3.3 to /Users/Coda/.rvm/src/ruby-2.3.3.....
ruby-2.3.3 - #applying patch /Users/Coda/.rvm/patches/ruby/ruby_2_3_gcc7.patch.
ruby-2.3.3 - #applying patch /Users/Coda/.rvm/patches/ruby/2.3.3/random_c_using_NR_prefix.patch.
ruby-2.3.3 - #configuring........................
Error running './configure --prefix=/Users/Coda/.rvm/rubies/ruby-2.3.3 --with-opt-dir=/usr/local/Cellar/libyaml/0.1.7:/usr/local/Cellar/readline/7.0.3_1:/usr/local/Cellar/libksba/1.3.5:/usr/local/opt/openssl --disable-install-doc --enable-shared',
please read /Users/Coda/.rvm/log/1518890785_ruby-2.3.3/configure.log
There has been an error while running configure. Halting the installation.
```

/Users/Coda/.rvm/log/1518890785_ruby-2.3.3/configure.log is here 
(https://gist.github.com/fifiteen82726/49e96a7f90a798eac6e336b213143478)

## Environment info

https://gist.github.com/fifiteen82726/47bb65311f9c1399f327e2a470251a42

**Comment by romenigld** [comment]
I have this to..

```
rvm install 2.3.3                       1 ↵
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.13/x86_64/ruby-2.3.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx_port.
Installing macports - please wait
Error running 'requirements_osx_port_install_port',
please read /Users/romenigld/.rvm/log/1520280795_ruby-2.3.3/port_install.log
Requirements installation failed with status: 56.
```

**Comment by jadrevenge** [comment]
did you read the suggested log files that were labelled "please read"?

/Users/Coda/.rvm/log/1518890785_ruby-2.3.3/configure.log
or
 /Users/romenigld/.rvm/log/1520280795_ruby-2.3.3/port_install.log

I'm guessing that there is an issue with your compiler, or a package that you have yet to install

**Comment by romenigld** [comment]
I don't read. But I fix doing something. And now work's, thank's @jadrevenge.

**Comment by LWanjiru** [comment]
What did you fix @romenigld ?

**Comment by aidan-fitz** [comment]
I'm still having this problem even after running `rvm --debug requirements ruby`.

**Comment by aidan-fitz** [comment]
Reinstalling RVM doesn't work either.

**Comment by jadrevenge** [comment]
the overkill, move the problem out of the way:
https://superuser.com/questions/1296016/rvm-error-running-configure

and from this email thread: http://emacs-w3m.namazu.org/ml/msg06843.html

My best guess is that you have Boehm GC installed in non-standard
`lib' directory, like /usr/local/lib/libgc.*.  /usr/local/lib is
standard of course, however the w3m installer doesn't treat it so.
I'm not an exception, and am always annoying with it.  My solution
is to set the LDFLAGS environment variable as /usr/local/lib before
building w3m.

Oops, sorry.  That's wrong.  The correct way is setting the
LDFLAGS environment variable as:

'-Xlinker -R/usr/local/lib'

I am not a Mac user, so can't help with the specifics

**Comment by aidan-fitz** [comment]
This works!

**Comment by chamini2** [comment]
I read the logs as instructed and it said:

```[2019-01-26 13:05:36] ./configure
current path: /Users/matteo/.rvm/src/ruby-2.5.3
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/bin:/bin:/bin:/bin:/bin:node_modules/.bin:/Users/matteo/.local/bin:/Users/matteo/.cabal/bin:.cabal-sandbox/bin:/usr/local/sbin:/usr/local/bin:/Users/matteo/Downloads/google-cloud-sdk/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/matteo/.rvm/bin
GEM_PATH=
command(5): ./configure --prefix=/Users/matteo/.rvm/rubies/ruby-2.5.3 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/libksba:/usr/local/opt/readline:/usr/local/opt/zlib:/usr/local/opt/openssl@1.1 --disable-install-doc --enable-shared
checking for ruby... /usr/bin/ruby
tool/config.guess already exists
tool/config.sub already exists
checking build system type... x86_64-apple-darwin18.2.0
checking host system type... x86_64-apple-darwin18.2.0
checking target system type... x86_64-apple-darwin18.2.0
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
configure: error: clang version 3.0 or later is required
```
Specifically,

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
configure: error: clang version 3.0 or later is required
```

So I did `$ clang` and got the same exact error, which led me to search that error message online, which led me to 

```xcode-select --install```

Which installs the command line developer tools and then `rvm install 2.5` worked.

**Comment by guofen** [comment]
I have same issue too;
I try 'xcode-select --install' and 'rvm --debug requirements ruby' method, but both can resolve my question; 
Have anythiing else idea?

**Comment by t12nslookup** [comment]
> I have same issue too;
> I try 'xcode-select --install' and 'rvm --debug requirements ruby' method, but both can not resolve my question;
> Have anythiing else idea?

Are you sure you have the same issue?  do you have the same lines in your log file?

**Comment by guofen** [comment]
[2019-11-20 14:34:33] ./configure
current path: /Users/guofen/.rvm/src/ruby-2.3.0
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/guofen/.nvm/versions/node/v12.4.0/bin:/Users/guofen/.nvm/versions/node/v7.10.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/guofen/.rvm/bin
command(5): ./configure --prefix=/Users/guofen/.rvm/rubies/ruby-2.3.0 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/libksba:/usr/local/opt/readline:/usr/local/opt/zlib:/usr/local/opt/openssl --disable-install-doc --enable-shared
checking for ruby... /usr/bin/ruby
config.guess already exists
config.sub already exists
checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking target system type... x86_64-apple-darwin18.7.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/guofen/.rvm/src/ruby-2.3.0':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details

**Comment by guofen** [comment]
yes, I have same line in my log file

**Comment by t12nslookup** [comment]
so a completely different error:

configure: error: in /Users/guofen/.rvm/src/ruby-2.3.0': configure: error: cannot run C compiled programs. If you meant to cross compile, use --host'.

can you try cleaning out the compile directories from within your RVM and trying again, or/and create a new git issue for this problem?

Thanks

Jon

**Comment by guofen** [comment]
Tnank You, Jon
I try it
