### ISSUE TITLE
Openssl, mkmain Error while running rvm install 1.9.2

### ISSUE THREAD

**Issue by pfisher3** [rvm/rvm#431]
I have been having a problem with installing ruby on my mac os x system. I really cant understand why because I've ran the same commands which have gotten everything up and running for a different user on the system.

see below:
Installing Ruby from source to: /Users/pfisher3/.rvm/rubies/ruby-1.9.2-p290, this may take a while depending on your cpu(s)...

ruby-1.9.2-p290 - #fetching 
ruby-1.9.2-p290 - #extracted to /Users/pfisher3/.rvm/src/ruby-1.9.2-p290 (already extracted)
Fetching yaml-0.1.4.tar.gz to /Users/pfisher3/.rvm/archives
Extracting yaml-0.1.4.tar.gz to /Users/pfisher3/.rvm/src
Configuring yaml in /Users/pfisher3/.rvm/src/yaml-0.1.4.
Compiling yaml in /Users/pfisher3/.rvm/src/yaml-0.1.4.
Installing yaml to /Users/pfisher3/.rvm/usr
ruby-1.9.2-p290 - #configuring 
ruby-1.9.2-p290 - #compiling 
ERROR: Error running 'make ', please read /Users/pfisher3/.rvm/log/ruby-1.9.2-p290/make.log
ERROR: There has been an error while running make. Halting the installation.

Also this is the end of my make log:

In file included from openssl_missing.c:22:
openssl_missing.h:71: error: conflicting types for ‘HMAC_CTX_copy’
/opt/local/include/openssl/hmac.h:102: error: previous declaration of ‘HMAC_CTX_copy’ was here
openssl_missing.h:95: error: conflicting types for ‘EVP_CIPHER_CTX_copy’
/opt/local/include/openssl/evp.h:459: error: previous declaration of ‘EVP_CIPHER_CTX_copy’ was here
openssl_missing.c:27: error: conflicting types for ‘HMAC_CTX_copy’
/opt/local/include/openssl/hmac.h:102: error: previous declaration of ‘HMAC_CTX_copy’ was here
openssl_missing.c:122: error: conflicting types for ‘EVP_CIPHER_CTX_copy’
/opt/local/include/openssl/evp.h:459: error: previous declaration of ‘EVP_CIPHER_CTX_copy’ was here
make[1]: **\* [openssl_missing.o] Error 1
make: **\* [mkmain.sh] Error 1

If anyone could help it would be greatly appreciated. note: Some things I've tried include reinstalling rvm, and running all commands again. installing readline, and openssl but I still receive the error running make. 

Phil

**Comment by RubenGram** [comment]
Solution proposed by @ddd worked for me (in my case `rvm install ruby-2.3.1 --with-openssl-dir=/usr/local/opt/openssl` because I wanted a different ruby version). 
I listed openssl's with `brew list -1 | grep openssl`, yielding 2 results: **openssl** and **openssl@1.1**.
From logs, it seems that rvm was trying to use **openssl@1.1** instead of **openssl**.  So my guess is that the flag `--with-openssl-dir=/usr/local/opt/openssl` did the job. Please correct me if I'm wrong.
