### ISSUE TITLE
rvm install --url, --branch undocumented; lacks --tag

### ISSUE THREAD

**Issue by saizai** [rvm/rvm#4312]
<s>1. The ability to install a ruby from a git url + branch w/ --url & --branch isn't documented in e.g. `rvm help install`. It should be.</s> ETA: Fixed in #4350.

2. It should also allow git tags, not just branches, which is how e.g. rubinius marks its releases.

**Comment by saizai** [comment]
See also https://github.com/rvm/rvm/issues/4311

**Comment by saizai** [comment]
This isn't closed. `--tag` is stil lacking.

**Comment by pkuczynski** [comment]
Here you go. Are you planning to fire up another PR?

**Comment by saizai** [comment]
Dunno that I have the spoons for it. :/
