### ISSUE TITLE
Compilation fails on Mac High Sierra - error reading '/dev/fd/4'

### ISSUE THREAD

**Issue by geo242** [rvm/rvm#4313]
## Description
Compilation of any ruby version fails

## Steps to reproduce

 1. rvm install 2.5.0

## Expected behavior

To install successfully

## Actual behavior

* [command](https://gist.github.com/geo242/fc7b852984e0b014233ca778db844d1a)
* [config.log](https://gist.github.com/geo242/c07960b850ffc56e7e6ba83e25a207a3)
* [make.log](https://gist.github.com/geo242/d772117c22fb6555a351f21e347aade3)

## Environment info
```
system:

  system:
    uname:        "Darwin Geoffs-MacBook-Pro-2.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.3 (latest)"
    updated:      "31 minutes 38 seconds ago"
    path:         "/Users/geoff/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/code/bethel/arcanist/bin:~/code/bethel/php:/usr/local/share/dotnet:/usr/local/opt/node@6/bin:/Users/geoff/.npm-packages/bin:/usr/local/opt/ansible@1.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/geoff/code/bethel/arcanist/bin:/Users/geoff/code/bethel/php:/usr/local/share/dotnet:/Applications/Server.app/Contents/ServerRoot/usr/bin:/Applications/Server.app/Contents/ServerRoot/usr/sbin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS:/Users/geoff/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by ThreeSixes** [comment]
+1 except with a different Ruby version:
`rvm install 2.3.1`

**Comment by dgboy2000** [comment]
+1 with ruby 2.3.1 as well

**Comment by mooserson** [comment]
+1 with 2.3.6

**Comment by lucksp** [comment]
+1 2.4.1

**Comment by looserfrog** [comment]
I have had a similar problem "error: error reading '/dev/fd/7'". 
In my case it helped to deactivate the antivirus software Avira.

**Comment by ThreeSixes** [comment]
^ That did it.

**Comment by mooserson** [comment]
Worked for me as well (2.3.6)

**Comment by johncarney** [comment]
Disabling Avira's real-time protection worked for me as well

**Comment by jcroucher** [comment]
Disable Avira fixed for me. I spent too long trying to fix this issue.

**Comment by BrightnBubbly** [comment]
looserfrog, you are a godsend.

**Comment by whitesnow9291** [comment]
I removed Avira after solving this!

**Comment by chentianwei411** [comment]
感谢，thanks everyone. this question cost me 5 hours。

**Comment by AdamYang121** [comment]
@looserfrog you are awesome! How did you find this solution? Magical!

**Comment by JoyceT-ECI** [comment]
works for me! thx a lot

**Comment by ethan-sletteland** [comment]
Thanks, this was killing me!

**Comment by ycbencheng** [comment]
@looserfrog Thanks!!!

**Comment by CLTPayne** [comment]
Amazing! Thank you @looserfrog. 

This worked like a dream come true!!

**Comment by rboldway** [comment]
Once I google searched for error: error reading '/dev/fd/8' I found this.
@loosefrog Thanks!!!

**Comment by teddyswu** [comment]
Thanks!!!!!!!!!!!!!!!!!!!!!!!!! It's work!!!!

**Comment by derfeo** [comment]
Thank you so much! It worked!

**Comment by ianbrind** [comment]
@looserfrog Top man, good spot!

**Comment by mind1949** [comment]
@looserfrog Thank you so much! It worked!

**Comment by nicktruch** [comment]
@whitesnow9291 OMG thank you soooooooooo much !!! It worked so well !!!

**Comment by deadlylaid** [comment]
fuck.... I solved my problem remove avira..... thankyou

**Comment by Michael1969** [comment]
yes fu... "In my case it helped to deactivate the antivirus software Avira."

**Comment by westerwei** [comment]
It worked!! Thank you so much!!
