### ISSUE TITLE
visual studio code auto create ruby-version again and again

### ISSUE THREAD

**Issue by Baozi2** [rvm/rvm#4341]
Hello.
I use vscode for rails when I open the vscode terminal，then  the .ruby-version and .ruby-gemset auto create.
I want to know is rvm bug or vscode?
![vs-code](https://user-images.githubusercontent.com/5621510/38065381-a5ee5e1a-3335-11e8-88d4-06c85ea566a0.png)

----
VScode version 1.21.1
shell zsh
rvm 1.29.3

**Comment by pkuczynski** [comment]
Must be vscode. We never experienced anything like this. Does it happen also when u switch to bash?

**Comment by Baozi2** [comment]
Does it happen also when u switch to bash? 
No happen!
thank you!

**Comment by Baozi2** [comment]
Now its' ok,  haven't do anything. So strange!!
