### ISSUE TITLE
missing install options in rvm-installer help 

### ISSUE THREAD

**Issue by E3V3A** [rvm/rvm#4351]
In the installer script [rvm-installer](https://github.com/rvm/rvm/blob/master/binscripts/rvm-installer), it seem that all the additional install options starting with `--<special-option>`  (such as `--ruby`) are not shown in `rvm-installer help`.

**Comment by E3V3A** [comment]
Are these documented somewhere? 
I.e. What does `rvm-installer stable --ruby` do differently than, let's say: `rvm install ruby-2.5.1` ??

**Comment by pkuczynski** [comment]
You shouldn't use `rvm-installer` directly. We added some more help in https://github.com/rvm/rvm/pull/4350
