### ISSUE TITLE
How to be sure to get the last MRI Ruby version 

### ISSUE THREAD

**Issue by knzudgt** [rvm/rvm#4352]
Considering what [ruby-lang.org](https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/) says, the last stable ruby release is 2.5.1
I would like to install it using rvm.
In section [Installing rubies](https://rvm.io/rubies/installing) at rvm.io, it is suggested to load the list of known rubies to be installed, using the following command:

    $ rvm list known

However ruby 2.5.1 is not in that list:

\# MRI Rubies
[ruby-]1.8.6[-p420]
[ruby-]1.8.7[-head] # security released on head
[ruby-]1.9.1[-p431]
[ruby-]1.9.2[-p330]
[ruby-]1.9.3[-p551]
[ruby-]2.0.0[-p648]
[ruby-]2.1[.8]
[ruby-]2.2[.4]
[ruby-]2.3[.0]
[ruby-]2.2-head
ruby-head

Is the above list incomplete or am I expected to stick with its rubies?
Also, is ruby 2.5.1 accepted by MRI?

**Comment by E3V3A** [comment]
I just did that, and got: 
```
    # MRI Rubies
    [ruby-]1.8.6[-p420]
    [ruby-]1.8.7[-head] # security released on head
    [ruby-]1.9.1[-p431]
    [ruby-]1.9.2[-p330]
    [ruby-]1.9.3[-p551]
    [ruby-]2.0.0[-p648]
    [ruby-]2.1[.10]
    [ruby-]2.2[.10]
    [ruby-]2.3[.7]
    [ruby-]2.4[.4]
    [ruby-]2.5[.1]
    [ruby-]2.6[.0-preview1]
    ruby-head
```

So I guess it is hardware architecture dependent?

**Comment by knzudgt** [comment]
@E3V3A That is weird. Might it be that I do not get the same list because I am using an outdated version of rvm, 1.27.0 instead of 1.29.3? I am using Ubuntu 14.04 LTS

**Comment by pkuczynski** [comment]
@knzudgt run `rvm get master` after installing the package. This will get latest ruby definition.

**Comment by knzudgt** [comment]
@pkuczynski am I expected to run `rvm get stable` AND after that `rvm get master`, or only `rvm get master`?

**Comment by pkuczynski** [comment]
`rvm get master` is enough

**Comment by knzudgt** [comment]
@pkuczynski last question: being on Ubuntu 14.04 LTS, would you suggest to run the command with `sudo` and option `--autolibs=enable`?

**Comment by pkuczynski** [comment]
Just run `rvm get master`. No other params and no `sudo`

**Comment by pkuczynski** [comment]
you can use the [dedicated Ubuntu package](https://github.com/rvm/ubuntu_rvm), so you'll receive stable RVM releases automatically and no `sudo` required.

**Comment by knzudgt** [comment]
Done! No problems whatsoever and now the list of rubies is also updated.
@pkuczynski To install the Ubuntu package I would need to know how to migrate from my present rvm installation: shall I remove it and then install the Ubuntu package, hopefully without loss of rubies and gemsets?
