### ISSUE TITLE
Is upgrading RVM safe?

### ISSUE THREAD

**Issue by knzudgt** [rvm/rvm#4353]
I am on a Ubuntu 14.04 LTS machine with rvm `1.27.0` installed with curl.
Does upgrading rvm to the latest stable version `1.29.3` preserves rubies, gemsets and does not modify configuration files like `~/bashrc`, `~/.profile` and `~/.bash_profile`?
Which one of the following codes would you suggest to upgrade'

    $ rvm get stable
    $ rvm get stable --autolibs=enable
    $ rvm get stable --autolibs=packages

Also. is it advisable to use sudo with the above commands, such as `sudo rvm get stable`?

**Comment by pkuczynski** [comment]
Upgrading RVM is safe in a sense it does not touch installed rubies.

**Comment by raelgc** [comment]
@knzudgt Just to share: you can use the [dedicated Ubuntu package](https://github.com/rvm/ubuntu_rvm), so you'll receive stable RVM releases automatically and no `sudo` required.

**Comment by knzudgt** [comment]
@raelgc I already installed via curl. Do you by chance know how to safely remove rvm and install the Ubuntu package, without loss of rubies and gemsets?
