### ISSUE TITLE
"ps: unknown option --o" error

### ISSUE THREAD

**Issue by charliepugh92** [rvm/rvm#4354]
## Description

Hi all,

I just got a fresh new Windows workstation, and I'm coming up on an error when trying to use rvm after installing the master branch.

I'm using the latest version of git-bash (2.17.0.windows.1)
My `uname` is: `MINGW64_NT-10.0`

Here's some output to show what's happening, and I'll gladly give any info needed to help diagnose what's wrong.

`/curl -sSL https://get.rvm.io | bash` output:

```
Downloading https://github.com/rvm/rvm/archive/master.tar.gz
Upgrading the RVM installation in /c/Users/Charlie/.rvm/
    RVM PATH line found in /c/Users/Charlie/.mkshrc /c/Users/Charlie/.profile /c/Users/Charlie/.bashrc /c/Users/Charlie/.zshrc.
    RVM sourcing line found in /c/Users/Charlie/.profile /c/Users/Charlie/.bash_profile /c/Users/Charlie/.zlogin.
Upgrade of RVM in /c/Users/Charlie/.rvm/ is complete.
Do not know how to check user shell on 'MINGW64_NT-10.0'.
  * RVM 1.30 simplifies behavior of 'rvm wrapper' subcommand
```

`rvm install ruby-2.2.5` output:

```
ps: unknown option -- o
Try `ps --help' for more information.
RVM not loaded, aborting.
```

`type rvm | head -1` output:

```
rvm is hashed (/c/Users/Charlie/.rvm/bin/rvm)
```

`rvm info` output:
```
ps: unknown option -- o
Try `ps --help' for more information.
RVM not loaded, aborting.
```

Thanks,
Charlie

**Comment by pkuczynski** [comment]
Can you run `ps --help`? For me (on macOS)

```
-o       Display information associated with the space or comma separated list of keywords specified.  Multiple keywords may also be given in the form of more than one -o option.  Keywords may be appended with an equals (`=') sign and a string.  This causes the printed header to use the specified string instead of the standard header.  If all keywords have empty header texts, no header line is written.
```

**Comment by charliepugh92** [comment]
Hi pkuczynski,

I'm not on macOS, I'm on windows 10.

`ps --help` output:

```
Usage: ps [-aefls] [-u UID] [-p PID]

Report process status

 -a, --all       show processes of all users
 -e, --everyone  show processes of all users
 -f, --full      show process uids, ppids
 -h, --help      output usage information and exit
 -l, --long      show process uids, ppids, pgids, winpids
 -p, --process   show information for specified PID
 -s, --summary   show process summary
 -u, --user      list processes owned by UID
 -V, --version   output version information and exit
 -W, --windows   show windows as well as cygwin processes

With no options, ps outputs the long format by default
```

**Comment by tasaif** [comment]
I added the following into ~/.rvm/scripts/rvm after line 12:
(MINGW64_NT*) __shell_name="`\command \ps -p $$ | \command \awk 'END {print $NF}'` 2>/dev/null" ;;

**Comment by maryam21** [comment]
Thanks @tasaif , that worked for me.

**Comment by Odogwudozilla** [comment]
Thanks @tasaif !!

**Comment by KirillNesmashny** [comment]
Thanks, it help me solved the same problem.

**Comment by hermanomark** [comment]
@tasaif thank you very much!

**Comment by yaodao-x** [comment]
> I added the following into ~/.rvm/scripts/rvm after line 12:
> (MINGW64_NT*) __shell_name="`\command \ps -p $$ | \command \awk 'END {print $NF}'` 2>/dev/null" ;;

thanks a lot .

**Comment by PCZeroX** [comment]
Thanks a lot @tasaif. That worked fine for me!

**Comment by pkuczynski** [comment]
@PragmaticEd you just need to pull `rvm get master` to get the latest version...

**Comment by fdmarc** [comment]
The suggested change needs to tweaked for Windows 11 - `uname` for me is `MSYS_NT-10.0-26200` so the match needs to be `MSYS_NT-*`, I changed the `CYGWIN` match to from `(CYGWIN*|MINGW*)` to  `(CYGWIN*|MINGW*|MSYS_NT-*)`

So this my switch statement in `~/.rvm/scripts/rvm` :

```bash
  case "`uname`" in

    (CYGWIN*|MINGW*|MSYS_NT-*) 
      __shell_name="`\command \ps -p $$ | \command \awk 'END {print $NF}'` 2>/dev/null" ;;


```
