### ISSUE TITLE
Installing RVM - BASH 3.2.25 required (you have 3.2.57)

### ISSUE THREAD

**Issue by thelittlebreadcrumb** [rvm/rvm#4377]
## Description

I'm trying to follow some guidelines to install RVM via [OS X Installfest](http://installfest.railsbridge.org/installfest/osx_rvm#install-rvm). However when it comes to installing RVM, I face the below error

## Steps to reproduce

 1. `curl -L get.rvm.io | bash -s stable` is typed into Terminal
 2. I get the below message back in Terminal 

## Expected behavior
It installs, I guess?

## Actual behavior

* [command](https://gist.github.com/thelittlebreadcrumb/a850c0772296f0b68a521d5b172115e6)
* Sorry, I'm unsure where to find the config & make logs. 

## Environment info

`rvm info`
`-bash: rvm: command not found`

## I also tried
[Issue 2346](https://github.com/rvm/rvm/issues/2346)
* `My-MBP:~ coolusername$ type head`
`head is hashed (/Applications/XAMPP/xamppfiles/bin/head)`

I don't know where my .bash_profile is saved and if $PATH has anything to do with it. 

Any help would be appreciated! Would love to start learning Ruby :smiley:

**Comment by thelittlebreadcrumb** [comment]
### Update - this has now been resolved.
_*Found the .bash_profile file!*_
- This was located in `/Users/yourusername`. If you don't see it, press Command+Shift+. to view files. 
- I moved it into another folder as a backup before deleting it.

**Comment by hhzheinhtetzaw** [comment]
@thelittlebreadcrumb How did you resolve this ? I've been facing this issue about 2 days and still cannot solve.

**Comment by Celfonica** [comment]
I have the same problem but that doesn't solve it

**Comment by niightly** [comment]
I'm still with the error
