### ISSUE TITLE
Cannot install ruby on Mac OS Mojave (10.14 beta)

### ISSUE THREAD

**Issue by duhanebel** [rvm/rvm#4402]
when trying to install a version of ruby on Mac OS 10.14 beta 1, the pre-requirments check fails with the following:
```
Searching for binary rubies, this might take some time.
Found remote file https://rubies.[secure]-ci.org/osx/10.13/x86_64/ruby-2.5.1.tar.bz2
Checking requirements for osx.
Installing requirements for osx.
Updating system - please wait
Xcode version older than 4.6.2 installed, download and install newer version from:
    http://connect.apple.com
After installation open Xcode, go to Downloads and install Command Line Tools.
Error running 'requirements_osx_brew_update_system ruby-2.5.1',
please read /Users/[secure]/.rvm/log/1528193314_ruby-2.5.1/update_system.log
Requirements installation failed with status: 1.
```

**Comment by mjm** [comment]
I'm seeing a similar issue to this, but instead on High Sierra with the Xcode 10 beta 1 installed. It seems like the version check for Xcode thinks that Xcode 10 is a lower version than 4.6.2?

**Comment by mjm** [comment]
It looks like this issue is resolved in the master branch, which has had a few updates to the version sorting.

**Comment by hugazo** [comment]
I can confirm that the manual download of CLI for Xcode 10 Beta solved this (I've been failing to install all the afternoon, with rvm and rvenb).

**Comment by ivan-leschinsky** [comment]
Yep, in master branch it has been fixed.
```sh
rvm get master
rvm install 2.5.1
```

**Comment by pkuczynski** [comment]
Thanks for reporting. It's always best to try with `master`. However the above changes have been already released, so I can safely close...

**Comment by pkuczynski** [comment]
@sfsgagi whats wrong with the pkh-info check? I can fix it following your suggestion...

**Comment by pkuczynski** [comment]
Ignore this comment. Just noticed #4532 :)

**Comment by quantummachina** [comment]
> Had the same problem for Mojave
> In master branch it has been fixed.
> 
> ```shell
> rvm get master
> rvm install 2.5.1
> ```

te mereces lo mejor n_n <3

**Comment by TalayRuk** [comment]
Had the same problem for Mojave 10.14.5 
Run this & it's fixed 
rvm get master
rvm install 2.6.3

Thanks a ton
