### ISSUE TITLE
RVM changes shebangs which break rake/rdoc/ri on TruffleRuby

### ISSUE THREAD

**Issue by eregon** [rvm/rvm#4408]
## Description

RVM changes shebangs which break rake/rdoc/ri on TruffleRuby, because it changes the shebang line from
```
#!/usr/bin/env bash
```
to
```
#!/usr/bin/env truffleruby_executable_hooks
```

The original being https://github.com/oracle/truffleruby/blob/vm-1.0.0-rc2/bin/rake.
TruffleRuby does this so even if somebody ran `truffleruby/bin/rake` without adapting PATH or using a Ruby manager it would still pick truffleruby automatically.

The same happens for `ri` and `rdoc` (they are also broken), but not for `gem`, `irb`, `testrb` (they seem to work fine).

How I can disable these changes to shebangs of RVM for TruffleRuby?
I would like something reliable with no extra wrappers or changes to installed files, as I have no idea what they might break.

cc @mpapis @havenwood 

## Steps to reproduce

```
rvm install truffleruby
rvm use truffleruby
rake --version
```

## Expected behavior

```
rake, version 12.0.0
```

## Actual behavior

```
rake --version
/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin/truffleruby_executable_hooks:15:in `<main>': /home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin/rake:5: `$(' is not allowed as a global variable name (SyntaxError)
zsh: exit 1     rake --version
```

## Environment info

<details>
 <summary>rvm info</summary>
rvm info      

truffleruby-1.0.0-rc2:

  system:
    uname:        "Linux localhost.localdomain 4.13.12-200.fc26.x86_64 #1 SMP Wed Nov 8 16:47:26 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Fedora"
    version:      "26"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 4.4.12(1)-release (x86_64-redhat-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.3.1 (x86_64-redhat-linux-gnu)"
    remote_path:  "fedora/26/x86_64"

  rvm:
    version:      "1.29.3 (master)"
    updated:      "12 hours 49 minutes 47 seconds ago"
    path:         "/home/eregon/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "truffleruby"
    version:      "1.0.0-rc2,"
    date:         "truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]"
    platform:     "x86_64-linux"
    patchlevel:   "truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]"
    full_version: "truffleruby 1.0.0-rc2, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]"

  homes:
    gem:          "/home/eregon/.rvm/gems/truffleruby-1.0.0-rc2"
    ruby:         "/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2"

  binaries:
    ruby:         "/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin/ruby"
    irb:          "/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin/irb"
    gem:          "/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin/gem"
    rake:         "/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin/rake"

  environment:
    PATH:         "/home/eregon/.rvm/gems/truffleruby-1.0.0-rc2/bin:/home/eregon/.rvm/gems/truffleruby-1.0.0-rc2@global/bin:/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin:/home/eregon/.rvm/bin:/home/eregon/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/eregon/code/mx:/home/eregon/code/mspec/bin:/opt/crystal/bin"
    GEM_HOME:     "/home/eregon/.rvm/gems/truffleruby-1.0.0-rc2"
    GEM_PATH:     "/home/eregon/.rvm/gems/truffleruby-1.0.0-rc2:/home/eregon/.rvm/gems/truffleruby-1.0.0-rc2@global"
    MY_RUBY_HOME: "/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2"
    IRBRC:        "/home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
</details>

**Comment by eregon** [comment]
There is actually a fair bit of thought behind this design for our launchers, as documented at https://github.com/oracle/truffleruby/blob/master/doc/contributor/launchers.md, so I don't think we'd want to change the design of our `rake`/`rdoc`/`irb`/etc launchers.

**Comment by eregon** [comment]
PR at https://github.com/rvm/rvm/pull/4409

**Comment by eregon** [comment]
`~/.rvm/rubies/truffleruby-1.0.0-rc2/bin/truffleruby_executable_hooks` contains this:

```ruby
#!/usr/bin/env ruby

title = "ruby #{ARGV*" "}"
$0    = ARGV.shift
Process.setproctitle(title) if Process.methods.include?(:setproctitle)

require 'rubygems'
begin
  require 'executable-hooks/hooks'
  Gem::ExecutableHooks.run($0)
rescue LoadError
  warn "unable to load executable-hooks/hooks" if ENV.key?('ExecutableHooks_DEBUG')
end unless $0.end_with?('/executable-hooks-uninstaller')

eval File.read($0), binding, $0
```

The last line, `eval File.read("bin/rake")` doesn't work for TruffleRuby, because TruffleRuby's `bin/rake` is both an executable bash script and a Ruby executable (see below).

Ruby itself skips until it finds a shebang containing `ruby` when doing `ruby bin/rake`.
This is basically the `-x` flag of MRI, except it also happens automatically when the first shebang doesn't contain `ruby`.

So to make rubygems-bundler work with TruffleRuby, we'd probably need to replicate that logic in the generated `truffleruby_executable_hooks` or in some method of the gem, which is not so nice.
Both `load` and `require` also don't have the behavior to skip until a `ruby` shebang, it seems only the main script has this logic.

Another unfortunate side effect of rubygems-bundler changing the shebang of bin/rake is now it looks like a ruby shebang (`truffleruby_executable_hooks` contains `ruby`), and so even `truffleruby .../bin/rake` doesn't work anymore.

Here is the full unmodified `~/.rvm/rubies/truffleruby-1.0.0-rc2/bin/rake`:
```ruby
#!/usr/bin/env bash
# ignored by Ruby interpreter

# get the absolute path of the executable and resolve symlinks
SELF_PATH=$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")
while [ -h "$SELF_PATH" ]; do
  # 1) cd to directory of the symlink
  # 2) cd to the directory of where the symlink points
  # 3) get the pwd
  # 4) append the basename
  DIR=$(dirname "$SELF_PATH")
  SYM=$(readlink "$SELF_PATH")
  SELF_PATH=$(cd "$DIR" && cd "$(dirname "$SYM")" && pwd)/$(basename "$SYM")
done
exec "$(dirname $SELF_PATH)/ruby" "$SELF_PATH" "$@"

#!ruby
# ^ marks start of Ruby interpretation

#
# This file was generated by RubyGems.
#
# The application 'rake' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY") if str.respond_to? :force_encoding
  if str =~ /\A_(.*)_\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('rake', 'rake', version)
else
gem "rake", version
load Gem.bin_path("rake", "rake", version)
end
```

**Comment by eregon** [comment]
One interesting workaround is, if `rake` is gem installed, and the generated `bin/rake` overwrites the original `bin/rake` then it works fine.

```
$ rvm use truffleruby
$ gem install rubygems-bundler
$ rake --version # => broken as above
bin/rake:5: `$(' is not allowed as a global variable name (SyntaxError)

$ gem install rake
Fetching: rake-12.3.1.gem (100%)
rake's executable "rake" conflicts with /home/eregon/.rvm/rubies/truffleruby-1.0.0-rc2/bin/rake
Overwrite the executable? [yN]  y
Successfully installed rake-12.3.1
1 gem installed

$ rake --version
rake, version 12.3.1
```

This doesn't fix `ri`/`rdoc` though, until a new `rdoc` is installed.

**Comment by eregon** [comment]
I suppose one way to fix this although very hacky would be to remove the Bash preludes of known launchers (rake/rdoc/ri) when installing TruffleRuby in RVM.
Since that installation of TruffleRuby is inside RVM, the right `ruby` binary should be used anyway.

Another way would be to write the Bash code in such a way that it can be executed as Ruby code but has no side effects. This seems challenging, but might be possible.

**Comment by eregon** [comment]
> Another way would be to write the Bash code in such a way that it can be executed as Ruby code but has no side effects. This seems challenging, but might be possible.

@mame found a way to do this, a script that can be executed both as Bash or Ruby code, and allows arbitrary Ruby code and complex Bash code:

```bash
#!/bin/bash

echo "#{<<exit#" > /dev/null

echo "in bash"
exec ruby -x $0 $@

exit
}" if false

#!ruby
puts "in ruby"
p ARGV
```

```ruby
#!/bin/bash

echo "#{<<exit#" > /dev/null

echo "in bash"
exec ruby -x $0 $@

exit
}" if false

#!ruby
puts "in ruby"
p ARGV
```

```
$ ruby -e 'eval File.read "tt"' 1 2 3
in ruby
["1", "2", "3"]

$ bash tt 1 2 3
in bash
in ruby
["1", "2", "3"]
```

If we write TruffleRuby's bin/rake, bin/ri, etc launchers this way then the Bash part should also be executable as Ruby code, which should solve this problem nicely (although in a rather surprising manner).

**Comment by mpapis** [comment]
@eregon I just did this https://github.com/rvm/executable-hooks/blob/ae1b00c51a31f5a994bb60421ef977f1d56d8bb0/bin/ruby_executable_hooks - could you check if that works for you too?

**Comment by eregon** [comment]
https://github.com/rvm/executable-hooks/pull/32 seems to work well.
That's actually easier than I thought, that's a nice and easy solution :smiley: 

I tested by removing `gemsets/truffleruby/global.gems`, reinstalling truffleruby, then `rake --version` fails as expected,
then changing `~/.rvm/gems/truffleruby-1.0.0-rc2@global/gems/executable-hooks-1.4.2/bin/ruby_executable_hooks` to the version in the PR,
and then `gem regenerate_binstubs` + `gem install rubygems-bundler`
and `rake --version` works again.

I only have 1 TruffleRuby spec failing, which is:
```
1)
The launcher 'ri' in `RbConfig::CONFIG['bindir']` directory runs when symlinked FAILED
Expected "linktori 5.0.0\n"
 to match /^ri 5\.0\.0$/

~/code/truffleruby-tests/spec/truffle/launcher_spec.rb:43:in `block (6 levels) in <top (required)>'
~/code/truffleruby-tests/spec/truffle/launcher_spec.rb:39:in `chdir'
~/code/truffleruby-tests/spec/truffle/launcher_spec.rb:39:in `block (5 levels) in <top (required)>'
~/.rvm/rubies/truffleruby-1.0.0-rc2/lib/mri/tmpdir.rb:89:in `mktmpdir'
~/code/truffleruby-tests/spec/truffle/launcher_spec.rb:38:in `block (4 levels) in <top (required)>'
~/code/truffleruby-tests/spec/truffle/launcher_spec.rb:12:in `<top (required)>'
```

So if one does:
```bash
$ ln -s ~/.rvm/rubies/truffleruby-1.0.0-rc2/bin/ri linktori
$ ./linktori --version
linktori 5.0.0
```
`ri` uses `File.basename $0` and [RUBY_ENGINE]_executable_hooks does `$0    = ARGV.shift`.
If instead it did `$0 = File.realpath(ARGV.shift)` or `$0 = File.basename(File.realpath(ARGV.shift))` then this would print `ri 5.0.0` as expected.
This is a small matter, but seems worth fixing separately.

In any case, let's merge https://github.com/rvm/executable-hooks/pull/32 and I think we can revert 45f40f198003b4c5097077f644c4f3bf76690c79 once there is a release of `executable-hooks`.

**Comment by eregon** [comment]
With executable-hooks 1.5.0 [released](https://github.com/rvm/executable-hooks/commit/4b9c4b0ab4512899af4e02ed8fa709016a909edf) and 0233c51c9d8ca9e229833dac5f232b500d3e86e5, this issue can be closed, thank you @mpapis!
