### ISSUE TITLE
1.29.4 makes a breaking change to the syntax for rvm wrapper

### ISSUE THREAD

**Issue by johntoups** [rvm/rvm#4421]
## Description

deployed a new instance today, which automatically generates the wrapper for unicorn via:
rvm wrapper ruby-2.3.0@medaxion unicorn

New instances fail to stand up, as the above command is no longer valid syntax.

This may have been an intentional change, but in my case, all new autoscaling instances began failing on setup, and I would not have expected breaking behavior in a patch release.

## Steps to reproduce

run `rvm wrapper ruby-2.3.0@medaxion unicorn`.  

Obviously with your own gemset and script names.

## Expected behavior

`$rvm wrapper ruby-2.3.0@medaxiont unicorn`
Generating RVM wrappers:
Regenerating ruby-2.3.0@medaxion wrappers........

## Actual behavior

Delivers the help page - syntax no longer appears valid.

rvm wrapper regenerate DOES work.

## Environment info

$ rvm info

ruby-2.3.0@medaxion:

  system:
    uname:        "Linux ip-10-1-22-132 4.4.0-1041-aws #50-Ubuntu SMP Wed Nov 15 22:18:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "16.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/16.04/x86_64"

  rvm:
    version:      "1.29.4 (latest)"
    updated:      "1 hour 44 minutes 12 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.3.0p0"
    date:         "2015-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2015-12-25 revision 53290"
    full_version: "ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.3.0@medaxion"
    ruby:         "/usr/local/rvm/rubies/ruby-2.3.0"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.3.0/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.3.0/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.3.0/bin/gem"
    rake:         "/usr/local/rvm/gems/ruby-2.3.0@medaxion/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.3.0@medaxion/bin:/usr/local/rvm/gems/ruby-2.3.0@global/bin:/usr/local/rvm/rubies/ruby-2.3.0/bin:/usr/local/rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.3.0@medaxion"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.3.0@medaxion:/usr/local/rvm/gems/ruby-2.3.0@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.3.0"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.3.0/.irbrc"
    RUBYOPT:      ""
    gemset:       "medaxion"

**Comment by BrianHawley** [comment]
This is probably the same thing as #4380.

**Comment by kokovoj** [comment]
I am also hitting this. Unfortunately, it breaks when used as part of another gemset:
```rvm ${RUBY_VERSION}@yourgemset do rvm wrapper ${RUBY_VERSION}@yourgemset prefix your_script```
and returns 1
```... returned a non-zero code: 1```.

Till this issue is fixed, I can confirm that 1.29.3 works for me as before
```
#https://github.com/rvm/rvm/issues/4421 1.29.4 broke the rvm wrapper format
#so instead install 1.29.3 (until above ticket is fixed)
#curl -sSL --fail https://get.rvm.io | bash -s stable
curl -sSL --fail https://get.rvm.io | bash -s -- --version 1.29.3
```

Please fix this.

**Comment by Pepan** [comment]
Is doing anyone anything about it? It's still here!

**Comment by pkuczynski** [comment]
It was a big step between 1.29.3 and 1.29.4: https://github.com/rvm/rvm/compare/1.29.3..1.29.4

Any suggestions what could break rvm wrapper?

**Comment by pkuczynski** [comment]
Possibly this is causing you issues: https://github.com/rvm/rvm/pull/4184/files

@mpapis do you want to have a look at it?

**Comment by rivella50** [comment]
So also in 1.29.8 it's still not possible to create a wrapper like this:
```
rvm wrapper RUBY_VERSION@GEMSET WRAPPER_NAME BINARY
```
What to do here? I really need a solution since i have to manage a Rails app via launchd.

**Comment by mpapis** [comment]
@pkuczynski we should have dumped the version to 1.30 with this change ... right now there is not much there should or even can be done in the code, the feature has already 1.5 years.

For now I would suggest using the new way wrappers are working:
```bash
> rvm wrapper show rake # <- with rvm
/home/mpapis/.rvm/gems/ruby-2.5.1/wrappers/rake
> gem wrappers show rake # <- but rvm is not needed for that part
/home/mpapis/.rvm/gems/ruby-2.5.1/wrappers/rake
```
and then you can use that path anywhere as you would have done with previous setup

If there are use cases that the example does not cover let me know and we can think what to do with them.

**Comment by rivella50** [comment]
Thank you! Meanwhile i could solve it by using a shell script.

**Comment by vibro** [comment]
How should one make a wrapper for a gem installed via a gemset? It says [here](https://github.com/rvm/gem-wrappers#generating-wrappers) that all wrappers are created automatically, is this the case for gemsets too?

I'm also running into this issue updating from 1.29.3, as the Puppet rvm module still uses the old syntax for wrappers. How would I go about generating a wrapper for a gemset?

**Comment by swistak** [comment]
I have the same issue. The regressions seems to be pretty major to introduce in PATCH level version.

`rvm wrapper current scope god` works in `1.29.3` but not in a "stable" `1.29.9`

There's also documentation here https://rvm.io/integration/god that does not work now.

**Comment by pkuczynski** [comment]
@swistak would you be keen to provide a PR with a fix?
