### ISSUE TITLE
Unable to pass SIGINT signal (control-C) on 1.29.4

### ISSUE THREAD

**Issue by rdunlop** [rvm/rvm#4422]
## Description

After installing 1.29.4, when I log in to a bash shell, (and it runs the rvmrc), I cannot press control-C to have it clear the current line of shell code. It appears that signals are being trapped, and not making it to bash.

On 1.29.3, this was working.
I installed rvm from https://github.com/Wasapl/rvm/commit/22945f8abfb2cf01354d12d977c7f9ad60e15d32 (which is really just the same as 1.29.4, without https://github.com/rvm/rvm/pull/4417), and the behavior started working again.

(I used `rvm get branch add-default-gem-bundler --source github.com/Wasapl/rvm` to install this branch)

## Steps to reproduce

- When we log into our AWS linux boxes, it doesn't work.
- Strangely, on our mac os x developer laptops, it still works fine. (I don't know why)

## Expected behavior

- pressing control-c should clear the current command
- when running a `tail -f <file>`, pressing control-C should stop the tail

## Actual behavior

- the shell is not cleared,
- the tail is not stopped

## Environment info

```
$ rvm info

ruby-2.5.1:

  system:
    uname:        "Linux <redacted> 4.14.33-51.34.amzn1.x86_64 #1 SMP Fri Apr 13 18:18:26 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Amazon"
    version:      "2017.09"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "amazon/2017.09/x86_64"

  rvm:
    version:      "1.29.4 (latest)"
    updated:      "3 days 8 hours 15 minutes 14 seconds ago"
    path:         "/home/badges/.rvm"
    autolibs:     "[disable] Limit RVM automation as much as possible."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.1p57"
    date:         "2018-03-29"
    platform:     "x86_64-linux"
    patchlevel:   "2018-03-29 revision 63029"
    full_version: "ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]"

  homes:
    gem:          "/home/badges/.rvm/gems/ruby-2.5.1"
    ruby:         "/home/badges/.rvm/rubies/ruby-2.5.1"

  binaries:
    ruby:         "/home/badges/.rvm/rubies/ruby-2.5.1/bin/ruby"
    irb:          "/home/badges/.rvm/rubies/ruby-2.5.1/bin/irb"
    gem:          "/home/badges/.rvm/rubies/ruby-2.5.1/bin/gem"
    rake:         "/home/badges/.rvm/gems/ruby-2.5.1@global/bin/rake"

  environment:
    PATH:         "/home/badges/.rvm/gems/ruby-2.5.1/bin:/home/badges/.rvm/gems/ruby-2.5.1@global/bin:/home/badges/.rvm/rubies/ruby-2.5.1/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/aws/bin:/home/badges/.rvm/bin:/home/badges/.local/bin:/home/badges/bin"
    GEM_HOME:     "/home/badges/.rvm/gems/ruby-2.5.1"
    GEM_PATH:     "/home/badges/.rvm/gems/ruby-2.5.1:/home/badges/.rvm/gems/ruby-2.5.1@global"
    MY_RUBY_HOME: "/home/badges/.rvm/rubies/ruby-2.5.1"
    IRBRC:        "/home/badges/.rvm/rubies/ruby-2.5.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

Note, my local (working) install is:
```
 rvm info

ruby-2.3.7@push:

  system:
    uname:        "Darwin Robins-MacBook-Pro.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.4 (latest)"
    updated:      "2 minutes 54 seconds ago"
    path:         "/Users/robindunlop/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.3.7p456"
    date:         "2018-03-28"
    platform:     "x86_64-darwin17"
    patchlevel:   "2018-03-28 revision 63024"
    full_version: "ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin17]"

  homes:
    gem:          "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push"
    ruby:         "/Users/robindunlop/.rvm/rubies/ruby-2.3.7"

  binaries:
    ruby:         "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin/ruby"
    irb:          "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin/irb"
    gem:          "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin/gem"
    rake:         "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push/bin/rake"

  environment:
    PATH:         "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push/bin:/Users/robindunlop/.rvm/gems/ruby-2.3.7@global/bin:/Users/robindunlop/.rvm/rubies/ruby-2.3.7/bin:/Users/robindunlop/.rvm/bin:/usr/local/heroku/bin:/Users/robindunlop/.bin:.git/safe/../../bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/MacGPG2/bin:/opt/X11/bin"
    GEM_HOME:     "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push"
    GEM_PATH:     "/Users/robindunlop/.rvm/gems/ruby-2.3.7@push:/Users/robindunlop/.rvm/gems/ruby-2.3.7@global"
    MY_RUBY_HOME: "/Users/robindunlop/.rvm/rubies/ruby-2.3.7"
    IRBRC:        "/Users/robindunlop/.rvm/rubies/ruby-2.3.7/.irbrc"
    RUBYOPT:      ""
    gemset:       "push"
```

**Comment by rfpronk** [comment]
We have the same problem with #4417 on our Debian machines.

**Comment by fabiendelpierre** [comment]
Noticed the same problem in our AWS AMI builds using RVM 1.29.4. Interestingly, if you SSH into a box and press Ctrl-C, it doesn't work, as described here. If you start a new shell within your current shell by typing `bash`, and then do Ctrl-C, it works normally. Within that same shell-in-a-shell, do a `tail -f` on any file, and then you can't exit `tail` with Ctrl-C.

**Comment by WilliamMcCumstie** [comment]
Looks like the same issue on `Centos7` running in a vagrant machine. The bug seems to be associated with the `~/rvm/scripts/rvm` but can not be replicated by sourcing the file directly:
```
$ vagrant ssh
Last login: Mon Jul  9 11:30:13 2018 from 10.0.2.2
[vagrant@master ~]$ trap
trap -- '' SIGINT
trap -- '' SIGQUIT
trap -- '' SIGTSTP
trap -- '' SIGTTIN
trap -- '' SIGTTOU
[vagrant@master ~]$ trap - int
[vagrant@master ~]$ trap - quit
[vagrant@master ~]$ trap
trap -- '' SIGTSTP
trap -- '' SIGTTIN
trap -- '' SIGTTOU
[vagrant@master ~]$ source ~/.profile 
[vagrant@master ~]$ source ~/.rvm/scripts/rvm
[vagrant@master ~]$ trap
trap -- '' SIGTSTP
trap -- '' SIGTTIN
trap -- '' SIGTTOU
[vagrant@master ~]$
```

**Comment by charlietag** [comment]
I saw this...
https://github.com/rvm/rvm/blob/master/scripts/functions/utility_logging#L140

**Comment by charlietag** [comment]
Solution found: I solve my ctrl+c problem these ways.
1. modify source code
https://github.com/rvm/rvm/blob/master/scripts/functions/environment#L215
add "trap >/dev/null" as the following
<pre>
trap >/dev/null
_rvm_old_traps=$( __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM' <(trap) )
</pre>

2. workaround and wait rvm stable version to be fixed
remove trap in .bashrc
<pre>
export PATH="$PATH:$HOME/.rvm/bin"
trap >/dev/null
trap - INT QUIT
trap >/dev/null
</pre>

**Comment by phoolish** [comment]
Any thoughts from @Wasapl or @mpapis?

**Comment by prioux** [comment]
This bug happens on any plain centos; it's easy to verify, after loading rvm's stable release 1.29.4 one can just try in the shell to type this:

```
sleep 4
```

and then try to interrupt it with CTRL-C.

**Comment by charlietag** [comment]
@prioux 
I'm also using CentOS. Isn't this help you?
https://github.com/rvm/rvm/issues/4422#issuecomment-404705599

I'm now modify source code everytime rvm get stable.
`<home>/.rvm/scripts/functions/environment`



There's a PR waiting.  I think it would be fixed next version.
https://github.com/rvm/rvm/pull/4428

**Comment by prioux** [comment]
Actually I really only need one statement to fix it all:

```
trap - INT QUIT
```

**Comment by Wasapl** [comment]
Guys, I'm sorry I tested https://github.com/Wasapl/rvm/commit/22945f8abfb2cf01354d12d977c7f9ad60e15d32 on Ubuntu 16 with bash version 4.3 only.
I managed to reproduce this bug on Amazon AMI. Also, I reproduced fix https://github.com/rvm/rvm/pull/4428. Though I have questions regarding it.

**Comment by charlietag** [comment]
@prioux  But if you put it into .bashrc.  It will work for temporarily.  Next time you hit command 'rvm' .  It will source environment file.  And trap Ctrl-C is back...  That's why I hacked source code.   Otherwise you put this trap command into PS1 prompt...

**Comment by prioux** [comment]
@Wasapl There's only one trap command needed, it's the one above: `trap - INT QUIT` ; it just resets the shell's interrupt handlers for SIGINT and SIGQUIT to the default behavior. I think rvm was supposed to do this in its teardown but instead it leaves some handlers active permanently.

**Comment by prioux** [comment]
@charlietag I haven't been able to get the bug to re-manifest itself by using the 'rvm' function... That is, this works:

```
unix> sleep 4 # with rvm bug
^C^C^C^C^C
unix> trap - INT QUIT
unix> sleep 4 # now works fine
^C
unix> rvm info
(blah blah)
unix> sleep 4 # still works fine
```

**Comment by prioux** [comment]
@charlietag It works for me in my .bashrc ... no need to type it in manually. Not sure why it doesn't work for you. I put it just after the `source` statement for rvm.

**Comment by charlietag** [comment]
@prioux 
I've tried again.
It is not actually OK.
trap will go back when you chdir to other folder.

Could you please try to make a folder , and then go in , and go out

after setup .bashrc .bash_profile (trap - INT QUIT)
<pre>
Ctrl -C ---> OK
mkdir test_folder
Ctrl -C ---> OK
cd test_folder
Ctrl -C ---> sometimes ok, sometimes failed
echo "2.5.1" > .ruby-version
cd ..
cd test_folder
Ctrl -C ---> I almost fail at this step...
</pre>

**Comment by Wasapl** [comment]
@charlietag you're absolutely right. When you source RVM (usually in your `.bashrc` or `.profile` file) RVM replace commands `cd`, `popd`, `pushd` with it's own functions. During execution of those functions, RVM set some traps and then clear them with `trap - EXIT HUP INT QUIT TERM`. So it sets trap for signals EXIT HUP INT QUIT TERM and clears them every time you change directory!
To see how it works you can execute `set -x` and then `cd /`. Also, you may run `type cd`, `type pushd` or `type popd` (in bash >=4.2.46) to check did RVM replaced those builtin commands with its own functions or not.
I believe that the difference between @charlietag 's and @prioux 's experiences is in bash versions they use.

**Comment by charlietag** [comment]
@Wasapl 
Thanks for your explanation .   
I've learned a lot from this.

**Comment by mpapis** [comment]
the fix is on master

**Comment by akofink** [comment]
Is this issue not important enough to fix on stable? It's been broken for months, and we've had to change our automation to use head. :/

**Comment by my1free** [comment]
> @prioux
> I've tried again.
> It is not actually OK.
> trap will go back when you chdir to other folder.
> 
> Could you please try to make a folder , and then go in , and go out
> 
> after setup .bashrc .bash_profile (trap - INT QUIT)
> 
> Ctrl -C ---> OK
> mkdir test_folder
> Ctrl -C ---> OK
> cd test_folder
> Ctrl -C ---> sometimes ok, sometimes failed
> echo "2.5.1" > .ruby-version
> cd ..
> cd test_folder
> Ctrl -C ---> I almost fail at this step...

I have the same problem. whenever I change the folder, 'TRAP -- SIGINT' will come back

**Comment by BarnacleBob** [comment]
Here is a workaround that prevents it from coming back when you cd or run rvm.  Although im not sure if it will interfere with proper operation of rvm.

```
alias trap=true
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
unalias trap
```

**Comment by Gareth-Y** [comment]
I have the same problem.
I solved this problem by lowering the version
`$ rvm get 1.29.3`

**Comment by hppkus** [comment]
> I have the same problem.
> I solved this problem by lowering the version
> `$ rvm get 1.29.3`

this solve my problem too

**Comment by cruxcoder** [comment]
> > I have the same problem.
> > I solved this problem by lowering the version
> > `$ rvm get 1.29.3`
> 
> this solve my problem too

Me too, was on rvm 1.29.4 using Centos 7, took a while to isolate to an rvm issue and not Centos issue :|

**Comment by libp** [comment]
> My env: CentOS7 using bash
> 
> Solution found: I solve my ctrl+c problem these ways.
> 
> 1. modify source code (preferred)
>    https://github.com/rvm/rvm/blob/master/scripts/functions/environment#L215
>    add "trap >/dev/null" as the following
>    `<home>/.rvm/scripts/functions/environment`
> 
> trap >/dev/null
> _rvm_old_traps=$( trap | __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM' )
> trap >/dev/null
> 1. Workaround and wait rvm stable version to be fixed (Bad, still get issues, everytime check into rails app directory)
>    remove trap in .bash_profile
> 
> [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
> 
> trap >/dev/null
> trap - INT QUIT
> trap >/dev/null
> 
> alias rvm='trap >/dev/null; trap - INT QUIT; trap >/dev/null ; rvm'

thank you  this solve my problem too

**Comment by libp** [comment]
but when i change another sesession,the same problem occured again

**Comment by libp** [comment]
> > > I have the same problem.
> > > I solved this problem by lowering the version
> > > `$ rvm get 1.29.3`
> > 
> > 
> > this solve my problem too
> 
> Me too, was on rvm 1.29.4 using Centos 7, took a while to isolate to an rvm issue and not Centos issue :|

Me too

**Comment by dongli** [comment]
This error is really nasty, I have tracked down to rvm for a long time, all my crew are complaining it.

**Comment by stbenjam** [comment]
Is there a plan to update RVM stable with a fix for this?

**Comment by WoolenWang** [comment]
get the same issue when use 1.29.4 .... pls get 1.29.5 to stable release as son as possible

**Comment by w7374520** [comment]
> I have the same problem.
> I solved this problem by lowering the version
> `$ rvm get 1.29.3`

me too! goode

**Comment by gvganesh01** [comment]
I have same issue CTRL +C not working.
I updated to latest rvm 
$rvm get master
which is  1.29.7-next.
Worked after moving from 1.29.4 to 1.29.7-next

**Comment by Zhang21** [comment]
`rvm get head`

<br>

links: <https://www.v2ex.com/t/489138>
