### ISSUE TITLE
rvm install ruby-2.3.4 Error running '__rvm_make -j4',

### ISSUE THREAD

**Issue by Xyko** [rvm/rvm#4424]
## Description

Can't get ruby 2.3.4 with RVM on Linux Mint Tara (Ubuntu 18.04 LTS based)

## Steps to reproduce

rvm install ruby-2.3.4
ruby-2.3.4 - #removing src/ruby-2.3.4..
Searching for binary rubies, this might take some time.
No binary rubies available for: mint/19/x86_64/ruby-2.3.4.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for mint.
Installing requirements for mint.
Updating system..francisco password required for 'apt-get --quiet --yes update': 
..
Installing required packages: libreadline6-dev...
Requirements installation successful.
Installing Ruby from source to: /home/francisco/.rvm/rubies/ruby-2.3.4, this may take a while depending on your cpu(s)...
ruby-2.3.4 - #downloading ruby-2.3.4, this may take a while depending on your connection...
ruby-2.3.4 - #extracting ruby-2.3.4 to /home/francisco/.rvm/src/ruby-2.3.4.....
ruby-2.3.4 - #applying patch /home/francisco/.rvm/patches/ruby/ruby_2_3_gcc7.patch.
ruby-2.3.4 - #applying patch /home/francisco/.rvm/patches/ruby/2.3.4/fix_rb_thread_fd_close.patch.
ruby-2.3.4 - #applying patch /home/francisco/.rvm/patches/ruby/2.3.4/random_c_using_NR_prefix.patch.
ruby-2.3.4 - #configuring..........................................................
ruby-2.3.4 - #post-configuration..
ruby-2.3.4 - #compiling..................................................................................................................................-
Error running '__rvm_make -j4',
please read /home/francisco/.rvm/log/1531056099_ruby-2.3.4/make.log
There has been an error while running make. Halting the installation.

## Expected behavior

Getting operational ruby 2.3.4

## Actual behavior

[make.log](https://github.com/rvm/rvm/files/2173771/make.log)

Obs.: The solution posted in (https://github.com/rvm/rvm/issues/4407) dont work.  The error persist after this steps....

## Environment info

ruby-2.4.1:

  system:
    uname:        "Linux francisco-Latitude-7480 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Mint"
    version:      "19"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.4.2 (x86_64-ubuntu-linux-gnu)"
    remote_path:  "mint/19/x86_64"

  rvm:
    version:      "1.29.4 (master)"
    updated:      "17 hours 23 minutes 54 seconds ago"
    path:         "/home/francisco/.rvm"
    autolibs:     "[packages] Allow RVM to use package manager if found, install missing dependencies."

  ruby:
    interpreter:  "ruby"
    version:      "2.4.1p111"
    date:         "2017-03-22"
    platform:     "x86_64-linux"
    patchlevel:   "2017-03-22 revision 58053"
    full_version: "ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]"

  homes:
    gem:          "/home/francisco/.rvm/gems/ruby-2.4.1"
    ruby:         "/home/francisco/.rvm/rubies/ruby-2.4.1"

  binaries:
    ruby:         "/home/francisco/.rvm/rubies/ruby-2.4.1/bin/ruby"
    irb:          "/home/francisco/.rvm/rubies/ruby-2.4.1/bin/irb"
    gem:          "/home/francisco/.rvm/rubies/ruby-2.4.1/bin/gem"
    rake:         "/home/francisco/.rvm/gems/ruby-2.4.1@global/bin/rake"

  environment:
    PATH:         "/home/francisco/.rvm/gems/ruby-2.4.1/bin:/home/francisco/.rvm/gems/ruby-2.4.1@global/bin:/home/francisco/.rvm/rubies/ruby-2.4.1/bin:/home/francisco/bin:/home/francisco/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/home/francisco/.rvm/bin:/home/francisco/.rvm/bin"
    GEM_HOME:     "/home/francisco/.rvm/gems/ruby-2.4.1"
    GEM_PATH:     "/home/francisco/.rvm/gems/ruby-2.4.1:/home/francisco/.rvm/gems/ruby-2.4.1@global"
    MY_RUBY_HOME: "/home/francisco/.rvm/rubies/ruby-2.4.1"
    IRBRC:        "/home/francisco/.rvm/rubies/ruby-2.4.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by Xyko** [comment]
Folks,
I succeeded by doing this:
            **apt purge libssl-dev** && **apt install libssl1.0-dev**... 
After that the 'rvm install 2.3.5' works fine
**Obs.:** I tried before doing the same installation in a ubuntu 18.04 and the command 'rvm install 2.3.5' works fine too!  
Is not the Tara version the same as ububtu 18.04? I'm afraid there will be other differences......

**Comment by danielpclark** [comment]
I can confirm that the 1.29.4 version of RVM fixed this with the libssl dev switching.  I couldn't install Ruby 2.3.7 before but with the RVM upgrade it now works.

**Comment by feliarana** [comment]
Hi, I had a similar problem with LM 19 Tara edition. This solution helped me:

`$ rvm pkg install openssl
$ rvm remove x.x.x
$ rvm install x.x.x -C --with-openssl-dir=$HOME/.rvm/usr`

**Comment by brohit-97** [comment]
I had a similar problem and resolved it by
`export warnflags=-Wno-error=implicit-function-declaration`
`export optflags="-w"`
`rvm install "ruby-2.6.3" --with-out-ext=fiddle`

**Comment by trinitronx** [comment]
Looks like this one was fixed! :tada:

Closing as fixed, also due to Ruby `2.3.4` being [End of Life (EoL) as of 31 Mar 2020][1]

I'm closing this, to clean up some old issues that are against unsupported OS & ruby versions.

[1]: https://endoflife.date/ruby
