### ISSUE TITLE
Unable to install to /usr/local

### ISSUE THREAD

**Issue by chrisjcha** [rvm/rvm#4429]
## Description

I'm unable to install RVM even after adding "sudo" before bash, it still installs to the home directory:
$  \curl -L get.rvm.io | sudo bash -s stable

Upgrading the RVM installation in /home/ec2-user/.rvm/
Upgrade of RVM in /home/ec2-user/.rvm/ is complete.

## Steps to reproduce

 1.  \curl -L get.rvm.io | sudo bash -s stable

## Expected behavior

rvm should install in /usr/local

## Actual behavior
rvm is only installed to the home directory.

Downloading https://github.com/rvm/rvm/archive/1.29.4.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.4/1.29.4.tar.gz.asc
gpg: Signature made Sun 01 Jul 2018 03:41:26 PM EDT using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg:                 aka "Michal Papis <michal.papis@toptal.com>"
gpg:                 aka "[jpeg image of size 5015]"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/home/ec2-user/.rvm/archives/rvm-1.29.4.tgz'
Installing RVM to /home/ec2-user/.rvm/
Installation of RVM in /home/ec2-user/.rvm/ is almost complete:

## Environment info

system:

  system:
    uname:        "Linux ip-10-100-199-17.usdcag.aws.ray.com 3.10.0-514.el7.x86_64 #1 SMP Wed Oct 19 11:24:13 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "CentOS"
    version:      "7"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "centos/7/x86_64"

  rvm:
    version:      "1.29.4 (latest)"
    updated:      "13 minutes 22 seconds ago"
    path:         "/home/ec2-user/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/local/bin/ruby"
    irb:          "/usr/local/bin/irb"
    gem:          "/usr/local/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by pkuczynski** [comment]
Why do you think it should install to `/usr/local`?

**Comment by chrisjcha** [comment]
Wow 5 months ago!

**Comment by pkuczynski** [comment]
Well, we only a bunch of volunteers working for free. You welcome to join us and send PR :)

**Comment by chrisjcha** [comment]
Understood, thanks for your work.

**Comment by pkuczynski** [comment]
[Become a backer](https://opencollective.com/rvm#backer) and support us with a small donation to help us continue our activities :)
