### ISSUE TITLE
RVM Requirements error on Linux Mint 19

### ISSUE THREAD

**Issue by hermonjay** [rvm/rvm#4433]
I run following instruction in order to install Ruby on Rails on my Linux Mint 19:
`sudo apt-get install curl`
` \curl -sSL https://get.rvm.io | bash -s stable --ruby`

Then I got this error:
>Downloading https://github.com/rvm/rvm/archive/1.29.4.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.4/1.29.4.tar.gz.asc
gpg: Signature made Mon 02 Jul 2018 02:41:26 AM WIB
gpg:                using RSA key 62C9E5F4DA300D94AC36166BE206C29FBF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [unknown]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [unknown]
gpg:                 aka "[jpeg image of size 5015]" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/home/hermonjay/.rvm/archives/rvm-1.29.4.tgz'
Upgrading the RVM installation in /home/hermonjay/.rvm/
    RVM PATH line found in /home/hermonjay/.mkshrc /home/hermonjay/.profile /home/hermonjay/.bashrc /home/hermonjay/.zshrc.
    RVM sourcing line found in /home/hermonjay/.profile /home/hermonjay/.bash_profile /home/hermonjay/.zlogin.
Upgrade of RVM in /home/hermonjay/.rvm/ is complete.
No new notes to display.
Ruby enVironment Manager 1.29.4 (latest) (c) 2009-2017 Michal Papis, Piotr Kuczynski, Wayne E. Seguin
Searching for binary rubies, this might take some time.
No binary rubies available for: mint/19/x86_64/ruby-2.5.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for mint.
Installing requirements for mint.
Updating system....
Installing required packages: g++, autoconf, automake, libc6-dev, libffi-dev, libgdbm-dev, libncurses5-dev, libsqlite3-dev, libtool, libyaml-dev, sqlite3, zlib1g-dev, libgmp-dev, libreadline6-dev, libssl-dev.....
Error running 'requirements_debian_libs_install g++ autoconf automake libc6-dev libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev sqlite3 zlib1g-dev libgmp-dev libreadline6-dev libssl-dev',
please read /home/hermonjay/.rvm/log/1532170396_ruby-2.5.1/package_install_g++_autoconf_automake_libc6-dev_libffi-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_sqlite3_zlib1g-dev_libgmp-dev_libreadline6-dev_libssl-dev.log
Requirements installation failed with status: 100.

How to overcome this?

**Comment by otavioschwanck** [comment]
1 - Make a backup of your /etc/lsb-release:
sudo cp /etc/lsb-release /etc/lsb-release-mint

2 - edit your /etc/lsb-release:
sudo xed /etc/lsb-release

Change the content of file to:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Linux Mint 19 Tara"

Save.

3 - run rvm requirements.

4 - After installing all you need, bring back the mint lsb-release:
sudo rm /etc/lsb-release
sudo mv /etc/lsb-release-mint /etc/lsb-release

**Comment by pkuczynski** [comment]
Seems that we do not know how to install dependencies for your version of OS. You should post the content of the log listed in the output: `please read /home/hermonjay/.rvm/log/1532170396_ruby-2.5.1/package_install_g++_autoconf_automake_libc6-dev_libffi-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_sqlite3_zlib1g-dev_libgmp-dev_libreadline6-dev_libssl-dev.log` - and then I could try to figure out which package failed to install.

**Comment by pkuczynski** [comment]
Could u also please post content of `rvm info`?

**Comment by pkuczynski** [comment]
Just tested with latest RVM and Mint 19. All works. So without your logs I am blind...

**Comment by pkuczynski** [comment]
Thanks @digitalsparky! I prepared a fix by changing `libreadline6-dev` to `libreadline6-dev`. Can you do:

```
rvm get branch fix-mint-19
```

And then try installing again (using original `lsb-release` file)?

**Comment by digitalsparky** [comment]
Looks like that worked without incident @pkuczynski :)

**Comment by pkuczynski** [comment]
Awesome! :)

**Comment by pkuczynski** [comment]
We just released a new version 1.29.7 fixing this issue.

[Become a backer](https://opencollective.com/rvm#backer) and support us with a small donation to help us continue our activities. Thank you if you already one! 🙏
