### ISSUE TITLE
`use of undeclared identifier` when compiling Ruby 2.5.1 for i686 on latest macOS

### ISSUE THREAD

**Issue by s1gtrap** [rvm/rvm#4437]
## Description

Compiling Ruby 2.5.1 with `--with-arch=i686` on the latest macOS High Sierra (x86_64) causes a `use of undeclared identifier 'username_completion_function'` error in `readline.c`.

## Steps to reproduce

 1. `rvm install 2.5.1 --with-arch=i686`

## Expected behavior

Successful compilation, like when compiling with default settings or `--with-arch=x86_64`.

## Actual behavior

* [command](https://gist.github.com/0xbrt/92cc5083e2bdec8b44ef093e0bc1e9ad)
* [config.log](https://gist.github.com/0xbrt/5fc58e4af5abaa242151c1c371c3dfa2)
* [make.log](https://gist.github.com/0xbrt/30797a88c709e56abbc57969563b2221)

## Environment info

```

system:

  system:
    uname:        "Darwin stained.armpits 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/usr/local/bin/zsh => zsh 5.5.1 (x86_64-apple-darwin17.5.0)"
    remote_path:  "osx/10.13/x86_64"

  rvm:
    version:      "1.29.4 (master)"
    updated:      "39 minutes 22 seconds ago"
    path:         "/Users/brt/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/Users/brt/.nvm/versions/node/v9.3.0/bin:/Users/brt/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/brt/Library/Android/sdk/tools:/Users/brt/Library/Android/sdk/platform-tools:/usr/local/opt/go/libexec/bin:/Users/brt/Desktop/Work/Go/bin:/Users/brt/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""


```

**Comment by trinitronx** [comment]
Looks like logs from Gist are gone (all URLs return `404` errors).  Also this old issue is from 2018 on macOS High Sierra (`10.13`), which was [End of Life (EoL) on 01 Dec 2020][1].

Closing to clean up old issues. If you're still having problems with `rvm get master` on a supported OS, then feel free to open a new issue.

[1]: https://endoflife.date/macos
