### ISSUE TITLE
e@123

### ISSUE THREAD

**Issue by kuldipsi** [rvm/rvm#4446]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by raelgc** [comment]
If you want to open an issue, please provide all required info, starting by a short-but-clear title.
