### ISSUE TITLE
GPG signature verification failed

### ISSUE THREAD

**Issue by 42footPaul** [rvm/rvm#4457]
Pauls-MacBook-Pro:~ paulcottrell$ gpg --version
gpg (GnuPG) 2.2.10
libgcrypt 1.8.3
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /Users/paulcottrell/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
Pauls-MacBook-Pro:~ paulcottrell$ gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 # mpapis@gmail.com
gpg: key 3804BB82D39DC0E3: 98 signatures not checked due to missing keys
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

Pauls-MacBook-Pro:~ paulcottrell$ \curl https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24361  100 24361    0     0   106k      0 --:--:-- --:--:-- --:--:--  106k
Downloading https://github.com/rvm/rvm/archive/1.29.4.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.4/1.29.4.tar.gz.asc
gpg: Signature made Sun Jul  1 15:41:26 2018 EDT
gpg:                using RSA key 62C9E5F4DA300D94AC36166BE206C29FBF04FF17

gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>" [ultimate]
gpg:                 aka "Michal Papis <michal.papis@toptal.com>" [ultimate]
gpg:                 aka "[jpeg image of size 5015]" [ultimate]

Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/Users/paulcottrell/.rvm/archives/rvm-1.29.4.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.4/1.29.4.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

I'ver tried everything that everyone has mentioned on this subject to no avail.

**Comment by errodr** [comment]
Have the same error, this worked for me:

`gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

**Comment by pkuczynski** [comment]
Yes, this is described in the docs on http://rvm.io

**Comment by nykc** [comment]
This is still failing

**Comment by AnthonyDugarte** [comment]
> This is still failing
> ![Screen Shot 2019-09-27 at 10 42 10 AM](https://user-images.githubusercontent.com/815788/65778193-809e5880-e113-11e9-981d-1a2e04eb04cf.png)

This one worked for me:

`sudo gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

**Comment by PhillipMwaniki** [comment]
The keyserver is still failing. I've tried the tricks above, but all I get it this error:
`gpg: keyserver receive failed: No such file or directory`

**Comment by frankpengau** [comment]
Not sure my response from a year ago is still valid but worth a shot if you're stuck: https://github.com/rvm/rvm/issues/5144#issuecomment-1371606075

**Comment by PhillipMwaniki** [comment]
Hey, it didn't work.

**Comment by frankpengau** [comment]
Maybe try the new ones listed in rvm security page? 

https://rvm.io/rvm/security


Otherwise, I'm probably not too sure.
