### ISSUE TITLE
Loading rvm script with set -e fails

### ISSUE THREAD

**Issue by lwoggardner** [rvm/rvm#4465]
## Description

loading rvm script under set -e fails

I'm still trying to work out whether loading the rvm script under set -e is expected or not, but it used to work and now it doesn't.

Pretty sure introduced by this commit that added trap handling.
https://github.com/rvm/rvm/commit/3d9b93b3ce1a0651c3c7cc23193957f619f65fd9

## Steps to reproduce

 1. Amazon Linux with RVM installed to /usr/local/rvm
 2. test.sh
```bash
#!/bin/bash`
set -e
source /usr/local/rvm/scripts/rvm
```
 3. `./test.sh && echo "Success"`

## Expected behavior

./test.sh should return zero

## Actual behavior
non zero return code.

With set-x following are final lines before abort
```
+++ __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM'
+++ GREP_OPTIONS=
+++ command grep -E 'EXIT|HUP|INT|QUIT|TERM'
+++ grep -E 'EXIT|HUP|INT|QUIT|TERM'
+++ trap
+++ return 1
++ _rvm_old_traps=
```

ie the grep does not match the trap output, and that pipeline returns non zero, so with set -e aborts.

## Environment info

```
system:

  system:
    uname:        "Linux ip-10-xx-xx-xx 4.14.62-65.117.amzn1.x86_64 #1 SMP Fri Aug 10 20:03:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Amazon"
    version:      "2018.03"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "amazon/2018.03/x86_64"

  rvm:
    version:      "1.29.4 (master)"
    updated:      "30 days 11 hours 21 minutes 45 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         ""

  environment:
    PATH:         "/usr/local/bin:/bin:/usr/bin:/opt/aws/bin:/usr/local/rvm/bin:/home/ec2-user/.local/bin:/home/ec2-user/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by lwoggardner** [comment]
I don't have an environment to create a PR right now, but I think the fix is in /scripts/functions/environment.

```
215c215
<     _rvm_old_traps=$( trap | __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM' )
---
>     _rvm_old_traps=$( trap | __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM' || true )
```

**Comment by anjannath** [comment]
I am also facing this issue when sourcing `~/.profile` from a script which has `set -e`.
Running it on a centos box.

**Comment by disfluxly** [comment]
I am also facing this exact issue and traced it back to the spot that @lwoggardner found. Are there any plans to update this for an upcoming release?

**Comment by pkuczynski** [comment]
Would `_rvm_old_traps=$( trap | __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM' || true )` fix the issue?

**Comment by pkuczynski** [comment]
@lwoggardner, @disfluxly and @anjannath could you please try the same after `rvm get branch /trap-set-e`?
