### ISSUE TITLE
Add support for ruby 2.3.8, 2.4.5, 2.5.2

### ISSUE THREAD

**Issue by em77** [rvm/rvm#4471]
Three new ruby versions have been released:

https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-3-8-released/
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-4-5-released/
https://www.ruby-lang.org/en/news/2018/10/17/ruby-2-5-2-released/

**Comment by havenwood** [comment]
Closed by 398beb1785593e506cb16773480f971393b01f17.
