### ISSUE TITLE
Add support for ruby 2.5.3

### ISSUE THREAD

**Issue by em77** [rvm/rvm#4473]
Ruby 2.5.3 has been released:

https://www.ruby-lang.org/en/news/2018/10/18/ruby-2-5-3-released/

**Comment by solutus** [comment]
@havenwood, is it possible to release new stable version with ruby 2.5.3? Or is it better do not wait and to update it from master?

**Comment by em77** [comment]
This new version is fixing two CVEs and the Ruby core team recommends everyone upgrading immediately because of that so a new release that includes the merged support would be great.

**Comment by havenwood** [comment]
@solutus I'd suggest going ahead and updating from master.

A release sounds good to me.

**Comment by pkuczynski** [comment]
We just released a new version 1.29.7 fixing this issue.

[Become a backer](https://opencollective.com/rvm#backer) and support us with a small donation to help us continue our activities. Thank you if you already one! 🙏
