### ISSUE TITLE
RVM tries to use bzip2 on a .tar.gz archive

### ISSUE THREAD

**Issue by eregon** [rvm/rvm#4497]
## Description

I'm trying to make `truffleruby` work out of the box on TravisCI (see https://github.com/travis-ci/travis-ci/issues/9803).

When using
```yaml
rvm:
- truffleruby
```
in the `.travis.yml`, TravisCI runs (as shown [here](https://travis-ci.org/eregon/mspec/jobs/451587790)):
```
rvm use truffleruby --install --binary --fuzzy
```
This unfortunately fails, even though both `rvm install truffleruby` works (at least it does locally).

At some point, RVM downloads the .tar.gz as a .tar.bz2 which later results in using the wrong decompression method.
The full log is shown in https://travis-ci.org/eregon/mspec/jobs/451690277

@mpapis @havenwood @pkuczynski Could one of you try to figure out what goes wrong here and fix it?

**Comment by pkuczynski** [comment]
Why do you run with `--fuzzy` instead of `rvm install truffleruby` with autolibs enabled?

**Comment by eregon** [comment]
@pkuczynski it's what TravisCI does (see the link above), I don't know the reason.
We could maybe change it in TravisCI but I guess this should work regardless.

**Comment by eregon** [comment]
`--binary` is what seems to make it fail.
`rvm install truffleruby --debug --binary --fuzzy` also fails the [same way](https://travis-ci.org/eregon/mspec/jobs/453747021) onn TravisCI.
`rvm install truffleruby --debug --fuzzy` OTOH seems to [work fine](https://travis-ci.org/eregon/mspec/jobs/453747670).

@havenwood Maybe it's related to #4456? The log seems to show it doesn't check `__list_remote_all0`.

**Comment by eregon** [comment]
No longer an issue with #4708, closing.
