### ISSUE TITLE
rvm-installer stable (1.29.5) fails on GPG signature verification

### ISSUE THREAD

**Issue by rnitschelm** [rvm/rvm#4518]
## Description

Getting the latest stable version (1.29.5) of rvm does not work, since the GPG signature verification fails.

## Steps to reproduce

 1. `gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3`
 2. `./rvm-installer stable`

## Expected behavior

Rvm being installed.

## Actual behavior

```
Downloading https://github.com/rvm/rvm/archive/1.29.5.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.5/1.29.5.tar.gz.asc
gpg: Signature made Wed Dec 12 12:25:22 2018 CET
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/Users/rogier/.rvm/archives/rvm-1.29.5.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.5/1.29.5.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.
```

After importing using `curl -sSL https://rvm.io/mpapis.asc | gpg --import -` the problem persists.

## Environment info

We don't have the output of `rvm info` because we are unable to install rvm.

This is the output of gpg version:

```
$ gpg --version
gpg (GnuPG) 2.2.8
libgcrypt 1.8.4
```

**Comment by pkuczynski** [comment]
Following information on rvm.io you should fetch new keys:

```
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```

**Comment by rnitschelm** [comment]
Thank you for your quick reply.

We are using the ansible role: `rvm1-ansible`

Should we make an issue there about the missing key?

**Comment by pkuczynski** [comment]
Yes, please! Does it work after the steps I listed above?

**Comment by pkuczynski** [comment]
Could u also link the `rvm1-ansible` issue to this one for reference?

**Comment by pkuczynski** [comment]
No, it’s up to date. But we added my key as I did the release this time and it seems I will be doing this more often

**Comment by IgorTIV** [comment]
@pkuczynski But I can't install the last rvm with `mpapis.asc` either. Or fixes in `rvm1-ansible` will update `mpapis.asc` and I can use the current installation guide:
```
command curl -sSL https://rvm.io/mpapis.asc | sudo gpg --import -
curl -sSL https://get.rvm.io | bash -s stable
```

Am I right?

**Comment by bumpux** [comment]
I still experience this issue. When I try
`gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB` 

Output is 
`gpg: keyserver receive failed: Network is unreachable`

**Comment by rafa2000** [comment]
use gpg2, it works:
gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

**Comment by ramzieus** [comment]
this worked for me 
gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

**Comment by sumit007** [comment]
> this worked for me gpg --keyserver hkp://pgp.mit.edu --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

Thanks @ramzieus you saved my time.

**Comment by d00rsfan** [comment]
last adviced didn't work with error:  _gpg: keyserver receive failed: Server indicated a failure_
but (found on reddit) worked well:
gpg2 --keyserver keyserver.ubuntu.com --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
