### ISSUE TITLE
RVM is not working when i added the keys in centos 7

### ISSUE THREAD

**Issue by vijayreddy1991** [rvm/rvm#4529]
when I was installing ruby in centos 7 machine rvm is asking keys, so I added the keys but still, it's failing i don't know the reason
 
below error is attached

![image](https://user-images.githubusercontent.com/31643910/50073256-16f53380-01fe-11e9-935a-dc27f1c875d4.png)

**Comment by pkuczynski** [comment]
You need to provide full log

**Comment by vijayreddy1991** [comment]
# added to fix https://github.com/rvm/rvm/issues/3108
gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
curl -sSL https://rvm.io/mpapis.asc | sudo gpg2 --import -
sudo yum install which

echo "================= Installing RVM ==================="
curl -sSL https://get.rvm.io | bash -s stable

# Set source to rvm
source /usr/local/rvm/scripts/rvm
rvm requirements

export RVM_VERSION=2.5.3
echo "================= Installing default ruby ==================="
rvm install "$RVM_VERSION"


rvm use "$RVM_VERSION" --default


rvm rubygems current

this the script i am using

**Comment by vijayreddy1991** [comment]
================= Installing Ruby  ===================
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: requesting key 39499BDB from hkp server keys.gnupg.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: key 39499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 2  (RSA: 2)
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: ftp.iitm.ac.in
 * epel: mirrors.aliyun.com
 * extras: ftp.iitm.ac.in
 * ius: hkg.mirror.rackspace.com
 * updates: ftp.iitm.ac.in
Package which-2.20-7.el7.x86_64 already installed and latest version
Nothing to do
================= Installing RVM ===================
Downloading https://github.com/rvm/rvm/archive/1.29.6.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.6/1.29.6.tar.gz.asc
gpg: Signature made Thu Dec 13 15:09:53 2018 UTC using RSA key ID 39499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/usr/local/rvm/archives/rvm-1.29.6.tgz'
Creating group 'rvm'
Installing RVM to /usr/local/rvm/
Installation of RVM in /usr/local/rvm/ is almost complete:

  * First you need to add all users that will be using rvm to 'rvm' group,
    and logout - login again, anyone using rvm will be operating with `umask u=rwx,g=rwx,o=rx`.

  * To start using RVM you need to run `source /etc/profile.d/rvm.sh`
    in all your open shell windows, in rare cases you need to reopen all shell windows.
  * Please do NOT forget to add your users to the <code>rvm</code> group.
     The installer no longer auto-adds root or users to the rvm group. Admins must do this.
     Also, please note that group memberships are ONLY evaluated at login time.
     This means that users must log out then back in before group membership takes effect!
  * WARNING:  version This account is currently not available. detected - Zsh 4.3.12 / 5.0.0+ is recommended,
     with current one errors to be expected - bugs in shell code interpretation.

**Comment by pkuczynski** [comment]
Then show me the log for `rvm requirements` or `rvm install ...` please

**Comment by vijayreddy1991** [comment]
sorry its not rvm requirements its source /usr/local/rvm/scripts/rvm path issue

**Comment by pkuczynski** [comment]
I really need more details. Can't see any error in what you sent so far?

**Comment by pkuczynski** [comment]
I need to know what the error says. Otherwise I cant help

**Comment by checkmypi** [comment]
I'm having similar issue on Amazon Linux AMI 2018.03

I think it's related to 
https://github.com/rvm/rvm/pull/4428

as my script 

```
#!/bin/bash
set -ex
command curl -ksSL https://rvm.io/mpapis.asc | gpg2 --import -
command curl -ksSL https://rvm.io/pkuczynski.asc | sudo gpg2 --import -
command curl -ksSL http://get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh

some stuff 
```

fails to continue to do "some stuff" due to trap handling

```
+++ for __search in '"$@"'
+++ [[  __function_on_stack __rvm_setup source source main  == *\ \c\d\ * ]]
+++ for __search in '"$@"'
+++ [[  __function_on_stack __rvm_setup source source main  == *\ \p\u\s\h\d\ * ]]
+++ for __search in '"$@"'
+++ [[  __function_on_stack __rvm_setup source source main  == *\ \p\o\p\d\ * ]]
+++ return 1
+++ return 1
+++ export rvm_shell_nounset
+++ __rvm_has_opt nounset
+++ [[ -n '' ]]
+++ [[ -n '' ]]
+++ [[ -n 4.2.46(2)-release ]]
+++ [[ :braceexpand:hashall:interactive-comments:xtrace: == *\:\n\o\u\n\s\e\t\:* ]]
+++ return 1
+++ rvm_bash_nounset=0
+++ set +o nounset
++++ trap
++++ __rvm_grep -E 'EXIT|HUP|INT|QUIT|TERM'
++++ GREP_OPTIONS=
++++ command grep -E 'EXIT|HUP|INT|QUIT|TERM'
++++ grep -E 'EXIT|HUP|INT|QUIT|TERM'
++++ return 1
+++ _rvm_old_traps=
```

**Comment by sadam21** [comment]
We have the same problem described by @checkmypi - CentOS 7.

**Comment by jeremy** [comment]
See #4520. The signing key was changed from one maintainer to another. All users/platforms need to coordinate import and trust for the new key.
