### ISSUE TITLE
Error installing Ruby 2.5.3  on macos Mojave 10.14.2 

### ISSUE THREAD

**Issue by ejstembler** [rvm/rvm#4536]
## Description

RVM cannot successfully install Ruby 2.5.3.  First, it complains that `gcc@7` is not installed.  After installing it and rerunning, it deletes `gcc@7` and installs `gcc@6` and eventually errors out with:

```shell
There has been an error while running configure. Halting the installation.
```

## Steps to reproduce

1. Try to install Ruby 2.5.3:

```shell
rvm install 2.5.3
Warning, new version of rvm available '1.29.6', you are using older version '1.29.7'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.14/x86_64/ruby-2.5.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Error: No such keg: /usr/local/Cellar/gcc@7
Requirements installation failed with status: 1.
```

2. Install `gcc@7`:

```shell
brew install gcc@7
==> Downloading https://homebrew.bintray.com/bottles/gcc@7-7.4.0.mojave.bottle.tar.gz
Already downloaded: /Users/ejstembler/Library/Caches/Homebrew/downloads/d4552597f614fc16c0a55b77f775830c528596a0a33697fa028661c49b0f1e03--gcc@7-7.4.0.mojave.bottle.tar.gz
==> Pouring gcc@7-7.4.0.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/gcc@7/7.4.0: 1,399 files, 256.2MB
```

3. Try installing Ruby 2.5.3 again:

```shell
rvm install 2.5.3
Warning, new version of rvm available '1.29.6', you are using older version '1.29.7'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.14/x86_64/ruby-2.5.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Uninstalling /usr/local/Cellar/gcc@7/7.4.0... (1,399 files, 256.2MB)
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/ejstembler/.rvm/rubies/ruby-2.5.3, this may take a while depending on your cpu(s)...
ruby-2.5.3 - #downloading ruby-2.5.3, this may take a while depending on your connection...
ruby-2.5.3 - #extracting ruby-2.5.3 to /Users/ejstembler/.rvm/src/ruby-2.5.3.....
ruby-2.5.3 - #configuring......
Error running './configure --prefix=/Users/ejstembler/.rvm/rubies/ruby-2.5.3 --with-opt-dir=/usr/local/Cellar/libyaml/0.2.1:/usr/local/Cellar/readline/7.0.5:/usr/local/Cellar/libksba/1.3.5:/usr/local/opt/openssl@1.1 --disable-install-doc --enable-shared',
please read /Users/ejstembler/.rvm/log/1545189099_ruby-2.5.3/configure.log
There has been an error while running configure. Halting the installation.
```
or the more verbose message:
```shell
Error running './configure --prefix=/Users/ejstembler/.rvm/rubies/ruby-2.5.3 --with-opt-dir=/usr/local/Cellar/libyaml/0.2.1:/usr/local/Cellar/readline/7.0.5:/usr/local/Cellar/libksba/1.3.5:/usr/local/opt/openssl@1.1 --disable-install-doc --enable-shared',
please read /Users/ejstembler/.rvm/log/1545189561_ruby-2.5.3/configure.log
There has been an error while running configure. Halting the installation.
```

## Expected behavior

The expected behavior is to install Ruby 2.5.3 on macos Mojave 10.14.2.

## Actual behavior

**Debug mode**:
* [command](https://gist.github.com/ejstembler/cdda66c228b076c2ee665105e01016d8)
* [config.log](https://gist.github.com/ejstembler/b7caeba9b40412eda1a9a22127a4e57e)
* I'm not sure where the `make.log` is saved

## Environment info

system:

  system:
    uname:        "Darwin Mac-mini.home 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.14"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin18.0)"
    remote_path:  "osx/10.14/x86_64"
    xcode:        "10.1"

  rvm:
    version:      "1.29.7 (master)"
    updated:      "18 minutes 7 seconds ago"
    path:         "/Users/ejstembler/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/local/bin/ruby"
    irb:          "/usr/local/bin/irb"
    gem:          "/usr/local/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/usr/local/opt/ruby/bin:/Users/ejstembler/.kiex/bin:/Users/ejstembler/bin:/Users/ejstembler/go/bin:/mongodb/bin:/Users/ejstembler/miniconda3/bin:/usr/local/opt/erlang@17/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/share/dotnet:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/ejstembler/bin/FDK/Tools/osx:/Users/ejstembler/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by hivre** [comment]
can confirm on a macbook pro (2017 model)

**Comment by glennpratt** [comment]
Seeing the same behavior here.

**Comment by ozdigennaro** [comment]
I confirm on macbook pro (2018) Mojave 10.14.2.

**Comment by dtrabandt** [comment]
@pkuczynski I have the same issue like @glennpratt and @ejstembler on a prestine macOS 10.14 installation. When installing rvm the system install gcc@6 automatically and after this it always complains about the missing gcc@7 keg (while I try to figure out how to install ree-1.8.7-2012.02 - but thats another story).

**Comment by wndxlori** [comment]
I was getting the missing gcc@7 error.  So entertaining to install that (56 min 52 sec), only to have it promptly uninstalled when I tried the `rvm install` command again. ☹️ 

For some reason (old dependency?) I had an ancient brew version of gcc still installed (gcc@4.9). Once I explicitly uninstalled that brew version of gcc, my` rvm install 2.4` proceeded as desired.  

Those yaks are getting pretty razor-burned...

**Comment by printercu** [comment]
@pkuczynski I've just faced same issue. I also has command-line tools installed. After `brew install gcc@7`, starts working and first thing it does is removing fresh-installed gcc:
```
Checking requirements for osx.
Uninstalling /usr/local/Cellar/gcc@7/7.4.0...
```

I had to interrupt installation, and then had to reinstall gcc@7 again for the next `rvm install`.

**Comment by orneryd** [comment]
I had a similar issue with it detecting gcc on Mojave 10.14. I think the detection is looking for the string literal gcc*. I ran the following
```
ln -s /usr/local/Cellar/gcc /usr/local/Cellar/gcc\*
```
which created a symbolic link from gcc* (literal) to the gcc folder and I was able to install ruby 2.5.3. using RVM.

**Comment by ur5us** [comment]
Using @mbostler’s solution presented in https://github.com/rvm/rvm/issues/4536#issuecomment-449658736 works for me as well but it has side effects:

```
Error: Refusing to uninstall /usr/local/Cellar/gcc/8.2.0
because it is required by fftw, gdal, numpy, openblas, postgis and vips, which are currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies gcc*
```

Btw, I used @orneryd’s https://github.com/rvm/rvm/issues/4536#issuecomment-449761223 to debug the problem.

With regards to https://github.com/rvm/rvm/issues/4536#issuecomment-449592676, @pkuczynski I don’t think RVM should be ever allowed to remove arbitrary dependencies due to potential side effects as described above.

**Comment by nusco** [comment]
One more confirmation that the suggested fix doesn't always work. I have the command line tools installed and updated on Mojave 10.14.2, and I still get this error.

**Comment by m0n9oose** [comment]
Same problem here

```
~/d/s/c ❯❯❯ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
~/d/s/c ❯❯❯ xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
~/d/s/c ❯❯❯ rvm install 2.5.3
Warning, new version of rvm available '1.29.6', you are using older version '1.29.7'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.14/x86_64/ruby-2.5.3.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Error: No such keg: /usr/local/Cellar/gcc@7
Requirements installation failed with status: 1.
```

**Comment by justinhj** [comment]
Mojave 10.14 ... same here, had to `brew install gcc@7` and then when I ran `rvm install ruby-2.6.0-rc1` rvm uninstalled gcc@7 and continued to successfully build Ruby 2.6.0-rc1. Very confusing :D

**Comment by m0n9oose** [comment]
btw think this https://github.com/rvm/rvm/issues/4548 is the same issue

**Comment by pkuczynski** [comment]
This should be fixed by #4557

**Comment by GArgiz** [comment]
`brew install gcc@7` worked for me.
Thanks

**Comment by m0n9oose** [comment]
> This should be fixed by #4557

Confirm. Latest master version works fine.

**Comment by pkuczynski** [comment]
Awesome, thanks!

**Comment by binlecode** [comment]
Is this fix already in rvm stable version? 
thanks.

**Comment by binlecode** [comment]
Thanks much @pkuczynski !

**Comment by pkuczynski** [comment]
[Become a backer](https://opencollective.com/rvm#backer) and support us with a small donation to help us continue our activities. Thank you if you already one! 🙏

**Comment by tispratik** [comment]
Am facing same issue on Mac OS Catalina. 

```
$ rvm install 2.5.7
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.15/x86_64/ruby-2.5.7.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx_brew.
Installing requirements for osx_brew.
Updating system......|
Xcode version older than 4.6.2 installed, download and install newer version from:
.
    http://connect.apple.com

After installation open Xcode, go to Downloads and install Command Line Tools.

.
Error running 'requirements_osx_brew_update_system ruby-2.5.7',
please read /Users/pkhadloya/.rvm/log/1597506980_ruby-2.5.7/update_system.log
Requirements installation failed with status: 1.
```

**Comment by smmalini08** [comment]
Thank you for the solution

**Comment by lucasocon** [comment]
For my the soluton was, run `rvm get master` and then `rvm install "ruby-2.5.7"`
