### ISSUE TITLE
Ruby 2.6.0 Released!

### ISSUE THREAD

**Issue by sadiqmmm** [rvm/rvm#4543]
https://www.ruby-lang.org/en/news/2018/12/25/ruby-2-6-0-released/

**Comment by havenwood** [comment]
Yay for 2.6! Closed by #4542.

**Comment by ashmaroli** [comment]
https://bugs.ruby-lang.org/issues/15461

**Comment by pkuczynski** [comment]
We just released a new version 1.29.7 fixing this issue.
