### ISSUE TITLE
cannot upgrade with rvm get stable or get master command

### ISSUE THREAD

**Issue by MidnightRider67** [rvm/rvm#4545]
## Description

after installing rvm, when installing ruby, it says there is a newer version of rvm and to upgrade using rvm get stable, however that fails with many errors of "Cannot utime: Operation not permitted". i have also tried with rvm get master with the same results

## Steps to reproduce

 1. run "rvm get stable"
 2. run "rvm get master"
 3. ...

## Expected behavior

rvm should update
## Actual behavior
various errors with "Cannot utime: Operation not permitted"
  

https://gist.github.com/MidnightRider67/1d49133640c4fcc383eac89de5873090

## Environment info

https://gist.github.com/MidnightRider67/246b709e3b262fe510ebb527b55e592e

**Comment by zw963** [comment]
I think some environment variable is settings result to RVM try to install ruby to `/usr/share/rvm/`, that not the default behavior when run `rvm get stable`.

Following is solution:

1. remove current rvm, rerurn command with a normal user. (rvm should be install to $HOME/.rvm, recommend.)
2.  sudo su, switch to root, try to update rvm. (not recommend)
