### ISSUE TITLE
rvm get master fails in TravisCI

### ISSUE THREAD

**Issue by eregon** [rvm/rvm#4561]
## Description

`rvm get master` fails in TravisCI, as seen in this example job:
https://travis-ci.org/eregon/mspec/builds/473147581

The `.travis.yml` is minimal:
https://github.com/eregon/mspec/blob/663b50d3ba978d80fb61f529cc08464fba77c752/.travis.yml

This is annoying, because it [prevents](https://travis-ci.org/ruby/mspec/jobs/473108215) using TruffleRuby in TravisCI.

I think it would be worth to add a check in CI to ensure `rvm get master` works within TravisCI.

## Expected behavior

That it works.

## Actual behavior

```
$ rvm get master
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /home/travis/.rvm/archives/rvm-installer.asc
gpg: Signature made Thu 27 Dec 2018 06:38:39 PM UTC using RSA key ID 39499BDB
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
GPG signature verification failed for '/home/travis/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:
    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
or if it fails:
    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
the key can be compared with:
    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.
/home/travis/.rvm/scripts/functions/cli: line 243: return: _ret: numeric argument required
The command "rvm get master" exited with 2.
```

**Comment by eregon** [comment]
Here is the `--debug` output but it doesn't give much information: https://travis-ci.org/eregon/mspec/builds/473150635

**Comment by pkuczynski** [comment]
Your issue is related to the fact, that you are missing gpg keys for the new signer (me). add to your travis line:

`gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

before executing RVM get.

**Comment by eregon** [comment]
@pkuczynski This [worked](https://travis-ci.org/eregon/mspec/builds/473548407), thanks, but I believe it should work out of the box in TravisCI, without requiring this long and extra command line. How can we fix this?

IMHO, `rvm get update` should still work even if the gpg check fails, and warn, or there should be an option to skip the verification.

**Comment by eregon** [comment]
For instance, the `rvm get master`, part of `rvm: - truffleruby` used to work just fine but now fails:
https://travis-ci.org/ruby/mspec/jobs/473108215

It doesn't seem a good solution to change https://github.com/travis-ci/travis-build/blob/aec3718d99b234f1e55b0b4640d3fba691a2bc6f/lib/travis/build/script/shared/rvm.rb#L112-L121 for instance.

**Comment by eregon** [comment]
I just found https://travis-ci.community/t/new-gpg-key-for-rvm-releases/1521, that's probably a good solution. Here is to hoping it gets integrated fast.

**Comment by pkuczynski** [comment]
It worked before only because the key was already imported...

**Comment by ioquatix** [comment]
@BanzaiMan anything we can do to get this working again?

**Comment by pkuczynski** [comment]
@ioquatix just add gpg keys import as a first step of the build

**Comment by eregon** [comment]
@pkuczynski That won't work, because `rvm get master` is executed as part of `rvm: truffleruby`, before any user-defined command is executed.

**Comment by pkuczynski** [comment]
Then do it like:

```gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB && rvm get master```

**Comment by eregon** [comment]
@pkuczynski It's from https://github.com/travis-ci/travis-build/blob/aec3718d99b234f1e55b0b4640d3fba691a2bc6f/lib/travis/build/script/shared/rvm.rb#L117
Modifying that requires redeploying TravisCI images, so it seems much cleaner to add the GPG key in the keyring since anyway TravisCI images need to be modified to fix `rvm: truffleruby` in TravisCI.

I'll add a test using `rvm: truffleruby` in RVM's `.travis.yml`, then at least it shouldn't break without noticing anymore.

**Comment by pkuczynski** [comment]
Sure! It seems that for the next few months I will be the main person releasing RVM so ideally you should add my key... I am not sure if it would be possible to have one common key shared between all people releasing RVM...?

**Comment by BanzaiMan** [comment]
Hello, there. I'm finally getting around to this issue. Sorry for the delay.

The error message that RVM initially emits is somewhat confusing:

```
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/home/travis/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
```

There is only one key indicated, and it is one that does not work; If you run the `gpg2` command, it succeeds, yet the subsequent `rvm get head` still fails. Similar with `command curl …`.

The second key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB is nowhere to be found in the message, or the ASCII-armored GPG key given by https://rvm.io/mpapis.asc.

May I suggest improving the delivery mechanism for the new key?

Thanks.

**Comment by pkuczynski** [comment]
This has been fixed in the latest release.
