### ISSUE TITLE
Please release a version that allows to install ruby 2.6.0

### ISSUE THREAD

**Issue by johannesluedke** [rvm/rvm#4563]
Already fixed on master, but it would be nice to have this in stable as well 👍

**Comment by AaronRustad** [comment]
I'd like to see this happen too. For those not willing to wait, you can use `master` and then install `2.6.0` by doing the following:

```bash
> rvm get head  # this will give you master
> rvm install ruby-2.6.0
```

**Comment by pkuczynski** [comment]
Released! :)

**Comment by johannesluedke** [comment]
thanks!

**Comment by pkuczynski** [comment]
[Become a backer](https://opencollective.com/rvm#backer) and support us with a small donation to help us continue our activities. Thank you if you already one! 🙏
