### ISSUE TITLE
Unable to install any ruby versions using RVM in Mac OS 10.14.2(Mojave)

### ISSUE THREAD

**Issue by kamalakannan-chockalingam** [rvm/rvm#4565]
After upgrading to Mojave(10.14.2), tried to install any ruby versions using RVM.

Getting following error message related to Openssl. 

Have latest command line tools(Command_Line_Tools_macOS_10.14_for_Xcode_10.1) and xcode. Also installed latest stable RVM version(also rvm 1.29.7)

`FD:~ macuser$ rvm install 2.5.1
Warning, new version of rvm available '1.29.7', you are using older version '1.29.6'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
ruby-2.5.1 - #removing src/ruby-2.5.1..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.14/x86_64/ruby-2.5.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/macuser/.rvm/rubies/ruby-2.5.1, this may take a while depending on your cpu(s)...
ruby-2.5.1 - #downloading ruby-2.5.1, this may take a while depending on your connection...
ruby-2.5.1 - #extracting ruby-2.5.1 to /Users/macuser/.rvm/src/ruby-2.5.1.....
ruby-2.5.1 - #applying patch /Users/macuser/.rvm/patches/ruby/2.5.1/libressl_2_7.patch.
ruby-2.5.1 - #configuring.........................
Error running './configure --prefix=/Users/macuser/.rvm/rubies/ruby-2.5.1 --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/readline:/usr/local/opt/libksba:/usr/local/opt/openssl@1.1 --disable-install-doc --enable-shared',
please read /Users/macuser/.rvm/log/1546514340_ruby-2.5.1/configure.log
There has been an error while running configure. Halting the installation.`

Got the following message in configure.log file:

`checking size of long long... configure: error: in `/Users/macuser/.rvm/src/ruby-2.5.1':
configure: error: cannot compute sizeof (long long)
See `config.log' for more details`

**Comment by wyattisimo** [comment]
I had the exact same issue. Turned out my Homebrew formulae were all FUBARed and a bunch of the symlinks were busted. (I used the migration assistant when I upgraded to Mojave, and suspect that may have been the culprit.)

If you're using Homebrew, try running `brew doctor` and resolve all the issues it reports. You may need to remove and reinstall various formulae, like openssl and gettext, etc.

**Comment by pkuczynski** [comment]
@kamalakannan-chockalingam have u tried with `brew doctor`? I will close for now until you report further issues.

**Comment by mriveros** [comment]
This works for me:
rvm pkg install openssl
$ rvm remove rubyversion
$ rvm install rubyversionhere --with-openssl-dir=$HOME/.rvm/usr
$ gem install bundler
