### ISSUE TITLE
Submit Avira-flagged binary to Avira for whitelisting

### ISSUE THREAD

**Issue by paul-hammant** [rvm/rvm#4570]
Re https://github.com/rvm/rvm/pull/4498

Email support at avira.com with details of you're intermediate binary that's not really malware (false positive). I did so for an exe in Rust's source repo. It took them a month to fix it:

![2019-01-05_0923](https://user-images.githubusercontent.com/82182/50722742-86f32d00-10cb-11e9-8607-c26b23d8253b.png)

**Comment by pkuczynski** [comment]
I would need to send them a new version of ruby every time. Seems like too much effort, to be honest :(

**Comment by pkuczynski** [comment]
Thanks for the suggestion though!

**Comment by paul-hammant** [comment]
In the case of the Rust it was easily findable by the Avira team - https://github.com/rust-lang/rust/issues/55763

And I suspect you only have to deliver a single example to them of a false positive, for them to do the fingerprint work needed to whitelist it.
