### ISSUE TITLE
mac edition: Don’t depend on Homebrew

### ISSUE THREAD

**Issue by mcandre** [rvm/rvm#4574]
Would be better for rvm to install and operate with compatibility for plain vanilla macOS, such as bare Xcode for compilation, rather than requiring a full Homebrew setup. This would allow rvm to run in more places!

**Comment by havenwood** [comment]
@mcandre Xcode doesn't provide all of Ruby's build dependencies. You still need to link against Bison, OpenSSL, Readline, LibYAML, GDBM and libffi.

RVM doesn't depend on Homebrew! You can set `autolibs disable` and provide the dependencies yourself. (See the [autolibs docs](https://rvm.io/rvm/autolibs) for more.) RVM also support other macOS package managers like MacPorts and Fink.

**Comment by pkuczynski** [comment]
That's correct. Making plain vanilla for macOS would be a huge challenge. Other OS always offer some kind of package manager. macOS does not.
