### ISSUE TITLE
Ubuntu 18.04 binaries for rubies 2.2.10, 2.3.8, 2.4.5, 2.5.2, 2.5.3, 2.6.0

### ISSUE THREAD

**Issue by raelgc** [rvm/rvm#4595]
I'm building the above binaries for 18.04, trying to catch up the [official download page](https://www.ruby-lang.org/en/downloads/).

**Comment by saydulk** [comment]
is their any Ubuntu 16.04 binaries for rubies 2.5.0 ?

**Comment by saydulk** [comment]
@raelgc yes, i am using ubuntu 16 and i will happy to receive instruction from you

**Comment by raelgc** [comment]
@saydulk please, send me an email: rael.gc@gmail.com
