### ISSUE TITLE
The CI is failing, the rvm-test submodule was removed

### ISSUE THREAD

**Issue by eregon** [rvm/rvm#4609]
## Description

The latest build on master, https://travis-ci.org/rvm/rvm/builds/489053382, shows that all tests using `tf` are broken.

Maybe using an older version of `tf` would fix this?

I propose to make `master` a protected branch and enforce all Linux builds to succeed before merging a PR (until macOS builds also work, #4579).
Otherwise, it's just too easy to merge breaking changes.

cc @pkuczynski

**Comment by pkuczynski** [comment]
Hmm, don't know how and when the module was removed. You are right, we should focus on fixing macOS build... if we would only have more time :/

**Comment by eregon** [comment]
@pkuczynski @havenwood 
Now that the CI is green (with https://github.com/rvm/rvm/pull/4615), could we make `master` a GitHub protected branch, so only PRs passing the CI can be merged, and we can avoid cases like the above report issue?

Specifically, I suggest to make TravisCI a required status check with
https://help.github.com/articles/enabling-required-status-checks/
I wouldn't enable `Require branches to be up to date before merging` as that's rather annoying.

This would also make me (and I think others as well) more confident tests do not stop working without noticing.

**Comment by pkuczynski** [comment]
`master` is already a protected branch, I was just over-ruling it. Sorry about that. Will be more careful in the future!

**Comment by eregon** [comment]
Maybe the ` Include administrators` checkbox is good then :smile:

**Comment by eregon** [comment]
I think this was fixed in #4611, so let's close this issue.
TravisCI is now a required check, but it's not currently enforced for administrators.
