### ISSUE TITLE
Unable to install Homebrew in custom location

### ISSUE THREAD

**Issue by camyhsu** [rvm/rvm#4617]
## Description

Unable to install Homebrew when installing the first ruby binary.

## Steps to reproduce

 1. iMac 27in, macOS Mojave 10.14.3
 2. installed latest rvm (tried 1.29.7-next (master), 1.29.7, 1.29.4)
 3. attempt to install ruby 2.6.1

## Expected behavior

Be able to install Homebrew and move on.

## Actual behavior

* [command](https://gist.github.com/...)
```bash
CamyiMac27:~ camy$ rvm -v
rvm 1.29.7-next (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
CamyiMac27:~ camy$ rvm install 2.6.1
Warning, new version of rvm available '1.29.7', you are using older version '1.29.7-next'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.14/x86_64/ruby-2.6.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
About to install Homebrew, press `Enter` for default installation in `/usr/local`,
type new path if you wish custom Homebrew installation (the path needs to be writable for user)
: /Users/camy/code/homebrew
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   124    0   124    0     0    374      0 --:--:-- --:--:-- --:--:--   374
100   139    0   139    0     0    292      0 --:--:-- --:--:-- --:--:--   292
100   416    0   416    0     0    645      0 --:--:-- --:--:-- --:--:--   645
chmod: /Users/camy/code/homebrew/bin/brew: No such file or directory
Something went wrong during Homebrew installation,
can not find 'brew' command, please report a bug: https://github.com/rvm/rvm/issues
Requirements installation failed with status: 1.
CamyiMac27:~ camy$ 
```

* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

After the failure, I checked the homebrew directory, and found a README.md file indicating the repo for Homebrew has moved.

Content of the README.md:

# Homebrew (Legacy)
  
This repository was deprecated and split into two repositories:

- Homebrew formulae/packages: [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core) (former contents of `Library/Formula`)
- Homebrew package manager: [Homebrew/brew](https://github.com/Homebrew/brew)

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

```bash
CamyiMac27:~ camy$ rvm info

system:

  system:
    uname:        "Darwin CamyiMac27.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.14"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin18.0)"
    remote_path:  "osx/10.14/x86_64"
    xcode:        "10.1"

  rvm:
    version:      "1.29.7-next (master)"
    updated:      "8 minutes 54 seconds ago"
    path:         "/Users/camy/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/camy/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by havenwood** [comment]
If you'd like to install Homebrew into a non-standard path, you'll probably need to add it's `bin/` dir to `PATH` yourself. (Note that `/Users/camy/code/homebrew/bin` isn't in your `PATH` above.)

```sh
export PATH="$PATH:/Users/camy/code/homebrew/bin"
```

**Comment by camyhsu** [comment]
I don't think this is a path issue.  The bin directory does not exist in my system yet.

The error in the output is:
`chmod: /Users/camy/code/homebrew/bin/brew: No such file or directory`

And given the content in the Homebrew README, it seems RVM is going after an old location for Homebrew repo.

**Comment by havenwood** [comment]
Good point about `chmod` in the error. There seems to be an [issue around this code](https://github.com/rvm/rvm/blob/ff8caad474f4866e35540a365d0c20111e2eaf40/scripts/functions/requirements/osx_brew#L481-L483). The RVM `requirements_find_osx_brew()` function uses your `PATH` to find `brew` if it's not in `~/homebrew/bin/brew`, `~/.homebrew/bin/brew` or  the expected `/usr/local/bin/brew`. But it looks like for whatever reason brew isn't getting unarchived to the expected location, since as you point out it's not finding it to `chmod`. I'm really curious if this error with an alternate Homebrew installation location can be reproduced.

For what it's worth, the Homebrew folk say _"Pick another prefix at your peril!"_

**Comment by pkuczynski** [comment]
@camyhsu could you please run `rvm get branch /custom-brew-install` and try again? Your issue should be fixed :)

**Comment by camyhsu** [comment]
This branch works.  Thank you very much for fixing the repo location.

**Comment by pkuczynski** [comment]
Not a problem! Will merge it to master now :)
