### ISSUE TITLE
rvm doesn't update  ubuntu 18.04

### ISSUE THREAD

**Issue by Chagchen** [rvm/rvm#4622]
## Description

Rvm doesn't update to newest version. Went through all the possible options. 
This is the error message i get: 
"Could not update RVM, please report to https://github.com/rvm/rvm/issues"

It keeps downloading the same version: 
Warning, --auto is deprecated in favor of --auto-dotfiles.
Downloading https://github.com/rvm/rvm/archive/1.29.7.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.7/1.29.7.tar.gz.asc
gpg: Signature made Thu 03 Jan 2019 02:01:48 PM PST

I followed all the instructions at https://rvm.io/rvm/upgrading

No latest or later version downloaded:
(rvm 1.29.7 (manual) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io])

rvm info

ruby-2.5.1:

  system:
    uname:        "Linux gc-t530 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "18.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/18.04/x86_64"

  rvm:
    version:      "1.29.7 (manual)"
    updated:      "1 month 15 days 50 minutes 23 seconds ago"
    path:         "/usr/share/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.1p57"
    date:         "2018-03-29"
    platform:     "x86_64-linux"
    patchlevel:   "2018-03-29 revision 63029"
    full_version: "ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]"

  homes:
    gem:          "/usr/share/rvm/gems/ruby-2.5.1"
    ruby:         "/usr/share/rvm/rubies/ruby-2.5.1"

  binaries:
    ruby:         "/usr/share/rvm/rubies/ruby-2.5.1/bin/ruby"
    irb:          "/usr/share/rvm/rubies/ruby-2.5.1/bin/irb"
    gem:          "/usr/share/rvm/rubies/ruby-2.5.1/bin/gem"
    rake:         "/usr/share/rvm/gems/ruby-2.5.1/bin/rake"

  environment:
    PATH:         "/usr/share/rvm/gems/ruby-2.5.1/bin:/usr/share/rvm/gems/ruby-2.5.1@global/bin:/usr/share/rvm/rubies/ruby-2.5.1/bin:/usr/share/rvm/bin:/home/fifthavlabs/bin:/home/fifthavlabs/.nvm/versions/node/v8.11.3/bin:/home/fifthavlabs/.rvm/gems/ruby-2.5.1/bin:/home/fifthavlabs/.rvm/gems/ruby-2.5.1@global/bin:/home/fifthavlabs/.rvm/rubies/ruby-2.5.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    GEM_HOME:     "/usr/share/rvm/gems/ruby-2.5.1"
    GEM_PATH:     "/usr/share/rvm/gems/ruby-2.5.1:/usr/share/rvm/gems/ruby-2.5.1@global"
    MY_RUBY_HOME: "/usr/share/rvm/rubies/ruby-2.5.1"
    IRBRC:        "/usr/share/rvm/rubies/ruby-2.5.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by raelgc** [comment]
Which command you used? `rvm get stable`?

**Comment by Chagchen** [comment]
Yes, I have used that as well.

________________________________

**Comment by raelgc** [comment]
But the one you have installed is already the latest stable, `1.29.7`.

You can try get the development version with `rvm get master`.

And one friendly reminder: you can use the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm) to automatically receive new stable versions throw system updates.

**Comment by Chagchen** [comment]
Thank you!

________________________________
