### ISSUE TITLE
Error running '__rvm_make -j12' on Mac OS 10.14.3

### ISSUE THREAD

**Issue by 9jaswag** [rvm/rvm#4627]
## Description

I recently migrated to a new machine using the Migration Assistant. After that, I was having issues with RVM and installing any Ruby version. I uninstalled and re-installed RVM, getting the latest version.

Whenever I try to install any version of Ruby, I get this error: `Error running '__rvm_make -j12'`. I have tried several suggestions online including the ones [here](https://github.com/rvm/rvm/issues/4444).

I have XCode installed too.

## Steps to reproduce

Run `rvm install 2.6.0` or `rvm install ruby-2.5.1 --with-openssl-dir=/usr/local/opt/openssl`

## Expected behavior

I expect a clean install of Ruby

## Actual behavior
Returns the error: `Error running '__rvm_make -j12'`

Here's the content of the make.log file: [make.log](https://gist.github.com/9jaswag/4ef66b40ca6cb374f3373350c6ba281e)

## Environment info
```
system:

  system:
    uname:        "Darwin Chuks-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.14"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin18.0)"
    remote_path:  "osx/10.14/x86_64"
    xcode:        "10.1"

  rvm:
    version:      "1.29.7-next (master)"
    updated:      "51 minutes 16 seconds ago"
    path:         "/Users/andeladeveloper/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/local/bin/rake"

  environment:
    PATH:         "/Users/chuks/.nvm/versions/node/v10.15.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/chuks/Dev/flutter/bin:/Users/chuks/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```
I really need to fix this. All help is appreciated. Thanks

**Comment by 9jaswag** [comment]
@pkuczynski could please guide me how to fix this issue

**Comment by reginato** [comment]
@pkuczynski could you please guide me how to fix this issue

**Comment by pkuczynski** [comment]
@9jaswag closed this issue so I assume he found a fix?

**Comment by reginato** [comment]
Try 
- xcode-select --install
- rvm pkg install openssl
- rvm install XXX --with-openssl-dir=`brew --prefix openssl`

**Comment by cnadeau** [comment]
Another possibility:
 space in the XCode app name 

We had to support XCode 10 & 11 and had both installed, the path to `/Application/XCode.app/Contents/Developper` was `/Application/XCode 11.app/Contents/Developper` and caused a make error
