### ISSUE TITLE
Request that rvm also installs missing dependencies for compiling C++ gems for TruffleRuby on Ubuntu

### ISSUE THREAD

**Issue by ivoanjo** [rvm/rvm#4630]
Hello hello! And big thanks for rvm!

I recently hit upon this issue, and initially reported it to https://github.com/oracle/truffleruby/issues/1597 , but then realized that I was actually missing dependencies (:man_facepalming:).

Since rvm has support for installing OS dependencies during ruby install, could these be added? 🙏

## Description

I've installed `truffleruby 1.0.0-rc13` via RVM on Ubuntu, but could not compile C++-based gems because of missing dependencies to `libc++-dev` and `libc++abi-dev` [that are documented as required for TruffleRuby to compile these extensions](https://github.com/oracle/truffleruby/blob/master/doc/user/installing-llvm.md#ubuntu).

## Steps to reproduce

 1. Install `truffleruby 1.0.0-rc13`
 2. Run `gem install eventmachine`

## Expected behavior

When installing TruffleRuby, rvm should also install `libc++-dev` and `libc++abi-dev` so they can be used while installing eventmachine.

_(The gem itself will still not compile successfully due to unrelated bugs, see https://github.com/oracle/truffleruby/issues/1541)_

## Actual behavior

These dependencies were not installed, which meant that install failed:

```
./project.h:25:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
1 error generated.
make: *** [Makefile:204: binder.bc] Error 1
```

_(full output in https://github.com/oracle/truffleruby/issues/1597)_

After manually running `apt-get install libc++-dev libc++abi-dev` this error went away.

## Environment info

```
truffleruby-1.0.0-rc13:

  system:
    uname:        "Linux ubuntu 4.18.0-16-generic #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "18.10"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/18.10/x86_64"

  rvm:
    version:      "1.29.7-next (master)"
    updated:      "3 days 12 hours 9 minutes 9 seconds ago"
    path:         "/home/knuckles/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "truffleruby"
    version:      "1.0.0-rc13,"
    date:         "truffleruby 1.0.0-rc13, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]"
    platform:     "x86_64-linux"
    patchlevel:   "truffleruby 1.0.0-rc13, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]"
    full_version: "truffleruby 1.0.0-rc13, like ruby 2.4.4, GraalVM CE Native [x86_64-linux]"

  homes:
    gem:          "/home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13"
    ruby:         "/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13"

  binaries:
    ruby:         "/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13/bin/ruby"
    irb:          "/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13/bin/irb"
    gem:          "/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13/bin/gem"
    rake:         "/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13/bin/rake"

  environment:
    PATH:         "/home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13/bin:/home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13@global/bin:/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13/bin:/home/knuckles/.rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    GEM_HOME:     "/home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13"
    GEM_PATH:     "/home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13:/home/knuckles/.rvm/gems/truffleruby-1.0.0-rc13@global"
    MY_RUBY_HOME: "/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13"
    IRBRC:        "/home/knuckles/.rvm/rubies/truffleruby-1.0.0-rc13/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by brauliobo** [comment]
same here on archlinux and clang 8

**Comment by eregon** [comment]
Thanks for the bug report.
Starting from TruffleRuby 19.3.0, libc++ [no longer needs to be installed](https://github.com/oracle/truffleruby/blob/master/CHANGELOG.md#1930).

Therefore I think we can close this issues, because recent TruffleRuby releases should install fine without any manual package installation.
I also updated the list of dependencies 19.3.0+ no longer needs a system clang/LLVM: https://github.com/rvm/rvm/commit/28bf567b5d48d95843379075d3fe3837699d35dd
