### ISSUE TITLE
Error installing ruby

### ISSUE THREAD

**Issue by tamercuba** [rvm/rvm#4654]
I had never used Ruby on my life, im following this [installation tutorial](http://railsapps.github.io/installrubyonrails-ubuntu.html)
when I run `rvm get stable --autolibs=enable` happens (Im using ubuntu 18.10) :

Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /home/tamercuba/.rvm/archives/rvm-installer.asc
gpg: Assinatura feita dom 30 dez 2018 08:44:46 -02
gpg:                usando RSA chave 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Impossível verificar assinatura: Sem chave pública
GPG signature verification failed for '/home/tamercuba/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:

    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

In case of further problems with validation please refer to https://rvm.io/rvm/security 

I already installed gpg2 (i run ` sudo apt install gpgv2`) , I also run 

gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB 

that returns: 

 D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: key 105BD0E739499BDB: 5 signatures not checked due to missing keys
gpg: chave 105BD0E739499BDB: chave pública "Piotr Kuczynski <piotr.kuczynski@gmail.com>" importada
gpg: key 3804BB82D39DC0E3: 103 signatures not checked due to missing keys
gpg: chave 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" não mudada
gpg: ultimamente não encontradas chaves confiáveis
gpg: Número total processado: 2
gpg:               importados: 1
gpg:              não modificados: 1

(sorry my pt-br Linux i can translate for u if u need).
Idk what to do, any tips ? Ty

**Comment by raelgc** [comment]
Oi @tamercuba, tudo bem? Se importa em usar o [pacote dedicado para o Ubuntu](https://github.com/rvm/ubuntu_rvm) que fizemos?

**Comment by tamercuba** [comment]
Funcionou direitinho, consegui instalar o Ruby e o Rails tranquilamente. Muito obrigado @raelgc
