### ISSUE TITLE
Can't install jruby-9.2.6.0 on ubuntu 18.04: URL 404

### ISSUE THREAD

**Issue by rsov** [rvm/rvm#4655]
## Description

Helllo

I am having difficulty installing jruby-9.2.6.0 on ubuntu 18.04

It looks like it cannot find proper url to download binary artifacts and falls back on cloning and compiling from github, which then gives a maven error.

Is it expected for jruby to be compiled from source? 

Installing regular ruby versions works fine

I have also tried this command:
```
rvm mount -r https://repo1.maven.org/maven2/org/jruby/jruby-dist/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz
```
It installs jruby version fine but under `jruby-dist-9.2.6.0-bin` name and it can't load bundler after installing it with `gem install bundler`

Using `-n jruby-9.2.6.0` gives `Missing 'ruby' in 'rubygems_detect_ruby_lib_gem_path'.` error

## Steps to reproduce

 1. `rvm install jruby-9.2.6.0`

## Actual behavior

Output:
```
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz
Checking requirements for ubuntu.
Requirements installation successful.
jruby-9.2.6.0 - #configure
jruby-9.2.6.0 - #download
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
The requested url does not exist(22): 'https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz?rvm=1.29.7-next'
Checking fallback: ftp://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz?rvm=1.29.7-next
Checking fallback: https://www.mirrorservice.org/sites/rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz?rvm=1.29.7-next
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
The requested url does not exist(22): 'https://www.mirrorservice.org/sites/rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz?rvm=1.29.7-next'
Failed download
Downloading https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz failed.
Mounting remote ruby failed with status 2, trying to compile.
Checking requirements for ubuntu.
Requirements installation successful.
HEAD is now at 15ba00b533 Update for 9.2.6.0
Previous HEAD position was 15ba00b533 Update for 9.2.6.0
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
From https://github.com/jruby/jruby
 * branch                  master     -> FETCH_HEAD
Already up to date.
git checkout 9.2.6.0
Copying from repo to src path...
jruby-9.2.6.0 - #mvnw - please wait
Error running '/home/rsov/.rvm/src/jruby-9.2.6.0/mvnw',
please read /home/rsov/.rvm/log/1553873588_jruby-9.2.6.0/mvnw.log
```

URLs that it's trying to use:

https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz

https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz?rvm=1.29.7-next

ftp://rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz?rvm=1.29.7-next

https://www.mirrorservice.org/sites/rvm_io.global.ssl.fastly.net/binaries/ubuntu/18.04/x86_64/9.2.6.0/jruby-dist-9.2.6.0-bin.tar.gz?rvm=1.29.7-next

## Environment info

>  system:
>     uname:        "Linux Dev2 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"
>     name:         "Ubuntu"
>     version:      "18.04"
>     architecture: "x86_64"
>     bash:         "/bin/bash => GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)"
>     zsh:          "/usr/bin/zsh => zsh 5.4.2 (x86_64-ubuntu-linux-gnu)"
>     remote_path:  "ubuntu/18.04/x86_64"
> 
>   rvm:
>     version:      "1.29.7-next (master)"
>     updated:      "3 minutes 48 seconds ago"
>     path:         "/home/rsov/.rvm"
>     autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

**Comment by mojavelinux** [comment]
I'm getting this problem a lot on Travis CI.

Here's an example:

https://travis-ci.org/asciidoctor/asciidoctor-pdf/jobs/551197363

I have no idea what's going on, but it looks like there some flawed logic in RVM or the URL is just returning garbage RVM can't understand.

**Comment by rabos5** [comment]
I saw this was closed but wasn't sure exactly what the resolution was.  Can somebody add more detail?
