### ISSUE TITLE
Merge rvm-test inside the rvm repository

### ISSUE THREAD

**Issue by eregon** [rvm/rvm#4663]
## Description

Currently, the RVM test suite is a separate repository: https://github.com/rvm/rvm-test

It is imported as a git submodule.
Git submodule are to say the least inconvenient to work with.

As such, I proposed to merge `rvm-test` in `rvm`, since I don't think it's very valuable to have its own repository, and it's quite inconvenient to fix a bug and add a test:
3 PRs (rvm, rvm-test, bump import in rvm) to 2 different repos instead of just one PR to one repo.

cc @pkuczynski @mpapis

**Comment by eregon** [comment]
Also, the CI of `rvm-test` is redundant with `rvm`'s, and not in sync, so it's not possible to introduce a new test without the fix being merged in `rvm` first, and there are probably more synchronization issues.

**Comment by eregon** [comment]
e.g., the CI of `rvm-test` is broken on https://github.com/rvm/rvm-test/pull/27, but it doesn't matter since the important one is `rvm`'s CI.

**Comment by pkuczynski** [comment]
I agree. I think the only reason why those are not included is to make the bundle smaller, but the hassle is not worth it I think. @mpapis?

**Comment by eregon** [comment]
@mpapis gentle ping :smiley:

**Comment by eregon** [comment]
This was done in 7930978022d2163b05deebf813b920f608cbb7a2 / #4757 as a git subtree, thanks @mpapis!
