### ISSUE TITLE
`rvm get stable` fails with bad signature

### ISSUE THREAD

**Issue by BanzaiMan** [rvm/rvm#4675]
## Description

`rvm get stable` fails with the following sequence of commands:

```sh-session
$ command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
$ command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -
$ rvm get stable
```

## Steps to reproduce

See above.

## Expected behavior

RVM updates to the stable release

## Actual behavior

```
$ rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /home/travis/.rvm/archives/rvm-installer.asc
gpg: Signature made Sun 30 Dec 2018 10:44:46 AM UTC using RSA key ID 39499BDB
gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
GPG signature verification failed for '/home/travis/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:
    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
or if it fails:
    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
the key can be compared with:
    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.
```

## Environment info

<details>
<summary><tt>rvm info</tt> output</summary>
<pre>
$ rvm info

ruby-2.5.3:

  system:
    uname:        "Linux travis-job-a1523935-0f44-4dc2-aca1-aad6166aec32 4.15.0-1028-gcp #29~16.04.1-Ubuntu SMP Tue Feb 12 16:31:10 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "16.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/16.04/x86_64"

  rvm:
    version:      "1.29.7 (latest)"
    updated:      "28 days 19 hours 56 minutes 52 seconds ago"
    path:         "/home/travis/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.3p105"
    date:         "2018-10-18"
    platform:     "x86_64-linux"
    patchlevel:   "2018-10-18 revision 65156"
    full_version: "ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]"

  homes:
    gem:          "/home/travis/.rvm/gems/ruby-2.5.3"
    ruby:         "/home/travis/.rvm/rubies/ruby-2.5.3"

  binaries:
    ruby:         "/home/travis/.rvm/rubies/ruby-2.5.3/bin/ruby"
    irb:          "/home/travis/.rvm/rubies/ruby-2.5.3/bin/irb"
    gem:          "/home/travis/.rvm/rubies/ruby-2.5.3/bin/gem"
    rake:         "/home/travis/.rvm/gems/ruby-2.5.3@global/bin/rake"

  environment:
    PATH:         "/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.phpenv/shims:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/home/travis/.rvm/gems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/.rvm/bin:/home/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin:/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin:/home/travis/.debug:/home/travis/.phpenv/bin:/opt/pyenv/bin"
    GEM_HOME:     "/home/travis/.rvm/gems/ruby-2.5.3"
    GEM_PATH:     "/home/travis/.rvm/gems/ruby-2.5.3:/home/travis/.rvm/gems/ruby-2.5.3@global"
    MY_RUBY_HOME: "/home/travis/.rvm/rubies/ruby-2.5.3"
    IRBRC:        "/home/travis/.rvm/rubies/ruby-2.5.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
</pre>
</details>

**Comment by BanzaiMan** [comment]
I should note that these steps were working at least [19 days ago](https://travis-ci.org/simi/mongoid_paranoia/jobs/515711087#L461) (and perhaps more recently). The latest failure can be observed in https://travis-ci.org/simi/mongoid_paranoia/jobs/523433289#L469-L483.

To the best of my knowledge, these builds import the same keys.

**Comment by henderea** [comment]
I use `rvm get head`, and I last successfully ran that on Friday the 19th.  Skipped it yesterday, and got a failure today.

It lists the following as the import line (on macOS 10.14.4):

```shell
gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```

**Comment by henderea** [comment]
@pkuczynski: Did you forget to update `binscripts/rvm-installer.asc` after merging 51e8619137aa7116a9d6d415d32e0d3762016d3b?  And maybe whatever copy `rvm get stable` uses at some point?

**Comment by maxkerp** [comment]
I can confirm this problem. Let me know if you need more information.

**Comment by henderea** [comment]
I personally can't imagine any cause other than the fact that `binscripts/rvm-installer` was last updated "5 hours ago", and `binscripts/rvm-installer.asc` was last updated "4 months ago" 😅

**Comment by pkuczynski** [comment]
@henderea indeed! What a mistake. Sorry about this! Fixed.

**Comment by Nowaker** [comment]
How to recover from this issue now? I'm stuck at an older version and have no way to update.
