### ISSUE TITLE
BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>

### ISSUE THREAD

**Issue by stotler** [rvm/rvm#4677]
## Description

I've been installing rvm (1.25.34) via this method several times/day for months now, but as of yesterday I'm getting a BAD signature error:

gpg: Signature made Sun 30 Dec 2018 05:44:46 AM EST using RSA key ID 39499BDB
gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>

## Steps to reproduce

 1. /usr/bin/gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
wget -q https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer
wget -q https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
chmod +x rvm-installer
rm -f /etc/rvmrc
gpg --verify rvm-installer.asc && rvm_path=/usr/local/rvm ./rvm-installer

## Expected behavior

Up until yesterday this was smooth like butter, and would install cleanly every time.

## Actual behavior

https://gist.github.com/stotler/b4b347c2eab8776f7a42535968157fb6

## Environment info

rvm: command not found -- since it was unable to install...

**Comment by stotler** [comment]
I'm also getting this:

`/usr/bin/gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: keyring `/home/ubuntu/.gnupg/secring.gpg' created
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: requesting key 39499BDB from hkp server keys.gnupg.net
gpg: /home/ubuntu/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: key 39499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 2  (RSA: 2)`

**Comment by pkuczynski** [comment]
We had that issue yesterday but was fixed around 7PM CET. Does it still appear to you? Can u try to run `\curl -sSL https://get.rvm.io | bash`

I just checked and it works correctly.

**Comment by stotler** [comment]
Something must've been cached on that server (although I don't see how), I spun up a new one and am off to the races.

Thanks again!

**Comment by pkuczynski** [comment]
You welcome! :)

**Comment by pkuczynski** [comment]
#4675
