### ISSUE TITLE
Debian - Ruby 1.8.7-head

### ISSUE THREAD

**Issue by Cr4zyFl1x** [rvm/rvm#4682]
## Description

I try to install ruby 1.7.8-head on my Debian 9.9 System, because of projects that need such an old version. But every time I try to install this version I get an error.

## Steps to reproduce

 1. install the current rvm version
 2. try to install the ruby version 1.8.7-head ( `$ rvm install 1.8.7-head`)
 3. You'll see the following error:

Error running '__rvm_make -j6',
please read /usr/local/rvm/log/1556660176_ruby-1.8.7-p374/make.log

There has been an error while running make. Halting the installation.

To proceed rvm requires a ruby-1.8.7-p374 compatible ruby is installed.
We attempted to install it automatically but it failed with status 2.
Please install it manually (or a compatible alternative) to proceed.

## Expected behavior

A successful installation of ruby 1.8.7.

## Actual behavior

The installation of ruby fails. (`See -> Steps to reproduce`)

## Environment info

- Linux version => `Debian 9.9`
- Kernel => `2.6.32-openvz-042stab136.1-amd64`
- Architecture => `x86_64`

- Ruby => `Until now => not installed`
- Gem => `Until now => not installed`
- Rake => `Until now => not installed`

 
- RVM => `rvm 1.29.7-next (master)`
- Other environment info => [`https://pastebin.com/iMerpLNH`](https://pastebin.com/iMerpLNH)

**Comment by t12nslookup** [comment]
Did you see #4515?
