### ISSUE TITLE
rvm not working with linuxbrew

### ISSUE THREAD

**Issue by rwheadon** [rvm/rvm#4691]
I have updated my rvm from head.

## Description

After installing linuxbrew and setting rvm to enable autolibs (rvm autolibs homebrew) I am not able to run bundle or gem install commands. The search for requirements seems to be expecting xcode, but since this is linux it isn't there (nor available).

I have reached out to the linuxbrew team and they feel this is an issue with rvm.

console sample:
```
$ rvm reinstall 2.0 --with-openssl-dir=/home/linuxbrew/.linuxbrew/Cellar/openssl/1.0.2r
Checking requirements for osx_brew.
Installing requirements for osx_brew.
Updating system......./
Xcode version older than 4.6.2 installed, download and install newer version from:
.
    http://connect.apple.com
/
After installation open Xcode, go to Downloads and install Command Line Tools.
\
.
Error running 'requirements_osx_brew_update_system ruby-2.0.0-p648',
please read /home/deployer/.rvm/log/1557457671_ruby-2.0.0-p648/update_system.log
Requirements installation failed with status: 1.

```
## Steps to reproduce

**Environment:**
OS: OpenSuSE Leap 15.0
Homebrew : linuxbrew (Homebrew 2.1.2); Homebrew/linuxbrew-core (git revision 52cb; last commit 2019-05-09)
RVM : rvm 1.29.8-next (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

 1. New Leap 15.0 vcs.
 2. sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
 3. echo 'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)' >>~/.profile
 4. eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
 5. brew install gcc
 6. brew install openssl
 7. curl -sSL https://get.rvm.io | bash -s stable --ruby
 8. rvm autolibs homebrew
 9. rvm install 2.0 --with-openssl-dir=/usr/local/opt/openssl

## Expected behavior

ruby 2.0... install using openssl 1.0.2r which was installed via homebrew

## Actual behavior
* [rvm reinstall 2.0 --with-openssl-dir=/home/linuxbrew/.linuxbrew/Cellar/openssl/1.0.2r](https://gist.github.com/rwheadon/b3a8e9626422edb0336cd8790d3b5858)
* [update_system.log](https://gist.github.com/rwheadon/c17d2b2ff2d4dd960e29f2a2ec911f7f) 

## Environment info
```
 rvm info

ruby-2.0.0-p648:

  system:
    uname:        "Linux li483-43 4.12.14-lp150.12.58-default #1 SMP Mon Apr 1 15:20:46 UTC 2019 (58fcc15) x86_64 x86_64 x86_64 GNU/Linux"
    name:         "OpenSuSE"
    version:      "15.0"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 4.4.23(1)-release (x86_64-suse-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "opensuse/15.0/x86_64"

  rvm:
    version:      "1.29.8-next (master)"
    updated:      "1 day 14 hours 10 minutes 20 seconds ago"
    path:         "/home/deployer/.rvm"
    autolibs:     "[homebrew] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.0p0"
    date:         "2017-12-25"
    platform:     "x86_64-linux-gnu"
    patchlevel:   "2017-12-25 revision 61468"
    full_version: "ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]"

  homes:
    gem:          "/home/deployer/.rvm/gems/ruby-2.0.0-p648"
    ruby:         "/home/deployer/.rvm/rubies/ruby-2.0.0-p648"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/home/deployer/.rvm/gems/ruby-2.0.0-p648/bin:/home/deployer/.rvm/gems/ruby-2.0.0-p648@global/bin:/home/deployer/.rvm/rubies/ruby-2.0.0-p648/bin:/home/deployer/.rvm/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/bin:/home/deployer/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin"
    GEM_HOME:     "/home/deployer/.rvm/gems/ruby-2.0.0-p648"
    GEM_PATH:     "/home/deployer/.rvm/gems/ruby-2.0.0-p648:/home/deployer/.rvm/gems/ruby-2.0.0-p648@global"
    MY_RUBY_HOME: "/home/deployer/.rvm/rubies/ruby-2.0.0-p648"
    IRBRC:        "/home/deployer/.rvm/rubies/ruby-2.0.0-p648/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by pkuczynski** [comment]
We dont suport linuxbrew. Just set `rvm autolibs enable` and everything should work!
