### ISSUE TITLE
rvm auto-upgrading on bionic from 1.29.7 to .8

### ISSUE THREAD

**Issue by luke-hill** [rvm/rvm#4693]
## Description

Not a problem per se, but it seems that 1.29.7 auto-upgraded to 1.29.8 without any input

## Steps to reproduce

N/A
## Expected behavior

I was triaging a bug to do with 1.29.7 compatibility with RubyMine

## Environment info
```
Warning! PATH is not properly set up, /home/luke/.rvm/gems/ruby-2.6.3/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-2.6.3
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
rvm 1.29.8 (manual) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
```

**Comment by raelgc** [comment]
If you're using the [ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm), you'll receive automatic updates while updating your system using `apt`.

**Comment by luke-hill** [comment]
I'm using the apt package, but I've not ran apt-update in weeks. 

Does the ubuntu "Software Installer" do those updates? Those have occassionally ran, but I always thought those didn't update apts?

**Comment by raelgc** [comment]
If your server configuration totally in your hands or are you using services like AWS, DigitalOcean and others? Many of them will includes the `unattended-upgrades` package in the default install, which will perform some updates.

Anyway, yes, the package will only be updated if `apt` update was involved.

**Comment by luke-hill** [comment]
This was on my local machine, I'm not too worried about servers. Just been trying to diagnose an issue and spent a week wrongly assuming I was on 1.29.7 as I hadn't told it to upgrade.

**Comment by raelgc** [comment]
Got it. So, now it's clear that you're using the apt package and it relies on `apt` upgrades, if you don't mind, I'll close this issue. Anyway, feel free to re-open it if you have any additional questions.

**Comment by luke-hill** [comment]
I mean this feels kinda hidden tbh. I wouldn't expect it to auto-update without me at least telling it to. But I guess it's not a big problem, just perhaps something we should outline that it'll auto-upgrade as and when it sees fit.

**Comment by raelgc** [comment]
@luke-hill In the [README of the package repo](https://github.com/rvm/ubuntu_rvm/blob/master/README.md), the instructions are to add a PPA repo (so auto updates are expected when adding a PPA). 

Additionally the README file clearly states that:

> Additionally automatic updates are provided by a Ubuntu PPA.

Anyway, you can, optionally, just uninstall the `rvm` package and remove the PPA entry from apt sources (manually or using ppa purge). Then install using https://rvm.io/ instructions and don't be bothered by automatic updates again.
