### ISSUE TITLE
UI: more helpful warnings/error messages?

### ISSUE THREAD

**Issue by fwolfst** [rvm/rvm#4695]
## Description

    $ rvm --version
    rvm 1.29.8 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

I propose two changes to point users to their next action if they ran into "trouble":

### rvm install

    $ rvm install
    Can not use or install 'all' rubies.

The "error" message could be pointing into the direction of finding installation candidates

     Can not use or install 'all' rubies. Get a list of installable rubies by calling `rvm list known`.

### autoupdate warning

I actually came to this from following situation

> $ rvm install
> Warning, new version of rvm available '1.29.8', you are using older version '1.29.
> 7'.                                                                               
> You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc      
> You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc      
> Can not use or install 'all' rubies. 

I propose to change the text into

> Warning, new version of rvm available '1.29.8', you are using older version '1.29.
> 7'. You can use `rvm get` to update (e.g. `rvm get stable`).
> ...

Would such a PR be merged in?

**Comment by pkuczynski** [comment]
Sure, why not? We are open for feedback and improvements!

**Comment by fwolfst** [comment]
ack. PR.
