### ISSUE TITLE
GPG signature verification failed

### ISSUE THREAD

**Issue by LuisMiguelOG** [rvm/rvm#4698]
Hello team,

I'm facing a problem that I'm not able to solve. I've been looking on internet for many many days and I have not found any solution.

I'm following a guide of Android CI with Kubernetes and I need to add something called STF-Client (Smartphone Test Farm) from RubyGems.

**I have a DockerFile and the issue appears when I try the next:**

# Install STF-Client
RUN curl -sSL https://rvm.io/mpapis.asc | gpg --import - && \
    curl -sSL https://get.rvm.io | grep -v __rvm_print_headline | bash -s stable --ruby && \
    echo "source /Users/luismi/.rvm/scripts/rvm" >> ~/.bashrc && \
    # Install gems
    /bin/bash -l -c "gem install bundler stf-client:0.2.0 --no-ri --no-rdoc"

**One applied, this is what I get:**

 ---> Running in bce072b9a656
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: no ultimately trusted keys found
Downloading https://github.com/rvm/rvm/archive/1.29.8.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.8/1.29.8.tar.gz.asc
gpg: Signature made Wed 08 May 2019 02:14:49 PM UTC using RSA key ID 39499BDB
gpg: Can't check signature: public key not found
GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.8.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.8/1.29.8.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

In case of further problems with validation please refer to https://rvm.io/rvm/security

The command '/bin/sh -c curl -sSL https://rvm.io/mpapis.asc | gpg --import - &&     curl -sSL https://get.rvm.io | grep -v __rvm_print_headline | bash -s stable --ruby &&     echo "source /Users/luismi/.rvm/scripts/rvm" >> ~/.bashrc &&     /bin/bash -l -c "gem install bundler stf-client:0.2.0 --no-ri --no-rdoc"' returned a non-zero code: 2

Enviroment:
MacBook Pro
Mojave 10.14.2
$ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
$ gem --version
3.0.1

More info:
MBP-de-Luis:docker-android luismi$ echo 409B6B1796C275462A1703113804BB82D39DC0E3:6: | gpg --import-ownertrust
gpg: inserting ownertrust of 6
MBP-de-Luis:docker-android luismi$ echo 7D2BAF1CF37B13E2069D6956105BD0E739499BDB:6: | gpg --import-ownertrust
gpg: inserting ownertrust of 6

MBP-de-Luis:docker-android luismi$ curl -sSL https://rvm.io/mpapis.asc | gpg --import
gpg: key 3804BB82D39DC0E3: 47 firmas no comprobadas por falta de claves
gpg: clave 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" sin cambios
gpg: Cantidad total procesada: 1
gpg:              sin cambios: 1

If someone knows what is happening or know any workaround I will be very grateful.

Thanks in advance.

Kind Regards.

**Comment by pkuczynski** [comment]
You need to import more keys:

```
RUN curl -sSL https://rvm.io/mpapis.asc | gpg --import - && curl -sSL https://rvm.io/pkuczynski.asc | gpg --import - && ...
```
