### ISSUE TITLE
RVM Libraries missing for ruby-2.6.3: /home/damr67/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/x86_64-linux/openssl.so:. Refer to your system manual for installing libraries Mounting remote ruby failed with status 10, trying to compile.

### ISSUE THREAD

**Issue by damr67** [rvm/rvm#4710]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by pkuczynski** [comment]
Please open a new issue and provide all information required in issue template
