### ISSUE TITLE
Sponsor button not working

### ISSUE THREAD

**Issue by Eliada** [rvm/rvm#4715]
## Description

Hi! It seems that the github sponsor button is not properly set up:

This is the modal that appers when the Sponsor button is clicked:
![image](https://user-images.githubusercontent.com/1172532/59481440-9f196600-8e3a-11e9-815f-a29e7c88d88e.png)

I know you guys have the open collective running, that's great, but do you intent to use GitHub sponsor program too?

**Comment by pkuczynski** [comment]
I applied for GitHub Sponsors but has not been accepted yet. So temporarily I turned it off for RVM keeping only Open Collective

**Comment by pkuczynski** [comment]
Thanks for letting us know about the issue!
