### ISSUE TITLE
bash: error importing function definition for `__rvm_ruby_string_find'

### ISSUE THREAD

**Issue by natefaerber** [rvm/rvm#4721]
# Description

RVM complains when `set -a` is used in BASH.  This is similar to #2387 

```
bash: __rvm_ruby_string_find: line 8: syntax error near unexpected token `('
bash: __rvm_ruby_string_find: line 8: ` ruby-+([1-9]) | ruby-+([1-9]).+([0-9]) | ruby-1.+([1-9]).+([0-9]) | jruby-[19]*)'
bash: error importing function definition for `__rvm_ruby_string_find'
```

## Steps to reproduce

 1. `set -a`
 2. `rvm list`

## Expected behavior

RVM should list installed Rubies without BASH errors.

## Actual behavior

```
$ rvm list
=* ruby-2.4.5 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

$ set -a
$ rvm list
bash: __rvm_ruby_string_find: line 8: syntax error near unexpected token `('
bash: __rvm_ruby_string_find: line 8: ` ruby-+([1-9]) | ruby-+([1-9]).+([0-9]) | ruby-1.+([1-9]).+([0-9]) | jruby-[19]*)'
bash: error importing function definition for `__rvm_ruby_string_find'
=* ruby-2.4.5 [ x86_64 ]

# => - current
# =* - current && default
#  * - default

$
```

## Environment info

Probably not relevant.

## Possible Solution

I have tested simply added `__rvm_ruby_string_find` to the list of functions here: https://github.com/rvm/rvm/blob/master/scripts/functions/environment#L189.  With it added, the BASH error did not show up.  I don't fully understand what this is actually doing to resolve the issue so I don't know if this causes other problems.

**Comment by dfuentes77** [comment]
Thanks for posting.  I'm getting the same error from a recent stable install of RVM.  I use `set -a` for a lot of things so I need it in my `~/.bashrc`.  I confirmed that if I remove the `set -a` from my `~/.bashrc`, those errors cease.
