### ISSUE TITLE
Could not update RVM using rvm get stable - Sporadic failures

### ISSUE THREAD

**Issue by Dekken** [rvm/rvm#4723]
https://travis-ci.org/X-DataInitiative/tick/jobs/552469732

I end up just restarting the job until it runs

**Comment by Dekken** [comment]
It's been like this for about 4 days now

**Comment by travisdahlke** [comment]
This appears to be addressed here: https://github.com/rvm/rvm/pull/4722

**Comment by travisdahlke** [comment]
And the same issue on travis-ci forum: https://travis-ci.community/t/rvm-tries-to-download-blank-version-of-itself/3972/3

**Comment by Dekken** [comment]
cool thanks

**Comment by jrochkind** [comment]
I just had this problem again on travis today. 

```
1.33s$ rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /home/travis/.rvm/archives/rvm-installer.asc
gpg: Signature made Mon 01 Jul 2019 05:24:59 PM UTC using RSA key ID BF04FF17
gpg: Good signature from "Michal Papis (RVM signing) <mpapis@gmail.com>"
gpg:                 aka "Michal Papis <michal.papis@toptal.com>"
gpg:                 aka "[jpeg image of size 5015]"
gpg: Note: This key has expired!
Primary key fingerprint: 409B 6B17 96C2 7546 2A17  0311 3804 BB82 D39D C0E3
     Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36  166B E206 C29F BF04 FF17
GPG verified '/home/travis/.rvm/archives/rvm-installer'
curl: (22) The requested URL returned error: 403 Forbidden
curl: (22) The requested URL returned error: 410 Gone
Downloading https://github.com/rvm/rvm/archive/.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Could not download 'https://github.com/rvm/rvm/archive/.tar.gz'.
  curl returned status '22'.
Downloading https://bitbucket.org/mpapis/rvm/get/.tar.gz
curl: (22) The requested URL returned error: 404 Not Found
Could not download 'https://bitbucket.org/mpapis/rvm/get/.tar.gz'.
  curl returned status '22'.
Could not update RVM, please report to https://github.com/rvm/rvm/issues
The command "rvm get stable" failed and exited with 22 during .
```

Is the problem actually fixed?  Or does travis need to update something on their end?

**Comment by jrochkind** [comment]
(note also the key expiration warning in my console output, which is perhaps an unrelated issue, not sure if it should be concerning?)

**Comment by pkuczynski** [comment]
I just released a new stable version. This would hopefully solve the issue with travis. Let me know if it does not...

**Comment by jrochkind** [comment]
My travis finally went green, seems to have worked, thanks @pkuczynski !

**Comment by pkuczynski** [comment]
Glad to be able to help! You can also consider becoming a [backer](https://opencollective.com/rvm#backer), with a one-off or recurring donation, to sponsor further development of RVM :)

**Comment by jrochkind** [comment]
Is Travis currently a backer? If not, I will send them an email as a customer suggesting they become one. They lean pretty heavy on rvm to make ruby testing work on travis. 

I don't myself use rvm much, except via travis.

**Comment by pkuczynski** [comment]
Sure! Do so...

**Comment by stewi2** [comment]
fwiw, this does not seem to have fixed the issues with Travis. It's still failing most of the time, but does succeed sometimes after restarting the build multiple times.

**Comment by stewi2** [comment]
Btw - the 410 error above is because the Bitbucket API has been removed:

```
$ curl -s https://bitbucket.org/api/1.0/repositories/mpapis/rvm/branches-tags | jq .
{
  "type": "error",
  "error": {
    "message": "Resource removed",
    "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"
  }
}
```

**Comment by stewi2** [comment]
And the Github URL sometimes returns a 403 when queried from Travis. This is easy to debug via a Travis debug VM btw.

**Comment by stewi2** [comment]
It's possible that the 403s from Github aren't new, but that it was able to fall back to the deprecated Bitbucket API - until that got removed.

**Comment by stewi2** [comment]
This appears to be a rate limit imposed by Github: https://developer.github.com/v3/#rate-limiting

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour

```
Status: 403 Forbidden
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1562799734
```

**Comment by jrochkind** [comment]
Hmm, the docs you link to are about the Github API. I don't believe travis (or anyone else) is using the Github API (making "API requests using Basic Authentication or OAuth"), are they?

But it's possible Github has other undocumented rate limits on what URLs the rvm installation process does use. That Github uses 403 for rate limits for API requests does suggest that intermittent 403s are probably a rate limit. 

It's probably a lot higher than 60/minute for something that's not an API request -- but shared CI infrastructure running lots of jobs is potentially going to make a LOT of requests from the same IP addresses. 

I wonder if it would be possible/advisable to host the files necessary to download rvm on something that is not rate limited (say, fronted by a CDN or something). 

I have not been having this problem myself, it cleared up for me; it sounds like it's likely I'll run into it again though. If I do, I will implore Travis to work with rvm maintainers to resolve the issue -- using travis for ruby projects is heavily reliant on rvm, and travis's documented features use rvm.

**Comment by jrochkind** [comment]
Really travis ought to have their own local cache of rvm downloads, since nearly every ruby travis job is going to try to do it. 

But if the rvm install process requires checking a Github API before you even know what terminal URL you should cache... it may be difficult for travis to figure out where/what/how to cache when. 

Making the rvm install process more amenable to an intermediate cache would be another possible direction. Probably still by making it not need a github API call.

**Comment by stewi2** [comment]
Here's a workaround (after reading the Travis code: https://github.com/travis-ci/travis-build/blob/cadd246abd89be8c74e791df4fc8dcb0c08f5e96/lib/travis/build/script/shared/rvm.rb#L122):

Travis will only update rvm if you specify the rvm version in the .travis.yml file. It will not do it if it uses the .ruby-version file inside the repo instead:

```
          def use_ruby_version_file
            sh.fold('rvm') do
              sh.cmd 'rvm use $(< .ruby-version) --install --binary --fuzzy'
            end
          end
```
