### ISSUE TITLE
Discussion: Should rvm-installer randomize the order of where it pulls RVM versions from?

### ISSUE THREAD

**Issue by sfgeorge** [rvm/rvm#4729]
I wanted to open this question for discussion, should we always pull RVM versions from GitHub first, or randomize the ordering?

### A. Current default behavior: GitHub-first
 1. rvm-installer always hits the GitHub API first.
 2. If GitHub fails (such as because of 403 Forbidden rate-limiting), then Bitbucket is tried.

Because of the above behavior, even when we succeed with Bitbucket, we've made an obligatory hit to GitHub.  It's probably not a big deal as don't believe this further exacerbates an API rate-limiting lock-out period, but I could be wrong.

### B. Proposed behavior: Randomize between GitHub-first or BitBucket-first
1. Randomize a copy of our array of default sources, so that sometimes Bitbucket is attempted first.
2. Proceed through Bitbucket-then-GitHub or Github-then-Bitbucket attempts.

Pros
* By evenly distributing API requests across sources, we may very well avoid clients from getting api rate-limited when they otherwise would.

Cons
* Randomizing / non-deterministic behavior leads to confusion for users.  Reports of "It seems to work after I try to install 3 or so times ..." may become more prevalent.
* It feels perhaps less _canonical_ then having GitHub be the absolute, primary source of truth.

**Comment by pkuczynski** [comment]
I would stick to current behavior (github first). We are working on github and pushing to bitbucket only when releasing. So `get master` always needs to come from github for example.

 @mpapis?

**Comment by mpapis** [comment]
Each of the hosts theoretically has similar chances of failing, randomizing it might only make it harder to debug.
