### ISSUE TITLE
gpg: BAD signature from Piotr Kuczynski

### ISSUE THREAD

**Issue by Jack12816** [rvm/rvm#4736]
## Description

Broke a few minutes ago. Yesterday/today the GPG key was fine.
Seams to be related: https://github.com/rvm/rvm/issues/4677

## Steps to reproduce

```
gpg2 --recv-keys \
  409B6B1796C275462A1703113804BB82D39DC0E3 \
  7D2BAF1CF37B13E2069D6956105BD0E739499BDB      
```

## Expected behavior

No `gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"`

## Actual behavior

```
gpg: key D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 60 new signatures
gpg: key 39499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 2
gpg:               imported: 1  (RSA: 1)
gpg:         new signatures: 60
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /home/travis/.rvm/archives/rvm-installer.asc
gpg: Signature made Fri 12 Jul 2019 09:08:29 AM UTC using RSA key ID 39499BDB
gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found. Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).
GPG signature verification failed for '/home/travis/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'! Try to install GPG v2 and then fetch the public key:
    gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
or if it fails:
    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
the key can be compared with:
    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis
NOTE: GPG version 2.1.17 have a bug which cause failures during fetching keys from remote server. Please downgrade or upgrade to newer version (if available) or use the second method described above.
/home/travis/.rvm/scripts/functions/cli: line 243: return: _ret: numeric argument required
```

Thanks for taking care :)

**Comment by maxkerp** [comment]
I can confirm this. About 15 of our machines which are provisioned with puppet yell at us in our monitoring with the same error message. I believe the `binscripts/rvm-installer.asc` needed to be updated after the last merge?

**Comment by sfgeorge** [comment]
Hey guys, sorry about this.  As @maxkerp detected, we forgot to sign `binscripts/rvm-installer.asc` following the latest changes to `binscripts/rvm-installer` in #4719 .  We'll have that signature updated soon.  Sorry for the inconvenience.

**Comment by andrew-newell** [comment]
@sfgeorge is there a way those signatures could be validated in the deployment pipeline?

**Comment by pkuczynski** [comment]
Apologies, my fault! Fixed.

**Comment by sfgeorge** [comment]
@andrew-newell good call, we'll discuss how we can improve the pipeline and ensure that a failed validation doesn't get merged to master. @pkuczynski not to worry! Thanks for the quick fix, man.

**Comment by allisonwang** [comment]
I think the message when failing to install rvm also need to be fixed? I ran the second command and imported public key from @pkuczynski 
```
gpg: Can't check signature: No public key
or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -

In case of further problems with validation please refer to https://rvm.io/rvm/security
```

**Comment by pkuczynski** [comment]
How would you like this to be changed @allisonwang?

**Comment by allisonwang** [comment]
Is this an intended behavior to import your public key? I.E. when the installation fails, should we run this line to resolve the issue?
```
command curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
```

**Comment by pkuczynski** [comment]
Yes, this is a solution where my key is missing so RVM could not verify sig.
