### ISSUE TITLE
RVM source script loading is slow

### ISSUE THREAD

**Issue by vfonic** [rvm/rvm#4738]
* [x] Tested after doing `rvm get master`

## Description

Here's the long version of the story:
I needed to install ruby 2.2.3 (which failed due to some OpenSSL error).
I noticed rvm's warning message that I should update rvm. (I believe the version I was using was 1.29.7, but I'm not 100% sure on that)
So, after failed ruby installation, I gave up on that, but also ran `rvm remove 2.2.3` to make any cleanups.
Then I updated rvm with `rvm get stable`.
This is where rvm became really slow.

EDIT: I just tried `rvm get 1.29.7` but didn't help.

If I comment-out `source $HOME/.rvm/scripts/rvm` in my `~/.zshrc`, the shell becomes interactive in about 0.5s. With the line not-commented-out, it jumps to ~2s.

I also tried:

`rvm cleanup all`
`rvm reset` - this one actually made it faster, apart from when inside of projects with `Gemfile` (or I'd guess `.ruby-version` or similar)

What can I do to give you more info you might need so we can debug this further?

## Environment info

<details>

```
ruby-2.6.3:

  system:
    uname:        "Darwin Jesus.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.14"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin18.0)"
    remote_path:  "osx/10.14/x86_64"
    xcode:        "10.2.1"

  rvm:
    version:      "1.29.9 (latest)"
    updated:      "23 seconds ago"
    path:         "/Users/viktor/.rvm"
    autolibs:     "[rvm_pkg] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.6.3p62"
    date:         "2019-04-16"
    platform:     "x86_64-darwin18"
    patchlevel:   "2019-04-16 revision 67580"
    full_version: "ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]"

  homes:
    gem:          "/Users/viktor/.rvm/gems/ruby-2.6.3"
    ruby:         "/Users/viktor/.rvm/rubies/ruby-2.6.3"

  binaries:
    ruby:         "/Users/viktor/.rvm/rubies/ruby-2.6.3/bin/ruby"
    irb:          "/Users/viktor/.rvm/rubies/ruby-2.6.3/bin/irb"
    gem:          "/Users/viktor/.rvm/rubies/ruby-2.6.3/bin/gem"
    rake:         "/Users/viktor/.rvm/gems/ruby-2.6.3/bin/rake"

  environment:
    PATH:         "/Users/viktor/.rvm/gems/ruby-2.6.3/bin:/Users/viktor/.rvm/gems/ruby-2.6.3@global/bin:/Users/viktor/.rvm/rubies/ruby-2.6.3/bin:/usr/local/opt/mongodb@3.0/bin:/usr/local/opt/node@10/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/viktor/Dropbox/scripts:/Users/viktor/.rvm/bin"
    GEM_HOME:     "/Users/viktor/.rvm/gems/ruby-2.6.3"
    GEM_PATH:     "/Users/viktor/.rvm/gems/ruby-2.6.3:/Users/viktor/.rvm/gems/ruby-2.6.3@global"
    MY_RUBY_HOME: "/Users/viktor/.rvm/rubies/ruby-2.6.3"
    IRBRC:        "/Users/viktor/.rvm/rubies/ruby-2.6.3/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

</details>

**Comment by vfonic** [comment]
I did `rvm implode` and installed rvm and ruby 2.6.3 again. It seems to be fast again. :)

I'll close this issue now. If you want any more info from me for further investigation, I'm here.

**Comment by mpapis** [comment]
for whomever who hit's the slowness this is how to debug:
```zsh
__rvm_unload
set -o xtrace; PS4="+ %* %F{red}%x:%I %F{green}%N:%i%F{white} %_" source ~/.rvm/scripts/rvm; set +o xtrace
```
please gist the results
