### ISSUE TITLE
Error running '__rvm_make -j4' on Linux Mageia for ruby < 2.4

### ISSUE THREAD

**Issue by marcusmau** [rvm/rvm#4739]
Hello,

I try to install ruby 1.9.3 using rvm install, but I keep having this error during the compilation process

Error running '__rvm_make -j4',

## Steps to reproduce

**rvm install 1.9.3**

I had the exact same issue after I try :
**rvm get master
rvm install ruby-1.9.3**
and the issue is exact same if I install ruby 2.0 or 2.1 or 2.2 or 2.3
But when I install ruby 2.4 or 2.5 or 2.6, I don't have problem

I used a Rails application with ruby 1.9.3 and rails 3.0.17 and today I can't use it

* [configure.log](https://gist.github.com/marcusmau/eee0118c904b288009ed374b43d95d8f)
* [make.log](https://gist.github.com/marcusmau/155d0fad2d999fec62bae4c3b43f254c) 

## Environment info
marc@erato:~$ rvm info

system:

  system:
    uname:        "Linux erato 5.1.14-desktop-1.mga7 #1 SMP Sat Jun 22 10:35:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Mageia"
    version:      "7"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 4.4.23(1)-release (x86_64-mageia-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "mageia/7/x86_64"

  rvm:
    version:      "1.29.9-next (master)"
    updated:      "44 minutes 59 seconds ago"
    path:         "/home/marc/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         ""

  environment:
    PATH:         "/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/lib64/qt5/bin:/usr/lib64/qt4/bin:/home/marc/bin:/home/marc/bin:/home/marc/.rvm/bin:/home/marc/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by marcusmau** [comment]
I found a way to work around the problem on the internet (https://wiki.archlinux.org/index.php/RVM#Ruby_1.8.x_won.27t_compile_with_RVM_1.8.x_won.27t_compile_with_RVM). I have to install local openssl via RVM:
rvm pkg install openssl
and
rvm install 1.8.7 -C --with-openssl-dir=$HOME/.rvm/usr
rvm install 1.9.3 -C --with-openssl-dir=$HOME/.rvm/usr
rvm install 2.0 -C --with-openssl-dir=$HOME/.rvm/usr
rvm install 2.1 -C --with-openssl-dir=$HOME/.rvm/usr
rvm install 2.2 -C --with-openssl-dir=$HOME/.rvm/usr
rvm install 2.3 -C --with-openssl-dir=$HOME/.rvm/usr

RVM uses wrong OpenSSL version : Ruby versions older than 2.4 require OpenSSL 1.0 but RVM will try to build them with OpenSSL 1.1.

**Comment by nijeesh4all** [comment]
have you fixed the issue ?
