### ISSUE TITLE
Rvm 1.29.9 is not compatible with Rubymine 2019.1.2

### ISSUE THREAD

**Issue by alexandru-calinoiu** [rvm/rvm#4741]
## Description

After updating to 1.29.9 rvm is not longe recognized by Rubymine 2019.1.2

## Steps to reproduce

 1. Install rvm 1.29.9
 2. Start Rubymine and create a new project, select rails and notice that there are no ruby interpreters

## Expected behavior

All ruby versions recognized by rvm should be visible

## Actual behavior

No ruby versions are visible

## Environment info

```
ruby-2.6.3@.tour3:

  system:
    uname:        "Linux x1-extreme 5.2.1-zen1-1-zen #1 ZEN SMP PREEMPT Sun Jul 14 14:53:00 UTC 2019 x86_64 GNU/Linux"
    name:         "Arch"
    version:      "libc-2.29"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 5.0.7(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "arch/libc-2.29/x86_64"

  rvm:
    version:      "1.29.8 (1.29.8)"
    updated:      "4 minutes 14 seconds ago"
    path:         "/home/calin/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.6.3p62"
    date:         "2019-04-16"
    platform:     "x86_64-linux"
    patchlevel:   "2019-04-16 revision 67580"
    full_version: "ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]"

  homes:
    gem:          "/home/calin/.rvm/gems/ruby-2.6.3@.tour3"
    ruby:         "not set"

  binaries:
    ruby:         "/home/calin/.rvm/rubies/ruby-2.6.3/bin/ruby"
    irb:          ""
    gem:          "/home/calin/.rvm/rubies/ruby-2.6.3/bin/gem"
    rake:         "/home/calin/.rvm/gems/ruby-2.6.3@.tour3/bin/rake"

  environment:
    PATH:         "/home/calin/.rvm/gems/ruby-2.6.3@.tour3/bin:/home/calin/.rvm/gems/ruby-2.6.3@global/bin:/home/calin/.rvm/rubies/ruby-2.6.3/bin:/home/calin/.rvm/bin:/home/calin/.pyenv/shims:/home/calin/.cargo/bin:/home/calin/.nvm/versions/node/v12.3.1/bin:/home/calin/Android/Sdk/bundle-tools:/home/calin/Android/Sdk/bundle-tool:/bin:/usr/lib/jvm/java-8-openjdk/bin:/home/calin/.yarn/bin:/home/calin/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
    GEM_HOME:     "/home/calin/.rvm/gems/ruby-2.6.3@.tour3"
    GEM_PATH:     "/home/calin/.rvm/gems/ruby-2.6.3@.tour3:/home/calin/.rvm/gems/ruby-2.6.3@global"
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ".tour3"
```

**Comment by pkuczynski** [comment]
I am using Rubymine and do not have this problem. You need to configure your project in RVM and select installed sdk

**Comment by alexandru-calinoiu** [comment]
@pkuczynski of course I did.

There is something braken in the env setup, because after update it will throw a strange path error in the terminal also.

If there are no other reports then I will have to check my env, I can easily reproduce the issue by switching between versions.

**Comment by pkuczynski** [comment]
Try getting lates rvm `rvm get master` and let me know if that helps? We made a fix recently regarding the environment.

**Comment by ryanpool** [comment]
I am having a similar problem.  It may be the same problem, but my symptoms are slightly different.

I didn't have a problem until I upgraded to 1.29.9.  I don't know what previous version of RVM I had.  I'm using RubyMine 2019.2.

After finding this thread I upgraded to RVM master (1.29.9-next) but that did not change anything.  I do not have any strange path errors.  In RubyMine I do see one version of 
Ruby, but it doesn't have the RVM: tag on it.

Anything I can do to help troubleshoot I'm game.

**Comment by ryanpool** [comment]
I don't update RVM all that often.  I did it this time because I wanted to see if the MRI 2.7 preview was available.  

I don't even remember what version of RVM I had before updating to 1.29.9.  I thought I would downgrade my RVM version to see if I could fix the problem that way.  I ended up going back to 1.27.0 and the problem persisted.  I decided to implode RVM and start over with an older version and upgrade through a few versions to see if I could identify when the problem occurred.  I started with 1.27.0, then 1.28.0, then 1.29.0, 1.29.1, got bored and skipped to 1.29.8, and everything still worked.  I went all the way to 1.29.9 (not master) and surprise surprise, everything still works perfectly.  

Maybe something was corrupted in an upgrade and the implode cleaned it up.

**Comment by pkuczynski** [comment]
I just updated to RubyMine 2019.2 and everything works fine. I can not reproduce your issue, so I can't say when it could break for you...

**Comment by ryanpool** [comment]
Yeah, I can't recreate the problem either, I just wanted to add what fixed it for me in case anyone else sees this down the road.

**Comment by jcfjcosta** [comment]
Had this issue recently, marking a ruby version as default in RVM solved it for me. Leaving this as possible solution for anyone coming here through search as I did.
