### ISSUE TITLE
No binaries for Ruby MRI before 2.0

### ISSUE THREAD

**Issue by felipec** [rvm/rvm#4748]
## Description

There are no binaries for versions of Ruby before 2.0.

## Steps to reproduce

    rvm use 1.9.3 --install --binary --fuzzy

## Expected behavior

It works.

## Actual behavior

It doesn't work.

**Comment by raelgc** [comment]
Please, add the full details requested, like the Environment Info.

**Comment by felipec** [comment]
Everywhere? Even in Travis-CI.

**Comment by havenwood** [comment]
@felipec Binaries are specific a particular version of an OS/distro. If there are multiple OSes and versions that you're seeing missing binaries for, let us know which. There are some gaps due to lack of contributors available to provide binaries. Contributions are welcome! If you have time to let us know which systems you'd like binaries for, someone might be inspired to contribute.

**Comment by havenwood** [comment]
@felipec A side note, but Ruby 2.3 is past end of life. Rubies older than 2.0, particularly older than 1.9, don't compile on modern systems without substantial patches. Security patches would have to be backported. I think folk should be using modern Rubies and don't personally have any interest in providing unsupported Ruby binaries for modern systems.

**Comment by felipec** [comment]
Where is the list of binaries for each specific OS/distro? As far as I understand the x86_64 binaries should work for pretty much every Linux distro.

Anyway. I guess people can just stop testing for older Ruby versions.

**Comment by havenwood** [comment]
The x86_64 binaries are statically linked to various dependencies and aren't portable between divergent distros. You can see the [list of binaries in the checksum metadata](https://github.com/rvm/rvm/blob/1.29.9/config/sha512#L25-L653).

I'll close this issue, but please reopen if you have a specific Linux distro and a use case for testing ancient Rubies.

**Comment by felipec** [comment]
Static libraries have no dependencies, only dynamically linked libraries do. And in that list there's for example only two packages for ruby-2.6.3. So, where are the different tarballs for Fedora, OpenSUSE, or ArchLinux? I think all three use the same one.

**Comment by havenwood** [comment]
As far as I understand, some binaries can be shared between like distros. Some cannot. I don't have context on the various reasons. @raelgc might have more to say there.

If you'd like to explore additional binaries for modern Rubies, I'd be happy to assist in any way I can or help you get context with another maintainer who has worked with the statically linked Linux builds. (I've only built the macOS ones for RVM and have no experience building the Linux ones.) This is a volunteer run project, so folk with interest often maintain particular areas. I personally have zero interest in binaries for long-dead Rubies.

**Comment by raelgc** [comment]
@havenwood I'm building, as volunteer too, the binary for Ubuntu, so basically I'm building for the Ubuntu version I'm using in my desktop (18.04 until the 20.04 release).

@felipec You're welcome to build other binaries or investigate if they'll work in the list of platforms you've mentioned.

**Comment by felipec** [comment]
I'm quite familiar on how dynamic linking works in Linux; there's ways to compile to minimize dependencies so the binaries work on as many Linux distributions as possible. That's the whole reason library versions exist, and there's a version specifically for binary backwards compatibility.

Anyway. The platform I was talking about is Travis-CI, which AFAIK mainly uses Ubuntu Xenial. Either way I can't see any list of binaries for different distros anywhere.

I'll simply stop testing for 1.9.x on my programs, because as you say it's ancient anyway. But I find it curious that for example `rvm help install` uses 1.9.2 as example. If it's so ancient why is it used in the help as reference?

But say I wanted to provide the binaries for certain platform. How would I do that? Where do I upload them? How do I know other people can make use of them? All that information seems to be quite scarce.

**Comment by raelgc** [comment]
@felipec If you want, we can add you to the Slack channel, so we can help you with the binaries.

But basically these are the steps I'm following:

Pre-Requisite: get your `ssh` key added to the rvm server (ask in the Slack channel). Then:

1. install target ruby version with `rvm install <version> --movable` (of course, replacing `<version>`)
2. run `rvm prepare <version>` (again, replacing `<version>`)
3. upload `bz` files in the server using the `prepare` output instructions
4. clone rvm/rvm git repo, update `config/remote`, `config/md5`, `config/sha512` and `CHANGELOG.md` with new rubies using the checksums provided by the `prepare` command output; create a pull request with these changes
