### ISSUE TITLE
BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"

### ISSUE THREAD

**Issue by linearbag** [rvm/rvm#4750]
## Description

I installed rvm (latest 1.29.9) according to https://rvm.io/rvm/security today for several times, get error:
gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.9.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.9/1.29.9.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

## Steps to reproduce

 1.gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
 2. echo 409B6B1796C275462A1703113804BB82D39DC0E3:6: | gpg2 --import-ownertrust # mpapis@gmail.com
echo 7D2BAF1CF37B13E2069D6956105BD0E739499BDB:6: | gpg2 --import-ownertrust # piotr.kuczynski@gmail.com
 3. \curl -sSL https://get.rvm.io | bash -s stable
4.out put:
Downloading https://github.com/rvm/rvm/archive/1.29.9.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.9/1.29.9.tar.gz.asc
gpg: Signature made Wed Jul 10 16:31:02 2019 CST using RSA key ID 39499BDB
gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.9.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.9/1.29.9.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

## Expected behavior

gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>"
GPG signature verification failed for '/usr/local/rvm/archives/rvm-1.29.9.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.9/1.29.9.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

/]# rvm
bash: rvm: command not found
have not installed rvm.

**Comment by linearbag** [comment]
/]# \curl -sSL https://get.rvm.io | bash
Downloading https://github.com/rvm/rvm/archive/master.tar.gz

gzip: stdin: decompression OK, trailing garbage ignored
gtar: Child returned status 2
gtar: Error is not recoverable: exiting now
Could not extract RVM sources.
Downloading https://bitbucket.org/mpapis/rvm/get/master.tar.gz

gzip: stdin: decompression OK, trailing garbage ignored
gtar: Child returned status 2
gtar: Error is not recoverable: exiting now
Could not extract RVM sources.

**Comment by pkuczynski** [comment]
Well, not sure whats your toolset. For me master unzgips just fine. Nobody else seems to report similar issue either and last update to master was on 30th July...

**Comment by valdrinium** [comment]
I have the same issue

**Comment by pmontrasio** [comment]
Exactly the same issue today (I was trying to upgrade rvm to install Ruby 3).

Either `rvm get stable` or `\curl -sSL https://get.rvm.io | bash -s stable` end with

```
Downloading https://github.com/rvm/rvm/archive/1.29.11.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.11/1.29.11.tar.gz.asc
gpg: Signature made Tue Dec 29 14:40:04 2020 CET
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: BAD signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
GPG signature verification failed for '/home/montra/.rvm/archives/rvm-1.29.11.tgz' - 'https://github.com/rvm/rvm/releases/download/1.29.11/1.29.11.tar.gz.asc'! Try to install GPG v2 and then fetch the public key:

    gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
    command curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -

In case of further problems with validation please refer to https://rvm.io/rvm/security
```

I didn't have `gpg2`. I installed it and run `gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB` with exit code 0. It still fails.
