### ISSUE TITLE
Current stable version cause remote ssh failed

### ISSUE THREAD

**Issue by Lumuy** [rvm/rvm#4762]
> ➜  ~ rvm --version
rvm 1.29.9 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

>  Ubuntu 18.04.3 LTS

SSH error info

> free(): invalid next size (fast)

If i remove RVM, it's ok.

**Comment by pkuczynski** [comment]
Could you explain in a bit more details what do you try to do?

**Comment by Lumuy** [comment]
@pkuczynski 

I plan to use RVM to install ruby on a remote fresh new server via ssh. After I installed RVM, disconnect ssh tunnel. Next time, if I try to use ssh to connect my server, ssh will fail. But if I
removed the RVM installed, it will success.

It's like this.

-        ssh user@server
-        install RVM
-        Logout
-        ssh user@server ------------->> fail
-        remove RVM
-        Logout
-        ssh user@server ------------->> success

**Comment by pkuczynski** [comment]
Hmm, this is very strange. Without having access to the machine, we are not able to debug, I am afraid you have to do that...

**Comment by Lumuy** [comment]
@pkuczynski 

The error info in **/var/log/auth.log** is

> sshd[32248]: error: Could not load host key: /etc/ssh/ssh_host_ed25519_key

Solution is

> ssh-keygen -A && service ssh restart

[related](https://askubuntu.com/questions/626372/could-not-load-host-key-etc-ssh-ssh-host-ed25519-key-in-var-log-auth-log)

It's like **INSTALL RVM** change my ssh service behaviour.

**Comment by pkuczynski** [comment]
RVM is not doing anything with ssh, but it might modify paths in your profile. Not sure how SSH could be affected by RVM install...
