### ISSUE TITLE
Getting error of rvm

### ISSUE THREAD

**Issue by ishtiyaquekhan1411** [rvm/rvm#4773]
rvm error with status when i am trying to install rubyh 100.
I check rvm -v showing 1.29.9.
but not getting any rvm install there showing -bash: /home/ishtiyaque/.rvm/scripts/rvm: No such file or directory

**Comment by havenwood** [comment]
> rvm error with status when i am trying to install rubyh 100.

What command are you running that fails? What's the error output?
