### ISSUE TITLE
When I 'set -a' in shell to ensure export variables, 'rvm reinstall' throws bash errors

### ISSUE THREAD

**Issue by dfuentes77** [rvm/rvm#4775]
## Description

I normally have `set -a` in my `~/.bashrc` to ensure export environment variables are exports to all child processes.  When trying to reinstall a ruby via rvm I get a bunch a of bash errors with `Argument list too long`

## Steps to reproduce

```
$ set -a
$ rvm reinstall 2.5.1
-bash: /bin/cat: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/find: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/grep: Argument list too long
-bash: /usr/bin/tail: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/sort: Argument list too long
-bash: /usr/bin/find: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/grep: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/tail: Argument list too long
-bash: /usr/bin/sort: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/sed: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/head: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /usr/bin/sort: Argument list too long
-bash: /Users/<username>/.rvm/scripts/tools: Argument list too long
-bash: /usr/bin/stat: Argument list too long
-bash: /bin/cat: Argument list too long
-bash: /usr/bin/stat: Argument list too long
-bash: /bin/date: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /bin/mkdir: Argument list too long
-bash: /bin/rm: Argument list too long
-bash: /bin/date: Argument list too long
-bash: /usr/bin/tee: Argument list too long
-bash: /bin/cat: Argument list too long
ruby-2.5.1 - #removing src/ruby-2.5.1Error running '__rvm_rm_rf /Users/<username>/.rvm/src/ruby-2.5.1',
please read /Users/<username>/.rvm/log/_ruby-2.5.1/remove.src.log
-bash: /bin/date: Argument list too long
-bash: /usr/bin/awk: Argument list too long
-bash: /bin/mkdir: Argument list too long
-bash: /bin/rm: Argument list too long
-bash: /bin/date: Argument list too long
-bash: /usr/bin/tee: Argument list too long
-bash: /bin/cat: Argument list too long
ruby-2.5.1 - #removing src/ruby-2.5.1Error running '__rvm_rm_rf /Users/<username>/.rvm/src/ruby-2.5.1',
please read /Users/<username>/.rvm/log/_ruby-2.5.1/remove.src.log
-bash: /bin/df: Argument list too long
-bash: /usr/bin/awk: Argument list too long
Not enough space (0MB) to install ruby (440MB).
```

## Expected behavior

It should just attempt to install to ruby

## Environment info

ruby-2.5.1:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  system:
    uname:        "Darwin me.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.14"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin18.0)"
    remote_path:  "osx/10.14/x86_64"
    xcode:        ""

  rvm:
    version:      "1.29.9-next (master)"
    updated:      "2 hours 47 minutes 55 seconds ago"
    path:         "/Users/<username>/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.3.7p456"
    date:         "2018-03-28"
    platform:     "universal.x86_64-darwin18"
    patchlevel:   "2018-03-28 revision 63024"
    full_version: "ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]"

  homes:
    gem:          "/Users/<username>/.rvm/gems/ruby-2.5.1"
    ruby:         "/Users/<username>/.rvm/rubies/ruby-2.5.1"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/Users/<username>/.rvm/gems/ruby-2.5.1/bin:/Users/<username>/.rvm/gems/ruby-2.5.1@global/bin:/Users/<username>/.rvm/rubies/ruby-2.5.1/bin:/Users/<username>/.rvm/bin:/Users/<username>/.nvm/versions/node/v10.16.0/bin:/Users/<username>/.pyenv/shims:/Users/<username>/.chefdk/gem/ruby/2.6.0/bin:/usr/local/homebrew/opt/mysql-client/bin:/Users/<username>/misc/sparkpost_cli/osx:/usr/local/homebrew/opt/curl/bin:/Users/<username>/Library/Haskell/bin:/Users/<username>/bin:/usr/local/homebrew/bin:/usr/local/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    GEM_HOME:     "/Users/<username>/.rvm/gems/ruby-2.5.1"
    GEM_PATH:     "/Users/<username>/.rvm/gems/ruby-2.5.1:/Users/<username>/.rvm/gems/ruby-2.5.1@global"
    MY_RUBY_HOME: "/Users/<username>/.rvm/rubies/ruby-2.5.1"
    IRBRC:        "/Users/<username>/.rvm/rubies/ruby-2.5.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

```

**Comment by t12nslookup** [comment]
personally I find the "set -a" to be lazy and horrible.  can you not just "source <script>", or ". <script>" (dot-space for shorthand) when you need to set the environment variables in the parent session?

**Comment by dfuentes77** [comment]
Yes, you can do that here.  But if you have other CLI commands that fork child processes that also need the environment variables, you actually need `set -a`.  `set -a` tells the shell to ensure that all child processes also get the environment variables.  And many times you can't help what a command or software does.  Many often double fork and that `set -a` is all you can do to make sure that the last child process gets the environment variables it needs.  Which is why I just put `set -a` in my `.bashrc` so that it's always there.  I'm on the CLI all day and I use numerous tools and I have only had a issue with it and `rvm`

**Comment by t12nslookup** [comment]
I would fix my scripts so that I didn't need it.

I would definitely not set it by default, and if I couldn't get away with it, I'd make a wrapper for the particular scripts or programs that do rely on it
