### ISSUE TITLE
Cannot update RVM

### ISSUE THREAD

**Issue by pronebird** [rvm/rvm#4800]
```
rvm get stable
Downloading https://get.rvm.io
Downloading https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc
Verifying /Users/pronebird/.rvm/archives/rvm-installer.asc
gpg: Signature made Tue Jul 23 23:59:45 2019 CEST
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Can't check signature: No public key
Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

GPG signature verification failed for '/Users/pronebird/.rvm/archives/rvm-installer' - 'https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer.asc'!
try downloading the signatures:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -

the key can be compared with:

    https://rvm.io/mpapis.asc

```

No luck even after adding the key to macgpg

**Comment by raelgc** [comment]
And what happens if you follow the suggested command:

    gpg2 --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

and try again?

**Comment by pronebird** [comment]
@raelgc 

```
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

the rvm I have on my mac is

```
rvm --version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
```

**Comment by pronebird** [comment]
@raelgc so I've double checked and the original error mentions this:

```
Verifying /Users/pronebird/.rvm/archives/rvm-installer.asc
gpg: Signature made Tue Jul 23 23:59:45 2019 CEST
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Can't check signature: No public key
```

and it seems that the rvm-installer is signed with some other key `7D2BAF1CF37B13E2069D6956105BD0E739499BDB`. But I am not sure I can trust the `7D2BAF1CF37B13E2069D6956105BD0E739499BDB` key because it's not signed by Michal Papis as advertised.

**Comment by nessche** [comment]
If I read correctly the website both those two keys are mentioned as authorized keys. At https://rvm.io/rvm/security it says to add these two keys:

```
409B6B1796C275462A1703113804BB82D39DC0E3 # mpapis
7D2BAF1CF37B13E2069D6956105BD0E739499BDB # pkuczynski
```

**Comment by ElvenSpellmaker** [comment]
It works after adding both keys, it seems the error message should show both keys but only shows one.

**Comment by pkuczynski** [comment]
It should mention both keys. Maybe the version you had was so old, that it didn't know there are two keys?

**Comment by nessche** [comment]
> It should mention both keys. Maybe the version you had was so old, that it didn't know there are two keys?

Well I guess here we have a bit of chicken-and-egg problem, since you need to upgrade RVM to get a better message to the error that prevents you from upgrading RVM ... :)

**Comment by ElvenSpellmaker** [comment]
Mine was on `1.29.3`, with the latest stable being `1.29.9`

**Comment by josephecombs** [comment]
The error message is wrong! I had to run an additional (thanks to @nessche):

```
 gpg --keyserver hkp://keys.gnupg.net --recv-keys 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
```
