### ISSUE TITLE
Support for rvm install 2.5.7

### ISSUE THREAD

**Issue by saumier** [rvm/rvm#4803]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by raelgc** [comment]
Run `rvm get master` to get the latest rubies supported. And, please, next time, give more details (i.e., fill the placeholders).
