### ISSUE TITLE
rvm.io site  dns hosting is expired ?

### ISSUE THREAD

**Issue by control-panel** [rvm/rvm#4841]
## Description

https://www.name.com/domain/renew/rvm.io?utm_source=Sedo_parked_page&utm_medium=button&utm_campaign=Sedo_Expired_v

![image](https://user-images.githubusercontent.com/11228044/71580717-e6372200-2b12-11ea-99ce-881c90b22534.png)

**Comment by navid-farjad** [comment]
i cant get rvm get head as well

**Comment by pkuczynski** [comment]
We are working on this issue! Apologies for any inconvenience...

**Comment by OMGerCoder** [comment]
gotta buy the domain again

**Comment by Exorcist** [comment]
Please tell the IP address of the server, so that I register it in the hosts file.
Thanks!

**Comment by OMGerCoder** [comment]
Server wan ip address from `ping` command is: `91.195.240.94`

**Comment by Exorcist** [comment]
> Server wan ip address from `ping` command is: `91.195.240.94`
91.195.240.94 domain parking server.

**Comment by Exorcist** [comment]
Need rvm server IP address. Then it will be possible to register it in the hosts file, this will temporarily solve the problem

**Comment by OMGerCoder** [comment]
Ip address for Holtsville is 97.107.133.48

**Comment by OMGerCoder** [comment]
put that in the hosts file

**Comment by Exorcist** [comment]
> put that in the hosts file

Thanks, it work
![image](https://user-images.githubusercontent.com/174071/71582999-99a51400-2b1d-11ea-8472-204c1c2dc849.png)

**Comment by OMGerCoder** [comment]
not work for me

**Comment by Exorcist** [comment]
> not work for me

I put that 
![image](https://user-images.githubusercontent.com/174071/71583119-2d76e000-2b1e-11ea-85ae-002946170f1a.png)
in /etc/hosts and all work now

**Comment by SuperSandro2000** [comment]
> > not work for me
> 
> I put that
> ![image](https://user-images.githubusercontent.com/174071/71583119-2d76e000-2b1e-11ea-85ae-002946170f1a.png)
> in /etc/hosts and all work now

Perfect opportunity for injecting bad code into someones rvm installation. So for your own safety don't do that!

**Comment by OMGerCoder** [comment]
Hello, the main website is still down.

**Comment by OMGerCoder** [comment]
The main website is still down.

**Comment by navid-farjad** [comment]
> The main website (rvm.io) is still down.

I am sure everyone knows it. let's don't mention it all the time and giving people extra stress. just give it time and good luck to rvm team to fix it.

**Comment by bartj3** [comment]
For the people wanting a workaround to the site being down, according to the documentation:

> get.rvm.io is a redirect to https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer You could also use full path for the installer:

```
curl https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
```

This would be a bit more straightforward, and more obvious to your team members, than changing your hosts file.

**Comment by dgm** [comment]
It looks like it is back up to me.

**Comment by pkuczynski** [comment]
Yes, its should be back up now! We will work on preventing such issues in the future...

**Comment by SuperSandro2000** [comment]
> Yes, its should be back up now! We will work on preventing such issues in the future...

You should set the domain to auto renew and try locking it. Talk to your registrar about that.
