### ISSUE TITLE
Ruby installation

### ISSUE THREAD

**Issue by lsumner** [rvm/rvm#4860]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by lsumner** [comment]
I have never used Ruby and have no clue on the language. I am trying to install it on my Mac and need some assistance.

**Comment by pkuczynski** [comment]
Without knowing any details, we are not able to help.
