### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by tecjoint** [rvm/rvm#4867]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by raelgc** [comment]
Hi @tecjoint and thanks for raising an issue. But we cannot help you without any information provided.

I'll close this issue as you've opened 20 hours ago and didn't come back to edit it.

Feel free to re-open in case you can give us more info.
