### ISSUE TITLE
Unable to visit http://rvm.io

### ISSUE THREAD

**Issue by DevDengChao** [rvm/rvm#4870]
## Description

Unable to visit http://rvm.io

![TIM截图20200212165309](https://user-images.githubusercontent.com/16363180/74319711-58f61700-4dba-11ea-9949-a9ccef314b6e.png)

## Steps to reproduce

1. Open your brower
2. Type 'rvm.io' into its address input box
3. Enter

**Comment by pedrofurtado** [comment]
Maybe this issue can be related to a specific outage of rvm official site in that time.

@DevDengChao the error persists with you? If so, let me know, and I reopen the issue for investigation 🤝

**Comment by DevDengChao** [comment]
@pedrofurtado I can visit it now. Thanks for your reply.

**Comment by pedrofurtado** [comment]
@DevDengChao Thanks for feedback! 🤝 

Any future issues, please get in touch with us! 🎖️
