### ISSUE TITLE
GPG key installation instruction on website giving error

### ISSUE THREAD

**Issue by klsetzer** [rvm/rvm#4882]
## Description

When attempting to install using the instructions on https://rvm.io/rvm/install, an error is received.

## Steps to reproduce

```
$ gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: keyserver receive failed: No route to host
```
## Expected behavior

```
$ gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: key 105BD0E739499BDB: public key "Piotr Kuczynski <piotr.kuczynski@gmail.com>" imported
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 1 new signature
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 98 signatures cleaned
gpg: Total number processed: 2
gpg:               imported: 1
gpg:         new signatures: 1
gpg:     signatures cleaned: 98
```

## Environment info
MacOS

* System Version: macOS 10.15.3 (19D76)
* Kernel Version: Darwin 19.3.0

It should install the keys as following working example:

**Comment by pkuczynski** [comment]
Try different server. You can find list on https://rvm.io/rvm/security

**Comment by klsetzer** [comment]
Considering how frequently people experience this and how simple the solution is, why not post the alternate IPv4 URL as either the default or an alternative right on https://rvm.io/rvm/install?

For those of us who live on networks that do not have IPv6 correctly configured, having the IPv4 URL handy would be a big help.

The command is:
`gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`
