### ISSUE TITLE
sudo required to use rvm

### ISSUE THREAD

**Issue by kevr** [rvm/rvm#4890]
## Description

When installing a version of ruby via `rvm`, `rvm` attempts to update via `apt-get` if the system has some sort of pending updates.

This has issues running on machines that do not have `sudo`. Is there a way to just have `rvm` fail out nicely with an error about needing to update packages, and which packages need to be updated, instead of it trying to sudo for me to resolve the problem?

## Reproduce

1. Install a debian or ubuntu system.
2. Remove `sudo`.
3. Install `rvm` via `curl -sSL https://get.rvm.io | bash -s stable`
4. Try to install ruby 2.5.5 with rvm: `rvm install 2.5.5`

**Comment by kevr** [comment]
This is not truly a bug with `rvm`, but I wonder if defaults can be changed to support systems without sudo or admin access; like notifying the user what's missing and what needs to be installed to continue.

**Comment by pkuczynski** [comment]
Sudo is not required to install rubies as such, but might be required to install dependencies. You can disable auto installing deps, but then you need to do it manually yourself...

Installing ruby without deps is only possible when binary ruby is compiled for your OS. We have binaries mainly for Ubuntu at the moment.

**Comment by kevr** [comment]
Is there a way to have rvm list out what dependencies are missing? The sudo prompt blocked me from figuring out what it would actually need, so i just ran rvm install as a sudo-enabled user.

**Comment by raelgc** [comment]
@kevr Yes, run `rvm requirements`. Probably what you want is:

```bash
rvm autolibs disable # disable automatic package install
rvm requirements # list dependencies, but you'll need to manually install these
rvm install ruby
```

**Comment by kevr** [comment]
> @kevr Yes, run `rvm requirements`. Probably what you want is:
> 
> ```shell
> rvm autolibs disable # disable automatic package install
> rvm requirements # list dependencies, but you'll need to manually install these
> rvm install ruby
> ```

Thank you!

**Comment by Pavel077** [comment]
Looks like it is `rvm autolibs read-fail` in newer versions. Otherwise `rvm requirements` would not show missing packages.
