### ISSUE TITLE
Ubuntu 20.04 libssl1.0-dev not found, now the package is libssl-dev

### ISSUE THREAD

**Issue by drkpkg** [rvm/rvm#4918]
Ubuntu 20.04 rename libssl1.0-dev to libssl now.

```
requirements_ubuntu_define_libssl()
{
  # Legacy libssl-dev required by older version of ruby has been renamed to libssl1.0-dev
  # starting from Ubuntu 17.10 (Artful Aardvark)

  case "$1" in
    (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*|ruby-1.8*)
      if
        __rvm_version_compare ${_system_version} -ge 17.10
      then
        undesired_check libssl-dev
        requirements_check libssl-dev
      else
        requirements_check libssl-dev
      fi
      ;;

    (*)
      requirements_check libssl-dev
      ;;
  esac
}

```
If anyone has the same problem the patch inside `~/.rvm/scripts/functions/requirements/[debian, ubuntu]` is this.

**Comment by pkuczynski** [comment]
I believe the old version of ruby require old (1.0) version on openssl... Are you sure that your proposed solution works for old ruby?

**Comment by drkpkg** [comment]
Tried, not working. Maybe a manual installation of libssl1.0 or a recompile from scratch can work, gonna try this with the ubuntu 19.10 package build. Anyways this can be warning if someone wants to upgrade a production system maybe.

**Comment by MarkMT** [comment]
I ran into this problem today when trying to install rvm on Linux Mint 20 and was able to resolve it by installing libssl1.0-dev from an older repo following the guidance here: https://www.garron.me/en/linux/install-ruby-2-3-3-ubuntu.html

**Comment by raelgc** [comment]
I just build `libssl1.0-dev` on the [dedicated Ubuntu package](https://github.com/rvm/ubuntu_rvm) PPA. So, anyone using that package will have automatically this library available to install.

**Comment by omarjavierr277** [comment]
> Me encontré con este problema hoy al intentar instalar rvm en Linux Mint 20 y pude resolverlo instalando libssl1.0-dev desde un repositorio anterior siguiendo la guía aquí: [https://www.garron.me/en/linux /install-ruby-2-3-3-ubuntu.html](https://www.garron.me/en/linux/install-ruby-2-3-3-ubuntu.html)


Muchas gracias a mi me soluciono el error con este paso que compartiste
(https://www.garron.me/en/linux/install-ruby-2-3-3-ubuntu.html)

**Comment by englianhu** [comment]
> I just built `libssl1.0-dev` on the [dedicated Ubuntu package](https://github.com/rvm/ubuntu_rvm) PPA. So, anyone using that package will have automatically this library available to install.

https://github.com/rvm/ubuntu_rvm, I am using KDE and refer to https://askubuntu.com/a/503918/424049, successfully installed!

**Comment by SriHarshaKR07** [comment]
This error showing while installing libssl1.0-dev in ubuntu.
Package 'libssl1.0-dev' has no installation candidate..
plz share any suggestions 

thanks

**Comment by meetinfi** [comment]
*SOLUTION*
					
						sudo nano /etc/apt/sources.list
						add deb http://security.ubuntu.com/ubuntu bionic-security main
						sudo apt update && apt-cache policy libssl1.0-dev
						sudo apt-get install libssl1.0-dev

**Comment by lovetheguitar** [comment]
> _SOLUTION_
> 
> ```
> 					sudo nano /etc/apt/sources.list
> 					add deb http://security.ubuntu.com/ubuntu bionic-security main
> 					sudo apt update && apt-cache policy libssl1.0-dev
> 					sudo apt-get install libssl1.0-dev
> ```

This did not work for me on a RasPi (ARM). I had success with adding
`deb http://ports.ubuntu.com/ubuntu-ports bionic-security main` instead. 😄

**Comment by coolninja28** [comment]
> > _SOLUTION_
> > ```
> > 					sudo nano /etc/apt/sources.list
> > 					add deb http://security.ubuntu.com/ubuntu bionic-security main
> > 					sudo apt update && apt-cache policy libssl1.0-dev
> > 					sudo apt-get install libssl1.0-dev
> > ```
> 
> Thanks

It's still not working, is there any other way?

**Comment by raelgc** [comment]
@coolninja28 Yes, use the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm) and the old `libssl` package will be automatically available to your system.

**Comment by chuzirui** [comment]
sudo echo "deb http://ports.ubuntu.com/ubuntu-ports/ bionic  main" >> /etc/apt/sources.list
          sudo apt update && apt-cache policy libssl1.0-dev
          sudo apt-get install libssl1.0-dev

**Comment by raelgc** [comment]
@lucasldemello I don't know why people prefer add the entire old repository instead of just install the RVM ppa to get the `libssl1.0-dev`. Just follow the instructions in the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm) and you'll have the `libssl1.0-dev` available to install.

**Comment by donspablo** [comment]
> sudo apt-get install libssl1.0-dev

You are a life saver my friend, I am with you 100% regarding the key and stuff 🤣

**Comment by slshults** [comment]
Thanks @lucasldemello .  Your solution at https://github.com/rvm/rvm/issues/4918#issuecomment-1134671651 still works, as of Dec. 17. 2022 (I'm having to get Ruby 2.3.0 installed to revive an old website, and was blocked by rvm's inability to install libssl1.0-dev, thanks for the save. ChatGPT couldn't even help me with this one.)

**Comment by ssgumera23** [comment]
> _SOLUTION_
> 
> ```
> 					sudo nano /etc/apt/sources.list
> 					add deb http://security.ubuntu.com/ubuntu bionic-security main
> 					sudo apt update && apt-cache policy libssl1.0-dev
> 					sudo apt-get install libssl1.0-dev
> ```

Thank you!!

**Comment by surdialesera** [comment]
This led me in the right direction. I was able to get rvm to install an older ruby on Ubuntu 24.04.1 LTS

`sudo nano /etc/apt/sources.list.d/ubuntu_old_lib_source.list`
Added the line below 
`deb [trusted=yes] http://security.ubuntu.com/ubuntu bionic-security main`
Then ran the following commands
`sudo apt update && apt-cache policy libssl1.0-dev
 rvm pkg install openssl
 rvm install ruby-2.3.1 --with-openssl-dir=/home/$(whoami)/.rvm/usr
`
