### ISSUE TITLE
How can we publish new binaries?

### ISSUE THREAD

**Issue by mathieujobin** [rvm/rvm#4921]
## Description

We often see this warning `No binary rubies available for: ubuntu/20.04/x86_64/ruby-2.4.10.`

I found out its looking at binaries at this location
https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/

right now, I only see 2.6.6

## Steps to reproduce

 1. rvm get master
 2. rvm install 2.4.10
 3. rvm install 2.5.8
 4. rvm install 2.7.1

## Expected behavior

new binaries for most common rubies should be pushed
so many people building these, I wonder hasn't no one pushed their binaries yet?

## Actual behavior

no binaries

**Comment by raelgc** [comment]
Hi @mathieujobin and thanks for raising this issue.

Right now I'm the only one compiling binaries, as a volunteer, for Ubuntu.

I've installed 20.04 last week, but still had no time to prepare more binaries (I'm having a heavy time in my job).

Until the next weekend I'll prepare these binaries.

**Comment by pkuczynski** [comment]
We always welcome new binary builders. @mathieujobin if you would be interested in becoming one, I can add you for our slack so we can discuss the details?

**Comment by mrchucho** [comment]
I've built a ruby-2.5.8 binary for CentOS 7. I'm happy to upload and create a PR.

```
Preparing ruby-2.5.8 ...
Prepared ruby-2.5.8.tar.bz2.
--- upload:
ssh "rvm@ssh.rvm.io" "mkdir -p ~/site/shared/public/binaries/centos/7/x86_64/"
scp "ruby-2.5.8.tar.bz2" "rvm@ssh.rvm.io:~/site/shared/public/binaries/centos/7/x86_64/ruby-2.5.8.tar.bz2"
--- rvm/config/remote:
https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.5.8.tar.bz2
--- rvm/config/md5:
https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.5.8.tar.bz2=a192ca67846f7e8fa83a34917fbcf458
--- rvm/config/sha512:
https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-2.5.8.tar.bz2=97925257fe9c6a6dcaaf607469b37efb33d2f18b5d55c067d4f01c91f30ba4f2a36f55980672ac375dca35fab62a4bbfc9babf93cc49fcd7327099b2c8c6a30f
```

**Comment by dgpokl** [comment]
> We always welcome new binary builders. @mathieujobin if you would be interested in becoming one, I can add you for our slack so we can discuss the details?

Is this also the only reason that there haven't been mac binaries since 2016? I wonder how many kilowatts of electricity have been spent compiling ruby on every developer mac in 4 years. If you need a volunteer for catalina I'd sign up.

**Comment by svetam** [comment]
@pkuczynski, macOS is still missing builds since 2016. I would like to help if you are missing macOS binary builder? I have 3 machines running Big Sur, Catalina and Mojave.

**Comment by pkuczynski** [comment]
@svetam what's your email? I will add you to our slack and we can discuss this in more details...

**Comment by jeffshantz** [comment]
Are RVM binaries no longer being pushed?  I see under https://rvm.io/binaries/ that no distros have received any updates in quite some time.  I'd be happy to volunteer to push binaries for multiple distros, if interested.

**Comment by jeffshantz** [comment]
My email is foss@jeffshantz.com

**Comment by pkuczynski** [comment]
@jeffshantz I just invited you to our slack, where you can discuss the details with the team...

**Comment by mathieujobin** [comment]
I can push binaries for ubuntu 22.04 and osx 10.15

**Comment by mathieujobin** [comment]
@pkuczynski I sent you a message on Keybase

**Comment by pkuczynski** [comment]
I replied @mathieujobin :)

**Comment by noizwaves** [comment]
Hey @pkuczynski, I'd love to join the Slack too and learn more about building ruby binary installations, and may have some to volunteer. Would it be possible to get an invite? My email addess is rvm_slack [at] noizwaves [dot] com. Thanks!

**Comment by pkuczynski** [comment]
> Hey @pkuczynski, I'd love to join the Slack too and learn more about building ruby binary installations, and may have some to volunteer. Would it be possible to get an invite? My email addess is rvm_slack [at] noizwaves [dot] com. Thanks!

Invite sent...

**Comment by loqimean** [comment]
> We always welcome new binary builders. @mathieujobin if you would be interested in becoming one, I can add you for our slack so we can discuss the details?

Hi, I'm interesting to upload binaries for ruby at osx. That would be cool, so, add me to the slack please: vanuha277 [at] gmail [dot] com. Thanks!

**Comment by pkuczynski** [comment]
Invite send @loqimean

**Comment by pradeepnarava** [comment]
Hi @pkuczynski  
I want to upload ruby 3.3.7 binary  to centos, what is the process to upload to rvm.io, can anyone help on this?

**Comment by pradeepnarava** [comment]
Hi @pkuczynski ,
Can you please add me at pradeep.narava at_the_rate_gmail_dot_com
