### ISSUE TITLE
RVM does not detect multiple cores on Raspberry Pi 4 (8GB) running Debian 10

### ISSUE THREAD

**Issue by jhwinters** [rvm/rvm#4945]
## Description

On a Raspberry Pi 4 (8GB) running latest Debian 10 for 64 bit ARM, a command like:

$ rvm install ruby-2.6.6

works fine, except that it uses only one of the 4 cores for compilation.  If instead one types:

$ rvm install ruby-2.6.6 -j 4

it does it in less than half the time, but whinges slightly saying the "-j 4" bit is unnecessary.

"Found user configured '-j' flag in 'rvm_make_flags', please note that RVM can detect number of CPU threads and set the '-j' flag automatically if you do not set it."

## Steps to reproduce

$ rvm install ruby-2.6.6

## Expected behavior

I would expect it to use all the available cores automatically, as it seems to claim to do.

## Actual behavior

It compiles using just one core.

## Environment info

ruby-2.6.6:

  system:
    uname:        "Linux pi48 5.4.42-v8+ #1319 SMP PREEMPT Wed May 20 14:18:56 BST 2020 aarch64 GNU/Linux"
    name:         "Debian"
    version:      "10"
    architecture: "arm64"
    bash:         "/bin/bash => GNU bash, version 5.0.3(1)-release (aarch64-unknown-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "debian/10/arm64"

  rvm:
    version:      "1.29.10 (latest)"
    updated:      "1 hour 11 minutes 24 seconds ago"
    path:         "/home/john/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.6.6p146"
    date:         "2020-03-31"
    platform:     "aarch64-linux"
    patchlevel:   "2020-03-31 revision 67876"
    full_version: "ruby 2.6.6p146 (2020-03-31 revision 67876) [aarch64-linux]"

  homes:
    gem:          "/home/john/.rvm/gems/ruby-2.6.6"
    ruby:         "/home/john/.rvm/rubies/ruby-2.6.6"

  binaries:
    ruby:         "/home/john/.rvm/rubies/ruby-2.6.6/bin/ruby"
    irb:          "/home/john/.rvm/rubies/ruby-2.6.6/bin/irb"
    gem:          "/home/john/.rvm/rubies/ruby-2.6.6/bin/gem"
    rake:         "/home/john/.rvm/rubies/ruby-2.6.6/bin/rake"

  environment:
    PATH:         "/home/john/.rvm/gems/ruby-2.6.6/bin:/home/john/.rvm/gems/ruby-2.6.6@global/bin:/home/john/.rvm/rubies/ruby-2.6.6/bin:/home/john/.rvm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games"
    GEM_HOME:     "/home/john/.rvm/gems/ruby-2.6.6"
    GEM_PATH:     "/home/john/.rvm/gems/ruby-2.6.6:/home/john/.rvm/gems/ruby-2.6.6@global"
    MY_RUBY_HOME: "/home/john/.rvm/rubies/ruby-2.6.6"
    IRBRC:        "/home/john/.rvm/rubies/ruby-2.6.6/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

john@pi48:~$

**Comment by cure** [comment]
I am seeing the same problem on aarch64 cloud nodes.

**Comment by pkuczynski** [comment]
Only added the label, but not being able to work on this as I dont use netiher Debian or Raspberry Pi. But I would welcome a PR if you want to invest time?

**Comment by pkuczynski** [comment]
No, unfortunately not :(

**Comment by pkuczynski** [comment]
Fix merged into master! Thank you @darkBuddha
