### ISSUE TITLE
我改如何自定义安装rvm的路径呢？

### ISSUE THREAD

**Issue by xinsir88** [rvm/rvm#4958]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by raelgc** [comment]
Please, enter all requested details, so we can re-open this issue if required.

**Comment by xinsir88** [comment]
Hello, I use the installation method provided by the official website, rvm is installed under ~/.rvm, I think it is installed under /opt, how to do this change? ?
