### ISSUE TITLE
Error when trying to update rvm

### ISSUE THREAD

**Issue by COAB1** [rvm/rvm#4970]
## Description

When I tried to update RVM to change my ruby version from 2.7.1 to 2.7.0, I run the ```$ rvm get stable --auto-dotfiles``` and keep getting the "Cannot utime: Operation not permitted" error alongside with the final message "Exiting with failure status due to previous errors. Could not extract RVM sources. Could not update RVM, please report to https://github.com/rvm/rvm/issues"

## Steps to reproduce

 1. OS: Linux 20.04
 2. Comands on terminal: $ rvm rvm get stable --auto-dotfiles
                                         $ rvm get master
                                

## Expected behavior

I expected to successfully update rvm.

## Actual behavior

* [$ rvm get stable --auto-dotfiles](https://gist.github.com/COAB1/265d8bf3110bd842dbd2569cd7a8c59f)
* [$ rvm get master](https://gist.github.com/COAB1/93a5b88ce8393b802d33be58134251f1)

## Environment info

ruby-2.7.0:

  system:
    uname:        "Linux carol-asus 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "20.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/20.04/x86_64"

  rvm:
    version:      "1.29.10 (manual)"
    updated:      "9 days 43 minutes 45 seconds ago"
    path:         "/usr/share/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.7.0p0"
    date:         "2019-12-25"
    platform:     "x86_64-linux"
    patchlevel:   "2019-12-25 revision 647ee6f091"
    full_version: "ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]"

  homes:
    gem:          "/home/carol/.rvm/gems/ruby-2.7.0"
    ruby:         "/usr/share/rvm/rubies/ruby-2.7.0"

  binaries:
    ruby:         "/usr/share/rvm/rubies/ruby-2.7.0/bin/ruby"
    irb:          "/usr/share/rvm/rubies/ruby-2.7.0/bin/irb"
    gem:          "/usr/share/rvm/rubies/ruby-2.7.0/bin/gem"
    rake:         "/home/carol/.rvm/gems/ruby-2.7.0/bin/rake"

  environment:
    PATH:         "/home/carol/.rvm/gems/ruby-2.7.0/bin:/home/carol/.rvm/gems/ruby-2.7.0@global/bin:/usr/share/rvm/rubies/ruby-2.7.0/bin:/usr/share/rvm/bin:/home/carol/.poetry/bin:/home/carol/.local/bin:/home/carol/.nvm/versions/node/v10.19.0/bin:/home/carol/.poetry/bin:/home/carol/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
    GEM_HOME:     "/home/carol/.rvm/gems/ruby-2.7.0"
    GEM_PATH:     "/home/carol/.rvm/gems/ruby-2.7.0:/home/carol/.rvm/gems/ruby-2.7.0@global"
    MY_RUBY_HOME: "/usr/share/rvm/rubies/ruby-2.7.0"
    IRBRC:        "/usr/share/rvm/rubies/ruby-2.7.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

**Comment by raelgc** [comment]
Hi @COAB1 and thanks for reporting this issue.

Can you, please, try the following commands?

    rvmsudo rvm cleanup all
    rvm fix-permissions

Then try again run the commands that failed.

**Comment by COAB1** [comment]
Problem solved with those commands. Thank you very much for your help

**Comment by raelgc** [comment]
I'm glad it worked. I'll close this issue.
