### ISSUE TITLE
FFI gem installation fails with binary Ruby 2.7.1, but works with compiled one on Ubuntu 20.04

### ISSUE THREAD

**Issue by dhs-rec** [rvm/rvm#4975]
## Description
After updating Ruby from 2.7.0 to 2.7.1 on an Ubuntu 20.04 system using latest stable RVM, I ran into the following error when installing the `ffi` gem:
```
current directory: /usr/local/rvm/gems/ruby-2.7.1@MyGemset/gems/ffi-1.13.1/ext/ffi_c
make "DESTDIR=" install
make: /usr/bin/mkdir: Command not found
make: *** [Makefile:202: .sitearchdir.time] Error 127

make install failed, exit code 2
```
However, there is no `/usr/bin/mkdir`, just `/bin/mkdir` (system is Ubuntu 20.04, but I checked on 18.04 and Debian 10, too)

So I reinstalled the (working) Ruby 2.7.0 and recognised that this one was actually compiled by RVM. This led me to also reinstall Ruby 2.7.1, using the `--disable-binary` option. After that, ffi gem installation went fine on this version, too.

So I guess the problem is with the precompiled Ruby 2.7.1 provided by RVM.

## Steps to reproduce
 1. Install Ruby 2.7.1 w/o `--disable-binary` on Ubuntu or Debian
 2. Create a gemset
 3. Install FFI gem

## Expected behavior
The gem should have been installed

## Actual behavior
See above

## Environment info
```
# rvm info

ruby-2.7.1:

  system:
    uname:        "Linux ubuntu-test 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "20.04"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)"
    zsh:          "/usr/bin/zsh => zsh 5.8 (x86_64-ubuntu-linux-gnu)"
    remote_path:  "ubuntu/20.04/x86_64"

  rvm:
    version:      "1.29.10 (latest)"
    updated:      "19 hours 18 minutes 45 seconds ago"
    path:         "/usr/local/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.7.1p83"
    date:         "2020-03-31"
    platform:     "x86_64-linux"
    patchlevel:   "2020-03-31 revision a0c7c23c9c"
    full_version: "ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]"

  homes:
    gem:          "/usr/local/rvm/gems/ruby-2.7.1"
    ruby:         "/usr/local/rvm/rubies/ruby-2.7.1"

  binaries:
    ruby:         "/usr/local/rvm/rubies/ruby-2.7.1/bin/ruby"
    irb:          "/usr/local/rvm/rubies/ruby-2.7.1/bin/irb"
    gem:          "/usr/local/rvm/rubies/ruby-2.7.1/bin/gem"
    rake:         "/usr/local/rvm/rubies/ruby-2.7.1/bin/rake"

  environment:
    PATH:         "/usr/local/rvm/gems/ruby-2.7.1/bin:/usr/local/rvm/gems/ruby-2.7.1@global/bin:/usr/local/rvm/rubies/ruby-2.7.1/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/packer/current:/opt/puppetlabs/bin"
    GEM_HOME:     "/usr/local/rvm/gems/ruby-2.7.1"
    GEM_PATH:     "/usr/local/rvm/gems/ruby-2.7.1:/usr/local/rvm/gems/ruby-2.7.1@global"
    MY_RUBY_HOME: "/usr/local/rvm/rubies/ruby-2.7.1"
    IRBRC:        "/usr/local/rvm/rubies/ruby-2.7.1/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by mike-bourgeous** [comment]
Also affected.  This affects any Gem I try to install that builds a native extension.  I found bugs reported in other projects that indicated this was a change made in (or upstream of) Debian between 9.0 and 9.1, which now seems to have made its way to Ubuntu.

**Comment by raelgc** [comment]
I'm the one compiling binaries for Ubuntu. I don't use any specific configurations while compiling, so I'm wondering if Ubuntu suffered the same change between 20.04 and 20.04.1.

Would be better if I recompile and upload again now that we're on 20.04.1? (`rvm info` doesn't report minor versions like `20.04.1`, just `20.04`).

**Comment by mike-bourgeous** [comment]
You (or a patch to `rvm info`) might be able to detect the Ubuntu point release version with the `lsb_release` command if you wanted to have separate binaries for 20.04 and 20.04.1.

**Comment by Confusion** [comment]
> I'm the one compiling binaries for Ubuntu. I don't use any specific configurations while compiling, so I'm wondering if Ubuntu suffered the same change between 20.04 and 20.04.1.
 
According to a comment at https://stackoverflow.com/questions/64653051/make-usr-bin-mkdir-command-not-found-during-gem-install-nokogiri-in-ubuntu#comment114911452_64653051, it did:

    Ubuntu incorporated an upstream change somewhere between 20.04 and 20.04.1 that moved mkdir

> Would be better if I recompile and upload again now that we're on 20.04.1? (`rvm info` doesn't report minor versions like `20.04.1`, just `20.04`).
That would probably give the best experience for the most people, although people that haven't upgraded in a while might experience problems.

**Comment by kenyon** [comment]
This is not even Ubuntu-specific. I came here because I'm having this same problem, but on Debian 10, using the @puppetlabs [Puppet Development Kit (PDK)](https://github.com/puppetlabs/pdk). This error occurs when I do `pdk bundle install` in the current [puppetlabs-apt](https://github.com/puppetlabs/puppetlabs-apt) repo. :man_shrugging:

**Comment by franzliedke** [comment]
I have the same problem with Ruby 3.0.0 - does that need to be recompiled as well? :pray:

**Comment by raelgc** [comment]
Yes. Right now you'll need to install recompiling locally adding `--disable-binary`.
