### ISSUE TITLE
Cannot install Ruby 2.5.3 with rvm on WSL ubuntu1904

### ISSUE THREAD

**Issue by Anteayer** [rvm/rvm#4979]
```
rvm install ruby 2.5.3
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.5.3.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
Updating system....
Installing required packages: g++, gcc, autoconf, automake, bison, libc6-dev, libffi-dev, libgdbm-dev, libncurses5-dev, libsqlite3-dev, libtool, libyaml-dev, make, pkg-config, sqlite3, zlib1g-dev, libgmp-dev, libreadline-dev, libssl-dev.....
Error running 'requirements_debian_libs_install g++ gcc autoconf automake bison libc6-dev libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev make pkg-config sqlite3 zlib1g-dev libgmp-dev libreadline-dev libssl-dev',
please read /home/anteayer/.rvm/log/1600755231_ruby-2.5.3/package_install_g++_gcc_autoconf_automake_bison_libc6-dev_libffi-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_make_pkg-config_sqlite3_zlib1g-dev_libgmp-dev_libreadline-dev_libssl-dev.log
Requirements installation failed with status: 100.
```

**Comment by raelgc** [comment]
WSL is interesting. Let's see if we can help you to install `rvm` on it.

First thing I've noticed is that in the title you said `19.04`, which is no more supported by Canonical, but in the command output it's mentioning `20.04`.

1 - Are you using `19.04` or `20.04`? If `19.04`, can you use `20.04`?

2 - What is the content of `/home/anteayer/.rvm/log/1600755231_ruby-2.5.3/package_install_g++_gcc_autoconf_automake_bison_libc6-dev_libffi-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_make_pkg-config_sqlite3_zlib1g-dev_libgmp-dev_libreadline-dev_libssl-dev.log`?

3 - Does Ubuntu on WSL supports add a PPA repository?

**Comment by Anteayer** [comment]
> WSL is interesting. Let's see if we can help you to install `rvm` on it.
> 
> First thing I've noticed is that in the title you said `19.04`, which is no more supported by Canonical, but in the command output it's mentioning `20.04`.
> 
> 1 - Are you using `19.04` or `20.04`? If `19.04`, can you use `20.04`?
> 
> 2 - What is the content of `/home/anteayer/.rvm/log/1600755231_ruby-2.5.3/package_install_g++_gcc_autoconf_automake_bison_libc6-dev_libffi-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_make_pkg-config_sqlite3_zlib1g-dev_libgmp-dev_libreadline-dev_libssl-dev.log`?
> 
> 3 - Does Ubuntu on WSL supports add a PPA repository?



> WSL is interesting. Let's see if we can help you to install `rvm` on it.
> 
> First thing I've noticed is that in the title you said `19.04`, which is no more supported by Canonical, but in the command output it's mentioning `20.04`.
> 
> 1 - Are you using `19.04` or `20.04`? If `19.04`, can you use `20.04`?
> 
> 2 - What is the content of `/home/anteayer/.rvm/log/1600755231_ruby-2.5.3/package_install_g++_gcc_autoconf_automake_bison_libc6-dev_libffi-dev_libgdbm-dev_libncurses5-dev_libsqlite3-dev_libtool_libyaml-dev_make_pkg-config_sqlite3_zlib1g-dev_libgmp-dev_libreadline-dev_libssl-dev.log`?
> 
> 3 - Does Ubuntu on WSL supports add a PPA repository?

Gracias por su respuesta, Desafortunadamente, todavía no he podido instalarlo.

First off, I can install rvm, but when i input
`rvm install ruby 2.5.3`
It has an error.It is a dependency package issue.
I tried my best to solve it but still can't finish it.
Also I tried install WSL ubuntu 20.04LTS to resolve this issue.But it still didn't work, it was the same problem, so I gave up the project

**Comment by raelgc** [comment]
I think the dependency issue is related to the `ssl` libraries, not? I'm asking if you can add PPA repositories, because the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm) solves this issue. Maybe you should give a try with Ubuntu 20.04.

**Comment by darrylsepeda** [comment]
This issue shouldn't be closed.. I encounter the same issue, and still can't find a way to make it works

**Comment by conquext** [comment]
@darrylsepeda run the following command to install the necessary dependencies

```
sudo apt update
```

```
sudo apt install curl g++ gcc autoconf automake bison libc6-dev libffi-dev libgdbm-dev libncurses5-dev libsqlite3-dev libtool libyaml-dev make pkg-config sqlite3 zlib1g-dev libgmp-dev libreadline-dev libssl-dev
```
