### ISSUE TITLE
Rvm fails to install binary ruby 2.7.2 on Ubuntu 20.04, uses compiling instead

### ISSUE THREAD

**Issue by hurricup** [rvm/rvm#4993]
```
Libraries missing for ruby-2.7.2: libgdbm.so.5,libreadline.so.7. Refer to your system manual for installing libraries
Mounting remote ruby failed with status 10, trying to compile.
```

**Comment by raelgc** [comment]
I can see that, on `20.04`, there is a [`libgdbm-dev`](https://packages.ubuntu.com/focal/libgdbm-dev) package, which provides `libgdbm` **6**, installed at `/usr/lib/x86_64-linux-gnu/libgdbm.so`.

**Comment by hurricup** [comment]
Guess this one is fixed after re-building on the most recent ubuntu
