### ISSUE TITLE
REE 1.8.7 requires libssl much like Ruby 1.8.7

### ISSUE THREAD

**Issue by Jsisas** [rvm/rvm#4996]
## Description

While installine Ree 1.8.7 using RVM it throws an libssl error. To fix that I need to change ubuntu requirements file.

## Steps to reproduce

 1. rvm install ree-1.8.7-2012.02

## Expected behavior

I am expected to install ree-1.8.7-2012.02 without changing RVM source code

## Actual behavior

* [command](https://gist.github.com/Jsisas/e606c36cdb1adee43205bda957e5d573)
* [config.log](https://gist.github.com/Jsisas/11c77e06350bbeb02254ce8e8b83801a)
* I dont have a make log

## Environment info

ree-1.8.7-2012.02:

  system:
    uname:        "Linux INBNOT154 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "Ubuntu"
    version:      "20.04"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "ubuntu/20.04/x86_64"

  rvm:
    version:      "1.29.10 (manual)"
    updated:      "19 minutes 31 seconds ago"
    path:         "/usr/share/rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  ""
    version:      ""
    date:         ""
    platform:     ""
    patchlevel:   ""
    full_version: ""

  homes:
    gem:          "/home/joosep/.rvm/gems/ree-1.8.7-2012.02"
    ruby:         "/usr/share/rvm/rubies/ree-1.8.7-2012.02"

  binaries:
    ruby:         ""
    irb:          ""
    gem:          ""
    rake:         "/home/joosep/.rvm/gems/ree-1.8.7-2012.02/bin/rake"

  environment:
    PATH:         "/home/joosep/.rvm/gems/ree-1.8.7-2012.02/bin:/home/joosep/.rvm/gems/ree-1.8.7-2012.02@global/bin:/usr/share/rvm/rubies/ree-1.8.7-2012.02/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/share/rvm/bin"
    GEM_HOME:     "/home/joosep/.rvm/gems/ree-1.8.7-2012.02"
    GEM_PATH:     "/home/joosep/.rvm/gems/ree-1.8.7-2012.02:/home/joosep/.rvm/gems/ree-1.8.7-2012.02@global"
    MY_RUBY_HOME: "/usr/share/rvm/rubies/ree-1.8.7-2012.02"
    IRBRC:        "/usr/share/rvm/rubies/ree-1.8.7-2012.02/.irbrc"
    RUBYOPT:      ""
    gemset:       ""

## Solution

To change line 27 at /rvm/scripts/functions/requirements/ubuntu
to (ruby-2.3*|ruby-2.2*|ruby-2.1*|ruby-2.0*|ruby-1.9*|ruby-1.8*|ree-1.8*)

**Comment by pkuczynski** [comment]
Can you fire up a PR with the fix please?

**Comment by raelgc** [comment]
You can try the [Ubuntu dedicated package](https://github.com/rvm/ubuntu_rvm) which has the missing dependency in the PPA repository.

**Comment by Jsisas** [comment]
I did, it has the same problem.

I can fire up a PR :+1:
