### ISSUE TITLE
OSX requirement brew issue

### ISSUE THREAD

**Issue by Asandolo** [rvm/rvm#4998]
## Description

I can't install any version of ruby in MacOS Catalina, I have a brew issue

## Steps to reproduce

 1. `rvm install 2.7`

## Expected behavior

Intall ruby 2.7

## Actual behavior

* [command](https://gist.github.com/a806d05da126f54c1ee632607fcde9ec)

**Debug mode**:
* [command](https://gist.github.com/b325fe9ec9794ace61ce607d13886178)

## Environment info

![image](https://user-images.githubusercontent.com/11891385/97890268-a42bcd80-1d2d-11eb-9097-79e5074cbf7c.png)

![image](https://user-images.githubusercontent.com/11891385/97890472-dccba700-1d2d-11eb-92bc-7ea3aecc7d43.png)

**Comment by rafasoares** [comment]
Having the same issue. Although if you leave it, it installs fine (it's just a warning after all).

**Comment by evereichmann** [comment]
I get this error when I run that line
```
No binary rubies available for: osx/10.15/x86_64/ruby-2.7.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
```

**Comment by rafasoares** [comment]
> I get this error when I run that line
> 
> ```
> No binary rubies available for: osx/10.15/x86_64/ruby-2.7.2.
> Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
> Checking requirements for osx.
> ```

That's completely normal, it's not an error. I don't think I ever got a binary ruby on macOS. You just gotta be a bit patient.

**Comment by ashkulz** [comment]
It's now broken with the latest `brew`, as it is now an error:
```
No binary rubies available for: osx/10.13/x86_64/ruby-2.5.8.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
Error: Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead.
```

**Comment by tisba** [comment]
Seems to be related to https://github.com/rvm/rvm/issues/5017

**Comment by bvicenzo** [comment]
It seems that it was reported here https://github.com/rvm/rvm/issues/5007 and fixed here https://github.com/rvm/rvm/pull/4995.
