### ISSUE TITLE
Requirement `glibc-headers` obsolete on Fedora 33

### ISSUE THREAD

**Issue by quentin** [rvm/rvm#5021]
Hi everyone, I found this issue on Fedora 33, I'm surprised it was not reported already.
🎄 Merry Christmas.

## Description

RVM requirements includes `glibc-headers` on Fedora. The package is obsolete since Fedora 33 and replaced by [glibc-devel](https://fedora.pkgs.org/33/fedora-x86_64/glibc-devel-2.32-1.fc33.x86_64.rpm.html). Thus several rubies cannot be installed anymore with rvm because the requirements phase fails while checking for `glibc-headers`.

## Steps to reproduce

 1. Run `rvm requirements` on Fedora 33.
 2. Observe that rvm requires the installation of `glibc-headers` (`Installing required packages: glibc-headers`).
 3. Observe the error when rvm runs `dnf install -y glibc-headers`.

## Expected behavior

I expect requirements phase to complete successfully. RVM should not try to install the obsolete `glibc-headers` package on Fedora 33.

## Actual behavior

coming soon.

## Environment info

coming soon.

**Comment by pkuczynski** [comment]
Good catch! Here is some more info: https://fedoraproject.org/wiki/Changes/RemoveGlibcHeaders

**Comment by pkuczynski** [comment]
@quentin would you mind running `rvm get branch /fedora-glibc-headers` and verify if this solves the issue?

**Comment by quentin** [comment]
I'll try as soon as I am back from holidays.
Thanks for the investigation !

**Comment by quentin** [comment]
Hi @pkuczynski, I confirm that `rvm requirements` succeeds after `rvm get branch /fedora-glibc-headers`.

**Comment by pkuczynski** [comment]
Awesome! Thanks!
