### ISSUE TITLE
Error building ruby-3.0.0 on macOS Catalina

### ISSUE THREAD

**Issue by caponecicero** [rvm/rvm#5025]
System info:

<img width="491" alt="System Info:" src="https://user-images.githubusercontent.com/2354165/103317507-38d64300-49e0-11eb-9a04-cfba66aa2453.png">

The error message is:
```
ruby-3.0.0 - #generating default wrappers........
Error running 'run_gem_wrappers regenerate',
please read /Users/stevewi/.rvm/log/1609273270_ruby-3.0.0/gemset.wrappers.default.log
```

The compressed logs from `rvm install ruby-3.0.0 --debug`  --> [1609273270_ruby-3.0.0.zip](https://github.com/rvm/rvm/files/5752363/1609273270_ruby-3.0.0.zip)

```
ruby-3.0.0:

  system:
    uname:        "Darwin Steve-Wittens-MacBook-Air.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.15"
    architecture: "x86_64"
    bash:         "/usr/local/bin/bash => GNU bash, version 5.1.4(1)-release (x86_64-apple-darwin19.6.0)"
    zsh:          "/bin/zsh => zsh 5.7.1 (x86_64-apple-darwin19.0)"
    remote_path:  "osx/10.15/x86_64"
    xcode:        "12.0.1"

  rvm:
    version:      "1.29.11 (latest)"
    updated:      "2 hours 43 minutes 33 seconds ago"
    path:         "/Users/stevewi/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "3.0.0p0"
    date:         "2020-12-25"
    platform:     "x86_64-darwin19"
    patchlevel:   "2020-12-25 revision 95aff21468"
    full_version: "ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]"

  homes:
    gem:          "/Users/stevewi/.rvm/gems/ruby-3.0.0"
    ruby:         "/Users/stevewi/.rvm/rubies/ruby-3.0.0"

  binaries:
    ruby:         "/Users/stevewi/.rvm/rubies/ruby-3.0.0/bin/ruby"
    irb:          "/Users/stevewi/.rvm/rubies/ruby-3.0.0/bin/irb"
    gem:          "/Users/stevewi/.rvm/rubies/ruby-3.0.0/bin/gem"
    rake:         "/Users/stevewi/.rvm/rubies/ruby-3.0.0/bin/rake"

  environment:
    PATH:         "/Users/stevewi/.rvm/gems/ruby-3.0.0/bin:/Users/stevewi/.rvm/gems/ruby-3.0.0@global/bin:/Users/stevewi/.rvm/rubies/ruby-3.0.0/bin:/Users/stevewi/.rvm/bin:.:/Users/stevewi/bin:/Users/stevewi/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin"
    GEM_HOME:     "/Users/stevewi/.rvm/gems/ruby-3.0.0"
    GEM_PATH:     "/Users/stevewi/.rvm/gems/ruby-3.0.0:/Users/stevewi/.rvm/gems/ruby-3.0.0@global"
    MY_RUBY_HOME: "/Users/stevewi/.rvm/rubies/ruby-3.0.0"
    IRBRC:        "/Users/stevewi/.rvm/rubies/ruby-3.0.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by BrianHawley** [comment]
Already reported in #5020

**Comment by BrianHawley** [comment]
OK, @pkuczynski, this one is still happening. #5020, #5027 and #5029 fixed the problem for "scripts/functions/installer" but the problem still exists for "scripts/functions/gemset", which calls  `run_gem_wrappers regenerate` in `gemset_initial`, right after calling that `ruby-3.0.0 - #generating default wrappers` log statement (so it's the particular call that is failing). `run_gem_wrappers` calls `gem_install gem-wrappers`, but not `gem pristine gem-wrappers --only-plugins` like the other fix. Looks like we need to do the plugins fix for the gemset file too.

**Comment by pkuczynski** [comment]
@BrianHawley would you like to provide PR? or maybe @pedrofurtado would like to have a look?

**Comment by BrianHawley** [comment]
@pkuczynski if it hasn't been fixed by the end of day, I'll give it a shot. I may need code style advice though, and I don't know how to write tests for this, though I might be able to figure out manual testing.

**Comment by pedrofurtado** [comment]
@pkuczynski Thanks for ping! 

@BrianHawley, the error of this issue is related to the #5020 . We fixed it in the fresh install, the already previously installation, and now the last part 🎉 : the actual installation+compilation of ruby 3. I was already working on it, but I did not notify anyone yet 😄 

You can take a look on this PR that I've created:  https://github.com/rvm/rvm/pull/5030

I am finishing the test with it, but I think we can provide this fix soon (firstly in rvm codebase, and after in a official release, v1.29.12 for example) 👍

**Comment by BrianHawley** [comment]
@pedrofurtado I looked at the PR and left a comment. Take a look, and let me know if my concerns are unfounded.

**Comment by pedrofurtado** [comment]
@BrianHawley Thank you! The PR is not finished yet, but I will look the review/suggestions after tests here, to ensure that code works for ruby 3.x and 2.x 🤝

**Comment by BrianHawley** [comment]
@pedrofurtado it's probably that the `gem pristine` command won't be needed for sufficiently old ruby versions, or at least ones with an old enough version of rubygems that it doesn't have the issue we're fixing. My suggestion that you check whether `gem wrappers` without parameters works, then only do the `gem pristine` if it doesn't.
