### ISSUE TITLE
ruby-2.6.6 - #compiling - please wait Error running '__rvm_make -j8'

### ISSUE THREAD

**Issue by manel00** [rvm/rvm#5043]
## Description

ruby-2.6.6 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/manel/.rvm/log/1612637884_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.

On macbook m1 big sur

## Steps to reproduce

Install RVM with:
\curl -sSL https://get.rvm.io | bash -s stable
Restart your shell
Install Ruby with:
rvm install 2.6

## Expected behavior

Install RVM

## Actual behavior

ruby-2.6.6 - #compiling - please wait Error running '__rvm_make -j8'

## Environment info

system:

  system:
    uname:        "Darwin MacBook-Air-de-Manel.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64"
    name:         "OSX"
    version:      "11.2"
    architecture: "arm64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (arm64-apple-darwin20)"
    zsh:          "/bin/zsh => zsh 5.8 (x86_64-apple-darwin20.0)"
    remote_path:  "osx/11.2/arm64"
    xcode:        "12.4"

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "22 minutes 50 seconds ago"
    path:         "/Users/manel/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/manel/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by samkap** [comment]
Same issue for `rvm install 2.6.6`, on Big Sur.

**Comment by jamieorc** [comment]
Homebrew has precompiled versions of 2.4, 2.5, 2.6, 2.7 for Mac M1 ARM machines. Is there a way to use these with RVM?

2.7.2 compiles and runs fine, but I need access to older rubies for some legacy applications until we upgrade them.

**Comment by jamieorc** [comment]
After `brew install ruby@2.4` I just softlinked from `~/.rvm/rubies` and now I have a working version managed my RVM.

`ln -s /opt/homebrew/Cellar/ruby@2.4/2.4.10 ruby-2.4.10`

**Comment by samkap** [comment]
A version of [this fix](https://solnic.codes/2020/12/09/fixing-ruby-2-7-compilation-error-on-big-sur/) fixed this issue for me.

**Comment by tomrossi7** [comment]
I haven't been able to get a fix for this yet.

I've tried this solution:
```
brew update
brew upgrade
brew install llvm
export PATH="/usr/local/opt/llvm/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/llvm/lib"
export CPPFLAGS="-I/usr/local/opt/llvm/include"
```
But still can't get `rvm install "ruby-2.6.6"` to work on a fresh M1 Big Sur installation:

```
Installing Ruby from source to: /Users/tom/.rvm/rubies/ruby-2.6.6, this may take a while depending on your cpu(s)...
ruby-2.6.6 - #downloading ruby-2.6.6, this may take a while depending on your connection...
ruby-2.6.6 - #extracting ruby-2.6.6 to /Users/tom/.rvm/src/ruby-2.6.6 - please wait
ruby-2.6.6 - #configuring - please wait
Error running './configure --prefix=/Users/tom/.rvm/rubies/ruby-2.6.6  --with-opt-dir=/opt/homebrew/opt/libyaml:/opt/homebrew/opt/libksba:/opt/homebrew/opt/readline:/opt/homebrew/opt/zlib:/opt/homebrew/opt/openssl@1.1 --disable-install-doc --enable-shared',
please read /Users/tom/.rvm/log/1617220167_ruby-2.6.6/configure.log
There has been an error while running configure. Halting the installation.
```
I don't know if this helps, but I am able to install `ruby-2.7.2`.

Does anyone have anything else I can try?

**Comment by jamieorc** [comment]
See my comment a couple of rows above yours: https://github.com/rvm/rvm/issues/5043#issuecomment-780907628

**Comment by tomrossi7** [comment]
I was able to get RVM to install ruby-2.6.6 and ruby-2.6.5 with this syntax:

`CFLAGS="-Wno-error=implicit-function-declaration" rvm install 2.6.6`

**Comment by Seizeweb** [comment]
@tomrossi7 's solution fixed things for me!

**Comment by Shree-git** [comment]
@tomrossi7 's solution works!!!!

**Comment by jpgazmuri** [comment]
> I was able to get RVM to install `ruby-2.6.6` and `ruby-2.6.5` with this syntax:
> 
> `CFLAGS="-Wno-error=implicit-function-declaration" rvm install 2.6.6`

Does this cause any problems or issues?

**Comment by philip13** [comment]
> I was able to get RVM to install `ruby-2.6.6` and `ruby-2.6.5` with this syntax:
> 
> `CFLAGS="-Wno-error=implicit-function-declaration" rvm install 2.6.6`

Works good with ruby 2.6.7
but I don't know how install ruby-2.1.7

**Comment by mayur-kambariya** [comment]
1) Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
2) Uninstall Homebrew
  ```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
  rm -rf /opt/homebrew/*
  sudo rm -rf /opt/homebrew
```
3) Reinstall Homebrew
  `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
4) Restart terminal
5) Check Homebrew is working fine: `brew doctor`
6) Reinstall openssl: `brew install openssl`
7) Install Ruby: `rvm install 2.7` Or any version

**Comment by victorpolko** [comment]
@mayur-kambariya saved my day! Thank you sir!

After almost a day of triage and failures (sometimes Ruby is installed, but `ffi` lib missing a symbol, sometimes even Ruby fails to install) on a new M1 laptop, this solution worked!
I don't care how wrong it feels, for now it looks like the only way to run my old projects.

MacBook Pro M1 16-Core '21.

**Comment by mayur-kambariya** [comment]
> @mayur-kambariya saved my day! Thank you sir!
> 
> After almost a day of triage and failures (sometimes Ruby is installed, but `ffi` lib missing a symbol, sometimes even Ruby fails to install) on a new M1 laptop, this solution worked!
> I don't care how wrong it feels, for now it looks like the only way to run my old projects.
> 
> MacBook Pro M1 16-Core '21.

My pleasure

**Comment by joshuabrileyatk** [comment]
> 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> 2. Uninstall Homebrew
> 
> ```
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> rm -rf /opt/homebrew/*
> sudo rm -rf /opt/homebrew
> ```
> 
> 3. Reinstall Homebrew
>    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> 4. Restart terminal
> 5. Check Homebrew is working fine: `brew doctor`
> 6. Reinstall openssl: `brew install openssl`
> 7. Install Ruby: `rvm install 2.7` Or any version
 
This solution also worked for me! Thank you very much, @mayur-kambariya.

**Comment by glaylson** [comment]
> > `CFLAGS="-Wno-error=implicit-function-declaration" rvm install 2.6.6`

Error running '__rvm_make -j8',
please read /Users/glaylson/.rvm/log/1665494249_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.

**Comment by glaylson** [comment]
> > 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> > 2. Uninstall Homebrew
> > 
> > ```
> > /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> > rm -rf /opt/homebrew/*
> > sudo rm -rf /opt/homebrew
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Reinstall Homebrew
> >    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> > 4. Restart terminal
> > 5. Check Homebrew is working fine: `brew doctor`
> > 6. Reinstall openssl: `brew install openssl`
> > 7. Install Ruby: `rvm install 2.7` Or any version
> 
> This solution also worked for me! Thank you very much, @mayur-kambariya.

------------------
Error running '__rvm_make -j8',
please read /Users/glaylson/.rvm/log/1665494249_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.

**Comment by mayur-kambariya** [comment]
> > > 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> > > 2. Uninstall Homebrew
> > > 
> > > ```
> > > /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> > > rm -rf /opt/homebrew/*
> > > sudo rm -rf /opt/homebrew
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 3. Reinstall Homebrew
> > >    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> > > 4. Restart terminal
> > > 5. Check Homebrew is working fine: `brew doctor`
> > > 6. Reinstall openssl: `brew install openssl`
> > > 7. Install Ruby: `rvm install 2.7` Or any version
> > 
> > 
> > This solution also worked for me! Thank you very much, @mayur-kambariya.
> 
> Error running '__rvm_make -j8', please read /Users/glaylson/.rvm/log/1665494249_ruby-2.6.6/make.log
> 
> There has been an error while running make. Halting the installation.

I will help you @glaylson

**Comment by navdeep21** [comment]
`rvm install 2.5.1 --with-out-ext=fiddle`

append --with-out-ext=fiddle at the end 

and it worked!

**Comment by majnioui** [comment]
@mayur-kambariya Tried your solution but I'm getting this error now 

```
5 warnings generated.
building rb_mjit_header.h
2 warnings generated.
linking miniruby
rb_mjit_header.h updated
generating encdb.h
building .ext/include/-darwin22/rb_mjit_min_header-2.6.6.h
./miniruby -I./lib -I. -I.ext/common  ./tool/transform_mjit_header.rb "gcc " rb_mjit_header.h .ext/include/-darwin22/rb_mjit_min_header-2.6.6.h
encdb.h updated
./tool/ifchange "--timestamp=.rbconfig.time" rbconfig.rb rbconfig.tmp
rbconfig.rb updated
generating enc.mk
creating verconf.h
verconf.h updated
compiling loadpath.c
linking static-library libruby.2.6-static.a
making srcs under enc
linking shared-library libruby.2.6.dylib
make[1]: Nothing to be done for `srcs'.
generating transdb.h
Undefined symbols for architecture arm64:
  "__mh_execute_header", referenced from:
      _fill_lines in addr2line.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libruby.2.6.dylib] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by ZehraPunjwani** [comment]
> 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> 2. Uninstall Homebrew
> 
> ```
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> rm -rf /opt/homebrew/*
> sudo rm -rf /opt/homebrew
> ```
> 
> 3. Reinstall Homebrew
>    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> 4. Restart terminal
> 5. Check Homebrew is working fine: `brew doctor`
> 6. Reinstall openssl: `brew install openssl`
> 7. Install Ruby: `rvm install 2.7` Or any version

The only thing that worked .... Thanks a lot!!!!

**Comment by mayur-kambariya** [comment]
> The only thing that worked .... Thanks a lot!!!!

Welcome

**Comment by Blacklizardu** [comment]
> 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> 2. Uninstall Homebrew
> 
> ```
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> rm -rf /opt/homebrew/*
> sudo rm -rf /opt/homebrew
> ```
> 
> 3. Reinstall Homebrew
>    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> 4. Restart terminal
> 5. Check Homebrew is working fine: `brew doctor`
> 6. Reinstall openssl: `brew install openssl`
> 7. Install Ruby: `rvm install 2.7` Or any version

I tried this one but for me it's a diffrent error : Error running '__rvm_make -j10',

**Comment by mathieujobin** [comment]
how about replacing `-j10` by `-j2` ?

**Comment by usmanovrustam** [comment]
> `rvm install 2.5.1 --with-out-ext=fiddle`
> 
> append `--with-out-ext=fiddle` at the end
> 
> and it should work. This worked for me though.

That one is worked for me, Thanks a lot

**Comment by c-donald** [comment]
> > 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> > 2. Uninstall Homebrew
> > 
> > ```
> > /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> > rm -rf /opt/homebrew/*
> > sudo rm -rf /opt/homebrew
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Reinstall Homebrew
> >    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> > 4. Restart terminal
> > 5. Check Homebrew is working fine: `brew doctor`
> > 6. Reinstall openssl: `brew install openssl`
> > 7. Install Ruby: `rvm install 2.7` Or any version
> 
> I tried this one but for me it's a diffrent error : Error running '__rvm_make -j10', M1 pro

im getting this error when trying to rvm install 2.7 'Error running '__rvm_make -j10',
please read /Users/cdonald/.rvm/log/1689421157_ruby-2.7.2/make.log'

**Comment by c-donald** [comment]
i think i have fixed the problem

**Comment by sadeajayi** [comment]
when running step #6 "reinstall openssl" i get the message 
Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)!
To rerun under ARM use:
    arch -arm64 brew install ...
To install under x86_64, install Homebrew into /usr/local.

**Comment by jerry952** [comment]
> 
i meet the save promble:'Error running '__rvm_make -j10',how did you fix it

**Comment by vijaydevlandg** [comment]
I am also facing the same issue, i meet the save promble:'Error running '__rvm_make -j10',how did you fix it. tried all the above methods to fix. unfortunately not successful yet. :(

**Comment by omkarmosaic1234** [comment]
> 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> 2. Uninstall Homebrew
> 
> ```
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> rm -rf /opt/homebrew/*
> sudo rm -rf /opt/homebrew
> ```
> 
> 3. Reinstall Homebrew
>    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> 4. Restart terminal
> 5. Check Homebrew is working fine: `brew doctor`
> 6. Reinstall openssl: `brew install openssl`
> 7. Install Ruby: `rvm install 2.7` Or any version

This did not work for me too

**Comment by omkarmosaic1234** [comment]
> `rvm install 2.5.1 --with-out-ext=fiddle`
> 
> append `--with-out-ext=fiddle` at the end
> 
> and it should work. This worked for me though.

Neither this one

**Comment by adelstrinidadpm** [comment]
@omkarmosaic1234  Did you find any other solution? Any of the ones listed above worked for me :(

**Comment by omkarmosaic1234** [comment]
@adelstrinidadpm Ya this comment helped me on this [link](https://github.com/rvm/rvm/issues/5153#issuecomment-1423272333)

Since I have ios 16.5 on my iphone, xcode 14.2 wasn't finding the device. So i had to install xocde 14.3. It detected the device but did not run my project. So for running my project I had to switch to 14.2 again. I did this on my mac pro intel and it worked. Switching to m1 i started getting __rvm_make error. So now on my m1 i had 14.2 as 'Applications/xcode 2' and 14.3 as 'Applications/xcode' in my applications dir.

When I ran the command 'make install' from the above link it gave me an error that it was trying to install rvm in Applications/xcode 2, instead of just Applications/xcode. So I renamed them, changed xcode 2 to xcode for 14.2 and xcode to xcode 2 for 14.3. It installed successfully post that.

Its so weird that apple makes it so difficult for us developers that we have to waste time in all these things instead of solving important problems and the fact that theres no one solution to the same error, we have to search the whole universe to solve these things.

**Comment by bobyin** [comment]
> @omkarmosaic1234 Did you find any other solution? Any of the ones listed above worked for me :(

I use 'brew install ruby' instead, then rvm mount that ruby, works ok.

**Comment by rgandhi3352** [comment]
> rvm install 2.5.1 --with-out-ext=fiddle

getting the same, can you help me how do you solved that?

**Comment by rgandhi3352** [comment]
> i think i have fixed the problem

can you please help me here?

**Comment by nelliemckesson** [comment]
A combination of @mayur-kambariya solution plus downgrading openssl worked for me (M3 Pro Macbook): 

> 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> 2. Uninstall Homebrew
> 
> ```
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> rm -rf /opt/homebrew/*
> sudo rm -rf /opt/homebrew
> ```
> 
> 3. Reinstall Homebrew
>    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> 4. Restart terminal
> 5. Check Homebrew is working fine: `brew doctor`

6. Reinstall openssl with a lower version: `brew install openssl@1.1`
7. Install Ruby: `rvm install 2.7.7 --with-openssl-dir=/usr/local/opt/openssl@1.1` (or any version)

**Comment by danfodorean** [comment]
A solution that worked for me on macOS(intel) was running:
`CFLAGS=-DUSE_FFI_CLOSURE_ALLOC rvm install ruby-2.7.7 --with-openssl-dir=$(brew --prefix openssl@1.1)`
