### ISSUE TITLE
Unable to install any version of ruby on macOS Big Sur

### ISSUE THREAD

**Issue by balrajOla** [rvm/rvm#5047]
## Description
OS version: Big Sur
I am trying to install ruby using rvm. 
I ran following command.
```curl -sSL https://get.rvm.io | bash -s stable --ruby```

I am getting following error:
```Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
Found PGP signature at: 'https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc',
but no GPG software exists to validate it, skipping.
Upgrading the RVM installation in /Users/name/.rvm/
    RVM PATH line found in /Users/name/.mkshrc /Users/name/.profile /Users/name/.bashrc /Users/name/.zshrc.
    RVM sourcing line found in /Users/name/.profile /Users/name/.bash_profile /Users/name/.zlogin.
Upgrade of RVM in /Users/name/.rvm/ is complete.
Thanks for installing RVM 🙏
Please consider donating to our open collective to help us maintain RVM.
👉  Donate: https://opencollective.com/rvm/donate
Ruby enVironment Manager 1.29.12 (latest) (c) 2009-2020 Michal Papis, Piotr Kuczynski, Wayne E. Seguin
ruby-3.0.0 - #removing src/ruby-3.0.0..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.2/x86_64/ruby-3.0.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/name/.rvm/rubies/ruby-3.0.0, this may take a while depending on your cpu(s)...
ruby-3.0.0 - #downloading ruby-3.0.0, this may take a while depending on your connection...
ruby-3.0.0 - #extracting ruby-3.0.0 to /Users/name/.rvm/src/ruby-3.0.0.....
ruby-3.0.0 - #configuring..........................................................................
ruby-3.0.0 - #post-configuration.
ruby-3.0.0 - #compiling........
Error running '__rvm_make -j12',
please read /Users/name/.rvm/log/1613480016_ruby-3.0.0/make.log
There has been an error while running make. Halting the installation. 
```

Attaching my make.log file also.

[make.log](https://github.com/rvm/rvm/files/5988891/make.log)

Please help me to resolve this issue.

**Comment by balrajOla** [comment]
Also, tried to do following command mentioned here: [https://github.com/rvm/rvm/issues/4484#issuecomment-470707209](url)

```
$ cd /your/ruby/build/download/dir
$ make install
$ rvm repair all
```

getting constant error:
```
$ make install

./revision.h unchanged
compiling compile.c
In file included from compile.c:39:
./vm_callinfo.h:176:9: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
        rp(ci);
        ^
./internal.h:95:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
In file included from compile.c:39:
./vm_callinfo.h:217:16: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
    if (debug) rp(ci);
               ^
./internal.h:95:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
2 errors generated.
make: *** [compile.o] Error 1
```

**Comment by pedrofurtado** [comment]
@balrajOla Could you confirm to us if any of these workarounds works for this scenario?

https://github.com/rvm/rvm/issues/5039#issuecomment-774577714
https://github.com/rvm/rvm/issues/4966#issuecomment-770919610

This will help us to provide a official solution later 🤝

**Comment by PabloC** [comment]
Currently getting errors while trying to install the GPG key. 
Network erros like: No route to host.

**Comment by balrajOla** [comment]
@pedrofurtado I have tried both the solution. Nothing worked. Here is what i did:
```
Balraj-Singh:number26_ios balrajsingh$ CFLAGS="-Wno-error=implicit-function-declaration" rvm install 2.6.5
ruby-2.6.5 - #removing src/ruby-2.6.5..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.2/x86_64/ruby-2.6.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/balrajsingh/.rvm/rubies/ruby-2.6.5, this may take a while depending on your cpu(s)...
ruby-2.6.5 - #downloading ruby-2.6.5, this may take a while depending on your connection...
ruby-2.6.5 - #extracting ruby-2.6.5 to /Users/balrajsingh/.rvm/src/ruby-2.6.5.....
ruby-2.6.5 - #configuring.......................................................................
ruby-2.6.5 - #post-configuration.
ruby-2.6.5 - #compiling.........................
Error running '__rvm_make -j12',
please read /Users/balrajsingh/.rvm/log/1613494243_ruby-2.6.5/make.log

There has been an error while running make. Halting the installation.
Balraj-Singh:number26_ios balrajsingh$ export optflags=" -Wno-nullability-completeness " && rvm install 2.6.5
ruby-2.6.5 - #removing src/ruby-2.6.5..
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.2/x86_64/ruby-2.6.5.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/balrajsingh/.rvm/rubies/ruby-2.6.5, this may take a while depending on your cpu(s)...
ruby-2.6.5 - #downloading ruby-2.6.5, this may take a while depending on your connection...
ruby-2.6.5 - #extracting ruby-2.6.5 to /Users/balrajsingh/.rvm/src/ruby-2.6.5.....
ruby-2.6.5 - #configuring.......................................................................
ruby-2.6.5 - #post-configuration.
ruby-2.6.5 - #compiling.............................
Error running '__rvm_make -j12',
please read /Users/balrajsingh/.rvm/log/1613494510_ruby-2.6.5/make.log

There has been an error while running make. Halting the installation.
```

attaching log file too

[make.log](https://github.com/rvm/rvm/files/5990252/make.log)

**Comment by balrajOla** [comment]
@pedrofurtado On second attempt instead of trying to install 2.6.5 version i went with 2.5.5. As mentioned in this solution here: [link](https://github.com/rvm/rvm/issues/5039#issuecomment-774577714)

This worked for me. Now i do have 2.5.5 version.
But still having problem with any other version.

**Comment by pedrofurtado** [comment]
That is a really strange behavior 🤔 something in macOS Big Sur "internals" are affecting us in RVM

**Comment by balrajOla** [comment]
That is true. Do let me know if I need to provide more info or logs to solve this issue. As the issue with other versions of ruby still persists in my system.

**Comment by jamieorc** [comment]
Homebrew has precompiled versions of 2.4, 2.5, 2.6, 2.7 for Mac M1 ARM machines. Is there a way to use these with RVM?

**Comment by jamieorc** [comment]
After `brew install ruby@2.4` I just softlinked from `~/.rvm/rubies` and now I have a working version managed my RVM.

`ln -s /opt/homebrew/Cellar/ruby@2.4/2.4.10 ruby-2.4.10`

**Comment by A1bi** [comment]
I too ran into the `use of undeclared identifier RUBY_FUNCTION_NAME_STRING` error. To fix it all I had to do was update Xcode and the Xcode Command Line Tools. I updated from Xcode 12.1 to 12.4, I am running macOS 11.2.1.

**Comment by coneybeare** [comment]
> @balrajOla Could you confirm to us if any of these workarounds works for this scenario?
> 
> [#5039 (comment)](https://github.com/rvm/rvm/issues/5039#issuecomment-774577714)
> [#4966 (comment)](https://github.com/rvm/rvm/issues/4966#issuecomment-770919610)
> 
> This will help us to provide a official solution later 🤝

[#5039](https://github.com/rvm/rvm/issues/5039#issuecomment-774577714) worked for me with 2.4.10

**Comment by murtaza512** [comment]
For Big Sur, 
it's working with this

`export warnflags=-Wno-error=implicit-function-declaration
`
then you can install any ruby version

`rvm install 2.6.7`

**Comment by lrjbrual** [comment]
Hi, anyone resolve ruby 3.0.1 using Bigsur. Thanks. 

Here's the logs I got:

```
 railsprojects rvm install ruby-3.0.1
Warning, new version of rvm available '1.29.12', you are using older version '1.29.10'.
You can disable this warning with:   echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable auto-update with:     echo rvm_autoupdate_flag=2 >> ~/.rvmrc
You can update manually with:        rvm get VERSION                         (e.g. 'rvm get stable')

Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.3/x86_64/ruby-3.0.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/ryanjeffbrual/.rvm/rubies/ruby-3.0.1, this may take a while depending on your cpu(s)...
ruby-3.0.1 - #downloading ruby-3.0.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
The requested url does not exist(22): 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2'
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation.
```

**Comment by A1bi** [comment]
> Hi, anyone resolve ruby 3.0.1 using Bigsur. Thanks.

I didn't have any issues compiling 3.0.1 on Big Sur. It seems your system is trying to fetch the source as a bzipped tarball while it only exists as a gzipped one on the server  (see [here](https://ftp.ruby-lang.org/pub/ruby/3.0/)). Either this is a temporary issue with a missing file or this behaviour has been changed recently and you only need to update your rvm as described in the warning message (just run `rvm get stable`).

**Comment by lrjbrual** [comment]
@A1bi Thank you. but however when I tried to install the 3.0.1 I got the error in the log

here's it is: 

```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:42,
                 from random.c:480:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:14: error: variably modified 'bytes' at file scope
  193 |         char bytes[kAuthorizationExternalFormLength];
      |              ^~~~~
make: *** [random.o] Error 1
make: *** Waiting for unfinished jobs
```

Then:

```
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Warning: found user selected compiler 'gcc-11', this will suppress RVM auto detection mechanisms.
Installing Ruby from source to: /Users/ryanjeffbrual/.rvm/rubies/ruby-3.0.1, this may take a while depending on your cpu(s)...
ruby-3.0.1 - #downloading ruby-3.0.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.7M  100 18.7M    0     0  40.8M      0 --:--:-- --:--:-- --:--:-- 40.7M
No checksum for downloaded archive, recording checksum in user configuration.
ruby-3.0.1 - #extracting ruby-3.0.1 to /Users/ryanjeffbrual/.rvm/src/ruby-3.0.1 - please wait
ruby-3.0.1 - #configuring - please wait
ruby-3.0.1 - #post-configuration - please wait
ruby-3.0.1 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/ryanjeffbrual/.rvm/log/1622717986_ruby-3.0.1/make.log

There has been an error while running make. Halting the installation.
```

**Comment by iuliana** [comment]
I tried installing using `rvm install "ruby-3.0.1"` and got this. 
```
rvm install "ruby-3.0.1"
Warning, new version of rvm available '1.29.12', you are using older version '1.29.9'.
You can disable this warning with:   echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable auto-update with:     echo rvm_autoupdate_flag=2 >> ~/.rvmrc
You can update manually with:        rvm get VERSION                         (e.g. 'rvm get stable')

Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.2/x86_64/ruby-3.0.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/iulianacosmina/.rvm/rubies/ruby-3.0.1, this may take a while depending on your cpu(s)...
ruby-3.0.1 - #downloading ruby-3.0.1, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
The requested url does not exist(22): 'https://cache.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2'
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/3.0/ruby-3.0.1.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation.
```
Which makes sense, since at this location `https://cache.ruby-lang.org/pub/ruby/3.0/` there is no `ruby-3.0.1.tar.bz2`.

I tried multiple ways of installing `ruby-3.0.1` on  macOs Big Sur. 11.2.3 using `rbenv`, `homebrew` and I tried even compiling it myself. 

Nothing seems to work. But since I really need this version for a project, I will keep trying and hopefully provide more feedback.

**Comment by AndreaOlarte** [comment]
Updating rvm to the version mentioned in the warning fixed the problem for me

**Comment by dmolesUC** [comment]
@iuliana It looks like Ruby [stopped shipping `.tar.bz2` archives after 3.0.0-preview1](https://ftp.ruby-lang.org/pub/ruby/3.0/), and RVM didn't account for that till #5009. Updating to RVM 1.29.11 or later should pick up the change.

**Comment by iuliana** [comment]
Thank you @dmolesUC & @AndreaOlarte. I've already found a workaround. And ended up updating rvm later.

**Comment by luke-hill** [comment]
This should be closed with the fix provided by @murtaza512 https://github.com/rvm/rvm/issues/5047#issuecomment-844985557

**Comment by dsoegijono** [comment]
I'm still getting an error. I've tried https://github.com/rvm/rvm/issues/5047#issuecomment-844985557

```
$ rvm install ruby-2.6.7 --enable-shared=false
Warning! PATH is not properly set up, /Users/daphne/.rvm/gems/ruby-2.7.0/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-2.7.0
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
ruby-2.6.7 - #removing src/ruby-2.6.7 - please wait
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/daphne/.rvm/rubies/ruby-2.6.7, this may take a while depending on your cpu(s)...
ruby-2.6.7 - #downloading ruby-2.6.7, this may take a while depending on your connection...
ruby-2.6.7 - #extracting ruby-2.6.7 to /Users/daphne/.rvm/src/ruby-2.6.7 - please wait
ruby-2.6.7 - #configuring - please wait
Error running './configure --prefix=/Users/daphne/.rvm/rubies/ruby-2.6.7 --enable-shared=false --with-opt-dir=/usr/local/opt/libyaml:/usr/local/opt/libksba:/usr/local/opt/readline:/usr/local/opt/zlib:/usr/local/opt/openssl@1.1 --disable-install-doc --enable-shared',
please read /Users/daphne/.rvm/log/1633834618_ruby-2.6.7/configure.log
There has been an error while running configure. Halting the installation.
```

<details>
<summary>Versions</summary>

```shell
$ rvm --version
rvm 1.29.12 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
```

macOS Big Sur 11.6 (20G165)

Made sure Xcode is updated and xcode-select is installed

```shell
$ xcode-select --version
xcode-select version 2384.
```

</details>

**Comment by mightystrong** [comment]
> For Big Sur, it's working with this
> 
> `export warnflags=-Wno-error=implicit-function-declaration ` then you can install any ruby version
> 
> `rvm install 2.6.7`

This results in a broken installation on my system:

```
=> ruby-2.5.1 [ broken ]
   ruby-2.5.1@global [ broken ]
```

**Comment by dsoegijono** [comment]
@luke-hill I tried that, export, quit terminal and restart, then install. Still got an error:

```sh
$ rvm install 2.6.7
ruby-2.6.7 - #removing src/ruby-2.6.7 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/11.6/x86_64/ruby-2.6.7.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/daphne/.rvm/rubies/ruby-2.6.7, this may take a while depending on your cpu(s)...
ruby-2.6.7 - #downloading ruby-2.6.7, this may take a while depending on your connection...
ruby-2.6.7 - #extracting ruby-2.6.7 to /Users/daphne/.rvm/src/ruby-2.6.7 - please wait
ruby-2.6.7 - #configuring - please wait
ruby-2.6.7 - #post-configuration - please wait
ruby-2.6.7 - #compiling - please wait
Error running '__rvm_make -j16',
please read /Users/daphne/.rvm/log/1634436215_ruby-2.6.7/make.log

There has been an error while running make. Halting the installation.
```

`make.log` attached:

[make.log](https://github.com/rvm/rvm/files/7358597/make.log)

**Comment by mayur-kambariya** [comment]
1) Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
2) Uninstall Homebrew
  ```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
  rm -rf /opt/homebrew/*
  sudo rm -rf /opt/homebrew
```
3) Reinstall Homebrew
  `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
4) Restart terminal
5) Check Homebrew is working fine: `brew doctor`
6) Reinstall openssl: `brew install openssl`
7) Install Ruby: `rvm install 2.7` Or any version

**Comment by ziaulrehman40** [comment]
Fixing erros of `brew doctor` fixed the issue

**Comment by ssrcruz** [comment]
> > For Big Sur, it's working with this
> > `export warnflags=-Wno-error=implicit-function-declaration ` then you can install any ruby version
> > `rvm install 2.6.7`
> 
> This results in a broken installation on my system:
> 
> ```
> => ruby-2.5.1 [ broken ]
>    ruby-2.5.1@global [ broken ]
> ```
Did you resolve the broken ruby build? I am currently running into this as well. Thanks!

**Comment by usmanasif** [comment]
This is because of the certificates verification fails. Temporarily passing `-k` fixes the issue, though it's insecure and OpenSSL would need to be upgraded instead:

`curl -k -sSL https://get.rvm.io | bash -s stable`

**Comment by eva-matus** [comment]
Error rvm in Monterey (-v 12.2.1) (it worked for me)

Error running '__rvm_make -j8',
please read /Users/ewi/.rvm/log/1648737556_ruby-2.5.3/make.log

There has been an error while running make. Halting the installation.


Solution(thanks to @murtaza512 ):

`$ export warnflags=-Wno-error=implicit-function-declaration`

`$ rvm install 2.5.3`

**Comment by cristiancardosodexcom** [comment]
Error running '__rvm_make -j16',

**Comment by reginato** [comment]
Error running '__rvm_make -j8',
please read /Users/reginato/.rvm/log/1657657268_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.


Macos vesion 12.4 chip M1, heeeelpp

**Comment by ByteDecoder** [comment]
> Error rvm in Monterey (-v 12.2.1) (it worked for me)
> 
> Error running '__rvm_make -j8', please read /Users/ewi/.rvm/log/1648737556_ruby-2.5.3/make.log
> 
> There has been an error while running make. Halting the installation.
> 
> Solution(thanks to @murtaza512 ):
> 
> `$ export warnflags=-Wno-error=implicit-function-declaration`
> 
> `$ rvm install 2.5.3`

Works for me

**Comment by reginato** [comment]
Finally the solution....

CFLAGS="-Wno-error=implicit-function-declaration" rvm install 2.6.6

works.. thanks

**Comment by donmb1** [comment]
@Edilbek confirming this works, thank you

**Comment by G33kNoob** [comment]
it's solved just running terminal using rosetta setting

**Comment by Andy9822** [comment]
> For me, it works
> 
> `export optflags="-Wno-error=implicit-function-declaration" rvm install "ruby-2.6.4"`

Unfortunately that didn't work for me :/ 

> it's solved just running terminal using rosetta setting

This ☝️ was the only solution that worked

**Comment by johnkingzy** [comment]
I had a similar issue when trying to install rvm using the below command

Command:
```
rvm install 3.1.2
```

Error:
```
Error running '__rvm_make -j8',
please read ~/.rvm/log/1678723828_ruby-3.1.2/make.log
There has been an error while running make. Halting the installation.
```

What worked for me:
```
rvm install 3.1.2 --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
```

**Comment by Rim-777** [comment]
> I had a similar issue when trying to install rvm using the below command
> 
> OS version: macOS 13.2 (chip: Apple M1 Pro)
> 
> Command:
> 
> ```
> rvm install 3.1.2
> ```
> 
> Error:
> 
> ```
> Error running '__rvm_make -j8',
> please read ~/.rvm/log/1678723828_ruby-3.1.2/make.log
> There has been an error while running make. Halting the installation.
> ```
> 
> What worked for me:
> 
> ```
> rvm install 3.1.2 --with-openssl-dir=/opt/homebrew/opt/openssl@1.1
> ```

that also only this one worked for me

`brew list | grep openssl `#check if `openssl@1.1` is installed, if not 
`brew install openssl@1.1 `
 get the path of `openssl@1.1` by the following command:
`brew --prefix openssl@1.1` #you should get something similar to `/usr/local/opt/openssl@1.1`
then install the required version of Ruby:
`rvm install 3.2.2 --with-openssl-dir=/usr/local/opt/openssl@1.1` 
also works for ruby 2.....

**Comment by Amberevol** [comment]
Error running '__rvm_make install',
<img width="448" alt="Screenshot 2024-01-24 at 4 42 01 PM" src="https://github.com/rvm/rvm/assets/117064129/4569310b-3b3e-4a4c-a684-5c4b2f8f4913">

please read /Users/quanteondev/.rvm/log/1706094312_ruby-2.7.6/install.log
There has been an error while running make install. Halting the installation.
