### ISSUE TITLE
An error occurred while installing kgio (2.8.1), and Bundler cannot continue

### ISSUE THREAD

**Issue by tilipim123** [rvm/rvm#5053]
i'm trying to bundle install my project with ruby 1.8.7-head and got this errors

Gem files will remain installed in
/home/caio/.rvm/gems/ruby-1.8.7-head/gems/kgio-2.8.1 for inspection.
Results logged to
/home/caio/.rvm/gems/ruby-1.8.7-head/extensions/x86_64-linux/2.7.0/kgio-2.8.1/gem_make.out

An error occurred while installing kgio (2.8.1), and Bundler cannot
continue.
Make sure that `gem install kgio -v '2.8.1' --source 'https://rubygems.org/'`
succeeds before bundling.

In Gemfile:
  unicorn-rails was resolved to 1.0.1, which depends on
    unicorn was resolved to 4.2.0, which depends on
      kgio

**Comment by raelgc** [comment]
Hi @tilipim123. Can you please, fill all the requested info displayed when you open a new issue? Without it, it'll be impossible for us help you.

**Comment by raelgc** [comment]
@tilipim123 We'll be glad to help you if this is a `rvm` issue. But we really need the requested info. In this meanwhile, I'll close this issue. Feel free to re-open it in the case you can provide that info.
