### ISSUE TITLE
Error running 'requirements_termux_libs_install

### ISSUE THREAD

**Issue by iioowwu** [rvm/rvm#5057]
Hello. I have problems installing ruby ​​specific version, using rvm. I am using Termux. 
![IMG_20210312_120937.jpg](https://user-images.githubusercontent.com/80509790/110925719-340d0400-832c-11eb-9414-7b90f6baf64c.jpg)

I am stuck. What can i do? Please help!
**Thank you!**

**Comment by BrianHawley** [comment]
This was reported earlier in #5003.

**Comment by BrianHawley** [comment]
@pkuczynski the status 100 issue is not a bug in rvm; it's a Termux issue. See the above comment for details.

**Comment by pkuczynski** [comment]
I will close this ticket then as invalid. Thanks for looking into it...
