### ISSUE TITLE
Invalid brew syntax

### ISSUE THREAD

**Issue by CamJN** [rvm/rvm#5086]
https://github.com/rvm/rvm/blob/35e894c7070eaabc38d91220f6e26d1585a7098a/scripts/functions/requirements/osx_brew#L56

```
Usage: brew search, -S [options] [text|/regex/ ...]

Perform a substring search of cask tokens and formula names for text. If
text is flanked by slashes, it is interpreted as a regular expression. The
search for text is extended online to homebrew/core and homebrew/cask.

      --formula, --formulae        Search online and locally for formulae.
      --cask, --casks              Search online and locally for casks.
      --desc                       Search for formulae with a description
                                   matching text and casks with a name
                                   matching text.
      --pull-request               Search for GitHub pull requests containing
                                   text.
      --open                       Search for only open GitHub pull requests.
      --closed                     Search for only closed GitHub pull
                                   requests.
      --macports                   Search for text in the given package
                                   manager's list.
      --fink                       Search for text in the given package
                                   manager's list.
      --opensuse                   Search for text in the given package
                                   manager's list.
      --fedora                     Search for text in the given package
                                   manager's list.
      --debian                     Search for text in the given package
                                   manager's list.
      --ubuntu                     Search for text in the given package
                                   manager's list.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.

Error: Invalid usage: This command requires at least 1 text or regex argument.
```

**Comment by lexcraw4d** [comment]
I am having the same issue? Any updates?

**Comment by henryse** [comment]
Error: Invalid usage: This command requires at least 1 text or regex argument.
Usage: brew search, -S [options] text|/regex/ [...]

Perform a substring search of cask tokens and formula names for text. If
text is flanked by slashes, it is interpreted as a regular expression. The
search for text is extended online to homebrew/core and homebrew/cask.

      --formula, --formulae        Search online and locally for formulae.
      --cask, --casks              Search online and locally for casks.
      --desc                       Search for formulae with a description
                                   matching text and casks with a name
                                   matching text.
      --pull-request               Search for GitHub pull requests containing
                                   text.
      --open                       Search for only open GitHub pull requests.
      --closed                     Search for only closed GitHub pull
                                   requests.
      --macports                   Search for text in the given package
                                   manager's list.
      --fink                       Search for text in the given package
                                   manager's list.
      --opensuse                   Search for text in the given package
                                   manager's list.
      --fedora                     Search for text in the given package
                                   manager's list.
      --debian                     Search for text in the given package
                                   manager's list.
      --ubuntu                     Search for text in the given package
                                   manager's list.
  -d, --debug                      Display any debugging information.
  -q, --quiet                      Make some output more quiet.
  -v, --verbose                    Make some output more verbose.
  -h, --help                       Show this message.

Error: Invalid usage: This command requires at least 1 text or regex argument.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/henry/.rvm/rubies/ruby-3.0.0, this may take a while depending on your cpu(s)...
ruby-3.0.0 - #downloading ruby-3.0.0, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18.6M  100 18.6M    0     0  3051k      0  0:00:06  0:00:06 --:--:-- 3937k
ruby-3.0.0 - #extracting ruby-3.0.0 to /Users/henry/.rvm/src/ruby-3.0.0.....
ruby-3.0.0 - #configuring..
Error running 'env CFLAGS=-O3 -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include LDFLAGS=-L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib ./configure --prefix=/Users/henry/.rvm/rubies/ruby-3.0.0 --disable-install-doc --enable-shared',
please read /Users/henry/.rvm/log/1625520321_ruby-3.0.0/configure.log
There has been an error while running configure. Halting the installation.

Same here.... tried to upgrade to latest version with brew get head

**Comment by lexcraw4d** [comment]
I just deleted Xcode, reinstalled, and started all over. It wasn't working otherwise :( best of luck!

**Comment by BrianHawley** [comment]
This is fixed in master now.
