### ISSUE TITLE
Can't install ruby-head

### ISSUE THREAD

**Issue by dillonwelch** [rvm/rvm#5097]
## Description

When I try to install `rvm install ruby-head`, I get an error that blocks me from completing the installation.

## Steps to reproduce

 1. `rvm install ruby-head`

## Expected behavior

`ruby-head` installs

## Actual behavior

It's possible I'm failing at Google, but the only issue I can find when I google the error I'm seeing relates to erlang/asdf, which doesn't seem correct for this situation. https://github.com/asdf-vm/asdf-erlang/issues/195

All links are to files in the same gist.

* [command](https://gist.github.com/oniofchaos/f5cacbff075c550d3a2a7c4b449995c6#file-command-output-no-debug)
* [configure.log](https://gist.github.com/oniofchaos/f5cacbff075c550d3a2a7c4b449995c6#file-configure-no-debug.)
* [autoreconf.log](https://gist.github.com/oniofchaos/f5cacbff075c550d3a2a7c4b449995c6#file-autoreconf-no-debug) 

**Debug mode**:
* [command](https://gist.github.com/oniofchaos/f5cacbff075c550d3a2a7c4b449995c6#file-command-output-debug)
* [configure.log](https://gist.github.com/oniofchaos/f5cacbff075c550d3a2a7c4b449995c6#file-configure-debug.)
* [autoreconf.log](https://gist.github.com/oniofchaos/f5cacbff075c550d3a2a7c4b449995c6#file-autoreconf-debug) 

## Environment info

```
ruby-2.5.8:

  system:
    uname:        "Darwin Dillons-MBP 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "11.4"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)"
    zsh:          "/bin/zsh => zsh 5.8 (x86_64-apple-darwin20.0)"
    remote_path:  "osx/11.4/x86_64"
    xcode:        "12.5.1"

  rvm:
    version:      "1.29.12 (latest)"
    updated:      "15 hours 3 minutes 34 seconds ago"
    path:         "/Users/dillonwelch/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.8p224"
    date:         "2020-03-31"
    platform:     "x86_64-darwin19"
    patchlevel:   "2020-03-31 revision 67882"
    full_version: "ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]"

  homes:
    gem:          "/Users/dillonwelch/.rvm/gems/ruby-2.5.8"
    ruby:         "/Users/dillonwelch/.rvm/rubies/ruby-2.5.8"

  binaries:
    ruby:         "/Users/dillonwelch/.rvm/rubies/ruby-2.5.8/bin/ruby"
    irb:          "/Users/dillonwelch/.rvm/rubies/ruby-2.5.8/bin/irb"
    gem:          "/Users/dillonwelch/.rvm/rubies/ruby-2.5.8/bin/gem"
    rake:         "/Users/dillonwelch/.rvm/gems/ruby-2.5.8/bin/rake"

  environment:
    PATH:         "/Users/dillonwelch/.rvm/gems/ruby-2.5.8/bin:/Users/dillonwelch/.rvm/gems/ruby-2.5.8@global/bin:/Users/dillonwelch/.rvm/rubies/ruby-2.5.8/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/dillonwelch/.rvm/bin:/Users/dillonwelch/.rvm/bin"
    GEM_HOME:     "/Users/dillonwelch/.rvm/gems/ruby-2.5.8"
    GEM_PATH:     "/Users/dillonwelch/.rvm/gems/ruby-2.5.8:/Users/dillonwelch/.rvm/gems/ruby-2.5.8@global"
    MY_RUBY_HOME: "/Users/dillonwelch/.rvm/rubies/ruby-2.5.8"
    IRBRC:        "/Users/dillonwelch/.rvm/rubies/ruby-2.5.8/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by tagliala** [comment]
Same issue here

- macOS 11.6
- Xcode 13.0 Build version 13A233
- rvm 1.29.12-next (master)

I've tried to downgrade autoconf as described in asdf-vm/asdf-erlang#195 without success

Did you manage to solve this?

**Comment by oniofchaos** [comment]
Sadly nope, still have the same issue.

**Comment by brian-kephart** [comment]
Update: This issue persists on MacOS Monterey. However, `rvm install 3.1.0-preview1` works as expected.

**Comment by brodock** [comment]
same here

**Comment by brodock** [comment]
I can build ruby-head locally by running `./configure` manually on a cloned ruby repository. Is it fair to assume that autoreconf is not necessary anymore for ruby-head?

**Comment by brodock** [comment]
I found a way to build and sent a PR in #5238
