### ISSUE TITLE
get.rvm.io certificate has expired (SSL certificate problems)

### ISSUE THREAD

**Issue by adssidhu86** [rvm/rvm#5136]
## Description

While executing `curl -sSL https://get.rvm.io | bash -s stable`  observed message curl failed due to  ssl certificate problem : certificate expired.

This issue is similar to #4211

## Steps to reproduce

 1. curl -sSL https://get.rvm.io | bash -s stable
 2. Environment: CentOS
 

## Expected behavior

Install rvm 

## Actual behavior
rvm is not installed. Certificate issue message is observed 

```
curl -sSL https://get.rvm.io | bash -s stablecurl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

```

also see 

```
https://get.rvm.io -v
* Rebuilt URL to: https://get.rvm.io/
*   Trying 97.107.133.48...
* TCP_NODELAY set
*   Trying 2600:3c03::f03c:91ff:fedb:6957...
* TCP_NODELAY set
* Immediate connect fail for 2600:3c03::f03c:91ff:fedb:6957: Network is unreachable
* Connected to get.rvm.io (97.107.133.48) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, certificate expired (557):
* SSL certificate problem: certificate has expired
* Closing connection 0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

## Environment info

No info as issue observed while installing rvm

**Comment by jmkho-spirent** [comment]
Possibly related to: https://serverfault.com/questions/1079199/client-on-debian-9-erroneously-reports-expired-certificate-for-letsencrypt-issue

**Comment by sbetti02** [comment]
@adssidhu86 I think I just ran into this same issue you had. I don't know what the issue is exactly, but I think I was able to find a workaround using some instructions found here: https://rvm.io/rvm/install:

```
get.rvm.io is a redirect to https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer 
You could also use full path for the installer:

\curl https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer | bash -s stable
``` 

I gave this a shot and it worked for me first try, hopefully it might work for you as well.

**Comment by adssidhu86** [comment]
@sbetti02 Thanks!!!  the workaround is working fine. 
As these instructions  are on the official page I can close this issue, let me know your thoughts on this.

**Comment by adoontheway** [comment]
I solve this problem by download this file:
https://raw.githubusercontent.com/rvm/rvm/master/binscripts/rvm-installer
and rename the extension to .sh
and then excute :
`sh
./rvm-installer.sh stable
`
and it worked
