### ISSUE TITLE
Error running '__rvm_make -j4' - Ruby 3.0.0 or 2.6.3 on macOS 12.0.1

### ISSUE THREAD

**Issue by mkuti** [rvm/rvm#5152]
## Description

I am trying to install ruby on my mac via the terminal using the following command.
I had no ruby originally, tried to download the latest ruby 3.0.0, but had error during installation, tried 2.6.3, same error, then visited this [issue thread] (https://github.com/rvm/rvm/issues/4271), and then managed to install 2.5.0 with following command:

```
brew install openssl
rvm install ruby-2.5.0 --with-openssl-dir=/usr/bin/openssl
```

but trying to install 3.0.0 or 2.6.3 again and still have the same error

```
rvm install ruby-2.6.3 --with-openssl-dir=/usr/bin/openssl
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/Mapi/.rvm/rubies/ruby-2.6.3, this may take a while depending on your cpu(s)...
ruby-2.6.3 - #downloading ruby-2.6.3, this may take a while depending on your connection...
ruby-2.6.3 - #extracting ruby-2.6.3 to /Users/Mapi/.rvm/src/ruby-2.6.3 - please wait
ruby-2.6.3 - #configuring - please wait
ruby-2.6.3 - #post-configuration - please wait
ruby-2.6.3 - #compiling - please wait
Error running '__rvm_make -j4',
please read /Users/Mapi/.rvm/log/1636492558_ruby-2.6.3/make.log

There has been an error while running make. Halting the installation.
```

## Steps to reproduce

1. rvm get master && rvm known list
2. xcode-select -p
3. xcode-select --install
4. softwareupdate -l -a
5. rvm install 3.0.0 --with-openssl-dir=/usr/bin/openssl or rvm install 2.6.3 --with-openssl-dir=/usr/bin/openssl

## Expected behavior
Install of ruby-2.6.3 - #complete

## Actual behavior

``` 
Error running '__rvm_make -j4',
```

* [config.log](https://gist.github.com/mkuti/d22b0a7c6752f8f79bf5b92fa7f97374) - only for issues with `install`
* [make.log](https://gist.github.com/mkuti/458385a5b5a303f6e84104504b34395d) - only for issues with `install`

## Environment info
```
ruby-2.5.0:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  system:
    uname:        "Darwin Mobolajis-iMac.station 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "12.0"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)"
    zsh:          "/usr/local/bin/zsh => zsh 5.8 (x86_64-apple-darwin20.1.0)"
    remote_path:  "osx/12.0/x86_64"
    xcode:        ""

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "12 hours 19 minutes 22 seconds ago"
    path:         "/Users/Mapi/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  ruby:
    interpreter:  "ruby"
    version:      "2.5.0p0"
    date:         "2017-12-25"
    platform:     "x86_64-darwin21"
    patchlevel:   "2017-12-25 revision 61468"
    full_version: "ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin21]"

  homes:
    gem:          "/Users/Mapi/.rvm/gems/ruby-2.5.0"
    ruby:         "/Users/Mapi/.rvm/rubies/ruby-2.5.0"

  binaries:
    ruby:         "/Users/Mapi/.rvm/rubies/ruby-2.5.0/bin/ruby"
    irb:          "/Users/Mapi/.rvm/rubies/ruby-2.5.0/bin/irb"
    gem:          "/Users/Mapi/.rvm/rubies/ruby-2.5.0/bin/gem"
    rake:         "/Users/Mapi/.rvm/rubies/ruby-2.5.0/bin/rake"

  environment:
    PATH:         "/Users/Mapi/.rvm/gems/ruby-2.5.0/bin:/Users/Mapi/.rvm/gems/ruby-2.5.0@global/bin:/Users/Mapi/.rvm/rubies/ruby-2.5.0/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Users/Mapi/.rvm/bin"
    GEM_HOME:     "/Users/Mapi/.rvm/gems/ruby-2.5.0"
    GEM_PATH:     "/Users/Mapi/.rvm/gems/ruby-2.5.0:/Users/Mapi/.rvm/gems/ruby-2.5.0@global"
    MY_RUBY_HOME: "/Users/Mapi/.rvm/rubies/ruby-2.5.0"
    IRBRC:        "/Users/Mapi/.rvm/rubies/ruby-2.5.0/.irbrc"
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by mayur-kambariya** [comment]
1) Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
2) Uninstall Homebrew
  ```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
  rm -rf /opt/homebrew/*
  sudo rm -rf /opt/homebrew
```
3) Reinstall Homebrew
  `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
4) Restart terminal
5) Check Homebrew is working fine: `brew doctor`
6) Reinstall openssl: `brew install openssl`
7) Install Ruby: `rvm install 2.5.0` Or any version

**Comment by singh88** [comment]
> 1. Right clic Terminal from the Application/Utilities folder, Get Info, tick the "Open using Rosetta" box.
> 2. Uninstall Homebrew
> 
> ```
> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall.sh)"
> rm -rf /opt/homebrew/*
> sudo rm -rf /opt/homebrew
> ```
> 
> 1. Reinstall Homebrew
>    `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
> 2. Restart terminal
> 3. Check Homebrew is working fine: `brew doctor`
> 4. Reinstall openssl: `brew install openssl`
> 5. Install Ruby: `rvm install 2.5.0` Or any version

this is by far the best answer for the issue for recent M1 chipset, I remember doing this for Xcode but totally forgot Rosetta settings, thanks for finding it and saving it here, I believe someone should update the README for rvm github.

**Comment by peterbell215** [comment]
I encountered the same issue when trying to install Ruby 3.0.1 and Ruby 3.0.2 on Ubuntu 21.10.  I was able to get 3.0.2 installed installing and setting as default Ruby 2.7.3.  While running 2.7.3 I was able to compile and install both 3.0.1 and 3.0.2.
