### ISSUE TITLE
cannot create directory -- Permission denied

### ISSUE THREAD

**Issue by guleranaa** [rvm/rvm#5197]
am new on linux and trying to install rvm 2.3.5 by using command "rvm install 2.3.5"
am getting this error:

Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.3.5.tar.bz2
Checking requirements for ubuntu.
Installing requirements for ubuntu.
mkdir: cannot create directory ‘/usr/share/rvm/log/1648619894_ruby-2.3.5’: Permission denied
tee: /usr/share/rvm/log/1648619894_ruby-2.3.5/update_system.log: No such file or directory
Updating system....
Error running 'requirements_debian_update_system ruby-2.3.5',
please read /usr/share/rvm/log/1648619894_ruby-2.3.5/update_system.log
Requirements installation failed with status: 1.

--> i couldn't found it's solution anywhere on google

**Comment by algerrrr** [comment]
I'm having the same issue installing 2.7.2. Did you find the solution?

**Comment by algerrrr** [comment]
sudo chmod -R a+xwr /usr/share/rvm worked for me

**Comment by ramzieus** [comment]
`rvm fix-permissions system; rvm fix-permissions user`

**Comment by luke-hill** [comment]
My previous documentation (My own), mentions `rvm fix-permission system` however not the other one @ramzieus - So I've just amended this now. Great find. But again annoying I need to keep my own docs.

**Comment by whipowill** [comment]
As someone who wanted to just use GitHub pages, which led me to Jekyll, which led me to Ruby, which led me to RVM, which led me to this error, which led me to this page -- the documentation on all this is lacking.

**Comment by alex-bcc** [comment]
Really it helps a LOT. Thanksss @ramzieus

**Comment by mooventhan-k** [comment]
> `rvm fix-permissions system; rvm fix-permissions user`

This is working, we can close this i think

**Comment by edusurf10** [comment]
> `rvm fix-permissions system; rvm fix-permissions user`

This is working for me. Thanks man

**Comment by luke-hill** [comment]
@raelgc Should this be documented somewhere?
