### ISSUE TITLE
Use libreadline-dev instead of libreadline6-dev on Devuan

### ISSUE THREAD

**Issue by jensberke** [rvm/rvm#5203]
## Description

Building Ruby on Devuan fails because the expected requirement `libreadline6-dev` is missing. Only the first version of Devuan contained a `libreadline6-dev` actually, but since Devuan 2 there's only `libreadline-dev`.

## Steps to reproduce

 1. Install Devuan 2 or newer
 2. Install rvm stable 1.29.12 or rvm master
 3. rvm install 2.7.2 --disable-binary

## Expected behavior

Install Ruby using installed libreadline headers and libraries.

## Actual behavior

Install fails with message "Missing required packages: libreadline6-dev"

## Solution

I checked Devuan's version history on https://en.wikipedia.org/wiki/Devuan#Version_history and the package infos for "libreadline" on https://pkginfo.devuan.org, and the results are:

* Devuan 1 contains *both* `libreadline6-dev` and `libreadline-dev`, with `libreadline-dev` actually having a dependency on `libreadline6-dev`
* Devuan 2 and newer only contains `libreadline-dev`

This looks like the fix is simple and `libreadline-dev` can be used on all Devuan systems. In `scripts/functions/requirements/devuan`, change
```
requirements_check libreadline6-dev
```
to
```
requirements_check libreadline-dev
```
I made this change in my local RVM install on a Devuan 3 system and after that, building Ruby was successful.

**Comment by pkuczynski** [comment]
Can you provide PR?
