### ISSUE TITLE
macOS monterey version 12.4. Error running '__rvm_make -j12',

### ISSUE THREAD

**Issue by ahmedzoha029** [rvm/rvm#5225]
## Description
Can't install ruby 2.7.4 or any version

## Steps to reproduce
rvm install 2.7.4
Error running '__rvm_make -j12',
please read /Users/zoha/.rvm/log/1654826513_ruby-2.7.6/make.log

There has been an error while running make. Halting the installation.
## Expected Behaviour
__rvm_make () 
{ 
    \make "$@" || return $?
}
current path: /Users/zoha/.rvm/src/ruby-3.0.0
GEM_HOME=/Users/zoha/.rvm/gems/ruby-2.7.3
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/Users/zoha/.rvm/gems/ruby-2.7.3/bin:/Users/zoha/.rvm/gems/ruby-2.7.3@global/bin:/Users/zoha/.rvm/rubies/ruby-2.7.3/bin:/Users/zoha/.rvm/bin:/Users/zoha/.nvm/versions/node/v10.11.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Applications/Postgres.app/Contents/Versions/latest/bin
GEM_PATH=/Users/zoha/.rvm/gems/ruby-2.7.3:/Users/zoha/.rvm/gems/ruby-2.7.3@global
command(2): __rvm_make -j12
++ make -j12
	BASERUBY = /usr/bin/ruby --disable=gems
	CC = gcc -fdeclspec
	LD = ld
	LDSHARED = gcc -fdeclspec -dynamiclib
	CFLAGS = -O3 -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -fno-common -pipe 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -I. -I.ext/include/x86_64-darwin21 -I./include -I. -I./enc/unicode/12.1.0
	CPPFLAGS = -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   
	DLDFLAGS = -L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -install_name /Users/zoha/.rvm/rubies/ruby-3.0.0/lib/libruby.3.0.dylib -compatibility_version 3.0 -current_version 3.0.0  -fstack-protector-strong -framework Security -framework Foundation  -fstack-protector-strong -framework Security -framework Foundation  
	SOLIBS = -lpthread -lgmp -ldl -lobjc
	LANG = en_US.UTF-8
	LC_ALL = 
	LC_CTYPE = 
	MFLAGS = - --jobserver-fds=4,5 -j
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
compiling ./main.c
compiling dmydln.c
compiling miniinit.c
compiling dmyext.c
translating probes probes.d
compiling ast.c
compiling bignum.c
compiling class.c
compiling compar.c
. ./vm_opts.h
compiling compile.c
compiling complex.c
compiling cont.c
compiling debug.c
compiling debug_counter.c
compiling dir.c
compiling dln_find.c
compiling encoding.c
compiling enum.c
In file included from debug.c:27:
./vm_callinfo.h:176:9compiling enumerator.c
: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
        rp(ci);
        ^
./internal.h:95:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
In file included from debug.c:27:
./vm_callinfo.h:217:16: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
    if (debug) rp(ci);
               ^
./internal.h:95:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
2 errors generated.
make: *** [debug.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from compile.c:39:
./vm_callinfo.h:176:9: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
        rp(ci);
        ^
./internal.h:95:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
In file included from compile.c:39:
./vm_callinfo.h:217:16: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
    if (debug) rp(ci);
               ^
./internal.h:95:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
2 errors generated.
make: *** [compile.o] Error 1
++ return 2

**Comment by davideghz** [comment]
I get the same error, how did you fix it?

**Comment by yashwinkumar** [comment]
How is this got fixed?

**Comment by xta** [comment]
Also getting `Error running '__rvm_make -j12',`
