### ISSUE TITLE
rvm install 3.1.2 Error running '__rvm_make -j8'

### ISSUE THREAD

**Issue by leoplct** [rvm/rvm#5229]
## Description

I cannot install 3.1.2 on Mac OsX 12.4 x86_64

## Steps to reproduce

`rvm install 3.1.2`

Enviroment: osx/12.4/x86_64/ruby-3.1.2

## Actual behavior

` rvm install 3.1.2`

> Searching for binary rubies, this might take some time.
> No binary rubies available for: osx/12.4/x86_64/ruby-3.1.2.
> Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
> Checking requirements for osx.
> Updating certificates bundle '/usr/local/etc/openssl@1.1/cert.pem'
> Requirements installation successful.
> Installing Ruby from source to: /Users/name/.rvm/rubies/ruby-3.1.2, this may take a while depending on your cpu(s)...
> ruby-3.1.2 - #downloading ruby-3.1.2, this may take a while depending on your connection...
> ruby-3.1.2 - #extracting ruby-3.1.2 to /Users/name/.rvm/src/ruby-3.1.2 - please wait
> ruby-3.1.2 - #configuring - please wait
> ruby-3.1.2 - #post-configuration - please wait
> ruby-3.1.2 - #compiling - please wait
> Error running '__rvm_make -j8',
> please read /Users/name/.rvm/log/1656054377_ruby-3.1.2/make.log

> There has been an error while running make. Halting the installation.

## Logs

`cat /Users/name/.rvm/log/1656054377_ruby-3.1.2/make.log`

+__rvm_make:0> make -j8
	BASERUBY = /Users/name/.rvm/rubies/ruby-3.0.2/bin/ruby --disable=gems
	CC = gcc
	LD = ld
	LDSHARED = gcc -dynamiclib
	CFLAGS = -O3 -I/usr/local/opt/libyaml/include -I/usr/local/opt/libksba/include -I/usr/local/opt/readline/include -I/usr/local/opt/zlib/include -I/usr/local/opt/openssl@1.1/include -fdeclspec -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdivision-by-zero -Wimplicit-function-declaration -Wimplicit-int -Wmisleading-indentation -Wpointer-arith -Wshorten-64-to-32 -Wwrite-strings -Wold-style-definition -Wmissing-noreturn -Wno-constant-logical-operand -Wno-long-long -Wno-missing-field-initializers -Wno-overlength-strings -Wno-parentheses-equality -Wno-self-assign -Wno-tautological-compare -Wno-unused-parameter -Wno-unused-value -Wunused-variable -Wextra-tokens -Wundef -std=gnu99 -fno-common -pipe 
	XCFLAGS = -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fno-strict-overflow -fvisibility=hidden -DRUBY_EXPORT -I. -I.ext/include/x86_64-darwin21 -I./include -I. -I./enc/unicode/13.0.0
	CPPFLAGS = -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT   
	DLDFLAGS = -L/usr/local/opt/libyaml/lib -L/usr/local/opt/libksba/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/openssl@1.1/lib -install_name /Users/name/.rvm/rubies/ruby-3.1.2/lib/libruby.3.1.dylib -compatibility_version 3.1 -current_version 3.1.2  -fstack-protector-strong -framework CoreFoundation  -fstack-protector-strong -framework CoreFoundation  
	SOLIBS = -lpthread -lgmp -ldl -lobjc
	LANG = 
	LC_ALL = 
	LC_CTYPE = UTF-8
	MFLAGS = - --jobserver-fds=4,5 -j
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
compiling ./main.c
compiling dmydln.c
compiling miniinit.c
compiling dmyext.c
translating probes probes.d
compiling ast.c
compiling bignum.c
compiling class.c
compiling compar.c
. ./vm_opts.h
compiling compile.c
compiling complex.c
compiling cont.c
compiling debug.c
compiling debug_counter.c
In file included from debug.c:27:
./vm_callinfo.h:175:9: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
        rp(ci);
        ^
./internal.h:94:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
In file included from debug.c:27:
./vm_callinfo.h:216:16: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
    if (debug) rp(ci);
               ^
./internal.h:94:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
2 errors generated.
make: *** [debug.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from compile.c:40:
./vm_callinfo.h:175:9: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
        rp(ci);
        ^
./internal.h:94:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
In file included from compile.c:40:
./vm_callinfo.h:216:16: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
    if (debug) rp(ci);
               ^
./internal.h:94:72: note: expanded from macro 'rp'
#define rp(obj) rb_obj_info_dump_loc((VALUE)(obj), __FILE__, __LINE__, RUBY_FUNCTION_NAME_STRING)
                                                                       ^
2 errors generated.
make: *** [compile.o] Error 1
+__rvm_make:0> return 2

**Comment by GabrielLima1** [comment]
I have the same error and the same log return, but I try to install version `2.7.2` and on OS `linux/ubuntu`

**Comment by reginato** [comment]
me too

Error running '__rvm_make -j8',
please read /Users/reginato/.rvm/log/1657657268_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.

**Comment by mathieujobin** [comment]
How new is OSX 12.4 ? This could very much be a ruby problem and not rvm... 

this post is in korean and he using asdk, but it appears using LLVM was the solution
https://iksflow.tistory.com/130
similar solution using LLVM in English
https://stackoverflow.com/questions/71610807/troubles-upgrading-from-ruby-2-7-to-3-0

this other post suggest running `brew doctor` and updating XCode was the solution.
https://github.com/rbenv/ruby-build/issues/1409

**Comment by dalezak** [comment]
_Woot_, I finally got it working, hopefully this helps others with the same problem. 

```
brew uninstall --force openssl
brew install openssl
brew link --overwrite openssl --force
rvm install 3.1.2 --with-openssl-dir=`brew --prefix openssl`
```

**Comment by yangguanghei** [comment]
> _哇喔，多亏了_[这篇文章](https://stackoverflow.com/a/36896085/385730)，我终于让它工作了，希望这能帮助其他有同样问题的人。
> 
> ```
> brew uninstall --force openssl
> brew install openssl
> brew link --overwrite openssl --force
> rvm install 3.1.2 --with-openssl-dir=`brew --prefix openssl`
> ```

Error running '__rvm_make -j10',
please read /Users/liangsen/.rvm/log/1744024300_ruby-3.0.0/make.log

There has been an error while running make. Halting the installation.


no work
