### ISSUE TITLE
rvm install "ruby-2.5.1" --Error running '__rvm_make -j10', in MAC OS Monterey 12.4

### ISSUE THREAD

**Issue by ravisankarofp** [rvm/rvm#5240]
Below is the error i am facing while installig ruby-2.5.1. Please note that i have to install only this specific version of ruby. Appreciate if anyone can provide hints/clues to solve this issue?

Error running '__rvm_make -j10',
please read /Users/ravisankar/.rvm/log/1658948998_ruby-2.5.1/make.log

**Comment by Bardiamist** [comment]
Same issue on `rvm install 2.7.5` on macOS 12.5

**Comment by ravisankarofp** [comment]
Below solution worked for me...
In the terminal, execute below commands in sequence

export warnflags=-Wno-error=implicit-function-declaration
rvm install ruby-2.5.1

Please give it a try. 
<img width="397" alt="Screenshot 2022-08-04 at 5 38 41 PM" src="https://user-images.githubusercontent.com/100187698/182941033-be0b7230-0325-491b-b835-c862ff026052.png">

Even though status looks broken, but i am able to build my rails code and run the server successfully.

**Comment by evgeny-danilov** [comment]
I experienced the same issue with `ruby 2.7.1`, when I changed the machine. I changed the version to `2.7.8` and it solved the problem.

**Comment by mathieujobin** [comment]
try `-j2` instead, `-j10` is a lot of core, that's why it gets killed

**Comment by skqist225** [comment]
> Below solution worked for me... In the terminal, execute below commands in sequence
> 
> export warnflags=-Wno-error=implicit-function-declaration rvm install ruby-2.5.1
> 
> Please give it a try. <img alt="Screenshot 2022-08-04 at 5 38 41 PM" width="397" src="https://user-images.githubusercontent.com/100187698/182941033-be0b7230-0325-491b-b835-c862ff026052.png">
> 
> Even though status looks broken, but i am able to build my rails code and run the server successfully.

Thanks for your solution. That works in my case.

**Comment by muriithiKabogo** [comment]
Thanks th

> Below solution worked for me... In the terminal, execute below commands in sequence
> 
> export warnflags=-Wno-error=implicit-function-declaration rvm install ruby-2.5.1
> 
> Please give it a try. <img alt="Screenshot 2022-08-04 at 5 38 41 PM" width="397" src="https://user-images.githubusercontent.com/100187698/182941033-be0b7230-0325-491b-b835-c862ff026052.png">
> 
> Even though status looks broken, but i am able to build my rails code and run the server successfully.

This worked for me. Using a macbook pro M1

**Comment by hballangan-mdsol** [comment]
> ```
> arch -x86_64 rvm install 3.0.0
> ```

worked for me
`arch -arm64 rvm install 3.2.2 `

**Comment by Alex808r** [comment]
Mac M1 Monterey
rvm install 3.2.0 =>Error running '__rvm_make -j8' 


i solved the problem like this
1. `rvm remove 3.2.0 `

2.`rvm cleanup all`

3. `rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)  --disable-dtrace --disable-docs`

**Comment by k-vikram** [comment]
> Was installing Ruby 3.0.0 on Mac OS Monterey with an M2 chip. I recommend actually reading the error in the log because I had to try a couple of different things to finally get this to work, and I'm not 100% sure which one actually did the trick:
> 
> First error:
> 
> ```c
> closure.c:265:14: error: implicit declaration of function 'ffi_prep_closure' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
>     result = ffi_prep_closure(pcl, cif, callback, (void *)self);
>              ^
> 1 error generated.
> ```
> 
> It looks like @ravisankarofp's suggestion was meant to address this but unfortunate that didn't work for me. This did, however:
> 
> https://stackoverflow.com/a/68351730/3700490
> 
> I then got this error:
> 
> ```
> readline.c:1904:37: error: use of undeclared identifier 'username_completion_function'; did you mean 'rl_username_completion_function'?
>                                     rl_username_completion_function);
>                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                                     rl_username_completion_function
> readline.c:79:42: note: expanded from macro 'rl_username_completion_function'
> ```
> 
> So then I read https://stackoverflow.com/a/67249174/3700490 and the following resulted in a successful install:
> 
> ```
> arch -x86_64 rvm install 3.0.0
> ```
> 
> I'll report back if this results in a broken Ruby install.

@sometimescasey Super thanks for the pointer! I am on Mac M2 chipset and I was facing the `__rvm_make -j8` error without remedy. This [stackoverflow answer](https://stackoverflow.com/a/67249174/3700490), more so the idea to chuck `rvm` and go for `rbenv` worked for me. After spending more than 6-7hours , `rbenv` did the trick!

**Comment by gabeodess** [comment]
Okay, after running into this a number of times I've finally figured out my issues, so I'll document them here.

This is on a 2021 M1 MacBook Pro.

To @sometimescasey 's point, you should review your log file to determine specifically which issues you are facing.

My first error like some of the above comments was:
```
closure.c:264:14: error: call to undeclared function 'ffi_prep_closure'
```
This is fixed by setting the appropriate flags as also already mentioned:
```
export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"
```

The next issue I ran into is not mentioned in the above comments:
```
ossl.c:311:14: error: 'ERR_get_error_line_data' is deprecated
```

In my case, trying to install `ruby@2.5.8` which depends on `openssl@1.1` is failing because Homebrew is locking me to `openssl@3.0`.  I can't set this in my global flags because those are already being used for `libffi`, so we get a successful install by setting the flag locally:
```
rvm install 2.5 -- --with-openssl-dir=$(brew --prefix openssl@1.1)
```

**Comment by gitJoe42** [comment]
For me it was necessary to follow this instructions: https://medium.com/@canerten/building-ruby-3-1-3-fails-with-openssl-1-0-2o-1-on-m1-apple-silicon-mac-with-brew-89d7e550420b

Then `rvm install 3.2.2` worked like charm.

MacBook Air M2 macOs 14.0

**Comment by gabeodess** [comment]
> Okay, after running into this a number of times I've finally figured out my issues, so I'll document them here.
> 
> This is on a 2021 M1 MacBook Pro.
> 
> To @sometimescasey 's point, you should review your log file to determine specifically which issues you are facing.
> 
> My first error like some of the above comments was:
> 
> ```
> closure.c:264:14: error: call to undeclared function 'ffi_prep_closure'
> ```
> 
> This is fixed by setting the appropriate flags as also already mentioned:
> 
> ```
> export LDFLAGS="-L/opt/homebrew/opt/libffi/lib"
> export CPPFLAGS="-I/opt/homebrew/opt/libffi/include"
> export PKG_CONFIG_PATH="/opt/homebrew/opt/libffi/lib/pkgconfig"
> ```
> 
> The next issue I ran into is not mentioned in the above comments:
> 
> ```
> ossl.c:311:14: error: 'ERR_get_error_line_data' is deprecated
> ```
> 
> In my case, trying to install `ruby@2.5.8` which depends on `openssl@1.1` is failing because Homebrew is locking me to `openssl@3.0`. I can't set this in my global flags because those are already being used for `libffi`, so we get a successful install by setting the flag locally:
> 
> ```
> rvm install 2.5 -- --with-openssl-dir=$(brew --prefix openssl@1.1)
> ```

Following up on this, using `--with-openssl-dir` didn't seem to work for me when attempting to install `ruby@2.6.6`.  Although I was supplying the directory to `openssl@1.1`, the error logs from compilation were still referencing `openssl@3`.

To solve this I linked the older version of `openssl` using homebrew and then was able to install without issue:
```
brew link --overwrite openssl@1.1
openssl version
# => OpenSSL 1.1.1w  11 Sep 2023
rvm install 2.6
```

**Comment by fdecono** [comment]
> Mac M1 Monterey
> 
> `rvm install 3.2.0 `=> `Error running '__rvm_make -j8' `
> 
> I solved the problem like this
> 
> 1. `rvm remove 3.2.0 `
> 2. `rvm cleanup all`
> 3. `rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)  --disable-dtrace --disable-docs`

THX!!!! Was having issues with `3.1.3` after updating to Sonoma and this fixed it (using `3.1.3` instead of `3.2.0`)

**Comment by Princepushp** [comment]
> > Mac M1 Monterey
> > `rvm install 3.2.0 `=> `Error running '__rvm_make -j8' `
> > I solved the problem like this
> > 
> > 1. `rvm remove 3.2.0 `
> > 2. `rvm cleanup all`
> > 3. `rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)  --disable-dtrace --disable-docs`
> 
> THX!!!! Was having issues with `3.1.3` after updating to Sonoma and this fixed it (using `3.1.3` instead of `3.2.0`)

I am using sonoma this command solved my problem. THANK YOU : )

**Comment by felipefunes** [comment]
> Mac M1 Monterey
> 
> rvm install 3.2.0 => Error running '__rvm_make -j8' 
> 
> I solved the problem like this
> 
> rvm remove 3.2.0 
> rvm cleanup all
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)  --disable-dtrace --disable-docs

I'm using Mac M1 with Sonoma and this works for me installing Ruby 3.3.0 Thanks!

**Comment by elabayoub** [comment]
This one worked for me (Ventura 13.1) => OS cloned for another machine that's who i've force arch:

`arch -x86_64 rvm install 3.3.0 --with-openssl-dir=/usr/local/opt/openssl@1.1`

**Comment by ryankoch13** [comment]
> Mac M1 Monterey
> 
> `rvm install 3.2.0 `=> `Error running '__rvm_make -j8' `
> 
> I solved the problem like this
> 
> 1. `rvm remove 3.2.0 `
> 2. `rvm cleanup all`
> 3. `rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)  --disable-dtrace --disable-docs`

thank you so so so much

**Comment by asmrtfm** [comment]
The following worked on Monterey 12.7 - Intel i5 2017(late 2016) macbook pro (touchbar)

```bash
rvm remove 3.0.0 
sudo rvm cleanup all
rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl@3) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)  --disable-dtrace --disable-docs
```

> Note: RVM and Brew were both trying to install ruby 3.0.0 and so technically I'm not sure if it was specifying ruby 3.2 or openssl@3 but I suspect the ` --with-openssl-dir=$(brew --prefix openssl@3)` flag is what finally did the trick.
