### ISSUE TITLE
"cannot load such file -- openssl (LoadError)" when using autolibs

### ISSUE THREAD

**Issue by slondr** [rvm/rvm#5246]
## Description

On a fresh installation of rvm, I enabled `rvm autolibs enable` and `rvm autolibs macports` then tried to `rvm install 2.7.5`. This failed with the following error:

`.rvm/src/ruby-2.7.5/lib/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- openssl (LoadError)`

## Steps to reproduce

See description

## Expected behavior

Successful ruby installation 

## Actual behavior

Error message included in description

* [install.log](https://gist.github.com/slondr/f940968736ca9c076bb56bad62034fa1)
* [configure.log](https://gist.github.com/slondr/a4602b08c31d12ee41e74c1dee45c7fb) 
* [make.log](https://gist.github.com/slondr/b86d449d6024643df76651b80c3d4abd) - notice the openssl bit at the bottom

## Environment info

[rvm info](https://gist.github.com/slondr/eeaaf2e30a5d474f9cde8c81ccd8d4f2)

**Comment by ain** [comment]
Same issue on `2.7.6` as well, same trace.

**Comment by djfrodo** [comment]
I tried the above and still get an error installing 2.7.7...

**Comment by AaronKingston** [comment]
Still searching for the solution

**Comment by mujz** [comment]
> Same issue on `2.7.6` as well, same trace.
> 
> Following [How to install Ruby 3.0.3 with OpenSSL using MacPorts and RVM](https://mentalized.net/journal/2021/11/29/ruby-3-0-3-rvm-and-openssl-1-1/) resolves the issue when switched to OpenSSL 1.1:
> 
> ```
> PKG_CONFIG_PATH=/opt/local/lib/openssl-1.1/pkgconfig rvm reinstall 2.7.6 --with-openssl-lib=/opt/local/lib/openssl-1.1 --with-openssl-include=/opt/local/include/openssl-1.1
> ```
> 
> It fails with OpenSSL 3.

Thanks for this @ain, I took your suggestion and modified it a bit. I use Homebrew instead of MacPorts and this command worked for me:

```bash
PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@1.1/lib/pkgconfig rvm install 2.7.8 --with-openssl-lib=/opt/homebrew/opt/openssl@1.1 --with-openssl-include=/opt/homebrew/opt/openssl@1.1
```

**Comment by VanithashreeR** [comment]
For some reason even after I had set the pkg_config_path it was still pointing to openssl 3.
The below helped me solve the issue on mac using homebrew. 
brew unlink openssl@3
brew link openssl@1.1 --force

**Comment by NazarK** [comment]
> For some reason even after I had set the pkg_config_path it was still pointing to openssl 3.
> The below helped me solve the issue on mac using homebrew.
> brew unlink openssl@3
> brew link openssl@1.1 --force

fixed problem for me on macos ventura, while  "rvm install 2.7.6"

**Comment by denniswon** [comment]
> ```shell
> PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@1.1/lib/pkgconfig rvm install 2.7.8 --with-openssl-lib=/opt/homebrew/opt/openssl@1.1 --with-openssl-include=/opt/homebrew/opt/openssl@1.1
> ```

For me, it was `PKG_CONFIG_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1v/lib/pkgconfig/ rvm reinstall 2.7.6 --with-openssl-lib=/opt/homebrew/Cellar/openssl@1.1/ --with-openssl-include=/opt/homebrew/Cellar/openssl@1.1/1.1.1v/include/`

**Comment by soomrozaid** [comment]
> > Same issue on `2.7.6` as well, same trace.
> > Following [How to install Ruby 3.0.3 with OpenSSL using MacPorts and RVM](https://mentalized.net/journal/2021/11/29/ruby-3-0-3-rvm-and-openssl-1-1/) resolves the issue when switched to OpenSSL 1.1:
> > ```
> > PKG_CONFIG_PATH=/opt/local/lib/openssl-1.1/pkgconfig rvm reinstall 2.7.6 --with-openssl-lib=/opt/local/lib/openssl-1.1 --with-openssl-include=/opt/local/include/openssl-1.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It fails with OpenSSL 3.
> 
> Thanks for this @ain, I took your suggestion and modified it a bit. I use Homebrew instead of MacPorts and this command worked for me:
> 
> ```shell
> PKG_CONFIG_PATH=/opt/homebrew/opt/openssl@1.1/lib/pkgconfig rvm install 2.7.8 --with-openssl-lib=/opt/homebrew/opt/openssl@1.1 --with-openssl-include=/opt/homebrew/opt/openssl@1.1
> ```

For me it was `/usr/local/opt/openssl@1.1`. It's better to just use `$(brew --prefix openssl@1.1)` to get the directory address.

**Comment by ajakka** [comment]
This is what worked for me:

```
PKG_CONFIG_PATH=/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib/pkgconfig rvm reinstall ruby-2.7.5 --with-openssl-lib=/opt/homebrew/Cellar/openssl@1.1/1.1.1w/lib --with-openssl-include=/opt/homebrew/Cellar/openssl@1.1/1.1.1w/include
```

**Comment by amigobg** [comment]
I had the same issue on Linux, the workaround way to install 2.7.7
`rvm install ruby-2.7.7 --with-openssl-dir=$HOME/.rvm/usr`

**Comment by 13angel** [comment]
For me it was `PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig rvm reinstall 3.3.0 --with-openssl-lib=/usr/local/Cellar/openssl@1.1/1.1.1w --with-openssl-include=/usr/local/Cellar/openssl@1.1/1.1.1w/include`

**Comment by MissHenesy** [comment]
I've got an Apple M1 Max chip, and am running Sonoma 14.6.1.

I had a problem trying to get past installing Ruby 3.3.3. Even when running these commands, I would still get an OpenSSL Error:

```
# Set temp environment vars
export LDFLAGS="-L$(brew --prefix zlib)/lib -L$(brew --prefix openssl@1.1)/lib"
export CPPFLAGS="-I$(brew --prefix zlib)/include -I$(brew --prefix openssl@1.1)/include"
export PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig:$(brew --prefix openssl@1.1)/lib/pkgconfig"

# Install Ruby 3.3.3
rvm reinstall ruby-3.3.3 --with-zlib-dir=$(brew --prefix zlib) --with-openssl-dir=$(brew --prefix openssl@1.1)

# Check, set and verify the ruby version
ruby -v
rvm --default use ruby-3.3.3
rvm list

# Verify OpenSSL and zlib configuration
ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
ruby -rzlib -e 'puts Zlib::ZLIB_VERSION'	

```

But, no matter what, I ran into an `openSSL Load error`.

What finally worked::
Closing my terminal, and opening it up with Rosetta.

Everything just worked beautifully once I did that, and I was able to run:
```
gem install bundler
bundle install
```

Without a hitch!

I hope this helps someone.

**Comment by Rustik** [comment]
For those who installed `openssl` through rvm by running `rvm pkg install openssl` I used the installed package to install 2.7.5:
```
PKG_CONFIG_PATH=/Users/Your_Username/.rvm/usr/lib/pkgconfig rvm reinstall 2.7.5 --with-openssl-lib=/Users/Your_Username/.rvm/usr/lib --with-openssl-include=/Users/Your_Username/.rvm/usr/include/openssl
```
