### ISSUE TITLE
RVM install Ruby fails with "Error running '__rvm_make -j8'"

### ISSUE THREAD

**Issue by QuAcK3RjAcK** [rvm/rvm#5254]
## Description

Can't install ruby via RVM. 

Ruby Versions i tried:

- 2.6.3
- 2.6.6
- 3.0.0

## Steps to reproduce

 1. installed homebrew
 2. brew install openssl
 3. rehashed Certs with company certs
 4. installed rvm
 5. `rvm install 2.6.6 --with-openssl-dir=`brew --prefix openssl`

## Actual behavior

Always getting same Error:

```
$ rvm install 2.6.6 --with-openssl-dir=`brew --prefix openssl`
ruby-2.6.6 - #removing src/ruby-2.6.6 - please wait
Checking requirements for osx.
Certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/name/.rvm/rubies/ruby-2.6.6, this may take a while depending on your cpu(s)...
ruby-2.6.6 - #downloading ruby-2.6.6, this may take a while depending on your connection...
ruby-2.6.6 - #extracting ruby-2.6.6 to /Users/name/.rvm/src/ruby-2.6.6 - please wait
ruby-2.6.6 - #configuring - please wait
ruby-2.6.6 - #post-configuration - please wait
ruby-2.6.6 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/name/.rvm/log/1663870921_ruby-2.6.6/make.log

There has been an error while running make. Halting the installation.
```

LOG: [make.log GIST](https://gist.github.com/QuAcK3RjAcK/6eaa9233554eb919cdf4c12dfba5be69)

## Environment info

Completely new Mac. Got it this week.

MacBook Pro (14", 2021)
Apple M1 Pro

system:
    name:         "OSX"
    version:      "12.6"
    architecture: "arm64"
    remote_path:  "osx/12.6/arm64"
    xcode:        "14.0"

rvm:
    version:      "1.29.12 (latest)"

### What I tried so far

I tried following workarounds from other issues:

- [set CFLAGS](https://github.com/rvm/rvm/issues/5043)
- [set symbol prefix](https://github.com/rbenv/ruby-build/issues/1723)
- [completly reinstall all](https://github.com/rvm/rvm/issues/5229)
- [force link openssl](https://stackoverflow.com/questions/36649357/error-installing-ruby-2-3-on-osx/36896085#36896085)
- [switch to Xcode app instead of command line](https://github.com/nodejs/node-gyp/issues/569)

**Comment by msangel** [comment]
this is probably related with this: https://github.com/rbenv/ruby-build/discussions/1940
I have the same error on ubuntu 22.04 where only openssl v3 is installed

**Comment by msangel** [comment]
Also this seems to be fix: https://github.com/rvm/rvm/pull/5248

**Comment by QuAcK3RjAcK** [comment]
thanks for the links, so as mentioned I could install 3.1 with no error :)

but I also really need ruby in older versions. 
unfortunately the trick with setting `RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 rvm install 2.6.6` doesn't work

**Comment by solars** [comment]
Is there a solution to this already? Trying to switch to ruby 2.7.2 and can't.
As mentioned previously UBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 rvm install 2.7.2 doesn't work

**Comment by simonknoll** [comment]
For me, uninstalling brew and rvm and reinstalling it did the trick:
https://stackoverflow.com/a/74443264/328602

**Comment by rajkrgoyal** [comment]
I fixed it by following steps on Mac M1 Chip...

1. Open Rutella terminal
2. Uninstalling brew 
3. Install brew
4. restart terminal
5. Install ruby with rvm.

**Comment by jessearmandse** [comment]
A more simpler solution is to uninstall `openssl@3` and anything that depends on it:

```
brew uninstall gnupg gnutls libevent unbound wget

brew uninstall openssl@3

RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 rvm install 3.2.2
```

Then reinstall everything that was uninstalled

**Comment by paduh** [comment]
> Rutella terminal

@marcuxyz  I think he meant Rosetta terminal

**Comment by deeeeeelan** [comment]
> A more simpler solution is to uninstall `openssl@3` and anything that depends on it:
> 
> ```
> brew uninstall gnupg gnutls libevent unbound wget
> 
> brew uninstall openssl@3
> 
> RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 rvm install 3.2.2
> ```
> 
> Then reinstall everything that was uninstalled

thanks, you are a life saviour, this works for me after few hours trying multiple solutions

**Comment by lekemula** [comment]
> A more simpler solution is to uninstall `openssl@3` and anything that depends on it:
> 
> ```
> brew uninstall gnupg gnutls libevent unbound wget
> 
> brew uninstall openssl@3
> 
> RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 rvm install 3.2.2
> ```
> 
> Then reinstall everything that was uninstalled

`brew install --ignore-dependencies openssl@3` did the trick too, without needing to uninstall and reinstall every dependency.

**Comment by Ansarissab** [comment]
Try to install ruby with rvm like this

`rvm install ruby-3.2.1 -C --with-openssl-dir=/usr/local/etc/openssl@3`

**Comment by QuAcK3RjAcK** [comment]
> This worked for me:
> 
> ```
> rvm install 2.7.7 --with-openssl-dir=$HOME/.rvm/usr/include/ --force
> ```

This worked for me thx.

**Comment by pcantrell** [comment]
Note that solutions above assume a specific install location for OpenSSL that may be wrong if Homebrew is configured to use `/opt` instead of `/usr/local`.

Here’s a solution using Homebrew that should work either way:

```
brew install openssl@1.1  # May say “already installed and up-to-date”, which is just fine

rvm install 3.1.4 --with-openssl-dir=$(brew --prefix openssl@1.1)
```

**Comment by realafzallakdawala** [comment]
> > A more simpler solution is to uninstall `openssl@3` and anything that depends on it:
> > ```
> > brew uninstall gnupg gnutls libevent unbound wget
> > 
> > brew uninstall openssl@3
> > 
> > RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 rvm install 3.2.2
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then reinstall everything that was uninstalled
> 
> thanks, you are a life saviour, this works for me after few hours trying multiple solutions

I have tried with above given solution and it works!!!

**Comment by sahilbakoru** [comment]
> Try to install ruby with rvm like this
> 
> `rvm install ruby-3.2.1 -C --with-openssl-dir=/usr/local/etc/openssl@3`

thank you it worked for me .

**Comment by swapnilchincholkar** [comment]
For me this solution worked from [reference here](https://automationd.com/rvm-install-3-2-0-fails-with-error-running-rvm-make-j16/)
```
PKG_CONFIG_PATH=/usr/local/opt/openssl@1.1/lib/pkgconfig rvm install 3.2.0 --with-openssl --with-openssl-lib=/usr/local/opt/openssl@1.1/lib --with-openssl-include=/usr/local/opt/openssl@1.1/include
```

**Comment by mayankagnihotri7** [comment]
> Try to install ruby with rvm like this
> 
> `rvm install ruby-3.2.1 -C --with-openssl-dir=/usr/local/etc/openssl@3`

This worked for me while trying to get `ruby-3.0.1` installed. However I substituted the path with the one I got when I ran `which openssl`. Thank you so much.

**Comment by tiagocardosoc** [comment]
> Try to install ruby with rvm like this
> 
> `rvm install ruby-3.2.1 -C --with-openssl-dir=/usr/local/etc/openssl@3`

It's worked for me! I was a little bit worried cuz I didn't found a solution to solve this error. Thx a lot ^^

**Comment by deepakmahakale** [comment]
Nothing worked for me until xcode was upgraded

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

once done 

```
rvm reinstall 3.2.4 --with-openssl-dir=$(brew --prefix openssl@3)
```

This worked like a charm

**Comment by mohadel92** [comment]
> A more simpler solution is to uninstall `openssl@3` and anything that depends on it:
> 
> ```
> brew uninstall gnupg gnutls libevent unbound wget
> 
> brew uninstall openssl@3
> 
> RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 rvm install 3.2.2
> ```
> 
> Then reinstall everything that was uninstalled
@QuAcK3RjAcK 
for me this way the solution

**Comment by DK013** [comment]
> This worked for me:
> 
> ```
> rvm install 2.7.7 --with-openssl-dir=$HOME/.rvm/usr/include/ --force
> ```

This saved a lot of time. Thanks

**Comment by fhmurakami** [comment]
> > Try to install ruby with rvm like this
> > `rvm install ruby-3.2.1 -C --with-openssl-dir=/usr/local/etc/openssl@3`
> 
> This worked for me while trying to get `ruby-3.0.1` installed. However I substituted the path with the one I got when I ran `which openssl`. Thank you so much.
> 
> `rvm install ruby-3.0.1 -C --with-openssl-dir=/usr/bin/openssl`

This worked for me, thanks.
I'm using Ubuntu 22.04.4 LTS via WSL.

**Comment by developerJai** [comment]
https://github.com/rvm/rvm/issues/5254#issuecomment-1801500921

This solution worked for me

**Comment by gurdeep-punchh** [comment]
> Try to install ruby with rvm like this
> 
> `rvm install ruby-3.2.1 -C --with-openssl-dir=/usr/local/etc/openssl@3`

this worked from me thanks a lot.

**Comment by kouider2020** [comment]
Try : rvm repair all or rvm fix-permissions
