### ISSUE TITLE
"Error running '__rvm_make -j12'"

### ISSUE THREAD

**Issue by mykha** [rvm/rvm#5272]
## Description
WSL2 Ubuntu 22.04.1 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)
RVM 1.29.12
Command:
rvm install 2.6.2

Get an error:
Searching for binary rubies, this might take some time.
No binary rubies available for: ubuntu/22.04/x86_64/ruby-2.6.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for ubuntu.
Requirements installation successful.
Installing Ruby from source to: /usr/share/rvm/rubies/ruby-2.6.2, this may take a while depending on your cpu(s)...
ruby-2.6.2 - #downloading ruby-2.6.2, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13.9M  100 13.9M    0     0  4087k      0  0:00:03  0:00:03 --:--:-- 4086k
ruby-2.6.2 - #extracting ruby-2.6.2 to /usr/share/rvm/src/ruby-2.6.2.....
ruby-2.6.2 - #configuring.......................................................................
ruby-2.6.2 - #post-configuration..
ruby-2.6.2 - #compiling.....................................................................................................|
Error running '__rvm_make -j12',
please read /usr/share/rvm/log/1669745709_ruby-2.6.2/make.log

There has been an error while running make. Halting the installation.

## Steps to reproduce

 rvm install 2.6.2

## Expected behavior

functional install of ruby version 2.6.2

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info

[make.log](https://github.com/rvm/rvm/files/10116170/make.log)

**Comment by havenwood** [comment]
Hi! Some of the log links seem to be broken. Hem, the bottom one looks like it may be breaking on flags with CP-1252 encoding when UTF-8 is expected.

It might be worth setting `export LANG=C.UTF-8` or otherwise sanity checking your encoding with `locale`.

**Comment by Aaronphy** [comment]
+1

**Comment by facefor** [comment]
+1

**Comment by axveez** [comment]
+1

**Comment by min-verse** [comment]
Running into the same issue with the same OS trying to install ruby-2.7.4, if anybody has any updates

**Comment by patelgaurav4u** [comment]
+1

**Comment by mathieujobin** [comment]
the `make.log` posted by [Ganesh-Ponipireddy](https://github.com/Ganesh-Ponipireddy) contains this error...
```
In file included from vm.c:344:
./vm_insnhelper.c:5045:43: error: use of undeclared identifier 'RUBY_FUNCTION_NAME_STRING'
        fprintf(stderr, "%s %s(%d):%p\n", RUBY_FUNCTION_NAME_STRING, bf->name, bf->argc, bf->func_ptr);
```
quite weird, need to search around if this error also happens. 
I use `rvm` on OSX 12.6 and I have several rubies installed without any issue.
maybe try to `rvm get master` and update your xcode/command line tools.

The orignal poster @mykha entered his issue for Ubuntu under WSL.
He posted multiple log files. I don't have time to inspect them more. but in short `Error running make -jX` means nothing, the actual error is burried in the logs.

you can `grep -C 5 error: logfile` and post it here to save us from time.

Thanks
