### ISSUE TITLE
Error running '__rvm_make -j8',

### ISSUE THREAD

**Issue by vivektkclt** [rvm/rvm#5274]
Error running '__rvm_make -j8',
please read  ../.rvm/log/1669889466_ruby-2.7.5/make.log
There has been an error while running make. Halting the installation.

**Comment by dpaola2** [comment]
This is the error I see in #5278

**Comment by maioni** [comment]
At Pop!_OS 22.04 LTS x86_64 
Same issue when try to install RVM

maioni@pop-os:~$ echo /home/maioni/.rvm/log/1673116956_ruby-3.0.0/make.log 
/home/maioni/.rvm/log/1673116956_ruby-3.0.0/make.log
maioni@pop-os:~$ nano /home/maioni/.rvm/log/1673116956_ruby-3.0.0/make.log 
maioni@pop-os:~$ rvm pkg install openssl
Command 'rvm' not found, but there are 19 similar ones.
maioni@pop-os:~$ sudo apt install gnupg2
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  gnupg2
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 5,548 B of archives.
After this operation, 52.2 kB of additional disk space will be used.
Get:1 http://apt.pop-os.org/ubuntu jammy-security/universe amd64 gnupg2 all 2.2.27-3ubuntu2.1 [5,548 B]
Fetched 5,548 B in 1s (10.2 kB/s)  
Selecting previously unselected package gnupg2.
(Reading database ... 383534 files and directories currently installed.)
Preparing to unpack .../gnupg2_2.2.27-3ubuntu2.1_all.deb ...
Unpacking gnupg2 (2.2.27-3ubuntu2.1) ...
Setting up gnupg2 (2.2.27-3ubuntu2.1) ...
Processing triggers for man-db (2.10.2-1) ...
maioni@pop-os:~$ rvm pkg install openssl
Command 'rvm' not found, but there are 19 similar ones.
maioni@pop-os:~$ gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: key 105BD0E739499BDB: "Piotr Kuczynski <piotr.kuczynski@gmail.com>" not changed
gpg: key 3804BB82D39DC0E3: "Michal Papis (RVM signing) <mpapis@gmail.com>" 1 new signature
gpg: Total number processed: 2
gpg:              unchanged: 1
gpg:         new signatures: 1
maioni@pop-os:~$ \curl -sSL https://get.rvm.io | bash -s stable
Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made Fri 15 Jan 2021 03:46:22 PM -03
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/home/maioni/.rvm/archives/rvm-1.29.12.tgz'
Upgrading the RVM installation in /home/maioni/.rvm/
    RVM PATH line found in /home/maioni/.mkshrc /home/maioni/.profile /home/maioni/.bashrc /home/maioni/.zshrc.
    RVM sourcing line found in /home/maioni/.profile /home/maioni/.bash_profile /home/maioni/.zlogin.
Upgrade of RVM in /home/maioni/.rvm/ is complete.

Thanks for installing RVM 🙏
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: https://opencollective.com/rvm/donate


maioni@pop-os:~$ bash rvm-installer.sh stable --ruby
Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made Fri 15 Jan 2021 03:46:22 PM -03
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/home/maioni/.rvm/archives/rvm-1.29.12.tgz'
Upgrading the RVM installation in /home/maioni/.rvm/
    RVM PATH line found in /home/maioni/.mkshrc /home/maioni/.profile /home/maioni/.bashrc /home/maioni/.zshrc.
    RVM sourcing line found in /home/maioni/.profile /home/maioni/.bash_profile /home/maioni/.zlogin.
Upgrade of RVM in /home/maioni/.rvm/ is complete.

Thanks for installing RVM 🙏
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: https://opencollective.com/rvm/donate


Ruby enVironment Manager 1.29.12 (latest) (c) 2009-2020 Michal Papis, Piotr Kuczynski, Wayne E. Seguin

ruby-3.0.0 - #removing src/ruby-3.0.0..
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/bookworm_sid/x86_64/ruby-3.0.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system....
Installing required packages: libreadline6-dev...
Requirements installation successful.
Installing Ruby from source to: /home/maioni/.rvm/rubies/ruby-3.0.0, this may take a while depending on your cpu(s)...
ruby-3.0.0 - #downloading ruby-3.0.0, this may take a while depending on your connection...
ruby-3.0.0 - #extracting ruby-3.0.0 to /home/maioni/.rvm/src/ruby-3.0.0.....
ruby-3.0.0 - #configuring.........................................................................
ruby-3.0.0 - #post-configuration..
ruby-3.0.0 - #compiling..................................................................................................................-
Error running '__rvm_make -j8',
please read /home/maioni/.rvm/log/1673117504_ruby-3.0.0/make.log

There has been an error while running make. Halting the installation.
maioni@pop-os:~$ rvm install 2.3.0
Command 'rvm' not found, but there are 19 similar ones.
maioni@pop-os:~$ rvm
Command 'rvm' not found, but there are 19 similar ones.
maioni@pop-os:~$ \curl -sSL https://get.rvm.io | bash -s stable --rails
Downloading https://github.com/rvm/rvm/archive/1.29.12.tar.gz
Downloading https://github.com/rvm/rvm/releases/download/1.29.12/1.29.12.tar.gz.asc
gpg: Signature made Fri 15 Jan 2021 03:46:22 PM -03
gpg:                using RSA key 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
gpg: Good signature from "Piotr Kuczynski <piotr.kuczynski@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 7D2B AF1C F37B 13E2 069D  6956 105B D0E7 3949 9BDB
GPG verified '/home/maioni/.rvm/archives/rvm-1.29.12.tgz'
Upgrading the RVM installation in /home/maioni/.rvm/
    RVM PATH line found in /home/maioni/.mkshrc /home/maioni/.profile /home/maioni/.bashrc /home/maioni/.zshrc.
    RVM sourcing line found in /home/maioni/.profile /home/maioni/.bash_profile /home/maioni/.zlogin.
Upgrade of RVM in /home/maioni/.rvm/ is complete.

Thanks for installing RVM 🙏
Please consider donating to our open collective to help us maintain RVM.

👉  Donate: https://opencollective.com/rvm/donate


Ruby enVironment Manager 1.29.12 (latest) (c) 2009-2020 Michal Papis, Piotr Kuczynski, Wayne E. Seguin

ruby-3.0.0 - #removing src/ruby-3.0.0..
Searching for binary rubies, this might take some time.
No binary rubies available for: debian/bookworm_sid/x86_64/ruby-3.0.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for debian.
Installing requirements for debian.
Updating system....
Installing required packages: libreadline6-dev...
Requirements installation successful.
Installing Ruby from source to: /home/maioni/.rvm/rubies/ruby-3.0.0, this may take a while depending on your cpu(s)...
ruby-3.0.0 - #downloading ruby-3.0.0, this may take a while depending on your connection...
ruby-3.0.0 - #extracting ruby-3.0.0 to /home/maioni/.rvm/src/ruby-3.0.0.....
ruby-3.0.0 - #configuring.........................................................................
ruby-3.0.0 - #post-configuration..
ruby-3.0.0 - #compiling..................................................................................................................-
**Error running '__rvm_make -j8',**
please read /home/maioni/.rvm/log/1673117718_ruby-3.0.0/make.log

There has been an error while running make. Halting the installation.

**Comment by mathieujobin** [comment]
Can you please try with 2.7.7

then create aliases for any older ruby versions you need.
```bash
rvm alias create 2.5.5 2.7.7
rvm alias create 2.7.2 2.7.7
```

I will close to reduce noise on our side, but feel free to reopen if your issue remains
