### ISSUE TITLE
unable install any ruby versions through rvm with Mac M1 Ventura

### ISSUE THREAD

**Issue by seheesf88** [rvm/rvm#5285]
I am having an issue with installing ruby-2.7.5 for my react native app. 
I installed rvm as React native official home page recommend. 

my enviroment:
Mac OS - M1
Ventura
rvm 1.29.12-next (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

## Description

When I first installed it and checked ruby version with `rvm list`, I had ruby-3.0.0.
However I can't install ruby-2.7.5 with `rvm install 2.7.5`
I kept getting this error message:

```
Error running './configure --prefix=/Users/myname/.rvm/rubies/ruby-2.7.5  --with-opt-dir=/opt/homebrew/opt/libyaml:/opt/homebrew/opt/libksba:/opt/homebrew/opt/readline:/opt/homebrew/opt/zlib:/opt/homebrew/opt/openssl@1.1 --disable-install-doc --enable-shared',
please read /Users/myname/.rvm/log/1672114396_ruby-2.3.4/configure.log
There has been an error while running configure. Halting the installation.
```

Here is configure log 
```
configure: WARNING: you should use --build, --host, --target
checking for ruby... /usr/bin/ruby
tool/config.guess already exists
tool/config.sub already exists
checking build system type... arm-apple-darwin22.2.0
checking host system type... arm-apple-darwin22.2.0
checking target system type... arm-apple-darwin22.2.0
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/Users/myname/.rvm/src/ruby-2.7.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```
## Steps to reproduce
1. in terminal, `rvm install ruby-2.7.5` or `rvm install 2.7.5`
2. get above error

## Expected behavior
be able to install ruby-2.7.5 (actually any ruby version)

## Actual behavior
got an error message

I need to fix this asap because I don't have any ruby version installed now. 3.0.0 is removed while I was testing!

**Comment by G33kNoob** [comment]
do you have tried using rosetta terminal? it's work for me

**Comment by JoeNyland** [comment]
I'm a bit confused as you say you're trying to install 2.7.5, but the error refers to 2.3.4 and the log file it refers to mentions 2.7.1 🤔 

I'd cleanup with `rvm cleanup all`, then ensure you're on the latest stable version of RVM with `rvm get stable` and then try installing Ruby with `rvm install ruby`.

If this still doesn't work, I'd try completely uninstalling RVM with `rvm implode`, then reinstalling the latest stable version with `\curl -sSL https://get.rvm.io | bash -s stable` and then re-attempt to install Ruby with `rvm install ruby`.

**Comment by JoeNyland** [comment]
Also: make sure you've got XCode command line tools installed (sometimes needed after OS upgrades) with `xcode-select --install`

**Comment by smiley717** [comment]
still have the same issue to install any version of ruby with rvm, specifically configuring and compiling...
```
ruby-2.7.7 - #compiling - please wait
Error running '__rvm_make -j4',
please read /Users/xxx/.rvm/log/1679837849_ruby-2.7.7/make.log

There has been an error while running make. Halting the installation.
```

**Comment by Ununuk** [comment]
What helped me:
```
brew uninstall --ignore-dependencies openssl@3
brew reinstall openssl@1.1
rvm install 3.0.0
```

**Comment by clipsmm** [comment]
> rvm install 3.0.0

Thanks, this worked

**Comment by ppfreshworks** [comment]
@ConstLaf , this worked for me !
Thanks

**Comment by amitk-vmware** [comment]
check where your openssl@1.1 is installed by:
`brew --prefix openssl@1.1`

After that set the following flags, based on your OpenSSL installation destination:
```text
echo 'export PATH="/usr/local/opt/openssl@1.1/1.1.1m/bin:$PATH"' >> ~/.zshrc
export LDFLAGS="-L/usr/local/opt/openssl@1.1/1.1.1m/lib"
export CPPFLAGS="-I/usr/local/Cellar/openssl@1.1/1.1.1m/include"
export PKG_CONFIG_PATH="/usr/local/Cellar/openssl@1.1/1.1.1m/lib/pkgconfig"
source ~/.zshrc
rvm autolibs disable
export RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC
export optflags="-Wno-error=implicit-function-declaration"
rvm install 2.5.7 --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1m/
```

After trying multiple solutions this has worked for me in the end.

**Comment by edinaldo12** [comment]
> still have the same issue to install any version of ruby with rvm, specifically configuring and compiling...
> 
> ```
> ruby-2.7.7 - #compiling - please wait
> Error running '__rvm_make -j4',
> please read /Users/xxx/.rvm/log/1679837849_ruby-2.7.7/make.log
> 
> There has been an error while running make. Halting the installation.
> ```

Have the same problem but instead of getting the `Error running '__rvm_make -j4'` i got the following

```
Error running '__rvm_make -j8',
please read /Users/user/.rvm/log/1689709112_ruby-2.4.4/make.log
There has been an error while running make. Halting the installation.
```
Currently i have installed RVM in the following version: rvm 1.29.12-next

The suggestion supplied by @Ununuk did word for installing the rubies version 3.2.2 and 3.0.0 but older versions cant install

**Comment by ibrahimab** [comment]
rvm has the autolibs option to set the package manager you're using or to completely put it in its hands and more: https://rvm.io/rvm/autolibs

To be able to install rvm and ruby I just installed homebrew, then installed rvm and then ran `rvm autolibs homebrew`. Afterwards i was able to install the ruby versions i needed. rvm handled the compile/install through homebrew from there.

Note:
I have yet to try this out on a machine with existing setups (eg. existing homebrew with existing openssl installed or any other combo) as I don't need it. Maybe someone here might wanna do that testrun.

**Comment by rwaffen** [comment]
for me the following worked:

```bash
rvm install 3.2.2 --with-openssl-dir=$(brew --prefix)/opt/openssl@3
```

**Comment by aisrael** [comment]
This is what worked for me (macOS 14.x Sonoma, Apple M2):
```
rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl@3)
```

**Comment by ScottLWasserman-Stuzo** [comment]
> This is what worked for me (macOS 14.x Sonoma, Apple M2):
> 
> ```
> rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl@3)
> ```

That's the only one that worked for me! Thank you. 🙇‍♂️

**Comment by deodesumitsingh** [comment]
> What helped me:
> 
> ```
> brew uninstall --ignore-dependencies openssl@3
> brew reinstall openssl@1.1
> rvm install 3.0.0
> ```

This worked for me thank you so much :)

**Comment by seheesf88** [comment]
> What helped me:
> 
> ```
> brew uninstall --ignore-dependencies openssl@3
> brew reinstall openssl@1.1
> rvm install 3.0.0
> ```

Thank you ❤️

**Comment by shuxiaoman** [comment]
> What helped me:
> 
> ```
> brew uninstall --ignore-dependencies openssl@3
> brew reinstall openssl@1.1
> rvm install 3.0.0
> ```

you are my god

**Comment by supreethmr** [comment]
> What helped me:
> 
> ```
> brew uninstall --ignore-dependencies openssl@3
> brew reinstall openssl@1.1
> rvm install 3.0.0
> ```

rvm install did not worked on arm64 Mac M1 Sonama 14.3.1 Below command worked for me after re-installing openssl@1.1

```ruby
RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@1.1 arch -x86_64 rvm install 2.x.x
 ```

**Comment by yoshyosh** [comment]
I had to make sure I was using Rosetta terminal, for some reason my settings switched on my terminal. 
After that `rvm install 3.3.0` worked without issues

**Comment by 0xtruly** [comment]
> check where your openssl@1.1 is installed by: `brew --prefix openssl@1.1`
> 
> After that set the following flags, based on your OpenSSL installation destination:
> 
> ```
> echo 'export PATH="/usr/local/opt/openssl@1.1/1.1.1m/bin:$PATH"' >> ~/.zshrc
> export LDFLAGS="-L/usr/local/opt/openssl@1.1/1.1.1m/lib"
> export CPPFLAGS="-I/usr/local/Cellar/openssl@1.1/1.1.1m/include"
> export PKG_CONFIG_PATH="/usr/local/Cellar/openssl@1.1/1.1.1m/lib/pkgconfig"
> source ~/.zshrc
> rvm autolibs disable
> export RUBY_CFLAGS=-DUSE_FFI_CLOSURE_ALLOC
> export optflags="-Wno-error=implicit-function-declaration"
> rvm install 2.5.7 --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1m/
> ```
> 
> After trying multiple solutions this has worked for me in the end.

 Thanks. This solution did it for me

**Comment by ashaffah** [comment]
> This is what worked for me (macOS 14.x Sonoma, Apple M2):
> 
> ```
> rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl@3)
> ```

Thanks. This solution works for me

**Comment by randy** [comment]
I did this (macOS 14.4, Apple M3):
```
 brew uninstall --ignore-dependencies openssl@3
 brew reinstall openssl@3.0
 rvm install 3.0.0
```
Not entirely sure why `openssl` has `@3` and `@3.0`, but it does; that is not a typo... I already had `@1.1` installed, so figured I'd try `@3.0` first and it worked.

**Comment by siddhartha3295** [comment]
Here I have added another Ruby version with stable Ruby version  in RVM Checkout 
---------------------------------------------------------------------
brew uninstall --ignore-dependencies openssl@3
brew reinstall openssl@1.1
\curl -sSL https://get.rvm.io | bash -s stable --rails
source /Users/siddharthagupta/.rvm/scripts/rvm

---------------------------------------------------------------------

brew uninstall --ignore-dependencies openssl@3\n
brew reinstall openssl@1.1\n
\curl -sSL https://get.rvm.io | bash
\curl -sSL https://get.rvm.io | bash -s stable --rails\n 
rvm -version
source /Users/siddharthagupta/.rvm/scripts/rvm
rvm -v
rvm list

-----------------------------------------------------------------------
rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl@3)

**Comment by lucksp** [comment]
Having tried all the above, still Unable to install RVM2.7.6

```
Checking requirements for osx.
==> Upgrading 1 outdated package:
openssl@1.1 1.1.1u -> 1.1.1w
Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.
Requirements installation failed with status: 1.
```

**Comment by vicomte** [comment]
If you can only use brew, you will have to find another way to obtain openssl-1.x, like building from source, pretty much for anything before Ruby 3.2.

**Comment by rpatel29** [comment]
rvm install or rvm upgrade gave this error -
`Error: openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.`

I tried @vicomte suggestion, `rvm install 3.0.0 --autolibs=1` seems to work. Read https://rvm.io/rvm/autolibs

**Comment by rpatel29** [comment]
This worked for me - 
uninstalled rvm  -`rvm implode`
I used rbenv (install if you haven't already) - `rbenv install 3.3.5`
set the global version - `rbenv global 3.3.5`

**Comment by mahtab732** [comment]
rvm install 3.3.6 --with-openssl-dir=`brew --prefix openssl`

**Comment by driven-chris** [comment]
I fixed it by adding this to my `.zprofile`:

`export RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@3`

**Comment by driven-chris** [comment]
> I did this (macOS 14.4, Apple M3):
> 
> ```
>  brew uninstall --ignore-dependencies openssl@3
>  brew reinstall openssl@3.0

I fixed it by running the above, then adding this to my `.zprofile`:

`export RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/opt/openssl@3`

**Comment by drivas-val** [comment]
This worked for me for 2.6.1 I'm running M2 on Sequoia. 

First and most obviously make sure you have homebrew:

`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`

Install the correct version of openssl:

Ruby <= 2.4  —> OpenSSL1.0
Ruby 2.4-3.0 —> OppenSSL1.1
Ruby => 3.1 —> OpenSSL 3.x

`brew install openssl@1.1`

Now just make sure you have a stable version of RVM installed:

`curl -sSL https://get.rvm.io | bash -s stable`

nano into your .zshrc file and make sure you have it correctly setup should look something like this:

export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

```
export LDFLAGS="-L$(brew --prefix openssl@1.1)/lib"
export CPPFLAGS="-I$(brew --prefix openssl@1.1)/include"
export PKG_CONFIG_PATH="$(brew --prefix openssl@1.1)/lib/pkgconfig"
export PATH="$(brew --prefix openssl@1.1)/bin:$PATH"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
export PATH="$PATH:$HOME/.rvm/bin"
```

Note: Make sure the last two lines are in the end of your .zshrc file

Load in the updated config

`source ~/.zshrc`

Now for the magic:

`CFLAGS="-Wno-error=implicit-function-declaration -Wno-compound-token-split-by-macro" PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.1/lib/pkgconfig" rvm install 2.6.1 --with-openssl-dir=/opt/homebrew/opt/openssl@1.1`

And then lastly use it and make sure the version has changed:

`rvm use 2.6.1`
`ruby -v`

**Comment by kikikimbing** [comment]
> Install the correct version of openssl:
> 
> Ruby <= 2.4 —> OpenSSL1.0 Ruby 2.4-3.0 —> OppenSSL1.1 Ruby => 3.1 —> OpenSSL 3.x

This one work for me, im using mac M3 Sequoia
