### ISSUE TITLE
Consider releasing 1.29.13?

### ISSUE THREAD

**Issue by ivoanjo** [rvm/rvm#5290]
Hello there, and thanks a lot for rvm! I've been using it for quite a long time and it's a really great tool.

I just got bit by an issue that was actually fixed in master (I was running 1.29.12). I was able to fix it by installing the latest rvm using `rvm get latest`.

But it did take a few minutes of head-scratching and searching to find out that this issue was already fixed and the fix merged. I also noticed that there's quite a lot of fixes that have accumulated in the master branch (1.29.13 milestone: https://github.com/rvm/rvm/milestone/47).

Thus I thought to suggest that it may be a good time to cut a release with all of the fixes.

Thanks again!

**Comment by raelgc** [comment]
Any plans, @pkuczynski?

**Comment by luke-hill** [comment]
Just as a bump. It's been almost 2 years since the last release and this is quite a widely used piece of software. If there's options / opportunities to bring on an extra pair of hands for someone who wants to help then that could aid you?

**Comment by duaneking** [comment]
Not releasing this software for two years was a mistake IMHO; With respect, You should have at least monthly builds, as rvm is not just a utility, its a critical part of the ruby ecosystem and the ruby ecosystem is dead without it.

**Comment by raelgc** [comment]
@duaneking I agree that a release should be out for months, but it's not a blocker: you can run `rvm get master` and update to the latest. Not to mention alternatives, like `rbenv` and others.

I'm, like other `rvm` members, a contributor in my free time. You're welcome to join the team, if you want.

**Comment by ivoanjo** [comment]
+1 the rvm maintainers don't owe us anything @duaneking -- all we can do is ask (and sponsor) and they'll get around to if it they can.

**Comment by duaneking** [comment]
> @duaneking I agree that a release should be out for months
Good.

> but it's not a blocker:
False. Yes it is.  For many people.
 
> you can run `rvm get master` and update to the latest.
No true. This is not always a viable option in corporate environments; A stable release cycle that doesn't ignore the community or the companies that employ them for years at a time is honestly preferable to me.

> Not to mention alternatives, like `rbenv` and others.

They are not an option due to compatibility issues.

> I'm, like other `rvm` members, a contributor in my free time. You're welcome to join the team, if you want.

This project has not shipped anything stable in years;; why would I want to join a development team that doesn't do anything? Show me a repeating cycle of stable releases and I'll consider it.

**Comment by ivoanjo** [comment]
With my apologies to the rvm developers, I did not mean to attract this kind of comments so I shall close this issue.

**Comment by duaneking** [comment]
closing this issue would actively harm the Ruby community and would just give people like me who feel like Ruby is dying another data point that proves it.

We critically need a new release of the items that are in unstable as stable, And this illogical and irrational choice to not release this software for years at a time is actively hurting the community at large.

**Comment by duaneking** [comment]
https://github.com/rvm/rvm/issues/5330
