### ISSUE TITLE
Cannot run 'rvm get head'

### ISSUE THREAD

**Issue by chauhonglinh** [rvm/rvm#5293]
When I ran `rvm get head` on my local machine, I got this error:

```
Could not download rvm-installer, please report to https://github.com/rvm/rvm/issues
```

I was able to run it at the beginning of January 2023.

**Comment by mathieujobin** [comment]
can you please try again and reopen if the issue persist?

**Comment by mathieujobin** [comment]
oh, try `rvm get master` instead.
