### ISSUE TITLE
Could not download rvm-installer, please report to https://github.com/rvm/rvm/issues

### ISSUE THREAD

**Issue by msureshm** [rvm/rvm#5294]
## Steps to reproduce

 1. rvm get head

## Expected behavior

Update rvm to latest version

## Actual behavior

Getting below error:
Could not download rvm-installer, please report to https://github.com/rvm/rvm/issues

**Comment by mathieujobin** [comment]
please try again or `rvm get master` instead.
reopen if it remains an issue
