### ISSUE TITLE
not able to install ruby 3.0.1     Error running '__rvm_make -j8', please read /usr/local/rvm/log/1674544495_ruby-3.0.1/make.log  There has been an error while running make. Halting the installation

### ISSUE THREAD

**Issue by DF-anuj** [rvm/rvm#5296]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by Viko96** [comment]
Same thing with 2.7.2 in Ubuntu 22

**Comment by jesperronn** [comment]
@DF-anuj could you please update the description or delete the issue? Nobody can help you based on this description

**Comment by mathieujobin** [comment]
not enough information
