### ISSUE TITLE
'__rvm_make -j8 error' on rvm install 2.7.0 (M1 MBPro, Monterey 12.5)

### ISSUE THREAD

**Issue by fengyanxin** [rvm/rvm#5301]
## Description

rvm install 2.7.0

Get:

Error running '__rvm_make -j8',
please read /Users/penghe/.rvm/log/1675298402_ruby-2.7.0/make.log
There has been an error while running make. Halting the installation.

## Actual behavior

* [make.log](https://github.com/rvm/rvm/files/10563829/make.log)

**Comment by lebigsquare** [comment]
How was the error fixed ? :)

**Comment by fengyanxin** [comment]
> 

1、brew install openssl@1.1

2、Configure environment variables into .zshrc /.bashrc ：

export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

3、which openssl@1.1 
get openssl path: eg: /usr/local/opt/openssl@1.1/bin/openssl

4、rvm install ruby-2.7.0 --with-openssl-dir=/usr/local/opt/openssl@1.1/bin/openssl

**Comment by lebigsquare** [comment]
THANKS ! Anyone reading this with installation problems : this works !
