### ISSUE TITLE
I'm unable to update rvm in order to download ruby 2.7.4

### ISSUE THREAD

**Issue by Chris-Kamau** [rvm/rvm#5327]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by raelgc** [comment]
Please, provide more details. Anyway, update rvm with `rvm get master` to get the latest.
