### ISSUE TITLE
Release a New Stable as soon as possible, please.

### ISSUE THREAD

**Issue by duaneking** [rvm/rvm#5330]
## Description

As frustrating as it might be to hear for some people, RVM is a core part of critical infrastructure for the Ruby ecosystem due to its very entrenched usage and the overall design and history of ruby explicitly requiring it.  As a result, many people have no ability to use Ruby at all without using RVM, And many environments actively require it as a prerequisite in order to do any work.

So in short, many people cannot use Ruby at all without using something like RVM to deal with version issues, And because RVM is the most well known, it's largely considered the default in the ruby community - even if other alternatives are starting to exist due to this projects lack of stable releases - because of the great need within The Ruby Development Community to be able to manage ruby version issues in the way that it provides.

This is the state of the Ruby ecosystem.

The good news is that RVM provides exactly what the Ruby ecosystem needs when its stable and releasing versions consistently; The bad news is that from the public's perspective, even if that's not actually true and its possible to update once you get a working install (and getting that working install can be the hardest part!), the perception of this project is that it's dead, and has been for years, due to a lack of releases, and that in itself is hurting the Ruby community, because this project is seen as such a critical part of the Ruby community that even the perception of this project not being active makes the rest of the Ruby community that depends on it feel less safe to invest in by companies that hire engineers that want to use ruby.

I get that some of you are just passively working on an open source project in your spare time for fun; But what you don't understand is that this has basically turned into critical infrastructure for Ruby, so the same way many people wouldn't want to buy a house without a working toilet, many wont or cant work without it.

The old version of RVM that was released years ago cannot even be installed on some systems due to these issues fixed in master but unreleased as a stable release; more importantly it actively makes the project look bad to upper management or non-technical C-level individuals that actively control hiring budgets at companies, because to their perspective, these projects are not active anymore because there have been no stable releases in years.

Telling people to upgrade from Master is not a release strategy. Its a failure to ship software to the general public. It also makes people who control engineering teams have no faith in the Ruby ecosystem, because they are worried that the critical plumbing that RVM represents and critically depends on, just won't work in a critical time of need due to that lack of investment by its own community.

This leads to the people with the control over budgets saying to their engineers "no we're not gonna use Ruby, because these critical tools are not even maintained, and the old version only work on expensive macs we cant source easily anymore, and I don't want to spring for a 6k mac per dev when we can use C# or Python for free on cheaper hardware and start working on this project now.", as they look at the community for Ruby and decide that it's not strong enough to be able to care for or maintain the infrastructure they would need to depend on if they included it in their business operations.

I am forced to use Ruby at work.  It doesn't matter if it's my first choice or not, because I'm a part of the Ruby community via the above mentioned entrenched technical debt, and due to this I'm under the impression that it's my social and good faith responsibility as a member of the Ruby community to call out when I don't feel joy as a ruby developer; So I'm doing that here and asking, pleading, as respectfully as I can, for a stable release of RVM that is current.

## Steps to reproduce

Look at the release schedule and notice that this project hasn't released anything stable for years.

## Expected behavior

I definitely have my own opinions on how fast a release cycle should be, but I'm respectful enough to understand that I can't dictate to you a schedule here. 

That stated: It would be really nice if you could do at least one release per three months.

Either way, I would like to respectfully request that a new release happen at least once a year from now on.

## Actual behavior

No stable releases for years.

## Environment info

all

**Comment by havenwood** [comment]
I've heard on the wind a release may be coming soon, but starting issues about it doesn't help or speed things up. You're very welcome to contribute time or funding but please remember this is open source.

> But what you don't understand is that this has basically turned into critical infrastructure for Ruby, so the same way many people wouldn't want to buy a house without a working toilet, many wont or cant work without it.

I think you're presuming too much. Some contributors don't even use RVM themselves but volunteer time just for the sake of helping fellow Rubyists who might use RVM. Part of the reason there aren't more RVM volunteers and funding is that there are great alternatives like chruby+ruby-install, rbenv and asdf. I also contribute to chruby, which is what I personally use. I know other RVM members use chruby as well. There are multiple good options.

If you'd like to be release manager for RVM please make a proposal and discuss with maintainers. Otherwise, this isn't actionable unless someone else volunteers. For what it's worth, most folk use RVM by installing latest. I'd recommend doing that if you're not interested in contributing.

**Comment by havenwood** [comment]
If you'd like to start an initiative to sponsor the capability of quarterly RVM releases it'd be welcome. If someone steps up to do the work it would be great. This just isn't an issue we can fix without contribution.

**Comment by duaneking** [comment]
> I've heard on the wind a release may be coming soon, but starting issues about it doesn't help or speed things up.

You seem to be saying that making a simple and respectful request for a new release that will enable development for blocked teams is "starting issues"; Respectfully, That is not true, and if you honestly feel otherwise, I respectfully request that you explain why.

> I think you're presuming too much. Some contributors don't even use RVM themselves

That's a worse case scenario for a language community dependent on people using the toolset.

> There are multiple good options.

Sure, but if the stack requires rvm, these are not options.

> If you'd like to be release manager for RVM please make a proposal and discuss with maintainers.

Respectfully, I would rather not be release manager for rvm, but thank you for the offer,

> Otherwise, this isn't actionable unless someone else volunteers.

I'm stuck in rails update hell and I don't have a way forward without this.; this is literally what RVM was created for.  But its not working.

> For what it's worth, most folk use RVM by installing latest.

The issue here is that it's sometimes a recursive dependency due to the large number of bugfixes that exist in the master branch that have not been released as stable.  RVM also installs the wrong gems in an attempt to update on many ruby installs; so it breaks things. I just want a stable release I can depend on so I can save some lives.

I want nothing more than to at least be able to use the latest bits of ruby/rails/etc on the projects I'm currently forced to use ruby on.. but due to the above mentioned state of the ruby community that is not an option.

> This just isn't an issue we can address without contribution.

May I ask WHY?

From my perspective it feels like you're refusing to release stable code, and that is the weirdest thing ever,

**Comment by havenwood** [comment]
You're welcome to contribute or organize to help but nobody is refusing to release code. Volunteers are releasing stable updates infrequently and small updates more frequently as limited bandwidth allows. Please don't demand releases when you're as free as anyone else to make them happen. I'm going to lock this since it's not productive and is a distraction to maintainers. Contributions are welcome, but please don't make demands of volunteers when you're not willing to volunteer.

**Comment by havenwood** [comment]
Just to add some clarification, you can install latest RVM with `\curl -sSL https://get.rvm.io | bash` or update to latest with `rvm get head`. The stable concept is somewhat legacy, from when major RVM changes were happening frequently. RVM is just stable now and you can use latest.

In order for a stable release to be cut, @pkuczynski or another release manager with access to sign it needs to do so.

If you'd like to start a an Issue suggesting that signing as a requirement go away so versions can be cut automatically, or that we adopt tagged GitHub version releases without signing, or change the documentation to make it clear to use latest, or any other potential solution it would be on topic and welcome.
