### ISSUE TITLE
cannot install. SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by distillant** [rvm/rvm#5341]
## Description
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

## Steps to reproduce

rvm get stable

 1. gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
 2. \curl -sSL https://get.rvm.io | bash   

## Expected behavior

expected it to download script and execute in bash

## Actual behavior

certificate has expired

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

## Environment info
  system:
    uname:        "Darwin Incredibles-MacBook-Air.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.15"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)"
    zsh:          "/bin/zsh => zsh 5.7.1 (x86_64-apple-darwin19.0)"
    remote_path:  "osx/10.15/x86_64"
    xcode:        ""

**Comment by mathieujobin** [comment]
it works for me...

**Comment by distillant** [comment]
ok, I got the same issue on two macs, but at least it worked on AWS, so I'll close the ticket.
