### ISSUE TITLE
Ruby doesn't compile on macOS if openssl 3.1 is installed

### ISSUE THREAD

**Issue by BrianHawley** [rvm/rvm#5365]
## Description

I tried to install ruby-3.2.2 and ruby-3.1.2 on macOS Ventura, after using Homebrew to install rust so I could enable YJIT support for ruby-3.2.2. The rust formula had the `openssl@3` formula as a dependency, which was openssl 3.1.1.1 at the time, and having that installed made rvm try to use it when compiling ruby, which failed.

## Steps to reproduce

On macOS Ventura, with Homebrew.

 1. `brew install rust` (for YJIT support) or `brew install openssl@3` (for minimal reproduction)
 2. `rvm get master`
 3. `rvm install ruby-3.2.2 --reconfigure --enable-yjit` (for YJIT support) or `rvm install ruby-3.2.2` (for minimal reproduction)

## Expected behavior

RVM should install its base requirements, then Ruby should be configured, compiled, and installed.

## Actual behavior

* `rvm install ruby-3.2.2 --reconfigure --enable-yjit`

```
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/t442172/.rvm/rubies/ruby-3.2.2, this may take a while depending on your cpu(s)...
ruby-3.2.2 - #downloading ruby-3.2.2, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.5M  100 19.5M    0     0  18.8M      0  0:00:01  0:00:01 --:--:-- 18.9M
ruby-3.2.2 - #extracting ruby-3.2.2 to /Users/t442172/.rvm/src/ruby-3.2.2 - please wait
ruby-3.2.2 - #autogen.sh - please wait
ruby-3.2.2 - #configuring - please wait
ruby-3.2.2 - #post-configuration - please wait
ruby-3.2.2 - #compiling - please wait
Error running '__rvm_make -j16',
please read /Users/t442172/.rvm/log/1688431646_ruby-3.2.2/make.log

There has been an error while running make. Halting the installation.
```

* [configure.log](https://gist.github.com/BrianHawley/d9d9dc3eb5fc83bcda6b141caab6918f#file-configure-log)
* [make.log](https://gist.github.com/BrianHawley/d9d9dc3eb5fc83bcda6b141caab6918f#file-make-log)

It's notable that the configure.log made reference to the `openssl@1.1` formula that `rvm requirements` installed, but make.log makes reference to the `openssl@3` formula that was installed earlier as a dependency of the rust formula. I had similar results trying to install ruby-3.1.2, but the errors were much more extensive.

## Environment info

```
system:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  system:
    uname:        "Darwin AC02GQ0BN1PG3 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:22 PDT 2023; root:xnu-8796.121.3~7/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "13.4"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)"
    zsh:          "/bin/zsh => zsh 5.9 (x86_64-apple-darwin22.0)"
    remote_path:  "osx/13.4/x86_64"
    xcode:        ""

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "1 day 17 hours 11 minutes 26 seconds ago"
    path:         "/Users/t442172/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/usr/local/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Users/t442172/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by BrianHawley** [comment]
After some guessing, I guessed that this was an openssl 3.1 incompatibility. I managed to get it to work by installing the `openssl@3.0` formula and using that version specifically.

```
% brew install openssl@3.0
...
% rvm install ruby-3.2.2 --reconfigure --enable-yjit --with-openssl-dir=$(brew --prefix openssl@3.0)
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/t442172/.rvm/rubies/ruby-3.2.2, this may take a while depending on your cpu(s)...
ruby-3.2.2 - #downloading ruby-3.2.2, this may take a while depending on your connection...
ruby-3.2.2 - #extracting ruby-3.2.2 to /Users/t442172/.rvm/src/ruby-3.2.2 - please wait
ruby-3.2.2 - #autogen.sh - please wait
ruby-3.2.2 - #configuring - please wait
ruby-3.2.2 - #post-configuration - please wait
ruby-3.2.2 - #compiling - please wait
ruby-3.2.2 - #installing - please wait
ruby-3.2.2 - #making binaries executable - please wait
Installed rubygems 3.4.10 is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
ruby-3.2.2 - #gemset created /Users/t442172/.rvm/gems/ruby-3.2.2@global
ruby-3.2.2 - #importing gemset /Users/t442172/.rvm/gemsets/global.gems - please wait
ruby-3.2.2 - #generating global wrappers - please wait
ruby-3.2.2 - #gemset created /Users/t442172/.rvm/gems/ruby-3.2.2
ruby-3.2.2 - #importing gemsetfile /Users/t442172/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-3.2.2 - #generating default wrappers - please wait
ruby-3.2.2 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-3.2.2 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri
```

**Comment by d12** [comment]
Running into the same issue on initial installation of rvm. The compilation error is:

```
ossl_pkey_rsa.c:950:5: error: use of undeclared identifier 'RSA_SSLV23_PADDING'
```

**Comment by BrianHawley** [comment]
It might be worth noting that macOS Ventura has a system openssl of "LibreSSL 3.3.6", but I don't know whether Ruby will compile with that or which option to specify to make it do so (which directory to pass to `--with-openssl-dir`).

**Comment by BrianHawley** [comment]
Suspiciously enough, for ruby-3.2.2 (openssl gem 3.1.0) installing against the `openssl@3` formula (openssl library 3.1.1), I get the same error as the one reported in https://github.com/ruby/openssl/issues/592 which was for a different scenario. Still, the suggested causes there might also apply here.

**Comment by icungse** [comment]
I recently failed intaslling by command 'rvm install 2.7.2'. Then successfully installed using `rvm install 2.7'  as docemmented [here](https://rvm.io/rvm/install#try-out-your-new-rvm-installation)

**Comment by timsutton** [comment]
> macOS Ventura has a system openssl of "LibreSSL 3.3.6", but I don't know whether Ruby will compile with that

I don't have the source of this info at hand, but Apple explicitly prevents other projects from being able to link against their system LibreSSL in the same way that is possible with a regular OSS built install.

**Comment by amamrenko** [comment]
`brew uninstall --ignore-dependencies openssl`
`brew reinstall openssl@3`
`rvm install ruby-3.2.2 --reconfigure --enable-yjit --with-openssl-dir=$(brew --prefix openssl@3)`

works on my side

**Comment by belt** [comment]
> `brew uninstall --ignore-dependencies openssl` `brew reinstall openssl@3` `rvm install ruby-3.2.2 --reconfigure --enable-yjit --with-openssl-dir=$(brew --prefix openssl@3)`
> 
> works on my side

Do you see something like the following in your output?

**Comment by skatkov** [comment]
Ran into similar issue as well, but this solved it for me:
`rvm reinstall 3.2.2 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs`

**Comment by mikescar** [comment]
can confirm @skatkov  solution works for OS X Sonoma (14.2.1), ruby 3.3, openssl@3 

`rvm install ruby-3.3.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs`

**Comment by joeprivettsmart** [comment]
I'm running into a problem when trying to install any verison of Ruby:

```
rvm reinstall 3.2.2 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs

ruby-3.2.2 - #removing src/ruby-3.2.2 - please wait
Checking requirements for rvm_pkg.

Warning, you are using 'rvm autolibs rvm_pkg', this is rarely used and can produce errors,
make sure to report any problems to https://github.com/rvm/rvm/issues

Installing requirements for rvm_pkg.
Updating system - please wait
Always update your system first!
Installing required packages: readline - please wait
Error running '__rvm_autoreconf -is --force',
please read /Users/joe.privett/.rvm/log/1710533766_ruby-3.2.2/readline_autoreconf.log
Error running '__rvm_make ',
please read /Users/joe.privett/.rvm/log/1710533766_ruby-3.2.2/readline_make.log

Please note that it's required to reinstall all rubies:

    rvm reinstall all --force

Error running '__rvm_autoreconf -is --force',
please read /Users/joe.privett/.rvm/log/1710533766_ruby-3.2.2/readline_autoreconf.log
Error running '__rvm_make ',
please read /Users/joe.privett/.rvm/log/1710533766_ruby-3.2.2/readline_make.log

Please note that it's required to reinstall all rubies:

    rvm reinstall all --force

Requirements installation successful.
Installing Ruby from source to: /Users/joe.privett/.rvm/rubies/ruby-3.2.2, this may take a while depending on your cpu(s)...
ruby-3.2.2 - #downloading ruby-3.2.2, this may take a while depending on your connection...
ruby-3.2.2 - #extracting ruby-3.2.2 to /Users/joe.privett/.rvm/src/ruby-3.2.2 - please wait
ruby-3.2.2 - #autogen.sh - please wait
ruby-3.2.2 - #configuring - please wait
ruby-3.2.2 - #post-configuration - please wait
ruby-3.2.2 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/joe.privett/.rvm/log/1710533766_ruby-3.2.2/make.log

There has been an error while running make. Halting the installation.
```

**Comment by justdan0227** [comment]
Does anyone have experience doing this with rbenv?  Just updated to Mac 14.1.1 and having issues 

rbenv install 3.1.0
==> Downloading ruby-3.1.0.tar.gz...
-> curl -q -fL -o ruby-3.1.0.tar.gz https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.0.tar.gz


BUILD FAILED (macOS 14.4.1 on arm64 using ruby-build 20240319)

**Comment by monfresh** [comment]
@justdan0227 Try installing 3.1.4. Whenever installing any Ruby version, you always want to make sure you are using the latest patch version (the 3rd digit). In the 3.1.x series, the latest version is 3.1.4. There are known issues with older patch versions, so the first thing I recommend to everyone is to make sure you're installing the latest patch version.

Here's a more detailed guide I wrote that explains why and [how to upgrade the Ruby version in your project](https://www.rubyonmac.dev/how-to-upgrade-the-ruby-version-in-your-project).

**Comment by ancabury** [comment]
> `brew uninstall --ignore-dependencies openssl` `brew reinstall openssl@3` `rvm install ruby-3.2.2 --reconfigure --enable-yjit --with-openssl-dir=$(brew --prefix openssl@3)`
> 
> works on my side

inspired by this, I made it work for ruby `3.2.4` on macOS 14.4.1 (23E224) with a chip: Apple M1 Pro

```
brew uninstall --ignore-dependencies openssl
brew reinstall openssl@3.0
rvm install ruby-3.2.4 --reconfigure --enable-yjit --with-openssl-dir=$(brew --prefix openssl@3.0)
```

I read somewhere that `rvm` has a requirement of openssl > 3.0 and that there were errors starting from openssl 3.1

**Comment by arslanramay** [comment]
I confirm that @skatkov solution works fine for me on macOS Sonoma 14.5 with Intel chip.

> Ran into similar issue as well, but this solved it for me: `rvm reinstall 3.2.2 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs`

**Comment by xtrimf** [comment]
I confirm @amamrenko solution works

**Comment by martin-braun** [comment]
@pkuczynski Did this already land? Because I went into the same issue.

**Comment by a-sakr** [comment]
I am having this issue, tried all what was said in this issue, and it is not working, am on OSX 15.0.

Getting error:
Error running '__rvm_make -j10',
please read /Users/a_sakr/.rvm/log/1730394412_ruby-3.2.2/make.log

There has been an error while running make. Halting the installation.

**Comment by monfresh** [comment]
@a-sakr If you post the contents of `/Users/a_sakr/.rvm/log/1730394412_ruby-3.2.2/make.log`, people might be able to help you. Otherwise, I recommend trying a different version manager, such as ruby-install, rbenv, asdf, or mise.

Here's my [step by step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/) that might be helpful.

**Comment by manoj-plutoflume** [comment]
Sometimes, even after folloowing the above steps, the command `rvm install 3.1.5` goes back to openssl@1.1, the following steps worked for me. This is for ruby version 3.1.5

`
brew install openssl@3

export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig"

rvm autolibs disable
rvm reinstall 3.1.5 --with-openssl-dir=$(brew --prefix openssl@3)
`
