### ISSUE TITLE
Ruby Installation failed (__rvm_make -j12)

### ISSUE THREAD

**Issue by hamidiqbal598** [rvm/rvm#5379]
Whenever I tried to install Ruby with RVM it creates an issue.

ruby-2.7.4 - #compiling.............................................................................................................................................................................................................................................................................
Error running '__rvm_make -j12',
please read /Users/h_iqbal/.rvm/log/1691057288_ruby-2.7.4/make.log

There has been an error while running make. Halting the installation.

It's not even specific with 2.7.4, I tried with every other stable version as well but failed

![Screenshot 2023-08-03 at 12 12 23](https://github.com/rvm/rvm/assets/40686683/dc924955-b616-4a95-adb6-0b84b980dcfc)

**Comment by wangjianpeng** [comment]
I have similar problem and solve it from this post [reinstall](https://github.com/rvm/rvm/issues/5240) , you can try it with the latest  respoonse.

**Comment by hamidiqbal598** [comment]
I tried to use this command 

rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml)  --disable-dtrace --disable-docs

It works for 3.2.0 version but unfortunately not for other versions like 3.0.0

**Comment by thbar** [comment]
I meet the same problem while installing Ruby 3.2.2 but only (I believe) on a Mac M1 (ARM chip).

Are you also using M1/M2 chips?

**Comment by thbar** [comment]
I figured out how to solve this on my side: the default RVM ruby was `jruby 9.3.8.0`. Moving to `ruby-3.0.4` then installing `ruby-3.2.2` worked out fine. I figured this out thanks to the logs which mentioned:

```
current path: /home/worker/.rvm/src/ruby-3.2.2
GEM_PATH=/home/worker/.rvm/gems/jruby-9.3.8.0:/home/worker/.rvm/gems/jruby-9.3.8.0@global
GEM_HOME=/home/worker/.rvm/gems/jruby-9.3.8.0
```

Unsure if this is the culprit, but in case this helps someone else :smile:

**Comment by r-a-o** [comment]
This is so weird, installing `rvm install "ruby-3.0.4"` and then `rvm install "ruby-3.2.2"` worked for me too!

(running M1 mbp)

Thanks, @thbar!

**Comment by alex91ckua** [comment]
> I tried to use this command
> 
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
> 
> It works for 3.2.0 version but unfortunately not for other versions like 3.0.0

works fine with version 3.2.2 too on apple silicon

**Comment by amed-salazar-skydropx** [comment]
> I tried to use this command
> 
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
> 
> It works for 3.2.0 version but unfortunately not for other versions like 3.0.0

Work fine with version 3.2.2 too on macOS Monterey MacBook Pro m1 👍

**Comment by wangv5918** [comment]
> I tried to use this command我尝试使用这个命令
> 
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docsrvm重新安装3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --前缀 libyaml) --disable-dtrace --disable-docs
> 
> It works for 3.2.0 version but unfortunately not for other versions like 3.0.0它适用于 3.2.0 版本，但不幸的是不适用于 3.0.0 等其他版本

thans , it is very good!

**Comment by htthecool** [comment]
on macos (Sonoma 14.1.2) with M1, this command works:
`rvm install 3.1.4 --with-openssl-dir=$(brew --prefix openssl)`
(I use brew for dependency management, if you use something else then replace the openssl dir accordingly)

**Comment by willianeckstein** [comment]
on macos (Sonoma 14.0) with M2, this was what works for me:
arch -arm64 rvm install 3.2.2 --with-openssl-dir=$(brew --prefix openssl)

**Comment by mikgn** [comment]
Air M1, Big Sur 11.6
The only solution for me was to run the following command using the **default** terminal
`rvm install 3.1.2 --autolibs=disable`

**Comment by htthecool** [comment]
On macos (Sonoma 14.1.2) with M1 - to install ruby `2.6.10`, i had to remove openssl@3
`brew uninstall --ignore-dependencies openssl@3`
 and then run the following command:
`RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/etc/openssl@1.1 rvm install 2.6.10`

**Comment by sebasdeldi** [comment]
> `rvm install 3.1.4 --with-openssl-dir=$(brew --prefix openssl)`

Works for 3.3.0 on M1

**Comment by SowmyaFyle** [comment]
> I tried to use this command
> 
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
> 
> It works for 3.2.0 version but unfortunately not for other versions like 3.0.0

Thank you :) This was the only fix that worked after hours of googling

**Comment by arthurduarte1** [comment]
> I tried to use this command
> 
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
> 
> It works for 3.2.0 version but unfortunately not for other versions like 3.0.0

Worked for me on MacBook Air M2 Sonoma 14.2.
Using RVM with ruby 3.2.2.

**Comment by Rustamxon7** [comment]
> RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/etc/openssl@1.1 rvm install 2.6.10

This worked for me to install 3.0.1

**Comment by hamax97** [comment]
> I tried to use this command
> 
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
> 
> It works for 3.2.0 version but unfortunately not for other versions like 3.0.0

Only running this worked for me!

`rvm reinstall 3.2.2 --with-openssl-dir=$(brew --prefix openssl)`

I'm in an Apple M1 Pro.

**Comment by blulady** [comment]
using rvm to install ruby

`rvm install 3.3.0`

 * gets around `Error running '__rvm_make -j16',`

**Comment by RubyBlade** [comment]
> On macos (Sonoma 14.1.2) with M1 - to install ruby `2.6.10`, i had to remove openssl@3 `brew uninstall --ignore-dependencies openssl@3` and then run the following command: `RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/etc/openssl@1.1 rvm install 2.6.10`

The only option that worked for versions lower than 3.0 (M2 air Sanoma 14.1.2), thanks!

**Comment by InvaQ** [comment]
> on macos (Sonoma 14.1.2) with M1, this command works: `rvm install 3.1.4 --with-openssl-dir=$(brew --prefix openssl)` (I use brew for dependency management, if you use something else then replace the openssl dir accordingly)

`rvm install 3.3.0 --with-openssl-dir=$(brew --prefix openssl)` works on macOS Intel chip

**Comment by mikgn** [comment]
Air M1, Big Sur 11.6
The only solution for me was to run the following command using the default terminal
rvm install 3.3.0 --autolibs=disable

**Comment by mikgn** [comment]
Air M1, Big Sur 11.6
The only solution for me was to run the following command using the default terminal
`rvm install 3.3.0 --autolibs=disable`

**Comment by jeremylynch** [comment]
The below works great on Ruby 3.3.0 on M1: 

```
rvm install 3.3.0 --with-openssl-dir=$(brew --prefix openssl)
```

**Comment by danielfsokol** [comment]
> I tried to use this command
> 
> rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
> 
> It works for 3.2.0 version but unfortunately not for other versions like 3.0.0

Works for 3.2.3 on m3 mac

**Comment by muhammadyana** [comment]
I'm facing the same issue when installing `ruby-2.6.3` I've tried using `rvm install 2.6.3 --with-openssl-dir=$(brew --prefix openssl@1.0)` and still return the error `Error running '__rvm_make -j8'`. But it works for ruby 3.0.3 & 3.1.0. 
Anyone has a solution for ruby 2.x.x version?
I'm using mac M2 with macOS Sonoma 14.3.1

**Comment by monfresh** [comment]
@muhammadyana Try it with Ruby 2.6.10. There is rarely a good reason to use a Ruby version where the patch version (the 3rd digit) is not the latest one. In the Ruby 2.6.x series, the latest version is 2.6.10. This is a very important concept to understand when working with Ruby.

This is especially true on Apple Silicon (like your M2 Mac), where versions older than 2.6.8 are not supported out of the box.

Here's a detailed guide I wrote that explains [how and why to upgrade the Ruby version in your project](/how-to-upgrade-the-ruby-version-in-your-project), including a step-by-step guide at the end.

**Comment by nivvyart** [comment]
> > On macos (Sonoma 14.1.2) with M1 - to install ruby `2.6.10`, i had to remove openssl@3 `brew uninstall --ignore-dependencies openssl@3` and then run the following command: `RUBY_CONFIGURE_OPTS=--with-openssl-dir=/opt/homebrew/etc/openssl@1.1 rvm install 2.6.10`
> 
> The only option that worked for versions lower than 3.0 (M2 air Sanoma 14.1.2), thanks!

this worked for me for installing 2.7.3

**Comment by yashka713** [comment]
>  rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs

Works for `3.3.0` version, for M1/M2 Mac with `__rvm_make -j10` error

**Comment by alifja** [comment]
> The below works great on Ruby 3.3.0 on M1:
> 
> ```
> rvm install 3.3.0 --with-openssl-dir=$(brew --prefix openssl)
> ```

Works fine for m3 pro

**Comment by LuigiR0jas** [comment]
> The below works great on Ruby 3.3.0 on M1:
> 
> ```
> rvm install 3.3.0 --with-openssl-dir=$(brew --prefix openssl)
> ```

This worked for 3.3.1 in M2

**Comment by demko-a** [comment]
it helps me to install ruby: My global ruby version was 2.6.10, i changed it with `rbenv`

`rbenv install 3.0.3`
`rbenv global 3.0.3`
`rvm implode` (to remove rvm)
then
`rvm install ruby-3.0.3 --with-openssl-dir=$(brew --prefix openssl@1.1)`
