### ISSUE TITLE
Error running '__rvm_make install'

### ISSUE THREAD

**Issue by Snugi** [rvm/rvm#5393]
**## System**

Rocky Linux 9.2
rvm Version: 1.29.12

**## Description**

Während der inbetriebnahme einer einzelplatz RVM-Umgebung erhalte ich folgende Fehlermeldung:
Error running '__rvm_make install',
please read /home/devMGU/.rvm/log/1695799082_ruby-3.2.2/install.log
There has been an error while running make install. Halting the installation.

**##Steps to reproduce**

I have tried the following steps several times and have always run into the same error:

- [ ] sudo dnf -y install tar
- [ ] sudo dnf install gnupg
- [ ] sudo gpg2 --receive-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
- [ ] \curl -sSL https://get.rvm.io/ | bash -s stable
- [ ] \curl -sSL https://get.rvm.io/ | bash -s -- --ignore-dotfiles
- [ ] source /home/devMGU/.rvm/scripts/rvm
- [ ] Neuanmelden
- [ ] rvm -v
- [ ] echo "source $HOME/.rvm/scripts/rvm" >> ~/.bash_profile
- [ ] nano .bash_profile
- [ ] source ~/.rvm/scripts/rvm
- [ ] type rvm | head -n 1
- [ ] rvm install 3.2

**## Expected behavior**

No faults

**## Actual behavior**

Brings an error when installing Ruby-3.2.2.

**##Reinstall with --debug**

 ~]$ rvm reinstall 3.2 --debug
3.2 - reinstall
Log prefix: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/
Log filesystem: xfs
Log max name length: 250
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/remove.src.log
[2023-09-27 10:06:55] __rvm_rm_rf
__rvm_rm_rf () 
{ 
    __rvm_rm_rf_verbose "$@"
}
current path: /home/devMGU
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(2): __rvm_rm_rf /home/devMGU/.rvm/src/ruby-3.2.2
ruby-3.2.2 - #removing src/ruby-3.2.2..
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/remove.rubies.log
[2023-09-27 10:06:56] __rvm_rm_rf
__rvm_rm_rf () 
{ 
    __rvm_rm_rf_verbose "$@"
}
current path: /home/devMGU
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(2): __rvm_rm_rf /home/devMGU/.rvm/rubies/ruby-3.2.2
ruby-3.2.2 - #removing rubies/ruby-3.2.2..
ruby-3.2.2 - #already removed src/ruby-3.2.2
ruby-3.2.2 - #already removed rubies/ruby-3.2.2
Searching for binary rubies, this might take some time.
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rvm_io.global.ssl.fastly.net/binaries/centos/9/x86_64/ruby-3.2.2.tar.bz2 --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/centos/9/x86_64/ruby-3.2.2.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-3.2.2.tar.bz2 --insecure
Remote file does not exist https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-3.2.2.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/centos/9/x86_64/ruby-3.2.2.tar.bz2 --insecure
Remote file does not exist https://rubies.travis-ci.org/centos/9/x86_64/ruby-3.2.2.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rvm_io.global.ssl.fastly.net/binaries/centos/9/x86_64/ruby-3.2.2.tar.bz2 --insecure
Remote file does not exist https://rvm_io.global.ssl.fastly.net/binaries/centos/9/x86_64/ruby-3.2.2.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-3.2.2.tar.bz2 --insecure
Remote file does not exist https://repo1.maven.org/maven2/org/jruby/jruby-dist/ruby-3.2.2.tar.bz2
Running(16): curl --fail --location --max-redirs 10 --max-time 1800 --silent --insecure --location --list-only --max-time 5 --head https://rubies.travis-ci.org/centos/9/x86_64/ruby-3.2.2.tar.bz2 --insecure
Remote file does not exist https://rubies.travis-ci.org/centos/9/x86_64/ruby-3.2.2.tar.bz2
rvm_remote_server_url3 not found
No remote file name found
No binary rubies available for: centos/9/x86_64/ruby-3.2.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Free disk space 33013MB, required 440MB.
__rvm_setup_compile_environment_setup ruby-3.2.2
rvm_autolibs_flag=4
__rvm_setup_compile_environment_movable_early ruby-3.2.2
__rvm_setup_compile_environment_system_early ruby-3.2.2
__rvm_setup_compile_environment_requirements ruby-3.2.2
Checking requirements for centos.
requirements code for centos loaded
Found required packages: bash, curl, patch, autoconf, automake, bison, bzip2, gcc-c++, libffi-devel, libtool, make, patch, readline, readline-devel, ruby, sqlite-devel, zlib, zlib-devel, glibc-headers, glibc-devel, openssl-devel.
Requirements installation successful.
__rvm_setup_compile_environment_movable ruby-3.2.2
__rvm_setup_compile_environment_parse_name ruby-3.2.2
__rvm_setup_compile_environment_system ruby-3.2.2
__rvm_setup_compile_environment_architectures ruby-3.2.2
rvm_architectures(0):.
__rvm_setup_compile_environment_gcc47plus ruby-3.2.2
__rvm_setup_compile_environment_bison ruby-3.2.2
__rvm_setup_compile_environment_flags_docs ruby-3.2.2
__rvm_setup_compile_environment_flags_shared_static ruby-3.2.2
__rvm_setup_compile_environment_flags_threads ruby-3.2.2
__rvm_setup_compile_environment_compatibility_flag ruby-3.2.2
found compiler: /usr/bin/gcc
Installing Ruby from source to: /home/devMGU/.rvm/rubies/ruby-3.2.2, this may take a while depending on your cpu(s)...
ruby-3.2.2 - #downloading ruby-3.2.2, this may take a while depending on your connection...
Load checksums for https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz
Searching checksum config files for https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz
Searching checksum config files for ruby-3.2.2.tar.gz
Fetch https://cache.ruby-lang.org/pub/ruby/3.2/ruby-3.2.2.tar.gz => ruby-3.2.2.tar.gz
Validating checksums for file /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz
    ...checksums found in db
Validating md5 checksum
Calculate md5 checksum for /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz
    ...md5 checksum is valid!
Validating sha15 checksum
Calculate sha512 checksum for 512 /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz
    ...sha512 checksum is valid!
    ...archive checksum matched, not downloading
Validating checksums for file /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz
    ...checksums found in db
Validating md5 checksum
Calculate md5 checksum for /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz
    ...md5 checksum is valid!
Validating sha15 checksum
Calculate sha512 checksum for 512 /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz
    ...sha512 checksum is valid!
Downloaded archive checksum matched.
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/extract.log
[2023-09-27 10:07:00] __rvm_package_extract
__rvm_package_extract () 
{ 
    rvm_debug __rvm_package_extract:$#: "$@";
    \typeset __extract_src __extract_target __tempdir __path __file __return;
    __extract_src="$1";
    __extract_target="$2";
    shift 2;
    __return=0;
    __tempdir="$( TMPDIR="${rvm_tmp_path}" mktemp -d -t rvm-tmp.XXXXXXXXX )";
    __rvm_package_extract_run "$__extract_src" "$__tempdir" "$@" || __return=$?;
    if (( __return == 0 )); then
        for __path in "$__tempdir"/*;
        do
            __file="${__path##*/}";
            if [[ -n "${__file}" && -e "$__extract_target/${__file}" ]]; then
                \command \rm -rf "$__extract_target/${__file}" || __return=$?;
            fi;
            \command \mv -f "${__path}" "$__extract_target/" || __return=$?;
        done;
    fi;
    if [[ -n "$__tempdir" ]]; then
        \command \rm -rf "$__tempdir";
    fi;
    return $__return
}
current path: /home/devMGU/.rvm/src
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(3): __rvm_package_extract /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz /home/devMGU/.rvm/tmp/rvm_src_87303
__rvm_package_extract:2: /home/devMGU/.rvm/archives/ruby-3.2.2.tar.gz /home/devMGU/.rvm/tmp/rvm_src_87303
ruby-3.2.2 - #extracting ruby-3.2.2 to /home/devMGU/.rvm/src/ruby-3.2.2......
__rvm_rm_rf already gone: /home/devMGU/.rvm/src/ruby-3.2.2
Patch name 'optional', expanded_name(s) ''.
Patch name 'default', expanded_name(s) ''.
Patch name 'centos', expanded_name(s) ''.
All found patches(0): .
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/autogen.sh.log
[2023-09-27 10:07:00] /home/devMGU/.rvm/src/ruby-3.2.2/autogen.sh
current path: /home/devMGU/.rvm/src/ruby-3.2.2
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(1): /home/devMGU/.rvm/src/ruby-3.2.2/autogen.sh
ruby-3.2.2 - #autogen.sh.
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/configure.log
[2023-09-27 10:07:01] ./configure
current path: /home/devMGU/.rvm/src/ruby-3.2.2
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(4): ./configure --prefix=/home/devMGU/.rvm/rubies/ruby-3.2.2 --disable-install-doc --enable-shared
ruby-3.2.2 - #configuring.............................................................................
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/postconfigure.log
[2023-09-27 10:07:21] __rvm_post_configure_ruby
__rvm_post_configure_ruby () 
{ 
    __rvm_post_configure_ruby_fix_athlon_sse2;
    __rvm_post_configure_ruby_update_setup
}
current path: /home/devMGU/.rvm/src/ruby-3.2.2
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(1): __rvm_post_configure_ruby
ruby-3.2.2 - #post-configuration..
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/make.log
[2023-09-27 10:07:21] __rvm_make
__rvm_make () 
{ 
    \make "$@" || return $?
}
current path: /home/devMGU/.rvm/src/ruby-3.2.2
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(2): __rvm_make -j3
ruby-3.2.2 - #compiling...............................................................................................................................
__rvm_rm_rf already gone: /home/devMGU/.rvm/src/ruby-3.2.2/.ext/rdoc
Log file: /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/install.log
[2023-09-27 10:08:43] __rvm_make
__rvm_make () 
{ 
    \make "$@" || return $?
}
current path: /home/devMGU/.rvm/src/ruby-3.2.2
PATH=/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin
command(2): __rvm_make install
ruby-3.2.2 - #installing................
Error running '__rvm_make install',
please read /home/devMGU/.rvm/log/1695802015_ruby-3.2.2/install.log
There has been an error while running make install. Halting the installation.
__rvm_rm_rf already gone: /home/devMGU/.rvm/tmp/87303*

**## make.log Content**

See the Attachment.

**## Environment info**

system:

  system:
    uname:        "Linux templateFRP 5.14.0-284.11.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Tue May 9 17:09:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux"
    name:         "CentOS"
    version:      "9"
    architecture: "x86_64"
    bash:         "/usr/bin/bash => GNU bash, version 5.1.8(1)-release (x86_64-redhat-linux-gnu)"
    zsh:          " => not installed"
    remote_path:  "centos/9/x86_64"

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "12 hours 7 minutes 5 seconds ago"
    path:         "/home/devMGU/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          ""
    gem:          "/usr/bin/gem"
    rake:         ""

  environment:
    PATH:         "/home/devMGU/.local/bin:/home/devMGU/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/devMGU/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
[make.log](https://github.com/rvm/rvm/files/12736317/make.log)

**Comment by Snugi** [comment]
**In the make.log file, I have found a problem. The following lines I think are the problem:**
```
[33;1m*** Following extensions are not compiled:[m
[31;1mpsych:[m
	Could not be configured. It will not be installed.
	Check ext/psych/mkmf.log for more details.
[33;1m*** Fix the problems, then remove these directories and try again if you want.[m
```


**I opened the mkmf.log. I found them with the find command:**
`find /home/devMGU/.rvm/ -name mkmf.log`


**The full path of this file are:**
`/home/devMGU/.rvm/src/ruby-3.2.2/ext/psych/mkmf.log`


**The Content of this file is:**
```
LD_LIBRARY_PATH=.:../.. pkg-config --exists yaml-0.1
package configuration for yaml-0.1 is not found
find_header: checking for yaml.h... -------------------- no

LD_LIBRARY_PATH=.:../.. "gcc -o conftest -I../../.ext/include/x86_64-linux -I../.././include -I../.././ext/psych    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdiv-by-zero -Wduplicat>
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5:   return !!argv[argc];
6: }
/* end */

LD_LIBRARY_PATH=.:../.. "gcc -I../../.ext/include/x86_64-linux -I../.././include -I../.././ext/psych    -O3 -fno-fast-math -ggdb3 -Wall -Wextra -Wdeprecated-declarations -Wdiv-by-zero -Wduplicated-cond -Wim>
conftest.c:3:10: fatal error: yaml.h: No such file or directory
    3 | #include <yaml.h>
      |          ^~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <yaml.h>
/* end */

--------------------
```

**Comment by Snugi** [comment]
**Solution!**

**Attention**
I have a user specify installation.

**The error message i become in the installation:**
`Error running '__rvm_make install' ...`

The solution of the Problems are the following steps.
**Install or enable the crb as root:**
`dnf config-manager --set-enable crb`

**Then run the following commands by the sudo user you use to install the ruby environment:**
`sudo dnf install -y libyaml-devel-0.2.5-7.el9.x86_64`

**Then you can reinstall the ruby-3.2.2**
`rvm reinstall 3.2.2`

**That is my output after the installation:**
``` ruby-3.2.2 - #removing src/ruby-3.2.2..
ruby-3.2.2 - #removing rubies/ruby-3.2.2..
Searching for binary rubies, this might take some time.
No binary rubies available for: centos/9/x86_64/ruby-3.2.2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for centos.
Requirements installation successful.
Installing Ruby from source to: /home/devMGU/.rvm/rubies/ruby-3.2.2, this may take a while depending on your cpu(s)...
ruby-3.2.2 - #downloading ruby-3.2.2, this may take a while depending on your connection...
ruby-3.2.2 - #extracting ruby-3.2.2 to /home/devMGU/.rvm/src/ruby-3.2.2.....
ruby-3.2.2 - #configuring..................................................................
ruby-3.2.2 - #post-configuration..
ruby-3.2.2 - #compiling...............................................................................................................................
ruby-3.2.2 - #installing......................
ruby-3.2.2 - #making binaries executable...
Installed rubygems 3.4.10 is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
ruby-3.2.2 - #gemset created /home/devMGU/.rvm/gems/ruby-3.2.2@global
ruby-3.2.2 - #importing gemset /home/devMGU/.rvm/gemsets/global.gems..........................................................
ruby-3.2.2 - #generating global wrappers........
ruby-3.2.2 - #gemset created /home/devMGU/.rvm/gems/ruby-3.2.2
ruby-3.2.2 - #importing gemsetfile /home/devMGU/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-3.2.2 - #generating default wrappers........
ruby-3.2.2 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-3.2.2 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri
Making gemset ruby-3.2.2 pristine...................................................................
Making gemset ruby-3.2.2@global pristine....................................................................```

**Complete!**

**Comment by AndrewAlva** [comment]
It also works for ruby 3.1.0 on Mac OS 13  Ventura, M2 chip 

`rvm install 3.1.0 --with-openssl-dir=$(brew --prefix openssl)`

**Comment by monfresh** [comment]
For those of you trying to install Ruby 2.6.x versions older than 2.6.10, the best solution is to update your project to 2.6.10. There is rarely a good reason to use a Ruby version where the patch version (the 3rd digit) is not the latest one. In the Ruby 2.6.x series, the latest version is 2.6.10. This is a very important concept to understand when working with Ruby.

This is especially true on Apple Silicon, where versions older than 2.6.8 are not supported out of the box.

Here's a detailed guide I wrote that explains [how and why to upgrade the Ruby version in your project](https://www.rubyonmac.dev/how-to-upgrade-the-ruby-version-in-your-project), including a step-by-step guide at the end.

**Comment by Snugi** [comment]
@monfresh 
No, it's not the same error. My error is:
Error running '__rvm_make **install',**

And your error is:
Error running '__rvm_make **-j8'**

I think you can identify that's not the same error.
The difference is at the end of the line.
Your end:
**-j8**
My end:
**install**

**Comment by yashka713** [comment]
> It also works for ruby 3.1.0 on Mac OS 13 Ventura, M2 chip
> 
> `rvm install 3.1.0 --with-openssl-dir=$(brew --prefix openssl)`

Worked for me with `3.3.3` on Macbook M1 Pro

**Comment by dev1KING** [comment]
my error was -j10 took the first step like this:

1 rvm install 3.3.3 --with-openssl-dir=$(brew --prefix openssl) and then 

2  rvm install 3.4.2 --with-openssl-dir=$(brew --prefix openssl)
