### ISSUE TITLE
I cant install ruby-3.0.1 on rvm

### ISSUE THREAD

**Issue by WormerKing** [rvm/rvm#5397]
First of all, good work to everyone. I am trying to install ruby-3.0.1 on Endeavor OS using rvm, but I get an error like this:
`
Searching for binary rubies, this might take some time.
No binary rubies available for: arch/libc-2.38/x86_64/ruby-3.0.1.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for arch.
Requirements installation successful.
Installing Ruby from source to: /home/user/.rvm/rubies/ruby-3.0.1, this may take a while depending on your cpu(s)...
ruby-3.0.1 - #downloading ruby-3.0.1, this may take a while depending on your connection...
ruby-3.0.1 - #extracting ruby-3.0.1 to /home/user/.rvm/src/ruby-3.0.1.....
ruby-3.0.1 - #configuring.........................................................................
ruby-3.0.1 - #post-configuration..
ruby-3.0.1 - #compiling.....................................................................................................................................|
Error running '__rvm_make -j12',
please read /home/user/.rvm/log/1697130632_ruby-3.0.1/make.log

There has been an error while running make. Halting the installation.
`
Log file:
[make.log](https://github.com/rvm/rvm/files/12885537/make.log)
Thanks from now.

**Comment by monfresh** [comment]
I agree with Mathieu. In general, it's best to use the latest patch version for any given release. [endoflife.date](https://endoflife.date/ruby) is a handy site for finding the latest versions of each Ruby release.

I also wrote a detailed guide explaining why it's important to update the Ruby version in your Ruby projects, and how to do it, step by step:

https://www.rubyonmac.dev/how-to-upgrade-the-ruby-version-in-your-project

**Comment by WormerKing** [comment]
Thank you both very much. I updated the ruby version of my project and solved the problem. Good days.

**Comment by fouuuadi** [comment]
> don't bother with 3.0.1, install 3.0.6 or later instead

Thx !
