### ISSUE TITLE
Can't instal Ruby 3.2.2 or 3.3.0-preview2

### ISSUE THREAD

**Issue by jzakiya** [rvm/rvm#5400]
My Linux OS in PCLinuxOS, on a System76, i7 based laptop.
I have installed truffleruby-23.1.0 and jruby-9.4.3.0.

Here is error message:

```
➜  ~ rvm install ruby-3.3.0-preview2
Warning! PATH is not properly set up, /home/jzakiya/.rvm/gems/truffleruby-23.1.0/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use truffleruby-23.1.0
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
ruby-3.3.0-preview2 - #removing src/ruby-3.3.0-preview2 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: pclinuxos/2023/x86_64/ruby-3.3.0-preview2.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for pclinuxos.
Requirements installation successful.
Installing Ruby from source to: /home/jzakiya/.rvm/rubies/ruby-3.3.0-preview2, this may take a while depending on your cpu(s)...
ruby-3.3.0-preview2 - #downloading ruby-3.3.0-preview2, this may take a while depending on your connection...
ruby-3.3.0-preview2 - #extracting ruby-3.3.0-preview2 to /home/jzakiya/.rvm/src/ruby-3.3.0-preview2 - please wait
ruby-3.3.0-preview2 - #autogen.sh - please wait
ruby-3.3.0-preview2 - #configuring - please wait
ruby-3.3.0-preview2 - #post-configuration - please wait
ruby-3.3.0-preview2 - #compiling - please wait
Error running '__rvm_make -j8',
please read /home/jzakiya/.rvm/log/1697675987_ruby-3.3.0-preview2/make.log

There has been an error while running make. Halting the installation.


```

**Comment by coaxial** [comment]
Same here, even after `rvm get head`. This is the `ruby_strings` contents (3.2 is not in there):

```
            "ironruby-1.0",
            "ironruby-1.1.3",
            "jruby-0.9.0",
            "jruby-0.9.1",
            "jruby-0.9.2",
            "jruby-0.9.8",
            "jruby-0.9.9",
            "jruby-1.0.0RC1",
            "jruby-1.0.0RC2",
            "jruby-1.0.0RC3",
            "jruby-1.0",
            "jruby-1.0.1",
            "jruby-1.0.2",
            "jruby-1.0.3",
            "jruby-1.1b1",
            "jruby-1.1RC1",
            "jruby-1.1RC2",
            "jruby-1.1RC3",
            "jruby-1.1",
            "jruby-1.1.1",
            "jruby-1.1.2",
            "jruby-1.1.3",
            "jruby-1.1.4",
            "jruby-1.1.5",
            "jruby-1.1.6RC1",
            "jruby-1.1.6",
            "jruby-1.2.0RC1",
            "jruby-1.2.0RC2",
            "jruby-1.2.0",
            "jruby-1.3.0RC1",
            "jruby-1.3.0RC2",
            "jruby-1.3.0",
            "jruby-1.3.1",
            "jruby-1.4.0RC1",
            "jruby-1.4.0RC2",
            "jruby-1.4.0RC3",
            "jruby-1.4.0",
            "jruby-1.4.1",
            "jruby-1.5.0.RC1",
            "jruby-1.5.0.RC2",
            "jruby-1.5.0.RC3",
            "jruby-1.5.0",
            "jruby-1.5.1",
            "jruby-1.5.2",
            "jruby-1.5.3",
            "jruby-1.5.4",
            "jruby-1.5.5",
            "jruby-1.5.6",
            "jruby-1.6.0.RC1",
            "jruby-1.6.0.RC2",
            "jruby-1.6.0.RC3",
            "jruby-1.6.0",
            "jruby-1.6.1",
            "jruby-1.6.2",
            "jruby-1.6.3",
            "jruby-1.6.4",
            "jruby-1.6.5",
            "jruby-1.6.5.1",
            "jruby-1.6.7",
            "jruby-1.6.7.2",
            "jruby-1.6.8",
            "jruby-1.7.0.preview1",
            "jruby-1.7.0.preview2",
            "jruby-1.7.0.RC1",
            "jruby-1.7.0.RC2",
            "jruby-1.7.0",
            "jruby-1.7.1",
            "jruby-1.7.2",
            "jruby-1.7.3",
            "jruby-1.7.4",
            "jruby-1.7.5",
            "jruby-1.7.6",
            "jruby-1.7.7",
            "jruby-1.7.8",
            "jruby-1.7.9",
            "jruby-1.7.10",
            "jruby-1.7.11",
            "jruby-1.7.12",
            "jruby-1.7.13",
            "jruby-1.7.14",
            "jruby-1.7.15",
            "jruby-1.7.16",
            "jruby-1.7.16.1",
            "jruby-1.7.16.2",
            "jruby-1.7.17",
            "jruby-1.7.18",
            "jruby-1.7.19",
            "jruby-1.7.20",
            "jruby-1.7.20.1",
            "jruby-1.7.21",
            "jruby-1.7.22",
            "jruby-1.7.23",
            "jruby-1.7.24",
            "jruby-1.7.25",
            "jruby-1.7.26",
            "jruby-1.7.27",
            "jruby-9.0.0.0.pre1",
            "jruby-9.0.0.0.pre2",
            "jruby-9.0.0.0.rc1",
            "jruby-9.0.0.0.rc2",
            "jruby-9.0.0.0",
            "jruby-9.0.1.0",
            "jruby-9.0.2.0",
            "jruby-9.0.3.0",
            "jruby-9.0.4.0",
            "jruby-9.0.5.0",
            "jruby-9.1.0.0",
            "jruby-9.1.1.0",
            "jruby-9.1.2.0",
            "jruby-9.1.3.0",
            "jruby-9.1.4.0",
            "jruby-9.1.5.0",
            "jruby-9.1.6.0",
            "jruby-9.1.7.0",
            "jruby-9.1.8.0",
            "jruby-9.1.9.0",
            "jruby-9.1.10.0",
            "jruby-9.1.11.0",
            "jruby-9.1.12.0",
            "jruby-9.1.13.0",
            "jruby-9.1.14.0",
            "jruby-9.1.15.0",
            "ruby-2.6.0-preview3",
            "ruby-2.6.0-rc1",
            "ruby-2.6.0-rc2",
            "ruby-2.6.0",
            "ruby-2.6.1",
            "ruby-2.6.2",
            "ruby-2.6.3",
            "ruby-2.6.4",
            "ruby-2.6.5",
            "ruby-2.6.6",
            "ruby-2.7.0-preview1",
            "ruby-2.7.0-preview2",
            "ruby-2.7.0-preview3",
            "ruby-2.7.0-rc1",
            "ruby-2.7.0-rc2",
            "ruby-2.7.0",
            "ruby-2.7.1",
            "ruby-2.7.2",
            "ruby-3.0.0-preview1",
            "ruby-3.0.0-preview2",
            "ruby-3.0.0-rc1",
            "ruby-3.0.0",
            "truffleruby-1.0.0-rc2",
            "truffleruby-1.0.0-rc3",
            "truffleruby-1.0.0-rc5",
            "truffleruby-1.0.0-rc6",
            "truffleruby-1.0.0-rc7",
            "truffleruby-1.0.0-rc8",
            "truffleruby-1.0.0-rc9",
            "truffleruby-1.0.0-rc10",
            "truffleruby-1.0.0-rc11",
            "truffleruby-1.0.0-rc12",
            "truffleruby-1.0.0-rc13",
            "truffleruby-1.0.0-rc14",
            "truffleruby-1.0.0-rc15",
            "truffleruby-1.0.0-rc16",
            "truffleruby-19.0.0",
            "truffleruby-19.0.2",
            "truffleruby-19.1.0",
            "truffleruby-19.1.1",
            "truffleruby-19.2.0",
            "truffleruby-19.2.0.1",
            "truffleruby-19.2.1",
            "truffleruby-19.3.0",
            "truffleruby-19.3.0.2",
            "truffleruby-19.3.1",
            "truffleruby-20.0.0",
            "truffleruby-20.1.0",
            "truffleruby-20.2.0",
            "truffleruby-20.3.0"
```

**Comment by mathieujobin** [comment]
`rvm get master` instead of `rvm get head` maybe?

**Comment by jzakiya** [comment]
Nope, that didn't work.

**Comment by daprezjer** [comment]
@jzakiya were you able to get this to work? I'm having the same problem trying to install ruby 3.3.0 on OS Sonoma, latest Xcode installed.

```
rvm get master
rvm get head
rvm install 3.3.0

rvm install 3.3.0
Warning! PATH is not properly set up, xxxxx/gems/ruby-3.0.0/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-3.0.0
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/14.2/arm64/ruby-3.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/jeremy/.rvm/rubies/ruby-3.3.0, this may take a while depending on your cpu(s)...
ruby-3.3.0 - #downloading ruby-3.3.0, this may take a while depending on your connection...
ruby-3.3.0 - #extracting ruby-3.3.0 to /Users/jeremy/.rvm/src/ruby-3.3.0.....
ruby-3.3.0 - #autogen.sh.
ruby-3.3.0 - #configuring....................................................................
ruby-3.3.0 - #post-configuration.
ruby-3.3.0 - #compiling......................................................................................
Error running '__rvm_make -j10',
please read /Users/jeremy/.rvm/log/1705532668_ruby-3.3.0/make.log
```

I've tried the various suggestions there as well.

**Comment by jzakiya** [comment]
No, it still does not work. :-(

**Comment by daprezjer** [comment]
@jzakiya this ended up working for me on advice from a colleague.

rvm reinstall 3.3.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs

**Comment by monfresh** [comment]
There are many factors that can affect Ruby installation on a Mac. The solution depends on the exact state of your development setup. This is why a solution that works for one person might not work for someone else. 

If none of the solutions posted here have worked for you, here are other things you can try:

- Try a different Ruby version manager, such as chruby, asdf, or rbenv. I personally use and recommend chruby because it's faster and simpler.
- Completely uninstall all Ruby-related development tools, then start over from scratch. I wrote a [step-by-step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).
- If you value your time and want to be up and running in 15 minutes or less, buy my [Ruby on Mac](https://www.rubyonmac.dev/) product. The Ultimate version works with all the popular version managers (asdf, chruby, frum, rbenv, rvm). The creator of RVM is a happy customer and he considers it a serious time saver: https://www.threads.net/@wayneeseguin/post/C2Nih1BOJS7

**Comment by daprezjer** [comment]
Don't know, unfortunately.

**Comment by jzakiya** [comment]
I guess Linux don't get no luv.

**Comment by coaxial** [comment]
@jzakiya From what I remember, the issue for me lately was using an outdated Mint version that was based off Ubuntu 20.04 which shipped with an old OpenSSL implementation. This conflicted with what ruby expected. Once I updated to a more up-to-date Mint version, the issues went away and I could run ruby 3.{2,3}

**Comment by markfaust123** [comment]
> @jzakiya this ended up working for me on advice from a colleague.
> 
> rvm reinstall 3.3.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs

God bless.

**Comment by jzakiya** [comment]
I'm using Linux, not a Mac.

**Comment by sudaraka94** [comment]
Thanks @markfaust123 your solution worked like a charm
```
rvm reinstall 3.2.2 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
```

**Comment by jzakiya** [comment]
After completely reinstalling from scratch a current version of PCLOS on this laptop, using rvm I was able to install CRuby, JRuby, and TruffleRuby with no problems, install/update gems for them, and use them.

The reason I had to reinstall it was because somehow the OS became corrupted and wouldn't boot.
Once the pristine new OS was installed, everything seems to worker better/faster.

So you can consider this issue closed.

**Comment by Moussy** [comment]
> @jzakiya this ended up working for me on advice from a colleague.
> 
> rvm reinstall 3.3.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs

I executed this code, but reported a new error:

`➜  app-vipteach-swift git:(main) ✗ rvm reinstall 3.3.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/vipkid/.rvm/rubies/ruby-3.3.0, this may take a while depending on your cpu(s)...
ruby-3.3.0 - #downloading ruby-3.3.0, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: cache.ruby-china.org
Warning: Problem : timeout. Will retry in 2 seconds. 3 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: cache.ruby-china.org
Warning: Problem : timeout. Will retry in 2 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: cache.ruby-china.org
Warning: Problem : timeout. Will retry in 2 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: cache.ruby-china.org
There was an error(6).
Checking fallback: https://ftp.ruby-lang.org/pub/ruby/3.3/ruby-3.3.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.0M  100 21.0M    0     0  5699k      0  0:00:03  0:00:03 --:--:-- 5699k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-3.3.0 - #extracting ruby-3.3.0 to /Users/vipkid/.rvm/src/ruby-3.3.0 - please wait
ruby-3.3.0 - #configuring - please wait
ruby-3.3.0 - #post-configuration - please wait
ruby-3.3.0 - #compiling - please wait
ruby-3.3.0 - #installing - please wait
ruby-3.3.0 - #making binaries executable - please wait
Installed rubygems 3.5.3 is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
ruby-3.3.0 - #gemset created /Users/vipkid/.rvm/gems/ruby-3.3.0@global
ruby-3.3.0 - #importing gemset /Users/vipkid/.rvm/gemsets/global.gems - please wait
Error running 'command gem install /Users/vipkid/.rvm/gem-cache/gem-wrappers-1.4.0.gem --local --no-document',
please read /Users/vipkid/.rvm/log/1723453206_ruby-3.3.0/gem.install.gem-wrappers->=1.4.0.log
there was an error installing gem gem-wrappers
Error running 'command gem install rubygems-bundler --no-document',
please read /Users/vipkid/.rvm/log/1723453206_ruby-3.3.0/gem.install.rubygems-bundler.log
there was an error installing gem rubygems-bundler
Error running 'command gem install /Users/vipkid/.rvm/gem-cache/rvm-1.11.3.9.gem --local --no-document',
please read /Users/vipkid/.rvm/log/1723453206_ruby-3.3.0/gem.install.rvm->=1.11.3.9.log
there was an error installing gem rvm
ruby-3.3.0 - #generating global wrappers - please wait
Error running 'command gem install /Users/vipkid/.rvm/gem-cache/gem-wrappers-1.4.0.gem --local --no-document',
please read /Users/vipkid/.rvm/log/1723453206_ruby-3.3.0/gem.install.gem-wrappers->=1.4.0.log
Error running 'run_gem_wrappers regenerate',
please read /Users/vipkid/.rvm/log/1723453206_ruby-3.3.0/gemset.wrappers.global.log
ruby-3.3.0 - #gemset created /Users/vipkid/.rvm/gems/ruby-3.3.0
ruby-3.3.0 - #importing gemsetfile /Users/vipkid/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-3.3.0 - #generating default wrappers - please wait
Error running 'command gem install /Users/vipkid/.rvm/gem-cache/gem-wrappers-1.4.0.gem --local --no-document',
please read /Users/vipkid/.rvm/log/1723453206_ruby-3.3.0/gem.install.gem-wrappers->=1.4.0.log
Error running 'run_gem_wrappers regenerate',
please read /Users/vipkid/.rvm/log/1723453206_ruby-3.3.0/gemset.wrappers.default.log
ruby-3.3.0 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-3.3.0 - #complete
Ruby was built without documentation, to build it run: rvm docs generate-ri
Making gemset ruby-3.3.0 pristine - please wait
Making gemset ruby-3.3.0@global pristine - please wait

'command gem pristine --extensions debug --version 1.9.1 racc --version 1.7.3 rbs --version 3.4.0' failed, you need to fix these gems manually.
Error running '__rvm_with ruby-3.3.0@global gemset_pristine',
please read /Users/vipkid/.rvm/log/1723453269_ruby-3.3.0/gemset.pristine-ruby-3.3.0@global.log`

[Uploading log10.txt…]()

**Comment by willmagna** [comment]
> @jzakiya this ended up working for me on advice from a colleague.
> 
> rvm reinstall 3.3.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs

**Thanks a lot!** 

Works perfectly even for newer versions like 3.3.3.

To upgrade to version 3.3.3 is just to change from:

`rvm reinstall 3.3.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs`

To

`rvm reinstall 3.3.3 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs`

**Comment by srdevang** [comment]
```rvm reinstall 3.2.0 --with-openssl-dir=$(brew --prefix openssl) --with-readline-dir=$(brew --prefix readline) --with-libyaml-dir=$(brew --prefix libyaml) --disable-dtrace --disable-docs```

This worked for me.
