### ISSUE TITLE
__rvm_make -j4

### ISSUE THREAD

**Issue by xclidongbo** [rvm/rvm#5409]
➜  ~ rvm install 3.0.0 --with-openssl-dir=`brew --prefix openssl@1.1`

ruby-3.0.0 - #removing src/ruby-3.0.0 - please wait
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/xclidongbo/.rvm/rubies/ruby-3.0.0, this may take a while depending on your cpu(s)...
ruby-3.0.0 - #downloading ruby-3.0.0, this may take a while depending on your connection...
ruby-3.0.0 - #extracting ruby-3.0.0 to /Users/xclidongbo/.rvm/src/ruby-3.0.0 - please wait
ruby-3.0.0 - #configuring - please wait
ruby-3.0.0 - #post-configuration - please wait
ruby-3.0.0 - #compiling - please wait
Error running '__rvm_make -j4',
please read /Users/xclidongbo/.rvm/log/1700293479_ruby-3.0.0/make.log

There has been an error while running make. Halting the installation.

**Comment by ArifaAbid** [comment]
brew install openssl@3
rvm install 2.7.1 --with-openssl-dir=$(brew --prefix openssl@3)

**Comment by pkuczynski** [comment]
This has been already resolved in master
