### ISSUE TITLE
Error running '__rvm_make -j8' on chip M3

### ISSUE THREAD

**Issue by devsheva** [rvm/rvm#5411]
## Description

I switched from a Macbook Pro with Intel Chip to a Macbook Pro with Apple M3 chip.  
I'm trying to install ruby 3.1.3, but i get 

`Error running '__rvm_make -j8'`

## Debug info
[make.log](https://gist.github.com/devsheva/1a13c62169f85bc24be1f9d8632964da)
## Environment info

```
system:
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  system:
    uname:        "Darwin Mateos-MBP 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:32:52 PDT 2023; root:xnu-10002.41.9~7/RELEASE_ARM64_T8122 arm64"
    name:         "OSX"
    version:      "14.1"
    architecture: "arm64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (arm64-apple-darwin23)"
    zsh:          "/bin/zsh => zsh 5.9 (x86_64-apple-darwin23.0)"
    remote_path:  "osx/14.1/arm64"
    xcode:        ""

  rvm:
    version:      "1.29.12 (latest)"
    updated:      "8 minutes 31 seconds ago"
    path:         "/Users/mateo/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/Users/mateo/.nvm/versions/node/v18.17.1/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.10/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/usr/local/bin:/Users/mateo/.rvm/bin:/Users/mateo/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""
```

**Comment by MockingMockingBird** [comment]
I am having the same issue with x86

```
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: x86_64-apple-darwin23.1.0
```

Error msg: `Error running '__rvm_make -j8',`

Log shows an error in the file ossl_pkey_rsa.c. This file is part of the OpenSSL extension for Ruby. Specific error is related to **RSA_SSLV23_PADDING**, which seems like it's an undeclared identifier in this context... Maybe a compatibility issue with the version of OpenSSL being used? I'm going to try and install an older version of OpenSSL and run installation from there.

```
/usr/local/Cellar/openssl@3/3.2.0/include/openssl/macros.h:194:49: note: expanded from macro 'OSSL_DEPRECATEDIN_3_0'
#   define OSSL_DEPRECATEDIN_3_0                OSSL_DEPRECATED(3.0)
                                                ^
/usr/local/Cellar/openssl@3/3.2.0/include/openssl/macros.h:62:52: note: expanded from macro 'OSSL_DEPRECATED'
#     define OSSL_DEPRECATED(since) __attribute__((deprecated))
                                                   ^
ossl_pkey_rsa.c:950:5: error: use of undeclared identifier 'RSA_SSLV23_PADDING'
    DefRSAConst(SSLV23_PADDING);
    ^
ossl_pkey_rsa.c:885:58: note: expanded from macro 'DefRSAConst'
#define DefRSAConst(x) rb_define_const(cRSA, #x, INT2NUM(RSA_##x))
                                                         ^
<scratch space>:142:1: note: expanded from here
RSA_SSLV23_PADDING
^
109 warnings and 1 error generated.
make[2]: *** [ossl_pkey_rsa.o] Error 1
make[2]: *** Waiting for unfinished jobs....
compiling sha1init.c
linking shared-object digest/rmd160.bundle

```

**Comment by MockingMockingBird** [comment]
So versions < Openssl 3.0.0 are so longer supported after this year (September 2023) and has been deprecated on homebrew :( 
Going to try & manually download it then update the .config to point at it...

**Comment by jdromero88** [comment]
@devsheva I had the same issue and I fixed it like this:
1- brew should already had installed by default openssl@3 check the formulaes by running `brew list` there you should see listed openssl@1.1 openssl@3
2- list to see if the folder exist (just in case) by running `ls /opt/homebrew/op`
![image](https://github.com/rvm/rvm/assets/51330062/94e023d9-50b8-4976-8d87-77c301958ec6)
3- proceed to install ruby with `rvm install 3.1.4 --with-openssl-dir=$(brew --prefix openssl@1.1)`
![image](https://github.com/rvm/rvm/assets/51330062/06011385-c052-4f55-b962-cd173dba588d)

My system info in case you are wondering
![image](https://github.com/rvm/rvm/assets/51330062/7c1d6e35-332d-40e9-9d1c-82bf418a6af2)

**Comment by devsheva** [comment]
For everyone wondering, I fixed my concern for Ruby version > 3 doing these steps

1. Go to Applications, duplicate Terminal/iTerm and name it `Terminal x86_64`
    1. Right click, Info, Click open with Rosetta
    2. Run the terminal
    3. Run `arch` command, and check is different from **arm64**
    4. [[Uninstall Homebrew](https://github.com/homebrew/install#uninstall-homebrew)](https://github.com/homebrew/install#uninstall-homebrew)
2. Open a new normal term (arch should return arm64)
    1. [[Install Homebrew](https://docs.brew.sh/Installation)](https://docs.brew.sh/Installation)
    2. Reinstall all packages with `brew list | xargs brew reinstall`
    3. Run `\curl -sSL https://get.rvm.io | bash -s stable --auto-dotfiles` to install **RVM**
    4. Go to a project folder, and try to run suggested cmd to install required ruby version
    5. If all works, then you ***gucci***

For Ruby version < 3 i ran onto this [guide](https://nickymarino.com/2021/12/17/install-ruby-273-on-m1/)

**Comment by gokulakshay** [comment]
rvm install 2.7.4 --with-openssl-dir=$(brew --prefix openssl@1.1)
ruby-2.7.4 - #removing src/ruby-2.7.4 - please wait
Checking requirements for osx.
Warning: Calling the `appcast` stanza is deprecated! Use the `livecheck` stanza instead.
Please report this issue to the adoptopenjdk/openjdk tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/adoptopenjdk/homebrew-openjdk/Casks/adoptopenjdk8.rb:9

Certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/gokulgopi/.rvm/rubies/ruby-2.7.4, this may take a while depending on your cpu(s)...
ruby-2.7.4 - #downloading ruby-2.7.4, this may take a while depending on your connection...
ruby-2.7.4 - #extracting ruby-2.7.4 to /Users/gokulgopi/.rvm/src/ruby-2.7.4 - please wait
ruby-2.7.4 - #configuring - please wait
ruby-2.7.4 - #post-configuration - please wait
ruby-2.7.4 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/gokulgopi/.rvm/log/1702666833_ruby-2.7.4/make.log

There has been an error while running make. Halting the installation.

**Comment by scott8803** [comment]
Same for M2

Similar

MBA Mac M2 Ventura 13.5.2 (22G91)

```
rvm install 3.3
Warning! PATH is not properly set up, /Users/scott/.rvm/gems/ruby-3.0.4/bin is not at first place.
         Usually this is caused by shell initialization files. Search for PATH=... entries.
         You can also re-add RVM to your profile by running: rvm get stable --auto-dotfiles
         To fix it temporarily in this shell session run: rvm use ruby-3.0.4
         To ignore this error add rvm_silence_path_mismatch_check_flag=1 to your ~/.rvmrc file.
ruby-3.3.0 - #removing src/ruby-3.3.0 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/13.5/arm64/ruby-3.3.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/scott/.rvm/rubies/ruby-3.3.0, this may take a while depending on your cpu(s)...
ruby-3.3.0 - #downloading ruby-3.3.0, this may take a while depending on your connection...
ruby-3.3.0 - #extracting ruby-3.3.0 to /Users/scott/.rvm/src/ruby-3.3.0 - please wait
ruby-3.3.0 - #autogen.sh - please wait
ruby-3.3.0 - #configuring - please wait
ruby-3.3.0 - #post-configuration - please wait
ruby-3.3.0 - #compiling - please wait
Error running '__rvm_make -j8',
please read /Users/scott/.rvm/log/1703599753_ruby-3.3.0/make.log
```

There has been an error while running make. Halting the installation.
make.log has lots of:

```
In file included from ./ossl.h:175:
./openssl_missing.h:195:11: warning: 'TS_VERIFY_CTS_set_certs' macro redefined [-Wmacro-redefined]
#  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
          ^
/opt/homebrew/Cellar/openssl@3/3.1.4/include/openssl/ts.h:426:11: note: previous definition is here
#  define TS_VERIFY_CTS_set_certs(ctx, cert) TS_VERIFY_CTX_set_certs(ctx,cert)
          ^
1 warning generated.

```
Then

```

 In file included from ./ossl.h:175:
./openssl_missing.h:195:11: warning: 'TS_VERIFY_CTS_set_certs' macro redefined [-Wmacro-redefined]
#  define TS_VERIFY_CTS_set_certs(ctx, crts) ((ctx)->certs=(crts))
          ^
/opt/homebrew/Cellar/openssl@3/3.2.0_1/include/openssl/ts.h:426:11: note: previous definition is here
#  define TS_VERIFY_CTS_set_certs(ctx, cert) TS_VERIFY_CTX_set_certs(ctx,cert)
          ^
ossl_hmac.c:249:35: error: incomplete definition of type 'struct evp_md_ctx_st'
    pkey = EVP_PKEY_CTX_get0_pkey(EVP_MD_CTX_get_pkey_ctx(ctx));
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./openssl_missing.h:230:41: note: expanded from macro 'EVP_MD_CTX_get_pkey_ctx'
#  define EVP_MD_CTX_get_pkey_ctx(x) (x)->pctx
                                     ~~~^
/opt/homebrew/Cellar/openssl@3/3.2.0_1/include/openssl/types.h:107:16: note: forward declaration of 'struct evp_md_ctx_st'
typedef struct evp_md_ctx_st EVP_MD_CTX;
               ^
1 warning and 1 error generated.
```


Updated openssl and had same result

**Comment by Ajmal** [comment]
@scott8803 

`rvm install 3.3.0 --with-openssl-dir=$(brew --prefix openssl)`

if you need YJIT, install Rust (rustup) before you install `ruby 3.3.0`.

```
ruby -v --yjit
ruby 3.3.0 (2023-12-25 revision 5124f9ac75) +YJIT [arm64-darwin23]
```

**Comment by pcantrell** [comment]
Same problem here.

I wonder whether `--with-openssl-dir=$(brew --prefix openssl)` wouldn't be a sensible default behavior for rvm when brew is installed?

**Comment by stefanosalvucci** [comment]
rvm install 3.3.0 --with-openssl-dir=$(brew --prefix openssl)
worked for me

**Comment by monfresh** [comment]
There are many factors that can affect Ruby installation on a Mac. The solution depends on the exact state of your development setup. This is why a solution that works for one person might not work for someone else. 

If none of the solutions posted here have worked for you, here are other things you can try:

- Try a different Ruby version manager, such as chruby, asdf, or rbenv. I personally use and recommend chruby because it's faster and simpler.
- Completely uninstall all Ruby-related development tools, then start over from scratch. I wrote a [step-by-step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).
- If you value your time and want to be up and running in 15 minutes or less, buy my [Ruby on Mac](https://www.rubyonmac.dev/) product. With a single command, it takes care of everything for you. You don't ever have to worry about setting the correct OpenSSL version or any other settings. The Ultimate version works with all the popular version managers (asdf, chruby, frum, rbenv, rvm). The creator of RVM is a happy customer and he considers it a serious time saver: https://www.threads.net/@wayneeseguin/post/C2Nih1BOJS7

**Comment by sreenak** [comment]
@devsheva The above guide you shared on installing Ruby versions less than 3 really helped me. Thanks a lot for sharing it; it was very helpful. I was specifically looking for a guide on installing Ruby 2.5.3 on Mac Pro with an M3 chip. After searching and trying numerous results, I found the solution here.

**Comment by abhiviki** [comment]
For anyone still bumping in this, the above [comment](https://github.com/rvm/rvm/issues/5411#issuecomment-1852154150) worked.

I still couldn't get it working for ruby versions < 2.5.*. I can confirm the respective solutions worked individually for ruby versions > 3 and < 3.

**Comment by qzw881130** [comment]
I use chip M1

➜  homebrew git:(stable) brew list
==> Formulae
autoconf        coreutils       libgpg-error    libyaml         pkg-config
automake        gettext         libksba         m4              readline
ca-certificates gmp             libtool         openssl@1.1     zlib

➜  homebrew git:(stable) 
➜  homebrew git:(stable) 
➜  homebrew git:(stable) rvm install 3.1.4 --with-openssl-dir=$(brew --prefix openssl@1.1)
Checking requirements for osx.
Certificates bundle '/opt/homebrew/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/qianzhiwei/.rvm/rubies/ruby-3.1.4, this may take a while depending on your cpu(s)...
ruby-3.1.4 - #downloading ruby-3.1.4, this may take a while depending on your connection...
** Resuming transfer from byte position 258048
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.7M  100 19.7M    0     0  2889k      0  0:00:06  0:00:06 --:--:-- 4863k
No checksum for downloaded archive, recording checksum in user configuration.
ruby-3.1.4 - #extracting ruby-3.1.4 to /Users/qianzhiwei/.rvm/src/ruby-3.1.4 - please wait
ruby-3.1.4 - #configuring - please wait
ruby-3.1.4 - #post-configuration - please wait
ruby-3.1.4 - #compiling - please wait
ruby-3.1.4 - #installing - please wait
ruby-3.1.4 - #making binaries executable - please wait
Installed rubygems 3.3.26 is newer than 3.0.9 provided with installed ruby, skipping installation, use --force to force installation.
ruby-3.1.4 - #gemset created /Users/qianzhiwei/.rvm/gems/ruby-3.1.4@global
ruby-3.1.4 - #importing gemset /Users/qianzhiwei/.rvm/gemsets/global.gems - please wait
ruby-3.1.4 - #generating global wrappers - please wait
ruby-3.1.4 - #gemset created /Users/qianzhiwei/.rvm/gems/ruby-3.1.4
ruby-3.1.4 - #importing gemsetfile /Users/qianzhiwei/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-3.1.4 - #generating default wrappers - please wait
ruby-3.1.4 - #adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
Install of ruby-3.1.4 - #complete 
Ruby was built without documentation, to build it run: rvm docs generate-ri
➜  homebrew git:(stable) ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin23]

**Comment by npgretz** [comment]
I was able to install ruby 3.3.7 on Apple M2 Max with `rvm install 3.3.7 --with-openssl-dir=$(brew --prefix openssl@3.0)` after getting this error.

Thanks for the help everyone!
