### ISSUE TITLE
> > > > > > >

### ISSUE THREAD

**Issue by Masoudleyli** [rvm/rvm#5417]
> > > > > > > 
> > > > > > 
> > > > > > Masoudahg1
> > > > > > 
> > > > > > _Originally posted by @Masoudleyli in https://github.com/janoside/btc-rpc-explorer/issues/598#issuecomment-1851290058_
> > > > > 
> > > > > @Masoudleyli 
> > > > > 
> > > > > _Originally posted by @Masoudleyli in https://github.com/trustwallet/assets/issues/26965#issuecomment-1851291631_
> > > > 
> > > > 
> > > > 
> > > > _Originally posted by @Masoudleyli in https://github.com/janoside/btc-rpc-explorer/issues/599#issuecomment-1851292703_
> > > 
> > > 
> > > 
> > > _Originally posted by @Masoudleyli in https://github.com/TABASCOatw/wallet-adapter-ext/issues/2#issuecomment-1851293427_
> > 
> > 
> > 
> > _Originally posted by @Masoudleyli in https://github.com/golang/oauth2/issues/688#issuecomment-1851294478_
> 
> 
> 
> _Originally posted by @Masoudleyli in https://github.com/octocat/Hello-World/issues/2867#issuecomment-1851295361_

_Originally posted by @Masoudleyli in https://github.com/actions/setup-node/issues/915#issuecomment-1851296228_

**Comment by Masoudleyli** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > Masoudahg1
> > > > > > > 
> > > > > > > _Originally posted by @Masoudleyli in https://github.com/janoside/btc-rpc-explorer/issues/598#issuecomment-1851290058_
> > > > > > 
> > > > > > @Masoudleyli 
> > > > > > 
> > > > > > _Originally posted by @Masoudleyli in https://github.com/trustwallet/assets/issues/26965#issuecomment-1851291631_
> > > > > 
> > > > > 
> > > > > 
> > > > > _Originally posted by @Masoudleyli in https://github.com/janoside/btc-rpc-explorer/issues/599#issuecomment-1851292703_
> > > > 
> > > > 
> > > > 
> > > > _Originally posted by @Masoudleyli in https://github.com/TABASCOatw/wallet-adapter-ext/issues/2#issuecomment-1851293427_
> > > 
> > > 
> > > 
> > > _Originally posted by @Masoudleyli in https://github.com/golang/oauth2/issues/688#issuecomment-1851294478_
> > 
> > 
> > 
> > _Originally posted by @Masoudleyli in https://github.com/octocat/Hello-World/issues/2867#issuecomment-1851295361_
> 
> 
> 
> _Originally posted by @Masoudleyli in https://github.com/actions/setup-node/issues/915#issuecomment-1851296228_

**Comment by raelgc** [comment]
If you want to add details, feel free to re-open.

**Comment by mathieujobin** [comment]
this looks like Crypto spam ....

**Comment by raelgc** [comment]
I just blocked this user.
