### ISSUE TITLE
failed to install ruby Error running '__rvm_make -j4',

### ISSUE THREAD

**Issue by Tusenka** [rvm/rvm#5436]
## Steps to reproduce

 1. Run rvm install "3.0.2" 

## Expected behavior

Ruby is installed

## Actual behavior
Error running '__rvm_make -j4',
file:///usr/share/rvm/log/1706454093_ruby-3.0.2/make.log
![image](https://github.com/rvm/rvm/assets/7852737/d76e9449-f333-4d90-a04b-8fb3997db38e)

**Debug mode**:
[make.log](https://github.com/rvm/rvm/files/14076533/make.log)
## Environment info

` rvm info`

> `system:
> 
>   system:
>     uname:        "Linux cas12-GemiBook-Pro 6.5.0-15-generic #15~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Jan 12 18:54:30 UTC 2 x86_64 x86_64 x86_64 GNU/Linux"
>     name:         "Ubuntu"
>     version:      "22.04"
>     architecture: "x86_64"
>     bash:         "/usr/bin/bash => GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)"
>     zsh:          "/usr/bin/zsh => zsh 5.8.1 (x86_64-ubuntu-linux-gnu)"
>     remote_path:  "ubuntu/22.04/x86_64"
> 
>   rvm:
>     version:      "1.29.12 (manual)"
>     updated:      "51 minutes 1 second ago"
>     path:         "/usr/share/rvm"
>     autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."
> 
>   homes:
>     gem:          "not set"
>     ruby:         "not set"
> 
>   binaries:
>     ruby:         "/usr/bin/ruby"
>     irb:          "/usr/bin/irb"
>     gem:          "/usr/bin/gem"
>     rake:         "/usr/bin/rake"
> 
>   environment:
>     PATH:         "/home/cas12/istio-1.20.1/bin/:/root/go/src/k8s.io/kubernetes/third_party/etcd:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/bin:/usr/local/go/bin:/root/kubectl-plugins:/home/cas12/istio-1.20.1/bin:/root/.antigen/bundles/robbyrussell/oh-my-zsh/lib:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/command-not-found:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/docker-compose:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/fancy-ctrl-z:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git-extras:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gnu-utils:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/yarn:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/git:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/gh:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/terraform:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/aws:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/history:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/oc:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/npm:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/node:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/mvn:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/golang:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/kubectl:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/pip:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/systemd:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/python:/root/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/tmux:/root/.antigen/bundles/zsh-users/zsh-autosuggestions:/root/.antigen/bundles/popstas/zsh-command-time:/root/.antigen/bundles/urbainvaes/fzf-marks:/root/.antigen/bundles/ytet5uy4/fzf-widgets:/root/.antigen/bundles/zdharma-continuum/fast-syntax-highlighting:/usr/share/rvm/bin"
>     GEM_HOME:     ""
>     GEM_PATH:     ""
>     MY_RUBY_HOME: ""
>     IRBRC:        ""
>     RUBYOPT:      ""
>     gemset:       ""
> `

**Comment by chirag-codealchemy** [comment]
try **brew install ruby** 
(not permanent solution)

**Comment by omarkamal** [comment]
Facing the same issue here, on Ubuntu 22.04

**Comment by atenente** [comment]
in ubuntu it works for me

sudo apt install libssl-dev=1.1.1l-1ubuntu1.4  openssl=1.1.1l-1ubuntu1.4
