### ISSUE TITLE
Error running '__rvm_make -j12', in imac Sonoma 14.3.1 (23D60)

### ISSUE THREAD

**Issue by AkilaGametion** [rvm/rvm#5445]
## Description

try installing ruby using following command
 rvm install 2.7.0

[configure.log](https://github.com/rvm/rvm/files/14415527/configure.log)
[make.log](https://github.com/rvm/rvm/files/14415528/make.log)

## Environment info

system:

  system:
    uname:        "Darwin Itadmins-iMac.local 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:28:58 PST 2023; root:xnu-10002.81.5~7/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "14.3"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin23)"
    zsh:          "/bin/zsh => zsh 5.9 (x86_64-apple-darwin23.0)"
    remote_path:  "osx/14.3/x86_64"
    xcode:        "15.2"

  rvm:
    version:      "1.29.12-next (master)"
    updated:      "18 hours 32 minutes 28 seconds ago"
    path:         "/Users/akilak/.rvm"
    autolibs:     "[4] Allow RVM to use package manager if found, install missing dependencies, install package manager (only OS X)."

  homes:
    gem:          "not set"
    ruby:         "not set"

  binaries:
    ruby:         "/usr/bin/ruby"
    irb:          "/usr/bin/irb"
    gem:          "/usr/bin/gem"
    rake:         "/usr/bin/rake"

  environment:
    PATH:         "/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/akilak/.rvm/bin"
    GEM_HOME:     ""
    GEM_PATH:     ""
    MY_RUBY_HOME: ""
    IRBRC:        ""
    RUBYOPT:      ""
    gemset:       ""

**Comment by johnivanoff** [comment]
I had the same issue. while looking through the log I noticed **openssl@3** This is what I did to get around it but I'm not sure how safe it is.
I uninstalled openssl@3 (Which I used brew to install)
```shell
brew uninstall openssl@3
```
installed ruby via RVM
```shell
rvm install x.x.x
```
Then I reinstalled openssl@3
```shell
brew install openssl@3
```
🤷🏼
