### ISSUE TITLE
Could not update RVM, please report to https://github.com/rvm/rvm/issues

### ISSUE THREAD

**Issue by harshrathod8887** [rvm/rvm#5450]
## Steps to reproduce

 1. ...
 2. ...
 3. ...

## Actual behavior

* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Debug mode**:
* [command](https://gist.github.com/...)
* [config.log](https://gist.github.com/...) - only for issues with `install`
* [make.log](https://gist.github.com/...) - only for issues with `install`

**Comment by harshrathod8887** [comment]
how to update rvm

**Comment by torrocus** [comment]
https://rvm.io/rvm/upgrading#top
