### ISSUE TITLE
libncurses5-dev dependency broken on Ubuntu 24.04

### ISSUE THREAD

**Issue by denschub** [rvm/rvm#5475]
On Ubuntu 24.04, rvm wants to install `libncurses5-dev`. That package, however, [does not exist in the `noble` repos](https://packages.ubuntu.com/noble/libncurses5-dev), and you get redirected to [`libncurses-dev`, which installs version 6.4](https://packages.ubuntu.com/noble/libncurses-dev). The RVM requirement check does not accept that, though.

I monkey-patched `scripts/functions/requirements/debian` to use the version 6 package, and building Ruby 3.3.3 worked just fine.

**Comment by pkuczynski** [comment]
Maybe you could submit a PR for this?
