### ISSUE TITLE
Fedora 40+: `zlib` and `zlib-devel` packages no longer exist

### ISSUE THREAD

**Issue by denschub** [rvm/rvm#5478]
In Fedora 40+, `zlib` and `zlib-devel` no longer exist. Instead, the packages to install are now [`zlib-ng-compat`](https://packages.fedoraproject.org/pkgs/zlib-ng/zlib-ng-compat/) and [`zlib-ng-compat-devel`](https://packages.fedoraproject.org/pkgs/zlib-ng/zlib-ng-compat-devel/).

Ruby 3.3.3 compiles fine with those packages...

**Comment by pkuczynski** [comment]
@cocker-cc just run `rvm get master`

**Comment by cocker-cc** [comment]
so easy…   
Thanks, @pkuczynski
