### ISSUE TITLE
rubies.travis-ci.org cert expired on 6/23/2024

### ISSUE THREAD

**Issue by kyrofa** [rvm/rvm#5481]
This appears to prevent the downloading of pre-built rubies, forcing RVM to build from source instead. This is breaking my CI process, because it seems that rubies built from source are owned by `root:root` instead of `root:rvm` like the pre-built ones.

**Comment by kyrofa** [comment]
The weird permissions when building Ruby appears to be a known issue: #4940.

**Comment by mathieujobin** [comment]
interesting...

I did not know rvm binaries server had any relation with travis-ci ?!?

**Comment by kyrofa** [comment]
Yeah, for as long as I've used it.

**Comment by kyrofa** [comment]
This appears to be working again.
