### ISSUE TITLE
openssl@1.1 has been disabled because it is not supported upstream! It was disabled on 2024-10-24.

### ISSUE THREAD

**Issue by Xezun** [rvm/rvm#5524]
`rvm install 3.3.6       `                      
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/15.1/x86_64/ruby-3.3.6.tar.bz2
Checking requirements for osx.
Installing requirements for osx.
Updating system - please wait
Installing required packages: pkg-config, openssl@1.1 - please wait
There were package installation errors, make sure to read the log.

Try `brew tap --repair` and make sure `brew doctor` looks reasonable.

Check Homebrew requirements https://docs.brew.sh/Installation
Error running 'requirements_osx_brew_libs_install pkg-config openssl@1.1',
please read /Users/xezun/.rvm/log/1731700071_ruby-3.3.6/package_install_pkg-config_openssl@1.1.log
Requirements installation failed with status: 1.

**Comment by vicomte** [comment]
please try `rvm get master` and repeat.

**Comment by DeviPothula** [comment]
> please try `rvm get master` and repeat.

Great It is working fine!!

**Comment by Mynziak** [comment]
I'm trying to `rvm install 2.7.6`,
getting the same error mentioned in issue and `rvm get master`doesn't not help, same issue

**Comment by HafeezRai** [comment]
i am facing same on 2.6.6

**Comment by grandstairs** [comment]
Why did the rvm recommended `rvm get stable` fail to resolve this?

**Comment by pmikutel** [comment]
Thanks @vicomte `rvm get master` helped after many hours trying to fix damn thing

**Comment by vishalnagv** [comment]
Thanks mate

**Comment by vishalnagv** [comment]
> please try `rvm get master` and repeat.

Thanks mate, Cheers

**Comment by pawan-everbee** [comment]
> please try `rvm get master` and repeat.

thanks it worked

**Comment by huntingcat** [comment]
Great, it works!

**Comment by wzd-commits** [comment]
Great, it works!
