### ISSUE TITLE
Compiling with 32bit flags leads to 64bit ruby

### ISSUE THREAD

**Issue by apeiros** [rvm/rvm#623]
Hi

I'm using Kenneth Reitz' GCC installer (https://github.com/kennethreitz/osx-gcc-installer), the newest rvm (1.10.0-pre) and OS X Lion 10.7.2.
I tried to install ruby 1.9.2p290 as 32bit executable, following http://beginrescueend.com/support/troubleshooting/ (section "i386 (32 bit)").
However, the compiled executable is 64bit.

Additional information:

```
$ uname -mprsv
Darwin 11.2.0 Darwin Kernel Version 11.2.0: Tue Aug  9 20:54:00 PDT 2011; root:xnu-1699.24.8~1/RELEASE_X86_64 x86_64 i386

$ rvm_archflags="-arch i386" CFLAGS='-m32' CXXFLAGS='-m32' LDFLAGS='-m32' rvm install ruby-1.9.2
# …snip…
Install of ruby-1.9.2-p290 - #complete 
$ rvm use 1.9.2
$ which ruby
/Users/apeiros/.rvm/rubies/ruby-1.9.2-p290/bin/ruby
$ file /Users/apeiros/.rvm/rubies/ruby-1.9.2-p290/bin/ruby
/Users/apeiros/.rvm/rubies/ruby-1.9.2-p290/bin/ruby: Mach-O 64-bit executable x86_64
$ cat ~/.rvm/src/ruby-1.9.2-p290/Makefile | grep '^arch ='
arch = x86_64-darwin11.2.0
```

If I can supply any other information, please let me know.

**Comment by eevee** [comment]
Almost four years later, I wasted half a day chasing down a similar problem, because the flags are still not documented.  I finally found them reading the source code.

**Comment by v6** [comment]
// , Interesting that rubygems seems to use the system architecture for building native extensions. 

@eevee, how did you find this bug?

**Comment by eevee** [comment]
I have a 64-bit Linode running a 32-bit kernel.

It was originally all 32-bit, then they gave me a free upgrade to a 64-bit host, and I didn't see any good reason to redo a lot of ad-hoc stuff just to fix the mismatch.
