### ISSUE TITLE
online documentation update

### ISSUE THREAD

**Issue by petervandenabeele** [rvm/rvm#705]
I did not find how to submit a patch for the online documentation,
so, suggesting it here.

On page:

  http://beginrescueend.com/support/troubleshooting/

Please add a section:
`
  <h2>Multi-User Installs - Ubuntu - the program 'rvm' is currently not installed</h2>
  <p>After a multi-user install, and using a local terminal in the GUI, rvm seems to be not installed.</p>
  <pre class='code'>The program 'rvm' is currently not installed. ...</pre>
  <p>This is caused by the
  <a href="/integration/gnome-terminal/">Gnome terminal by default not using the login shell</a></p>       
`

**Comment by jpventura** [comment]
@mpapis At [_Integrating RVM with gnome-terminal_](https://rvm.io/integration/gnome-terminal), it is mentioned that:

_"By default, gnome-terminal runs Bash as usual, as a non-login shell, therefore skipping `/etc/profile*` and executing only the user's `~/.bashrc`"_. 

however create a configuration at `/etc/profile.d/rbenv.sh` should be enough. Both `/etc/profile` and `/etc/profile.d/*.sh` [are executed **once** when the user login into the distro](https://superuser.com/questions/789448/choosing-between-bashrc-profile-bash-profile-etc). Thus it would be required to logout/login in order the [`rbenv.sh`](https://gist.github.com/jpventura/0110747c5d321d0afacdbd217adda011) to take effect or simply run

```bash
source /etc/profile.d/rbenv.sh
```

At [AskUbuntu](https://askubuntu.com/questions/594656/how-to-install-the-latest-versions-of-nodejs-and-npm/711976) there is an analogous example of how I install Node.js at `/opt/node` and make it available to all users through `/etc/profile.d/node.js`.
