### ISSUE TITLE
command not found: __rvm_cleanse_variables (again?)

### ISSUE THREAD

**Issue by mysteriouspants** [rvm/rvm#770]
I see #662 is closed, but I'm getting the same problem with MRI 1.9.3-p125:

```
/Users/cmiller/.rvm/scripts/initialize:40: __rvm_cleanse_variables: function definition file not found
```

I'm using ZSH (`zsh 4.3.11 (i386-apple-darwin11.0)`) on OS 10.7.3 with oh-my-zsh. I tried reverting back to stable, upgrading to head, and reinstalling RVM (by moving the old .rvm to .rvm-backup and then installing again), but it still gives me this error. I'm also experiencing issues where Rails is loosing its head and refusing to run the server (the `rails s` command tells me "no Ruby script found in input (LoadError)"). RVM version says it's at 1.10.2.

```
> rvm -v

rvm 1.10.2 by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.beginrescueend.com/]
```

I'm a little interested in why it's doing this. I think it's plenty possible that I did something wrong. Sorry if this is a duplicate!

**Comment by dwcaraway** [comment]
the ```rm -f ~/.zcompdump*``` command to clear zcompdump worked for me as well, thanks @tam-vo

**Comment by johnwatsondev** [comment]
@tam-vo  Thanks for share.

**Comment by casatwy** [comment]
rm -f ~/.zcompdump* does not work for me.

I checked the ~/.zlogin and modfied the rvm script path to below:

`[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*`

and it works.

I think you should check wether there is rvm in `~/.rvm/scripts`

**Comment by wesson-yi** [comment]
@Jeweller-Tsai， you are very clever。I don't know why, but I can avoid him.(￣.￣)
