### ISSUE TITLE
RVM Install and Dotfiles

### ISSUE THREAD

**Issue by kmowery** [rvm/rvm#774]
After installing RVM earlier today using the rvm-install script, I found that my bash environment had mysteriously gone missing. The culprit?

rvm-install created .bash_login and modified .bashrc, while my shell configuration lives in .profile (and .bashrc is a pointer to .profile). Upon creating a new shell, .bash_login shadows .profile and my configuration silently disappears.

rvm-install should, instead, check for the existence of .profile, .bash_login, and .bash_profile and, if one is found, modify the one with highest bash priority. Only if none exist should rvm-install create a new file.

Lastly (and this is a philosophical issue and not part of the bug), rvm-install should _not touch my dotfiles under any circumstances_. Let the user do that. You don't know what you might be breaking or how the environment is configured. At the very least,  add a switch to rvm-install that turns off dotfile modification and provide appropriate documentation for the user to configure their shell environment hemselves.

**Comment by NightMachinary** [comment]
It would be a good idea to mention the option `--ignore-dotfiles` in the getting started guide. In general, just asking the user is better. Scripted usage will specify a flag to either enablle or disable the behavior, but just running `curl -sSL https://get.rvm.io | bash -s stable --rails` should simply ask the user if they want their dotfiles updated.
