### ISSUE TITLE
Infinite loop when run from cron job with not-yet-trusted rvmrc?

### ISSUE THREAD

**Issue by simonrussell** [rvm/rvm#791]
Running RVM 1.10.2 on Ubuntu 10.04.4.

I've got a cron job setup which doesn't mention RVM; there is an .rvmrc in the project.  When cron runs, the system ends up falling over because pretty much an infinite number of my cron job gets spawned.  This only seems to happen if the .rvmrc hasn't ever been trusted -- if you trust then reset the trust, the problem doesn't occur.  It's only if it's never been trusted.

Not sure what's causing the infinite respawn -- cron, or rvm -- but it's quite alarming.  Any ideas?  It may well not be RVM, but I'm not really sure where to start looking, and I'd be unhappy if this caused pain for anyone else.

(yes, I know I should have trusted the rvmrc -- I forgot; I don't think this should be the outcome however.)

**Comment by hangmiao** [comment]
Super late for the party but thought I'd share b/c it took us quite a while to get this resolved.
In our case, it's the extra BASH_ENV souring specified in cron_tab that causes the issue:

```
# In cron file
SHELL=/bin/bash
BASH_ENV=~/.bashrc <------------------- this causes endless spawning
...
```

Taking that out works. Hope that helps.
